class AnkletExecutor {
    public static void main(String[] args) {
       
        Anklet a1 = new Anklet();
		a1.ankletId = 1;
        Anklet a2 = new Anklet(); 
		a2.ankletId = 2;
        Anklet a3 = new Anklet(); 
		a3.ankletId = 3;
        Anklet a4 = new Anklet();
		a4.ankletId = 4;
        Anklet a5 = new Anklet(); 
		a5.ankletId = 5;
        Anklet a6 = new Anklet();
		a6.ankletId = 6;
        Anklet a7 = new Anklet(); 
		a7.ankletId = 7;
        Anklet a8 = new Anklet();
		a8.ankletId = 8;
        Anklet a9 = new Anklet();
		a9.ankletId = 9;
        Anklet a10 = new Anklet();
		a10.ankletId = 10;
        Anklet a11 = new Anklet();
		a11.ankletId = 11;
        Anklet a12 = new Anklet();
		a12.ankletId = 12;
        Anklet a13 = new Anklet(); 
		a13.ankletId = 13;
        Anklet a14 = new Anklet();
		a14.ankletId = 14;
        Anklet a15 = new Anklet();
		a15.ankletId = 15;
        Anklet a16 = new Anklet(); 
		a16.ankletId = 16;
        Anklet a17 = new Anklet(); 
		a17.ankletId = 17;
        Anklet a18 = new Anklet(); 
		a18.ankletId = 18;
        Anklet a19 = new Anklet(); 
		a19.ankletId = 19;
        Anklet a20 = new Anklet();
		a20.ankletId = 20;
        Anklet a21 = new Anklet(); 
		a21.ankletId = 21;
        Anklet a22 = new Anklet(); 
		a22.ankletId = 22;
        Anklet a23 = new Anklet();
		a23.ankletId = 23;
        Anklet a24 = new Anklet();
		a24.ankletId = 24;
        Anklet a25 = new Anklet(); 
		a25.ankletId = 25;
      
        System.out.println("Anklet a1 ID: " + a1.ankletId);
        System.out.println("Anklet a2 ID: " + a2.ankletId);
        System.out.println("Anklet a3 ID: " + a3.ankletId);
        System.out.println("Anklet a4 ID: " + a4.ankletId);
        System.out.println("Anklet a5 ID: " + a5.ankletId);
        System.out.println("Anklet a6 ID: " + a6.ankletId);
        System.out.println("Anklet a7 ID: " + a7.ankletId);
        System.out.println("Anklet a8 ID: " + a8.ankletId);
        System.out.println("Anklet a9 ID: " + a9.ankletId);
        System.out.println("Anklet a10 ID: " + a10.ankletId);
        System.out.println("Anklet a11 ID: " + a11.ankletId);
        System.out.println("Anklet a12 ID: " + a12.ankletId);
        System.out.println("Anklet a13 ID: " + a13.ankletId);
        System.out.println("Anklet a14 ID: " + a14.ankletId);
        System.out.println("Anklet a15 ID: " + a15.ankletId);
        System.out.println("Anklet a16 ID: " + a16.ankletId);
        System.out.println("Anklet a17 ID: " + a17.ankletId);
        System.out.println("Anklet a18 ID: " + a18.ankletId);
        System.out.println("Anklet a19 ID: " + a19.ankletId);
        System.out.println("Anklet a20 ID: " + a20.ankletId);
        System.out.println("Anklet a21 ID: " + a21.ankletId);
        System.out.println("Anklet a22 ID: " + a22.ankletId);
        System.out.println("Anklet a23 ID: " + a23.ankletId);
        System.out.println("Anklet a24 ID: " + a24.ankletId);
        System.out.println("Anklet a25 ID: " + a25.ankletId);
        System.out.println("----------------------------------------------------------");
     	  
        Anklet p1 = new Anklet(1);// parmeterized instance
        Anklet p2 = new Anklet(2);
        Anklet p3 = new Anklet(3);
        Anklet p4 = new Anklet(4);
        Anklet p5 = new Anklet(5);
        Anklet p6 = new Anklet(6);
        Anklet p7 = new Anklet(7);
        Anklet p8 = new Anklet(8);
        Anklet p9 = new Anklet(9);
        Anklet p10 = new Anklet(10);
        Anklet p11 = new Anklet(11);
        Anklet p12 = new Anklet(12);
        Anklet p13 = new Anklet(13);
        Anklet p14 = new Anklet(14);
        Anklet p15 = new Anklet(15);
        Anklet p16 = new Anklet(16);
        Anklet p17 = new Anklet(17);
        Anklet p18 = new Anklet(18);
        Anklet p19 = new Anklet(19);
        Anklet p20 = new Anklet(20);
        Anklet p21 = new Anklet(21);
        Anklet p22 = new Anklet(22);
        Anklet p23 = new Anklet(23);
        Anklet p24 = new Anklet(24);
        Anklet p25 = new Anklet(25);
        
    	System.out.println("Anklet p1 ID: " + p1.ankletId);
        System.out.println("Anklet p2 ID: " + p2.ankletId);
        System.out.println("Anklet p3 ID: " + p3.ankletId);
        System.out.println("Anklet p4 ID: " + p4.ankletId);
        System.out.println("Anklet p5 ID: " + p5.ankletId);
        System.out.println("Anklet p6 ID: " + p6.ankletId);
        System.out.println("Anklet p7 ID: " + p7.ankletId);
        System.out.println("Anklet p8 ID: " + p8.ankletId);
        System.out.println("Anklet p9 ID: " + p9.ankletId);
        System.out.println("Anklet p10 ID: " + p10.ankletId);
        System.out.println("Anklet p11 ID: " + p11.ankletId);
        System.out.println("Anklet p12 ID: " + p12.ankletId);
        System.out.println("Anklet p13 ID: " + p13.ankletId);
        System.out.println("Anklet p14 ID: " + p14.ankletId);
        System.out.println("Anklet p15 ID: " + p15.ankletId);
        System.out.println("Anklet p16 ID: " + p16.ankletId);
        System.out.println("Anklet p17 ID: " + p17.ankletId);
        System.out.println("Anklet p18 ID: " + p18.ankletId);
        System.out.println("Anklet p19 ID: " + p19.ankletId);
        System.out.println("Anklet p20 ID: " + p20.ankletId);
        System.out.println("Anklet p21 ID: " + p21.ankletId);
        System.out.println("Anklet p22 ID: " + p22.ankletId);
        System.out.println("Anklet p23 ID: " + p23.ankletId);
        System.out.println("Anklet p24 ID: " + p24.ankletId);
        System.out.println("Anklet p25 ID: " + p25.ankletId);
        System.out.println("----------------------------------------------------------");
    }
}
