class AntExecutor {
    public static void main(String[] args) {
       Ant a1 = new Ant(); a1.antId = 1; a1.antType = "Worker"; a1.colonyName = "Alpha";
        Ant a2 = new Ant(); a2.antId = 2; a2.antType = "Soldier"; a2.colonyName = "Beta";
        Ant a3 = new Ant(); a3.antId = 3; a3.antType = "Queen"; a3.colonyName = "Gamma";
        Ant a4 = new Ant(); a4.antId = 4; a4.antType = "Worker"; a4.colonyName = "Delta";
        Ant a5 = new Ant(); a5.antId = 5; a5.antType = "Scout"; a5.colonyName = "Epsilon";
        Ant a6 = new Ant(); a6.antId = 6; a6.antType = "Soldier"; a6.colonyName = "Zeta";
        Ant a7 = new Ant(); a7.antId = 7; a7.antType = "Forager"; a7.colonyName = "Eta";
        Ant a8 = new Ant(); a8.antId = 8; a8.antType = "Worker"; a8.colonyName = "Theta";
        Ant a9 = new Ant(); a9.antId = 9; a9.antType = "Nurse"; a9.colonyName = "Iota";
        Ant a10 = new Ant(); a10.antId = 10; a10.antType = "Queen"; a10.colonyName = "Kappa";
        Ant a11 = new Ant(); a11.antId = 11; a11.antType = "Scout"; a11.colonyName = "Lambda";
        Ant a12 = new Ant(); a12.antId = 12; a12.antType = "Soldier"; a12.colonyName = "Mu";
        Ant a13 = new Ant(); a13.antId = 13; a13.antType = "Worker"; a13.colonyName = "Nu";
        Ant a14 = new Ant(); a14.antId = 14; a14.antType = "Forager"; a14.colonyName = "Xi";
        Ant a15 = new Ant(); a15.antId = 15; a15.antType = "Nurse"; a15.colonyName = "Omicron";
        Ant a16 = new Ant(); a16.antId = 16; a16.antType = "Worker"; a16.colonyName = "Pi";
        Ant a17 = new Ant(); a17.antId = 17; a17.antType = "Soldier"; a17.colonyName = "Rho";
        Ant a18 = new Ant(); a18.antId = 18; a18.antType = "Scout"; a18.colonyName = "Sigma";
        Ant a19 = new Ant(); a19.antId = 19; a19.antType = "Queen"; a19.colonyName = "Tau";
        Ant a20 = new Ant(); a20.antId = 20; a20.antType = "Forager"; a20.colonyName = "Upsilon";
        Ant a21 = new Ant(); a21.antId = 21; a21.antType = "Worker"; a21.colonyName = "Phi";
        Ant a22 = new Ant(); a22.antId = 22; a22.antType = "Nurse"; a22.colonyName = "Chi";
        Ant a23 = new Ant(); a23.antId = 23; a23.antType = "Soldier"; a23.colonyName = "Psi";
        Ant a24 = new Ant(); a24.antId = 24; a24.antType = "Scout"; a24.colonyName = "Omega";
        Ant a25 = new Ant(); a25.antId = 25; a25.antType = "Worker"; a25.colonyName = "Alpha2";
        
        System.out.println("Ant a1 ID: " + a1.antId + " Type: " + a1.antType + " Colony: " + a1.colonyName);
        System.out.println("Ant a2 ID: " + a2.antId + " Type: " + a2.antType + " Colony: " + a2.colonyName);
        System.out.println("Ant a3 ID: " + a3.antId + " Type: " + a3.antType + " Colony: " + a3.colonyName);
        System.out.println("Ant a4 ID: " + a4.antId + " Type: " + a4.antType + " Colony: " + a4.colonyName);
        System.out.println("Ant a5 ID: " + a5.antId + " Type: " + a5.antType + " Colony: " + a5.colonyName);
        System.out.println("Ant a6 ID: " + a6.antId + " Type: " + a6.antType + " Colony: " + a6.colonyName);
        System.out.println("Ant a7 ID: " + a7.antId + " Type: " + a7.antType + " Colony: " + a7.colonyName);
        System.out.println("Ant a8 ID: " + a8.antId + " Type: " + a8.antType + " Colony: " + a8.colonyName);
        System.out.println("Ant a9 ID: " + a9.antId + " Type: " + a9.antType + " Colony: " + a9.colonyName);
        System.out.println("Ant a10 ID: " + a10.antId + " Type: " + a10.antType + " Colony: " + a10.colonyName);
        System.out.println("Ant a11 ID: " + a11.antId + " Type: " + a11.antType + " Colony: " + a11.colonyName);
        System.out.println("Ant a12 ID: " + a12.antId + " Type: " + a12.antType + " Colony: " + a12.colonyName);
        System.out.println("Ant a13 ID: " + a13.antId + " Type: " + a13.antType + " Colony: " + a13.colonyName);
        System.out.println("Ant a14 ID: " + a14.antId + " Type: " + a14.antType + " Colony: " + a14.colonyName);
        System.out.println("Ant a15 ID: " + a15.antId + " Type: " + a15.antType + " Colony: " + a15.colonyName);
        System.out.println("Ant a16 ID: " + a16.antId + " Type: " + a16.antType + " Colony: " + a16.colonyName);
        System.out.println("Ant a17 ID: " + a17.antId + " Type: " + a17.antType + " Colony: " + a17.colonyName);
        System.out.println("Ant a18 ID: " + a18.antId + " Type: " + a18.antType + " Colony: " + a18.colonyName);
        System.out.println("Ant a19 ID: " + a19.antId + " Type: " + a19.antType + " Colony: " + a19.colonyName);
        System.out.println("Ant a20 ID: " + a20.antId + " Type: " + a20.antType + " Colony: " + a20.colonyName);
        System.out.println("Ant a21 ID: " + a21.antId + " Type: " + a21.antType + " Colony: " + a21.colonyName);
        System.out.println("Ant a22 ID: " + a22.antId + " Type: " + a22.antType + " Colony: " + a22.colonyName);
        System.out.println("Ant a23 ID: " + a23.antId + " Type: " + a23.antType + " Colony: " + a23.colonyName);
        System.out.println("Ant a24 ID: " + a24.antId + " Type: " + a24.antType + " Colony: " + a24.colonyName);
        System.out.println("Ant a25 ID: " + a25.antId + " Type: " + a25.antType + " Colony: " + a25.colonyName);
        System.out.println("----------------------------------------------------------");
       

        Ant p1 = new Ant(1, "Worker", "Alpha");
        Ant p2 = new Ant(2, "Soldier", "Beta");
        Ant p3 = new Ant(3, "Queen", "Gamma");
        Ant p4 = new Ant(4, "Worker", "Delta");
        Ant p5 = new Ant(5, "Scout", "Epsilon");
        Ant p6 = new Ant(6, "Soldier", "Zeta");
        Ant p7 = new Ant(7, "Forager", "Eta");
        Ant p8 = new Ant(8, "Worker", "Theta");
        Ant p9 = new Ant(9, "Nurse", "Iota");
        Ant p10 = new Ant(10, "Queen", "Kappa");
        Ant p11 = new Ant(11, "Scout", "Lambda");
        Ant p12 = new Ant(12, "Soldier", "Mu");
        Ant p13 = new Ant(13, "Worker", "Nu");
        Ant p14 = new Ant(14, "Forager", "Xi");
        Ant p15 = new Ant(15, "Nurse", "Omicron");
        Ant p16 = new Ant(16, "Worker", "Pi");
        Ant p17 = new Ant(17, "Soldier", "Rho");
        Ant p18 = new Ant(18, "Scout", "Sigma");
        Ant p19 = new Ant(19, "Queen", "Tau");
        Ant p20 = new Ant(20, "Forager", "Upsilon");
        Ant p21 = new Ant(21, "Worker", "Phi");
        Ant p22 = new Ant(22, "Nurse", "Chi");
        Ant p23 = new Ant(23, "Soldier", "Psi");
        Ant p24 = new Ant(24, "Scout", "Omega");
        Ant p25 = new Ant(25, "Worker", "Alpha2");
         
        System.out.println("Ant p1 ID: " + p1.antId + " Type: " + p1.antType + " Colony: " + p1.colonyName);
        System.out.println("Ant p2 ID: " + p2.antId + " Type: " + p2.antType + " Colony: " + p2.colonyName);
        System.out.println("Ant p3 ID: " + p3.antId + " Type: " + p3.antType + " Colony: " + p3.colonyName);
        System.out.println("Ant p4 ID: " + p4.antId + " Type: " + p4.antType + " Colony: " + p4.colonyName);
        System.out.println("Ant p5 ID: " + p5.antId + " Type: " + p5.antType + " Colony: " + p5.colonyName);
        System.out.println("Ant p6 ID: " + p6.antId + " Type: " + p6.antType + " Colony: " + p6.colonyName);
        System.out.println("Ant p7 ID: " + p7.antId + " Type: " + p7.antType + " Colony: " + p7.colonyName);
        System.out.println("Ant p8 ID: " + p8.antId + " Type: " + p8.antType + " Colony: " + p8.colonyName);
        System.out.println("Ant p9 ID: " + p9.antId + " Type: " + p9.antType + " Colony: " + p9.colonyName);
        System.out.println("Ant p10 ID: " + p10.antId + " Type: " + p10.antType + " Colony: " + p10.colonyName);
        System.out.println("Ant p11 ID: " + p11.antId + " Type: " + p11.antType + " Colony: " + p11.colonyName);
        System.out.println("Ant p12 ID: " + p12.antId + " Type: " + p12.antType + " Colony: " + p12.colonyName);
        System.out.println("Ant p13 ID: " + p13.antId + " Type: " + p13.antType + " Colony: " + p13.colonyName);
        System.out.println("Ant p14 ID: " + p14.antId + " Type: " + p14.antType + " Colony: " + p14.colonyName);
        System.out.println("Ant p15 ID: " + p15.antId + " Type: " + p15.antType + " Colony: " + p15.colonyName);
        System.out.println("Ant p16 ID: " + p16.antId + " Type: " + p16.antType + " Colony: " + p16.colonyName);
        System.out.println("Ant p17 ID: " + p17.antId + " Type: " + p17.antType + " Colony: " + p17.colonyName);
        System.out.println("Ant p18 ID: " + p18.antId + " Type: " + p18.antType + " Colony: " + p18.colonyName);
        System.out.println("Ant p19 ID: " + p19.antId + " Type: " + p19.antType + " Colony: " + p19.colonyName);
        System.out.println("Ant p20 ID: " + p20.antId + " Type: " + p20.antType + " Colony: " + p20.colonyName);
        System.out.println("Ant p21 ID: " + p21.antId + " Type: " + p21.antType + " Colony: " + p21.colonyName);
        System.out.println("Ant p22 ID: " + p22.antId + " Type: " + p22.antType + " Colony: " + p22.colonyName);
        System.out.println("Ant p23 ID: " + p23.antId + " Type: " + p23.antType + " Colony: " + p23.colonyName);
        System.out.println("Ant p24 ID: " + p24.antId + " Type: " + p24.antType + " Colony: " + p24.colonyName);
        System.out.println("Ant p25 ID: " + p25.antId + " Type: " + p25.antType + " Colony: " + p25.colonyName);
        System.out.println("----------------------------------------------------------");
    }
}

