class BangleExecutor {
    public static void main(String[] args) {
        Bangle b1 = new Bangle();// default constructor instances b1
		b1.bangleId = 101;
        Bangle b2 = new Bangle(); 
		b2.bangleId = 102;
        Bangle b3 = new Bangle(); 
		b3.bangleId = 103;
        Bangle b4 = new Bangle();
		b4.bangleId = 104;
        Bangle b5 = new Bangle();
		b5.bangleId = 105;
        Bangle b6 = new Bangle();
		b6.bangleId = 106;
        Bangle b7 = new Bangle(); 
		b7.bangleId = 107;
        Bangle b8 = new Bangle();
		b8.bangleId = 108;
        Bangle b9 = new Bangle();
		b9.bangleId = 109;
        Bangle b10 = new Bangle(); 
		b10.bangleId = 110;
        Bangle b11 = new Bangle();
		b11.bangleId = 111;
        Bangle b12 = new Bangle(); 
		b12.bangleId = 112;
        Bangle b13 = new Bangle();
		b13.bangleId = 113;
        Bangle b14 = new Bangle();
		b14.bangleId = 114;
        Bangle b15 = new Bangle();
		b15.bangleId = 115;
        Bangle b16 = new Bangle(); 
		b16.bangleId = 116;
        Bangle b17 = new Bangle();
		b17.bangleId = 117;
        Bangle b18 = new Bangle(); 
		b18.bangleId = 118;
        Bangle b19 = new Bangle(); 
		b19.bangleId = 119;
        Bangle b20 = new Bangle();
		b20.bangleId = 120;
        Bangle b21 = new Bangle(); 
		b21.bangleId = 121;
        Bangle b22 = new Bangle();
		b22.bangleId = 122;
        Bangle b23 = new Bangle();
		b23.bangleId = 123;
        Bangle b24 = new Bangle(); 
		b24.bangleId = 124;
        Bangle b25 = new Bangle();
		b25.bangleId = 125;
		   
        System.out.println("Bangle b1 ID: " + b1.bangleId);
        System.out.println("Bangle b2 ID: " + b2.bangleId);
        System.out.println("Bangle b3 ID: " + b3.bangleId);
        System.out.println("Bangle b4 ID: " + b4.bangleId);
        System.out.println("Bangle b5 ID: " + b5.bangleId);
        System.out.println("Bangle b6 ID: " + b6.bangleId);
        System.out.println("Bangle b7 ID: " + b7.bangleId);
        System.out.println("Bangle b8 ID: " + b8.bangleId);
        System.out.println("Bangle b9 ID: " + b9.bangleId);
        System.out.println("Bangle b10 ID: " + b10.bangleId);
        System.out.println("Bangle b11 ID: " + b11.bangleId);
        System.out.println("Bangle b12 ID: " + b12.bangleId);
        System.out.println("Bangle b13 ID: " + b13.bangleId);
        System.out.println("Bangle b14 ID: " + b14.bangleId);
        System.out.println("Bangle b15 ID: " + b15.bangleId);
        System.out.println("Bangle b16 ID: " + b16.bangleId);
        System.out.println("Bangle b17 ID: " + b17.bangleId);
        System.out.println("Bangle b18 ID: " + b18.bangleId);
        System.out.println("Bangle b19 ID: " + b19.bangleId);
        System.out.println("Bangle b20 ID: " + b20.bangleId);
        System.out.println("Bangle b21 ID: " + b21.bangleId);
        System.out.println("Bangle b22 ID: " + b22.bangleId);
        System.out.println("Bangle b23 ID: " + b23.bangleId);
        System.out.println("Bangle b24 ID: " + b24.bangleId);
        System.out.println("Bangle b25 ID: " + b25.bangleId);
        System.out.println("----------------------------------------------------------");
        
        Bangle p1 = new Bangle(1);// parameterized instance p1
        Bangle p2 = new Bangle(2);
        Bangle p3 = new Bangle(3);
        Bangle p4 = new Bangle(4);
        Bangle p5 = new Bangle(5);
        Bangle p6 = new Bangle(6);
        Bangle p7 = new Bangle(7);
        Bangle p8 = new Bangle(8);
        Bangle p9 = new Bangle(9);
        Bangle p10 = new Bangle(10);
        Bangle p11 = new Bangle(11);
        Bangle p12 = new Bangle(12);
        Bangle p13 = new Bangle(13);
        Bangle p14 = new Bangle(14);
        Bangle p15 = new Bangle(15);
        Bangle p16 = new Bangle(16);
        Bangle p17 = new Bangle(17);
        Bangle p18 = new Bangle(18);
        Bangle p19 = new Bangle(19);
        Bangle p20 = new Bangle(20);
        Bangle p21 = new Bangle(21);
        Bangle p22 = new Bangle(22);
        Bangle p23 = new Bangle(23);
        Bangle p24 = new Bangle(24);
        Bangle p25 = new Bangle(25);
      
        System.out.println("Bangle p1 ID: " + p1.bangleId);
        System.out.println("Bangle p2 ID: " + p2.bangleId);
        System.out.println("Bangle p3 ID: " + p3.bangleId);
        System.out.println("Bangle p4 ID: " + p4.bangleId);
        System.out.println("Bangle p5 ID: " + p5.bangleId);
        System.out.println("Bangle p6 ID: " + p6.bangleId);
        System.out.println("Bangle p7 ID: " + p7.bangleId);
        System.out.println("Bangle p8 ID: " + p8.bangleId);
        System.out.println("Bangle p9 ID: " + p9.bangleId);
        System.out.println("Bangle p10 ID: " + p10.bangleId);
        System.out.println("Bangle p11 ID: " + p11.bangleId);
        System.out.println("Bangle p12 ID: " + p12.bangleId);
        System.out.println("Bangle p13 ID: " + p13.bangleId);
        System.out.println("Bangle p14 ID: " + p14.bangleId);
        System.out.println("Bangle p15 ID: " + p15.bangleId);
        System.out.println("Bangle p16 ID: " + p16.bangleId);
        System.out.println("Bangle p17 ID: " + p17.bangleId);
        System.out.println("Bangle p18 ID: " + p18.bangleId);
        System.out.println("Bangle p19 ID: " + p19.bangleId);
        System.out.println("Bangle p20 ID: " + p20.bangleId);
        System.out.println("Bangle p21 ID: " + p21.bangleId);
        System.out.println("Bangle p22 ID: " + p22.bangleId);
        System.out.println("Bangle p23 ID: " + p23.bangleId);
        System.out.println("Bangle p24 ID: " + p24.bangleId);
        System.out.println("Bangle p25 ID: " + p25.bangleId);
        System.out.println("----------------------------------------------------------");
    }
}
