class BankDetailsExecutor {
    public static void main(String[] args) {
        
        BankDetails bank1 = new BankDetails();
        bank1.setAccountId(5001); 
        bank1.setAccountHolder("Srushti G M");
        bank1.setAccountNumber("123456789012");
        bank1.setBankName("State Bank of India");
        bank1.setBranchName("Bengaluru MG Road");
        bank1.setBalance(25000.00); 
        bank1.setAccountType("Savings");
        bank1.setIfscCode("SBIN0001234");
        bank1.setCreatedOn("2026-01-15"); 
        bank1.setStatus("Active");

        System.out.println("Account id is " + bank1.getAccountId());
        System.out.println("Account holder is " + bank1.getAccountHolder());
        System.out.println("Account number is " + bank1.getAccountNumber());
        System.out.println("Bank name is " + bank1.getBankName());
        System.out.println("Branch name is " + bank1.getBranchName());
        System.out.println("Balance is " + bank1.getBalance());
        System.out.println("Account type is " + bank1.getAccountType());
        System.out.println("IFSC code is " + bank1.getIfscCode());
        System.out.println("Created on " + bank1.getCreatedOn());
        System.out.println("Status is " + bank1.getStatus());
        System.out.println();
		
		
		BankDetails bank2 = new BankDetails();
        bank2.setAccountId(5002); 
        bank2.setAccountHolder("Rahul Sharma");
        bank2.setAccountNumber("987654321098");
        bank2.setBankName("HDFC Bank");
        bank2.setBranchName("Bengaluru Koramangala");
        bank2.setBalance(45000.00); 
        bank2.setAccountType("Current");
        bank2.setIfscCode("HDFC0001235");
        bank2.setCreatedOn("2026-01-20"); 
        bank2.setStatus("Active");

        System.out.println("Account id is " + bank2.getAccountId());
        System.out.println("Account holder is " + bank2.getAccountHolder());
        System.out.println("Account number is " + bank2.getAccountNumber());
        System.out.println("Bank name is " + bank2.getBankName());
        System.out.println("Branch name is " + bank2.getBranchName());
        System.out.println("Balance is " + bank2.getBalance());
        System.out.println("Account type is " + bank2.getAccountType());
        System.out.println("IFSC code is " + bank2.getIfscCode());
        System.out.println("Created on " + bank2.getCreatedOn());
        System.out.println("Status is " + bank2.getStatus());
        System.out.println();

        BankDetails bank3 = new BankDetails();
        bank3.setAccountId(5003); 
        bank3.setAccountHolder("Priya R");
        bank3.setAccountNumber("456789123456");
        bank3.setBankName("ICICI Bank");
        bank3.setBranchName("Bengaluru Jayanagar");
        bank3.setBalance(125000.00); 
        bank3.setAccountType("Savings");
        bank3.setIfscCode("ICIC0001236");
        bank3.setCreatedOn("2026-02-01"); 
        bank3.setStatus("Active");

        System.out.println("Account id is " + bank3.getAccountId());
        System.out.println("Account holder is " + bank3.getAccountHolder());
        System.out.println("Account number is " + bank3.getAccountNumber());
        System.out.println("Bank name is " + bank3.getBankName());
        System.out.println("Branch name is " + bank3.getBranchName());
        System.out.println("Balance is " + bank3.getBalance());
        System.out.println("Account type is " + bank3.getAccountType());
        System.out.println("IFSC code is " + bank3.getIfscCode());
        System.out.println("Created on " + bank3.getCreatedOn());
        System.out.println("Status is " + bank3.getStatus());
        System.out.println();

        BankDetails bank4 = new BankDetails();
        bank4.setAccountId(5004); 
        bank4.setAccountHolder("Arjun K");
        bank4.setAccountNumber("789123456789");
        bank4.setBankName("Canara Bank");
        bank4.setBranchName("Bengaluru Indiranagar");
        bank4.setBalance(85000.00); 
        bank4.setAccountType("Salary");
        bank4.setIfscCode("CNRB0001237");
        bank4.setCreatedOn("2026-02-10"); 
        bank4.setStatus("Active");

        System.out.println("Account id is " + bank4.getAccountId());
        System.out.println("Account holder is " + bank4.getAccountHolder());
        System.out.println("Account number is " + bank4.getAccountNumber());
        System.out.println("Bank name is " + bank4.getBankName());
        System.out.println("Branch name is " + bank4.getBranchName());
        System.out.println("Balance is " + bank4.getBalance());
        System.out.println("Account type is " + bank4.getAccountType());
        System.out.println("IFSC code is " + bank4.getIfscCode());
        System.out.println("Created on " + bank4.getCreatedOn());
        System.out.println("Status is " + bank4.getStatus());
        System.out.println();
		
		
		BankDetails bank5 = new BankDetails();
        bank5.setAccountId(5005); 
        bank5.setAccountHolder("Vikram S");
        bank5.setAccountNumber("321654987012");
        bank5.setBankName("Axis Bank");
        bank5.setBranchName("Bengaluru Whitefield");
        bank5.setBalance(75000.00); 
        bank5.setAccountType("Savings");
        bank5.setIfscCode("UTIB0001238");
        bank5.setCreatedOn("2026-02-15"); 
        bank5.setStatus("Active");

        System.out.println("Account id is " + bank5.getAccountId());
        System.out.println("Account holder is " + bank5.getAccountHolder());
        System.out.println("Account number is " + bank5.getAccountNumber());
        System.out.println("Bank name is " + bank5.getBankName());
        System.out.println("Branch name is " + bank5.getBranchName());
        System.out.println("Balance is " + bank5.getBalance());
        System.out.println("Account type is " + bank5.getAccountType());
        System.out.println("IFSC code is " + bank5.getIfscCode());
        System.out.println("Created on " + bank5.getCreatedOn());
        System.out.println("Status is " + bank5.getStatus());
        System.out.println();

        BankDetails bank6 = new BankDetails();
        bank6.setAccountId(5006); 
        bank6.setAccountHolder("Neha P");
        bank6.setAccountNumber("654987321456");
        bank6.setBankName("Punjab National Bank");
        bank6.setBranchName("Bengaluru Malleswaram");
        bank6.setBalance(32000.00); 
        bank6.setAccountType("Savings");
        bank6.setIfscCode("PUNB0123459");
        bank6.setCreatedOn("2026-02-20"); 
        bank6.setStatus("Active");

        System.out.println("Account id is " + bank6.getAccountId());
        System.out.println("Account holder is " + bank6.getAccountHolder());
        System.out.println("Account number is " + bank6.getAccountNumber());
        System.out.println("Bank name is " + bank6.getBankName());
        System.out.println("Branch name is " + bank6.getBranchName());
        System.out.println("Balance is " + bank6.getBalance());
        System.out.println("Account type is " + bank6.getAccountType());
        System.out.println("IFSC code is " + bank6.getIfscCode());
        System.out.println("Created on " + bank6.getCreatedOn());
        System.out.println("Status is " + bank6.getStatus());
        System.out.println();

        BankDetails bank7 = new BankDetails();
        bank7.setAccountId(5007); 
        bank7.setAccountHolder("Kiran M");
        bank7.setAccountNumber("147258369852");
        bank7.setBankName("Bank of Baroda");
        bank7.setBranchName("Bengaluru Electronic City");
        bank7.setBalance(98000.00); 
        bank7.setAccountType("Current");
        bank7.setIfscCode("BARB0ECITY");
        bank7.setCreatedOn("2026-03-01"); 
        bank7.setStatus("Active");

        System.out.println("Account id is " + bank7.getAccountId());
        System.out.println("Account holder is " + bank7.getAccountHolder());
        System.out.println("Account number is " + bank7.getAccountNumber());
        System.out.println("Bank name is " + bank7.getBankName());
        System.out.println("Branch name is " + bank7.getBranchName());
        System.out.println("Balance is " + bank7.getBalance());
        System.out.println("Account type is " + bank7.getAccountType());
        System.out.println("IFSC code is " + bank7.getIfscCode());
        System.out.println("Created on " + bank7.getCreatedOn());
        System.out.println("Status is " + bank7.getStatus());
        System.out.println();
		
		
		BankDetails bank8 = new BankDetails();
        bank8.setAccountId(5008); 
        bank8.setAccountHolder("Anita D");
        bank8.setAccountNumber("258369147963");
        bank8.setBankName("Kotak Mahindra Bank");
        bank8.setBranchName("Bengaluru Marathahalli");
        bank8.setBalance(62000.00); 
        bank8.setAccountType("Savings");
        bank8.setIfscCode("KKBK0001239");
        bank8.setCreatedOn("2026-03-05"); 
        bank8.setStatus("Active");

        System.out.println("Account id is " + bank8.getAccountId());
        System.out.println("Account holder is " + bank8.getAccountHolder());
        System.out.println("Account number is " + bank8.getAccountNumber());
        System.out.println("Bank name is " + bank8.getBankName());
        System.out.println("Branch name is " + bank8.getBranchName());
        System.out.println("Balance is " + bank8.getBalance());
        System.out.println("Account type is " + bank8.getAccountType());
        System.out.println("IFSC code is " + bank8.getIfscCode());
        System.out.println("Created on " + bank8.getCreatedOn());
        System.out.println("Status is " + bank8.getStatus());
        System.out.println();

        BankDetails bank9 = new BankDetails();
        bank9.setAccountId(5009); 
        bank9.setAccountHolder("Rohan T");
        bank9.setAccountNumber("369852147852");
        bank9.setBankName("Union Bank of India");
        bank9.setBranchName("Bengaluru HSR Layout");
        bank9.setBalance(150000.00); 
        bank9.setAccountType("Current");
        bank9.setIfscCode("UNBA0001240");
        bank9.setCreatedOn("2026-03-10"); 
        bank9.setStatus("Active");

        System.out.println("Account id is " + bank9.getAccountId());
        System.out.println("Account holder is " + bank9.getAccountHolder());
        System.out.println("Account number is " + bank9.getAccountNumber());
        System.out.println("Bank name is " + bank9.getBankName());
        System.out.println("Branch name is " + bank9.getBranchName());
        System.out.println("Balance is " + bank9.getBalance());
        System.out.println("Account type is " + bank9.getAccountType());
        System.out.println("IFSC code is " + bank9.getIfscCode());
        System.out.println("Created on " + bank9.getCreatedOn());
        System.out.println("Status is " + bank9.getStatus());
        System.out.println();

        BankDetails bank10 = new BankDetails();
        bank10.setAccountId(5010); 
        bank10.setAccountHolder("Meera N");
        bank10.setAccountNumber("852741963147");
        bank10.setBankName("Indian Overseas Bank");
        bank10.setBranchName("Bengaluru Electronic City");
        bank10.setBalance(42000.00); 
        bank10.setAccountType("Savings");
        bank10.setIfscCode("IOBA0003743");
        bank10.setCreatedOn("2026-03-15"); 
        bank10.setStatus("Active");

        System.out.println("Account id is " + bank10.getAccountId());
        System.out.println("Account holder is " + bank10.getAccountHolder());
        System.out.println("Account number is " + bank10.getAccountNumber());
        System.out.println("Bank name is " + bank10.getBankName());
        System.out.println("Branch name is " + bank10.getBranchName());
        System.out.println("Balance is " + bank10.getBalance());
        System.out.println("Account type is " + bank10.getAccountType());
        System.out.println("IFSC code is " + bank10.getIfscCode());
        System.out.println("Created on " + bank10.getCreatedOn());
        System.out.println("Status is " + bank10.getStatus());
        System.out.println();
		
		
		BankDetails bank11 = new BankDetails();
        bank11.setAccountId(5011); 
        bank11.setAccountHolder("Pooja R");
        bank11.setAccountNumber("963852741258");
        bank11.setBankName("IDBI Bank");
        bank11.setBranchName("Bengaluru KR Puram");
        bank11.setBalance(58000.00); 
        bank11.setAccountType("Savings");
        bank11.setIfscCode("IBKL0001241");
        bank11.setCreatedOn("2026-03-20"); 
        bank11.setStatus("Active");

        System.out.println("Account id is " + bank11.getAccountId());
        System.out.println("Account holder is " + bank11.getAccountHolder());
        System.out.println("Account number is " + bank11.getAccountNumber());
        System.out.println("Bank name is " + bank11.getBankName());
        System.out.println("Branch name is " + bank11.getBranchName());
        System.out.println("Balance is " + bank11.getBalance());
        System.out.println("Account type is " + bank11.getAccountType());
        System.out.println("IFSC code is " + bank11.getIfscCode());
        System.out.println("Created on " + bank11.getCreatedOn());
        System.out.println("Status is " + bank11.getStatus());
        System.out.println();

        BankDetails bank12 = new BankDetails();
        bank12.setAccountId(5012); 
        bank12.setAccountHolder("Naveen K");
        bank12.setAccountNumber("741852963147");
        bank12.setBankName("Indian Bank");
        bank12.setBranchName("Bengaluru Rajajinagar");
        bank12.setBalance(210000.00); 
        bank12.setAccountType("Current");
        bank12.setIfscCode("IDIB000IN12");
        bank12.setCreatedOn("2026-03-25"); 
        bank12.setStatus("Active");

        System.out.println("Account id is " + bank12.getAccountId());
        System.out.println("Account holder is " + bank12.getAccountHolder());
        System.out.println("Account number is " + bank12.getAccountNumber());
        System.out.println("Bank name is " + bank12.getBankName());
        System.out.println("Branch name is " + bank12.getBranchName());
        System.out.println("Balance is " + bank12.getBalance());
        System.out.println("Account type is " + bank12.getAccountType());
        System.out.println("IFSC code is " + bank12.getIfscCode());
        System.out.println("Created on " + bank12.getCreatedOn());
        System.out.println("Status is " + bank12.getStatus());
        System.out.println();

        BankDetails bank13 = new BankDetails();
        bank13.setAccountId(5013); 
        bank13.setAccountHolder("Shreya S");
        bank13.setAccountNumber("159753486252");
        bank13.setBankName("Federal Bank");
        bank13.setBranchName("Bengaluru Sarjapur Road");
        bank13.setBalance(95000.00); 
        bank13.setAccountType("Savings");
        bank13.setIfscCode("FDRL0001242");
        bank13.setCreatedOn("2026-03-28"); 
        bank13.setStatus("Active");

        System.out.println("Account id is " + bank13.getAccountId());
        System.out.println("Account holder is " + bank13.getAccountHolder());
        System.out.println("Account number is " + bank13.getAccountNumber());
        System.out.println("Bank name is " + bank13.getBankName());
        System.out.println("Branch name is " + bank13.getBranchName());
        System.out.println("Balance is " + bank13.getBalance());
        System.out.println("Account type is " + bank13.getAccountType());
        System.out.println("IFSC code is " + bank13.getIfscCode());
        System.out.println("Created on " + bank13.getCreatedOn());
        System.out.println("Status is " + bank13.getStatus());
        System.out.println();
		
		BankDetails bank14 = new BankDetails();
        bank14.setAccountId(5014); 
        bank14.setAccountHolder("Ravi K");
        bank14.setAccountNumber("486252147369");
        bank14.setBankName("Vijaya Bank");
        bank14.setBranchName("Bengaluru Basaveshwaranagar");
        bank14.setBalance(68000.00); 
        bank14.setAccountType("Savings");
        bank14.setIfscCode("VIJY0001243");
        bank14.setCreatedOn("2026-03-29"); 
        bank14.setStatus("Active");

        System.out.println("Account id is " + bank14.getAccountId());
        System.out.println("Account holder is " + bank14.getAccountHolder());
        System.out.println("Account number is " + bank14.getAccountNumber());
        System.out.println("Bank name is " + bank14.getBankName());
        System.out.println("Branch name is " + bank14.getBranchName());
        System.out.println("Balance is " + bank14.getBalance());
        System.out.println("Account type is " + bank14.getAccountType());
        System.out.println("IFSC code is " + bank14.getIfscCode());
        System.out.println("Created on " + bank14.getCreatedOn());
        System.out.println("Status is " + bank14.getStatus());
        System.out.println();

        BankDetails bank15 = new BankDetails();
        bank15.setAccountId(5015); 
        bank15.setAccountHolder("Lakshmi V");
        bank15.setAccountNumber("357924168753");
        bank15.setBankName("Syndicate Bank");
        bank15.setBranchName("Bengaluru Shivajinagar");
        bank15.setBalance(115000.00); 
        bank15.setAccountType("Current");
        bank15.setIfscCode("SYNB0001244");
        bank15.setCreatedOn("2026-03-30"); 
        bank15.setStatus("Active");

        System.out.println("Account id is " + bank15.getAccountId());
        System.out.println("Account holder is " + bank15.getAccountHolder());
        System.out.println("Account number is " + bank15.getAccountNumber());
        System.out.println("Bank name is " + bank15.getBankName());
        System.out.println("Branch name is " + bank15.getBranchName());
        System.out.println("Balance is " + bank15.getBalance());
        System.out.println("Account type is " + bank15.getAccountType());
        System.out.println("IFSC code is " + bank15.getIfscCode());
        System.out.println("Created on " + bank15.getCreatedOn());
        System.out.println("Status is " + bank15.getStatus());
        System.out.println();

        BankDetails bank16 = new BankDetails();
        bank16.setAccountId(5016); 
        bank16.setAccountHolder("Ajay P");
        bank16.setAccountNumber("246813579864");
        bank16.setBankName("Corporation Bank");
        bank16.setBranchName("Bengaluru Ulsoor");
        bank16.setBalance(54000.00); 
        bank16.setAccountType("Savings");
        bank16.setIfscCode("MAHB0001245");
        bank16.setCreatedOn("2026-03-30"); 
        bank16.setStatus("Active");

        System.out.println("Account id is " + bank16.getAccountId());
        System.out.println("Account holder is " + bank16.getAccountHolder());
        System.out.println("Account number is " + bank16.getAccountNumber());
        System.out.println("Bank name is " + bank16.getBankName());
        System.out.println("Branch name is " + bank16.getBranchName());
        System.out.println("Balance is " + bank16.getBalance());
        System.out.println("Account type is " + bank16.getAccountType());
        System.out.println("IFSC code is " + bank16.getIfscCode());
        System.out.println("Created on " + bank16.getCreatedOn());
        System.out.println("Status is " + bank16.getStatus());
        System.out.println();
		
		
		BankDetails bank17 = new BankDetails();
        bank17.setAccountId(5017); 
        bank17.setAccountHolder("Sanjay G");
        bank17.setAccountNumber("753168492753");
        bank17.setBankName("Karnataka Bank");
        bank17.setBranchName("Bengaluru Udupi Garden");
        bank17.setBalance(72000.00); 
        bank17.setAccountType("Savings");
        bank17.setIfscCode("KARB0001246");
        bank17.setCreatedOn("2026-03-30"); 
        bank17.setStatus("Active");

        System.out.println("Account id is " + bank17.getAccountId());
        System.out.println("Account holder is " + bank17.getAccountHolder());
        System.out.println("Account number is " + bank17.getAccountNumber());
        System.out.println("Bank name is " + bank17.getBankName());
        System.out.println("Branch name is " + bank17.getBranchName());
        System.out.println("Balance is " + bank17.getBalance());
        System.out.println("Account type is " + bank17.getAccountType());
        System.out.println("IFSC code is " + bank17.getIfscCode());
        System.out.println("Created on " + bank17.getCreatedOn());
        System.out.println("Status is " + bank17.getStatus());
        System.out.println();

        BankDetails bank18 = new BankDetails();
        bank18.setAccountId(5018); 
        bank18.setAccountHolder("Divya M");
        bank18.setAccountNumber("864197532864");
        bank18.setBankName("South Indian Bank");
        bank18.setBranchName("Bengaluru Frazer Town");
        bank18.setBalance(89000.00); 
        bank18.setAccountType("Current");
        bank18.setIfscCode("SIBI0001247");
        bank18.setCreatedOn("2026-03-30"); 
        bank18.setStatus("Active");

        System.out.println("Account id is " + bank18.getAccountId());
        System.out.println("Account holder is " + bank18.getAccountHolder());
        System.out.println("Account number is " + bank18.getAccountNumber());
        System.out.println("Bank name is " + bank18.getBankName());
        System.out.println("Branch name is " + bank18.getBranchName());
        System.out.println("Balance is " + bank18.getBalance());
        System.out.println("Account type is " + bank18.getAccountType());
        System.out.println("IFSC code is " + bank18.getIfscCode());
        System.out.println("Created on " + bank18.getCreatedOn());
        System.out.println("Status is " + bank18.getStatus());
        System.out.println();

        BankDetails bank19 = new BankDetails();
        bank19.setAccountId(5019); 
        bank19.setAccountHolder("Tejas R");
        bank19.setAccountNumber("975308642975");
        bank19.setBankName("Karur Vysya Bank");
        bank19.setBranchName("Bengaluru Domlur");
        bank19.setBalance(125000.00); 
        bank19.setAccountType("Savings");
        bank19.setIfscCode("KVBL0001248");
        bank19.setCreatedOn("2026-03-30"); 
        bank19.setStatus("Active");

        System.out.println("Account id is " + bank19.getAccountId());
        System.out.println("Account holder is " + bank19.getAccountHolder());
        System.out.println("Account number is " + bank19.getAccountNumber());
        System.out.println("Bank name is " + bank19.getBankName());
        System.out.println("Branch name is " + bank19.getBranchName());
        System.out.println("Balance is " + bank19.getBalance());
        System.out.println("Account type is " + bank19.getAccountType());
        System.out.println("IFSC code is " + bank19.getIfscCode());
        System.out.println("Created on " + bank19.getCreatedOn());
        System.out.println("Status is " + bank19.getStatus());
        System.out.println();
		
		BankDetails bank20 = new BankDetails();
        bank20.setAccountId(5020); 
        bank20.setAccountHolder("Prakash S");
        bank20.setAccountNumber("168493752168");
        bank20.setBankName("Lakshmi Vilas Bank");
        bank20.setBranchName("Bengaluru Jayanagar");
        bank20.setBalance(83000.00); 
        bank20.setAccountType("Savings");
        bank20.setIfscCode("LAVB0001249");
        bank20.setCreatedOn("2026-03-30"); 
        bank20.setStatus("Active");

        System.out.println("Account id is " + bank20.getAccountId());
        System.out.println("Account holder is " + bank20.getAccountHolder());
        System.out.println("Account number is " + bank20.getAccountNumber());
        System.out.println("Bank name is " + bank20.getBankName());
        System.out.println("Branch name is " + bank20.getBranchName());
        System.out.println("Balance is " + bank20.getBalance());
        System.out.println("Account type is " + bank20.getAccountType());
        System.out.println("IFSC code is " + bank20.getIfscCode());
        System.out.println("Created on " + bank20.getCreatedOn());
        System.out.println("Status is " + bank20.getStatus());
        System.out.println();

        BankDetails bank21 = new BankDetails();
        bank21.setAccountId(5021); 
        bank21.setAccountHolder("Swathi R");
        bank21.setAccountNumber("279504831279");
        bank21.setBankName("City Union Bank");
        bank21.setBranchName("Bengaluru Bannerghatta Road");
        bank21.setBalance(67000.00); 
        bank21.setAccountType("Current");
        bank21.setIfscCode("CIUB0001250");
        bank21.setCreatedOn("2026-03-30"); 
        bank21.setStatus("Active");

        System.out.println("Account id is " + bank21.getAccountId());
        System.out.println("Account holder is " + bank21.getAccountHolder());
        System.out.println("Account number is " + bank21.getAccountNumber());
        System.out.println("Bank name is " + bank21.getBankName());
        System.out.println("Branch name is " + bank21.getBranchName());
        System.out.println("Balance is " + bank21.getBalance());
        System.out.println("Account type is " + bank21.getAccountType());
        System.out.println("IFSC code is " + bank21.getIfscCode());
        System.out.println("Created on " + bank21.getCreatedOn());
        System.out.println("Status is " + bank21.getStatus());
        System.out.println();

        BankDetails bank22 = new BankDetails();
        bank22.setAccountId(5022); 
        bank22.setAccountHolder("Mohan K");
        bank22.setAccountNumber("380615942380");
        bank22.setBankName("Dhanlaxmi Bank");
        bank22.setBranchName("Bengaluru Residency Road");
        bank22.setBalance(145000.00); 
        bank22.setAccountType("Savings");
        bank22.setIfscCode("DLXB0001251");
        bank22.setCreatedOn("2026-03-30"); 
        bank22.setStatus("Active");

        System.out.println("Account id is " + bank22.getAccountId());
        System.out.println("Account holder is " + bank22.getAccountHolder());
        System.out.println("Account number is " + bank22.getAccountNumber());
        System.out.println("Bank name is " + bank22.getBankName());
        System.out.println("Branch name is " + bank22.getBranchName());
        System.out.println("Balance is " + bank22.getBalance());
        System.out.println("Account type is " + bank22.getAccountType());
        System.out.println("IFSC code is " + bank22.getIfscCode());
        System.out.println("Created on " + bank22.getCreatedOn());
        System.out.println("Status is " + bank22.getStatus());
        System.out.println();
		
		
		BankDetails bank23 = new BankDetails();
        bank23.setAccountId(5023); 
        bank23.setAccountHolder("Deepa S");
        bank23.setAccountNumber("492761583492");
        bank23.setBankName("Yes Bank");
        bank23.setBranchName("Bengaluru Brigade Road");
        bank23.setBalance(92000.00); 
        bank23.setAccountType("Savings");
        bank23.setIfscCode("YESB0001252");
        bank23.setCreatedOn("2026-03-30"); 
        bank23.setStatus("Active");

        System.out.println("Account id is " + bank23.getAccountId());
        System.out.println("Account holder is " + bank23.getAccountHolder());
        System.out.println("Account number is " + bank23.getAccountNumber());
        System.out.println("Bank name is " + bank23.getBankName());
        System.out.println("Branch name is " + bank23.getBranchName());
        System.out.println("Balance is " + bank23.getBalance());
        System.out.println("Account type is " + bank23.getAccountType());
        System.out.println("IFSC code is " + bank23.getIfscCode());
        System.out.println("Created on " + bank23.getCreatedOn());
        System.out.println("Status is " + bank23.getStatus());
        System.out.println();

        BankDetails bank24 = new BankDetails();
        bank24.setAccountId(5024); 
        bank24.setAccountHolder("Karthik R");
        bank24.setAccountNumber("583472916583");
        bank24.setBankName("RBL Bank");
        bank24.setBranchName("Bengaluru Bellandur");
        bank24.setBalance(78000.00); 
        bank24.setAccountType("Current");
        bank24.setIfscCode("RATN0001253");
        bank24.setCreatedOn("2026-03-30"); 
        bank24.setStatus("Active");

        System.out.println("Account id is " + bank24.getAccountId());
        System.out.println("Account holder is " + bank24.getAccountHolder());
        System.out.println("Account number is " + bank24.getAccountNumber());
        System.out.println("Bank name is " + bank24.getBankName());
        System.out.println("Branch name is " + bank24.getBranchName());
        System.out.println("Balance is " + bank24.getBalance());
        System.out.println("Account type is " + bank24.getAccountType());
        System.out.println("IFSC code is " + bank24.getIfscCode());
        System.out.println("Created on " + bank24.getCreatedOn());
        System.out.println("Status is " + bank24.getStatus());
        System.out.println();

        BankDetails bank25 = new BankDetails();
        bank25.setAccountId(5025); 
        bank25.setAccountHolder("Geetha M");
        bank25.setAccountNumber("694583027694");
        bank25.setBankName("IndusInd Bank");
        bank25.setBranchName("Bengaluru Outer Ring Road");
        bank25.setBalance(135000.00); 
        bank25.setAccountType("Savings");
        bank25.setIfscCode("INDB0001254");
        bank25.setCreatedOn("2026-03-30"); 
        bank25.setStatus("Active");

        System.out.println("Account id is " + bank25.getAccountId());
        System.out.println("Account holder is " + bank25.getAccountHolder());
        System.out.println("Account number is " + bank25.getAccountNumber());
        System.out.println("Bank name is " + bank25.getBankName());
        System.out.println("Branch name is " + bank25.getBranchName());
        System.out.println("Balance is " + bank25.getBalance());
        System.out.println("Account type is " + bank25.getAccountType());
        System.out.println("IFSC code is " + bank25.getIfscCode());
        System.out.println("Created on " + bank25.getCreatedOn());
        System.out.println("Status is " + bank25.getStatus());
        System.out.println();
		
		BankDetails bank26 = new BankDetails();
        bank26.setAccountId(5026); 
        bank26.setAccountHolder("Suresh P");
        bank26.setAccountNumber("705694138705");
        bank26.setBankName("Bandhan Bank");
        bank26.setBranchName("Bengaluru Kammanahalli");
        bank26.setBalance(56000.00); 
        bank26.setAccountType("Savings");
        bank26.setIfscCode("BDBL0001255");
        bank26.setCreatedOn("2026-03-30"); 
        bank26.setStatus("Active");

        System.out.println("Account id is " + bank26.getAccountId());
        System.out.println("Account holder is " + bank26.getAccountHolder());
        System.out.println("Account number is " + bank26.getAccountNumber());
        System.out.println("Bank name is " + bank26.getBankName());
        System.out.println("Branch name is " + bank26.getBranchName());
        System.out.println("Balance is " + bank26.getBalance());
        System.out.println("Account type is " + bank26.getAccountType());
        System.out.println("IFSC code is " + bank26.getIfscCode());
        System.out.println("Created on " + bank26.getCreatedOn());
        System.out.println("Status is " + bank26.getStatus());
        System.out.println();

        BankDetails bank27 = new BankDetails();
        bank27.setAccountId(5027); 
        bank27.setAccountHolder("Anjali K");
        bank27.setAccountNumber("816805249816");
        bank27.setBankName("Ujjivan Small Finance Bank");
        bank27.setBranchName("Bengaluru BTM Layout");
        bank27.setBalance(104000.00); 
        bank27.setAccountType("Current");
        bank27.setIfscCode("UJVN0001256");
        bank27.setCreatedOn("2026-03-30"); 
        bank27.setStatus("Active");

        System.out.println("Account id is " + bank27.getAccountId());
        System.out.println("Account holder is " + bank27.getAccountHolder());
        System.out.println("Account number is " + bank27.getAccountNumber());
        System.out.println("Bank name is " + bank27.getBankName());
        System.out.println("Branch name is " + bank27.getBranchName());
        System.out.println("Balance is " + bank27.getBalance());
        System.out.println("Account type is " + bank27.getAccountType());
        System.out.println("IFSC code is " + bank27.getIfscCode());
        System.out.println("Created on " + bank27.getCreatedOn());
        System.out.println("Status is " + bank27.getStatus());
        System.out.println();

        BankDetails bank28 = new BankDetails();
        bank28.setAccountId(5028); 
        bank28.setAccountHolder("Vijay M");
        bank28.setAccountNumber("927916350927");
        bank28.setBankName("AU Small Finance Bank");
        bank28.setBranchName("Bengaluru Hebbal");
        bank28.setBalance(73000.00); 
        bank28.setAccountType("Savings");
        bank28.setIfscCode("AUBL0001257");
        bank28.setCreatedOn("2026-03-30"); 
        bank28.setStatus("Active");

        System.out.println("Account id is " + bank28.getAccountId());
        System.out.println("Account holder is " + bank28.getAccountHolder());
        System.out.println("Account number is " + bank28.getAccountNumber());
        System.out.println("Bank name is " + bank28.getBankName());
        System.out.println("Branch name is " + bank28.getBranchName());
        System.out.println("Balance is " + bank28.getBalance());
        System.out.println("Account type is " + bank28.getAccountType());
        System.out.println("IFSC code is " + bank28.getIfscCode());
        System.out.println("Created on " + bank28.getCreatedOn());
        System.out.println("Status is " + bank28.getStatus());
        System.out.println();
		
		
		BankDetails bank29 = new BankDetails();
        bank29.setAccountId(5029); 
        bank29.setAccountHolder("Ramesh K");
        bank29.setAccountNumber("038927461038");
        bank29.setBankName("Jio Payments Bank");
        bank29.setBranchName("Bengaluru Yelahanka");
        bank29.setBalance(45000.00); 
        bank29.setAccountType("Digital Savings");
        bank29.setIfscCode("JPBL0001258");
        bank29.setCreatedOn("2026-03-30"); 
        bank29.setStatus("Active");

        System.out.println("Account id is " + bank29.getAccountId());
        System.out.println("Account holder is " + bank29.getAccountHolder());
        System.out.println("Account number is " + bank29.getAccountNumber());
        System.out.println("Bank name is " + bank29.getBankName());
        System.out.println("Branch name is " + bank29.getBranchName());
        System.out.println("Balance is " + bank29.getBalance());
        System.out.println("Account type is " + bank29.getAccountType());
        System.out.println("IFSC code is " + bank29.getIfscCode());
        System.out.println("Created on " + bank29.getCreatedOn());
        System.out.println("Status is " + bank29.getStatus());
        System.out.println();
    }
}