class BedSheetExecutor {
    public static void main(String[] args) {

        BedSheet bed1 = new BedSheet();
        
        bed1.itemCode = 1501;
        bed1.unitPrice = 2499.99;
        bed1.hypoAllergenic = true;
        bed1.inStock = true;
        bed1.purchaseDate = "05/03/2026";
        bed1.warrantyEnd = "05/03/2028";
        bed1.warrantyValid = true;
        bed1.brand = "Bombay Dyeing";
        bed1.material = "100% Cotton";
        bed1.size = "King Double";
        bed1.color = "White";
        bed1.threadCount = 300;
        bed1.weaveType = "Percale";
        bed1.fittedSheet = true;
        bed1.pillowCaseCount = 2;
        bed1.weight = 1.8;
        bed1.careInstructions = "Machine Wash Cold";
        bed1.machineWashable = true;
        bed1.fabricQuality = "Premium";
        bed1.gsm = 200;
        bed1.wrinkleResistant = true;
        bed1.patternDesign = "Solid";
        bed1.organicCotton = false;
        bed1.collectionName = "Luxury Line";
        bed1.discountPrice = 1999.99;
        bed1.storageMethod = "Pillowcase Method";
        
        System.out.println("Item Code: " + bed1.itemCode);
        System.out.println("Unit Price: " + bed1.unitPrice);
        System.out.println("Hypo Allergenic: " + bed1.hypoAllergenic);
        System.out.println("In Stock: " + bed1.inStock);
        System.out.println("Purchase Date: " + bed1.purchaseDate);
        System.out.println("Warranty Ends: " + bed1.warrantyEnd);
        System.out.println("Warranty Valid: " + bed1.warrantyValid);
        System.out.println("Brand: " + bed1.brand);
        System.out.println("Material: " + bed1.material);
        System.out.println("Size: " + bed1.size);
        System.out.println("Color: " + bed1.color);
        System.out.println("Thread Count: " + bed1.threadCount);
        System.out.println("Weave Type: " + bed1.weaveType);
        System.out.println("Fitted Sheet: " + bed1.fittedSheet);
        System.out.println("Pillow Case Count: " + bed1.pillowCaseCount);
        System.out.println("Weight: " + bed1.weight + "kg");
        System.out.println("Care Instructions: " + bed1.careInstructions);
        System.out.println("Machine Washable: " + bed1.machineWashable);
        System.out.println("Fabric Quality: " + bed1.fabricQuality);
        System.out.println("GSM: " + bed1.gsm);
        System.out.println("Wrinkle Resistant: " + bed1.wrinkleResistant);
        System.out.println("Pattern Design: " + bed1.patternDesign);
        System.out.println("Organic Cotton: " + bed1.organicCotton);
        System.out.println("Collection Name: " + bed1.collectionName);
        System.out.println("Discount Price: " + bed1.discountPrice);
        System.out.println("Storage Method: " + bed1.storageMethod);
        System.out.println("-----------------------------");
		
        BedSheet bed2 = new BedSheet();
        
        bed2.itemCode = 1502;
        bed2.unitPrice = 1899.99;
        bed2.hypoAllergenic = false;
        bed2.inStock = true;
        bed2.purchaseDate = "04/03/2026";
        bed2.warrantyEnd = "04/03/2028";
        bed2.warrantyValid = true;
        bed2.brand = "Trident";
        bed2.material = "100% Cotton";
        bed2.size = "Double Bed";
        bed2.color = "Multicolor";
        bed2.threadCount = 180;
        bed2.weaveType = "Sateen";
        bed2.fittedSheet = false;
        bed2.pillowCaseCount = 1;
        bed2.weight = 1.2;
        bed2.careInstructions = "Warm Wash";
        bed2.machineWashable = true;
        bed2.fabricQuality = "Superior";
        bed2.gsm = 180;
        bed2.wrinkleResistant = false;
        bed2.patternDesign = "Floral Printed";
        bed2.organicCotton = false;
        bed2.collectionName = "Home Collection";
        bed2.discountPrice = 1499.99;
        bed2.storageMethod = "Drawer Organizer";
        
        System.out.println("Item Code: " + bed2.itemCode);
        System.out.println("Unit Price: " + bed2.unitPrice);
        System.out.println("Hypo Allergenic: " + bed2.hypoAllergenic);
        System.out.println("In Stock: " + bed2.inStock);
        System.out.println("Purchase Date: " + bed2.purchaseDate);
        System.out.println("Warranty Ends: " + bed2.warrantyEnd);
        System.out.println("Warranty Valid: " + bed2.warrantyValid);
        System.out.println("Brand: " + bed2.brand);
        System.out.println("Material: " + bed2.material);
        System.out.println("Size: " + bed2.size);
        System.out.println("Color: " + bed2.color);
        System.out.println("Thread Count: " + bed2.threadCount);
        System.out.println("Weave Type: " + bed2.weaveType);
        System.out.println("Fitted Sheet: " + bed2.fittedSheet);
        System.out.println("Pillow Case Count: " + bed2.pillowCaseCount);
        System.out.println("Weight: " + bed2.weight + "kg");
        System.out.println("Care Instructions: " + bed2.careInstructions);
        System.out.println("Machine Washable: " + bed2.machineWashable);
        System.out.println("Fabric Quality: " + bed2.fabricQuality);
        System.out.println("GSM: " + bed2.gsm);
        System.out.println("Wrinkle Resistant: " + bed2.wrinkleResistant);
        System.out.println("Pattern Design: " + bed2.patternDesign);
        System.out.println("Organic Cotton: " + bed2.organicCotton);
        System.out.println("Collection Name: " + bed2.collectionName);
        System.out.println("Discount Price: " + bed2.discountPrice);
        System.out.println("Storage Method: " + bed2.storageMethod);
        System.out.println("-----------------------------");
		
	
        BedSheet bed3 = new BedSheet();
        
        bed3.itemCode = 1503;
        bed3.unitPrice = 3499.99;
        bed3.hypoAllergenic = true;
        bed3.inStock = true;
        bed3.purchaseDate = "03/03/2026";
        bed3.warrantyEnd = "03/03/2029";
        bed3.warrantyValid = true;
        bed3.brand = "Spaces";
        bed3.material = "Organic Cotton";
        bed3.size = "Queen";
        bed3.color = "Beige";
        bed3.threadCount = 400;
        bed3.weaveType = "Satin";
        bed3.fittedSheet = true;
        bed3.pillowCaseCount = 2;
        bed3.weight = 1.5;
        bed3.careInstructions = "Gentle Cycle";
        bed3.machineWashable = true;
        bed3.fabricQuality = "Luxury";
        bed3.gsm = 240;
        bed3.wrinkleResistant = true;
        bed3.patternDesign = "Jacquard";
        bed3.organicCotton = true;
        bed3.collectionName = "Organic Luxe";
        bed3.discountPrice = 2999.99;
        bed3.storageMethod = "LinenMate Organizer";
        
        System.out.println("Item Code: " + bed3.itemCode);
        System.out.println("Unit Price: " + bed3.unitPrice);
        System.out.println("Storage Method: " + bed3.storageMethod);
        System.out.println("-----------------------------");

     
        BedSheet bed4 = new BedSheet();
        
        bed4.itemCode = 1504;
        bed4.unitPrice = 1299.99;
        bed4.hypoAllergenic = false;
        bed4.inStock = false;
        bed4.purchaseDate = "02/03/2026";
        bed4.warrantyEnd = "02/03/2027";
        bed4.warrantyValid = false;
        bed4.brand = "AmazonBasics";
        bed4.material = "Microfiber";
        bed4.size = "King";
        bed4.color = "Blue";
        bed4.threadCount = 0;
        bed4.weaveType = "Knit";
        bed4.fittedSheet = true;
        bed4.pillowCaseCount = 2;
        bed4.weight = 1.0;
        bed4.careInstructions = "Cold Wash";
        bed4.machineWashable = true;
        bed4.fabricQuality = "Standard";
        bed4.gsm = 120;
        bed4.wrinkleResistant = true;
        bed4.patternDesign = "Geometric Print";
        bed4.organicCotton = false;
        bed4.collectionName = "Basics Collection";
        bed4.discountPrice = 999.99;
        bed4.storageMethod = "Vacuum Bag";
        
        System.out.println("Item Code: " + bed4.itemCode);
        System.out.println("Unit Price: " + bed4.unitPrice);
        System.out.println("Storage Method: " + bed4.storageMethod);
        System.out.println("-----------------------------");
		
		        
        BedSheet bed5 = new BedSheet();
        
        bed5.itemCode = 1505;
        bed5.unitPrice = 4999.99;
        bed5.hypoAllergenic = true;
        bed5.inStock = true;
        bed5.purchaseDate = "01/03/2026";
        bed5.warrantyEnd = "01/03/2030";
        bed5.warrantyValid = true;
        bed5.brand = "Welspun";
        bed5.material = "Bamboo Silk";
        bed5.size = "Queen";
        bed5.color = "Ivory";
        bed5.threadCount = 600;
        bed5.weaveType = "Damask";
        bed5.fittedSheet = true;
        bed5.pillowCaseCount = 4;
        bed5.weight = 2.1;
        bed5.careInstructions = "Delicate Wash";
        bed5.machineWashable = false;
        bed5.fabricQuality = "Ultra Premium";
        bed5.gsm = 300;
        bed5.wrinkleResistant = true;
        bed5.patternDesign = "Damask Weave";
        bed5.organicCotton = true;
        bed5.collectionName = "Silk Luxe";
        bed5.discountPrice = 3999.99;
        bed5.storageMethod = "Cedar Chest";
        
        System.out.println("Item Code: " + bed5.itemCode);
        System.out.println("Unit Price: " + bed5.unitPrice);
        System.out.println("Hypo Allergenic: " + bed5.hypoAllergenic);
        System.out.println("In Stock: " + bed5.inStock);
        System.out.println("Purchase Date: " + bed5.purchaseDate);
        System.out.println("Warranty Ends: " + bed5.warrantyEnd);
        System.out.println("Warranty Valid: " + bed5.warrantyValid);
        System.out.println("Brand: " + bed5.brand);
        System.out.println("Material: " + bed5.material);
        System.out.println("Size: " + bed5.size);
        System.out.println("Color: " + bed5.color);
        System.out.println("Thread Count: " + bed5.threadCount);
        System.out.println("Weave Type: " + bed5.weaveType);
        System.out.println("Fitted Sheet: " + bed5.fittedSheet);
        System.out.println("Pillow Case Count: " + bed5.pillowCaseCount);
        System.out.println("Weight: " + bed5.weight + "kg");
        System.out.println("Care Instructions: " + bed5.careInstructions);
        System.out.println("Machine Washable: " + bed5.machineWashable);
        System.out.println("Fabric Quality: " + bed5.fabricQuality);
        System.out.println("GSM: " + bed5.gsm);
        System.out.println("Wrinkle Resistant: " + bed5.wrinkleResistant);
        System.out.println("Pattern Design: " + bed5.patternDesign);
        System.out.println("Organic Cotton: " + bed5.organicCotton);
        System.out.println("Collection Name: " + bed5.collectionName);
        System.out.println("Discount Price: " + bed5.discountPrice);
        System.out.println("Storage Method: " + bed5.storageMethod);
        System.out.println("-----------------------------");
		
		

        BedSheet bed6 = new BedSheet();
        
        bed6.itemCode = 1506;
        bed6.unitPrice = 999.99;
        bed6.hypoAllergenic = false;
        bed6.inStock = true;
        bed6.purchaseDate = "28/02/2026";
        bed6.warrantyEnd = "28/02/2027";
        bed6.warrantyValid = false;
        bed6.brand = "HomeCenter";
        bed6.material = "Linen Cotton Blend";
        bed6.size = "Single";
        bed6.color = "Grey";
        bed6.threadCount = 120;
        bed6.weaveType = "Plain Weave";
        bed6.fittedSheet = false;
        bed6.pillowCaseCount = 1;
        bed6.weight = 0.8;
        bed6.careInstructions = "Hot Wash";
        bed6.machineWashable = true;
        bed6.fabricQuality = "Basic";
        bed6.gsm = 150;
        bed6.wrinkleResistant = false;
        bed6.patternDesign = "Striped";
        bed6.organicCotton = false;
        bed6.collectionName = "Everyday Basics";
        bed6.discountPrice = 799.99;
        bed6.storageMethod = "Under Bed Storage";
        
        System.out.println("Item Code: " + bed6.itemCode);
        System.out.println("Unit Price: " + bed6.unitPrice);
        System.out.println("Hypo Allergenic: " + bed6.hypoAllergenic);
        System.out.println("In Stock: " + bed6.inStock);
        System.out.println("Purchase Date: " + bed6.purchaseDate);
        System.out.println("Warranty Ends: " + bed6.warrantyEnd);
        System.out.println("Warranty Valid: " + bed6.warrantyValid);
        System.out.println("Brand: " + bed6.brand);
        System.out.println("Material: " + bed6.material);
        System.out.println("Size: " + bed6.size);
        System.out.println("Color: " + bed6.color);
        System.out.println("Thread Count: " + bed6.threadCount);
        System.out.println("Weave Type: " + bed6.weaveType);
        System.out.println("Fitted Sheet: " + bed6.fittedSheet);
        System.out.println("Pillow Case Count: " + bed6.pillowCaseCount);
        System.out.println("Weight: " + bed6.weight + "kg");
        System.out.println("Care Instructions: " + bed6.careInstructions);
        System.out.println("Machine Washable: " + bed6.machineWashable);
        System.out.println("Fabric Quality: " + bed6.fabricQuality);
        System.out.println("GSM: " + bed6.gsm);
        System.out.println("Wrinkle Resistant: " + bed6.wrinkleResistant);
        System.out.println("Pattern Design: " + bed6.patternDesign);
        System.out.println("Organic Cotton: " + bed6.organicCotton);
        System.out.println("Collection Name: " + bed6.collectionName);
        System.out.println("Discount Price: " + bed6.discountPrice);
        System.out.println("Storage Method: " + bed6.storageMethod);
        System.out.println("-----------------------------");
		
	
        BedSheet bed7 = new BedSheet();
        
        bed7.itemCode = 1507;
        bed7.unitPrice = 2999.99;
        bed7.hypoAllergenic = true;
        bed7.inStock = true;
        bed7.purchaseDate = "27/02/2026";
        bed7.warrantyEnd = "27/02/2029";
        bed7.warrantyValid = true;
        bed7.brand = "Portico";
        bed7.material = "Egyptian Cotton";
        bed7.size = "King";
        bed7.color = "Navy Blue";
        bed7.threadCount = 500;
        bed7.weaveType = "Percale";
        bed7.fittedSheet = true;
        bed7.pillowCaseCount = 2;
        bed7.weight = 2.0;
        bed7.careInstructions = "Cold Wash";
        bed7.machineWashable = true;
        bed7.fabricQuality = "Luxury";
        bed7.gsm = 220;
        bed7.wrinkleResistant = true;
        bed7.patternDesign = "Block Print";
        bed7.organicCotton = false;
        bed7.collectionName = "Royal Collection";
        bed7.discountPrice = 2499.99;
        bed7.storageMethod = "Fabric Box";
        
        System.out.println("Item Code: " + bed7.itemCode);
        System.out.println("Unit Price: " + bed7.unitPrice);
        System.out.println("Hypo Allergenic: " + bed7.hypoAllergenic);
        System.out.println("In Stock: " + bed7.inStock);
        System.out.println("Purchase Date: " + bed7.purchaseDate);
        System.out.println("Warranty Ends: " + bed7.warrantyEnd);
        System.out.println("Warranty Valid: " + bed7.warrantyValid);
        System.out.println("Brand: " + bed7.brand);
        System.out.println("Material: " + bed7.material);
        System.out.println("Size: " + bed7.size);
        System.out.println("Color: " + bed7.color);
        System.out.println("Thread Count: " + bed7.threadCount);
        System.out.println("Weave Type: " + bed7.weaveType);
        System.out.println("Fitted Sheet: " + bed7.fittedSheet);
        System.out.println("Pillow Case Count: " + bed7.pillowCaseCount);
        System.out.println("Weight: " + bed7.weight + "kg");
        System.out.println("Care Instructions: " + bed7.careInstructions);
        System.out.println("Machine Washable: " + bed7.machineWashable);
        System.out.println("Fabric Quality: " + bed7.fabricQuality);
        System.out.println("GSM: " + bed7.gsm);
        System.out.println("Wrinkle Resistant: " + bed7.wrinkleResistant);
        System.out.println("Pattern Design: " + bed7.patternDesign);
        System.out.println("Organic Cotton: " + bed7.organicCotton);
        System.out.println("Collection Name: " + bed7.collectionName);
        System.out.println("Discount Price: " + bed7.discountPrice);
        System.out.println("Storage Method: " + bed7.storageMethod);
        System.out.println("-----------------------------");
		
		
		       
        BedSheet bed8 = new BedSheet();
        
        bed8.itemCode = 1508;
        bed8.unitPrice = 1599.99;
        bed8.hypoAllergenic = true;
        bed8.inStock = true;
        bed8.purchaseDate = "26/02/2026";
        bed8.warrantyEnd = "26/02/2028";
        bed8.warrantyValid = true;
        bed8.brand = "Duro";
        bed8.material = "Polyester with Waterproof Coating";
        bed8.size = "Queen";
        bed8.color = "Charcoal";
        bed8.threadCount = 250;
        bed8.weaveType = "Microfiber";
        bed8.fittedSheet = true;
        bed8.pillowCaseCount = 2;
        bed8.weight = 1.4;
        bed8.careInstructions = "Cold Wash, No Bleach";
        bed8.machineWashable = true;
        bed8.fabricQuality = "Durable";
        bed8.gsm = 160;
        bed8.wrinkleResistant = true;
        bed8.patternDesign = "Solid";
        bed8.organicCotton = false;
        bed8.collectionName = "Protective Series";
        bed8.discountPrice = 1299.99;
        bed8.storageMethod = "Plastic Bin";
        
        System.out.println("Item Code: " + bed8.itemCode);
        System.out.println("Unit Price: " + bed8.unitPrice);
        System.out.println("Hypo Allergenic: " + bed8.hypoAllergenic);
        System.out.println("In Stock: " + bed8.inStock);
        System.out.println("Purchase Date: " + bed8.purchaseDate);
        System.out.println("Warranty Ends: " + bed8.warrantyEnd);
        System.out.println("Warranty Valid: " + bed8.warrantyValid);
        System.out.println("Brand: " + bed8.brand);
        System.out.println("Material: " + bed8.material);
        System.out.println("Size: " + bed8.size);
        System.out.println("Color: " + bed8.color);
        System.out.println("Thread Count: " + bed8.threadCount);
        System.out.println("Weave Type: " + bed8.weaveType);
        System.out.println("Fitted Sheet: " + bed8.fittedSheet);
        System.out.println("Pillow Case Count: " + bed8.pillowCaseCount);
        System.out.println("Weight: " + bed8.weight + "kg");
        System.out.println("Care Instructions: " + bed8.careInstructions);
        System.out.println("Machine Washable: " + bed8.machineWashable);
        System.out.println("Fabric Quality: " + bed8.fabricQuality);
        System.out.println("GSM: " + bed8.gsm);
        System.out.println("Wrinkle Resistant: " + bed8.wrinkleResistant);
        System.out.println("Pattern Design: " + bed8.patternDesign);
        System.out.println("Organic Cotton: " + bed8.organicCotton);
        System.out.println("Collection Name: " + bed8.collectionName);
        System.out.println("Discount Price: " + bed8.discountPrice);
        System.out.println("Storage Method: " + bed8.storageMethod);
        System.out.println("-----------------------------");
		
		
        BedSheet bed9 = new BedSheet();
        
        bed9.itemCode = 1509;
        bed9.unitPrice = 3999.99;
        bed9.hypoAllergenic = true;
        bed9.inStock = true;
        bed9.purchaseDate = "25/02/2026";
        bed9.warrantyEnd = "25/02/2029";
        bed9.warrantyValid = true;
        bed9.brand = "Luxome";
        bed9.material = "100% Bamboo Viscose";
        bed9.size = "King";
        bed9.color = "Sage Green";
        bed9.threadCount = 400;
        bed9.weaveType = "Sateen";
        bed9.fittedSheet = true;
        bed9.pillowCaseCount = 2;
        bed9.weight = 1.6;
        bed9.careInstructions = "Cold Wash Gentle";
        bed9.machineWashable = true;
        bed9.fabricQuality = "Luxury Cooling";
        bed9.gsm = 260;
        bed9.wrinkleResistant = true;
        bed9.patternDesign = "Solid";
        bed9.organicCotton = false;
        bed9.collectionName = "Cooling Series";
        bed9.discountPrice = 3499.99;
        bed9.storageMethod = "Breathable Cotton Bag";
        
        System.out.println("Item Code: " + bed9.itemCode);
        System.out.println("Unit Price: " + bed9.unitPrice);
        System.out.println("Hypo Allergenic: " + bed9.hypoAllergenic);
        System.out.println("In Stock: " + bed9.inStock);
        System.out.println("Purchase Date: " + bed9.purchaseDate);
        System.out.println("Warranty Ends: " + bed9.warrantyEnd);
        System.out.println("Warranty Valid: " + bed9.warrantyValid);
        System.out.println("Brand: " + bed9.brand);
        System.out.println("Material: " + bed9.material);
        System.out.println("Size: " + bed9.size);
        System.out.println("Color: " + bed9.color);
        System.out.println("Thread Count: " + bed9.threadCount);
        System.out.println("Weave Type: " + bed9.weaveType);
        System.out.println("Fitted Sheet: " + bed9.fittedSheet);
        System.out.println("Pillow Case Count: " + bed9.pillowCaseCount);
        System.out.println("Weight: " + bed9.weight + "kg");
        System.out.println("Care Instructions: " + bed9.careInstructions);
        System.out.println("Machine Washable: " + bed9.machineWashable);
        System.out.println("Fabric Quality: " + bed9.fabricQuality);
        System.out.println("GSM: " + bed9.gsm);
        System.out.println("Wrinkle Resistant: " + bed9.wrinkleResistant);
        System.out.println("Pattern Design: " + bed9.patternDesign);
        System.out.println("Organic Cotton: " + bed9.organicCotton);
        System.out.println("Collection Name: " + bed9.collectionName);
        System.out.println("Discount Price: " + bed9.discountPrice);
        System.out.println("Storage Method: " + bed9.storageMethod);
        System.out.println("-----------------------------");



        BedSheet bed10 = new BedSheet();
        
        bed10.itemCode = 1510;
        bed10.unitPrice = 5999.99;
        bed10.hypoAllergenic = true;
        bed10.inStock = true;
        bed10.purchaseDate = "24/02/2026";
        bed10.warrantyEnd = "24/02/2031";
        bed10.warrantyValid = true;
        bed10.brand = "Pure Parima";
        bed10.material = "100% Egyptian Cotton";
        bed10.size = "Double";
        bed10.color = "Ivory";
        bed10.threadCount = 600;
        bed10.weaveType = "Sateen";
        bed10.fittedSheet = true;
        bed10.pillowCaseCount = 2;
        bed10.weight = 1.9;
        bed10.careInstructions = "Delicate Cold Wash";
        bed10.machineWashable = true;
        bed10.fabricQuality = "Extra Long Staple";
        bed10.gsm = 280;
        bed10.wrinkleResistant = true;
        bed10.patternDesign = "Solid Luxury";
        bed10.organicCotton = false;
        bed10.collectionName = "Egyptian Royale";
        bed10.discountPrice = 4999.99;
        bed10.storageMethod = "Silk Lined Box";
        
        System.out.println("Item Code: " + bed10.itemCode);
        System.out.println("Unit Price: " + bed10.unitPrice);
        System.out.println("Hypo Allergenic: " + bed10.hypoAllergenic);
        System.out.println("In Stock: " + bed10.inStock);
        System.out.println("Purchase Date: " + bed10.purchaseDate);
        System.out.println("Warranty Ends: " + bed10.warrantyEnd);
        System.out.println("Warranty Valid: " + bed10.warrantyValid);
        System.out.println("Brand: " + bed10.brand);
        System.out.println("Material: " + bed10.material);
        System.out.println("Size: " + bed10.size);
        System.out.println("Color: " + bed10.color);
        System.out.println("Thread Count: " + bed10.threadCount);
        System.out.println("Weave Type: " + bed10.weaveType);
        System.out.println("Fitted Sheet: " + bed10.fittedSheet);
        System.out.println("Pillow Case Count: " + bed10.pillowCaseCount);
        System.out.println("Weight: " + bed10.weight + "kg");
        System.out.println("Care Instructions: " + bed10.careInstructions);
        System.out.println("Machine Washable: " + bed10.machineWashable);
        System.out.println("Fabric Quality: " + bed10.fabricQuality);
        System.out.println("GSM: " + bed10.gsm);
        System.out.println("Wrinkle Resistant: " + bed10.wrinkleResistant);
        System.out.println("Pattern Design: " + bed10.patternDesign);
        System.out.println("Organic Cotton: " + bed10.organicCotton);
        System.out.println("Collection Name: " + bed10.collectionName);
        System.out.println("Discount Price: " + bed10.discountPrice);
        System.out.println("Storage Method: " + bed10.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed11 = new BedSheet();
        
        bed11.itemCode = 1511;
        bed11.unitPrice = 2799.99;
        bed11.hypoAllergenic = true;
        bed11.inStock = true;
        bed11.purchaseDate = "23/02/2026";
        bed11.warrantyEnd = "23/02/2028";
        bed11.warrantyValid = true;
        bed11.brand = "Raymond Home";
        bed11.material = "Brushed Cotton Flannel";
        bed11.size = "King";
        bed11.color = "Deep Maroon";
        bed11.threadCount = 170;
        bed11.weaveType = "Flannel";
        bed11.fittedSheet = true;
        bed11.pillowCaseCount = 2;
        bed11.weight = 2.4;
        bed11.careInstructions = "Warm Wash, Low Dry";
        bed11.machineWashable = true;
        bed11.fabricQuality = "Thermal";
        bed11.gsm = 320;
        bed11.wrinkleResistant = false;
        bed11.patternDesign = "Checked";
        bed11.organicCotton = false;
        bed11.collectionName = "Winter Comfort";
        bed11.discountPrice = 2299.99;
        bed11.storageMethod = "Vacuum Sealed Bag";
        
        System.out.println("Item Code: " + bed11.itemCode);
        System.out.println("Unit Price: " + bed11.unitPrice);
        System.out.println("Hypo Allergenic: " + bed11.hypoAllergenic);
        System.out.println("In Stock: " + bed11.inStock);
        System.out.println("Purchase Date: " + bed11.purchaseDate);
        System.out.println("Warranty Ends: " + bed11.warrantyEnd);
        System.out.println("Warranty Valid: " + bed11.warrantyValid);
        System.out.println("Brand: " + bed11.brand);
        System.out.println("Material: " + bed11.material);
        System.out.println("Size: " + bed11.size);
        System.out.println("Color: " + bed11.color);
        System.out.println("Thread Count: " + bed11.threadCount);
        System.out.println("Weave Type: " + bed11.weaveType);
        System.out.println("Fitted Sheet: " + bed11.fittedSheet);
        System.out.println("Pillow Case Count: " + bed11.pillowCaseCount);
        System.out.println("Weight: " + bed11.weight + "kg");
        System.out.println("Care Instructions: " + bed11.careInstructions);
        System.out.println("Machine Washable: " + bed11.machineWashable);
        System.out.println("Fabric Quality: " + bed11.fabricQuality);
        System.out.println("GSM: " + bed11.gsm);
        System.out.println("Wrinkle Resistant: " + bed11.wrinkleResistant);
        System.out.println("Pattern Design: " + bed11.patternDesign);
        System.out.println("Organic Cotton: " + bed11.organicCotton);
        System.out.println("Collection Name: " + bed11.collectionName);
        System.out.println("Discount Price: " + bed11.discountPrice);
        System.out.println("Storage Method: " + bed11.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed12 = new BedSheet();
        
        bed12.itemCode = 1512;
        bed12.unitPrice = 3299.99;
        bed12.hypoAllergenic = true;
        bed12.inStock = true;
        bed12.purchaseDate = "22/02/2026";
        bed12.warrantyEnd = "22/02/2029";
        bed12.warrantyValid = true;
        bed12.brand = "Weavve";
        bed12.material = "Tencel Lyocell";
        bed12.size = "Queen";
        bed12.color = "Oatmeal";
        bed12.threadCount = 300;
        bed12.weaveType = "Jersey Knit";
        bed12.fittedSheet = true;
        bed12.pillowCaseCount = 2;
        bed12.weight = 1.3;
        bed12.careInstructions = "Eco Wash Cold";
        bed12.machineWashable = true;
        bed12.fabricQuality = "Sustainable";
        bed12.gsm = 200;
        bed12.wrinkleResistant = true;
        bed12.patternDesign = "Texture Weave";
        bed12.organicCotton = true;
        bed12.collectionName = "Eco Luxe";
        bed12.discountPrice = 2799.99;
        bed12.storageMethod = "Bamboo Basket";
        
        System.out.println("Item Code: " + bed12.itemCode);
        System.out.println("Unit Price: " + bed12.unitPrice);
        System.out.println("Hypo Allergenic: " + bed12.hypoAllergenic);
        System.out.println("In Stock: " + bed12.inStock);
        System.out.println("Purchase Date: " + bed12.purchaseDate);
        System.out.println("Warranty Ends: " + bed12.warrantyEnd);
        System.out.println("Warranty Valid: " + bed12.warrantyValid);
        System.out.println("Brand: " + bed12.brand);
        System.out.println("Material: " + bed12.material);
        System.out.println("Size: " + bed12.size);
        System.out.println("Color: " + bed12.color);
        System.out.println("Thread Count: " + bed12.threadCount);
        System.out.println("Weave Type: " + bed12.weaveType);
        System.out.println("Fitted Sheet: " + bed12.fittedSheet);
        System.out.println("Pillow Case Count: " + bed12.pillowCaseCount);
        System.out.println("Weight: " + bed12.weight + "kg");
        System.out.println("Care Instructions: " + bed12.careInstructions);
        System.out.println("Machine Washable: " + bed12.machineWashable);
        System.out.println("Fabric Quality: " + bed12.fabricQuality);
        System.out.println("GSM: " + bed12.gsm);
        System.out.println("Wrinkle Resistant: " + bed12.wrinkleResistant);
        System.out.println("Pattern Design: " + bed12.patternDesign);
        System.out.println("Organic Cotton: " + bed12.organicCotton);
        System.out.println("Collection Name: " + bed12.collectionName);
        System.out.println("Discount Price: " + bed12.discountPrice);
        System.out.println("Storage Method: " + bed12.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed13 = new BedSheet();
        
        bed13.itemCode = 1513;
        bed13.unitPrice = 8999.99;
        bed13.hypoAllergenic = true;
        bed13.inStock = false;
        bed13.purchaseDate = "21/02/2026";
        bed13.warrantyEnd = "21/02/2032";
        bed13.warrantyValid = true;
        bed13.brand = "Zomas";
        bed13.material = "Mulberry Silk Blend";
        bed13.size = "California King";
        bed13.color = "Champagne";
        bed13.threadCount = 800;
        bed13.weaveType = "Charmeuse";
        bed13.fittedSheet = true;
        bed13.pillowCaseCount = 4;
        bed13.weight = 1.1;
        bed13.careInstructions = "Dry Clean Only";
        bed13.machineWashable = false;
        bed13.fabricQuality = "19 Momme";
        bed13.gsm = 350;
        bed13.wrinkleResistant = true;
        bed13.patternDesign = "Satin Sheen";
        bed13.organicCotton = false;
        bed13.collectionName = "Silk Heritage";
        bed13.discountPrice = 7999.99;
        bed13.storageMethod = "Silk Pouch";
        
        System.out.println("Item Code: " + bed13.itemCode);
        System.out.println("Unit Price: " + bed13.unitPrice);
        System.out.println("Hypo Allergenic: " + bed13.hypoAllergenic);
        System.out.println("In Stock: " + bed13.inStock);
        System.out.println("Purchase Date: " + bed13.purchaseDate);
        System.out.println("Warranty Ends: " + bed13.warrantyEnd);
        System.out.println("Warranty Valid: " + bed13.warrantyValid);
        System.out.println("Brand: " + bed13.brand);
        System.out.println("Material: " + bed13.material);
        System.out.println("Size: " + bed13.size);
        System.out.println("Color: " + bed13.color);
        System.out.println("Thread Count: " + bed13.threadCount);
        System.out.println("Weave Type: " + bed13.weaveType);
        System.out.println("Fitted Sheet: " + bed13.fittedSheet);
        System.out.println("Pillow Case Count: " + bed13.pillowCaseCount);
        System.out.println("Weight: " + bed13.weight + "kg");
        System.out.println("Care Instructions: " + bed13.careInstructions);
        System.out.println("Machine Washable: " + bed13.machineWashable);
        System.out.println("Fabric Quality: " + bed13.fabricQuality);
        System.out.println("GSM: " + bed13.gsm);
        System.out.println("Wrinkle Resistant: " + bed13.wrinkleResistant);
        System.out.println("Pattern Design: " + bed13.patternDesign);
        System.out.println("Organic Cotton: " + bed13.organicCotton);
        System.out.println("Collection Name: " + bed13.collectionName);
        System.out.println("Discount Price: " + bed13.discountPrice);
        System.out.println("Storage Method: " + bed13.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed14 = new BedSheet();
        
        bed14.itemCode = 1514;
        bed14.unitPrice = 7499.99;
        bed14.hypoAllergenic = true;
        bed14.inStock = true;
        bed14.purchaseDate = "20/02/2026";
        bed14.warrantyEnd = "20/02/2030";
        bed14.warrantyValid = true;
        bed14.brand = "Blue Nile Mills";
        bed14.material = "Giza 45 Egyptian Cotton";
        bed14.size = "Super King";
        bed14.color = "Natural White";
        bed14.threadCount = 580;
        bed14.weaveType = "Sateen";
        bed14.fittedSheet = true;
        bed14.pillowCaseCount = 2;
        bed14.weight = 2.2;
        bed14.careInstructions = "Cold Wash Delicate";
        bed14.machineWashable = true;
        bed14.fabricQuality = "Extra Long Staple";
        bed14.gsm = 290;
        bed14.wrinkleResistant = true;
        bed14.patternDesign = "Pinstripe";
        bed14.organicCotton = false;
        bed14.collectionName = "Giza Elite";
        bed14.discountPrice = 6499.99;
        bed14.storageMethod = "Wooden Linen Chest";
        
        System.out.println("Item Code: " + bed14.itemCode);
        System.out.println("Unit Price: " + bed14.unitPrice);
        System.out.println("Hypo Allergenic: " + bed14.hypoAllergenic);
        System.out.println("In Stock: " + bed14.inStock);
        System.out.println("Purchase Date: " + bed14.purchaseDate);
        System.out.println("Warranty Ends: " + bed14.warrantyEnd);
        System.out.println("Warranty Valid: " + bed14.warrantyValid);
        System.out.println("Brand: " + bed14.brand);
        System.out.println("Material: " + bed14.material);
        System.out.println("Size: " + bed14.size);
        System.out.println("Color: " + bed14.color);
        System.out.println("Thread Count: " + bed14.threadCount);
        System.out.println("Weave Type: " + bed14.weaveType);
        System.out.println("Fitted Sheet: " + bed14.fittedSheet);
        System.out.println("Pillow Case Count: " + bed14.pillowCaseCount);
        System.out.println("Weight: " + bed14.weight + "kg");
        System.out.println("Care Instructions: " + bed14.careInstructions);
        System.out.println("Machine Washable: " + bed14.machineWashable);
        System.out.println("Fabric Quality: " + bed14.fabricQuality);
        System.out.println("GSM: " + bed14.gsm);
        System.out.println("Wrinkle Resistant: " + bed14.wrinkleResistant);
        System.out.println("Pattern Design: " + bed14.patternDesign);
        System.out.println("Organic Cotton: " + bed14.organicCotton);
        System.out.println("Collection Name: " + bed14.collectionName);
        System.out.println("Discount Price: " + bed14.discountPrice);
        System.out.println("Storage Method: " + bed14.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed15 = new BedSheet();
        
        bed15.itemCode = 1515;
        bed15.unitPrice = 1399.99;
        bed15.hypoAllergenic = true;
        bed15.inStock = true;
        bed15.purchaseDate = "19/02/2026";
        bed15.warrantyEnd = "19/02/2028";
        bed15.warrantyValid = true;
        bed15.brand = "UFO";
        bed15.material = "Organic Percale Cotton";
        bed15.size = "Twin";
        bed15.color = "Pastel Blue";
        bed15.threadCount = 200;
        bed15.weaveType = "Percale";
        bed15.fittedSheet = true;
        bed15.pillowCaseCount = 1;
        bed15.weight = 1.0;
        bed15.careInstructions = "Regular Wash";
        bed15.machineWashable = true;
        bed15.fabricQuality = "Kid-Safe";
        bed15.gsm = 180;
        bed15.wrinkleResistant = true;
        bed15.patternDesign = "Cartoon Print";
        bed15.organicCotton = true;
        bed15.collectionName = "Kids Collection";
        bed15.discountPrice = 1099.99;
        bed15.storageMethod = "Kids Wardrobe Shelf";
        
        System.out.println("Item Code: " + bed15.itemCode);
        System.out.println("Unit Price: " + bed15.unitPrice);
        System.out.println("Hypo Allergenic: " + bed15.hypoAllergenic);
        System.out.println("In Stock: " + bed15.inStock);
        System.out.println("Purchase Date: " + bed15.purchaseDate);
        System.out.println("Warranty Ends: " + bed15.warrantyEnd);
        System.out.println("Warranty Valid: " + bed15.warrantyValid);
        System.out.println("Brand: " + bed15.brand);
        System.out.println("Material: " + bed15.material);
        System.out.println("Size: " + bed15.size);
        System.out.println("Color: " + bed15.color);
        System.out.println("Thread Count: " + bed15.threadCount);
        System.out.println("Weave Type: " + bed15.weaveType);
        System.out.println("Fitted Sheet: " + bed15.fittedSheet);
        System.out.println("Pillow Case Count: " + bed15.pillowCaseCount);
        System.out.println("Weight: " + bed15.weight + "kg");
        System.out.println("Care Instructions: " + bed15.careInstructions);
        System.out.println("Machine Washable: " + bed15.machineWashable);
        System.out.println("Fabric Quality: " + bed15.fabricQuality);
        System.out.println("GSM: " + bed15.gsm);
        System.out.println("Wrinkle Resistant: " + bed15.wrinkleResistant);
        System.out.println("Pattern Design: " + bed15.patternDesign);
        System.out.println("Organic Cotton: " + bed15.organicCotton);
        System.out.println("Collection Name: " + bed15.collectionName);
        System.out.println("Discount Price: " + bed15.discountPrice);
        System.out.println("Storage Method: " + bed15.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed16 = new BedSheet();
        
        bed16.itemCode = 1516;
        bed16.unitPrice = 2199.99;
        bed16.hypoAllergenic = false;
        bed16.inStock = true;
        bed16.purchaseDate = "18/02/2026";
        bed16.warrantyEnd = "18/02/2028";
        bed16.warrantyValid = true;
        bed16.brand = "FabIndia";
        bed16.material = "Handloom Cotton";
        bed16.size = "Queen";
        bed16.color = "Terracotta";
        bed16.threadCount = 220;
        bed16.weaveType = "Plain Weave";
        bed16.fittedSheet = false;
        bed16.pillowCaseCount = 2;
        bed16.weight = 1.4;
        bed16.careInstructions = "Hand Wash Preferred";
        bed16.machineWashable = true;
        bed16.fabricQuality = "Artisan";
        bed16.gsm = 190;
        bed16.wrinkleResistant = false;
        bed16.patternDesign = "Geometric Block Print";
        bed16.organicCotton = true;
        bed16.collectionName = "Heritage Collection";
        bed16.discountPrice = 1799.99;
        bed16.storageMethod = "Wicker Basket";
        
        System.out.println("Item Code: " + bed16.itemCode);
        System.out.println("Unit Price: " + bed16.unitPrice);
        System.out.println("Hypo Allergenic: " + bed16.hypoAllergenic);
        System.out.println("In Stock: " + bed16.inStock);
        System.out.println("Purchase Date: " + bed16.purchaseDate);
        System.out.println("Warranty Ends: " + bed16.warrantyEnd);
        System.out.println("Warranty Valid: " + bed16.warrantyValid);
        System.out.println("Brand: " + bed16.brand);
        System.out.println("Material: " + bed16.material);
        System.out.println("Size: " + bed16.size);
        System.out.println("Color: " + bed16.color);
        System.out.println("Thread Count: " + bed16.threadCount);
        System.out.println("Weave Type: " + bed16.weaveType);
        System.out.println("Fitted Sheet: " + bed16.fittedSheet);
        System.out.println("Pillow Case Count: " + bed16.pillowCaseCount);
        System.out.println("Weight: " + bed16.weight + "kg");
        System.out.println("Care Instructions: " + bed16.careInstructions);
        System.out.println("Machine Washable: " + bed16.machineWashable);
        System.out.println("Fabric Quality: " + bed16.fabricQuality);
        System.out.println("GSM: " + bed16.gsm);
        System.out.println("Wrinkle Resistant: " + bed16.wrinkleResistant);
        System.out.println("Pattern Design: " + bed16.patternDesign);
        System.out.println("Organic Cotton: " + bed16.organicCotton);
        System.out.println("Collection Name: " + bed16.collectionName);
        System.out.println("Discount Price: " + bed16.discountPrice);
        System.out.println("Storage Method: " + bed16.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed17 = new BedSheet();
        
        bed17.itemCode = 1517;
        bed17.unitPrice = 2599.99;
        bed17.hypoAllergenic = true;
        bed17.inStock = true;
        bed17.purchaseDate = "17/02/2026";
        bed17.warrantyEnd = "17/02/2029";
        bed17.warrantyValid = true;
        bed17.brand = "Sleepwell";
        bed17.material = "Modal with Cooling Tech";
        bed17.size = "Double";
        bed17.color = "Ice Blue";
        bed17.threadCount = 350;
        bed17.weaveType = "Micro Sateen";
        bed17.fittedSheet = true;
        bed17.pillowCaseCount = 2;
        bed17.weight = 1.2;
        bed17.careInstructions = "Cold Wash Gentle";
        bed17.machineWashable = true;
        bed17.fabricQuality = "Performance";
        bed17.gsm = 210;
        bed17.wrinkleResistant = true;
        bed17.patternDesign = "Subtle Texture";
        bed17.organicCotton = false;
        bed17.collectionName = "CoolTech Series";
        bed17.discountPrice = 2199.99;
        bed17.storageMethod = "Mesh Laundry Bag";
        
        System.out.println("Item Code: " + bed17.itemCode);
        System.out.println("Unit Price: " + bed17.unitPrice);
        System.out.println("Hypo Allergenic: " + bed17.hypoAllergenic);
        System.out.println("In Stock: " + bed17.inStock);
        System.out.println("Purchase Date: " + bed17.purchaseDate);
        System.out.println("Warranty Ends: " + bed17.warrantyEnd);
        System.out.println("Warranty Valid: " + bed17.warrantyValid);
        System.out.println("Brand: " + bed17.brand);
        System.out.println("Material: " + bed17.material);
        System.out.println("Size: " + bed17.size);
        System.out.println("Color: " + bed17.color);
        System.out.println("Thread Count: " + bed17.threadCount);
        System.out.println("Weave Type: " + bed17.weaveType);
        System.out.println("Fitted Sheet: " + bed17.fittedSheet);
        System.out.println("Pillow Case Count: " + bed17.pillowCaseCount);
        System.out.println("Weight: " + bed17.weight + "kg");
        System.out.println("Care Instructions: " + bed17.careInstructions);
        System.out.println("Machine Washable: " + bed17.machineWashable);
        System.out.println("Fabric Quality: " + bed17.fabricQuality);
        System.out.println("GSM: " + bed17.gsm);
        System.out.println("Wrinkle Resistant: " + bed17.wrinkleResistant);
        System.out.println("Pattern Design: " + bed17.patternDesign);
        System.out.println("Organic Cotton: " + bed17.organicCotton);
        System.out.println("Collection Name: " + bed17.collectionName);
        System.out.println("Discount Price: " + bed17.discountPrice);
        System.out.println("Storage Method: " + bed17.storageMethod);
        System.out.println("-----------------------------");



        BedSheet bed18 = new BedSheet();
        
        bed18.itemCode = 1518;
        bed18.unitPrice = 3699.99;
        bed18.hypoAllergenic = true;
        bed18.inStock = true;
        bed18.purchaseDate = "16/02/2026";
        bed18.warrantyEnd = "16/02/2029";
        bed18.warrantyValid = true;
        bed18.brand = "Spaces";
        bed18.material = "Cotton Satin Stripe";
        bed18.size = "King";
        bed18.color = "Silver Grey";
        bed18.threadCount = 400;
        bed18.weaveType = "Satin Stripe";
        bed18.fittedSheet = true;
        bed18.pillowCaseCount = 2;
        bed18.weight = 1.7;
        bed18.careInstructions = "Gentle Machine Wash";
        bed18.machineWashable = true;
        bed18.fabricQuality = "High Gloss";
        bed18.gsm = 250;
        bed18.wrinkleResistant = true;
        bed18.patternDesign = "Fine Stripes";
        bed18.organicCotton = false;
        bed18.collectionName = "Elegance Series";
        bed18.discountPrice = 3199.99;
        bed18.storageMethod = "Linen Closet Shelf";
        
        System.out.println("Item Code: " + bed18.itemCode);
        System.out.println("Unit Price: " + bed18.unitPrice);
        System.out.println("Hypo Allergenic: " + bed18.hypoAllergenic);
        System.out.println("In Stock: " + bed18.inStock);
        System.out.println("Purchase Date: " + bed18.purchaseDate);
        System.out.println("Warranty Ends: " + bed18.warrantyEnd);
        System.out.println("Warranty Valid: " + bed18.warrantyValid);
        System.out.println("Brand: " + bed18.brand);
        System.out.println("Material: " + bed18.material);
        System.out.println("Size: " + bed18.size);
        System.out.println("Color: " + bed18.color);
        System.out.println("Thread Count: " + bed18.threadCount);
        System.out.println("Weave Type: " + bed18.weaveType);
        System.out.println("Fitted Sheet: " + bed18.fittedSheet);
        System.out.println("Pillow Case Count: " + bed18.pillowCaseCount);
        System.out.println("Weight: " + bed18.weight + "kg");
        System.out.println("Care Instructions: " + bed18.careInstructions);
        System.out.println("Machine Washable: " + bed18.machineWashable);
        System.out.println("Fabric Quality: " + bed18.fabricQuality);
        System.out.println("GSM: " + bed18.gsm);
        System.out.println("Wrinkle Resistant: " + bed18.wrinkleResistant);
        System.out.println("Pattern Design: " + bed18.patternDesign);
        System.out.println("Organic Cotton: " + bed18.organicCotton);
        System.out.println("Collection Name: " + bed18.collectionName);
        System.out.println("Discount Price: " + bed18.discountPrice);
        System.out.println("Storage Method: " + bed18.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed19 = new BedSheet();
        
        bed19.itemCode = 1519;
        bed19.unitPrice = 899.99;
        bed19.hypoAllergenic = true;
        bed19.inStock = true;
        bed19.purchaseDate = "15/02/2026";
        bed19.warrantyEnd = "15/02/2027";
        bed19.warrantyValid = true;
        bed19.brand = "Disney";
        bed19.material = "Soft Cotton";
        bed19.size = "Single";
        bed19.color = "Multi-Color";
        bed19.threadCount = 144;
        bed19.weaveType = "Printed";
        bed19.fittedSheet = true;
        bed19.pillowCaseCount = 1;
        bed19.weight = 0.9;
        bed19.careInstructions = "Warm Machine Wash";
        bed19.machineWashable = true;
        bed19.fabricQuality = "Child Safe";
        bed19.gsm = 140;
        bed19.wrinkleResistant = false;
        bed19.patternDesign = "Character Print";
        bed19.organicCotton = false;
        bed19.collectionName = "Kids Fun";
        bed19.discountPrice = 699.99;
        bed19.storageMethod = "Toy Box Storage";
        
        System.out.println("Item Code: " + bed19.itemCode);
        System.out.println("Unit Price: " + bed19.unitPrice);
        System.out.println("Hypo Allergenic: " + bed19.hypoAllergenic);
        System.out.println("In Stock: " + bed19.inStock);
        System.out.println("Purchase Date: " + bed19.purchaseDate);
        System.out.println("Warranty Ends: " + bed19.warrantyEnd);
        System.out.println("Warranty Valid: " + bed19.warrantyValid);
        System.out.println("Brand: " + bed19.brand);
        System.out.println("Material: " + bed19.material);
        System.out.println("Size: " + bed19.size);
        System.out.println("Color: " + bed19.color);
        System.out.println("Thread Count: " + bed19.threadCount);
        System.out.println("Weave Type: " + bed19.weaveType);
        System.out.println("Fitted Sheet: " + bed19.fittedSheet);
        System.out.println("Pillow Case Count: " + bed19.pillowCaseCount);
        System.out.println("Weight: " + bed19.weight + "kg");
        System.out.println("Care Instructions: " + bed19.careInstructions);
        System.out.println("Machine Washable: " + bed19.machineWashable);
        System.out.println("Fabric Quality: " + bed19.fabricQuality);
        System.out.println("GSM: " + bed19.gsm);
        System.out.println("Wrinkle Resistant: " + bed19.wrinkleResistant);
        System.out.println("Pattern Design: " + bed19.patternDesign);
        System.out.println("Organic Cotton: " + bed19.organicCotton);
        System.out.println("Collection Name: " + bed19.collectionName);
        System.out.println("Discount Price: " + bed19.discountPrice);
        System.out.println("Storage Method: " + bed19.storageMethod);
        System.out.println("-----------------------------");


        BedSheet bed20 = new BedSheet();
        
        bed20.itemCode = 1520;
        bed20.unitPrice = 1999.99;
        bed20.hypoAllergenic = false;
        bed20.inStock = true;
        bed20.purchaseDate = "14/02/2026";
        bed20.warrantyEnd = "14/02/2028";
        bed20.warrantyValid = true;
        bed20.brand = "Maspar";
        bed20.material = "Pure Cotton";
        bed20.size = "Double";
        bed20.color = "Festive Gold";
        bed20.threadCount = 250;
        bed20.weaveType = "Jacquard";
        bed20.fittedSheet = false;
        bed20.pillowCaseCount = 2;
        bed20.weight = 1.5;
        bed20.careInstructions = "Normal Wash";
        bed20.machineWashable = true;
        bed20.fabricQuality = "Festival Grade";
        bed20.gsm = 200;
        bed20.wrinkleResistant = false;
        bed20.patternDesign = "Traditional Motifs";
        bed20.organicCotton = false;
        bed20.collectionName = "Puja Special";
        bed20.discountPrice = 1599.99;
        bed20.storageMethod = "Festival Storage Box";
        
        System.out.println("Item Code: " + bed20.itemCode);
        System.out.println("Unit Price: " + bed20.unitPrice);
        System.out.println("Hypo Allergenic: " + bed20.hypoAllergenic);
        System.out.println("In Stock: " + bed20.inStock);
        System.out.println("Purchase Date: " + bed20.purchaseDate);
        System.out.println("Warranty Ends: " + bed20.warrantyEnd);
        System.out.println("Warranty Valid: " + bed20.warrantyValid);
        System.out.println("Brand: " + bed20.brand);
        System.out.println("Material: " + bed20.material);
        System.out.println("Size: " + bed20.size);
        System.out.println("Color: " + bed20.color);
        System.out.println("Thread Count: " + bed20.threadCount);
        System.out.println("Weave Type: " + bed20.weaveType);
        System.out.println("Fitted Sheet: " + bed20.fittedSheet);
        System.out.println("Pillow Case Count: " + bed20.pillowCaseCount);
        System.out.println("Weight: " + bed20.weight + "kg");
        System.out.println("Care Instructions: " + bed20.careInstructions);
        System.out.println("Machine Washable: " + bed20.machineWashable);
        System.out.println("Fabric Quality: " + bed20.fabricQuality);
        System.out.println("GSM: " + bed20.gsm);
        System.out.println("Wrinkle Resistant: " + bed20.wrinkleResistant);
        System.out.println("Pattern Design: " + bed20.patternDesign);
        System.out.println("Organic Cotton: " + bed20.organicCotton);
        System.out.println("Collection Name: " + bed20.collectionName);
        System.out.println("Discount Price: " + bed20.discountPrice);
        System.out.println("Storage Method: " + bed20.storageMethod);
        System.out.println("-----------------------------");





    }
}
