class BroadcastExecutor {
    public static void main(String[] prgms) {
	
        Broadcast bc1 = new Broadcast();
        bc1.setId(501);
        System.out.println("ID: " + bc1.getId());
        bc1.setName("PM Modi Address");
        System.out.println("Name: " + bc1.getName());
        bc1.setTime("8:00 PM");
        System.out.println("Time: " + bc1.getTime());
        bc1.setChannel("DD National");
        System.out.println("Channel: " + bc1.getChannel());
        bc1.setBroadcastBy("Doordarshan");
        System.out.println("Broadcast By: " + bc1.getBroadcastBy());
        bc1.setDate("2026-03-31");
        System.out.println("Date: " + bc1.getDate());
        bc1.setDuration("1hr");
        System.out.println("Duration: " + bc1.getDuration());
        System.out.println();

        Broadcast bc2 = new Broadcast();
        bc2.setId(723);
        System.out.println("ID: " + bc2.getId());
        bc2.setName("IPL Opening Ceremony");
        System.out.println("Name: " + bc2.getName());
        bc2.setTime("7:30 PM");
        System.out.println("Time: " + bc2.getTime());
        bc2.setChannel("Star Sports");
        System.out.println("Channel: " + bc2.getChannel());
        bc2.setBroadcastBy("Star Sports Network");
        System.out.println("Broadcast By: " + bc2.getBroadcastBy());
        bc2.setDate("2026-03-31");
        System.out.println("Date: " + bc2.getDate());
        bc2.setDuration("2hrs");
        System.out.println("Duration: " + bc2.getDuration());
        System.out.println();

        Broadcast bc3 = new Broadcast();
        bc3.setId(319);
        System.out.println("ID: " + bc3.getId());
        bc3.setName("Republic TV Debate");
        System.out.println("Name: " + bc3.getName());
        bc3.setTime("9:00 PM");
        System.out.println("Time: " + bc3.getTime());
        bc3.setChannel("Republic TV");
        System.out.println("Channel: " + bc3.getChannel());
        bc3.setBroadcastBy("Republic Media");
        System.out.println("Broadcast By: " + bc3.getBroadcastBy());
        bc3.setDate("2026-03-31");
        System.out.println("Date: " + bc3.getDate());
        bc3.setDuration("1hr");
        System.out.println("Duration: " + bc3.getDuration());
        System.out.println();

        Broadcast bc4 = new Broadcast();
        bc4.setId(847);
        System.out.println("ID: " + bc4.getId());
        bc4.setName("Taarak Mehta Episode");
        System.out.println("Name: " + bc4.getName());
        bc4.setTime("8:30 PM");
        System.out.println("Time: " + bc4.getTime());
        bc4.setChannel("Sony SAB");
        System.out.println("Channel: " + bc4.getChannel());
        bc4.setBroadcastBy("Neela Telefilms");
        System.out.println("Broadcast By: " + bc4.getBroadcastBy());
        bc4.setDate("2026-03-31");
        bc4.setDuration("30min");
        System.out.println("Duration: " + bc4.getDuration());
        System.out.println();

        Broadcast bc5 = new Broadcast();
        bc5.setId(642);
        System.out.println("ID: " + bc5.getId());
        bc5.setName("Bigg Boss Grand Finale");
        System.out.println("Name: " + bc5.getName());
        bc5.setTime("9:00 PM");
        System.out.println("Time: " + bc5.getTime());
        bc5.setChannel("Colors TV");
        System.out.println("Channel: " + bc5.getChannel());
        bc5.setBroadcastBy("Endemol Shine India");
        System.out.println("Broadcast By: " + bc5.getBroadcastBy());
        bc5.setDate("2026-03-31");
        System.out.println("Date: " + bc5.getDate());
        bc5.setDuration("3hrs");
        System.out.println("Duration: " + bc5.getDuration());
        System.out.println();

        Broadcast bc6 = new Broadcast();
        bc6.setId(928);
        System.out.println("ID: " + bc6.getId());
        bc6.setName("India vs Australia T20");
        System.out.println("Name: " + bc6.getName());
        bc6.setTime("7:30 PM");
        System.out.println("Time: " + bc6.getTime());
        bc6.setChannel("Sony Sports");
        System.out.println("Channel: " + bc6.getChannel());
        bc6.setBroadcastBy("Sony Pictures Networks");
        System.out.println("Broadcast By: " + bc6.getBroadcastBy());
        bc6.setDate("2026-03-31");
        System.out.println("Date: " + bc6.getDate());
        bc6.setDuration("3hrs");
        System.out.println("Duration: " + bc6.getDuration());
        System.out.println();

        Broadcast bc7 = new Broadcast();
        bc7.setId(375);
        System.out.println("ID: " + bc7.getId());
        bc7.setName("Anupamaa Episode");
        System.out.println("Name: " + bc7.getName());
        bc7.setTime("10:00 PM");
        System.out.println("Time: " + bc7.getTime());
        bc7.setChannel("Star Plus");
        System.out.println("Channel: " + bc7.getChannel());
        bc7.setBroadcastBy("Rajshri Productions");
        System.out.println("Broadcast By: " + bc7.getBroadcastBy());
        bc7.setDate("2026-03-31");
        System.out.println("Date: " + bc7.getDate());
        bc7.setDuration("30min");
        System.out.println("Duration: " + bc7.getDuration());
        System.out.println();

        Broadcast bc8 = new Broadcast();
        bc8.setId(156);
        System.out.println("ID: " + bc8.getId());
        bc8.setName("NewsHour Debate");
        System.out.println("Name: " + bc8.getName());
        bc8.setTime("10:00 PM");
        System.out.println("Time: " + bc8.getTime());
        bc8.setChannel("Times Now");
        System.out.println("Channel: " + bc8.getChannel());
        bc8.setBroadcastBy("Times Network");
        System.out.println("Broadcast By: " + bc8.getBroadcastBy());
        bc8.setDate("2026-03-31");
        System.out.println("Date: " + bc8.getDate());
        bc8.setDuration("1hr");
        System.out.println("Duration: " + bc8.getDuration());
        System.out.println();

        Broadcast bc9 = new Broadcast();
        bc9.setId(784);
        System.out.println("ID: " + bc9.getId());
        bc9.setName("Yeh Rishta Kya Kehlata Hai");
        System.out.println("Name: " + bc9.getName());
        bc9.setTime("9:30 PM");
        System.out.println("Time: " + bc9.getTime());
        bc9.setChannel("Star Plus");
        System.out.println("Channel: " + bc9.getChannel());
        bc9.setBroadcastBy("Director's Kut Productions");
        System.out.println("Broadcast By: " + bc9.getBroadcastBy());
        bc9.setDate("2026-03-31");
        System.out.println("Date: " + bc9.getDate());
        bc9.setDuration("30min");
        System.out.println("Duration: " + bc9.getDuration());
        System.out.println();

        Broadcast bc10 = new Broadcast();
        bc10.setId(293);
        System.out.println("ID: " + bc10.getId());
        bc10.setName("Aaj Tak Prime Time");
        System.out.println("Name: " + bc10.getName());
        bc10.setTime("8:00 PM");
        System.out.println("Time: " + bc10.getTime());
        bc10.setChannel("Aaj Tak");
        System.out.println("Channel: " + bc10.getChannel());
        bc10.setBroadcastBy("Living India Media");
        System.out.println("Broadcast By: " + bc10.getBroadcastBy());
        bc10.setDate("2026-03-31");
        System.out.println("Date: " + bc10.getDate());
        bc10.setDuration("1hr");
        System.out.println("Duration: " + bc10.getDuration());
        System.out.println();

        Broadcast bc11 = new Broadcast();
        bc11.setId(671);
        System.out.println("ID: " + bc11.getId());
        bc11.setName("KBC Episode 45");
        System.out.println("Name: " + bc11.getName());
        bc11.setTime("9:00 PM");
        System.out.println("Time: " + bc11.getTime());
        bc11.setChannel("Sony Entertainment");
        System.out.println("Channel: " + bc11.getChannel());
        bc11.setBroadcastBy("Sony Pictures Television");
        System.out.println("Broadcast By: " + bc11.getBroadcastBy());
        bc11.setDate("2026-03-31");
        System.out.println("Date: " + bc11.getDate());
        bc11.setDuration("1hr");
        System.out.println("Duration: " + bc11.getDuration());
        System.out.println();

        Broadcast bc12 = new Broadcast();
        bc12.setId(419);
        System.out.println("ID: " + bc12.getId());
        bc12.setName("India News Headlines");
        System.out.println("Name: " + bc12.getName());
        bc12.setTime("7:00 PM");
        System.out.println("Time: " + bc12.getTime());
        bc12.setChannel("India News");
        System.out.println("Channel: " + bc12.getChannel());
        bc12.setBroadcastBy("India News Pvt Ltd");
        System.out.println("Broadcast By: " + bc12.getBroadcastBy());
        bc12.setDate("2026-03-31");
        System.out.println("Date: " + bc12.getDate());
        bc12.setDuration("30min");
        System.out.println("Duration: " + bc12.getDuration());
        System.out.println();

        Broadcast bc13 = new Broadcast();
        bc13.setId(958);
        System.out.println("ID: " + bc13.getId());
        bc13.setName("Shark Tank India Pitch");
        System.out.println("Name: " + bc13.getName());
        bc13.setTime("8:00 PM");
        System.out.println("Time: " + bc13.getTime());
        bc13.setChannel("Sony LIV");
        System.out.println("Channel: " + bc13.getChannel());
        bc13.setBroadcastBy("Sony Pictures Networks");
        System.out.println("Broadcast By: " + bc13.getBroadcastBy());
        bc13.setDate("2026-03-31");
        System.out.println("Date: " + bc13.getDate());
        bc13.setDuration("1hr");
        System.out.println("Duration: " + bc13.getDuration());
        System.out.println();

        Broadcast bc14 = new Broadcast();
        bc14.setId(267);
        System.out.println("ID: " + bc14.getId());
        bc14.setName("CID Special Episode");
        System.out.println("Name: " + bc14.getName());
        bc14.setTime("10:30 PM");
        System.out.println("Time: " + bc14.getTime());
        bc14.setChannel("Sony Max");
        System.out.println("Channel: " + bc14.getChannel());
        bc14.setBroadcastBy("Fireworks Productions");
        System.out.println("Broadcast By: " + bc14.getBroadcastBy());
        bc14.setDate("2026-03-31");
        System.out.println("Date: " + bc14.getDate());
        bc14.setDuration("45min");
        System.out.println("Duration: " + bc14.getDuration());
        System.out.println();

        Broadcast bc15 = new Broadcast();
        bc15.setId(835);
        System.out.println("ID: " + bc15.getId());
        bc15.setName("Election Results Update");
        System.out.println("Name: " + bc15.getName());
        bc15.setTime("11:00 PM");
        System.out.println("Time: " + bc15.getTime());
        bc15.setChannel("NDTV 24x7");
        System.out.println("Channel: " + bc15.getChannel());
        bc15.setBroadcastBy("NDTV Group");
        System.out.println("Broadcast By: " + bc15.getBroadcastBy());
        bc15.setDate("2026-03-31");
        System.out.println("Date: " + bc15.getDate());
        bc15.setDuration("2hrs");
        System.out.println("Duration: " + bc15.getDuration());
        System.out.println();
		
		Broadcast bc23 = new Broadcast();
        bc23.setId(128);
        System.out.println("ID: " + bc23.getId());
        bc23.setName("Naagin 7 Episode");
        System.out.println("Name: " + bc23.getName());
        bc23.setTime("8:00 PM");
        System.out.println("Time: " + bc23.getTime());
        bc23.setChannel("Colors TV");
        System.out.println("Channel: " + bc23.getChannel());
        bc23.setBroadcastBy("Balaji Telefilms");
        System.out.println("Broadcast By: " + bc23.getBroadcastBy());
        bc23.setDate("2026-03-31");
        System.out.println("Date: " + bc23.getDate());
        bc23.setDuration("45min");
        System.out.println("Duration: " + bc23.getDuration());
        System.out.println();

        Broadcast bc24 = new Broadcast();
        bc24.setId(964);
        System.out.println("ID: " + bc24.getId());
        bc24.setName("India vs South Africa Test");
        System.out.println("Name: " + bc24.getName());
        bc24.setTime("11:00 AM");
        System.out.println("Time: " + bc24.getTime());
        bc24.setChannel("Star Sports");
        System.out.println("Channel: " + bc24.getChannel());
        bc24.setBroadcastBy("Star Sports Network");
        System.out.println("Broadcast By: " + bc24.getBroadcastBy());
        bc24.setDate("2026-03-31");
        System.out.println("Date: " + bc24.getDate());
        bc24.setDuration("6hrs");
        System.out.println("Duration: " + bc24.getDuration());
        System.out.println();

        Broadcast bc25 = new Broadcast();
        bc25.setId(306);
        System.out.println("ID: " + bc25.getId());
        bc25.setName("Imlie Episode 450");
        System.out.println("Name: " + bc25.getName());
        bc25.setTime("6:30 PM");
        System.out.println("Time: " + bc25.getTime());
        bc25.setChannel("Star Plus");
        System.out.println("Channel: " + bc25.getChannel());
        bc25.setBroadcastBy("Triangle Film Company");
        System.out.println("Broadcast By: " + bc25.getBroadcastBy());
        bc25.setDate("2026-03-31");
        System.out.println("Date: " + bc25.getDate());
        bc25.setDuration("30min");
        System.out.println("Duration: " + bc25.getDuration());
        System.out.println();

        Broadcast bc26 = new Broadcast();
        bc26.setId(817);
        System.out.println("ID: " + bc26.getId());
        bc26.setName("India TV Special Report");
        System.out.println("Name: " + bc26.getName());
        bc26.setTime("7:00 PM");
        System.out.println("Time: " + bc26.getTime());
        bc26.setChannel("India TV");
        System.out.println("Channel: " + bc26.getChannel());
        bc26.setBroadcastBy("India TV Network");
        System.out.println("Broadcast By: " + bc26.getBroadcastBy());
        bc26.setDate("2026-03-31");
        System.out.println("Date: " + bc26.getDate());
        bc26.setDuration("1hr");
        System.out.println("Duration: " + bc26.getDuration());
        System.out.println();

        Broadcast bc27 = new Broadcast();
        bc27.setId(543);
        System.out.println("ID: " + bc27.getId());
        bc27.setName("Dance India Dance");
        System.out.println("Name: " + bc27.getName());
        bc27.setTime("9:00 PM");
        System.out.println("Time: " + bc27.getTime());
        bc27.setChannel("Zee TV");
        System.out.println("Channel: " + bc27.getChannel());
        bc27.setBroadcastBy("Urban Brew Studios");
        System.out.println("Broadcast By: " + bc27.getBroadcastBy());
        bc27.setDate("2026-03-31");
        System.out.println("Date: " + bc27.getDate());
        bc27.setDuration("1hr 30min");
        System.out.println("Duration: " + bc27.getDuration());
        System.out.println();

        Broadcast bc28 = new Broadcast();
        bc28.setId(729);
        System.out.println("ID: " + bc28.getId());
        bc28.setName("Pandya Store Episode");
        System.out.println("Name: " + bc28.getName());
        bc28.setTime("7:15 PM");
        System.out.println("Time: " + bc28.getTime());
        bc28.setChannel("Star Plus");
        System.out.println("Channel: " + bc28.getChannel());
        bc28.setBroadcastBy("Sphere Origins");
        System.out.println("Broadcast By: " + bc28.getBroadcastBy());
        bc28.setDate("2026-03-31");
        System.out.println("Date: " + bc28.getDate());
        bc28.setDuration("30min");
        System.out.println("Duration: " + bc28.getDuration());
        System.out.println();

        Broadcast bc29 = new Broadcast();
        bc29.setId(182);
        System.out.println("ID: " + bc29.getId());
        bc29.setName("Zee News Breaking News");
        System.out.println("Name: " + bc29.getName());
        bc29.setTime("11:00 PM");
        System.out.println("Time: " + bc29.getTime());
        bc29.setChannel("Zee News");
        System.out.println("Channel: " + bc29.getChannel());
        bc29.setBroadcastBy("Zee Media Corporation");
        System.out.println("Broadcast By: " + bc29.getBroadcastBy());
        bc29.setDate("2026-03-31");
        System.out.println("Date: " + bc29.getDate());
        bc29.setDuration("1hr");
        System.out.println("Duration: " + bc29.getDuration());
        System.out.println();
		}
		
		}
		
       