class CarBrandExecutor {
    public static void main(String[] args) {
        CarBrand brand1 = new CarBrand();
        brand1.brandId = 1;
        brand1.brandName = "Maruti Suzuki";
        brand1.country = "India";
        brand1.foundedYear = 1981;
        brand1.ceoName = "Hisashi Takeuchi";
        brand1.revenue = 12500000000.00;
        brand1.electricCars = true;
        brand1.headquarters = "New Delhi";
        brand1.modelsCount = 17;
        brand1.luxurySegment = "Economy";
        brand1.indianBrand = true;
        brand1.marketShare = 42.5;
        brand1.factoriesCount = 5;
        brand1.popularModel = "Swift";
        brand1.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand1.brandId);
        System.out.println("Brand Name: " + brand1.brandName);
        System.out.println("Country: " + brand1.country);
        System.out.println("Founded Year: " + brand1.foundedYear);
        System.out.println("CEO Name: " + brand1.ceoName);
        System.out.println("Revenue: " + brand1.revenue);
        System.out.println("Electric Cars: " + brand1.electricCars);
        System.out.println("Headquarters: " + brand1.headquarters);
        System.out.println("Models Count: " + brand1.modelsCount);
        System.out.println("Luxury Segment: " + brand1.luxurySegment);
        System.out.println("Indian Brand: " + brand1.indianBrand);
        System.out.println("Market Share: " + brand1.marketShare);
        System.out.println("Factories Count: " + brand1.factoriesCount);
        System.out.println("Popular Model: " + brand1.popularModel);
        System.out.println("Sponsor Sports: " + brand1.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand2 = new CarBrand();
        brand2.brandId = 2;
        brand2.brandName = "Tata Motors";
        brand2.country = "India";
        brand2.foundedYear = 1945;
        brand2.ceoName = "N. Chandrasekaran";
        brand2.revenue = 38500000000.00;
        brand2.electricCars = true;
        brand2.headquarters = "Mumbai";
        brand2.modelsCount = 12;
        brand2.luxurySegment = "Premium";
        brand2.indianBrand = true;
        brand2.marketShare = 14.2;
        brand2.factoriesCount = 8;
        brand2.popularModel = "Nexon";
        brand2.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand2.brandId);
        System.out.println("Brand Name: " + brand2.brandName);
        System.out.println("Country: " + brand2.country);
        System.out.println("Founded Year: " + brand2.foundedYear);
        System.out.println("CEO Name: " + brand2.ceoName);
        System.out.println("Revenue: " + brand2.revenue);
        System.out.println("Electric Cars: " + brand2.electricCars);
        System.out.println("Headquarters: " + brand2.headquarters);
        System.out.println("Models Count: " + brand2.modelsCount);
        System.out.println("Luxury Segment: " + brand2.luxurySegment);
        System.out.println("Indian Brand: " + brand2.indianBrand);
        System.out.println("Market Share: " + brand2.marketShare);
        System.out.println("Factories Count: " + brand2.factoriesCount);
        System.out.println("Popular Model: " + brand2.popularModel);
        System.out.println("Sponsor Sports: " + brand2.sponsorSports);
        System.out.println("-----------------------------");
		
		
		        CarBrand brand3 = new CarBrand();
        brand3.brandId = 3;
        brand3.brandName = "Hyundai";
        brand3.country = "South Korea";
        brand3.foundedYear = 1967;
        brand3.ceoName = "Chang Jae-Hoon";
        brand3.revenue = 152000000000.00;
        brand3.electricCars = true;
        brand3.headquarters = "Seoul";
        brand3.modelsCount = 10;
        brand3.luxurySegment = "Premium";
        brand3.indianBrand = false;
        brand3.marketShare = 12.7;
        brand3.factoriesCount = 2;
        brand3.popularModel = "Creta";
        brand3.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand3.brandId);
        System.out.println("Brand Name: " + brand3.brandName);
        System.out.println("Country: " + brand3.country);
        System.out.println("Founded Year: " + brand3.foundedYear);
        System.out.println("CEO Name: " + brand3.ceoName);
        System.out.println("Revenue: " + brand3.revenue);
        System.out.println("Electric Cars: " + brand3.electricCars);
        System.out.println("Headquarters: " + brand3.headquarters);
        System.out.println("Models Count: " + brand3.modelsCount);
        System.out.println("Luxury Segment: " + brand3.luxurySegment);
        System.out.println("Indian Brand: " + brand3.indianBrand);
        System.out.println("Market Share: " + brand3.marketShare);
        System.out.println("Factories Count: " + brand3.factoriesCount);
        System.out.println("Popular Model: " + brand3.popularModel);
        System.out.println("Sponsor Sports: " + brand3.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand4 = new CarBrand();
        brand4.brandId = 4;
        brand4.brandName = "Mahindra";
        brand4.country = "India";
        brand4.foundedYear = 1945;
        brand4.ceoName = "Anish Shah";
        brand4.revenue = 13500000000.00;
        brand4.electricCars = true;
        brand4.headquarters = "Mumbai";
        brand4.modelsCount = 8;
        brand4.luxurySegment = "SUV";
        brand4.indianBrand = true;
        brand4.marketShare = 14.4;
        brand4.factoriesCount = 10;
        brand4.popularModel = "XUV700";
        brand4.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand4.brandId);
        System.out.println("Brand Name: " + brand4.brandName);
        System.out.println("Country: " + brand4.country);
        System.out.println("Founded Year: " + brand4.foundedYear);
        System.out.println("CEO Name: " + brand4.ceoName);
        System.out.println("Revenue: " + brand4.revenue);
        System.out.println("Electric Cars: " + brand4.electricCars);
        System.out.println("Headquarters: " + brand4.headquarters);
        System.out.println("Models Count: " + brand4.modelsCount);
        System.out.println("Luxury Segment: " + brand4.luxurySegment);
        System.out.println("Indian Brand: " + brand4.indianBrand);
        System.out.println("Market Share: " + brand4.marketShare);
        System.out.println("Factories Count: " + brand4.factoriesCount);
        System.out.println("Popular Model: " + brand4.popularModel);
        System.out.println("Sponsor Sports: " + brand4.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand5 = new CarBrand();
        brand5.brandId = 5;
        brand5.brandName = "Toyota";
        brand5.country = "Japan";
        brand5.foundedYear = 1937;
        brand5.ceoName = "Koji Sato";
        brand5.revenue = 275000000000.00;
        brand5.electricCars = true;
        brand5.headquarters = "Toyota City";
        brand5.modelsCount = 15;
        brand5.luxurySegment = "Premium";
        brand5.indianBrand = false;
        brand5.marketShare = 8.4;
        brand5.factoriesCount = 1;
        brand5.popularModel = "Innova";
        brand5.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand5.brandId);
        System.out.println("Brand Name: " + brand5.brandName);
        System.out.println("Country: " + brand5.country);
        System.out.println("Founded Year: " + brand5.foundedYear);
        System.out.println("CEO Name: " + brand5.ceoName);
        System.out.println("Revenue: " + brand5.revenue);
        System.out.println("Electric Cars: " + brand5.electricCars);
        System.out.println("Headquarters: " + brand5.headquarters);
        System.out.println("Models Count: " + brand5.modelsCount);
        System.out.println("Luxury Segment: " + brand5.luxurySegment);
        System.out.println("Indian Brand: " + brand5.indianBrand);
        System.out.println("Market Share: " + brand5.marketShare);
        System.out.println("Factories Count: " + brand5.factoriesCount);
        System.out.println("Popular Model: " + brand5.popularModel);
        System.out.println("Sponsor Sports: " + brand5.sponsorSports);
        System.out.println("-----------------------------");

	        CarBrand brand6 = new CarBrand();
        brand6.brandId = 6;
        brand6.brandName = "Kia";
        brand6.country = "South Korea";
        brand6.foundedYear = 1944;
        brand6.ceoName = "Ho-sung Song";
        brand6.revenue = 85000000000.00;
        brand6.electricCars = true;
        brand6.headquarters = "Seoul";
        brand6.modelsCount = 9;
        brand6.luxurySegment = "Premium";
        brand6.indianBrand = false;
        brand6.marketShare = 6.8;
        brand6.factoriesCount = 1;
        brand6.popularModel = "Seltos";
        brand6.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand6.brandId);
        System.out.println("Brand Name: " + brand6.brandName);
        System.out.println("Country: " + brand6.country);
        System.out.println("Founded Year: " + brand6.foundedYear);
        System.out.println("CEO Name: " + brand6.ceoName);
        System.out.println("Revenue: " + brand6.revenue);
        System.out.println("Electric Cars: " + brand6.electricCars);
        System.out.println("Headquarters: " + brand6.headquarters);
        System.out.println("Models Count: " + brand6.modelsCount);
        System.out.println("Luxury Segment: " + brand6.luxurySegment);
        System.out.println("Indian Brand: " + brand6.indianBrand);
        System.out.println("Market Share: " + brand6.marketShare);
        System.out.println("Factories Count: " + brand6.factoriesCount);
        System.out.println("Popular Model: " + brand6.popularModel);
        System.out.println("Sponsor Sports: " + brand6.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand7 = new CarBrand();
        brand7.brandId = 7;
        brand7.brandName = "Nissan";
        brand7.country = "Japan";
        brand7.foundedYear = 1933;
        brand7.ceoName = "Makoto Uchida";
        brand7.revenue = 73000000000.00;
        brand7.electricCars = true;
        brand7.headquarters = "Yokohama";
        brand7.modelsCount = 11;
        brand7.luxurySegment = "Mid-range";
        brand7.indianBrand = false;
        brand7.marketShare = 2.1;
        brand7.factoriesCount = 1;
        brand7.popularModel = "Magnite";
        brand7.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand7.brandId);
        System.out.println("Brand Name: " + brand7.brandName);
        System.out.println("Country: " + brand7.country);
        System.out.println("Founded Year: " + brand7.foundedYear);
        System.out.println("CEO Name: " + brand7.ceoName);
        System.out.println("Revenue: " + brand7.revenue);
        System.out.println("Electric Cars: " + brand7.electricCars);
        System.out.println("Headquarters: " + brand7.headquarters);
        System.out.println("Models Count: " + brand7.modelsCount);
        System.out.println("Luxury Segment: " + brand7.luxurySegment);
        System.out.println("Indian Brand: " + brand7.indianBrand);
        System.out.println("Market Share: " + brand7.marketShare);
        System.out.println("Factories Count: " + brand7.factoriesCount);
        System.out.println("Popular Model: " + brand7.popularModel);
        System.out.println("Sponsor Sports: " + brand7.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand8 = new CarBrand();
        brand8.brandId = 8;
        brand8.brandName = "MG Motor";
        brand8.country = "China/UK";
        brand8.foundedYear = 1924;
        brand8.ceoName = "Ravi Bhargava";
        brand8.revenue = 4500000000.00;
        brand8.electricCars = true;
        brand8.headquarters = "Gurugram";
        brand8.modelsCount = 6;
        brand8.luxurySegment = "Premium";
        brand8.indianBrand = false;
        brand8.marketShare = 3.2;
        brand8.factoriesCount = 1;
        brand8.popularModel = "Hector";
        brand8.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand8.brandId);
        System.out.println("Brand Name: " + brand8.brandName);
        System.out.println("Country: " + brand8.country);
        System.out.println("Founded Year: " + brand8.foundedYear);
        System.out.println("CEO Name: " + brand8.ceoName);
        System.out.println("Revenue: " + brand8.revenue);
        System.out.println("Electric Cars: " + brand8.electricCars);
        System.out.println("Headquarters: " + brand8.headquarters);
        System.out.println("Models Count: " + brand8.modelsCount);
        System.out.println("Luxury Segment: " + brand8.luxurySegment);
        System.out.println("Indian Brand: " + brand8.indianBrand);
        System.out.println("Market Share: " + brand8.marketShare);
        System.out.println("Factories Count: " + brand8.factoriesCount);
        System.out.println("Popular Model: " + brand8.popularModel);
        System.out.println("Sponsor Sports: " + brand8.sponsorSports);
        System.out.println("-----------------------------");
	
	        CarBrand brand9 = new CarBrand();
        brand9.brandId = 9;
        brand9.brandName = "Honda";
        brand9.country = "Japan";
        brand9.foundedYear = 1948;
        brand9.ceoName = "Toshihiro Mibe";
        brand9.revenue = 135000000000.00;
        brand9.electricCars = true;
        brand9.headquarters = "Tokyo";
        brand9.modelsCount = 8;
        brand9.luxurySegment = "Premium";
        brand9.indianBrand = false;
        brand9.marketShare = 2.8;
        brand9.factoriesCount = 1;
        brand9.popularModel = "City";
        brand9.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand9.brandId);
        System.out.println("Brand Name: " + brand9.brandName);
        System.out.println("Country: " + brand9.country);
        System.out.println("Founded Year: " + brand9.foundedYear);
        System.out.println("CEO Name: " + brand9.ceoName);
        System.out.println("Revenue: " + brand9.revenue);
        System.out.println("Electric Cars: " + brand9.electricCars);
        System.out.println("Headquarters: " + brand9.headquarters);
        System.out.println("Models Count: " + brand9.modelsCount);
        System.out.println("Luxury Segment: " + brand9.luxurySegment);
        System.out.println("Indian Brand: " + brand9.indianBrand);
        System.out.println("Market Share: " + brand9.marketShare);
        System.out.println("Factories Count: " + brand9.factoriesCount);
        System.out.println("Popular Model: " + brand9.popularModel);
        System.out.println("Sponsor Sports: " + brand9.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand10 = new CarBrand();
        brand10.brandId = 10;
        brand10.brandName = "Renault";
        brand10.country = "France";
        brand10.foundedYear = 1899;
        brand10.ceoName = "Luca de Meo";
        brand10.revenue = 55000000000.00;
        brand10.electricCars = true;
        brand10.headquarters = "Boulogne-Billancourt";
        brand10.modelsCount = 7;
        brand10.luxurySegment = "Economy";
        brand10.indianBrand = false;
        brand10.marketShare = 1.5;
        brand10.factoriesCount = 1;
        brand10.popularModel = "Kwid";
        brand10.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand10.brandId);
        System.out.println("Brand Name: " + brand10.brandName);
        System.out.println("Country: " + brand10.country);
        System.out.println("Founded Year: " + brand10.foundedYear);
        System.out.println("CEO Name: " + brand10.ceoName);
        System.out.println("Revenue: " + brand10.revenue);
        System.out.println("Electric Cars: " + brand10.electricCars);
        System.out.println("Headquarters: " + brand10.headquarters);
        System.out.println("Models Count: " + brand10.modelsCount);
        System.out.println("Luxury Segment: " + brand10.luxurySegment);
        System.out.println("Indian Brand: " + brand10.indianBrand);
        System.out.println("Market Share: " + brand10.marketShare);
        System.out.println("Factories Count: " + brand10.factoriesCount);
        System.out.println("Popular Model: " + brand10.popularModel);
        System.out.println("Sponsor Sports: " + brand10.sponsorSports);
        System.out.println("-----------------------------");
	
	        CarBrand brand11 = new CarBrand();
        brand11.brandId = 11;
        brand11.brandName = "Volkswagen";
        brand11.country = "Germany";
        brand11.foundedYear = 1937;
        brand11.ceoName = "Oliver Blume";
        brand11.revenue = 293000000000.00;
        brand11.electricCars = true;
        brand11.headquarters = "Wolfsburg";
        brand11.modelsCount = 12;
        brand11.luxurySegment = "Premium";
        brand11.indianBrand = false;
        brand11.marketShare = 2.3;
        brand11.factoriesCount = 1;
        brand11.popularModel = "Virtus";
        brand11.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand11.brandId);
        System.out.println("Brand Name: " + brand11.brandName);
        System.out.println("Country: " + brand11.country);
        System.out.println("Founded Year: " + brand11.foundedYear);
        System.out.println("CEO Name: " + brand11.ceoName);
        System.out.println("Revenue: " + brand11.revenue);
        System.out.println("Electric Cars: " + brand11.electricCars);
        System.out.println("Headquarters: " + brand11.headquarters);
        System.out.println("Models Count: " + brand11.modelsCount);
        System.out.println("Luxury Segment: " + brand11.luxurySegment);
        System.out.println("Indian Brand: " + brand11.indianBrand);
        System.out.println("Market Share: " + brand11.marketShare);
        System.out.println("Factories Count: " + brand11.factoriesCount);
        System.out.println("Popular Model: " + brand11.popularModel);
        System.out.println("Sponsor Sports: " + brand11.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand12 = new CarBrand();
        brand12.brandId = 12;
        brand12.brandName = "Skoda";
        brand12.country = "Czech Republic";
        brand12.foundedYear = 1895;
        brand12.ceoName = "Klaus-Dieter Schulten";
        brand12.revenue = 28000000000.00;
        brand12.electricCars = true;
        brand12.headquarters = "Mlada Boleslav";
        brand12.modelsCount = 5;
        brand12.luxurySegment = "Premium";
        brand12.indianBrand = false;
        brand12.marketShare = 1.8;
        brand12.factoriesCount = 1;
        brand12.popularModel = "Kushaq";
        brand12.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand12.brandId);
        System.out.println("Brand Name: " + brand12.brandName);
        System.out.println("Country: " + brand12.country);
        System.out.println("Founded Year: " + brand12.foundedYear);
        System.out.println("CEO Name: " + brand12.ceoName);
        System.out.println("Revenue: " + brand12.revenue);
        System.out.println("Electric Cars: " + brand12.electricCars);
        System.out.println("Headquarters: " + brand12.headquarters);
        System.out.println("Models Count: " + brand12.modelsCount);
        System.out.println("Luxury Segment: " + brand12.luxurySegment);
        System.out.println("Indian Brand: " + brand12.indianBrand);
        System.out.println("Market Share: " + brand12.marketShare);
        System.out.println("Factories Count: " + brand12.factoriesCount);
        System.out.println("Popular Model: " + brand12.popularModel);
        System.out.println("Sponsor Sports: " + brand12.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand13 = new CarBrand();
        brand13.brandId = 13;
        brand13.brandName = "Citroen";
        brand13.country = "France";
        brand13.foundedYear = 1919;
        brand13.ceoName = "Vincent Cobee";
        brand13.revenue = 45000000000.00;
        brand13.electricCars = true;
        brand13.headquarters = "Stellantis Paris";
        brand13.modelsCount = 4;
        brand13.luxurySegment = "Economy";
        brand13.indianBrand = false;
        brand13.marketShare = 0.9;
        brand13.factoriesCount = 1;
        brand13.popularModel = "C3";
        brand13.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand13.brandId);
        System.out.println("Brand Name: " + brand13.brandName);
        System.out.println("Country: " + brand13.country);
        System.out.println("Founded Year: " + brand13.foundedYear);
        System.out.println("CEO Name: " + brand13.ceoName);
        System.out.println("Revenue: " + brand13.revenue);
        System.out.println("Electric Cars: " + brand13.electricCars);
        System.out.println("Headquarters: " + brand13.headquarters);
        System.out.println("Models Count: " + brand13.modelsCount);
        System.out.println("Luxury Segment: " + brand13.luxurySegment);
        System.out.println("Indian Brand: " + brand13.indianBrand);
        System.out.println("Market Share: " + brand13.marketShare);
        System.out.println("Factories Count: " + brand13.factoriesCount);
        System.out.println("Popular Model: " + brand13.popularModel);
        System.out.println("Sponsor Sports: " + brand13.sponsorSports);
        System.out.println("-----------------------------");
	
	        CarBrand brand14 = new CarBrand();
        brand14.brandId = 14;
        brand14.brandName = "Ford";
        brand14.country = "USA";
        brand14.foundedYear = 1903;
        brand14.ceoName = "Jim Farley";
        brand14.revenue = 158000000000.00;
        brand14.electricCars = true;
        brand14.headquarters = "Dearborn";
        brand14.modelsCount = 6;
        brand14.luxurySegment = "Premium";
        brand14.indianBrand = false;
        brand14.marketShare = 1.2;
        brand14.factoriesCount = 1;
        brand14.popularModel = "Endeavour";
        brand14.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand14.brandId);
        System.out.println("Brand Name: " + brand14.brandName);
        System.out.println("Country: " + brand14.country);
        System.out.println("Founded Year: " + brand14.foundedYear);
        System.out.println("CEO Name: " + brand14.ceoName);
        System.out.println("Revenue: " + brand14.revenue);
        System.out.println("Electric Cars: " + brand14.electricCars);
        System.out.println("Headquarters: " + brand14.headquarters);
        System.out.println("Models Count: " + brand14.modelsCount);
        System.out.println("Luxury Segment: " + brand14.luxurySegment);
        System.out.println("Indian Brand: " + brand14.indianBrand);
        System.out.println("Market Share: " + brand14.marketShare);
        System.out.println("Factories Count: " + brand14.factoriesCount);
        System.out.println("Popular Model: " + brand14.popularModel);
        System.out.println("Sponsor Sports: " + brand14.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand15 = new CarBrand();
        brand15.brandId = 15;
        brand15.brandName = "Jeep";
        brand15.country = "USA";
        brand15.foundedYear = 1941;
        brand15.ceoName = "Antonio Filosa";
        brand15.revenue = 45000000000.00;
        brand15.electricCars = true;
        brand15.headquarters = "Toledo";
        brand15.modelsCount = 5;
        brand15.luxurySegment = "SUV";
        brand15.indianBrand = false;
        brand15.marketShare = 0.8;
        brand15.factoriesCount = 1;
        brand15.popularModel = "Compass";
        brand15.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand15.brandId);
        System.out.println("Brand Name: " + brand15.brandName);
        System.out.println("Country: " + brand15.country);
        System.out.println("Founded Year: " + brand15.foundedYear);
        System.out.println("CEO Name: " + brand15.ceoName);
        System.out.println("Revenue: " + brand15.revenue);
        System.out.println("Electric Cars: " + brand15.electricCars);
        System.out.println("Headquarters: " + brand15.headquarters);
        System.out.println("Models Count: " + brand15.modelsCount);
        System.out.println("Luxury Segment: " + brand15.luxurySegment);
        System.out.println("Indian Brand: " + brand15.indianBrand);
        System.out.println("Market Share: " + brand15.marketShare);
        System.out.println("Factories Count: " + brand15.factoriesCount);
        System.out.println("Popular Model: " + brand15.popularModel);
        System.out.println("Sponsor Sports: " + brand15.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand16 = new CarBrand();
        brand16.brandId = 16;
        brand16.brandName = "BYD";
        brand16.country = "China";
        brand16.foundedYear = 1995;
        brand16.ceoName = "Wang Chuanfu";
        brand16.revenue = 85000000000.00;
        brand16.electricCars = true;
        brand16.headquarters = "Shenzhen";
        brand16.modelsCount = 10;
        brand16.luxurySegment = "Electric";
        brand16.indianBrand = false;
        brand16.marketShare = 0.5;
        brand16.factoriesCount = 1;
        brand16.popularModel = "Atto 3";
        brand16.sponsorSports = false;
        
        System.out.println("Brand ID: " + brand16.brandId);
        System.out.println("Brand Name: " + brand16.brandName);
        System.out.println("Country: " + brand16.country);
        System.out.println("Founded Year: " + brand16.foundedYear);
        System.out.println("CEO Name: " + brand16.ceoName);
        System.out.println("Revenue: " + brand16.revenue);
        System.out.println("Electric Cars: " + brand16.electricCars);
        System.out.println("Headquarters: " + brand16.headquarters);
        System.out.println("Models Count: " + brand16.modelsCount);
        System.out.println("Luxury Segment: " + brand16.luxurySegment);
        System.out.println("Indian Brand: " + brand16.indianBrand);
        System.out.println("Market Share: " + brand16.marketShare);
        System.out.println("Factories Count: " + brand16.factoriesCount);
        System.out.println("Popular Model: " + brand16.popularModel);
        System.out.println("Sponsor Sports: " + brand16.sponsorSports);
        System.out.println("-----------------------------");
	
	        CarBrand brand17 = new CarBrand();
        brand17.brandId = 17;
        brand17.brandName = "Mercedes-Benz";
        brand17.country = "Germany";
        brand17.foundedYear = 1926;
        brand17.ceoName = "Ola Källenius";
        brand17.revenue = 153000000000.00;
        brand17.electricCars = true;
        brand17.headquarters = "Stuttgart";
        brand17.modelsCount = 25;
        brand17.luxurySegment = "Luxury";
        brand17.indianBrand = false;
        brand17.marketShare = 0.7;
        brand17.factoriesCount = 0;
        brand17.popularModel = "GLE";
        brand17.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand17.brandId);
        System.out.println("Brand Name: " + brand17.brandName);
        System.out.println("Country: " + brand17.country);
        System.out.println("Founded Year: " + brand17.foundedYear);
        System.out.println("CEO Name: " + brand17.ceoName);
        System.out.println("Revenue: " + brand17.revenue);
        System.out.println("Electric Cars: " + brand17.electricCars);
        System.out.println("Headquarters: " + brand17.headquarters);
        System.out.println("Models Count: " + brand17.modelsCount);
        System.out.println("Luxury Segment: " + brand17.luxurySegment);
        System.out.println("Indian Brand: " + brand17.indianBrand);
        System.out.println("Market Share: " + brand17.marketShare);
        System.out.println("Factories Count: " + brand17.factoriesCount);
        System.out.println("Popular Model: " + brand17.popularModel);
        System.out.println("Sponsor Sports: " + brand17.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand18 = new CarBrand();
        brand18.brandId = 18;
        brand18.brandName = "BMW";
        brand18.country = "Germany";
        brand18.foundedYear = 1916;
        brand18.ceoName = "Oliver Zipse";
        brand18.revenue = 155000000000.00;
        brand18.electricCars = true;
        brand18.headquarters = "Munich";
        brand18.modelsCount = 30;
        brand18.luxurySegment = "Luxury";
        brand18.indianBrand = false;
        brand18.marketShare = 0.6;
        brand18.factoriesCount = 0;
        brand18.popularModel = "X1";
        brand18.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand18.brandId);
        System.out.println("Brand Name: " + brand18.brandName);
        System.out.println("Country: " + brand18.country);
        System.out.println("Founded Year: " + brand18.foundedYear);
        System.out.println("CEO Name: " + brand18.ceoName);
        System.out.println("Revenue: " + brand18.revenue);
        System.out.println("Electric Cars: " + brand18.electricCars);
        System.out.println("Headquarters: " + brand18.headquarters);
        System.out.println("Models Count: " + brand18.modelsCount);
        System.out.println("Luxury Segment: " + brand18.luxurySegment);
        System.out.println("Indian Brand: " + brand18.indianBrand);
        System.out.println("Market Share: " + brand18.marketShare);
        System.out.println("Factories Count: " + brand18.factoriesCount);
        System.out.println("Popular Model: " + brand18.popularModel);
        System.out.println("Sponsor Sports: " + brand18.sponsorSports);
        System.out.println("-----------------------------");
        
        CarBrand brand19 = new CarBrand();
        brand19.brandId = 19;
        brand19.brandName = "Audi";
        brand19.country = "Germany";
        brand19.foundedYear = 1909;
        brand19.ceoName = "Gernot Döllner";
        brand19.revenue = 65000000000.00;
        brand19.electricCars = true;
        brand19.headquarters = "Ingolstadt";
        brand19.modelsCount = 18;
        brand19.luxurySegment = "Luxury";
        brand19.indianBrand = false;
        brand19.marketShare = 0.4;
        brand19.factoriesCount = 0;
        brand19.popularModel = "Q3";
        brand19.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand19.brandId);
        System.out.println("Brand Name: " + brand19.brandName);
        System.out.println("Country: " + brand19.country);
        System.out.println("Founded Year: " + brand19.foundedYear);
        System.out.println("CEO Name: " + brand19.ceoName);
        System.out.println("Revenue: " + brand19.revenue);
        System.out.println("Electric Cars: " + brand19.electricCars);
        System.out.println("Headquarters: " + brand19.headquarters);
        System.out.println("Models Count: " + brand19.modelsCount);
        System.out.println("Luxury Segment: " + brand19.luxurySegment);
        System.out.println("Indian Brand: " + brand19.indianBrand);
        System.out.println("Market Share: " + brand19.marketShare);
        System.out.println("Factories Count: " + brand19.factoriesCount);
        System.out.println("Popular Model: " + brand19.popularModel);
        System.out.println("Sponsor Sports: " + brand19.sponsorSports);
        System.out.println("-----------------------------");


        CarBrand brand20 = new CarBrand();
        brand20.brandId = 20;
        brand20.brandName = "Land Rover";
        brand20.country = "UK";
        brand20.foundedYear = 1948;
        brand20.ceoName = "Richard Mudge";
        brand20.revenue = 28000000000.00;
        brand20.electricCars = true;
        brand20.headquarters = "Coventry";
        brand20.modelsCount = 8;
        brand20.luxurySegment = "Luxury SUV";
        brand20.indianBrand = false;
        brand20.marketShare = 0.3;
        brand20.factoriesCount = 0;
        brand20.popularModel = "Defender";
        brand20.sponsorSports = true;
        
        System.out.println("Brand ID: " + brand20.brandId);
        System.out.println("Brand Name: " + brand20.brandName);
        System.out.println("Country: " + brand20.country);
        System.out.println("Founded Year: " + brand20.foundedYear);
        System.out.println("CEO Name: " + brand20.ceoName);
        System.out.println("Revenue: " + brand20.revenue);
        System.out.println("Electric Cars: " + brand20.electricCars);
        System.out.println("Headquarters: " + brand20.headquarters);
        System.out.println("Models Count: " + brand20.modelsCount);
        System.out.println("Luxury Segment: " + brand20.luxurySegment);
        System.out.println("Indian Brand: " + brand20.indianBrand);
        System.out.println("Market Share: " + brand20.marketShare);
        System.out.println("Factories Count: " + brand20.factoriesCount);
        System.out.println("Popular Model: " + brand20.popularModel);
        System.out.println("Sponsor Sports: " + brand20.sponsorSports);
        System.out.println("-----------------------------");

	
		
    }
}
