class ClothInfoExecutor {
    public static void main(String[] cloth) {
	
        ClothInfo cloth1 = new ClothInfo();
        cloth1.setId(101);
        System.out.println("ID: " + cloth1.getId());
        cloth1.setClothName("Levis 511 Slim Fit");
        System.out.println("Cloth Name: " + cloth1.getClothName());
        cloth1.setSize("32x30");
        System.out.println("Size: " + cloth1.getSize());
        cloth1.setBrand("Levis");
        System.out.println("Brand: " + cloth1.getBrand());
        cloth1.setMaterial("Cotton Denim");
        System.out.println("Material: " + cloth1.getMaterial());
        cloth1.setPrice(2899.00);
        System.out.println("Price: " + cloth1.getPrice());
        cloth1.setColor("Indigo Blue");
        System.out.println("Color: " + cloth1.getColor());
        System.out.println();

        ClothInfo cloth2 = new ClothInfo();
        cloth2.setId(102);
        System.out.println("ID: " + cloth2.getId());
        cloth2.setClothName("Roadster Polo T-Shirt");
        System.out.println("Cloth Name: " + cloth2.getClothName());
        cloth2.setSize("M");
        System.out.println("Size: " + cloth2.getSize());
        cloth2.setBrand("Roadster");
        System.out.println("Brand: " + cloth2.getBrand());
        cloth2.setMaterial("Cotton Pique");
        System.out.println("Material: " + cloth2.getMaterial());
        cloth2.setPrice(599.00);
        System.out.println("Price: " + cloth2.getPrice());
        cloth2.setColor("Navy Blue");
        System.out.println("Color: " + cloth2.getColor());
        System.out.println();

        ClothInfo cloth3 = new ClothInfo();
        cloth3.setId(103);
        System.out.println("ID: " + cloth3.getId());
        cloth3.setClothName("HRX Full Sleeve Shirt");
        System.out.println("Cloth Name: " + cloth3.getClothName());
        cloth3.setSize("40");
        System.out.println("Size: " + cloth3.getSize());
        cloth3.setBrand("HRX by Hrithik");
        System.out.println("Brand: " + cloth3.getBrand());
        cloth3.setMaterial("Cotton Linen");
        System.out.println("Material: " + cloth3.getMaterial());
        cloth3.setPrice(1499.00);
        System.out.println("Price: " + cloth3.getPrice());
        cloth3.setColor("White");
        System.out.println("Color: " + cloth3.getColor());
        System.out.println();

        ClothInfo cloth4 = new ClothInfo();
        cloth4.setId(104);
        System.out.println("ID: " + cloth4.getId());
        cloth4.setClothName("Sparx Running Shoes");
        System.out.println("Cloth Name: " + cloth4.getClothName());
        cloth4.setSize("9 UK");
        System.out.println("Size: " + cloth4.getSize());
        cloth4.setBrand("Sparx");
        System.out.println("Brand: " + cloth4.getBrand());
        cloth4.setMaterial("Synthetic Mesh");
        System.out.println("Material: " + cloth4.getMaterial());
        cloth4.setPrice(1299.00);
        System.out.println("Price: " + cloth4.getPrice());
        cloth4.setColor("Black Orange");
        System.out.println("Color: " + cloth4.getColor());
        System.out.println();

        ClothInfo cloth5 = new ClothInfo();
        cloth5.setId(105);
        System.out.println("ID: " + cloth5.getId());
        cloth5.setClothName("Allen Solly Chinos");
        System.out.println("Cloth Name: " + cloth5.getClothName());
        cloth5.setSize("34x32");
        System.out.println("Size: " + cloth5.getSize());
        cloth5.setBrand("Allen Solly");
        System.out.println("Brand: " + cloth5.getBrand());
        cloth5.setMaterial("Cotton Twill");
        System.out.println("Material: " + cloth5.getMaterial());
        cloth5.setPrice(2199.00);
        System.out.println("Price: " + cloth5.getPrice());
        cloth5.setColor("Khaki");
        System.out.println("Color: " + cloth5.getColor());
        System.out.println();
		
		ClothInfo cloth6 = new ClothInfo();
        cloth6.setId(106);
        System.out.println("ID: " + cloth6.getId());
        cloth6.setClothName("Jack & Jones Slim Fit Jeans");
        System.out.println("Cloth Name: " + cloth6.getClothName());
        cloth6.setSize("30x32");
        System.out.println("Size: " + cloth6.getSize());
        cloth6.setBrand("Jack & Jones");
        System.out.println("Brand: " + cloth6.getBrand());
        cloth6.setMaterial("Stretch Denim");
        System.out.println("Material: " + cloth6.getMaterial());
        cloth6.setPrice(2799.00);
        System.out.println("Price: " + cloth6.getPrice());
        cloth6.setColor("Dark Grey");
        System.out.println("Color: " + cloth6.getColor());
        System.out.println();

        ClothInfo cloth7 = new ClothInfo();
        cloth7.setId(107);
        System.out.println("ID: " + cloth7.getId());
        cloth7.setClothName("Puma Sports T-Shirt");
        System.out.println("Cloth Name: " + cloth7.getClothName());
        cloth7.setSize("L");
        System.out.println("Size: " + cloth7.getSize());
        cloth7.setBrand("Puma");
        System.out.println("Brand: " + cloth7.getBrand());
        cloth7.setMaterial("Polyester DryCELL");
        System.out.println("Material: " + cloth7.getMaterial());
        cloth7.setPrice(899.00);
        System.out.println("Price: " + cloth7.getPrice());
        cloth7.setColor("Red Black");
        System.out.println("Color: " + cloth7.getColor());
        System.out.println();

        ClothInfo cloth8 = new ClothInfo();
        cloth8.setId(108);
        System.out.println("ID: " + cloth8.getId());
        cloth8.setClothName("Peter England Formal Shirt");
        System.out.println("Cloth Name: " + cloth8.getClothName());
        cloth8.setSize("42");
        System.out.println("Size: " + cloth8.getSize());
        cloth8.setBrand("Peter England");
        System.out.println("Brand: " + cloth8.getBrand());
        cloth8.setMaterial("Cotton Blend");
        System.out.println("Material: " + cloth8.getMaterial());
        cloth8.setPrice(1799.00);
        System.out.println("Price: " + cloth8.getPrice());
        cloth8.setColor("Light Blue");
        System.out.println("Color: " + cloth8.getColor());
        System.out.println();

        ClothInfo cloth9 = new ClothInfo();
        cloth9.setId(109);
        System.out.println("ID: " + cloth9.getId());
        cloth9.setClothName("Reebok Running Shoes");
        System.out.println("Cloth Name: " + cloth9.getClothName());
        cloth9.setSize("8 UK");
        System.out.println("Size: " + cloth9.getSize());
        cloth9.setBrand("Reebok");
        System.out.println("Brand: " + cloth9.getBrand());
        cloth9.setMaterial("Mesh EVA");
        System.out.println("Material: " + cloth9.getMaterial());
        cloth9.setPrice(3499.00);
        System.out.println("Price: " + cloth9.getPrice());
        cloth9.setColor("White Green");
        System.out.println("Color: " + cloth9.getColor());
        System.out.println();

        ClothInfo cloth10 = new ClothInfo();
        cloth10.setId(110);
        System.out.println("ID: " + cloth10.getId());
        cloth10.setClothName("Basics Cotton Full Sleeve");
        System.out.println("Cloth Name: " + cloth10.getClothName());
        cloth10.setSize("XL");
        System.out.println("Size: " + cloth10.getSize());
        cloth10.setBrand("Basics");
        System.out.println("Brand: " + cloth10.getBrand());
        cloth10.setMaterial("100% Cotton");
        System.out.println("Material: " + cloth10.getMaterial());
        cloth10.setPrice(499.00);
        System.out.println("Price: " + cloth10.getPrice());
        cloth10.setColor("Black");
        System.out.println("Color: " + cloth10.getColor());
        System.out.println();

        ClothInfo cloth11 = new ClothInfo();
        cloth11.setId(111);
        System.out.println("ID: " + cloth11.getId());
        cloth11.setClothName("Van Heusen Cargo Pants");
        System.out.println("Cloth Name: " + cloth11.getClothName());
        cloth11.setSize("36x32");
        System.out.println("Size: " + cloth11.getSize());
        cloth11.setBrand("Van Heusen");
        System.out.println("Brand: " + cloth11.getBrand());
        cloth11.setMaterial("Cotton Ripstop");
        System.out.println("Material: " + cloth11.getMaterial());
        cloth11.setPrice(2499.00);
        System.out.println("Price: " + cloth11.getPrice());
        cloth11.setColor("Olive Green");
        System.out.println("Color: " + cloth11.getColor());
        System.out.println();

        ClothInfo cloth12 = new ClothInfo();
        cloth12.setId(112);
        System.out.println("ID: " + cloth12.getId());
        cloth12.setClothName("Nike Pro Tights");
        System.out.println("Cloth Name: " + cloth12.getClothName());
        cloth12.setSize("M");
        System.out.println("Size: " + cloth12.getSize());
        cloth12.setBrand("Nike");
        System.out.println("Brand: " + cloth12.getBrand());
        cloth12.setMaterial("Dri-FIT Polyester");
        System.out.println("Material: " + cloth12.getMaterial());
        cloth12.setPrice(2999.00);
        System.out.println("Price: " + cloth12.getPrice());
        cloth12.setColor("Black");
        System.out.println("Color: " + cloth12.getColor());
        System.out.println();

        ClothInfo cloth13 = new ClothInfo();
        cloth13.setId(113);
        System.out.println("ID: " + cloth13.getId());
        cloth13.setClothName("Adidas Hoodie");
        System.out.println("Cloth Name: " + cloth13.getClothName());
        cloth13.setSize("L");
        System.out.println("Size: " + cloth13.getSize());
        cloth13.setBrand("Adidas");
        System.out.println("Brand: " + cloth13.getBrand());
        cloth13.setMaterial("Fleece Cotton");
        System.out.println("Material: " + cloth13.getMaterial());
        cloth13.setPrice(3999.00);
        System.out.println("Price: " + cloth13.getPrice());
        cloth13.setColor("Grey Melange");
        System.out.println("Color: " + cloth13.getColor());
        System.out.println();

        ClothInfo cloth14 = new ClothInfo();
        cloth14.setId(114);
        System.out.println("ID: " + cloth14.getId());
        cloth14.setClothName("Flying Machine Denim Shirt");
        System.out.println("Cloth Name: " + cloth14.getClothName());
        cloth14.setSize("M");
        System.out.println("Size: " + cloth14.getSize());
        cloth14.setBrand("Flying Machine");
        System.out.println("Brand: " + cloth14.getBrand());
        cloth14.setMaterial("Cotton Denim");
        System.out.println("Material: " + cloth14.getMaterial());
        cloth14.setPrice(1299.00);
        System.out.println("Price: " + cloth14.getPrice());
        cloth14.setColor("Light Wash");
        System.out.println("Color: " + cloth14.getColor());
        System.out.println();

        ClothInfo cloth15 = new ClothInfo();
        cloth15.setId(115);
        System.out.println("ID: " + cloth15.getId());
        cloth15.setClothName("Asics Gel Shoes");
        System.out.println("Cloth Name: " + cloth15.getClothName());
        cloth15.setSize("10 UK");
        System.out.println("Size: " + cloth15.getSize());
        cloth15.setBrand("Asics");
        System.out.println("Brand: " + cloth15.getBrand());
        cloth15.setMaterial("Engineered Mesh");
        System.out.println("Material: " + cloth15.getMaterial());
        cloth15.setPrice(5999.00);
        System.out.println("Price: " + cloth15.getPrice());
        cloth15.setColor("Blue White");
        System.out.println("Color: " + cloth15.getColor());
        System.out.println();

        ClothInfo cloth16 = new ClothInfo();
        cloth16.setId(116);
        System.out.println("ID: " + cloth16.getId());
        cloth16.setClothName("U.S. Polo Assn. Polo Shirt");
        System.out.println("Cloth Name: " + cloth16.getClothName());
        cloth16.setSize("L");
        System.out.println("Size: " + cloth16.getSize());
        cloth16.setBrand("U.S. Polo Assn.");
        System.out.println("Brand: " + cloth16.getBrand());
        cloth16.setMaterial("Pique Cotton");
        System.out.println("Material: " + cloth16.getMaterial());
        cloth16.setPrice(1599.00);
        System.out.println("Price: " + cloth16.getPrice());
        cloth16.setColor("Maroon");
        System.out.println("Color: " + cloth16.getColor());
        System.out.println();

        ClothInfo cloth17 = new ClothInfo();
        cloth17.setId(117);
        System.out.println("ID: " + cloth17.getId());
        cloth17.setClothName("Pepe Jeans Straight Fit");
        System.out.println("Cloth Name: " + cloth17.getClothName());
        cloth17.setSize("32x34");
        System.out.println("Size: " + cloth17.getSize());
        cloth17.setBrand("Pepe Jeans");
        System.out.println("Brand: " + cloth17.getBrand());
        cloth17.setMaterial("Cotton Stretch");
        System.out.println("Material: " + cloth17.getMaterial());
        cloth17.setPrice(2599.00);
        System.out.println("Price: " + cloth17.getPrice());
        cloth17.setColor("Mid Blue");
        System.out.println("Color: " + cloth17.getColor());
        System.out.println();
		
		ClothInfo cloth18 = new ClothInfo();
        cloth18.setId(118);
        System.out.println("ID: " + cloth18.getId());
        cloth18.setClothName("Arrow Formal Shirt");
        System.out.println("Cloth Name: " + cloth18.getClothName());
        cloth18.setSize("39");
        System.out.println("Size: " + cloth18.getSize());
        cloth18.setBrand("Arrow");
        System.out.println("Brand: " + cloth18.getBrand());
        cloth18.setMaterial("Cotton Formal");
        System.out.println("Material: " + cloth18.getMaterial());
        cloth18.setPrice(2299.00);
        System.out.println("Price: " + cloth18.getPrice());
        cloth18.setColor("Sky Blue");
        System.out.println("Color: " + cloth18.getColor());
        System.out.println();

        ClothInfo cloth19 = new ClothInfo();
        cloth19.setId(119);
        System.out.println("ID: " + cloth19.getId());
        cloth19.setClothName("Under Armour Shorts");
        System.out.println("Cloth Name: " + cloth19.getClothName());
        cloth19.setSize("M");
        System.out.println("Size: " + cloth19.getSize());
        cloth19.setBrand("Under Armour");
        System.out.println("Brand: " + cloth19.getBrand());
        cloth19.setMaterial("HeatGear Fabric");
        System.out.println("Material: " + cloth19.getMaterial());
        cloth19.setPrice(1899.00);
        System.out.println("Price: " + cloth19.getPrice());
        cloth19.setColor("Black Grey");
        System.out.println("Color: " + cloth19.getColor());
        System.out.println();

        ClothInfo cloth20 = new ClothInfo();
        cloth20.setId(120);
        System.out.println("ID: " + cloth20.getId());
        cloth20.setClothName("Lee Straight Fit Jeans");
        System.out.println("Cloth Name: " + cloth20.getClothName());
        cloth20.setSize("34x32");
        System.out.println("Size: " + cloth20.getSize());
        cloth20.setBrand("Lee");
        System.out.println("Brand: " + cloth20.getBrand());
        cloth20.setMaterial("Cotton Denim");
        System.out.println("Material: " + cloth20.getMaterial());
        cloth20.setPrice(2699.00);
        System.out.println("Price: " + cloth20.getPrice());
        cloth20.setColor("Dark Wash");
        System.out.println("Color: " + cloth20.getColor());
        System.out.println();

        ClothInfo cloth21 = new ClothInfo();
        cloth21.setId(121);
        System.out.println("ID: " + cloth21.getId());
        cloth21.setClothName("Fila Track Pants");
        System.out.println("Cloth Name: " + cloth21.getClothName());
        cloth21.setSize("L");
        System.out.println("Size: " + cloth21.getSize());
        cloth21.setBrand("Fila");
        System.out.println("Brand: " + cloth21.getBrand());
        cloth21.setMaterial("Polyester Fleece");
        System.out.println("Material: " + cloth21.getMaterial());
        cloth21.setPrice(1399.00);
        System.out.println("Price: " + cloth21.getPrice());
        cloth21.setColor("Navy Blue");
        System.out.println("Color: " + cloth21.getColor());
        System.out.println();

        ClothInfo cloth22 = new ClothInfo();
        cloth22.setId(122);
        System.out.println("ID: " + cloth22.getId());
        cloth22.setClothName("Raymond Suiting Fabric");
        System.out.println("Cloth Name: " + cloth22.getClothName());
        cloth22.setSize("42");
        System.out.println("Size: " + cloth22.getSize());
        cloth22.setBrand("Raymond");
        System.out.println("Brand: " + cloth22.getBrand());
        cloth22.setMaterial("Poly Viscose");
        System.out.println("Material: " + cloth22.getMaterial());
        cloth22.setPrice(3499.00);
        System.out.println("Price: " + cloth22.getPrice());
        cloth22.setColor("Charcoal Grey");
        System.out.println("Color: " + cloth22.getColor());
        System.out.println();

        ClothInfo cloth23 = new ClothInfo();
        cloth23.setId(123);
        System.out.println("ID: " + cloth23.getId());
        cloth23.setClothName("Campus Casual Shoes");
        System.out.println("Cloth Name: " + cloth23.getClothName());
        cloth23.setSize("8 UK");
        System.out.println("Size: " + cloth23.getSize());
        cloth23.setBrand("Campus");
        System.out.println("Brand: " + cloth23.getBrand());
        cloth23.setMaterial("PU Leather");
        System.out.println("Material: " + cloth23.getMaterial());
        cloth23.setPrice(999.00);
        System.out.println("Price: " + cloth23.getPrice());
        cloth23.setColor("Tan Brown");
        System.out.println("Color: " + cloth23.getColor());
        System.out.println();

        ClothInfo cloth24 = new ClothInfo();
        cloth24.setId(124);
        System.out.println("ID: " + cloth24.getId());
        cloth24.setClothName("Jockey Boxer Pack 3");
        System.out.println("Cloth Name: " + cloth24.getClothName());
        cloth24.setSize("M");
        System.out.println("Size: " + cloth24.getSize());
        cloth24.setBrand("Jockey");
        System.out.println("Brand: " + cloth24.getBrand());
        cloth24.setMaterial("Cotton Rich Microfiber");
        System.out.println("Material: " + cloth24.getMaterial());
        cloth24.setPrice(699.00);
        System.out.println("Price: " + cloth24.getPrice());
        cloth24.setColor("Multi Colour");
        System.out.println("Color: " + cloth24.getColor());
        System.out.println();

        ClothInfo cloth25 = new ClothInfo();
        cloth25.setId(125);
        System.out.println("ID: " + cloth25.getId());
        cloth25.setClothName("Louis Philippe T-Shirt");
        System.out.println("Cloth Name: " + cloth25.getClothName());
        cloth25.setSize("XL");
        System.out.println("Size: " + cloth25.getSize());
        cloth25.setBrand("Louis Philippe");
        System.out.println("Brand: " + cloth25.getBrand());
        cloth25.setMaterial("Pima Cotton");
        System.out.println("Material: " + cloth25.getMaterial());
        cloth25.setPrice(999.00);
        System.out.println("Price: " + cloth25.getPrice());
        cloth25.setColor("Olive Green");
        System.out.println("Color: " + cloth25.getColor());
        System.out.println();

        ClothInfo cloth26 = new ClothInfo();
        cloth26.setId(126);
        System.out.println("ID: " + cloth26.getId());
        cloth26.setClothName("Bata Formal Shoes");
        System.out.println("Cloth Name: " + cloth26.getClothName());
        cloth26.setSize("9 UK");
        System.out.println("Size: " + cloth26.getSize());
        cloth26.setBrand("Bata");
        System.out.println("Brand: " + cloth26.getBrand());
        cloth26.setMaterial("Bonded Leather");
        System.out.println("Material: " + cloth26.getMaterial());
        cloth26.setPrice(2199.00);
        System.out.println("Price: " + cloth26.getPrice());
        cloth26.setColor("Black");
        System.out.println("Color: " + cloth26.getColor());
        System.out.println();

        ClothInfo cloth27 = new ClothInfo();
        cloth27.setId(127);
        System.out.println("ID: " + cloth27.getId());
        cloth27.setClothName("ColorPlus Chinos");
        System.out.println("Cloth Name: " + cloth27.getClothName());
        cloth27.setSize("32x30");
        System.out.println("Size: " + cloth27.getSize());
        cloth27.setBrand("ColorPlus");
        System.out.println("Brand: " + cloth27.getBrand());
        cloth27.setMaterial("Stretch Cotton");
        System.out.println("Material: " + cloth27.getMaterial());
        cloth27.setPrice(1899.00);
        System.out.println("Price: " + cloth27.getPrice());
        cloth27.setColor("Beige");
        System.out.println("Color: " + cloth27.getColor());
        System.out.println();

        ClothInfo cloth28 = new ClothInfo();
        cloth28.setId(128);
        System.out.println("ID: " + cloth28.getId());
        cloth28.setClothName("Decathlon Yoga Pants");
        System.out.println("Cloth Name: " + cloth28.getClothName());
        cloth28.setSize("S");
        System.out.println("Size: " + cloth28.getSize());
        cloth28.setBrand("Decathlon");
        System.out.println("Brand: " + cloth28.getBrand());
        cloth28.setMaterial("Elastane Spandex");
        System.out.println("Material: " + cloth28.getMaterial());
        cloth28.setPrice(799.00);
        System.out.println("Price: " + cloth28.getPrice());
        cloth28.setColor("Midnight Blue");
        System.out.println("Color: " + cloth28.getColor());
        System.out.println();

        ClothInfo cloth29 = new ClothInfo();
        cloth29.setId(129);
        System.out.println("ID: " + cloth29.getId());
        cloth29.setClothName("Park Avenue Blazer");
        System.out.println("Cloth Name: " + cloth29.getClothName());
        cloth29.setSize("40");
        System.out.println("Size: " + cloth29.getSize());
        cloth29.setBrand("Park Avenue");
        System.out.println("Brand: " + cloth29.getBrand());
        cloth29.setMaterial("Poly Wool Blend");
        System.out.println("Material: " + cloth29.getMaterial());
        cloth29.setPrice(5999.00);
        System.out.println("Price: " + cloth29.getPrice());
        cloth29.setColor("Navy Blue");
        System.out.println("Color: " + cloth29.getColor());
        System.out.println();
    }
}