class CoffeeExecutor {
    public static void main(String[] args) {
        Coffee c1 = new Coffee(); 
		c1.coffeeId = 1; 
		c1.coffeeType = "Espresso";
        Coffee c2 = new Coffee();
		c2.coffeeId = 2; 
		c2.coffeeType = "Cappuccino";
        Coffee c3 = new Coffee();
		c3.coffeeId = 3; 
		c3.coffeeType = "Latte";
        Coffee c4 = new Coffee(); 
		c4.coffeeId = 4;
		c4.coffeeType = "Americano";
        Coffee c5 = new Coffee();
		c5.coffeeId = 5; 
		c5.coffeeType = "Mocha";
        Coffee c6 = new Coffee(); 
		c6.coffeeId = 6; 
		c6.coffeeType = "Filter Coffee";
        Coffee c7 = new Coffee();
		c7.coffeeId = 7;
		c7.coffeeType = "Turkish";
        Coffee c8 = new Coffee();
		c8.coffeeId = 8; 
		c8.coffeeType = "Ristretto";
        Coffee c9 = new Coffee(); 
		c9.coffeeId = 9;
		c9.coffeeType = "Macchiato";
        Coffee c10 = new Coffee(); 
		c10.coffeeId = 10; 
		c10.coffeeType = "Flat White";
        Coffee c11 = new Coffee(); 
		c11.coffeeId = 11;
		c11.coffeeType = "Affogato";
        Coffee c12 = new Coffee();
		c12.coffeeId = 12;
		c12.coffeeType = "Doppio";
        Coffee c13 = new Coffee();
		c13.coffeeId = 13;
		c13.coffeeType = "Breve";
        Coffee c14 = new Coffee();
		c14.coffeeId = 14;
		c14.coffeeType = "Cortado";
        Coffee c15 = new Coffee();
		c15.coffeeId = 15;
		c15.coffeeType = "Galao";
        Coffee c16 = new Coffee();
		c16.coffeeId = 16;
		c16.coffeeType = "Instant";
        Coffee c17 = new Coffee(); 
		c17.coffeeId = 17;
		c17.coffeeType = "Cold Brew";
        Coffee c18 = new Coffee();
		c18.coffeeId = 18;
		c18.coffeeType = "Nitro";
        Coffee c19 = new Coffee();
		c19.coffeeId = 19;
		c19.coffeeType = "Vienna";
        Coffee c20 = new Coffee();
		c20.coffeeId = 20;
		c20.coffeeType = "Mazagran";
        Coffee c21 = new Coffee();
		c21.coffeeId = 21;
		c21.coffeeType = "Eiskaffee";
        Coffee c22 = new Coffee();
		c22.coffeeId = 22;
		c22.coffeeType = "Frappuccino";
        Coffee c23 = new Coffee();
		c23.coffeeId = 23;
		c23.coffeeType = "Robusta";
        Coffee c24 = new Coffee();
		c24.coffeeId = 24;
		c24.coffeeType = "Arabica";
        Coffee c25 = new Coffee(); 
		c25.coffeeId = 25; 
		c25.coffeeType = "Decaf";
		
       System.out.println("Coffee c1 ID: " + c1.coffeeId + " Type: " + c1.coffeeType);
        System.out.println("Coffee c2 ID: " + c2.coffeeId + " Type: " + c2.coffeeType);
        System.out.println("Coffee c3 ID: " + c3.coffeeId + " Type: " + c3.coffeeType);
        System.out.println("Coffee c4 ID: " + c4.coffeeId + " Type: " + c4.coffeeType);
        System.out.println("Coffee c5 ID: " + c5.coffeeId + " Type: " + c5.coffeeType);
        System.out.println("Coffee c6 ID: " + c6.coffeeId + " Type: " + c6.coffeeType);
        System.out.println("Coffee c7 ID: " + c7.coffeeId + " Type: " + c7.coffeeType);
        System.out.println("Coffee c8 ID: " + c8.coffeeId + " Type: " + c8.coffeeType);
        System.out.println("Coffee c9 ID: " + c9.coffeeId + " Type: " + c9.coffeeType);
        System.out.println("Coffee c10 ID: " + c10.coffeeId + " Type: " + c10.coffeeType);
        System.out.println("Coffee c11 ID: " + c11.coffeeId + " Type: " + c11.coffeeType);
        System.out.println("Coffee c12 ID: " + c12.coffeeId + " Type: " + c12.coffeeType);
        System.out.println("Coffee c13 ID: " + c13.coffeeId + " Type: " + c13.coffeeType);
        System.out.println("Coffee c14 ID: " + c14.coffeeId + " Type: " + c14.coffeeType);
        System.out.println("Coffee c15 ID: " + c15.coffeeId + " Type: " + c15.coffeeType);
        System.out.println("Coffee c16 ID: " + c16.coffeeId + " Type: " + c16.coffeeType);
        System.out.println("Coffee c17 ID: " + c17.coffeeId + " Type: " + c17.coffeeType);
        System.out.println("Coffee c18 ID: " + c18.coffeeId + " Type: " + c18.coffeeType);
        System.out.println("Coffee c19 ID: " + c19.coffeeId + " Type: " + c19.coffeeType);
        System.out.println("Coffee c20 ID: " + c20.coffeeId + " Type: " + c20.coffeeType);
        System.out.println("Coffee c21 ID: " + c21.coffeeId + " Type: " + c21.coffeeType);
        System.out.println("Coffee c22 ID: " + c22.coffeeId + " Type: " + c22.coffeeType);
        System.out.println("Coffee c23 ID: " + c23.coffeeId + " Type: " + c23.coffeeType);
        System.out.println("Coffee c24 ID: " + c24.coffeeId + " Type: " + c24.coffeeType);
        System.out.println("Coffee c25 ID: " + c25.coffeeId + " Type: " + c25.coffeeType);
        System.out.println("----------------------------------------------------------");
              
	  
        Coffee p1 = new Coffee(1, "Espresso");
        Coffee p2 = new Coffee(2, "Cappuccino");
        Coffee p3 = new Coffee(3, "Latte");
        Coffee p4 = new Coffee(4, "Americano");
        Coffee p5 = new Coffee(5, "Mocha");
        Coffee p6 = new Coffee(6, "Filter Coffee");
        Coffee p7 = new Coffee(7, "Turkish");
        Coffee p8 = new Coffee(8, "Ristretto");
        Coffee p9 = new Coffee(9, "Macchiato");
        Coffee p10 = new Coffee(10, "Flat White");
        Coffee p11 = new Coffee(11, "Affogato");
        Coffee p12 = new Coffee(12, "Doppio");
        Coffee p13 = new Coffee(13, "Breve");
        Coffee p14 = new Coffee(14, "Cortado");
        Coffee p15 = new Coffee(15, "Galao");
        Coffee p16 = new Coffee(16, "Instant");
        Coffee p17 = new Coffee(17, "Cold Brew");
        Coffee p18 = new Coffee(18, "Nitro");
        Coffee p19 = new Coffee(19, "Vienna");
        Coffee p20 = new Coffee(20, "Mazagran");
        Coffee p21 = new Coffee(21, "Eiskaffee");
        Coffee p22 = new Coffee(22, "Frappuccino");
        Coffee p23 = new Coffee(23, "Robusta");
        Coffee p24 = new Coffee(24, "Arabica");
        Coffee p25 = new Coffee(25, "Decaf");
        

        System.out.println("Coffee p1 ID: " + p1.coffeeId + " Type: " + p1.coffeeType);
        System.out.println("Coffee p2 ID: " + p2.coffeeId + " Type: " + p2.coffeeType);
        System.out.println("Coffee p3 ID: " + p3.coffeeId + " Type: " + p3.coffeeType);
        System.out.println("Coffee p4 ID: " + p4.coffeeId + " Type: " + p4.coffeeType);
        System.out.println("Coffee p5 ID: " + p5.coffeeId + " Type: " + p5.coffeeType);
        System.out.println("Coffee p6 ID: " + p6.coffeeId + " Type: " + p6.coffeeType);
        System.out.println("Coffee p7 ID: " + p7.coffeeId + " Type: " + p7.coffeeType);
        System.out.println("Coffee p8 ID: " + p8.coffeeId + " Type: " + p8.coffeeType);
        System.out.println("Coffee p9 ID: " + p9.coffeeId + " Type: " + p9.coffeeType);
        System.out.println("Coffee p10 ID: " + p10.coffeeId + " Type: " + p10.coffeeType);
        System.out.println("Coffee p11 ID: " + p11.coffeeId + " Type: " + p11.coffeeType);
        System.out.println("Coffee p12 ID: " + p12.coffeeId + " Type: " + p12.coffeeType);
        System.out.println("Coffee p13 ID: " + p13.coffeeId + " Type: " + p13.coffeeType);
        System.out.println("Coffee p14 ID: " + p14.coffeeId + " Type: " + p14.coffeeType);
        System.out.println("Coffee p15 ID: " + p15.coffeeId + " Type: " + p15.coffeeType);
        System.out.println("Coffee p16 ID: " + p16.coffeeId + " Type: " + p16.coffeeType);
        System.out.println("Coffee p17 ID: " + p17.coffeeId + " Type: " + p17.coffeeType);
        System.out.println("Coffee p18 ID: " + p18.coffeeId + " Type: " + p18.coffeeType);
        System.out.println("Coffee p19 ID: " + p19.coffeeId + " Type: " + p19.coffeeType);
        System.out.println("Coffee p20 ID: " + p20.coffeeId + " Type: " + p20.coffeeType);
        System.out.println("Coffee p21 ID: " + p21.coffeeId + " Type: " + p21.coffeeType);
        System.out.println("Coffee p22 ID: " + p22.coffeeId + " Type: " + p22.coffeeType);
        System.out.println("Coffee p23 ID: " + p23.coffeeId + " Type: " + p23.coffeeType);
        System.out.println("Coffee p24 ID: " + p24.coffeeId + " Type: " + p24.coffeeType);
        System.out.println("Coffee p25 ID: " + p25.coffeeId + " Type: " + p25.coffeeType);
        System.out.println("----------------------------------------------------------");
    }
}
