class ForestExecutor {
    public static void main(String[] args) {
        Forest forest1 = new Forest();
        
        forest1.forestId = 201;
        forest1.location = "Bandipur National Park";
        forest1.state = "Karnataka";
        forest1.protectedArea = true;
        forest1.declarationDate = "01/04/1974";
        forest1.lastSurveyDate = "15/02/2026";
        forest1.surveyDue = false;
        forest1.managedBy = "Karnataka Forest Department";
        forest1.forestType = "Dry Deciduous";
        forest1.areaHectares = 8800;
        forest1.dominantSpecies = "Teak, Sandalwood";
        forest1.tigerReserve = true;
        forest1.treeDensity = 450;
        forest1.conservationStatus = "IUCN Category II";
        forest1.biodiversityHotspot = true;
        forest1.speciesCount = 350;
        forest1.carbonSequestration = 12500.5;
        forest1.climateZone = "Tropical";
        forest1.waterSource = true;
        forest1.soilType = "Red Loamy";
        forest1.canopyHeight = 25;
        forest1.fireResistant = true;
        forest1.wildlifeCorridor = "Nagarhole-Bandipur";
        forest1.cameraTraps = true;
        forest1.forestDivision = "Mysore Circle";
        forest1.annualBudget = 25000000.00;
        forest1.emergencyContact = "08224-254221";
        
        System.out.println("Forest ID: " + forest1.forestId);
        System.out.println("Location: " + forest1.location);
        System.out.println("State: " + forest1.state);
        System.out.println("Protected Area: " + forest1.protectedArea);
        System.out.println("Declaration Date: " + forest1.declarationDate);
        System.out.println("Last Survey: " + forest1.lastSurveyDate);
        System.out.println("Survey Due: " + forest1.surveyDue);
        System.out.println("Managed By: " + forest1.managedBy);
        System.out.println("Forest Type: " + forest1.forestType);
        System.out.println("Area: " + forest1.areaHectares + " hectares");
        System.out.println("Dominant Species: " + forest1.dominantSpecies);
        System.out.println("Tiger Reserve: " + forest1.tigerReserve);
        System.out.println("Tree Density: " + forest1.treeDensity + " trees/hectare");
        System.out.println("Conservation Status: " + forest1.conservationStatus);
        System.out.println("Biodiversity Hotspot: " + forest1.biodiversityHotspot);
        System.out.println("Species Count: " + forest1.speciesCount);
        System.out.println("Carbon Sequestration: " + forest1.carbonSequestration + " tons/year");
        System.out.println("Climate Zone: " + forest1.climateZone);
        System.out.println("Water Source: " + forest1.waterSource);
        System.out.println("Soil Type: " + forest1.soilType);
        System.out.println("Canopy Height: " + forest1.canopyHeight + " meters");
        System.out.println("Fire Resistant: " + forest1.fireResistant);
        System.out.println("Wildlife Corridor: " + forest1.wildlifeCorridor);
        System.out.println("Camera Traps: " + forest1.cameraTraps);
        System.out.println("Forest Division: " + forest1.forestDivision);
        System.out.println("Annual Budget: " + forest1.annualBudget);
        System.out.println("Emergency Contact: " + forest1.emergencyContact);
        System.out.println("================================");
		
	// Forest 2 - Nagarhole National Park
Forest forest2 = new Forest();

forest2.forestId = 202;
forest2.location = "Nagarhole National Park";
forest2.state = "Karnataka";
forest2.protectedArea = true;
forest2.declarationDate = "15/10/1955";
forest2.lastSurveyDate = "20/02/2026";
forest2.surveyDue = false;
forest2.managedBy = "Karnataka Forest Department";
forest2.forestType = "Moist Deciduous";
forest2.areaHectares = 6439;
forest2.dominantSpecies = "Rosewood, Teak";
forest2.tigerReserve = true;
forest2.treeDensity = 520;
forest2.conservationStatus = "IUCN Category II";
forest2.biodiversityHotspot = true;
forest2.speciesCount = 320;
forest2.carbonSequestration = 11800.0;
forest2.climateZone = "Tropical";
forest2.waterSource = true;
forest2.soilType = "Laterite";
forest2.canopyHeight = 28;
forest2.fireResistant = true;
forest2.wildlifeCorridor = "Bandipur-Nagarhole";
forest2.cameraTraps = true;
forest2.forestDivision = "Mysore Circle";
forest2.annualBudget = 22000000.00;
forest2.emergencyContact = "08228-237221";

System.out.println("Forest ID: " + forest2.forestId);
System.out.println("Location: " + forest2.location);
System.out.println("State: " + forest2.state);
System.out.println("Protected Area: " + forest2.protectedArea);
System.out.println("Declaration Date: " + forest2.declarationDate);
System.out.println("Last Survey: " + forest2.lastSurveyDate);
System.out.println("Survey Due: " + forest2.surveyDue);
System.out.println("Managed By: " + forest2.managedBy);
System.out.println("Forest Type: " + forest2.forestType);
System.out.println("Area: " + forest2.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest2.dominantSpecies);
System.out.println("Tiger Reserve: " + forest2.tigerReserve);
System.out.println("Tree Density: " + forest2.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest2.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest2.biodiversityHotspot);
System.out.println("Species Count: " + forest2.speciesCount);
System.out.println("Carbon Sequestration: " + forest2.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest2.climateZone);
System.out.println("Water Source: " + forest2.waterSource);
System.out.println("Soil Type: " + forest2.soilType);
System.out.println("Canopy Height: " + forest2.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest2.fireResistant);
System.out.println("Wildlife Corridor: " + forest2.wildlifeCorridor);
System.out.println("Camera Traps: " + forest2.cameraTraps);
System.out.println("Forest Division: " + forest2.forestDivision);
System.out.println("Annual Budget: " + forest2.annualBudget);
System.out.println("Emergency Contact: " + forest2.emergencyContact);
System.out.println("================================");

// Forest 3 - Bhadra Wildlife Sanctuary
Forest forest3 = new Forest();

forest3.forestId = 203;
forest3.location = "Bhadra Wildlife Sanctuary";
forest3.state = "Karnataka";
forest3.protectedArea = true;
forest3.declarationDate = "07/10/1974";
forest3.lastSurveyDate = "25/01/2026";
forest3.surveyDue = true;
forest3.managedBy = "Karnataka Forest Department";
forest3.forestType = "Moist Deciduous";
forest3.areaHectares = 492;
forest3.dominantSpecies = "Teak, Rosewood, Bamboo";
forest3.tigerReserve = true;
forest3.treeDensity = 480;
forest3.conservationStatus = "IUCN Category IV";
forest3.biodiversityHotspot = true;
forest3.speciesCount = 280;
forest3.carbonSequestration = 9500.0;
forest3.climateZone = "Subtropical";
forest3.waterSource = true;
forest3.soilType = "Red Sandy";
forest3.canopyHeight = 22;
forest3.fireResistant = false;
forest3.wildlifeCorridor = "Bhadra-Mullayanagiri";
forest3.cameraTraps = true;
forest3.forestDivision = "Chikmagalur Circle";
forest3.annualBudget = 18000000.00;
forest3.emergencyContact = "08262-236221";

System.out.println("Forest ID: " + forest3.forestId);
System.out.println("Location: " + forest3.location);
System.out.println("State: " + forest3.state);
System.out.println("Protected Area: " + forest3.protectedArea);
System.out.println("Declaration Date: " + forest3.declarationDate);
System.out.println("Last Survey: " + forest3.lastSurveyDate);
System.out.println("Survey Due: " + forest3.surveyDue);
System.out.println("Managed By: " + forest3.managedBy);
System.out.println("Forest Type: " + forest3.forestType);
System.out.println("Area: " + forest3.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest3.dominantSpecies);
System.out.println("Tiger Reserve: " + forest3.tigerReserve);
System.out.println("Tree Density: " + forest3.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest3.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest3.biodiversityHotspot);
System.out.println("Species Count: " + forest3.speciesCount);
System.out.println("Carbon Sequestration: " + forest3.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest3.climateZone);
System.out.println("Water Source: " + forest3.waterSource);
System.out.println("Soil Type: " + forest3.soilType);
System.out.println("Canopy Height: " + forest3.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest3.fireResistant);
System.out.println("Wildlife Corridor: " + forest3.wildlifeCorridor);
System.out.println("Camera Traps: " + forest3.cameraTraps);
System.out.println("Forest Division: " + forest3.forestDivision);
System.out.println("Annual Budget: " + forest3.annualBudget);
System.out.println("Emergency Contact: " + forest3.emergencyContact);
System.out.println("================================");
	
		
// Forest 4 - Bannerghatta National Park
Forest forest4 = new Forest();

forest4.forestId = 204;
forest4.location = "Bannerghatta National Park";
forest4.state = "Karnataka";
forest4.protectedArea = true;
forest4.declarationDate = "15/08/1971";
forest4.lastSurveyDate = "10/03/2026";
forest4.surveyDue = false;
forest4.managedBy = "Karnataka Forest Department";
forest4.forestType = "Dry Deciduous";
forest4.areaHectares = 104;
forest4.dominantSpecies = "Sandalwood, Bamboo";
forest4.tigerReserve = false;
forest4.treeDensity = 380;
forest4.conservationStatus = "IUCN Category II";
forest4.biodiversityHotspot = true;
forest4.speciesCount = 250;
forest4.carbonSequestration = 8200.0;
forest4.climateZone = "Tropical";
forest4.waterSource = true;
forest4.soilType = "Granite Derived";
forest4.canopyHeight = 18;
forest4.fireResistant = true;
forest4.wildlifeCorridor = "Cauvery-Bannerghatta";
forest4.cameraTraps = true;
forest4.forestDivision = "Bengaluru Circle";
forest4.annualBudget = 15000000.00;
forest4.emergencyContact = "080-28534798";

System.out.println("Forest ID: " + forest4.forestId);
System.out.println("Location: " + forest4.location);
System.out.println("State: " + forest4.state);
System.out.println("Protected Area: " + forest4.protectedArea);
System.out.println("Declaration Date: " + forest4.declarationDate);
System.out.println("Last Survey: " + forest4.lastSurveyDate);
System.out.println("Survey Due: " + forest4.surveyDue);
System.out.println("Managed By: " + forest4.managedBy);
System.out.println("Forest Type: " + forest4.forestType);
System.out.println("Area: " + forest4.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest4.dominantSpecies);
System.out.println("Tiger Reserve: " + forest4.tigerReserve);
System.out.println("Tree Density: " + forest4.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest4.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest4.biodiversityHotspot);
System.out.println("Species Count: " + forest4.speciesCount);
System.out.println("Carbon Sequestration: " + forest4.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest4.climateZone);
System.out.println("Water Source: " + forest4.waterSource);
System.out.println("Soil Type: " + forest4.soilType);
System.out.println("Canopy Height: " + forest4.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest4.fireResistant);
System.out.println("Wildlife Corridor: " + forest4.wildlifeCorridor);
System.out.println("Camera Traps: " + forest4.cameraTraps);
System.out.println("Forest Division: " + forest4.forestDivision);
System.out.println("Annual Budget: " + forest4.annualBudget);
System.out.println("Emergency Contact: " + forest4.emergencyContact);
System.out.println("================================");
	
		
	// Forest 5 - Kudremukh National Park
Forest forest5 = new Forest();

forest5.forestId = 205;
forest5.location = "Kudremukh National Park";
forest5.state = "Karnataka";
forest5.protectedArea = true;
forest5.declarationDate = "01/10/1987";
forest5.lastSurveyDate = "05/03/2026";
forest5.surveyDue = false;
forest5.managedBy = "Karnataka Forest Department";
forest5.forestType = "Evergreen Shola";
forest5.areaHectares = 600;
forest5.dominantSpecies = "Evergreen, Shola Trees";
forest5.tigerReserve = false;
forest5.treeDensity = 650;
forest5.conservationStatus = "IUCN Category II";
forest5.biodiversityHotspot = true;
forest5.speciesCount = 420;
forest5.carbonSequestration = 14500.0;
forest5.climateZone = "Montane";
forest5.waterSource = true;
forest5.soilType = "Laterite";
forest5.canopyHeight = 35;
forest5.fireResistant = false;
forest5.wildlifeCorridor = "Western Ghats";
forest5.cameraTraps = true;
forest5.forestDivision = "Chikmagalur Circle";
forest5.annualBudget = 32000000.00;
forest5.emergencyContact = "08262-233221";

System.out.println("Forest ID: " + forest5.forestId);
System.out.println("Location: " + forest5.location);
System.out.println("State: " + forest5.state);
System.out.println("Protected Area: " + forest5.protectedArea);
System.out.println("Declaration Date: " + forest5.declarationDate);
System.out.println("Last Survey: " + forest5.lastSurveyDate);
System.out.println("Survey Due: " + forest5.surveyDue);
System.out.println("Managed By: " + forest5.managedBy);
System.out.println("Forest Type: " + forest5.forestType);
System.out.println("Area: " + forest5.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest5.dominantSpecies);
System.out.println("Tiger Reserve: " + forest5.tigerReserve);
System.out.println("Tree Density: " + forest5.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest5.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest5.biodiversityHotspot);
System.out.println("Species Count: " + forest5.speciesCount);
System.out.println("Carbon Sequestration: " + forest5.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest5.climateZone);
System.out.println("Water Source: " + forest5.waterSource);
System.out.println("Soil Type: " + forest5.soilType);
System.out.println("Canopy Height: " + forest5.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest5.fireResistant);
System.out.println("Wildlife Corridor: " + forest5.wildlifeCorridor);
System.out.println("Camera Traps: " + forest5.cameraTraps);
System.out.println("Forest Division: " + forest5.forestDivision);
System.out.println("Annual Budget: " + forest5.annualBudget);
System.out.println("Emergency Contact: " + forest5.emergencyContact);
System.out.println("================================");
	
		
	// Forest 6 - Anshi National Park
Forest forest6 = new Forest();

forest6.forestId = 206;
forest6.location = "Anshi National Park";
forest6.state = "Karnataka";
forest6.protectedArea = true;
forest6.declarationDate = "01/09/1987";
forest6.lastSurveyDate = "18/02/2026";
forest6.surveyDue = false;
forest6.managedBy = "Karnataka Forest Department";
forest6.forestType = "Evergreen Rainforest";
forest6.areaHectares = 340;
forest6.dominantSpecies = "Teak, Rosewood, Bamboo";
forest6.tigerReserve = true;
forest6.treeDensity = 580;
forest6.conservationStatus = "IUCN Category II";
forest6.biodiversityHotspot = true;
forest6.speciesCount = 380;
forest6.carbonSequestration = 13800.0;
forest6.climateZone = "Tropical Wet";
forest6.waterSource = true;
forest6.soilType = "Alluvial";
forest6.canopyHeight = 32;
forest6.fireResistant = false;
forest6.wildlifeCorridor = "Dandeli-Anshi";
forest6.cameraTraps = true;
forest6.forestDivision = "Kanara Circle";
forest6.annualBudget = 28000000.00;
forest6.emergencyContact = "08284-230221";

System.out.println("Forest ID: " + forest6.forestId);
System.out.println("Location: " + forest6.location);
System.out.println("State: " + forest6.state);
System.out.println("Protected Area: " + forest6.protectedArea);
System.out.println("Declaration Date: " + forest6.declarationDate);
System.out.println("Last Survey: " + forest6.lastSurveyDate);
System.out.println("Survey Due: " + forest6.surveyDue);
System.out.println("Managed By: " + forest6.managedBy);
System.out.println("Forest Type: " + forest6.forestType);
System.out.println("Area: " + forest6.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest6.dominantSpecies);
System.out.println("Tiger Reserve: " + forest6.tigerReserve);
System.out.println("Tree Density: " + forest6.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest6.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest6.biodiversityHotspot);
System.out.println("Species Count: " + forest6.speciesCount);
System.out.println("Carbon Sequestration: " + forest6.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest6.climateZone);
System.out.println("Water Source: " + forest6.waterSource);
System.out.println("Soil Type: " + forest6.soilType);
System.out.println("Canopy Height: " + forest6.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest6.fireResistant);
System.out.println("Wildlife Corridor: " + forest6.wildlifeCorridor);
System.out.println("Camera Traps: " + forest6.cameraTraps);
System.out.println("Forest Division: " + forest6.forestDivision);
System.out.println("Annual Budget: " + forest6.annualBudget);
System.out.println("Emergency Contact: " + forest6.emergencyContact);
System.out.println("================================");
	
// Forest 7 - Dandeli Wildlife Sanctuary
Forest forest7 = new Forest();

forest7.forestId = 207;
forest7.location = "Dandeli Wildlife Sanctuary";
forest7.state = "Karnataka";
forest7.protectedArea = true;
forest7.declarationDate = "01/07/1963";
forest7.lastSurveyDate = "22/01/2026";
forest7.surveyDue = true;
forest7.managedBy = "Karnataka Forest Department";
forest7.forestType = "Moist Deciduous";
forest7.areaHectares = 475;
forest7.dominantSpecies = "Teak, Silver Oak";
forest7.tigerReserve = true;
forest7.treeDensity = 510;
forest7.conservationStatus = "IUCN Category IV";
forest7.biodiversityHotspot = true;
forest7.speciesCount = 310;
forest7.carbonSequestration = 11200.0;
forest7.climateZone = "Tropical";
forest7.waterSource = true;
forest7.soilType = "Black Cotton";
forest7.canopyHeight = 26;
forest7.fireResistant = true;
forest7.wildlifeCorridor = "Anshi-Dandeli";
forest7.cameraTraps = true;
forest7.forestDivision = "Kanara Circle";
forest7.annualBudget = 19500000.00;
forest7.emergencyContact = "08284-235221";

System.out.println("Forest ID: " + forest7.forestId);
System.out.println("Location: " + forest7.location);
System.out.println("State: " + forest7.state);
System.out.println("Protected Area: " + forest7.protectedArea);
System.out.println("Declaration Date: " + forest7.declarationDate);
System.out.println("Last Survey: " + forest7.lastSurveyDate);
System.out.println("Survey Due: " + forest7.surveyDue);
System.out.println("Managed By: " + forest7.managedBy);
System.out.println("Forest Type: " + forest7.forestType);
System.out.println("Area: " + forest7.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest7.dominantSpecies);
System.out.println("Tiger Reserve: " + forest7.tigerReserve);
System.out.println("Tree Density: " + forest7.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest7.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest7.biodiversityHotspot);
System.out.println("Species Count: " + forest7.speciesCount);
System.out.println("Carbon Sequestration: " + forest7.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest7.climateZone);
System.out.println("Water Source: " + forest7.waterSource);
System.out.println("Soil Type: " + forest7.soilType);
System.out.println("Canopy Height: " + forest7.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest7.fireResistant);
System.out.println("Wildlife Corridor: " + forest7.wildlifeCorridor);
System.out.println("Camera Traps: " + forest7.cameraTraps);
System.out.println("Forest Division: " + forest7.forestDivision);
System.out.println("Annual Budget: " + forest7.annualBudget);
System.out.println("Emergency Contact: " + forest7.emergencyContact);
System.out.println("================================");
	
	
// Forest 8 - Kabini Wildlife Sanctuary
Forest forest8 = new Forest();

forest8.forestId = 208;
forest8.location = "Kabini Wildlife Sanctuary";
forest8.state = "Karnataka";
forest8.protectedArea = true;
forest8.declarationDate = "01/05/1955";
forest8.lastSurveyDate = "28/02/2026";
forest8.surveyDue = false;
forest8.managedBy = "Karnataka Forest Department";
forest8.forestType = "Dry Deciduous";
forest8.areaHectares = 557;
forest8.dominantSpecies = "Teak, Rosewood";
forest8.tigerReserve = false;
forest8.treeDensity = 420;
forest8.conservationStatus = "IUCN Category IV";
forest8.biodiversityHotspot = true;
forest8.speciesCount = 290;
forest8.carbonSequestration = 9800.0;
forest8.climateZone = "Tropical";
forest8.waterSource = true;
forest8.soilType = "Red Loamy";
forest8.canopyHeight = 20;
forest8.fireResistant = true;
forest8.wildlifeCorridor = "Bandipur-Nagarhole";
forest8.cameraTraps = true;
forest8.forestDivision = "Mysore Circle";
forest8.annualBudget = 16500000.00;
forest8.emergencyContact = "08227-247221";

System.out.println("Forest ID: " + forest8.forestId);
System.out.println("Location: " + forest8.location);
System.out.println("State: " + forest8.state);
System.out.println("Protected Area: " + forest8.protectedArea);
System.out.println("Declaration Date: " + forest8.declarationDate);
System.out.println("Last Survey: " + forest8.lastSurveyDate);
System.out.println("Survey Due: " + forest8.surveyDue);
System.out.println("Managed By: " + forest8.managedBy);
System.out.println("Forest Type: " + forest8.forestType);
System.out.println("Area: " + forest8.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest8.dominantSpecies);
System.out.println("Tiger Reserve: " + forest8.tigerReserve);
System.out.println("Tree Density: " + forest8.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest8.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest8.biodiversityHotspot);
System.out.println("Species Count: " + forest8.speciesCount);
System.out.println("Carbon Sequestration: " + forest8.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest8.climateZone);
System.out.println("Water Source: " + forest8.waterSource);
System.out.println("Soil Type: " + forest8.soilType);
System.out.println("Canopy Height: " + forest8.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest8.fireResistant);
System.out.println("Wildlife Corridor: " + forest8.wildlifeCorridor);
System.out.println("Camera Traps: " + forest8.cameraTraps);
System.out.println("Forest Division: " + forest8.forestDivision);
System.out.println("Annual Budget: " + forest8.annualBudget);
System.out.println("Emergency Contact: " + forest8.emergencyContact);
System.out.println("================================");


// Forest 9 - Ranebennur Blackbuck Sanctuary
Forest forest9 = new Forest();

forest9.forestId = 209;
forest9.location = "Ranebennur Blackbuck Sanctuary";
forest9.state = "Karnataka";
forest9.protectedArea = true;
forest9.declarationDate = "01/04/1974";
forest9.lastSurveyDate = "12/03/2026";
forest9.surveyDue = false;
forest9.managedBy = "Karnataka Forest Department";
forest9.forestType = "Grassland";
forest9.areaHectares = 119;
forest9.dominantSpecies = "Acacia, Grasslands";
forest9.tigerReserve = false;
forest9.treeDensity = 180;
forest9.conservationStatus = "IUCN Category IV";
forest9.biodiversityHotspot = false;
forest9.speciesCount = 210;
forest9.carbonSequestration = 4500.0;
forest9.climateZone = "Semi-Arid";
forest9.waterSource = true;
forest9.soilType = "Black Cotton";
forest9.canopyHeight = 8;
forest9.fireResistant = true;
forest9.wildlifeCorridor = "Deccan Plateau";
forest9.cameraTraps = false;
forest9.forestDivision = " Haveri Circle";
forest9.annualBudget = 8500000.00;
forest9.emergencyContact = "08375-232221";

System.out.println("Forest ID: " + forest9.forestId);
System.out.println("Location: " + forest9.location);
System.out.println("State: " + forest9.state);
System.out.println("Protected Area: " + forest9.protectedArea);
System.out.println("Declaration Date: " + forest9.declarationDate);
System.out.println("Last Survey: " + forest9.lastSurveyDate);
System.out.println("Survey Due: " + forest9.surveyDue);
System.out.println("Managed By: " + forest9.managedBy);
System.out.println("Forest Type: " + forest9.forestType);
System.out.println("Area: " + forest9.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest9.dominantSpecies);
System.out.println("Tiger Reserve: " + forest9.tigerReserve);
System.out.println("Tree Density: " + forest9.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest9.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest9.biodiversityHotspot);
System.out.println("Species Count: " + forest9.speciesCount);
System.out.println("Carbon Sequestration: " + forest9.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest9.climateZone);
System.out.println("Water Source: " + forest9.waterSource);
System.out.println("Soil Type: " + forest9.soilType);
System.out.println("Canopy Height: " + forest9.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest9.fireResistant);
System.out.println("Wildlife Corridor: " + forest9.wildlifeCorridor);
System.out.println("Camera Traps: " + forest9.cameraTraps);
System.out.println("Forest Division: " + forest9.forestDivision);
System.out.println("Annual Budget: " + forest9.annualBudget);
System.out.println("Emergency Contact: " + forest9.emergencyContact);
System.out.println("================================");


// Forest 10 - Cauvery Wildlife Sanctuary
Forest forest10 = new Forest();

forest10.forestId = 210;
forest10.location = "Cauvery Wildlife Sanctuary";
forest10.state = "Karnataka";
forest10.protectedArea = true;
forest10.declarationDate = "01/04/1987";
forest10.lastSurveyDate = "15/03/2026";
forest10.surveyDue = false;
forest10.managedBy = "Karnataka Forest Department";
forest10.forestType = "Dry Deciduous";
forest10.areaHectares = 1028;
forest10.dominantSpecies = "Teak, Sandalwood";
forest10.tigerReserve = true;
forest10.treeDensity = 410;
forest10.conservationStatus = "IUCN Category IV";
forest10.biodiversityHotspot = true;
forest10.speciesCount = 265;
forest10.carbonSequestration = 10500.0;
forest10.climateZone = "Tropical";
forest10.waterSource = true;
forest10.soilType = "Red Sandy";
forest10.canopyHeight = 21;
forest10.fireResistant = true;
forest10.wildlifeCorridor = "Cauvery-MM Hills";
forest10.cameraTraps = true;
forest10.forestDivision = "Kollegal Circle";
forest10.annualBudget = 17500000.00;
forest10.emergencyContact = "08234-252221";

System.out.println("Forest ID: " + forest10.forestId);
System.out.println("Location: " + forest10.location);
System.out.println("State: " + forest10.state);
System.out.println("Protected Area: " + forest10.protectedArea);
System.out.println("Declaration Date: " + forest10.declarationDate);
System.out.println("Last Survey: " + forest10.lastSurveyDate);
System.out.println("Survey Due: " + forest10.surveyDue);
System.out.println("Managed By: " + forest10.managedBy);
System.out.println("Forest Type: " + forest10.forestType);
System.out.println("Area: " + forest10.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest10.dominantSpecies);
System.out.println("Tiger Reserve: " + forest10.tigerReserve);
System.out.println("Tree Density: " + forest10.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest10.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest10.biodiversityHotspot);
System.out.println("Species Count: " + forest10.speciesCount);
System.out.println("Carbon Sequestration: " + forest10.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest10.climateZone);
System.out.println("Water Source: " + forest10.waterSource);
System.out.println("Soil Type: " + forest10.soilType);
System.out.println("Canopy Height: " + forest10.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest10.fireResistant);
System.out.println("Wildlife Corridor: " + forest10.wildlifeCorridor);
System.out.println("Camera Traps: " + forest10.cameraTraps);
System.out.println("Forest Division: " + forest10.forestDivision);
System.out.println("Annual Budget: " + forest10.annualBudget);
System.out.println("Emergency Contact: " + forest10.emergencyContact);
System.out.println("================================");


// Forest 11 - MM Hills Wildlife Sanctuary
Forest forest11 = new Forest();

forest11.forestId = 211;
forest11.location = "MM Hills Wildlife Sanctuary";
forest11.state = "Karnataka";
forest11.protectedArea = true;
forest11.declarationDate = "01/10/1974";
forest11.lastSurveyDate = "20/02/2026";
forest11.surveyDue = true;
forest11.managedBy = "Karnataka Forest Department";
forest11.forestType = "Dry Thorn Scrub";
forest11.areaHectares = 64;
forest11.dominantSpecies = "Acacia, Neem";
forest11.tigerReserve = false;
forest11.treeDensity = 290;
forest11.conservationStatus = "IUCN Category IV";
forest11.biodiversityHotspot = true;
forest11.speciesCount = 195;
forest11.carbonSequestration = 6200.0;
forest11.climateZone = "Semi-Arid";
forest11.waterSource = true;
forest11.soilType = "Rocky Outcrops";
forest11.canopyHeight = 12;
forest11.fireResistant = true;
forest11.wildlifeCorridor = "Cauvery-MM Hills";
forest11.cameraTraps = true;
forest11.forestDivision = "Kollegal Circle";
forest11.annualBudget = 9500000.00;
forest11.emergencyContact = "08234-261221";

System.out.println("Forest ID: " + forest11.forestId);
System.out.println("Location: " + forest11.location);
System.out.println("State: " + forest11.state);
System.out.println("Protected Area: " + forest11.protectedArea);
System.out.println("Declaration Date: " + forest11.declarationDate);
System.out.println("Last Survey: " + forest11.lastSurveyDate);
System.out.println("Survey Due: " + forest11.surveyDue);
System.out.println("Managed By: " + forest11.managedBy);
System.out.println("Forest Type: " + forest11.forestType);
System.out.println("Area: " + forest11.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest11.dominantSpecies);
System.out.println("Tiger Reserve: " + forest11.tigerReserve);
System.out.println("Tree Density: " + forest11.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest11.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest11.biodiversityHotspot);
System.out.println("Species Count: " + forest11.speciesCount);
System.out.println("Carbon Sequestration: " + forest11.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest11.climateZone);
System.out.println("Water Source: " + forest11.waterSource);
System.out.println("Soil Type: " + forest11.soilType);
System.out.println("Canopy Height: " + forest11.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest11.fireResistant);
System.out.println("Wildlife Corridor: " + forest11.wildlifeCorridor);
System.out.println("Camera Traps: " + forest11.cameraTraps);
System.out.println("Forest Division: " + forest11.forestDivision);
System.out.println("Annual Budget: " + forest11.annualBudget);
System.out.println("Emergency Contact: " + forest11.emergencyContact);
System.out.println("================================");


// Forest 12 - Sharavathi Valley Wildlife Sanctuary
Forest forest12 = new Forest();

forest12.forestId = 212;
forest12.location = "Sharavathi Valley Wildlife Sanctuary";
forest12.state = "Karnataka";
forest12.protectedArea = true;
forest12.declarationDate = "15/07/1978";
forest12.lastSurveyDate = "25/02/2026";
forest12.surveyDue = false;
forest12.managedBy = "Karnataka Forest Department";
forest12.forestType = "Evergreen Rainforest";
forest12.areaHectares = 1080;
forest12.dominantSpecies = "Rosewood, Mahogany, Teak";
forest12.tigerReserve = false;
forest12.treeDensity = 610;
forest12.conservationStatus = "IUCN Category IV";
forest12.biodiversityHotspot = true;
forest12.speciesCount = 340;
forest12.carbonSequestration = 15200.0;
forest12.climateZone = "Tropical Wet";
forest12.waterSource = true;
forest12.soilType = "Laterite";
forest12.canopyHeight = 38;
forest12.fireResistant = false;
forest12.wildlifeCorridor = "Western Ghats";
forest12.cameraTraps = true;
forest12.forestDivision = "Sirsi Circle";
forest12.annualBudget = 26500000.00;
forest12.emergencyContact = "08386-242221";

System.out.println("Forest ID: " + forest12.forestId);
System.out.println("Location: " + forest12.location);
System.out.println("State: " + forest12.state);
System.out.println("Protected Area: " + forest12.protectedArea);
System.out.println("Declaration Date: " + forest12.declarationDate);
System.out.println("Last Survey: " + forest12.lastSurveyDate);
System.out.println("Survey Due: " + forest12.surveyDue);
System.out.println("Managed By: " + forest12.managedBy);
System.out.println("Forest Type: " + forest12.forestType);
System.out.println("Area: " + forest12.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest12.dominantSpecies);
System.out.println("Tiger Reserve: " + forest12.tigerReserve);
System.out.println("Tree Density: " + forest12.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest12.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest12.biodiversityHotspot);
System.out.println("Species Count: " + forest12.speciesCount);
System.out.println("Carbon Sequestration: " + forest12.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest12.climateZone);
System.out.println("Water Source: " + forest12.waterSource);
System.out.println("Soil Type: " + forest12.soilType);
System.out.println("Canopy Height: " + forest12.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest12.fireResistant);
System.out.println("Wildlife Corridor: " + forest12.wildlifeCorridor);
System.out.println("Camera Traps: " + forest12.cameraTraps);
System.out.println("Forest Division: " + forest12.forestDivision);
System.out.println("Annual Budget: " + forest12.annualBudget);
System.out.println("Emergency Contact: " + forest12.emergencyContact);
System.out.println("================================");



// Forest 13 - Attappady Valley Forest
Forest forest13 = new Forest();

forest13.forestId = 213;
forest13.location = "Attappady Valley Forest";
forest13.state = "Karnataka";
forest13.protectedArea = true;
forest13.declarationDate = "22/11/1985";
forest13.lastSurveyDate = "18/03/2026";
forest13.surveyDue = false;
forest13.managedBy = "Karnataka Forest Department";
forest13.forestType = "Moist Deciduous";
forest13.areaHectares = 850;
forest13.dominantSpecies = "Teak, Bamboo, Rosewood";
forest13.tigerReserve = true;
forest13.treeDensity = 460;
forest13.conservationStatus = "IUCN Category IV";
forest13.biodiversityHotspot = true;
forest13.speciesCount = 305;
forest13.carbonSequestration = 12800.0;
forest13.climateZone = "Tropical";
forest13.waterSource = true;
forest13.soilType = "Red Loamy";
forest13.canopyHeight = 24;
forest13.fireResistant = true;
forest13.wildlifeCorridor = "Western Ghats";
forest13.cameraTraps = true;
forest13.forestDivision = "Mysore Circle";
forest13.annualBudget = 21000000.00;
forest13.emergencyContact = "08224-268221";

System.out.println("Forest ID: " + forest13.forestId);
System.out.println("Location: " + forest13.location);
System.out.println("State: " + forest13.state);
System.out.println("Protected Area: " + forest13.protectedArea);
System.out.println("Declaration Date: " + forest13.declarationDate);
System.out.println("Last Survey: " + forest13.lastSurveyDate);
System.out.println("Survey Due: " + forest13.surveyDue);
System.out.println("Managed By: " + forest13.managedBy);
System.out.println("Forest Type: " + forest13.forestType);
System.out.println("Area: " + forest13.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest13.dominantSpecies);
System.out.println("Tiger Reserve: " + forest13.tigerReserve);
System.out.println("Tree Density: " + forest13.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest13.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest13.biodiversityHotspot);
System.out.println("Species Count: " + forest13.speciesCount);
System.out.println("Carbon Sequestration: " + forest13.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest13.climateZone);
System.out.println("Water Source: " + forest13.waterSource);
System.out.println("Soil Type: " + forest13.soilType);
System.out.println("Canopy Height: " + forest13.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest13.fireResistant);
System.out.println("Wildlife Corridor: " + forest13.wildlifeCorridor);
System.out.println("Camera Traps: " + forest13.cameraTraps);
System.out.println("Forest Division: " + forest13.forestDivision);
System.out.println("Annual Budget: " + forest13.annualBudget);
System.out.println("Emergency Contact: " + forest13.emergencyContact);
System.out.println("================================");


// Forest 14 - BRT Wildlife Sanctuary
Forest forest14 = new Forest();

forest14.forestId = 214;
forest14.location = "BRT Wildlife Sanctuary";
forest14.state = "Karnataka";
forest14.protectedArea = true;
forest14.declarationDate = "25/01/1987";
forest14.lastSurveyDate = "22/02/2026";
forest14.surveyDue = false;
forest14.managedBy = "Karnataka Forest Department";
forest14.forestType = "Mixed Deciduous";
forest14.areaHectares = 575;
forest14.dominantSpecies = "Teak, Sandalwood, Bamboo";
forest14.tigerReserve = true;
forest14.treeDensity = 440;
forest14.conservationStatus = "IUCN Category IV";
forest14.biodiversityHotspot = true;
forest14.speciesCount = 320;
forest14.carbonSequestration = 11500.0;
forest14.climateZone = "Tropical";
forest14.waterSource = true;
forest14.soilType = "Laterite";
forest14.canopyHeight = 23;
forest14.fireResistant = true;
forest14.wildlifeCorridor = "BRT-MM Hills";
forest14.cameraTraps = true;
forest14.forestDivision = "Chamarajanagar Circle";
forest14.annualBudget = 19800000.00;
forest14.emergencyContact = "08226-245221";

System.out.println("Forest ID: " + forest14.forestId);
System.out.println("Location: " + forest14.location);
System.out.println("State: " + forest14.state);
System.out.println("Protected Area: " + forest14.protectedArea);
System.out.println("Declaration Date: " + forest14.declarationDate);
System.out.println("Last Survey: " + forest14.lastSurveyDate);
System.out.println("Survey Due: " + forest14.surveyDue);
System.out.println("Managed By: " + forest14.managedBy);
System.out.println("Forest Type: " + forest14.forestType);
System.out.println("Area: " + forest14.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest14.dominantSpecies);
System.out.println("Tiger Reserve: " + forest14.tigerReserve);
System.out.println("Tree Density: " + forest14.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest14.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest14.biodiversityHotspot);
System.out.println("Species Count: " + forest14.speciesCount);
System.out.println("Carbon Sequestration: " + forest14.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest14.climateZone);
System.out.println("Water Source: " + forest14.waterSource);
System.out.println("Soil Type: " + forest14.soilType);
System.out.println("Canopy Height: " + forest14.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest14.fireResistant);
System.out.println("Wildlife Corridor: " + forest14.wildlifeCorridor);
System.out.println("Camera Traps: " + forest14.cameraTraps);
System.out.println("Forest Division: " + forest14.forestDivision);
System.out.println("Annual Budget: " + forest14.annualBudget);
System.out.println("Emergency Contact: " + forest14.emergencyContact);
System.out.println("================================");



// Forest 15 - Nugu Wildlife Sanctuary
Forest forest15 = new Forest();

forest15.forestId = 215;
forest15.location = "Nugu Wildlife Sanctuary";
forest15.state = "Karnataka";
forest15.protectedArea = true;
forest15.declarationDate = "01/04/1955";
forest15.lastSurveyDate = "28/01/2026";
forest15.surveyDue = true;
forest15.managedBy = "Karnataka Forest Department";
forest15.forestType = "Dry Deciduous";
forest15.areaHectares = 30500;
forest15.dominantSpecies = "Teak, Acacia";
forest15.tigerReserve = false;
forest15.treeDensity = 390;
forest15.conservationStatus = "IUCN Category IV";
forest15.biodiversityHotspot = true;
forest15.speciesCount = 275;
forest15.carbonSequestration = 9800.0;
forest15.climateZone = "Tropical";
forest15.waterSource = true;
forest15.soilType = "Black Soil";
forest15.canopyHeight = 19;
forest15.fireResistant = true;
forest15.wildlifeCorridor = "Bandipur-Nugu";
forest15.cameraTraps = true;
forest15.forestDivision = "Mysore Circle";
forest15.annualBudget = 14200000.00;
forest15.emergencyContact = "08227-238221";

System.out.println("Forest ID: " + forest15.forestId);
System.out.println("Location: " + forest15.location);
System.out.println("State: " + forest15.state);
System.out.println("Protected Area: " + forest15.protectedArea);
System.out.println("Declaration Date: " + forest15.declarationDate);
System.out.println("Last Survey: " + forest15.lastSurveyDate);
System.out.println("Survey Due: " + forest15.surveyDue);
System.out.println("Managed By: " + forest15.managedBy);
System.out.println("Forest Type: " + forest15.forestType);
System.out.println("Area: " + forest15.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest15.dominantSpecies);
System.out.println("Tiger Reserve: " + forest15.tigerReserve);
System.out.println("Tree Density: " + forest15.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest15.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest15.biodiversityHotspot);
System.out.println("Species Count: " + forest15.speciesCount);
System.out.println("Carbon Sequestration: " + forest15.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest15.climateZone);
System.out.println("Water Source: " + forest15.waterSource);
System.out.println("Soil Type: " + forest15.soilType);
System.out.println("Canopy Height: " + forest15.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest15.fireResistant);
System.out.println("Wildlife Corridor: " + forest15.wildlifeCorridor);
System.out.println("Camera Traps: " + forest15.cameraTraps);
System.out.println("Forest Division: " + forest15.forestDivision);
System.out.println("Annual Budget: " + forest15.annualBudget);
System.out.println("Emergency Contact: " + forest15.emergencyContact);
System.out.println("================================");




// Forest 16 - Western Ghat Shola Forest
Forest forest16 = new Forest();

forest16.forestId = 216;
forest16.location = "Western Ghat Shola Forest";
forest16.state = "Karnataka";
forest16.protectedArea = true;
forest16.declarationDate = "12/06/1988";
forest16.lastSurveyDate = "02/03/2026";
forest16.surveyDue = false;
forest16.managedBy = "Karnataka Forest Department";
forest16.forestType = "Montane Shola";
forest16.areaHectares = 420;
forest16.dominantSpecies = "Shola Trees, Rhododendron";
forest16.tigerReserve = false;
forest16.treeDensity = 720;
forest16.conservationStatus = "IUCN Category I";
forest16.biodiversityHotspot = true;
forest16.speciesCount = 450;
forest16.carbonSequestration = 16800.0;
forest16.climateZone = "Montane";
forest16.waterSource = true;
forest16.soilType = "Humus Rich";
forest16.canopyHeight = 42;
forest16.fireResistant = false;
forest16.wildlifeCorridor = "Nilgiri Biosphere";
forest16.cameraTraps = true;
forest16.forestDivision = "Kodagu Circle";
forest16.annualBudget = 28500000.00;
forest16.emergencyContact = "08272-238221";

System.out.println("Forest ID: " + forest16.forestId);
System.out.println("Location: " + forest16.location);
System.out.println("State: " + forest16.state);
System.out.println("Protected Area: " + forest16.protectedArea);
System.out.println("Declaration Date: " + forest16.declarationDate);
System.out.println("Last Survey: " + forest16.lastSurveyDate);
System.out.println("Survey Due: " + forest16.surveyDue);
System.out.println("Managed By: " + forest16.managedBy);
System.out.println("Forest Type: " + forest16.forestType);
System.out.println("Area: " + forest16.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest16.dominantSpecies);
System.out.println("Tiger Reserve: " + forest16.tigerReserve);
System.out.println("Tree Density: " + forest16.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest16.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest16.biodiversityHotspot);
System.out.println("Species Count: " + forest16.speciesCount);
System.out.println("Carbon Sequestration: " + forest16.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest16.climateZone);
System.out.println("Water Source: " + forest16.waterSource);
System.out.println("Soil Type: " + forest16.soilType);
System.out.println("Canopy Height: " + forest16.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest16.fireResistant);
System.out.println("Wildlife Corridor: " + forest16.wildlifeCorridor);
System.out.println("Camera Traps: " + forest16.cameraTraps);
System.out.println("Forest Division: " + forest16.forestDivision);
System.out.println("Annual Budget: " + forest16.annualBudget);
System.out.println("Emergency Contact: " + forest16.emergencyContact);
System.out.println("================================");


// Forest 17 - Pushpagiri Wildlife Sanctuary
Forest forest17 = new Forest();

forest17.forestId = 217;
forest17.location = "Pushpagiri Wildlife Sanctuary";
forest17.state = "Karnataka";
forest17.protectedArea = true;
forest17.declarationDate = "29/06/1987";
forest17.lastSurveyDate = "08/03/2026";
forest17.surveyDue = false;
forest17.managedBy = "Karnataka Forest Department";
forest17.forestType = "Evergreen Rainforest";
forest17.areaHectares = 102;
forest17.dominantSpecies = "Dipterocarpus, Hopea";
forest17.tigerReserve = false;
forest17.treeDensity = 680;
forest17.conservationStatus = "IUCN Category IV";
forest17.biodiversityHotspot = true;
forest17.speciesCount = 380;
forest17.carbonSequestration = 14200.0;
forest17.climateZone = "Tropical Wet";
forest17.waterSource = true;
forest17.soilType = "Alluvial Loam";
forest17.canopyHeight = 36;
forest17.fireResistant = false;
forest17.wildlifeCorridor = "Western Ghats";
forest17.cameraTraps = true;
forest17.forestDivision = "Kodagu Circle";
forest17.annualBudget = 17200000.00;
forest17.emergencyContact = "08272-249221";

System.out.println("Forest ID: " + forest17.forestId);
System.out.println("Location: " + forest17.location);
System.out.println("State: " + forest17.state);
System.out.println("Protected Area: " + forest17.protectedArea);
System.out.println("Declaration Date: " + forest17.declarationDate);
System.out.println("Last Survey: " + forest17.lastSurveyDate);
System.out.println("Survey Due: " + forest17.surveyDue);
System.out.println("Managed By: " + forest17.managedBy);
System.out.println("Forest Type: " + forest17.forestType);
System.out.println("Area: " + forest17.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest17.dominantSpecies);
System.out.println("Tiger Reserve: " + forest17.tigerReserve);
System.out.println("Tree Density: " + forest17.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest17.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest17.biodiversityHotspot);
System.out.println("Species Count: " + forest17.speciesCount);
System.out.println("Carbon Sequestration: " + forest17.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest17.climateZone);
System.out.println("Water Source: " + forest17.waterSource);
System.out.println("Soil Type: " + forest17.soilType);
System.out.println("Canopy Height: " + forest17.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest17.fireResistant);
System.out.println("Wildlife Corridor: " + forest17.wildlifeCorridor);
System.out.println("Camera Traps: " + forest17.cameraTraps);
System.out.println("Forest Division: " + forest17.forestDivision);
System.out.println("Annual Budget: " + forest17.annualBudget);
System.out.println("Emergency Contact: " + forest17.emergencyContact);
System.out.println("================================");

// Forest 18 - Brahmagiri Wildlife Sanctuary
Forest forest18 = new Forest();

forest18.forestId = 218;
forest18.location = "Brahmagiri Wildlife Sanctuary";
forest18.state = "Karnataka";
forest18.protectedArea = true;
forest18.declarationDate = "15/06/1974";
forest18.lastSurveyDate = "10/03/2026";
forest18.surveyDue = false;
forest18.managedBy = "Karnataka Forest Department";
forest18.forestType = "Evergreen Rainforest";
forest18.areaHectares = 181;
forest18.dominantSpecies = "Rosewood, Laurel, Canarium";
forest18.tigerReserve = false;
forest18.treeDensity = 640;
forest18.conservationStatus = "IUCN Category IV";
forest18.biodiversityHotspot = true;
forest18.speciesCount = 360;
forest18.carbonSequestration = 13500.0;
forest18.climateZone = "Tropical Wet";
forest18.waterSource = true;
forest18.soilType = "Lateritic Loam";
forest18.canopyHeight = 34;
forest18.fireResistant = false;
forest18.wildlifeCorridor = "Nagarhole-Brahmagiri";
forest18.cameraTraps = true;
forest18.forestDivision = "Kodagu Circle";
forest18.annualBudget = 18500000.00;
forest18.emergencyContact = "08272-255221";

System.out.println("Forest ID: " + forest18.forestId);
System.out.println("Location: " + forest18.location);
System.out.println("State: " + forest18.state);
System.out.println("Protected Area: " + forest18.protectedArea);
System.out.println("Declaration Date: " + forest18.declarationDate);
System.out.println("Last Survey: " + forest18.lastSurveyDate);
System.out.println("Survey Due: " + forest18.surveyDue);
System.out.println("Managed By: " + forest18.managedBy);
System.out.println("Forest Type: " + forest18.forestType);
System.out.println("Area: " + forest18.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest18.dominantSpecies);
System.out.println("Tiger Reserve: " + forest18.tigerReserve);
System.out.println("Tree Density: " + forest18.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest18.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest18.biodiversityHotspot);
System.out.println("Species Count: " + forest18.speciesCount);
System.out.println("Carbon Sequestration: " + forest18.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest18.climateZone);
System.out.println("Water Source: " + forest18.waterSource);
System.out.println("Soil Type: " + forest18.soilType);
System.out.println("Canopy Height: " + forest18.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest18.fireResistant);
System.out.println("Wildlife Corridor: " + forest18.wildlifeCorridor);
System.out.println("Camera Traps: " + forest18.cameraTraps);
System.out.println("Forest Division: " + forest18.forestDivision);
System.out.println("Annual Budget: " + forest18.annualBudget);
System.out.println("Emergency Contact: " + forest18.emergencyContact);
System.out.println("================================");



// Forest 19 - Someshwara Wildlife Sanctuary
Forest forest19 = new Forest();

forest19.forestId = 219;
forest19.location = "Someshwara Wildlife Sanctuary";
forest19.state = "Karnataka";
forest19.protectedArea = true;
forest19.declarationDate = "01/07/1974";
forest19.lastSurveyDate = "15/02/2026";
forest19.surveyDue = true;
forest19.managedBy = "Karnataka Forest Department";
forest19.forestType = "Moist Deciduous";
forest19.areaHectares = 314;
forest19.dominantSpecies = "Teak, Rosewood, Bamboo";
forest19.tigerReserve = false;
forest19.treeDensity = 530;
forest19.conservationStatus = "IUCN Category IV";
forest19.biodiversityHotspot = true;
forest19.speciesCount = 295;
forest19.carbonSequestration = 11900.0;
forest19.climateZone = "Tropical";
forest19.waterSource = true;
forest19.soilType = "Red Sandy Loam";
forest19.canopyHeight = 27;
forest19.fireResistant = true;
forest19.wildlifeCorridor = "Agumbe-Someshwara";
forest19.cameraTraps = true;
forest19.forestDivision = "Shivamogga Circle";
forest19.annualBudget = 16200000.00;
forest19.emergencyContact = "08183-246221";
 
 
System.out.println("Forest ID: " + forest19.forestId);
System.out.println("Location: " + forest19.location);
System.out.println("State: " + forest19.state);
System.out.println("Protected Area: " + forest19.protectedArea);
System.out.println("Declaration Date: " + forest19.declarationDate);
System.out.println("Last Survey: " + forest19.lastSurveyDate);
System.out.println("Survey Due: " + forest19.surveyDue);
System.out.println("Managed By: " + forest19.managedBy);
System.out.println("Forest Type: " + forest19.forestType);
System.out.println("Area: " + forest19.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest19.dominantSpecies);
System.out.println("Tiger Reserve: " + forest19.tigerReserve);
System.out.println("Tree Density: " + forest19.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest19.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest19.biodiversityHotspot);
System.out.println("Species Count: " + forest19.speciesCount);
System.out.println("Carbon Sequestration: " + forest19.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest19.climateZone);
System.out.println("Water Source: " + forest19.waterSource);
System.out.println("Soil Type: " + forest19.soilType);
System.out.println("Canopy Height: " + forest19.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest19.fireResistant);
System.out.println("Wildlife Corridor: " + forest19.wildlifeCorridor);
System.out.println("Camera Traps: " + forest19.cameraTraps);
System.out.println("Forest Division: " + forest19.forestDivision);
System.out.println("Annual Budget: " + forest19.annualBudget);
System.out.println("Emergency Contact: " + forest19.emergencyContact);
System.out.println("================================");


// Forest 20 - Agumbe Rainforest Reserve
Forest forest20 = new Forest();

forest20.forestId = 220;
forest20.location = "Agumbe Rainforest Reserve";
forest20.state = "Karnataka";
forest20.protectedArea = true;
forest20.declarationDate = "01/11/1974";
forest20.lastSurveyDate = "20/03/2026";
forest20.surveyDue = false;
forest20.managedBy = "Karnataka Forest Department";
forest20.forestType = "West Coast Tropical Rainforest";
forest20.areaHectares = 105;
forest20.dominantSpecies = "King Cobra Habitat, Evergreen Trees";
forest20.tigerReserve = false;
forest20.treeDensity = 710;
forest20.conservationStatus = "IUCN Category IV";
forest20.biodiversityHotspot = true;
forest20.speciesCount = 410;
forest20.carbonSequestration = 16200.0;
forest20.climateZone = "Tropical Wettest";
forest20.waterSource = true;
forest20.soilType = "Humus Rich Laterite";
forest20.canopyHeight = 40;
forest20.fireResistant = false;
forest20.wildlifeCorridor = "Someshwara-Agumbe";
forest20.cameraTraps = true;
forest20.forestDivision = "Shivamogga Circle";
forest20.annualBudget = 19500000.00;
forest20.emergencyContact = "08182-221221";


System.out.println("Forest ID: " + forest20.forestId);
System.out.println("Location: " + forest20.location);
System.out.println("State: " + forest20.state);
System.out.println("Protected Area: " + forest20.protectedArea);
System.out.println("Declaration Date: " + forest20.declarationDate);
System.out.println("Last Survey: " + forest20.lastSurveyDate);
System.out.println("Survey Due: " + forest20.surveyDue);
System.out.println("Managed By: " + forest20.managedBy);
System.out.println("Forest Type: " + forest20.forestType);
System.out.println("Area: " + forest20.areaHectares + " hectares");
System.out.println("Dominant Species: " + forest20.dominantSpecies);
System.out.println("Tiger Reserve: " + forest20.tigerReserve);
System.out.println("Tree Density: " + forest20.treeDensity + " trees/hectare");
System.out.println("Conservation Status: " + forest20.conservationStatus);
System.out.println("Biodiversity Hotspot: " + forest20.biodiversityHotspot);
System.out.println("Species Count: " + forest20.speciesCount);
System.out.println("Carbon Sequestration: " + forest20.carbonSequestration + " tons/year");
System.out.println("Climate Zone: " + forest20.climateZone);
System.out.println("Water Source: " + forest20.waterSource);
System.out.println("Soil Type: " + forest20.soilType);
System.out.println("Canopy Height: " + forest20.canopyHeight + " meters");
System.out.println("Fire Resistant: " + forest20.fireResistant);
System.out.println("Wildlife Corridor: " + forest20.wildlifeCorridor);
System.out.println("Camera Traps: " + forest20.cameraTraps);
System.out.println("Forest Division: " + forest20.forestDivision);
System.out.println("Annual Budget: " + forest20.annualBudget);
System.out.println("Emergency Contact: " + forest20.emergencyContact);
System.out.println("================================");

	
		
		
		
    }
}
