class GameInfoExecutor {
    public static void main(String[] games) {
	
        GameInfo game1 = new GameInfo();
        game1.setId(1);
        System.out.println("ID: " + game1.getId());
        game1.setGameName("GTA VI");
        System.out.println("Game Name: " + game1.getGameName());
        game1.setPlatform("PS5, Xbox Series X");
        System.out.println("Platform: " + game1.getPlatform());
        game1.setGenre("Open World Action");
        System.out.println("Genre: " + game1.getGenre());
        game1.setReleaseDate("2026-05-26");
        System.out.println("Release Date: " + game1.getReleaseDate());
        game1.setDeveloper("Rockstar North");
        System.out.println("Developer: " + game1.getDeveloper());
        game1.setPublisher("Rockstar Games");
        System.out.println("Publisher: " + game1.getPublisher());
        game1.setRating("Mature 17+");
        System.out.println("Rating: " + game1.getRating());
        System.out.println();

        GameInfo game2 = new GameInfo();
        game2.setId(2);
        System.out.println("ID: " + game2.getId());
        game2.setGameName("God of War Ragnarok");
        System.out.println("Game Name: " + game2.getGameName());
        game2.setPlatform("PS5, PC");
        System.out.println("Platform: " + game2.getPlatform());
        game2.setGenre("Action Adventure");
        System.out.println("Genre: " + game2.getGenre());
        game2.setReleaseDate("2022-11-09");
        System.out.println("Release Date: " + game2.getReleaseDate());
        game2.setDeveloper("Santa Monica Studio");
        System.out.println("Developer: " + game2.getDeveloper());
        game2.setPublisher("Sony Interactive");
        System.out.println("Publisher: " + game2.getPublisher());
        game2.setRating("Mature 17+");
        System.out.println("Rating: " + game2.getRating());
        System.out.println();

        GameInfo game3 = new GameInfo();
        game3.setId(3);
        System.out.println("ID: " + game3.getId());
        game3.setGameName("Elden Ring");
        System.out.println("Game Name: " + game3.getGameName());
        game3.setPlatform("PS5, Xbox, PC");
        System.out.println("Platform: " + game3.getPlatform());
        game3.setGenre("Action RPG");
        System.out.println("Genre: " + game3.getGenre());
        game3.setReleaseDate("2022-02-25");
        System.out.println("Release Date: " + game3.getReleaseDate());
        game3.setDeveloper("FromSoftware");
        System.out.println("Developer: " + game3.getDeveloper());
        game3.setPublisher("Bandai Namco");
        System.out.println("Publisher: " + game3.getPublisher());
        game3.setRating("Mature 17+");
        System.out.println("Rating: " + game3.getRating());
        System.out.println();

        GameInfo game4 = new GameInfo();
        game4.setId(4);
        System.out.println("ID: " + game4.getId());
        game4.setGameName("BGMI India Season 6");
        System.out.println("Game Name: " + game4.getGameName());
        game4.setPlatform("Android, iOS");
        System.out.println("Platform: " + game4.getPlatform());
        game4.setGenre("Battle Royale");
        System.out.println("Genre: " + game4.getGenre());
        game4.setReleaseDate("2026-03-15");
        System.out.println("Release Date: " + game4.getReleaseDate());
        game4.setDeveloper("Krafton India");
        System.out.println("Developer: " + game4.getDeveloper());
        game4.setPublisher("Krafton");
        System.out.println("Publisher: " + game4.getPublisher());
        game4.setRating("Teen");
        System.out.println("Rating: " + game4.getRating());
        System.out.println();

        GameInfo game5 = new GameInfo();
        game5.setId(5);
        System.out.println("ID: " + game5.getId());
        game5.setGameName("Valorant Episode 9");
        System.out.println("Game Name: " + game5.getGameName());
        game5.setPlatform("PC");
        System.out.println("Platform: " + game5.getPlatform());
        game5.setGenre("Tactical FPS");
        System.out.println("Genre: " + game5.getGenre());
        game5.setReleaseDate("2026-01-07");
        System.out.println("Release Date: " + game5.getReleaseDate());
        game5.setDeveloper("Riot Games");
        System.out.println("Developer: " + game5.getDeveloper());
        game5.setPublisher("Riot Games");
        System.out.println("Publisher: " + game5.getPublisher());
        game5.setRating("Teen");
        System.out.println("Rating: " + game5.getRating());
        System.out.println();
		
		GameInfo game6 = new GameInfo();
        game6.setId(6);
        System.out.println("ID: " + game6.getId());
        game6.setGameName("Forza Horizon 6");
        System.out.println("Game Name: " + game6.getGameName());
        game6.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game6.getPlatform());
        game6.setGenre("Racing Open World");
        System.out.println("Genre: " + game6.getGenre());
        game6.setReleaseDate("2026-05-19");
        System.out.println("Release Date: " + game6.getReleaseDate());
        game6.setDeveloper("Playground Games");
        System.out.println("Developer: " + game6.getDeveloper());
        game6.setPublisher("Xbox Game Studios");
        System.out.println("Publisher: " + game6.getPublisher());
        game6.setRating("Everyone");
        System.out.println("Rating: " + game6.getRating());
        System.out.println();

        GameInfo game7 = new GameInfo();
        game7.setId(7);
        System.out.println("ID: " + game7.getId());
        game7.setGameName("Fable");
        System.out.println("Game Name: " + game7.getGameName());
        game7.setPlatform("PC, Xbox Series X");
        System.out.println("Platform: " + game7.getPlatform());
        game7.setGenre("Action RPG");
        System.out.println("Genre: " + game7.getGenre());
        game7.setReleaseDate("2026-Q4");
        System.out.println("Release Date: " + game7.getReleaseDate());
        game7.setDeveloper("Playground Games");
        System.out.println("Developer: " + game7.getDeveloper());
        game7.setPublisher("Xbox Game Studios");
        game7.setRating("Mature 17+");
        System.out.println("Rating: " + game7.getRating());
        System.out.println();

        GameInfo game8 = new GameInfo();
        game8.setId(8);
        System.out.println("ID: " + game8.getId());
        game8.setGameName("Crimson Desert");
        System.out.println("Game Name: " + game8.getGameName());
        game8.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game8.getPlatform());
        game8.setGenre("Action Adventure");
        System.out.println("Genre: " + game8.getGenre());
        game8.setReleaseDate("2026-03-19");
        System.out.println("Release Date: " + game8.getReleaseDate());
        game8.setDeveloper("Pearl Abyss");
        System.out.println("Developer: " + game8.getDeveloper());
        game8.setPublisher("Pearl Abyss");
        System.out.println("Publisher: " + game8.getPublisher());
        game8.setRating("Mature 17+");
        System.out.println("Rating: " + game8.getRating());
        System.out.println();

        GameInfo game9 = new GameInfo();
        game9.setId(9);
        System.out.println("ID: " + game9.getId());
        game9.setGameName("Nioh 3");
        System.out.println("Game Name: " + game9.getGameName());
        game9.setPlatform("PC, PS5");
        System.out.println("Platform: " + game9.getPlatform());
        game9.setGenre("Action RPG");
        System.out.println("Genre: " + game9.getGenre());
        game9.setReleaseDate("2026-02-06");
        System.out.println("Release Date: " + game9.getReleaseDate());
        game9.setDeveloper("Team Ninja");
        System.out.println("Developer: " + game9.getDeveloper());
        game9.setPublisher("Koei Tecmo");
        System.out.println("Publisher: " + game9.getPublisher());
        game9.setRating("Mature 17+");
        System.out.println("Rating: " + game9.getRating());
        System.out.println();

        GameInfo game10 = new GameInfo();
        game10.setId(10);
        System.out.println("ID: " + game10.getId());
        game10.setGameName("Subnautica 2");
        System.out.println("Game Name: " + game10.getGameName());
        game10.setPlatform("PC, PS5");
        System.out.println("Platform: " + game10.getPlatform());
        game10.setGenre("Survival Adventure");
        System.out.println("Genre: " + game10.getGenre());
        game10.setReleaseDate("2026");
        System.out.println("Release Date: " + game10.getReleaseDate());
        game10.setDeveloper("Unknown Worlds");
        System.out.println("Developer: " + game10.getDeveloper());
        game10.setPublisher("Krafton");
        System.out.println("Publisher: " + game10.getPublisher());
        game10.setRating("Teen");
        System.out.println("Rating: " + game10.getRating());
        System.out.println();

        GameInfo game11 = new GameInfo();
        game11.setId(11);
        System.out.println("ID: " + game11.getId());
        game11.setGameName("Phantom Blade Zero");
        System.out.println("Game Name: " + game11.getGameName());
        game11.setPlatform("PC, PS5");
        System.out.println("Platform: " + game11.getPlatform());
        game11.setGenre("Action RPG");
        System.out.println("Genre: " + game11.getGenre());
        game11.setReleaseDate("2026-09-09");
        System.out.println("Release Date: " + game11.getReleaseDate());
        game11.setDeveloper("S-Game Studio");
        System.out.println("Developer: " + game11.getDeveloper());
        game11.setPublisher("Sony Interactive");
        System.out.println("Publisher: " + game11.getPublisher());
        game11.setRating("Mature 17+");
        System.out.println("Rating: " + game11.getRating());
        System.out.println();

        GameInfo game12 = new GameInfo();
        game12.setId(12);
        System.out.println("ID: " + game12.getId());
        game12.setGameName("Resident Evil Requiem");
        System.out.println("Game Name: " + game12.getGameName());
        game12.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game12.getPlatform());
        game12.setGenre("Survival Horror");
        System.out.println("Genre: " + game12.getGenre());
        game12.setReleaseDate("2026-02-27");
        System.out.println("Release Date: " + game12.getReleaseDate());
        game12.setDeveloper("Capcom");
        System.out.println("Developer: " + game12.getDeveloper());
        game12.setPublisher("Capcom");
        System.out.println("Publisher: " + game12.getPublisher());
        game12.setRating("Mature 17+");
        System.out.println("Rating: " + game12.getRating());
        System.out.println();

        GameInfo game13 = new GameInfo();
        game13.setId(13);
        System.out.println("ID: " + game13.getId());
        game13.setGameName("Gears of War: E-Day");
        System.out.println("Game Name: " + game13.getGameName());
        game13.setPlatform("PC, Xbox Series X");
        System.out.println("Platform: " + game13.getPlatform());
        game13.setGenre("Third Person Shooter");
        System.out.println("Genre: " + game13.getGenre());
        game13.setReleaseDate("2026");
        System.out.println("Release Date: " + game13.getReleaseDate());
        game13.setDeveloper("The Coalition");
        System.out.println("Developer: " + game13.getDeveloper());
        game13.setPublisher("Xbox Game Studios");
        System.out.println("Publisher: " + game13.getPublisher());
        game13.setRating("Mature 17+");
        System.out.println("Rating: " + game13.getRating());
        System.out.println();

        GameInfo game14 = new GameInfo();
        game14.setId(14);
        System.out.println("ID: " + game14.getId());
        game14.setGameName("Judas");
        System.out.println("Game Name: " + game14.getGameName());
        game14.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game14.getPlatform());
        game14.setGenre("Immersive Sim");
        System.out.println("Genre: " + game14.getGenre());
        game14.setReleaseDate("2026");
        System.out.println("Release Date: " + game14.getReleaseDate());
        game14.setDeveloper("Ghost Story Games");
        System.out.println("Developer: " + game14.getDeveloper());
        game14.setPublisher("Ghost Story Games");
        System.out.println("Publisher: " + game14.getPublisher());
        game14.setRating("Mature 17+");
        System.out.println("Rating: " + game14.getRating());
        System.out.println();

        GameInfo game15 = new GameInfo();
        game15.setId(15);
        System.out.println("ID: " + game15.getId());
        game15.setGameName("Slay the Spire 2");
        System.out.println("Game Name: " + game15.getGameName());
        game15.setPlatform("PC");
        System.out.println("Platform: " + game15.getPlatform());
        game15.setGenre("Roguelike Deckbuilding");
        System.out.println("Genre: " + game15.getGenre());
        game15.setReleaseDate("2026-03");
        System.out.println("Release Date: " + game15.getReleaseDate());
        game15.setDeveloper("MegaCrit");
        System.out.println("Developer: " + game15.getDeveloper());
        game15.setPublisher("MegaCrit");
        System.out.println("Publisher: " + game15.getPublisher());
        game15.setRating("Everyone 10+");
        System.out.println("Rating: " + game15.getRating());
        System.out.println();

        GameInfo game16 = new GameInfo();
        game16.setId(16);
        System.out.println("ID: " + game16.getId());
        game16.setGameName("Lego Batman: Legacy");
        System.out.println("Game Name: " + game16.getGameName());
        game16.setPlatform("PC, PS5, Xbox, Switch 2");
        System.out.println("Platform: " + game16.getPlatform());
        game16.setGenre("Action Adventure");
        System.out.println("Genre: " + game16.getGenre());
        game16.setReleaseDate("2026-05-29");
        System.out.println("Release Date: " + game16.getReleaseDate());
        game16.setDeveloper("TT Games");
        System.out.println("Developer: " + game16.getDeveloper());
        game16.setPublisher("Warner Bros Games");
        System.out.println("Publisher: " + game16.getPublisher());
        game16.setRating("Everyone 10+");
        System.out.println("Rating: " + game16.getRating());
        System.out.println();

        GameInfo game17 = new GameInfo();
        game17.setId(17);
        System.out.println("ID: " + game17.getId());
        game17.setGameName("007 First Light");
        System.out.println("Game Name: " + game17.getGameName());
        game17.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game17.getPlatform());
        game17.setGenre("Action Stealth");
        System.out.println("Genre: " + game17.getGenre());
        game17.setReleaseDate("2026-05-27");
        System.out.println("Release Date: " + game17.getReleaseDate());
        game17.setDeveloper("IO Interactive");
        System.out.println("Developer: " + game17.getDeveloper());
        game17.setPublisher("IO Interactive");
        System.out.println("Publisher: " + game17.getPublisher());
        game17.setRating("Teen");
        System.out.println("Rating: " + game17.getRating());
        System.out.println();
		
		GameInfo game18 = new GameInfo();
        game18.setId(18);
        System.out.println("ID: " + game18.getId());
        game18.setGameName("Code Vein 2");
        System.out.println("Game Name: " + game18.getGameName());
        game18.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game18.getPlatform());
        game18.setGenre("Action RPG Soulslike");
        System.out.println("Genre: " + game18.getGenre());
        game18.setReleaseDate("2026-01-30");
        System.out.println("Release Date: " + game18.getReleaseDate());
        game18.setDeveloper("Shift Up");
        System.out.println("Developer: " + game18.getDeveloper());
        game18.setPublisher("Bandai Namco");
        System.out.println("Publisher: " + game18.getPublisher());
        game18.setRating("Mature 17+");
        System.out.println("Rating: " + game18.getRating());
        System.out.println();

        GameInfo game19 = new GameInfo();
        game19.setId(19);
        System.out.println("ID: " + game19.getId());
        game19.setGameName("Pragmata");
        System.out.println("Game Name: " + game19.getGameName());
        game19.setPlatform("PC, PS5, Xbox Series X, Switch 2");
        System.out.println("Platform: " + game19.getPlatform());
        game19.setGenre("Sci-Fi Action Adventure");
        System.out.println("Genre: " + game19.getGenre());
        game19.setReleaseDate("2026-04-17");
        System.out.println("Release Date: " + game19.getReleaseDate());
        game19.setDeveloper("Capcom");
        System.out.println("Developer: " + game19.getDeveloper());
        game19.setPublisher("Capcom");
        System.out.println("Publisher: " + game19.getPublisher());
        game19.setRating("Teen");
        System.out.println("Rating: " + game19.getRating());
        System.out.println();

        GameInfo game20 = new GameInfo();
        game20.setId(20);
        System.out.println("ID: " + game20.getId());
        game20.setGameName("High on Life 2");
        System.out.println("Game Name: " + game20.getGameName());
        game20.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game20.getPlatform());
        game20.setGenre("FPS Comedy Adventure");
        System.out.println("Genre: " + game20.getGenre());
        game20.setReleaseDate("2026-02-13");
        System.out.println("Release Date: " + game20.getReleaseDate());
        game20.setDeveloper("Squanch Games");
        System.out.println("Developer: " + game20.getDeveloper());
        game20.setPublisher("Squanch Games");
        System.out.println("Publisher: " + game20.getPublisher());
        game20.setRating("Mature 17+");
        System.out.println("Rating: " + game20.getRating());
        System.out.println();

        GameInfo game21 = new GameInfo();
        game21.setId(21);
        System.out.println("ID: " + game21.getId());
        game21.setGameName("Saros");
        System.out.println("Game Name: " + game21.getGameName());
        game21.setPlatform("PS5");
        System.out.println("Platform: " + game21.getPlatform());
        game21.setGenre("Rogue-lite Action");
        System.out.println("Genre: " + game21.getGenre());
        game21.setReleaseDate("2026-04-30");
        System.out.println("Release Date: " + game21.getReleaseDate());
        game21.setDeveloper("Housemarque");
        System.out.println("Developer: " + game21.getDeveloper());
        game21.setPublisher("Sony Interactive");
        System.out.println("Publisher: " + game21.getPublisher());
        game21.setRating("Everyone 10+");
        System.out.println("Rating: " + game21.getRating());
        System.out.println();

        GameInfo game22 = new GameInfo();
        game22.setId(22);
        System.out.println("ID: " + game22.getId());
        game22.setGameName("Reanimal");
        System.out.println("Game Name: " + game22.getGameName());
        game22.setPlatform("PC, PS5, Xbox Series X, Switch 2");
        System.out.println("Platform: " + game22.getPlatform());
        game22.setGenre("Survival Horror");
        System.out.println("Genre: " + game22.getGenre());
        game22.setReleaseDate("2026-02-13");
        System.out.println("Release Date: " + game22.getReleaseDate());
        game22.setDeveloper("Hollow Earth");
        System.out.println("Developer: " + game22.getDeveloper());
        game22.setPublisher("Hollow Earth");
        System.out.println("Publisher: " + game22.getPublisher());
        game22.setRating("Mature 17+");
        System.out.println("Rating: " + game22.getRating());
        System.out.println();

        GameInfo game23 = new GameInfo();
        game23.setId(23);
        System.out.println("ID: " + game23.getId());
        game23.setGameName("Pathologic 3");
        System.out.println("Game Name: " + game23.getGameName());
        game23.setPlatform("PC");
        System.out.println("Platform: " + game23.getPlatform());
        game23.setGenre("Survival Horror RPG");
        System.out.println("Genre: " + game23.getGenre());
        game23.setReleaseDate("2026-01-09");
        System.out.println("Release Date: " + game23.getReleaseDate());
        game23.setDeveloper("Ice-Pick Lodge");
        System.out.println("Developer: " + game23.getDeveloper());
        game23.setPublisher("Ice-Pick Lodge");
        System.out.println("Publisher: " + game23.getPublisher());
        game23.setRating("Mature 17+");
        System.out.println("Rating: " + game23.getRating());
        System.out.println();

        GameInfo game24 = new GameInfo();
        game24.setId(24);
        System.out.println("ID: " + game24.getId());
        game24.setGameName("Fatal Frame II Remake");
        System.out.println("Game Name: " + game24.getGameName());
        game24.setPlatform("PC, PS5, Xbox Series X, Switch 2");
        System.out.println("Platform: " + game24.getPlatform());
        game24.setGenre("Survival Horror");
        System.out.println("Genre: " + game24.getGenre());
        game24.setReleaseDate("2026-03-12");
        System.out.println("Release Date: " + game24.getReleaseDate());
        game24.setDeveloper("Koei Tecmo");
        System.out.println("Developer: " + game24.getDeveloper());
        game24.setPublisher("Koei Tecmo");
        System.out.println("Publisher: " + game24.getPublisher());
        game24.setRating("Mature 17+");
        System.out.println("Rating: " + game24.getRating());
        System.out.println();

        GameInfo game25 = new GameInfo();
        game25.setId(25);
        System.out.println("ID: " + game25.getId());
        game25.setGameName("Diablo IV: Lord of Hatred");
        System.out.println("Game Name: " + game25.getGameName());
        game25.setPlatform("PC, PS5, PS4, Xbox Series X, Xbox One");
        System.out.println("Platform: " + game25.getPlatform());
        game25.setGenre("Action RPG");
        System.out.println("Genre: " + game25.getGenre());
        game25.setReleaseDate("2026-04-28");
        System.out.println("Release Date: " + game25.getReleaseDate());
        game25.setDeveloper("Blizzard Entertainment");
        System.out.println("Developer: " + game25.getDeveloper());
        game25.setPublisher("Blizzard Entertainment");
        System.out.println("Publisher: " + game25.getPublisher());
        game25.setRating("Mature 17+");
        System.out.println("Rating: " + game25.getRating());
        System.out.println();

        GameInfo game26 = new GameInfo();
        game26.setId(26);
        System.out.println("ID: " + game26.getId());
        game26.setGameName("Monster Hunter Stories 3");
        System.out.println("Game Name: " + game26.getGameName());
        game26.setPlatform("PS5, Xbox Series X, Switch 2, PC");
        System.out.println("Platform: " + game26.getPlatform());
        game26.setGenre("Action RPG");
        System.out.println("Genre: " + game26.getGenre());
        game26.setReleaseDate("2026-03-13");
        System.out.println("Release Date: " + game26.getReleaseDate());
        game26.setDeveloper("Capcom");
        System.out.println("Developer: " + game26.getDeveloper());
        game26.setPublisher("Capcom");
        System.out.println("Publisher: " + game26.getPublisher());
        game26.setRating("Teen");
        System.out.println("Rating: " + game26.getRating());
        System.out.println();

        GameInfo game27 = new GameInfo();
        game27.setId(27);
        System.out.println("ID: " + game27.getId());
        game27.setGameName("MARVEL 1943: Rise of Hydra");
        System.out.println("Game Name: " + game27.getGameName());
        game27.setPlatform("PC, Xbox Series X, PS5");
        System.out.println("Platform: " + game27.getPlatform());
        game27.setGenre("Action Adventure");
        System.out.println("Genre: " + game27.getGenre());
        game27.setReleaseDate("2026-TBC");
        System.out.println("Release Date: " + game27.getReleaseDate());
        game27.setDeveloper("Skydance Interactive");
        System.out.println("Developer: " + game27.getDeveloper());
        game27.setPublisher("Skydance Interactive");
        System.out.println("Publisher: " + game27.getPublisher());
        game27.setRating("Teen");
        System.out.println("Rating: " + game27.getRating());
        System.out.println();

        GameInfo game28 = new GameInfo();
        game28.setId(28);
        System.out.println("ID: " + game28.getId());
        game28.setGameName("Mortal Shell 2");
        System.out.println("Game Name: " + game28.getGameName());
        game28.setPlatform("PC, PS5, Xbox Series X");
        System.out.println("Platform: " + game28.getPlatform());
        game28.setGenre("Soulslike Action RPG");
        System.out.println("Genre: " + game28.getGenre());
        game28.setReleaseDate("2026-TBC");
        System.out.println("Release Date: " + game28.getReleaseDate());
        game28.setDeveloper("Cold Symmetry");
        System.out.println("Developer: " + game28.getDeveloper());
        game28.setPublisher("Playstack");
        System.out.println("Publisher: " + game28.getPublisher());
        game28.setRating("Mature 17+");
        System.out.println("Rating: " + game28.getRating());
        System.out.println();

        GameInfo game29 = new GameInfo();
        game29.setId(29);
        System.out.println("ID: " + game29.getId());
        game29.setGameName("Prince of Persia Sands of Time Remake");
        System.out.println("Game Name: " + game29.getGameName());
        game29.setPlatform("PC, PS5, Xbox Series X, PS4, Xbox One, Switch");
        System.out.println("Platform: " + game29.getPlatform());
        game29.setGenre("Action Adventure Platformer");
        System.out.println("Genre: " + game29.getGenre());
        game29.setReleaseDate("2026-01");
        System.out.println("Release Date: " + game29.getReleaseDate());
        game29.setDeveloper("Ubisoft");
        System.out.println("Developer: " + game29.getDeveloper());
        game29.setPublisher("Ubisoft");
        System.out.println("Publisher: " + game29.getPublisher());
        game29.setRating("Teen");
        System.out.println("Rating: " + game29.getRating());
        System.out.println();
    }
}