class GpsDetailsExecutor {

    public static void main(String[] gps) {
	
        GpsDetails gps1 = new GpsDetails();
        gps1.setGpsId(1);
        System.out.println("GPS ID: " + gps1.getGpsId());
        gps1.setDeviceId("DEV001");
        System.out.println("Device ID: " + gps1.getDeviceId());
        gps1.setLatitude(12.9716);
        System.out.println("Latitude: " + gps1.getLatitude());
        gps1.setLongitude(77.5946);
        System.out.println("Longitude: " + gps1.getLongitude());
        gps1.setSpeedKmh(45.5);
        System.out.println("Speed: " + gps1.getSpeedKmh() + " km/h");
        gps1.setTimestamp("2026-03-31 23:10:15");
        System.out.println("Timestamp: " + gps1.getTimestamp());
        gps1.setLocationStatus("Active");
        System.out.println("Status: " + gps1.getLocationStatus());
        System.out.println();

        GpsDetails gps2 = new GpsDetails();
        gps2.setGpsId(2);
        System.out.println("GPS ID: " + gps2.getGpsId());
        gps2.setDeviceId("DEV002");
        System.out.println("Device ID: " + gps2.getDeviceId());
        gps2.setLatitude(12.9352);
        System.out.println("Latitude: " + gps2.getLatitude());
        gps2.setLongitude(77.6245);
        System.out.println("Longitude: " + gps2.getLongitude());
        gps2.setSpeedKmh(28.3);
        System.out.println("Speed: " + gps2.getSpeedKmh() + " km/h");
        gps2.setTimestamp("2026-03-31 23:12:30");
        System.out.println("Timestamp: " + gps2.getTimestamp());
        gps2.setLocationStatus("Active");
        System.out.println("Status: " + gps2.getLocationStatus());
        System.out.println();

        GpsDetails gps3 = new GpsDetails();
        gps3.setGpsId(3);
        System.out.println("GPS ID: " + gps3.getGpsId());
        gps3.setDeviceId("DEV003");
        System.out.println("Device ID: " + gps3.getDeviceId());
        gps3.setLatitude(13.0827);
        System.out.println("Latitude: " + gps3.getLatitude());
        gps3.setLongitude(77.6069);
        System.out.println("Longitude: " + gps3.getLongitude());
        gps3.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps3.getSpeedKmh() + " km/h");
        gps3.setTimestamp("2026-03-31 23:15:45");
        System.out.println("Timestamp: " + gps3.getTimestamp());
        gps3.setLocationStatus("Parked");
        System.out.println("Status: " + gps3.getLocationStatus());
        System.out.println();

        GpsDetails gps4 = new GpsDetails();
        gps4.setGpsId(4);
        System.out.println("GPS ID: " + gps4.getGpsId());
        gps4.setDeviceId("DEV004");
        System.out.println("Device ID: " + gps4.getDeviceId());
        gps4.setLatitude(12.9249);
        System.out.println("Latitude: " + gps4.getLatitude());
        gps4.setLongitude(77.5377);
        System.out.println("Longitude: " + gps4.getLongitude());
        gps4.setSpeedKmh(62.8);
        System.out.println("Speed: " + gps4.getSpeedKmh() + " km/h");
        gps4.setTimestamp("2026-03-31 23:18:22");
        System.out.println("Timestamp: " + gps4.getTimestamp());
        gps4.setLocationStatus("Active");
        System.out.println("Status: " + gps4.getLocationStatus());
        System.out.println();

        GpsDetails gps5 = new GpsDetails();
        gps5.setGpsId(5);
        System.out.println("GPS ID: " + gps5.getGpsId());
        gps5.setDeviceId("DEV005");
        System.out.println("Device ID: " + gps5.getDeviceId());
        gps5.setLatitude(13.0278);
        System.out.println("Latitude: " + gps5.getLatitude());
        gps5.setLongitude(77.5667);
        System.out.println("Longitude: " + gps5.getLongitude());
        gps5.setSpeedKmh(35.2);
        System.out.println("Speed: " + gps5.getSpeedKmh() + " km/h");
        gps5.setTimestamp("2026-03-31 23:20:10");
        System.out.println("Timestamp: " + gps5.getTimestamp());
        gps5.setLocationStatus("Active");
        System.out.println("Status: " + gps5.getLocationStatus());
        System.out.println();
		
		GpsDetails gps6 = new GpsDetails();
        gps6.setGpsId(6);
        System.out.println("GPS ID: " + gps6.getGpsId());
        gps6.setDeviceId("DEV006");
        System.out.println("Device ID: " + gps6.getDeviceId());
        gps6.setLatitude(12.9279);
        System.out.println("Latitude: " + gps6.getLatitude());
        gps6.setLongitude(77.6284);
        System.out.println("Longitude: " + gps6.getLongitude());
        gps6.setSpeedKmh(52.1);
        System.out.println("Speed: " + gps6.getSpeedKmh() + " km/h");
        gps6.setTimestamp("2026-03-31 23:22:35");
        System.out.println("Timestamp: " + gps6.getTimestamp());
        gps6.setLocationStatus("Active");
        System.out.println("Status: " + gps6.getLocationStatus());
        System.out.println();

        GpsDetails gps7 = new GpsDetails();
        gps7.setGpsId(7);
        System.out.println("GPS ID: " + gps7.getGpsId());
        gps7.setDeviceId("DEV007");
        System.out.println("Device ID: " + gps7.getDeviceId());
        gps7.setLatitude(13.0413);
        System.out.println("Latitude: " + gps7.getLatitude());
        gps7.setLongitude(77.5854);
        System.out.println("Longitude: " + gps7.getLongitude());
        gps7.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps7.getSpeedKmh() + " km/h");
        gps7.setTimestamp("2026-03-31 23:25:12");
        System.out.println("Timestamp: " + gps7.getTimestamp());
        gps7.setLocationStatus("Parked");
        System.out.println("Status: " + gps7.getLocationStatus());
        System.out.println();

        GpsDetails gps8 = new GpsDetails();
        gps8.setGpsId(8);
        System.out.println("GPS ID: " + gps8.getGpsId());
        gps8.setDeviceId("DEV008");
        System.out.println("Device ID: " + gps8.getDeviceId());
        gps8.setLatitude(12.9346);
        System.out.println("Latitude: " + gps8.getLatitude());
        gps8.setLongitude(77.6043);
        System.out.println("Longitude: " + gps8.getLongitude());
        gps8.setSpeedKmh(38.7);
        System.out.println("Speed: " + gps8.getSpeedKmh() + " km/h");
        gps8.setTimestamp("2026-03-31 23:27:48");
        System.out.println("Timestamp: " + gps8.getTimestamp());
        gps8.setLocationStatus("Active");
        System.out.println("Status: " + gps8.getLocationStatus());
        System.out.println();

        GpsDetails gps9 = new GpsDetails();
        gps9.setGpsId(9);
        System.out.println("GPS ID: " + gps9.getGpsId());
        gps9.setDeviceId("DEV009");
        System.out.println("Device ID: " + gps9.getDeviceId());
        gps9.setLatitude(12.9638);
        System.out.println("Latitude: " + gps9.getLatitude());
        gps9.setLongitude(77.6410);
        System.out.println("Longitude: " + gps9.getLongitude());
        gps9.setSpeedKmh(65.2);
        System.out.println("Speed: " + gps9.getSpeedKmh() + " km/h");
        gps9.setTimestamp("2026-03-31 23:30:05");
        System.out.println("Timestamp: " + gps9.getTimestamp());
        gps9.setLocationStatus("Highway");
        System.out.println("Status: " + gps9.getLocationStatus());
        System.out.println();

        GpsDetails gps10 = new GpsDetails();
        gps10.setGpsId(10);
        System.out.println("GPS ID: " + gps10.getGpsId());
        gps10.setDeviceId("DEV010");
        System.out.println("Device ID: " + gps10.getDeviceId());
        gps10.setLatitude(13.0005);
        System.out.println("Latitude: " + gps10.getLatitude());
        gps10.setLongitude(77.5502);
        System.out.println("Longitude: " + gps10.getLongitude());
        gps10.setSpeedKmh(12.4);
        System.out.println("Speed: " + gps10.getSpeedKmh() + " km/h");
        gps10.setTimestamp("2026-03-31 23:32:19");
        System.out.println("Timestamp: " + gps10.getTimestamp());
        gps10.setLocationStatus("Traffic");
        System.out.println("Status: " + gps10.getLocationStatus());
        System.out.println();

        GpsDetails gps11 = new GpsDetails();
        gps11.setGpsId(11);
        System.out.println("GPS ID: " + gps11.getGpsId());
        gps11.setDeviceId("DEV011");
        System.out.println("Device ID: " + gps11.getDeviceId());
        gps11.setLatitude(12.9104);
        System.out.println("Latitude: " + gps11.getLatitude());
        gps11.setLongitude(77.5789);
        System.out.println("Longitude: " + gps11.getLongitude());
        gps11.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps11.getSpeedKmh() + " km/h");
        gps11.setTimestamp("2026-03-31 23:35:33");
        System.out.println("Timestamp: " + gps11.getTimestamp());
        gps11.setLocationStatus("Parked");
        System.out.println("Status: " + gps11.getLocationStatus());
        System.out.println();

        GpsDetails gps12 = new GpsDetails();
        gps12.setGpsId(12);
        System.out.println("GPS ID: " + gps12.getGpsId());
        gps12.setDeviceId("DEV012");
        System.out.println("Device ID: " + gps12.getDeviceId());
        gps12.setLatitude(13.0674);
        System.out.println("Latitude: " + gps12.getLatitude());
        gps12.setLongitude(77.5961);
        System.out.println("Longitude: " + gps12.getLongitude());
        gps12.setSpeedKmh(47.8);
        System.out.println("Speed: " + gps12.getSpeedKmh() + " km/h");
        gps12.setTimestamp("2026-03-31 23:38:07");
        System.out.println("Timestamp: " + gps12.getTimestamp());
        gps12.setLocationStatus("Active");
        System.out.println("Status: " + gps12.getLocationStatus());
        System.out.println();

        GpsDetails gps13 = new GpsDetails();
        gps13.setGpsId(13);
        System.out.println("GPS ID: " + gps13.getGpsId());
        gps13.setDeviceId("DEV013");
        System.out.println("Device ID: " + gps13.getDeviceId());
        gps13.setLatitude(12.9523);
        System.out.println("Latitude: " + gps13.getLatitude());
        gps13.setLongitude(77.6127);
        System.out.println("Longitude: " + gps13.getLongitude());
        gps13.setSpeedKmh(29.6);
        System.out.println("Speed: " + gps13.getSpeedKmh() + " km/h");
        gps13.setTimestamp("2026-03-31 23:40:42");
        System.out.println("Timestamp: " + gps13.getTimestamp());
        gps13.setLocationStatus("Active");
        System.out.println("Status: " + gps13.getLocationStatus());
        System.out.println();

        GpsDetails gps14 = new GpsDetails();
        gps14.setGpsId(14);
        System.out.println("GPS ID: " + gps14.getGpsId());
        gps14.setDeviceId("DEV014");
        System.out.println("Device ID: " + gps14.getDeviceId());
        gps14.setLatitude(12.9887);
        System.out.println("Latitude: " + gps14.getLatitude());
        gps14.setLongitude(77.5345);
        System.out.println("Longitude: " + gps14.getLongitude());
        gps14.setSpeedKmh(58.3);
        System.out.println("Speed: " + gps14.getSpeedKmh() + " km/h");
        gps14.setTimestamp("2026-03-31 23:43:16");
        System.out.println("Timestamp: " + gps14.getTimestamp());
        gps14.setLocationStatus("Active");
        System.out.println("Status: " + gps14.getLocationStatus());
        System.out.println();

        GpsDetails gps15 = new GpsDetails();
        gps15.setGpsId(15);
        System.out.println("GPS ID: " + gps15.getGpsId());
        gps15.setDeviceId("DEV015");
        System.out.println("Device ID: " + gps15.getDeviceId());
        gps15.setLatitude(13.0532);
        System.out.println("Latitude: " + gps15.getLatitude());
        gps15.setLongitude(77.6208);
        System.out.println("Longitude: " + gps15.getLongitude());
        gps15.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps15.getSpeedKmh() + " km/h");
        gps15.setTimestamp("2026-03-31 23:45:59");
        System.out.println("Timestamp: " + gps15.getTimestamp());
        gps15.setLocationStatus("Parked");
        System.out.println("Status: " + gps15.getLocationStatus());
        System.out.println();


        GpsDetails gps16 = new GpsDetails();
        gps16.setGpsId(16);
        System.out.println("GPS ID: " + gps16.getGpsId());
        gps16.setDeviceId("DEV016");
        System.out.println("Device ID: " + gps16.getDeviceId());
        gps16.setLatitude(12.9198);
        System.out.println("Latitude: " + gps16.getLatitude());
        gps16.setLongitude(77.5901);
        System.out.println("Longitude: " + gps16.getLongitude());
        gps16.setSpeedKmh(41.9);
        System.out.println("Speed: " + gps16.getSpeedKmh() + " km/h");
        gps16.setTimestamp("2026-03-31 23:48:24");
        System.out.println("Timestamp: " + gps16.getTimestamp());
        gps16.setLocationStatus("Active");
        System.out.println("Status: " + gps16.getLocationStatus());
        System.out.println();

        GpsDetails gps17 = new GpsDetails();
        gps17.setGpsId(17);
        System.out.println("GPS ID: " + gps17.getGpsId());
        gps17.setDeviceId("DEV017");
        System.out.println("Device ID: " + gps17.getDeviceId());
        gps17.setLatitude(13.0789);
        System.out.println("Latitude: " + gps17.getLatitude());
        gps17.setLongitude(77.5673);
        System.out.println("Longitude: " + gps17.getLongitude());
        gps17.setSpeedKmh(33.7);
        System.out.println("Speed: " + gps17.getSpeedKmh() + " km/h");
        gps17.setTimestamp("2026-03-31 23:50:51");
        System.out.println("Timestamp: " + gps17.getTimestamp());
        gps17.setLocationStatus("Active");
        System.out.println("Status: " + gps17.getLocationStatus());
        System.out.println();
		
		GpsDetails gps18 = new GpsDetails();
        gps18.setGpsId(18);
        System.out.println("GPS ID: " + gps18.getGpsId());
        gps18.setDeviceId("DEV018");
        System.out.println("Device ID: " + gps18.getDeviceId());
        gps18.setLatitude(12.9733);
        System.out.println("Latitude: " + gps18.getLatitude());
        gps18.setLongitude(77.6405);
        System.out.println("Longitude: " + gps18.getLongitude());
        gps18.setSpeedKmh(25.6);
        System.out.println("Speed: " + gps18.getSpeedKmh() + " km/h");
        gps18.setTimestamp("2026-03-31 23:53:27");
        System.out.println("Timestamp: " + gps18.getTimestamp());
        gps18.setLocationStatus("Active");
        System.out.println("Status: " + gps18.getLocationStatus());
        System.out.println();

        GpsDetails gps19 = new GpsDetails();
        gps19.setGpsId(19);
        System.out.println("GPS ID: " + gps19.getGpsId());
        gps19.setDeviceId("DEV019");
        System.out.println("Device ID: " + gps19.getDeviceId());
        gps19.setLatitude(13.0945);
        System.out.println("Latitude: " + gps19.getLatitude());
        gps19.setLongitude(77.5860);
        System.out.println("Longitude: " + gps19.getLongitude());
        gps19.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps19.getSpeedKmh() + " km/h");
        gps19.setTimestamp("2026-03-31 23:55:44");
        System.out.println("Timestamp: " + gps19.getTimestamp());
        gps19.setLocationStatus("Parked");
        System.out.println("Status: " + gps19.getLocationStatus());
        System.out.println();

        GpsDetails gps20 = new GpsDetails();
        gps20.setGpsId(20);
        System.out.println("GPS ID: " + gps20.getGpsId());
        gps20.setDeviceId("DEV020");
        System.out.println("Device ID: " + gps20.getDeviceId());
        gps20.setLatitude(12.9512);
        System.out.println("Latitude: " + gps20.getLatitude());
        gps20.setLongitude(77.6998);
        System.out.println("Longitude: " + gps20.getLongitude());
        gps20.setSpeedKmh(54.3);
        System.out.println("Speed: " + gps20.getSpeedKmh() + " km/h");
        gps20.setTimestamp("2026-03-31 23:58:09");
        System.out.println("Timestamp: " + gps20.getTimestamp());
        gps20.setLocationStatus("Highway");
        System.out.println("Status: " + gps20.getLocationStatus());
        System.out.println();

        GpsDetails gps21 = new GpsDetails();
        gps21.setGpsId(21);
        System.out.println("GPS ID: " + gps21.getGpsId());
        gps21.setDeviceId("DEV021");
        System.out.println("Device ID: " + gps21.getDeviceId());
        gps21.setLatitude(12.9719);
        System.out.println("Latitude: " + gps21.getLatitude());
        gps21.setLongitude(77.6412);
        System.out.println("Longitude: " + gps21.getLongitude());
        gps21.setSpeedKmh(18.9);
        System.out.println("Speed: " + gps21.getSpeedKmh() + " km/h");
        gps21.setTimestamp("2026-04-01 00:00:32");
        System.out.println("Timestamp: " + gps21.getTimestamp());
        gps21.setLocationStatus("Traffic");
        System.out.println("Status: " + gps21.getLocationStatus());
        System.out.println();

        GpsDetails gps22 = new GpsDetails();
        gps22.setGpsId(22);
        System.out.println("GPS ID: " + gps22.getGpsId());
        gps22.setDeviceId("DEV022");
        System.out.println("Device ID: " + gps22.getDeviceId());
        gps22.setLatitude(13.1075);
        System.out.println("Latitude: " + gps22.getLatitude());
        gps22.setLongitude(77.6003);
        System.out.println("Longitude: " + gps22.getLongitude());
        gps22.setSpeedKmh(42.7);
        System.out.println("Speed: " + gps22.getSpeedKmh() + " km/h");
        gps22.setTimestamp("2026-04-01 00:02:18");
        System.out.println("Timestamp: " + gps22.getTimestamp());
        gps22.setLocationStatus("Active");
        System.out.println("Status: " + gps22.getLocationStatus());
        System.out.println();

        GpsDetails gps23 = new GpsDetails();
        gps23.setGpsId(23);
        System.out.println("GPS ID: " + gps23.getGpsId());
        gps23.setDeviceId("DEV023");
        System.out.println("Device ID: " + gps23.getDeviceId());
        gps23.setLatitude(12.9297);
        System.out.println("Latitude: " + gps23.getLatitude());
        gps23.setLongitude(77.6861);
        System.out.println("Longitude: " + gps23.getLongitude());
        gps23.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps23.getSpeedKmh() + " km/h");
        gps23.setTimestamp("2026-04-01 00:04:55");
        System.out.println("Timestamp: " + gps23.getTimestamp());
        gps23.setLocationStatus("Parked");
        System.out.println("Status: " + gps23.getLocationStatus());
        System.out.println();

        GpsDetails gps24 = new GpsDetails();
        gps24.setGpsId(24);
        System.out.println("GPS ID: " + gps24.getGpsId());
        gps24.setDeviceId("DEV024");
        System.out.println("Device ID: " + gps24.getDeviceId());
        gps24.setLatitude(12.9808);
        System.out.println("Latitude: " + gps24.getLatitude());
        gps24.setLongitude(77.6398);
        System.out.println("Longitude: " + gps24.getLongitude());
        gps24.setSpeedKmh(31.4);
        System.out.println("Speed: " + gps24.getSpeedKmh() + " km/h");
        gps24.setTimestamp("2026-04-01 00:07:13");
        System.out.println("Timestamp: " + gps24.getTimestamp());
        gps24.setLocationStatus("Active");
        System.out.println("Status: " + gps24.getLocationStatus());
        System.out.println();

        GpsDetails gps25 = new GpsDetails();
        gps25.setGpsId(25);
        System.out.println("GPS ID: " + gps25.getGpsId());
        gps25.setDeviceId("DEV025");
        System.out.println("Device ID: " + gps25.getDeviceId());
        gps25.setLatitude(13.0578);
        System.out.println("Latitude: " + gps25.getLatitude());
        gps25.setLongitude(77.5912);
        System.out.println("Longitude: " + gps25.getLongitude());
        gps25.setSpeedKmh(59.8);
        System.out.println("Speed: " + gps25.getSpeedKmh() + " km/h");
        gps25.setTimestamp("2026-04-01 00:09:47");
        System.out.println("Timestamp: " + gps25.getTimestamp());
        gps25.setLocationStatus("Highway");
        System.out.println("Status: " + gps25.getLocationStatus());
        System.out.println();

        GpsDetails gps26 = new GpsDetails();
        gps26.setGpsId(26);
        System.out.println("GPS ID: " + gps26.getGpsId());
        gps26.setDeviceId("DEV026");
        System.out.println("Device ID: " + gps26.getDeviceId());
        gps26.setLatitude(12.9456);
        System.out.println("Latitude: " + gps26.getLatitude());
        gps26.setLongitude(77.5054);
        System.out.println("Longitude: " + gps26.getLongitude());
        gps26.setSpeedKmh(15.2);
        System.out.println("Speed: " + gps26.getSpeedKmh() + " km/h");
        gps26.setTimestamp("2026-04-01 00:12:21");
        System.out.println("Timestamp: " + gps26.getTimestamp());
        gps26.setLocationStatus("Traffic");
        System.out.println("Status: " + gps26.getLocationStatus());
        System.out.println();

        GpsDetails gps27 = new GpsDetails();
        gps27.setGpsId(27);
        System.out.println("GPS ID: " + gps27.getGpsId());
        gps27.setDeviceId("DEV027");
        System.out.println("Device ID: " + gps27.getDeviceId());
        gps27.setLatitude(13.0289);
        System.out.println("Latitude: " + gps27.getLatitude());
        gps27.setLongitude(77.6078);
        System.out.println("Longitude: " + gps27.getLongitude());
        gps27.setSpeedKmh(48.6);
        System.out.println("Speed: " + gps27.getSpeedKmh() + " km/h");
        gps27.setTimestamp("2026-04-01 00:14:38");
        System.out.println("Timestamp: " + gps27.getTimestamp());
        gps27.setLocationStatus("Active");
        System.out.println("Status: " + gps27.getLocationStatus());
        System.out.println();

        GpsDetails gps28 = new GpsDetails();
        gps28.setGpsId(28);
        System.out.println("GPS ID: " + gps28.getGpsId());
        gps28.setDeviceId("DEV028");
        System.out.println("Device ID: " + gps28.getDeviceId());
        gps28.setLatitude(12.9765);
        System.out.println("Latitude: " + gps28.getLatitude());
        gps28.setLongitude(77.5987);
        System.out.println("Longitude: " + gps28.getLongitude());
        gps28.setSpeedKmh(0.0);
        System.out.println("Speed: " + gps28.getSpeedKmh() + " km/h");
        gps28.setTimestamp("2026-04-01 00:17:02");
        System.out.println("Timestamp: " + gps28.getTimestamp());
        gps28.setLocationStatus("Parked");
        System.out.println("Status: " + gps28.getLocationStatus());
        System.out.println();

        GpsDetails gps29 = new GpsDetails();
        gps29.setGpsId(29);
        System.out.println("GPS ID: " + gps29.getGpsId());
        gps29.setDeviceId("DEV029");
        System.out.println("Device ID: " + gps29.getDeviceId());
        gps29.setLatitude(13.0456);
        System.out.println("Latitude: " + gps29.getLatitude());
        gps29.setLongitude(77.5793);
        System.out.println("Longitude: " + gps29.getLongitude());
        gps29.setSpeedKmh(36.1);
        System.out.println("Speed: " + gps29.getSpeedKmh() + " km/h");
        gps29.setTimestamp("2026-04-01 00:19:29");
        System.out.println("Timestamp: " + gps29.getTimestamp());
        gps29.setLocationStatus("Active");
        System.out.println("Status: " + gps29.getLocationStatus());
        System.out.println();
    }
}