public class GraveyardExecutor {

    public static void main(String[] yard) {
	
        Graveyard graveyard1 = new Graveyard();
        graveyard1.setGraveyardId(1);
        System.out.println("Graveyard ID: " + graveyard1.getGraveyardId());
        graveyard1.setGraveyardName("St. John's Church Cemetery");
        System.out.println("Name: " + graveyard1.getGraveyardName());
        graveyard1.setLocation("Kalpalli, Cleveland Town, Bengaluru");
        System.out.println("Location: " + graveyard1.getLocation());
        graveyard1.setEstablishedYear("1808");
        System.out.println("Established: " + graveyard1.getEstablishedYear());
        graveyard1.setTotalGraves(4500);
        System.out.println("Total Graves: " + graveyard1.getTotalGraves());
        graveyard1.setType("Christian");
        System.out.println("Type: " + graveyard1.getType());
        graveyard1.setCaretaker("St. Mark's Cathedral Trust");
        System.out.println("Caretaker: " + graveyard1.getCaretaker());
        System.out.println();

        Graveyard graveyard2 = new Graveyard();
        graveyard2.setGraveyardId(2);
        System.out.println("Graveyard ID: " + graveyard2.getGraveyardId());
        graveyard2.setGraveyardName("Hosur Road Protestant Cemetery");
        System.out.println("Name: " + graveyard2.getGraveyardName());
        graveyard2.setLocation("Electronic City Phase 1");
        System.out.println("Location: " + graveyard2.getLocation());
        graveyard2.setEstablishedYear("1850");
        System.out.println("Established: " + graveyard2.getEstablishedYear());
        graveyard2.setTotalGraves(3200);
        System.out.println("Total Graves: " + graveyard2.getTotalGraves());
        graveyard2.setType("Protestant");
        System.out.println("Type: " + graveyard2.getType());
        graveyard2.setCaretaker("Church Authorities");
        System.out.println("Caretaker: " + graveyard2.getCaretaker());
        System.out.println();

        Graveyard graveyard3 = new Graveyard();
        graveyard3.setGraveyardId(3);
        System.out.println("Graveyard ID: " + graveyard3.getGraveyardId());
        graveyard3.setGraveyardName("Wilson Garden Burial Ground");
        System.out.println("Name: " + graveyard3.getGraveyardName());
        graveyard3.setLocation("Wilson Garden, Bengaluru");
        System.out.println("Location: " + graveyard3.getLocation());
        graveyard3.setEstablishedYear("1925");
        System.out.println("Established: " + graveyard3.getEstablishedYear());
        graveyard3.setTotalGraves(2800);
        System.out.println("Total Graves: " + graveyard3.getTotalGraves());
        graveyard3.setType("Christian");
        System.out.println("Type: " + graveyard3.getType());
        graveyard3.setCaretaker("Local Church Committee");
        System.out.println("Caretaker: " + graveyard3.getCaretaker());
        System.out.println();

        Graveyard graveyard4 = new Graveyard();
        graveyard4.setGraveyardId(4);
        System.out.println("Graveyard ID: " + graveyard4.getGraveyardId());
        graveyard4.setGraveyardName("Shia Qabristan");
        System.out.println("Name: " + graveyard4.getGraveyardName());
        graveyard4.setLocation("Richmond Town, Bengaluru");
        System.out.println("Location: " + graveyard4.getLocation());
        graveyard4.setEstablishedYear("1930");
        System.out.println("Established: " + graveyard4.getEstablishedYear());
        graveyard4.setTotalGraves(1500);
        System.out.println("Total Graves: " + graveyard4.getTotalGraves());
        graveyard4.setType("Muslim Shia");
        System.out.println("Type: " + graveyard4.getType());
        graveyard4.setCaretaker("Shia Jamaat");
        System.out.println("Caretaker: " + graveyard4.getCaretaker());
        System.out.println();

        Graveyard graveyard5 = new Graveyard();
        graveyard5.setGraveyardId(5);
        System.out.println("Graveyard ID: " + graveyard5.getGraveyardId());
        graveyard5.setGraveyardName("Kallahalli Cemetery");
        System.out.println("Name: " + graveyard5.getGraveyardName());
        graveyard5.setLocation("Cox Town, Bengaluru");
        System.out.println("Location: " + graveyard5.getLocation());
        graveyard5.setEstablishedYear("1947");
        System.out.println("Established: " + graveyard5.getEstablishedYear());
        graveyard5.setTotalGraves(2200);
        System.out.println("Total Graves: " + graveyard5.getTotalGraves());
        graveyard5.setType("Christian");
        System.out.println("Type: " + graveyard5.getType());
        graveyard5.setCaretaker("Cox Town Church");
        System.out.println("Caretaker: " + graveyard5.getCaretaker());
        System.out.println();
		
	    Graveyard graveyard6 = new Graveyard();
        graveyard6.setGraveyardId(6);
        System.out.println("Graveyard ID: " + graveyard6.getGraveyardId());
        graveyard6.setGraveyardName("Lakshmipuram Graveyard");
        System.out.println("Name: " + graveyard6.getGraveyardName());
        graveyard6.setLocation("Indiranagar, Bengaluru");
        System.out.println("Location: " + graveyard6.getLocation());
        graveyard6.setEstablishedYear("1880");
        System.out.println("Established: " + graveyard6.getEstablishedYear());
        graveyard6.setTotalGraves(3800);
        System.out.println("Total Graves: " + graveyard6.getTotalGraves());
        graveyard6.setType("Christian");
        System.out.println("Type: " + graveyard6.getType());
        graveyard6.setCaretaker("Local Church Trust");
        System.out.println("Caretaker: " + graveyard6.getCaretaker());
        System.out.println();

        Graveyard graveyard7 = new Graveyard();
        graveyard7.setGraveyardId(7);
        System.out.println("Graveyard ID: " + graveyard7.getGraveyardId());
        graveyard7.setGraveyardName("Sacred Heart Cemetery");
        System.out.println("Name: " + graveyard7.getGraveyardName());
        graveyard7.setLocation("Victoria Layout, Bengaluru");
        System.out.println("Location: " + graveyard7.getLocation());
        graveyard7.setEstablishedYear("1952");
        System.out.println("Established: " + graveyard7.getEstablishedYear());
        graveyard7.setTotalGraves(1800);
        System.out.println("Total Graves: " + graveyard7.getTotalGraves());
        graveyard7.setType("Catholic");
        System.out.println("Type: " + graveyard7.getType());
        graveyard7.setCaretaker("Sacred Heart Church");
        System.out.println("Caretaker: " + graveyard7.getCaretaker());
        System.out.println();

        Graveyard graveyard8 = new Graveyard();
        graveyard8.setGraveyardId(8);
        System.out.println("Graveyard ID: " + graveyard8.getGraveyardId());
        graveyard8.setGraveyardName("Sunnat Qabristan");
        System.out.println("Name: " + graveyard8.setGraveyardName());
        graveyard8.setLocation("Shivajinagar, Bengaluru");
        System.out.println("Location: " + graveyard8.getLocation());
        graveyard8.setEstablishedYear("1910");
        System.out.println("Established: " + graveyard8.getEstablishedYear());
        graveyard8.setTotalGraves(2500);
        System.out.println("Total Graves: " + graveyard8.getTotalGraves());
        graveyard8.setType("Muslim Sunni");
        System.out.println("Type: " + graveyard8.getType());
        graveyard8.setCaretaker("Masjid Committee");
        System.out.println("Caretaker: " + graveyard8.getCaretaker());
        System.out.println();

        Graveyard graveyard9 = new Graveyard();
        graveyard9.setGraveyardId(9);
        System.out.println("Graveyard ID: " + graveyard9.getGraveyardId());
        graveyard9.setGraveyardName("Agram Cemetery");
        System.out.println("Name: " + graveyard9.getGraveyardName());
        graveyard9.setLocation("Hosur Road, Bengaluru");
        System.out.println("Location: " + graveyard9.getLocation());
        graveyard9.setEstablishedYear("1869");
        System.out.println("Established: " + graveyard9.getEstablishedYear());
        graveyard9.setTotalGraves(2900);
        System.out.println("Total Graves: " + graveyard9.getTotalGraves());
        graveyard9.setType("Protestant");
        System.out.println("Type: " + graveyard9.getType());
        graveyard9.setCaretaker("St. Mark's Cathedral");
        System.out.println("Caretaker: " + graveyard9.getCaretaker());
        System.out.println();

        Graveyard graveyard10 = new Graveyard();
        graveyard10.setGraveyardId(10);
        System.out.println("Graveyard ID: " + graveyard10.getGraveyardId());
        graveyard10.setGraveyardName("Jayanagar Muslim Burial Ground");
        System.out.println("Name: " + graveyard10.getGraveyardName());
        graveyard10.setLocation("Jayanagar 4th Block");
        System.out.println("Location: " + graveyard10.getLocation());
        graveyard10.setEstablishedYear("1965");
        System.out.println("Established: " + graveyard10.getEstablishedYear());
        graveyard10.setTotalGraves(1200);
        System.out.println("Total Graves: " + graveyard10.getTotalGraves());
        graveyard10.setType("Muslim");
        System.out.println("Type: " + graveyard10.getType());
        graveyard10.setCaretaker("Jayanagar Jamaat");
        System.out.println("Caretaker: " + graveyard10.getCaretaker());
        System.out.println();

        Graveyard graveyard11 = new Graveyard();
        graveyard11.setGraveyardId(11);
        System.out.println("Graveyard ID: " + graveyard11.getGraveyardId());
        graveyard11.setGraveyardName("Frazer Town Cemetery");
        System.out.println("Name: " + graveyard11.getGraveyardName());
        graveyard11.setLocation("MM Road, Frazer Town");
        System.out.println("Location: " + graveyard11.getLocation());
        graveyard11.setEstablishedYear("1935");
        System.out.println("Established: " + graveyard11.getEstablishedYear());
        graveyard11.setTotalGraves(3400);
        System.out.println("Total Graves: " + graveyard11.getTotalGraves());
        graveyard11.setType("Christian");
        System.out.println("Type: " + graveyard11.getType());
        graveyard11.setCaretaker("Frazer Town Church");
        System.out.println("Caretaker: " + graveyard11.getCaretaker());
        System.out.println();

        Graveyard graveyard12 = new Graveyard();
        graveyard12.setGraveyardId(12);
        System.out.println("Graveyard ID: " + graveyard12.getGraveyardId());
        graveyard12.setGraveyardName("Varthur Cemetery");
        System.out.println("Name: " + graveyard12.getGraveyardName());
        graveyard12.setLocation("Varthur, Whitefield");
        System.out.println("Location: " + graveyard12.getLocation());
        graveyard12.setEstablishedYear("1980");
        System.out.println("Established: " + graveyard12.getEstablishedYear());
        graveyard12.setTotalGraves(900);
        System.out.println("Total Graves: " + graveyard12.getTotalGraves());
        graveyard12.setType("Christian");
        System.out.println("Type: " + graveyard12.getType());
        graveyard12.setCaretaker("Local Parish");
        System.out.println("Caretaker: " + graveyard12.getCaretaker());
        System.out.println();

        Graveyard graveyard13 = new Graveyard();
        graveyard13.setGraveyardId(13);
        System.out.println("Graveyard ID: " + graveyard13.getGraveyardId());
        graveyard13.setGraveyardName("Ulsoor Qabristan");
        System.out.println("Name: " + graveyard13.getGraveyardName());
        graveyard13.setLocation("Ulsoor, Bengaluru");
        System.out.println("Location: " + graveyard13.getLocation());
        graveyard13.setEstablishedYear("1890");
        System.out.println("Established: " + graveyard13.getEstablishedYear());
        graveyard13.setTotalGraves(2100);
        System.out.println("Total Graves: " + graveyard13.getTotalGraves());
        graveyard13.setType("Muslim");
        System.out.println("Type: " + graveyard13.getType());
        graveyard13.setCaretaker("Ulsoor Mosque Committee");
        System.out.println("Caretaker: " + graveyard13.getCaretaker());
        System.out.println();

        Graveyard graveyard14 = new Graveyard();
        graveyard14.setGraveyardId(14);
        System.out.println("Graveyard ID: " + graveyard14.getGraveyardId());
        graveyard14.setGraveyardName("St. Mary's Basilica Cemetery");
        System.out.println("Name: " + graveyard14.getGraveyardName());
        graveyard14.setLocation("Shivajinagar");
        System.out.println("Location: " + graveyard14.getLocation());
        graveyard14.setEstablishedYear("1810");
        System.out.println("Established: " + graveyard14.getEstablishedYear());
        graveyard14.setTotalGraves(4200);
        System.out.println("Total Graves: " + graveyard14.getTotalGraves());
        graveyard14.setType("Catholic");
        System.out.println("Type: " + graveyard14.getType());
        graveyard14.setCaretaker("Archdiocese of Bengaluru");
        System.out.println("Caretaker: " + graveyard14.getCaretaker());
        System.out.println();

        Graveyard graveyard15 = new Graveyard();
        graveyard15.setGraveyardId(15);
        System.out.println("Graveyard ID: " + graveyard15.getGraveyardId());
        graveyard15.setGraveyardName("Padmavathipuram Burial Ground");
        System.out.println("Name: " + graveyard15.getGraveyardName());
        graveyard15.setLocation("Koramangala");
        System.out.println("Location: " + graveyard15.getLocation());
        graveyard15.setEstablishedYear("1975");
        System.out.println("Established: " + graveyard15.getEstablishedYear());
        graveyard15.setTotalGraves(1400);
        System.out.println("Total Graves: " + graveyard15.getTotalGraves());
        graveyard15.setType("Christian");
        System.out.println("Type: " + graveyard15.getType());
        graveyard15.setCaretaker("Local Church");
        System.out.println("Caretaker: " + graveyard15.getCaretaker());
        System.out.println();

        Graveyard graveyard6 = new Graveyard();
        graveyard6.setGraveyardId(6);
        System.out.println("Graveyard ID: " + graveyard6.getGraveyardId());
        graveyard6.setGraveyardName("Lakshmipuram Graveyard");
        System.out.println("Name: " + graveyard6.getGraveyardName());
        graveyard6.setLocation("Indiranagar, Bengaluru");
        System.out.println("Location: " + graveyard6.getLocation());
        graveyard6.setEstablishedYear("1880");
        System.out.println("Established: " + graveyard6.getEstablishedYear());
        graveyard6.setTotalGraves(3800);
        System.out.println("Total Graves: " + graveyard6.getTotalGraves());
        graveyard6.setType("Christian");
        System.out.println("Type: " + graveyard6.getType());
        graveyard6.setCaretaker("Local Church Trust");
        System.out.println("Caretaker: " + graveyard6.getCaretaker());
        System.out.println();

        Graveyard graveyard7 = new Graveyard();
        graveyard7.setGraveyardId(7);
        System.out.println("Graveyard ID: " + graveyard7.getGraveyardId());
        graveyard7.setGraveyardName("Sacred Heart Cemetery");
        System.out.println("Name: " + graveyard7.getGraveyardName());
        graveyard7.setLocation("Victoria Layout, Bengaluru");
        System.out.println("Location: " + graveyard7.getLocation());
        graveyard7.setEstablishedYear("1952");
        System.out.println("Established: " + graveyard7.getEstablishedYear());
        graveyard7.setTotalGraves(1800);
        System.out.println("Total Graves: " + graveyard7.getTotalGraves());
        graveyard7.setType("Catholic");
        System.out.println("Type: " + graveyard7.getType());
        graveyard7.setCaretaker("Sacred Heart Church");
        System.out.println("Caretaker: " + graveyard7.getCaretaker());
        System.out.println();

        Graveyard graveyard8 = new Graveyard();
        graveyard8.setGraveyardId(8);
        System.out.println("Graveyard ID: " + graveyard8.getGraveyardId());
        graveyard8.setGraveyardName("Sunnat Qabristan");
        System.out.println("Name: " + graveyard8.setGraveyardName());
        graveyard8.setLocation("Shivajinagar, Bengaluru");
        System.out.println("Location: " + graveyard8.getLocation());
        graveyard8.setEstablishedYear("1910");
        System.out.println("Established: " + graveyard8.getEstablishedYear());
        graveyard8.setTotalGraves(2500);
        System.out.println("Total Graves: " + graveyard8.getTotalGraves());
        graveyard8.setType("Muslim Sunni");
        System.out.println("Type: " + graveyard8.getType());
        graveyard8.setCaretaker("Masjid Committee");
        System.out.println("Caretaker: " + graveyard8.getCaretaker());
        System.out.println();

        Graveyard graveyard9 = new Graveyard();
        graveyard9.setGraveyardId(9);
        System.out.println("Graveyard ID: " + graveyard9.getGraveyardId());
        graveyard9.setGraveyardName("Agram Cemetery");
        System.out.println("Name: " + graveyard9.getGraveyardName());
        graveyard9.setLocation("Hosur Road, Bengaluru");
        System.out.println("Location: " + graveyard9.getLocation());
        graveyard9.setEstablishedYear("1869");
        System.out.println("Established: " + graveyard9.getEstablishedYear());
        graveyard9.setTotalGraves(2900);
        System.out.println("Total Graves: " + graveyard9.getTotalGraves());
        graveyard9.setType("Protestant");
        System.out.println("Type: " + graveyard9.getType());
        graveyard9.setCaretaker("St. Mark's Cathedral");
        System.out.println("Caretaker: " + graveyard9.getCaretaker());
        System.out.println();

        Graveyard graveyard10 = new Graveyard();
        graveyard10.setGraveyardId(10);
        System.out.println("Graveyard ID: " + graveyard10.getGraveyardId());
        graveyard10.setGraveyardName("Jayanagar Muslim Burial Ground");
        System.out.println("Name: " + graveyard10.getGraveyardName());
        graveyard10.setLocation("Jayanagar 4th Block");
        System.out.println("Location: " + graveyard10.getLocation());
        graveyard10.setEstablishedYear("1965");
        System.out.println("Established: " + graveyard10.getEstablishedYear());
        graveyard10.setTotalGraves(1200);
        System.out.println("Total Graves: " + graveyard10.getTotalGraves());
        graveyard10.setType("Muslim");
        System.out.println("Type: " + graveyard10.getType());
        graveyard10.setCaretaker("Jayanagar Jamaat");
        System.out.println("Caretaker: " + graveyard10.getCaretaker());
        System.out.println();

        Graveyard graveyard11 = new Graveyard();
        graveyard11.setGraveyardId(11);
        System.out.println("Graveyard ID: " + graveyard11.getGraveyardId());
        graveyard11.setGraveyardName("Frazer Town Cemetery");
        System.out.println("Name: " + graveyard11.getGraveyardName());
        graveyard11.setLocation("MM Road, Frazer Town");
        System.out.println("Location: " + graveyard11.getLocation());
        graveyard11.setEstablishedYear("1935");
        System.out.println("Established: " + graveyard11.getEstablishedYear());
        graveyard11.setTotalGraves(3400);
        System.out.println("Total Graves: " + graveyard11.getTotalGraves());
        graveyard11.setType("Christian");
        System.out.println("Type: " + graveyard11.getType());
        graveyard11.setCaretaker("Frazer Town Church");
        System.out.println("Caretaker: " + graveyard11.getCaretaker());
        System.out.println();

        Graveyard graveyard12 = new Graveyard();
        graveyard12.setGraveyardId(12);
        System.out.println("Graveyard ID: " + graveyard12.getGraveyardId());
        graveyard12.setGraveyardName("Varthur Cemetery");
        System.out.println("Name: " + graveyard12.getGraveyardName());
        graveyard12.setLocation("Varthur, Whitefield");
        System.out.println("Location: " + graveyard12.getLocation());
        graveyard12.setEstablishedYear("1980");
        System.out.println("Established: " + graveyard12.getEstablishedYear());
        graveyard12.setTotalGraves(900);
        System.out.println("Total Graves: " + graveyard12.getTotalGraves());
        graveyard12.setType("Christian");
        System.out.println("Type: " + graveyard12.getType());
        graveyard12.setCaretaker("Local Parish");
        System.out.println("Caretaker: " + graveyard12.getCaretaker());
        System.out.println();

        Graveyard graveyard13 = new Graveyard();
        graveyard13.setGraveyardId(13);
        System.out.println("Graveyard ID: " + graveyard13.getGraveyardId());
        graveyard13.setGraveyardName("Ulsoor Qabristan");
        System.out.println("Name: " + graveyard13.getGraveyardName());
        graveyard13.setLocation("Ulsoor, Bengaluru");
        System.out.println("Location: " + graveyard13.getLocation());
        graveyard13.setEstablishedYear("1890");
        System.out.println("Established: " + graveyard13.getEstablishedYear());
        graveyard13.setTotalGraves(2100);
        System.out.println("Total Graves: " + graveyard13.getTotalGraves());
        graveyard13.setType("Muslim");
        System.out.println("Type: " + graveyard13.getType());
        graveyard13.setCaretaker("Ulsoor Mosque Committee");
        System.out.println("Caretaker: " + graveyard13.getCaretaker());
        System.out.println();

        Graveyard graveyard14 = new Graveyard();
        graveyard14.setGraveyardId(14);
        System.out.println("Graveyard ID: " + graveyard14.getGraveyardId());
        graveyard14.setGraveyardName("St. Mary's Basilica Cemetery");
        System.out.println("Name: " + graveyard14.getGraveyardName());
        graveyard14.setLocation("Shivajinagar");
        System.out.println("Location: " + graveyard14.getLocation());
        graveyard14.setEstablishedYear("1810");
        System.out.println("Established: " + graveyard14.getEstablishedYear());
        graveyard14.setTotalGraves(4200);
        System.out.println("Total Graves: " + graveyard14.getTotalGraves());
        graveyard14.setType("Catholic");
        System.out.println("Type: " + graveyard14.getType());
        graveyard14.setCaretaker("Archdiocese of Bengaluru");
        System.out.println("Caretaker: " + graveyard14.getCaretaker());
        System.out.println();

        Graveyard graveyard15 = new Graveyard();
        graveyard15.setGraveyardId(15);
        System.out.println("Graveyard ID: " + graveyard15.getGraveyardId());
        graveyard15.setGraveyardName("Padmavathipuram Burial Ground");
        System.out.println("Name: " + graveyard15.getGraveyardName());
        graveyard15.setLocation("Koramangala");
        System.out.println("Location: " + graveyard15.getLocation());
        graveyard15.setEstablishedYear("1975");
        System.out.println("Established: " + graveyard15.getEstablishedYear());
        graveyard15.setTotalGraves(1400);
        System.out.println("Total Graves: " + graveyard15.getTotalGraves());
        graveyard15.setType("Christian");
        System.out.println("Type: " + graveyard15.getType());
        graveyard15.setCaretaker("Local Church");
        System.out.println("Caretaker: " + graveyard15.getCaretaker());
        System.out.println();

        Graveyard graveyard16 = new Graveyard();
        graveyard16.setGraveyardId(16);
        System.out.println("Graveyard ID: " + graveyard16.getGraveyardId());
        graveyard16.setGraveyardName("Bhashyam Circle Muslim Cemetery");
        System.out.println("Name: " + graveyard16.getGraveyardName());
        graveyard16.setLocation("RT Nagar");
        System.out.println("Location: " + graveyard16.getLocation());
        graveyard16.setEstablishedYear("1940");
        System.out.println("Established: " + graveyard16.getEstablishedYear());
        graveyard16.setTotalGraves(1600);
        System.out.println("Total Graves: " + graveyard16.getTotalGraves());
        graveyard16.setType("Muslim");
        System.out.println("Type: " + graveyard16.getType());
        graveyard16.setCaretaker("RT Nagar Jamaat");
        System.out.println("Caretaker: " + graveyard16.getCaretaker());
        System.out.println();

        Graveyard graveyard17 = new Graveyard();
        graveyard17.setGraveyardId(17);
        System.out.println("Graveyard ID: " + graveyard17.getGraveyardId());
        graveyard17.setGraveyardName("New Protestant Cemetery #2");
        System.out.println("Name: " + graveyard17.getGraveyardName());
        graveyard17.setLocation("Hosur Road");
        System.out.println("Location: " + graveyard17.getLocation());
        graveyard17.setEstablishedYear("1917");
        System.out.println("Established: " + graveyard17.getEstablishedYear());
        graveyard17.setTotalGraves(2600);
        System.out.println("Total Graves: " + graveyard17.getTotalGraves());
        graveyard17.setType("Protestant");
        System.out.println("Type: " + graveyard17.getType());
        graveyard17.setCaretaker("St. Mark's Cathedral");
        System.out.println("Caretaker: " + graveyard17.getCaretaker());
        System.out.println();
		
		  Graveyard graveyard18 = new Graveyard();
        graveyard18.setGraveyardId(18);
        System.out.println("Graveyard ID: " + graveyard18.getGraveyardId());
        graveyard18.setGraveyardName("Indian Christian Cemetery");
        System.out.println("Name: " + graveyard18.getGraveyardName());
        graveyard18.setLocation("Old Mission Road, Shanti Nagar");
        System.out.println("Location: " + graveyard18.getLocation());
        graveyard18.setEstablishedYear("1850");
        System.out.println("Established: " + graveyard18.getEstablishedYear());
        graveyard18.setTotalGraves(5200);
        System.out.println("Total Graves: " + graveyard18.getTotalGraves());
        graveyard18.setType("Christian");
        System.out.println("Type: " + graveyard18.getType());
        graveyard18.setCaretaker("Cemetery Trust");
        System.out.println("Caretaker: " + graveyard18.getCaretaker());
        System.out.println();

        Graveyard graveyard19 = new Graveyard();
        graveyard19.setGraveyardId(19);
        System.out.println("Graveyard ID: " + graveyard19.getGraveyardId());
        graveyard19.setGraveyardName("Hoskote Muslim Kabristan");
        System.out.println("Name: " + graveyard19.getGraveyardName());
        graveyard19.setLocation("Hoskote, Bengaluru Rural");
        System.out.println("Location: " + graveyard19.getLocation());
        graveyard19.setEstablishedYear("1920");
        System.out.println("Established: " + graveyard19.getEstablishedYear());
        graveyard19.setTotalGraves(1100);
        System.out.println("Total Graves: " + graveyard19.getTotalGraves());
        graveyard19.setType("Muslim");
        System.out.println("Type: " + graveyard19.getType());
        graveyard19.setCaretaker("Hoskote Jamaat");
        System.out.println("Caretaker: " + graveyard19.getCaretaker());
        System.out.println();

        Graveyard graveyard20 = new Graveyard();
        graveyard20.setGraveyardId(20);
        System.out.println("Graveyard ID: " + graveyard20.getGraveyardId());
        graveyard20.setGraveyardName("St. Philomena's Cemetery");
        System.out.println("Name: " + graveyard20.getGraveyardName());
        graveyard20.setLocation("Near St. Philomena's Church");
        System.out.println("Location: " + graveyard20.getLocation());
        graveyard20.setEstablishedYear("1955");
        System.out.println("Established: " + graveyard20.getEstablishedYear());
        graveyard20.setTotalGraves(2300);
        System.out.println("Total Graves: " + graveyard20.getTotalGraves());
        graveyard20.setType("Catholic");
        System.out.println("Type: " + graveyard20.getType());
        graveyard20.setCaretaker("St. Philomena's Church");
        System.out.println("Caretaker: " + graveyard20.getCaretaker());
        System.out.println();

        Graveyard graveyard21 = new Graveyard();
        graveyard21.setGraveyardId(21);
        System.out.println("Graveyard ID: " + graveyard21.getGraveyardId());
        graveyard21.setGraveyardName("Banashankari Temple Road Qabristan");
        System.out.println("Name: " + graveyard21.getGraveyardName());
        graveyard21.setLocation("Banashankari 2nd Stage");
        System.out.println("Location: " + graveyard21.getLocation());
        graveyard21.setEstablishedYear("1970");
        System.out.println("Established: " + graveyard21.getEstablishedYear());
        graveyard21.setTotalGraves(950);
        System.out.println("Total Graves: " + graveyard21.getTotalGraves());
        graveyard21.setType("Muslim");
        System.out.println("Type: " + graveyard21.getType());
        graveyard21.setCaretaker("Banashankari Mosque");
        System.out.println("Caretaker: " + graveyard21.getCaretaker());
        System.out.println();

        Graveyard graveyard22 = new Graveyard();
        graveyard22.setGraveyardId(22);
        System.out.println("Graveyard ID: " + graveyard22.getGraveyardId());
        graveyard22.setGraveyardName("Holy Family Cemetery");
        System.out.println("Name: " + graveyard22.getGraveyardName());
        graveyard22.setLocation("Kalyan Nagar, Bengaluru");
        System.out.println("Location: " + graveyard22.getLocation());
        graveyard22.setEstablishedYear("1968");
        System.out.println("Established: " + graveyard22.getEstablishedYear());
        graveyard22.setTotalGraves(1700);
        System.out.println("Total Graves: " + graveyard22.getTotalGraves());
        graveyard22.setType("Catholic");
        System.out.println("Type: " + graveyard22.getType());
        graveyard22.setCaretaker("Holy Family Church");
        System.out.println("Caretaker: " + graveyard22.getCaretaker());
        System.out.println();

        Graveyard graveyard23 = new Graveyard();
        graveyard23.setGraveyardId(23);
        System.out.println("Graveyard ID: " + graveyard23.getGraveyardId());
        graveyard23.setGraveyardName("KR Puram Burial Ground");
        System.out.println("Name: " + graveyard23.getGraveyardName());
        graveyard23.setLocation("KR Puram, Bengaluru");
        System.out.println("Location: " + graveyard23.getLocation());
        graveyard23.setEstablishedYear("1985");
        System.out.println("Established: " + graveyard23.getEstablishedYear());
        graveyard23.setTotalGraves(1300);
        System.out.println("Total Graves: " + graveyard23.getTotalGraves());
        graveyard23.setType("Christian");
        System.out.println("Type: " + graveyard23.getType());
        graveyard23.setCaretaker("KR Puram Church");
        System.out.println("Caretaker: " + graveyard23.getCaretaker());
        System.out.println();

        Graveyard graveyard24 = new Graveyard();
        graveyard24.setGraveyardId(24);
        System.out.println("Graveyard ID: " + graveyard24.getGraveyardId());
        graveyard24.setGraveyardName("Chowk Qabristan");
        System.out.println("Name: " + graveyard24.getGraveyardName());
        graveyard24.setLocation("City Market, Bengaluru");
        System.out.println("Location: " + graveyard24.getLocation());
        graveyard24.setEstablishedYear("1875");
        System.out.println("Established: " + graveyard24.getEstablishedYear());
        graveyard24.setTotalGraves(3100);
        System.out.println("Total Graves: " + graveyard24.getTotalGraves());
        graveyard24.setType("Muslim");
        System.out.println("Type: " + graveyard24.getType());
        graveyard24.setCaretaker("City Market Jamaat");
        System.out.println("Caretaker: " + graveyard24.getCaretaker());
        System.out.println();

        Graveyard graveyard25 = new Graveyard();
        graveyard25.setGraveyardId(25);
        System.out.println("Graveyard ID: " + graveyard25.getGraveyardId());
        graveyard25.setGraveyardName("St. Joseph's Church Cemetery");
        System.out.println("Name: " + graveyard25.getGraveyardName());
        graveyard25.setLocation("Langford Town");
        System.out.println("Location: " + graveyard25.getLocation());
        graveyard25.setEstablishedYear("1900");
        System.out.println("Established: " + graveyard25.getEstablishedYear());
        graveyard25.setTotalGraves(2800);
        System.out.println("Total Graves: " + graveyard25.getTotalGraves());
        graveyard25.setType("Catholic");
        System.out.println("Type: " + graveyard25.getType());
        graveyard25.setCaretaker("St. Joseph's Church");
        System.out.println("Caretaker: " + graveyard25.getCaretaker());
        System.out.println();

        Graveyard graveyard26 = new Graveyard();
        graveyard26.setGraveyardId(26);
        System.out.println("Graveyard ID: " + graveyard26.getGraveyardId());
        graveyard26.setGraveyardName("Yelahanka Muslim Kabristan");
        System.out.println("Name: " + graveyard26.getGraveyardName());
        graveyard26.setLocation("Yelahanka New Town");
        System.out.println("Location: " + graveyard26.getLocation());
        graveyard26.setEstablishedYear("1990");
        System.out.println("Established: " + graveyard26.getEstablishedYear());
        graveyard26.setTotalGraves(850);
        System.out.println("Total Graves: " + graveyard26.getTotalGraves());
        graveyard26.setType("Muslim");
        System.out.println("Type: " + graveyard26.getType());
        graveyard26.setCaretaker("Yelahanka Mosque");
        System.out.println("Caretaker: " + graveyard26.getCaretaker());
        System.out.println();

        Graveyard graveyard27 = new Graveyard();
        graveyard27.setGraveyardId(27);
        System.out.println("Graveyard ID: " + graveyard27.getGraveyardId());
        graveyard27.setGraveyardName("Assumption Church Cemetery");
        System.out.println("Name: " + graveyard27.getGraveyardName());
        graveyard27.setLocation("Ashok Nagar, Bengaluru");
        System.out.println("Location: " + graveyard27.getLocation());
        graveyard27.setEstablishedYear("1962");
        System.out.println("Established: " + graveyard27.getEstablishedYear());
        graveyard27.setTotalGraves(1900);
        System.out.println("Total Graves: " + graveyard27.getTotalGraves());
        graveyard27.setType("Catholic");
        System.out.println("Type: " + graveyard27.getType());
        graveyard27.setCaretaker("Assumption Church");
        System.out.println("Caretaker: " + graveyard27.getCaretaker());
        System.out.println();

        Graveyard graveyard28 = new Graveyard();
        graveyard28.setGraveyardId(28);
        System.out.println("Graveyard ID: " + graveyard28.getGraveyardId());
        graveyard28.setGraveyardName("Devanhalli Christian Cemetery");
        System.out.println("Name: " + graveyard28.getGraveyardName());
        graveyard28.setLocation("Devanhalli, Bengaluru Rural");
        System.out.println("Location: " + graveyard28.getLocation());
        graveyard28.setEstablishedYear("1895");
        System.out.println("Established: " + graveyard28.getEstablishedYear());
        graveyard28.setTotalGraves(2400);
        System.out.println("Total Graves: " + graveyard28.getTotalGraves());
        graveyard28.setType("Christian");
        System.out.println("Type: " + graveyard28.getType());
        graveyard28.setCaretaker("Devanhalli Church");
        System.out.println("Caretaker: " + graveyard28.getCaretaker());
        System.out.println();

        Graveyard graveyard29 = new Graveyard();
        graveyard29.setGraveyardId(29);
        System.out.println("Graveyard ID: " + graveyard29.getGraveyardId());
        graveyard29.setGraveyardName("Regal Circle Burial Ground");
        System.out.println("Name: " + graveyard29.getGraveyardName());
        graveyard29.setLocation("Regal Circle, Bengaluru");
        System.out.println("Location: " + graveyard29.getLocation());
        graveyard29.setEstablishedYear("1948");
        System.out.println("Established: " + graveyard29.getEstablishedYear());
        graveyard29.setTotalGraves(2100);
        System.out.println("Total Graves: " + graveyard29.getTotalGraves());
        graveyard29.setType("Christian");
        System.out.println("Type: " + graveyard29.getType());
        graveyard29.setCaretaker("Local Church Committee");
        System.out.println("Caretaker: " + graveyard29.getCaretaker());
        System.out.println();
		
		}
		
		}