class JacketExecutor {
    public static void main(String[] args) {
       Jacket d1 = new Jacket(); d1.jacketId = 4129; d1.material = "Cotton"; d1.size = "M"; d1.color = "Black"; d1.price = 1299.0;
        Jacket d2 = new Jacket(); d2.jacketId = 7385; d2.material = "Denim"; d2.size = "L"; d2.color = "Blue"; d2.price = 1899.0;
        Jacket d3 = new Jacket(); d3.jacketId = 2951; d3.material = "Leather"; d3.size = "XL"; d3.color = "Brown"; d3.price = 4999.0;
        Jacket d4 = new Jacket(); d4.jacketId = 8673; d4.material = "Wool"; d4.size = "S"; d4.color = "Grey"; d4.price = 2499.0;
        Jacket d5 = new Jacket(); d5.jacketId = 1547; d5.material = "Nylon"; d5.size = "M"; d5.color = "Green"; d5.price = 1599.0;
        Jacket d6 = new Jacket(); d6.jacketId = 6294; d6.material = "Polyester"; d6.size = "L"; d6.color = "Red"; d6.price = 1399.0;
        Jacket d7 = new Jacket(); d7.jacketId = 3816; d7.material = "Fleece"; d7.size = "XL"; d7.color = "Navy"; d7.price = 2199.0;
        Jacket d8 = new Jacket(); d8.jacketId = 9472; d8.material = "Cotton"; d8.size = "S"; d8.color = "White"; d8.price = 1199.0;
        Jacket d9 = new Jacket(); d9.jacketId = 2568; d9.material = "Denim"; d9.size = "M"; d9.color = "Indigo"; d9.price = 1799.0;
        Jacket d10 = new Jacket(); d10.jacketId = 7134; d10.material = "Leather"; d10.size = "L"; d10.color = "Black"; d10.price = 5999.0;
        Jacket d11 = new Jacket(); d11.jacketId = 4892; d11.material = "Wool"; d11.size = "XL"; d11.color = "Charcoal"; d11.price = 2799.0;
        Jacket d12 = new Jacket(); d12.jacketId = 1659; d12.material = "Nylon"; d12.size = "S"; d12.color = "Olive"; d12.price = 1699.0;
        Jacket d13 = new Jacket(); d13.jacketId = 7428; d13.material = "Polyester"; d13.size = "M"; d13.color = "Maroon"; d13.price = 1499.0;
        Jacket d14 = new Jacket(); d14.jacketId = 3917; d14.material = "Fleece"; d14.size = "L"; d14.color = "Purple"; d14.price = 2299.0;
        Jacket d15 = new Jacket(); d15.jacketId = 5836; d15.material = "Cotton"; d15.size = "XL"; d15.color = "Beige"; d15.price = 1349.0;
        Jacket d16 = new Jacket(); d16.jacketId = 2671; d16.material = "Denim"; d16.size = "S"; d16.color = "Khaki"; d16.price = 1999.0;
        Jacket d17 = new Jacket(); d17.jacketId = 9354; d17.material = "Leather"; d17.size = "M"; d17.color = "Tan"; d17.price = 5499.0;
        Jacket d18 = new Jacket(); d18.jacketId = 4728; d18.material = "Wool"; d18.size = "L"; d18.color = "Camel"; d18.price = 2599.0;
        Jacket d19 = new Jacket(); d19.jacketId = 1983; d19.material = "Nylon"; d19.size = "XL"; d19.color = "Teal"; d19.price = 1799.0;
        Jacket d20 = new Jacket(); d20.jacketId = 6542; d20.material = "Polyester"; d20.size = "S"; d20.color = "Pink"; d20.price = 1599.0;
        Jacket d21 = new Jacket(); d21.jacketId = 3279; d21.material = "Fleece"; d21.size = "M"; d21.color = "Orange"; d21.price = 2399.0;
        Jacket d22 = new Jacket(); d22.jacketId = 8916; d22.material = "Cotton"; d22.size = "L"; d22.color = "Yellow"; d22.price = 1449.0;
        Jacket d23 = new Jacket(); d23.jacketId = 5761; d23.material = "Denim"; d23.size = "XL"; d23.color = "Mustard"; d23.price = 2099.0;
        Jacket d24 = new Jacket(); d24.jacketId = 2438; d24.material = "Leather"; d24.size = "S"; d24.color = "Burgundy"; d24.price = 5699.0;
        Jacket d25 = new Jacket(); d25.jacketId = 7185; d25.material = "Wool"; d25.size = "M"; d25.color = "Lavender"; d25.price = 2699.0;
        
       Jacket p1 = new Jacket(4129, "Cotton", "M", "Black", 1299.0);
        Jacket p2 = new Jacket(7385, "Denim", "L", "Blue", 1899.0);
        Jacket p3 = new Jacket(2951, "Leather", "XL", "Brown", 4999.0);
        Jacket p4 = new Jacket(8673, "Wool", "S", "Grey", 2499.0);
        Jacket p5 = new Jacket(1547, "Nylon", "M", "Green", 1599.0);
        Jacket p6 = new Jacket(6294, "Polyester", "L", "Red", 1399.0);
        Jacket p7 = new Jacket(3816, "Fleece", "XL", "Navy", 2199.0);
        Jacket p8 = new Jacket(9472, "Cotton", "S", "White", 1199.0);
        Jacket p9 = new Jacket(2568, "Denim", "M", "Indigo", 1799.0);
        Jacket p10 = new Jacket(7134, "Leather", "L", "Black", 5999.0);
        Jacket p11 = new Jacket(4892, "Wool", "XL", "Charcoal", 2799.0);
        Jacket p12 = new Jacket(1659, "Nylon", "S", "Olive", 1699.0);
        Jacket p13 = new Jacket(7428, "Polyester", "M", "Maroon", 1499.0);
        Jacket p14 = new Jacket(3917, "Fleece", "L", "Purple", 2299.0);
        Jacket p15 = new Jacket(5836, "Cotton", "XL", "Beige", 1349.0);
        Jacket p16 = new Jacket(2671, "Denim", "S", "Khaki", 1999.0);
        Jacket p17 = new Jacket(9354, "Leather", "M", "Tan", 5499.0);
        Jacket p18 = new Jacket(4728, "Wool", "L", "Camel", 2599.0);
        Jacket p19 = new Jacket(1983, "Nylon", "XL", "Teal", 1799.0);
        Jacket p20 = new Jacket(6542, "Polyester", "S", "Pink", 1599.0);
        Jacket p21 = new Jacket(3279, "Fleece", "M", "Orange", 2399.0);
        Jacket p22 = new Jacket(8916, "Cotton", "L", "Yellow", 1449.0);
        Jacket p23 = new Jacket(5761, "Denim", "XL", "Mustard", 2099.0);
        Jacket p24 = new Jacket(2438, "Leather", "S", "Burgundy", 5699.0);
        Jacket p25 = new Jacket(7185, "Wool", "M", "Lavender", 2699.0);
        
       System.out.println("Jacket d1 ID: " + d1.jacketId + " Material: " + d1.material + " Size: " + d1.size + " Color: " + d1.color + " Price: " + d1.price);
        System.out.println("Jacket d2 ID: " + d2.jacketId + " Material: " + d2.material + " Size: " + d2.size + " Color: " + d2.color + " Price: " + d2.price);
        System.out.println("Jacket d3 ID: " + d3.jacketId + " Material: " + d3.material + " Size: " + d3.size + " Color: " + d3.color + " Price: " + d3.price);
        System.out.println("Jacket d4 ID: " + d4.jacketId + " Material: " + d4.material + " Size: " + d4.size + " Color: " + d4.color + " Price: " + d4.price);
        System.out.println("Jacket d5 ID: " + d5.jacketId + " Material: " + d5.material + " Size: " + d5.size + " Color: " + d5.color + " Price: " + d5.price);
        System.out.println("Jacket d6 ID: " + d6.jacketId + " Material: " + d6.material + " Size: " + d6.size + " Color: " + d6.color + " Price: " + d6.price);
        System.out.println("Jacket d7 ID: " + d7.jacketId + " Material: " + d7.material + " Size: " + d7.size + " Color: " + d7.color + " Price: " + d7.price);
        System.out.println("Jacket d8 ID: " + d8.jacketId + " Material: " + d8.material + " Size: " + d8.size + " Color: " + d8.color + " Price: " + d8.price);
        System.out.println("Jacket d9 ID: " + d9.jacketId + " Material: " + d9.material + " Size: " + d9.size + " Color: " + d9.color + " Price: " + d9.price);
        System.out.println("Jacket d10 ID: " + d10.jacketId + " Material: " + d10.material + " Size: " + d10.size + " Color: " + d10.color + " Price: " + d10.price);
        System.out.println("Jacket d11 ID: " + d11.jacketId + " Material: " + d11.material + " Size: " + d11.size + " Color: " + d11.color + " Price: " + d11.price);
        System.out.println("Jacket d12 ID: " + d12.jacketId + " Material: " + d12.material + " Size: " + d12.size + " Color: " + d12.color + " Price: " + d12.price);
        System.out.println("Jacket d13 ID: " + d13.jacketId + " Material: " + d13.material + " Size: " + d13.size + " Color: " + d13.color + " Price: " + d13.price);
        System.out.println("Jacket d14 ID: " + d14.jacketId + " Material: " + d14.material + " Size: " + d14.size + " Color: " + d14.color + " Price: " + d14.price);
        System.out.println("Jacket d15 ID: " + d15.jacketId + " Material: " + d15.material + " Size: " + d15.size + " Color: " + d15.color + " Price: " + d15.price);
        System.out.println("Jacket d16 ID: " + d16.jacketId + " Material: " + d16.material + " Size: " + d16.size + " Color: " + d16.color + " Price: " + d16.price);
        System.out.println("Jacket d17 ID: " + d17.jacketId + " Material: " + d17.material + " Size: " + d17.size + " Color: " + d17.color + " Price: " + d17.price);
        System.out.println("Jacket d18 ID: " + d18.jacketId + " Material: " + d18.material + " Size: " + d18.size + " Color: " + d18.color + " Price: " + d18.price);
        System.out.println("Jacket d19 ID: " + d19.jacketId + " Material: " + d19.material + " Size: " + d19.size + " Color: " + d19.color + " Price: " + d19.price);
        System.out.println("Jacket d20 ID: " + d20.jacketId + " Material: " + d20.material + " Size: " + d20.size + " Color: " + d20.color + " Price: " + d20.price);
        System.out.println("Jacket d21 ID: " + d21.jacketId + " Material: " + d21.material + " Size: " + d21.size + " Color: " + d21.color + " Price: " + d21.price);
        System.out.println("Jacket d22 ID: " + d22.jacketId + " Material: " + d22.material + " Size: " + d22.size + " Color: " + d22.color + " Price: " + d22.price);
        System.out.println("Jacket d23 ID: " + d23.jacketId + " Material: " + d23.material + " Size: " + d23.size + " Color: " + d23.color + " Price: " + d23.price);
        System.out.println("Jacket d24 ID: " + d24.jacketId + " Material: " + d24.material + " Size: " + d24.size + " Color: " + d24.color + " Price: " + d24.price);
        System.out.println("Jacket d25 ID: " + d25.jacketId + " Material: " + d25.material + " Size: " + d25.size + " Color: " + d25.color + " Price: " + d25.price);
        System.out.println("----------------------------------------------------------");
        
        System.out.println("Jacket p1 ID: " + p1.jacketId + " Material: " + p1.material + " Size: " + p1.size + " Color: " + p1.color + " Price: " + p1.price);
        System.out.println("Jacket p2 ID: " + p2.jacketId + " Material: " + p2.material + " Size: " + p2.size + " Color: " + p2.color + " Price: " + p2.price);
        System.out.println("Jacket p3 ID: " + p3.jacketId + " Material: " + p3.material + " Size: " + p3.size + " Color: " + p3.color + " Price: " + p3.price);
        System.out.println("Jacket p4 ID: " + p4.jacketId + " Material: " + p4.material + " Size: " + p4.size + " Color: " + p4.color + " Price: " + p4.price);
        System.out.println("Jacket p5 ID: " + p5.jacketId + " Material: " + p5.material + " Size: " + p5.size + " Color: " + p5.color + " Price: " + p5.price);
        System.out.println("Jacket p6 ID: " + p6.jacketId + " Material: " + p6.material + " Size: " + p6.size + " Color: " + p6.color + " Price: " + p6.price);
        System.out.println("Jacket p7 ID: " + p7.jacketId + " Material: " + p7.material + " Size: " + p7.size + " Color: " + p7.color + " Price: " + p7.price);
        System.out.println("Jacket p8 ID: " + p8.jacketId + " Material: " + p8.material + " Size: " + p8.size + " Color: " + p8.color + " Price: " + p8.price);
        System.out.println("Jacket p9 ID: " + p9.jacketId + " Material: " + p9.material + " Size: " + p9.size + " Color: " + p9.color + " Price: " + p9.price);
        System.out.println("Jacket p10 ID: " + p10.jacketId + " Material: " + p10.material + " Size: " + p10.size + " Color: " + p10.color + " Price: " + p10.price);
        System.out.println("Jacket p11 ID: " + p11.jacketId + " Material: " + p11.material + " Size: " + p11.size + " Color: " + p11.color + " Price: " + p11.price);
        System.out.println("Jacket p12 ID: " + p12.jacketId + " Material: " + p12.material + " Size: " + p12.size + " Color: " + p12.color + " Price: " + p12.price);
        System.out.println("Jacket p13 ID: " + p13.jacketId + " Material: " + p13.material + " Size: " + p13.size + " Color: " + p13.color + " Price: " + p13.price);
        System.out.println("Jacket p14 ID: " + p14.jacketId + " Material: " + p14.material + " Size: " + p14.size + " Color: " + p14.color + " Price: " + p14.price);
        System.out.println("Jacket p15 ID: " + p15.jacketId + " Material: " + p15.material + " Size: " + p15.size + " Color: " + p15.color + " Price: " + p15.price);
        System.out.println("Jacket p16 ID: " + p16.jacketId + " Material: " + p16.material + " Size: " + p16.size + " Color: " + p16.color + " Price: " + p16.price);
        System.out.println("Jacket p17 ID: " + p17.jacketId + " Material: " + p17.material + " Size: " + p17.size + " Color: " + p17.color + " Price: " + p17.price);
        System.out.println("Jacket p18 ID: " + p18.jacketId + " Material: " + p18.material + " Size: " + p18.size + " Color: " + p18.color + " Price: " + p18.price);
        System.out.println("Jacket p19 ID: " + p19.jacketId + " Material: " + p19.material + " Size: " + p19.size + " Color: " + p19.color + " Price: " + p19.price);
        System.out.println("Jacket p20 ID: " + p20.jacketId + " Material: " + p20.material + " Size: " + p20.size + " Color: " + p20.color + " Price: " + p20.price);
        System.out.println("Jacket p21 ID: " + p21.jacketId + " Material: " + p21.material + " Size: " + p21.size + " Color: " + p21.color + " Price: " + p21.price);
        System.out.println("Jacket p22 ID: " + p22.jacketId + " Material: " + p22.material + " Size: " + p22.size + " Color: " + p22.color + " Price: " + p22.price);
        System.out.println("Jacket p23 ID: " + p23.jacketId + " Material: " + p23.material + " Size: " + p23.size + " Color: " + p23.color + " Price: " + p23.price);
        System.out.println("Jacket p24 ID: " + p24.jacketId + " Material: " + p24.material + " Size: " + p24.size + " Color: " + p24.color + " Price: " + p24.price);
        System.out.println("Jacket p25 ID: " + p25.jacketId + " Material: " + p25.material + " Size: " + p25.size + " Color: " + p25.color + " Price: " + p25.price);
        System.out.println("----------------------------------------------------------");
    }
}
