class KarnatakaTreeExecutor {
    public static void main(String[] args) {

        KarnatakaTree tree1 = new KarnatakaTree();
        
        tree1.registrationId = 1001;
        tree1.botanicalName = "Neem (Azadirachta indica)";
        tree1.plantationSite = "Cubbon Park, Bengaluru";
        tree1.criticallyEndangered = false;
        tree1.datePlanted = "05/03/2020";
        tree1.recentInspection = "05/03/2025";
        tree1.inspectionNeeded = true;
        tree1.growthPattern = "Fast Growing";
        tree1.foliageType = "Compound Pinnate";
        tree1.treeHeight = 18.5;
        tree1.seedPodType = "Olive-shaped Drupe";
        tree1.therapeuticProperties = true;
        tree1.co2Sequestration = 28;
        tree1.trunkTexture = "Rough Grey";
        tree1.indigenousVariety = true;
        tree1.maturityYears = 6;
        tree1.commercialWorth = 18500.99;
        tree1.habitatZone = "Tropical Dry";
        tree1.highWaterNeeds = false;
        tree1.preferredSoil = "Well-drained Loamy";
        tree1.crownDiameter = 12;
        tree1.heatTolerant = true;
        tree1.faunaHabitat = "Birds, Butterflies";
        tree1.geoTracked = true;
        tree1.forestryZone = "Bengaluru Circle";
        tree1.annualUpkeep = 450.50;
        tree1.crisisResponse = "080-23456789";
        
        System.out.println("Registration ID: " + tree1.registrationId);
        System.out.println("Botanical Name: " + tree1.botanicalName);
        System.out.println("Plantation Site: " + tree1.plantationSite);
        System.out.println("Critically Endangered: " + tree1.criticallyEndangered);
        System.out.println("Date Planted: " + tree1.datePlanted);
        System.out.println("Recent Inspection: " + tree1.recentInspection);
        System.out.println("Inspection Needed: " + tree1.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree1.growthPattern);
        System.out.println("Foliage Type: " + tree1.foliageType);
        System.out.println("Tree Height: " + tree1.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree1.seedPodType);
        System.out.println("Therapeutic Properties: " + tree1.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree1.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree1.trunkTexture);
        System.out.println("Indigenous Variety: " + tree1.indigenousVariety);
        System.out.println("Maturity Years: " + tree1.maturityYears);
        System.out.println("Commercial Worth: ₹" + tree1.commercialWorth);
        System.out.println("Habitat Zone: " + tree1.habitatZone);
        System.out.println("High Water Needs: " + tree1.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree1.preferredSoil);
        System.out.println("Crown Diameter: " + tree1.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree1.heatTolerant);
        System.out.println("Fauna Habitat: " + tree1.faunaHabitat);
        System.out.println("Geo Tracked: " + tree1.geoTracked);
        System.out.println("Forestry Zone: " + tree1.forestryZone);
        System.out.println("Annual Upkeep: " + tree1.annualUpkeep);
        System.out.println("Crisis Response: " + tree1.crisisResponse);
        System.out.println("-----------------------------");

       
        KarnatakaTree tree2 = new KarnatakaTree();
        tree2.registrationId = 1002;
        tree2.botanicalName = "Sandalwood (Santalum album)";
        tree2.plantationSite = "Mysuru Forest";
        tree2.criticallyEndangered = true;
        tree2.datePlanted = "05/03/2018";
        tree2.recentInspection = "05/03/2026";
        tree2.inspectionNeeded = false;
        tree2.growthPattern = "Slow Growing";
        tree2.foliageType = "Simple";
        tree2.treeHeight = 12.0;
        tree2.seedPodType = "Small Drupe";
        tree2.therapeuticProperties = true;
        tree2.co2Sequestration = 22;
        tree2.trunkTexture = "Smooth";
        tree2.indigenousVariety = true;
        tree2.maturityYears = 8;
        tree2.commercialWorth = 250000.00;
        tree2.habitatZone = "Dry Deciduous";
        tree2.highWaterNeeds = false;
        tree2.preferredSoil = "Red Sandy";
        tree2.crownDiameter = 8;
        tree2.heatTolerant = true;
        tree2.faunaHabitat = "Birds";
        tree2.geoTracked = true;
        tree2.forestryZone = "Mysuru Circle";
        tree2.annualUpkeep = 1200.00;
        tree2.crisisResponse = "0821-56789012";
        
        System.out.println("Registration ID: " + tree2.registrationId);
        System.out.println("Botanical Name: " + tree2.botanicalName);
        System.out.println("Plantation Site: " + tree2.plantationSite);
        System.out.println("Critically Endangered: " + tree2.criticallyEndangered);
        System.out.println("Date Planted: " + tree2.datePlanted);
        System.out.println("Recent Inspection: " + tree2.recentInspection);
        System.out.println("Inspection Needed: " + tree2.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree2.growthPattern);
        System.out.println("Foliage Type: " + tree2.foliageType);
        System.out.println("Tree Height: " + tree2.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree2.seedPodType);
        System.out.println("Therapeutic Properties: " + tree2.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree2.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree2.trunkTexture);
        System.out.println("Indigenous Variety: " + tree2.indigenousVariety);
        System.out.println("Maturity Years: " + tree2.maturityYears);
        System.out.println("Commercial Worth: " + tree2.commercialWorth);
        System.out.println("Habitat Zone: " + tree2.habitatZone);
        System.out.println("High Water Needs: " + tree2.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree2.preferredSoil);
        System.out.println("Crown Diameter: " + tree2.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree2.heatTolerant);
        System.out.println("Fauna Habitat: " + tree2.faunaHabitat);
        System.out.println("Geo Tracked: " + tree2.geoTracked);
        System.out.println("Forestry Zone: " + tree2.forestryZone);
        System.out.println("Annual Upkeep: " + tree2.annualUpkeep);
        System.out.println("Crisis Response: " + tree2.crisisResponse);
        System.out.println("-----------------------------");

        
        KarnatakaTree tree3 = new KarnatakaTree();
        tree3.registrationId = 1003;
        tree3.botanicalName = "Jackfruit (Artocarpus heterophyllus)";
        tree3.plantationSite = "Bannerghatta Forest";
        tree3.criticallyEndangered = false;
        tree3.datePlanted = "05/03/2022";
        tree3.recentInspection = "05/03/2026";
        tree3.inspectionNeeded = false;
        tree3.growthPattern = "Fast Growing";
        tree3.foliageType = "Large Oval";
        tree3.treeHeight = 15.0;
        tree3.seedPodType = "Multiple Fruit";
        tree3.therapeuticProperties = true;
        tree3.co2Sequestration = 35;
        tree3.trunkTexture = "Rough Brown";
        tree3.indigenousVariety = true;
        tree3.maturityYears = 4;
        tree3.commercialWorth = 12500.00;
        tree3.habitatZone = "Tropical Wet";
        tree3.highWaterNeeds = true;
        tree3.preferredSoil = "Loamy";
        tree3.crownDiameter = 15;
        tree3.heatTolerant = false;
        tree3.faunaHabitat = "Monkeys, Birds";
        tree3.geoTracked = true;
        tree3.forestryZone = "Bengaluru Circle";
        tree3.annualUpkeep = 350.00;
        tree3.crisisResponse = "080-34567890";
        
        System.out.println("Registration ID: " + tree3.registrationId);
        System.out.println("Botanical Name: " + tree3.botanicalName);
        System.out.println("Plantation Site: " + tree3.plantationSite);
        System.out.println("Critically Endangered: " + tree3.criticallyEndangered);
        System.out.println("Date Planted: " + tree3.datePlanted);
        System.out.println("Recent Inspection: " + tree3.recentInspection);
        System.out.println("Inspection Needed: " + tree3.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree3.growthPattern);
        System.out.println("Foliage Type: " + tree3.foliageType);
        System.out.println("Tree Height: " + tree3.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree3.seedPodType);
        System.out.println("Therapeutic Properties: " + tree3.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree3.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree3.trunkTexture);
        System.out.println("Indigenous Variety: " + tree3.indigenousVariety);
        System.out.println("Maturity Years: " + tree3.maturityYears);
        System.out.println("Commercial Worth: " + tree3.commercialWorth);
        System.out.println("Habitat Zone: " + tree3.habitatZone);
        System.out.println("High Water Needs: " + tree3.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree3.preferredSoil);
        System.out.println("Crown Diameter: " + tree3.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree3.heatTolerant);
        System.out.println("Fauna Habitat: " + tree3.faunaHabitat);
        System.out.println("Geo Tracked: " + tree3.geoTracked);
        System.out.println("Forestry Zone: " + tree3.forestryZone);
        System.out.println("Annual Upkeep: " + tree3.annualUpkeep);
        System.out.println("Crisis Response: " + tree3.crisisResponse);
        System.out.println("-----------------------------");
		
	
        KarnatakaTree tree4 = new KarnatakaTree();
        tree4.registrationId = 1004;
        tree4.botanicalName = "Teak (Tectona grandis)";
        tree4.plantationSite = "Bandipur Tiger Reserve";
        tree4.criticallyEndangered = false;
        tree4.datePlanted = "05/03/2019";
        tree4.recentInspection = "05/03/2026";
        tree4.inspectionNeeded = true;
        tree4.growthPattern = "Moderate Growing";
        tree4.foliageType = "Large Simple";
        tree4.treeHeight = 22.0;
        tree4.seedPodType = "Dry Capsule";
        tree4.therapeuticProperties = false;
        tree4.co2Sequestration = 32;
        tree4.trunkTexture = "Smooth Grey";
        tree4.indigenousVariety = true;
        tree4.maturityYears = 7;
        tree4.commercialWorth = 45000.00;
        tree4.habitatZone = "Moist Deciduous";
        tree4.highWaterNeeds = true;
        tree4.preferredSoil = "Deep Alluvial";
        tree4.crownDiameter = 18;
        tree4.heatTolerant = true;
        tree4.faunaHabitat = "Deer, Squirrels";
        tree4.geoTracked = true;
        tree4.forestryZone = "Mysuru Circle";
        tree4.annualUpkeep = 650.00;
        tree4.crisisResponse = "0821-23456789";
        
        System.out.println("Registration ID: " + tree4.registrationId);
        System.out.println("Botanical Name: " + tree4.botanicalName);
        System.out.println("Plantation Site: " + tree4.plantationSite);
        System.out.println("Critically Endangered: " + tree4.criticallyEndangered);
        System.out.println("Date Planted: " + tree4.datePlanted);
        System.out.println("Recent Inspection: " + tree4.recentInspection);
        System.out.println("Inspection Needed: " + tree4.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree4.growthPattern);
        System.out.println("Foliage Type: " + tree4.foliageType);
        System.out.println("Tree Height: " + tree4.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree4.seedPodType);
        System.out.println("Therapeutic Properties: " + tree4.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree4.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree4.trunkTexture);
        System.out.println("Indigenous Variety: " + tree4.indigenousVariety);
        System.out.println("Maturity Years: " + tree4.maturityYears);
        System.out.println("Commercial Worth: " + tree4.commercialWorth);
        System.out.println("Habitat Zone: " + tree4.habitatZone);
        System.out.println("High Water Needs: " + tree4.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree4.preferredSoil);
        System.out.println("Crown Diameter: " + tree4.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree4.heatTolerant);
        System.out.println("Fauna Habitat: " + tree4.faunaHabitat);
        System.out.println("Geo Tracked: " + tree4.geoTracked);
        System.out.println("Forestry Zone: " + tree4.forestryZone);
        System.out.println("Annual Upkeep: " + tree4.annualUpkeep);
        System.out.println("Crisis Response: " + tree4.crisisResponse);
        System.out.println("-----------------------------");

       
        KarnatakaTree tree5 = new KarnatakaTree();
        tree5.registrationId = 1005;
        tree5.botanicalName = "Peepal (Ficus religiosa)";
        tree5.plantationSite = "Nandi Hills";
        tree5.criticallyEndangered = false;
        tree5.datePlanted = "05/03/2015";
        tree5.recentInspection = "05/03/2026";
        tree5.inspectionNeeded = false;
        tree5.growthPattern = "Fast Growing";
        tree5.foliageType = "Heart-shaped";
        tree5.treeHeight = 25.0;
        tree5.seedPodType = "Fig-like Syconium";
        tree5.therapeuticProperties = true;
        tree5.co2Sequestration = 45;
        tree5.trunkTexture = "Grey Brown";
        tree5.indigenousVariety = true;
        tree5.maturityYears = 11;
        tree5.commercialWorth = 28000.00;
        tree5.habitatZone = "All Zones";
        tree5.highWaterNeeds = false;
        tree5.preferredSoil = "Any Soil Type";
        tree5.crownDiameter = 25;
        tree5.heatTolerant = true;
        tree5.faunaHabitat = "Birds, Bats";
        tree5.geoTracked = true;
        tree5.forestryZone = "Bengaluru Circle";
        tree5.annualUpkeep = 200.00;
        tree5.crisisResponse = "080-45678901";
        
        System.out.println("Registration ID: " + tree5.registrationId);
        System.out.println("Botanical Name: " + tree5.botanicalName);
        System.out.println("Plantation Site: " + tree5.plantationSite);
        System.out.println("Critically Endangered: " + tree5.criticallyEndangered);
        System.out.println("Date Planted: " + tree5.datePlanted);
        System.out.println("Recent Inspection: " + tree5.recentInspection);
        System.out.println("Inspection Needed: " + tree5.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree5.growthPattern);
        System.out.println("Foliage Type: " + tree5.foliageType);
        System.out.println("Tree Height: " + tree5.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree5.seedPodType);
        System.out.println("Therapeutic Properties: " + tree5.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree5.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree5.trunkTexture);
        System.out.println("Indigenous Variety: " + tree5.indigenousVariety);
        System.out.println("Maturity Years: " + tree5.maturityYears);
        System.out.println("Commercial Worth: " + tree5.commercialWorth);
        System.out.println("Habitat Zone: " + tree5.habitatZone);
        System.out.println("High Water Needs: " + tree5.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree5.preferredSoil);
        System.out.println("Crown Diameter: " + tree5.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree5.heatTolerant);
        System.out.println("Fauna Habitat: " + tree5.faunaHabitat);
        System.out.println("Geo Tracked: " + tree5.geoTracked);
        System.out.println("Forestry Zone: " + tree5.forestryZone);
        System.out.println("Annual Upkeep: " + tree5.annualUpkeep);
        System.out.println("Crisis Response: " + tree5.crisisResponse);
        System.out.println("-----------------------------");
		
		
        KarnatakaTree tree6 = new KarnatakaTree();
        tree6.registrationId = 1006;
        tree6.botanicalName = "Banyan (Ficus benghalensis)";
        tree6.plantationSite = "BR Hills";
        tree6.criticallyEndangered = false;
        tree6.datePlanted = "05/03/2012";
        tree6.recentInspection = "05/03/2026";
        tree6.inspectionNeeded = false;
        tree6.growthPattern = "Very Fast Growing";
        tree6.foliageType = "Oval Glossy";
        tree6.treeHeight = 28.0;
        tree6.seedPodType = "Fig-like Syconium";
        tree6.therapeuticProperties = true;
        tree6.co2Sequestration = 55;
        tree6.trunkTexture = "Aerial Roots Grey";
        tree6.indigenousVariety = true;
        tree6.maturityYears = 14;
        tree6.commercialWorth = 35000.00;
        tree6.habitatZone = "All Zones";
        tree6.highWaterNeeds = false;
        tree6.preferredSoil = "Fertile Loamy";
        tree6.crownDiameter = 35;
        tree6.heatTolerant = true;
        tree6.faunaHabitat = "Birds, Bats, Monkeys";
        tree6.geoTracked = true;
        tree6.forestryZone = "Chamarajanagar";
        tree6.annualUpkeep = 180.00;
        tree6.crisisResponse = "08226-123456";
        
        System.out.println("Registration ID: " + tree6.registrationId);
        System.out.println("Botanical Name: " + tree6.botanicalName);
        System.out.println("Plantation Site: " + tree6.plantationSite);
        System.out.println("Critically Endangered: " + tree6.criticallyEndangered);
        System.out.println("Date Planted: " + tree6.datePlanted);
        System.out.println("Recent Inspection: " + tree6.recentInspection);
        System.out.println("Inspection Needed: " + tree6.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree6.growthPattern);
        System.out.println("Foliage Type: " + tree6.foliageType);
        System.out.println("Tree Height: " + tree6.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree6.seedPodType);
        System.out.println("Therapeutic Properties: " + tree6.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree6.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree6.trunkTexture);
        System.out.println("Indigenous Variety: " + tree6.indigenousVariety);
        System.out.println("Maturity Years: " + tree6.maturityYears);
        System.out.println("Commercial Worth: " + tree6.commercialWorth);
        System.out.println("Habitat Zone: " + tree6.habitatZone);
        System.out.println("High Water Needs: " + tree6.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree6.preferredSoil);
        System.out.println("Crown Diameter: " + tree6.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree6.heatTolerant);
        System.out.println("Fauna Habitat: " + tree6.faunaHabitat);
        System.out.println("Geo Tracked: " + tree6.geoTracked);
        System.out.println("Forestry Zone: " + tree6.forestryZone);
        System.out.println("Annual Upkeep: " + tree6.annualUpkeep);
        System.out.println("Crisis Response: " + tree6.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree7 = new KarnatakaTree();
        tree7.registrationId = 1007;
        tree7.botanicalName = "Mango (Mangifera indica)";
        tree7.plantationSite = "Kabini Wildlife Sanctuary";
        tree7.criticallyEndangered = false;
        tree7.datePlanted = "05/03/2021";
        tree7.recentInspection = "05/03/2026";
        tree7.inspectionNeeded = true;
        tree7.growthPattern = "Moderate Growing";
        tree7.foliageType = "Lanceolate";
        tree7.treeHeight = 16.0;
        tree7.seedPodType = "Drupaceous Fruit";
        tree7.therapeuticProperties = true;
        tree7.co2Sequestration = 30;
        tree7.trunkTexture = "Rough Brown";
        tree7.indigenousVariety = true;
        tree7.maturityYears = 5;
        tree7.commercialWorth = 22000.00;
        tree7.habitatZone = "Tropical";
        tree7.highWaterNeeds = true;
        tree7.preferredSoil = "Laterite Loamy";
        tree7.crownDiameter = 14;
        tree7.heatTolerant = true;
        tree7.faunaHabitat = "Birds, Squirrels";
        tree7.geoTracked = true;
        tree7.forestryZone = "Mysuru Circle";
        tree7.annualUpkeep = 420.00;
        tree7.crisisResponse = "08226-789012";
        
        System.out.println("Registration ID: " + tree7.registrationId);
        System.out.println("Botanical Name: " + tree7.botanicalName);
        System.out.println("Plantation Site: " + tree7.plantationSite);
        System.out.println("Critically Endangered: " + tree7.criticallyEndangered);
        System.out.println("Date Planted: " + tree7.datePlanted);
        System.out.println("Recent Inspection: " + tree7.recentInspection);
        System.out.println("Inspection Needed: " + tree7.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree7.growthPattern);
        System.out.println("Foliage Type: " + tree7.foliageType);
        System.out.println("Tree Height: " + tree7.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree7.seedPodType);
        System.out.println("Therapeutic Properties: " + tree7.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree7.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree7.trunkTexture);
        System.out.println("Indigenous Variety: " + tree7.indigenousVariety);
        System.out.println("Maturity Years: " + tree7.maturityYears);
        System.out.println("Commercial Worth: " + tree7.commercialWorth);
        System.out.println("Habitat Zone: " + tree7.habitatZone);
        System.out.println("High Water Needs: " + tree7.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree7.preferredSoil);
        System.out.println("Crown Diameter: " + tree7.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree7.heatTolerant);
        System.out.println("Fauna Habitat: " + tree7.faunaHabitat);
        System.out.println("Geo Tracked: " + tree7.geoTracked);
        System.out.println("Forestry Zone: " + tree7.forestryZone);
        System.out.println("Annual Upkeep: " + tree7.annualUpkeep);
        System.out.println("Crisis Response: " + tree7.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree8 = new KarnatakaTree();
        tree8.registrationId = 1008;
        tree8.botanicalName = "Tamarind (Tamarindus indica)";
        tree8.plantationSite = "Dandeli Wildlife Sanctuary";
        tree8.criticallyEndangered = false;
        tree8.datePlanted = "05/03/2017";
        tree8.recentInspection = "05/03/2026";
        tree8.inspectionNeeded = false;
        tree8.growthPattern = "Slow Growing";
        tree8.foliageType = "Compound Even-Pinnate";
        tree8.treeHeight = 20.0;
        tree8.seedPodType = "Brown Pods";
        tree8.therapeuticProperties = true;
        tree8.co2Sequestration = 38;
        tree8.trunkTexture = "Rough Dark Brown";
        tree8.indigenousVariety = true;
        tree8.maturityYears = 9;
        tree8.commercialWorth = 18000.00;
        tree8.habitatZone = "Dry Deciduous";
        tree8.highWaterNeeds = false;
        tree8.preferredSoil = "Sandy Loam";
        tree8.crownDiameter = 16;
        tree8.heatTolerant = true;
        tree8.faunaHabitat = "Deer, Birds";
        tree8.geoTracked = true;
        tree8.forestryZone = "Dharwad Circle";
        tree8.annualUpkeep = 280.00;
        tree8.crisisResponse = "0836-45678901";
        
        System.out.println("Registration ID: " + tree8.registrationId);
        System.out.println("Botanical Name: " + tree8.botanicalName);
        System.out.println("Plantation Site: " + tree8.plantationSite);
        System.out.println("Critically Endangered: " + tree8.criticallyEndangered);
        System.out.println("Date Planted: " + tree8.datePlanted);
        System.out.println("Recent Inspection: " + tree8.recentInspection);
        System.out.println("Inspection Needed: " + tree8.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree8.growthPattern);
        System.out.println("Foliage Type: " + tree8.foliageType);
        System.out.println("Tree Height: " + tree8.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree8.seedPodType);
        System.out.println("Therapeutic Properties: " + tree8.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree8.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree8.trunkTexture);
        System.out.println("Indigenous Variety: " + tree8.indigenousVariety);
        System.out.println("Maturity Years: " + tree8.maturityYears);
        System.out.println("Commercial Worth: " + tree8.commercialWorth);
        System.out.println("Habitat Zone: " + tree8.habitatZone);
        System.out.println("High Water Needs: " + tree8.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree8.preferredSoil);
        System.out.println("Crown Diameter: " + tree8.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree8.heatTolerant);
        System.out.println("Fauna Habitat: " + tree8.faunaHabitat);
        System.out.println("Geo Tracked: " + tree8.geoTracked);
        System.out.println("Forestry Zone: " + tree8.forestryZone);
        System.out.println("Annual Upkeep: " + tree8.annualUpkeep);
        System.out.println("Crisis Response: " + tree8.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree9 = new KarnatakaTree();
        tree9.registrationId = 1009;
        tree9.botanicalName = "Jamun (Syzygium cumini)";
        tree9.plantationSite = "Shivanasamudra";
        tree9.criticallyEndangered = false;
        tree9.datePlanted = "05/03/2023";
        tree9.recentInspection = "05/03/2026";
        tree9.inspectionNeeded = true;
        tree9.growthPattern = "Fast Growing";
        tree9.foliageType = "Oval Lanceolate";
        tree9.treeHeight = 14.0;
        tree9.seedPodType = "Purple Berry";
        tree9.therapeuticProperties = true;
        tree9.co2Sequestration = 26;
        tree9.trunkTexture = "Smooth Grey";
        tree9.indigenousVariety = true;
        tree9.maturityYears = 3;
        tree9.commercialWorth = 9500.00;
        tree9.habitatZone = "Moist Deciduous";
        tree9.highWaterNeeds = true;
        tree9.preferredSoil = "Clay Loam";
        tree9.crownDiameter = 10;
        tree9.heatTolerant = true;
        tree9.faunaHabitat = "Birds, Bats";
        tree9.geoTracked = true;
        tree9.forestryZone = "Shivamogga Circle";
        tree9.annualUpkeep = 320.00;
        tree9.crisisResponse = "08182-234567";
        
        System.out.println("Registration ID: " + tree9.registrationId);
        System.out.println("Botanical Name: " + tree9.botanicalName);
        System.out.println("Plantation Site: " + tree9.plantationSite);
        System.out.println("Critically Endangered: " + tree9.criticallyEndangered);
        System.out.println("Date Planted: " + tree9.datePlanted);
        System.out.println("Recent Inspection: " + tree9.recentInspection);
        System.out.println("Inspection Needed: " + tree9.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree9.growthPattern);
        System.out.println("Foliage Type: " + tree9.foliageType);
        System.out.println("Tree Height: " + tree9.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree9.seedPodType);
        System.out.println("Therapeutic Properties: " + tree9.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree9.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree9.trunkTexture);
        System.out.println("Indigenous Variety: " + tree9.indigenousVariety);
        System.out.println("Maturity Years: " + tree9.maturityYears);
        System.out.println("Commercial Worth: " + tree9.commercialWorth);
        System.out.println("Habitat Zone: " + tree9.habitatZone);
        System.out.println("High Water Needs: " + tree9.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree9.preferredSoil);
        System.out.println("Crown Diameter: " + tree9.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree9.heatTolerant);
        System.out.println("Fauna Habitat: " + tree9.faunaHabitat);
        System.out.println("Geo Tracked: " + tree9.geoTracked);
        System.out.println("Forestry Zone: " + tree9.forestryZone);
        System.out.println("Annual Upkeep: " + tree9.annualUpkeep);
        System.out.println("Crisis Response: " + tree9.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree10 = new KarnatakaTree();
        tree10.registrationId = 1010;
        tree10.botanicalName = "Rosewood (Dalbergia latifolia)";
        tree10.plantationSite = "Western Ghats";
        tree10.criticallyEndangered = true;
        tree10.datePlanted = "05/03/2016";
        tree10.recentInspection = "05/03/2026";
        tree10.inspectionNeeded = true;
        tree10.growthPattern = "Slow Growing";
        tree10.foliageType = "Compound Imperfect";
        tree10.treeHeight = 19.0;
        tree10.seedPodType = "Flat Pods";
        tree10.therapeuticProperties = true;
        tree10.co2Sequestration = 29;
        tree10.trunkTexture = "Dark Brown";
        tree10.indigenousVariety = true;
        tree10.maturityYears = 10;
        tree10.commercialWorth = 75000.00;
        tree10.habitatZone = "Evergreen Forest";
        tree10.highWaterNeeds = true;
        tree10.preferredSoil = "Rich Loamy";
        tree10.crownDiameter = 13;
        tree10.heatTolerant = false;
        tree10.faunaHabitat = "Insects, Birds";
        tree10.geoTracked = true;
        tree10.forestryZone = "Belagavi Circle";
        tree10.annualUpkeep = 850.00;
        tree10.crisisResponse = "0831-56789012";
        
        System.out.println("Registration ID: " + tree10.registrationId);
        System.out.println("Botanical Name: " + tree10.botanicalName);
        System.out.println("Plantation Site: " + tree10.plantationSite);
        System.out.println("Critically Endangered: " + tree10.criticallyEndangered);
        System.out.println("Date Planted: " + tree10.datePlanted);
        System.out.println("Recent Inspection: " + tree10.recentInspection);
        System.out.println("Inspection Needed: " + tree10.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree10.growthPattern);
        System.out.println("Foliage Type: " + tree10.foliageType);
        System.out.println("Tree Height: " + tree10.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree10.seedPodType);
        System.out.println("Therapeutic Properties: " + tree10.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree10.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree10.trunkTexture);
        System.out.println("Indigenous Variety: " + tree10.indigenousVariety);
        System.out.println("Maturity Years: " + tree10.maturityYears);
        System.out.println("Commercial Worth: " + tree10.commercialWorth);
        System.out.println("Habitat Zone: " + tree10.habitatZone);
        System.out.println("High Water Needs: " + tree10.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree10.preferredSoil);
        System.out.println("Crown Diameter: " + tree10.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree10.heatTolerant);
        System.out.println("Fauna Habitat: " + tree10.faunaHabitat);
        System.out.println("Geo Tracked: " + tree10.geoTracked);
        System.out.println("Forestry Zone: " + tree10.forestryZone);
        System.out.println("Annual Upkeep: " + tree10.annualUpkeep);
        System.out.println("Crisis Response: " + tree10.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree11 = new KarnatakaTree();
        tree11.registrationId = 1011;
        tree11.botanicalName = "Honge (Pongamia pinnata)";
        tree11.plantationSite = "Ankasamudra";
        tree11.criticallyEndangered = false;
        tree11.datePlanted = "05/03/2020";
        tree11.recentInspection = "05/03/2026";
        tree11.inspectionNeeded = false;
        tree11.growthPattern = "Fast Growing";
        tree11.foliageType = "Compound";
        tree11.treeHeight = 17.0;
        tree11.seedPodType = "Winged Seeds";
        tree11.therapeuticProperties = true;
        tree11.co2Sequestration = 33;
        tree11.trunkTexture = "Grey Bark";
        tree11.indigenousVariety = true;
        tree11.maturityYears = 6;
        tree11.commercialWorth = 14500.00;
        tree11.habitatZone = "Riverine";
        tree11.highWaterNeeds = true;
        tree11.preferredSoil = "Alluvial";
        tree11.crownDiameter = 11;
        tree11.heatTolerant = true;
        tree11.faunaHabitat = "Bees, Butterflies";
        tree11.geoTracked = true;
        tree11.forestryZone = "Shivamogga Circle";
        tree11.annualUpkeep = 380.00;
        tree11.crisisResponse = "08183-789012";
        
        System.out.println("Registration ID: " + tree11.registrationId);
        System.out.println("Botanical Name: " + tree11.botanicalName);
        System.out.println("Plantation Site: " + tree11.plantationSite);
        System.out.println("Critically Endangered: " + tree11.criticallyEndangered);
        System.out.println("Date Planted: " + tree11.datePlanted);
        System.out.println("Recent Inspection: " + tree11.recentInspection);
        System.out.println("Inspection Needed: " + tree11.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree11.growthPattern);
        System.out.println("Foliage Type: " + tree11.foliageType);
        System.out.println("Tree Height: " + tree11.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree11.seedPodType);
        System.out.println("Therapeutic Properties: " + tree11.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree11.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree11.trunkTexture);
        System.out.println("Indigenous Variety: " + tree11.indigenousVariety);
        System.out.println("Maturity Years: " + tree11.maturityYears);
        System.out.println("Commercial Worth: " + tree11.commercialWorth);
        System.out.println("Habitat Zone: " + tree11.habitatZone);
        System.out.println("High Water Needs: " + tree11.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree11.preferredSoil);
        System.out.println("Crown Diameter: " + tree11.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree11.heatTolerant);
        System.out.println("Fauna Habitat: " + tree11.faunaHabitat);
        System.out.println("Geo Tracked: " + tree11.geoTracked);
        System.out.println("Forestry Zone: " + tree11.forestryZone);
        System.out.println("Annual Upkeep: " + tree11.annualUpkeep);
        System.out.println("Crisis Response: " + tree11.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree12 = new KarnatakaTree();
        tree12.registrationId = 1012;
        tree12.botanicalName = "Arjuna (Terminalia arjuna)";
        tree12.plantationSite = "Cauvery Wildlife Sanctuary";
        tree12.criticallyEndangered = false;
        tree12.datePlanted = "05/03/2014";
        tree12.recentInspection = "05/03/2026";
        tree12.inspectionNeeded = true;
        tree12.growthPattern = "Moderate Growing";
        tree12.foliageType = "Oval Lanceolate";
        tree12.treeHeight = 21.0;
        tree12.seedPodType = "Winged Samara";
        tree12.therapeuticProperties = true;
        tree12.co2Sequestration = 40;
        tree12.trunkTexture = "Pinkish Grey";
        tree12.indigenousVariety = true;
        tree12.maturityYears = 12;
        tree12.commercialWorth = 19500.00;
        tree12.habitatZone = "Riverine Forest";
        tree12.highWaterNeeds = true;
        tree12.preferredSoil = "Moist Alluvial";
        tree12.crownDiameter = 17;
        tree12.heatTolerant = true;
        tree12.faunaHabitat = "Birds, Squirrels";
        tree12.geoTracked = true;
        tree12.forestryZone = "Hassan Circle";
        tree12.annualUpkeep = 450.00;
        tree12.crisisResponse = "08172-345678";
        
        System.out.println("Registration ID: " + tree12.registrationId);
        System.out.println("Botanical Name: " + tree12.botanicalName);
        System.out.println("Plantation Site: " + tree12.plantationSite);
        System.out.println("Critically Endangered: " + tree12.criticallyEndangered);
        System.out.println("Date Planted: " + tree12.datePlanted);
        System.out.println("Recent Inspection: " + tree12.recentInspection);
        System.out.println("Inspection Needed: " + tree12.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree12.growthPattern);
        System.out.println("Foliage Type: " + tree12.foliageType);
        System.out.println("Tree Height: " + tree12.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree12.seedPodType);
        System.out.println("Therapeutic Properties: " + tree12.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree12.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree12.trunkTexture);
        System.out.println("Indigenous Variety: " + tree12.indigenousVariety);
        System.out.println("Maturity Years: " + tree12.maturityYears);
        System.out.println("Commercial Worth: " + tree12.commercialWorth);
        System.out.println("Habitat Zone: " + tree12.habitatZone);
        System.out.println("High Water Needs: " + tree12.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree12.preferredSoil);
        System.out.println("Crown Diameter: " + tree12.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree12.heatTolerant);
        System.out.println("Fauna Habitat: " + tree12.faunaHabitat);
        System.out.println("Geo Tracked: " + tree12.geoTracked);
        System.out.println("Forestry Zone: " + tree12.forestryZone);
        System.out.println("Annual Upkeep: " + tree12.annualUpkeep);
        System.out.println("Crisis Response: " + tree12.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree13 = new KarnatakaTree();
        tree13.registrationId = 1013;
        tree13.botanicalName = "Amla (Phyllanthus emblica)";
        tree13.plantationSite = "Ranganathittu Bird Sanctuary";
        tree13.criticallyEndangered = false;
        tree13.datePlanted = "05/03/2022";
        tree13.recentInspection = "05/03/2026";
        tree13.inspectionNeeded = false;
        tree13.growthPattern = "Moderate Growing";
        tree13.foliageType = "Simple Spiral";
        tree13.treeHeight = 13.0;
        tree13.seedPodType = "Green Drupe";
        tree13.therapeuticProperties = true;
        tree13.co2Sequestration = 24;
        tree13.trunkTexture = "Light Grey";
        tree13.indigenousVariety = true;
        tree13.maturityYears = 4;
        tree13.commercialWorth = 11500.00;
        tree13.habitatZone = "Dry Deciduous";
        tree13.highWaterNeeds = false;
        tree13.preferredSoil = "Sandy Loam";
        tree13.crownDiameter = 9;
        tree13.heatTolerant = true;
        tree13.faunaHabitat = "Birds, Monkeys";
        tree13.geoTracked = true;
        tree13.forestryZone = "Mandya Circle";
        tree13.annualUpkeep = 290.00;
        tree13.crisisResponse = "08236-567890";
        
        System.out.println("Registration ID: " + tree13.registrationId);
        System.out.println("Botanical Name: " + tree13.botanicalName);
        System.out.println("Plantation Site: " + tree13.plantationSite);
        System.out.println("Critically Endangered: " + tree13.criticallyEndangered);
        System.out.println("Date Planted: " + tree13.datePlanted);
        System.out.println("Recent Inspection: " + tree13.recentInspection);
        System.out.println("Inspection Needed: " + tree13.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree13.growthPattern);
        System.out.println("Foliage Type: " + tree13.foliageType);
        System.out.println("Tree Height: " + tree13.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree13.seedPodType);
        System.out.println("Therapeutic Properties: " + tree13.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree13.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree13.trunkTexture);
        System.out.println("Indigenous Variety: " + tree13.indigenousVariety);
        System.out.println("Maturity Years: " + tree13.maturityYears);
        System.out.println("Commercial Worth: " + tree13.commercialWorth);
        System.out.println("Habitat Zone: " + tree13.habitatZone);
        System.out.println("High Water Needs: " + tree13.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree13.preferredSoil);
        System.out.println("Crown Diameter: " + tree13.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree13.heatTolerant);
        System.out.println("Fauna Habitat: " + tree13.faunaHabitat);
        System.out.println("Geo Tracked: " + tree13.geoTracked);
        System.out.println("Forestry Zone: " + tree13.forestryZone);
        System.out.println("Annual Upkeep: " + tree13.annualUpkeep);
        System.out.println("Crisis Response: " + tree13.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree14 = new KarnatakaTree();
        tree14.registrationId = 1014;
        tree14.botanicalName = "Bael (Aegle marmelos)";
        tree14.plantationSite = "Nagarhole National Park";
        tree14.criticallyEndangered = false;
        tree14.datePlanted = "05/03/2019";
        tree14.recentInspection = "05/03/2026";
        tree14.inspectionNeeded = true;
        tree14.growthPattern = "Moderate Growing";
        tree14.foliageType = "Trifoliate";
        tree14.treeHeight = 11.0;
        tree14.seedPodType = "Spiny Fruit";
        tree14.therapeuticProperties = true;
        tree14.co2Sequestration = 27;
        tree14.trunkTexture = "Spiny Grey";
        tree14.indigenousVariety = true;
        tree14.maturityYears = 7;
        tree14.commercialWorth = 9800.00;
        tree14.habitatZone = "Dry Forest";
        tree14.highWaterNeeds = false;
        tree14.preferredSoil = "Rocky Loam";
        tree14.crownDiameter = 10;
        tree14.heatTolerant = true;
        tree14.faunaHabitat = "Deer, Birds";
        tree14.geoTracked = true;
        tree14.forestryZone = "Mysuru Circle";
        tree14.annualUpkeep = 260.00;
        tree14.crisisResponse = "08228-789012";
        
        System.out.println("Registration ID: " + tree14.registrationId);
        System.out.println("Botanical Name: " + tree14.botanicalName);
        System.out.println("Plantation Site: " + tree14.plantationSite);
        System.out.println("Critically Endangered: " + tree14.criticallyEndangered);
        System.out.println("Date Planted: " + tree14.datePlanted);
        System.out.println("Recent Inspection: " + tree14.recentInspection);
        System.out.println("Inspection Needed: " + tree14.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree14.growthPattern);
        System.out.println("Foliage Type: " + tree14.foliageType);
        System.out.println("Tree Height: " + tree14.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree14.seedPodType);
        System.out.println("Therapeutic Properties: " + tree14.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree14.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree14.trunkTexture);
        System.out.println("Indigenous Variety: " + tree14.indigenousVariety);
        System.out.println("Maturity Years: " + tree14.maturityYears);
        System.out.println("Commercial Worth: " + tree14.commercialWorth);
        System.out.println("Habitat Zone: " + tree14.habitatZone);
        System.out.println("High Water Needs: " + tree14.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree14.preferredSoil);
        System.out.println("Crown Diameter: " + tree14.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree14.heatTolerant);
        System.out.println("Fauna Habitat: " + tree14.faunaHabitat);
        System.out.println("Geo Tracked: " + tree14.geoTracked);
        System.out.println("Forestry Zone: " + tree14.forestryZone);
        System.out.println("Annual Upkeep: " + tree14.annualUpkeep);
        System.out.println("Crisis Response: " + tree14.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree15 = new KarnatakaTree();
        tree15.registrationId = 1015;
        tree15.botanicalName = "Palash (Butea monosperma)";
        tree15.plantationSite = "Bhadra Wildlife Sanctuary";
        tree15.criticallyEndangered = false;
        tree15.datePlanted = "05/03/2018";
        tree15.recentInspection = "05/03/2026";
        tree15.inspectionNeeded = false;
        tree15.growthPattern = "Fast Growing";
        tree15.foliageType = "Trifoliate";
        tree15.treeHeight = 15.0;
        tree15.seedPodType = "Flat Pods";
        tree15.therapeuticProperties = true;
        tree15.co2Sequestration = 31;
        tree15.trunkTexture = "Rough Grey";
        tree15.indigenousVariety = true;
        tree15.maturityYears = 8;
        tree15.commercialWorth = 16200.00;
        tree15.habitatZone = "Dry Deciduous";
        tree15.highWaterNeeds = false;
        tree15.preferredSoil = "Black Cotton";
        tree15.crownDiameter = 12;
        tree15.heatTolerant = true;
        tree15.faunaHabitat = "Bees, Butterflies";
        tree15.geoTracked = true;
        tree15.forestryZone = "Shivamogga Circle";
        tree15.annualUpkeep = 340.00;
        tree15.crisisResponse = "08281-123456";
        
        System.out.println("Registration ID: " + tree15.registrationId);
        System.out.println("Botanical Name: " + tree15.botanicalName);
        System.out.println("Plantation Site: " + tree15.plantationSite);
        System.out.println("Critically Endangered: " + tree15.criticallyEndangered);
        System.out.println("Date Planted: " + tree15.datePlanted);
        System.out.println("Recent Inspection: " + tree15.recentInspection);
        System.out.println("Inspection Needed: " + tree15.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree15.growthPattern);
        System.out.println("Foliage Type: " + tree15.foliageType);
        System.out.println("Tree Height: " + tree15.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree15.seedPodType);
        System.out.println("Therapeutic Properties: " + tree15.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree15.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree15.trunkTexture);
        System.out.println("Indigenous Variety: " + tree15.indigenousVariety);
        System.out.println("Maturity Years: " + tree15.maturityYears);
        System.out.println("Commercial Worth: " + tree15.commercialWorth);
        System.out.println("Habitat Zone: " + tree15.habitatZone);
        System.out.println("High Water Needs: " + tree15.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree15.preferredSoil);
        System.out.println("Crown Diameter: " + tree15.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree15.heatTolerant);
        System.out.println("Fauna Habitat: " + tree15.faunaHabitat);
        System.out.println("Geo Tracked: " + tree15.geoTracked);
        System.out.println("Forestry Zone: " + tree15.forestryZone);
        System.out.println("Annual Upkeep: " + tree15.annualUpkeep);
        System.out.println("Crisis Response: " + tree15.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree16 = new KarnatakaTree();
        tree16.registrationId = 1016;
        tree16.botanicalName = "Mahogany (Swietenia mahagoni)";
        tree16.plantationSite = "Kemmannugundi";
        tree16.criticallyEndangered = false;
        tree16.datePlanted = "05/03/2021";
        tree16.recentInspection = "05/03/2026";
        tree16.inspectionNeeded = true;
        tree16.growthPattern = "Fast Growing";
        tree16.foliageType = "Pinnate Compound";
        tree16.treeHeight = 24.0;
        tree16.seedPodType = "Woody Capsule";
        tree16.therapeuticProperties = true;
        tree16.co2Sequestration = 42;
        tree16.trunkTexture = "Smooth Reddish";
        tree16.indigenousVariety = true;
        tree16.maturityYears = 5;
        tree16.commercialWorth = 38500.00;
        tree16.habitatZone = "Moist Deciduous";
        tree16.highWaterNeeds = true;
        tree16.preferredSoil = "Deep Loamy";
        tree16.crownDiameter = 20;
        tree16.heatTolerant = true;
        tree16.faunaHabitat = "Birds, Squirrels";
        tree16.geoTracked = true;
        tree16.forestryZone = "Chikkamagaluru";
        tree16.annualUpkeep = 520.00;
        tree16.crisisResponse = "08262-456789";
        
        System.out.println("Registration ID: " + tree16.registrationId);
        System.out.println("Botanical Name: " + tree16.botanicalName);
        System.out.println("Plantation Site: " + tree16.plantationSite);
        System.out.println("Critically Endangered: " + tree16.criticallyEndangered);
        System.out.println("Date Planted: " + tree16.datePlanted);
        System.out.println("Recent Inspection: " + tree16.recentInspection);
        System.out.println("Inspection Needed: " + tree16.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree16.growthPattern);
        System.out.println("Foliage Type: " + tree16.foliageType);
        System.out.println("Tree Height: " + tree16.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree16.seedPodType);
        System.out.println("Therapeutic Properties: " + tree16.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree16.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree16.trunkTexture);
        System.out.println("Indigenous Variety: " + tree16.indigenousVariety);
        System.out.println("Maturity Years: " + tree16.maturityYears);
        System.out.println("Commercial Worth: " + tree16.commercialWorth);
        System.out.println("Habitat Zone: " + tree16.habitatZone);
        System.out.println("High Water Needs: " + tree16.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree16.preferredSoil);
        System.out.println("Crown Diameter: " + tree16.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree16.heatTolerant);
        System.out.println("Fauna Habitat: " + tree16.faunaHabitat);
        System.out.println("Geo Tracked: " + tree16.geoTracked);
        System.out.println("Forestry Zone: " + tree16.forestryZone);
        System.out.println("Annual Upkeep: " + tree16.annualUpkeep);
        System.out.println("Crisis Response: " + tree16.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree17 = new KarnatakaTree();
        tree17.registrationId = 1017;
        tree17.botanicalName = "Bamboo (Bambusa bambos)";
        tree17.plantationSite = "Agumbe Rainforest";
        tree17.criticallyEndangered = false;
        tree17.datePlanted = "05/03/2023";
        tree17.recentInspection = "05/03/2026";
        tree17.inspectionNeeded = false;
        tree17.growthPattern = "Very Fast Growing";
        tree17.foliageType = "Linear";
        tree17.treeHeight = 30.0;
        tree17.seedPodType = "Infrequent Seeds";
        tree17.therapeuticProperties = true;
        tree17.co2Sequestration = 60;
        tree17.trunkTexture = "Thorny Green";
        tree17.indigenousVariety = true;
        tree17.maturityYears = 3;
        tree17.commercialWorth = 8500.00;
        tree17.habitatZone = "Evergreen Forest";
        tree17.highWaterNeeds = true;
        tree17.preferredSoil = "Wet Clay";
        tree17.crownDiameter = 8;
        tree17.heatTolerant = false;
        tree17.faunaHabitat = "Pandas, Birds";
        tree17.geoTracked = true;
        tree17.forestryZone = "Shivamogga Circle";
        tree17.annualUpkeep = 220.00;
        tree17.crisisResponse = "08181-234567";
        
        System.out.println("Registration ID: " + tree17.registrationId);
        System.out.println("Botanical Name: " + tree17.botanicalName);
        System.out.println("Plantation Site: " + tree17.plantationSite);
        System.out.println("Critically Endangered: " + tree17.criticallyEndangered);
        System.out.println("Date Planted: " + tree17.datePlanted);
        System.out.println("Recent Inspection: " + tree17.recentInspection);
        System.out.println("Inspection Needed: " + tree17.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree17.growthPattern);
        System.out.println("Foliage Type: " + tree17.foliageType);
        System.out.println("Tree Height: " + tree17.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree17.seedPodType);
        System.out.println("Therapeutic Properties: " + tree17.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree17.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree17.trunkTexture);
        System.out.println("Indigenous Variety: " + tree17.indigenousVariety);
        System.out.println("Maturity Years: " + tree17.maturityYears);
        System.out.println("Commercial Worth: " + tree17.commercialWorth);
        System.out.println("Habitat Zone: " + tree17.habitatZone);
        System.out.println("High Water Needs: " + tree17.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree17.preferredSoil);
        System.out.println("Crown Diameter: " + tree17.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree17.heatTolerant);
        System.out.println("Fauna Habitat: " + tree17.faunaHabitat);
        System.out.println("Geo Tracked: " + tree17.geoTracked);
        System.out.println("Forestry Zone: " + tree17.forestryZone);
        System.out.println("Annual Upkeep: " + tree17.annualUpkeep);
        System.out.println("Crisis Response: " + tree17.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree18 = new KarnatakaTree();
        tree18.registrationId = 1018;
        tree18.botanicalName = "Cashew (Anacardium occidentale)";
        tree18.plantationSite = "Kodachadri Hills";
        tree18.criticallyEndangered = false;
        tree18.datePlanted = "05/03/2020";
        tree18.recentInspection = "05/03/2026";
        tree18.inspectionNeeded = true;
        tree18.growthPattern = "Moderate Growing";
        tree18.foliageType = "Simple Oval";
        tree18.treeHeight = 12.0;
        tree18.seedPodType = "Kidney Nut";
        tree18.therapeuticProperties = true;
        tree18.co2Sequestration = 25;
        tree18.trunkTexture = "Light Grey";
        tree18.indigenousVariety = true;
        tree18.maturityYears = 6;
        tree18.commercialWorth = 13200.00;
        tree18.habitatZone = "Coastal";
        tree18.highWaterNeeds = false;
        tree18.preferredSoil = "Sandy";
        tree18.crownDiameter = 11;
        tree18.heatTolerant = true;
        tree18.faunaHabitat = "Squirrels, Birds";
        tree18.geoTracked = true;
        tree18.forestryZone = "Udupi Circle";
        tree18.annualUpkeep = 310.00;
        tree18.crisisResponse = "08252-567890";
        
        System.out.println("Registration ID: " + tree18.registrationId);
        System.out.println("Botanical Name: " + tree18.botanicalName);
        System.out.println("Plantation Site: " + tree18.plantationSite);
        System.out.println("Critically Endangered: " + tree18.criticallyEndangered);
        System.out.println("Date Planted: " + tree18.datePlanted);
        System.out.println("Recent Inspection: " + tree18.recentInspection);
        System.out.println("Inspection Needed: " + tree18.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree18.growthPattern);
        System.out.println("Foliage Type: " + tree18.foliageType);
        System.out.println("Tree Height: " + tree18.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree18.seedPodType);
        System.out.println("Therapeutic Properties: " + tree18.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree18.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree18.trunkTexture);
        System.out.println("Indigenous Variety: " + tree18.indigenousVariety);
        System.out.println("Maturity Years: " + tree18.maturityYears);
        System.out.println("Commercial Worth: " + tree18.commercialWorth);
        System.out.println("Habitat Zone: " + tree18.habitatZone);
        System.out.println("High Water Needs: " + tree18.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree18.preferredSoil);
        System.out.println("Crown Diameter: " + tree18.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree18.heatTolerant);
        System.out.println("Fauna Habitat: " + tree18.faunaHabitat);
        System.out.println("Geo Tracked: " + tree18.geoTracked);
        System.out.println("Forestry Zone: " + tree18.forestryZone);
        System.out.println("Annual Upkeep: " + tree18.annualUpkeep);
        System.out.println("Crisis Response: " + tree18.crisisResponse);
        System.out.println("-----------------------------");

        KarnatakaTree tree19 = new KarnatakaTree();
        tree19.registrationId = 1019;
        tree19.botanicalName = "Guava (Psidium guajava)";
        tree19.plantationSite = "Chikmagalur Hills";
        tree19.criticallyEndangered = false;
        tree19.datePlanted = "05/03/2022";
        tree19.recentInspection = "05/03/2026";
        tree19.inspectionNeeded = false;
        tree19.growthPattern = "Fast Growing";
        tree19.foliageType = "Oval Glossy";
        tree19.treeHeight = 10.0;
        tree19.seedPodType = "Round Fruit";
        tree19.therapeuticProperties = true;
        tree19.co2Sequestration = 22;
        tree19.trunkTexture = "Smooth Light Brown";
        tree19.indigenousVariety = true;
        tree19.maturityYears = 4;
        tree19.commercialWorth = 8900.00;
        tree19.habitatZone = "Tropical";
        tree19.highWaterNeeds = true;
        tree19.preferredSoil = "Loamy";
        tree19.crownDiameter = 8;
        tree19.heatTolerant = true;
        tree19.faunaHabitat = "Birds, Fruit Bats";
        tree19.geoTracked = true;
        tree19.forestryZone = "Chikkamagaluru";
        tree19.annualUpkeep = 270.00;
        tree19.crisisResponse = "08262-123456";
        
        System.out.println("Registration ID: " + tree19.registrationId);
        System.out.println("Botanical Name: " + tree19.botanicalName);
        System.out.println("Plantation Site: " + tree19.plantationSite);
        System.out.println("Critically Endangered: " + tree19.criticallyEndangered);
        System.out.println("Date Planted: " + tree19.datePlanted);
        System.out.println("Recent Inspection: " + tree19.recentInspection);
        System.out.println("Inspection Needed: " + tree19.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree19.growthPattern);
        System.out.println("Foliage Type: " + tree19.foliageType);
        System.out.println("Tree Height: " + tree19.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree19.seedPodType);
        System.out.println("Therapeutic Properties: " + tree19.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree19.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree19.trunkTexture);
        System.out.println("Indigenous Variety: " + tree19.indigenousVariety);
        System.out.println("Maturity Years: " + tree19.maturityYears);
        System.out.println("Commercial Worth: " + tree19.commercialWorth);
        System.out.println("Habitat Zone: " + tree19.habitatZone);
        System.out.println("High Water Needs: " + tree19.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree19.preferredSoil);
        System.out.println("Crown Diameter: " + tree19.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree19.heatTolerant);
        System.out.println("Fauna Habitat: " + tree19.faunaHabitat);
        System.out.println("Geo Tracked: " + tree19.geoTracked);
        System.out.println("Forestry Zone: " + tree19.forestryZone);
        System.out.println("Annual Upkeep: " + tree19.annualUpkeep);
        System.out.println("Crisis Response: " + tree19.crisisResponse);
        System.out.println("-----------------------------");


        KarnatakaTree tree20 = new KarnatakaTree();
        tree20.registrationId = 1020;
        tree20.botanicalName = "Coconut (Cocos nucifera)";
        tree20.plantationSite = "Malpe Beach Coastal";
        tree20.criticallyEndangered = false;
        tree20.datePlanted = "05/03/2015";
        tree20.recentInspection = "05/03/2026";
        tree20.inspectionNeeded = false;
        tree20.growthPattern = "Moderate Growing";
        tree20.foliageType = "Feathery Pinnate";
        tree20.treeHeight = 26.0;
        tree20.seedPodType = "Drupe Nut";
        tree20.therapeuticProperties = true;
        tree20.co2Sequestration = 36;
        tree20.trunkTexture = "Smooth Fibrous";
        tree20.indigenousVariety = true;
        tree20.maturityYears = 11;
        tree20.commercialWorth = 24500.00;
        tree20.habitatZone = "Coastal";
        tree20.highWaterNeeds = true;
        tree20.preferredSoil = "Sandy Coastal";
        tree20.crownDiameter = 9;
        tree20.heatTolerant = true;
        tree20.faunaHabitat = "Coconut Crab, Birds";
        tree20.geoTracked = true;
        tree20.forestryZone = "Udupi Circle";
        tree20.annualUpkeep = 410.00;
        tree20.crisisResponse = "08252-789012";
        
        System.out.println("Registration ID: " + tree20.registrationId);
        System.out.println("Botanical Name: " + tree20.botanicalName);
        System.out.println("Plantation Site: " + tree20.plantationSite);
        System.out.println("Critically Endangered: " + tree20.criticallyEndangered);
        System.out.println("Date Planted: " + tree20.datePlanted);
        System.out.println("Recent Inspection: " + tree20.recentInspection);
        System.out.println("Inspection Needed: " + tree20.inspectionNeeded);
        System.out.println("Growth Pattern: " + tree20.growthPattern);
        System.out.println("Foliage Type: " + tree20.foliageType);
        System.out.println("Tree Height: " + tree20.treeHeight + "m");
        System.out.println("Seed Pod Type: " + tree20.seedPodType);
        System.out.println("Therapeutic Properties: " + tree20.therapeuticProperties);
        System.out.println("CO2 Sequestration: " + tree20.co2Sequestration + "kg/year");
        System.out.println("Trunk Texture: " + tree20.trunkTexture);
        System.out.println("Indigenous Variety: " + tree20.indigenousVariety);
        System.out.println("Maturity Years: " + tree20.maturityYears);
        System.out.println("Commercial Worth: " + tree20.commercialWorth);
        System.out.println("Habitat Zone: " + tree20.habitatZone);
        System.out.println("High Water Needs: " + tree20.highWaterNeeds);
        System.out.println("Preferred Soil: " + tree20.preferredSoil);
        System.out.println("Crown Diameter: " + tree20.crownDiameter + "m");
        System.out.println("Heat Tolerant: " + tree20.heatTolerant);
        System.out.println("Fauna Habitat: " + tree20.faunaHabitat);
        System.out.println("Geo Tracked: " + tree20.geoTracked);
        System.out.println("Forestry Zone: " + tree20.forestryZone);
        System.out.println("Annual Upkeep: " + tree20.annualUpkeep);
        System.out.println("Crisis Response: " + tree20.crisisResponse);
        System.out.println("-----------------------------");
	
		
    }
}

