public class LoanDetailsExecutor {

    public static void main(String[] loan) {
	
        LoanDetails loan1 = new LoanDetails();
        loan1.setLoanId(1);
        System.out.println("Loan ID: " + loan1.getLoanId());
        loan1.setCustomerName("Srushti G M");
        System.out.println("Customer: " + loan1.getCustomerName());
        loan1.setLoanType("Home Loan");
        System.out.println("Type: " + loan1.getLoanType());
        loan1.setLoanAmount(2500000.00);
        System.out.println("Amount: Rs." + loan1.getLoanAmount());
        loan1.setInterestRate(8.25);
        System.out.println("Interest Rate: " + loan1.getInterestRate() + "%");
        loan1.setTenureYears(20);
        System.out.println("Tenure: " + loan1.getTenureYears() + " years");
        loan1.setLoanStatus("Active");
        System.out.println("Status: " + loan1.getLoanStatus());
        System.out.println();

        LoanDetails loan2 = new LoanDetails();
        loan2.setLoanId(2);
        System.out.println("Loan ID: " + loan2.getLoanId());
        loan2.setCustomerName("Rajesh Kumar");
        System.out.println("Customer: " + loan2.getCustomerName());
        loan2.setLoanType("Car Loan");
        System.out.println("Type: " + loan2.getLoanType());
        loan2.setLoanAmount(850000.00);
        System.out.println("Amount: Rs." + loan2.getLoanAmount());
        loan2.setInterestRate(9.75);
        System.out.println("Interest Rate: " + loan2.getInterestRate() + "%");
        loan2.setTenureYears(5);
        System.out.println("Tenure: " + loan2.getTenureYears() + " years");
        loan2.setLoanStatus("Active");
        System.out.println("Status: " + loan2.getLoanStatus());
        System.out.println();

        LoanDetails loan3 = new LoanDetails();
        loan3.setLoanId(3);
        System.out.println("Loan ID: " + loan3.getLoanId());
        loan3.setCustomerName("Priya Sharma");
        System.out.println("Customer: " + loan3.getCustomerName());
        loan3.setLoanType("Education Loan");
        System.out.println("Type: " + loan3.getLoanType());
        loan3.setLoanAmount(1200000.00);
        System.out.println("Amount: Rs." + loan3.getLoanAmount());
        loan3.setInterestRate(10.50);
        System.out.println("Interest Rate: " + loan3.getInterestRate() + "%");
        loan3.setTenureYears(7);
        System.out.println("Tenure: " + loan3.getTenureYears() + " years");
        loan3.setLoanStatus("Disbursed");
        System.out.println("Status: " + loan3.getLoanStatus());
        System.out.println();

        LoanDetails loan4 = new LoanDetails();
        loan4.setLoanId(4);
        System.out.println("Loan ID: " + loan4.getLoanId());
        loan4.setCustomerName("Anil Patel");
        System.out.println("Customer: " + loan4.getCustomerName());
        loan4.setLoanType("Personal Loan");
        System.out.println("Type: " + loan4.getLoanType());
        loan4.setLoanAmount(300000.00);
        System.out.println("Amount: Rs." + loan4.getLoanAmount());
        loan4.setInterestRate(12.00);
        System.out.println("Interest Rate: " + loan4.getInterestRate() + "%");
        loan4.setTenureYears(3);
        System.out.println("Tenure: " + loan4.getTenureYears() + " years");
        loan4.setLoanStatus("Closed");
        System.out.println("Status: " + loan4.getLoanStatus());
        System.out.println();

        LoanDetails loan5 = new LoanDetails();
        loan5.setLoanId(5);
        System.out.println("Loan ID: " + loan5.getLoanId());
        loan5.setCustomerName("Meera Reddy");
        System.out.println("Customer: " + loan5.getCustomerName());
        loan5.setLoanType("Business Loan");
        System.out.println("Type: " + loan5.getLoanType());
        loan5.setLoanAmount(5000000.00);
        System.out.println("Amount: Rs." + loan5.getLoanAmount());
        loan5.setInterestRate(11.25);
        System.out.println("Interest Rate: " + loan5.getInterestRate() + "%");
        loan5.setTenureYears(10);
        System.out.println("Tenure: " + loan5.getTenureYears() + " years");
        loan5.setLoanStatus("Approved");
        System.out.println("Status: " + loan5.getLoanStatus());
        System.out.println();
		
		LoanDetails loan6 = new LoanDetails();
        loan6.setLoanId(6);
        System.out.println("Loan ID: " + loan6.getLoanId());
        loan6.setCustomerName("Vikram Singh");
        System.out.println("Customer: " + loan6.getCustomerName());
        loan6.setLoanType("Two Wheeler Loan");
        System.out.println("Type: " + loan6.getLoanType());
        loan6.setLoanAmount(150000.00);
        System.out.println("Amount: Rs." + loan6.getLoanAmount());
        loan6.setInterestRate(11.50);
        System.out.println("Interest Rate: " + loan6.getInterestRate() + "%");
        loan6.setTenureYears(3);
        System.out.println("Tenure: " + loan6.getTenureYears() + " years");
        loan6.setLoanStatus("EMI Active");
        System.out.println("Status: " + loan6.getLoanStatus());
        System.out.println();

        LoanDetails loan7 = new LoanDetails();
        loan7.setLoanId(7);
        System.out.println("Loan ID: " + loan7.getLoanId());
        loan7.setCustomerName("Lakshmi Devi");
        System.out.println("Customer: " + loan7.getCustomerName());
        loan7.setLoanType("Gold Loan");
        System.out.println("Type: " + loan7.getLoanType());
        loan7.setLoanAmount(750000.00);
        System.out.println("Amount: Rs." + loan7.getLoanAmount());
        loan7.setInterestRate(7.50);
        System.out.println("Interest Rate: " + loan7.getInterestRate() + "%");
        loan7.setTenureYears(1);
        System.out.println("Tenure: " + loan7.getTenureYears() + " years");
        loan7.setLoanStatus("Active");
        System.out.println("Status: " + loan7.getLoanStatus());
        System.out.println();

        LoanDetails loan8 = new LoanDetails();
        loan8.setLoanId(8);
        System.out.println("Loan ID: " + loan8.getLoanId());
        loan8.setCustomerName("Kiran Gowda");
        System.out.println("Customer: " + loan8.getCustomerName());
        loan8.setLoanType("Home Improvement Loan");
        System.out.println("Type: " + loan8.getLoanType());
        loan8.setLoanAmount(800000.00);
        System.out.println("Amount: Rs." + loan8.getLoanAmount());
        loan8.setInterestRate(9.00);
        System.out.println("Interest Rate: " + loan8.getInterestRate() + "%");
        loan8.setTenureYears(5);
        System.out.println("Tenure: " + loan8.getTenureYears() + " years");
        loan8.setLoanStatus("Active");
        System.out.println("Status: " + loan8.getLoanStatus());
        System.out.println();

        LoanDetails loan9 = new LoanDetails();
        loan9.setLoanId(9);
        System.out.println("Loan ID: " + loan9.getLoanId());
        loan9.setCustomerName("Rohit Menon");
        System.out.println("Customer: " + loan9.getCustomerName());
        loan9.setLoanType("Laptop Loan");
        System.out.println("Type: " + loan9.getLoanType());
        loan9.setLoanAmount(125000.00);
        System.out.println("Amount: Rs." + loan9.getLoanAmount());
        loan9.setInterestRate(13.25);
        System.out.println("Interest Rate: " + loan9.getInterestRate() + "%");
        loan9.setTenureYears(2);
        System.out.println("Tenure: " + loan9.getTenureYears() + " years");
        loan9.setLoanStatus("Repaying");
        System.out.println("Status: " + loan9.getLoanStatus());
        System.out.println();

        LoanDetails loan10 = new LoanDetails();
        loan10.setLoanId(10);
        System.out.println("Loan ID: " + loan10.getLoanId());
        loan10.setCustomerName("Sunita Naik");
        System.out.println("Customer: " + loan10.getCustomerName());
        loan10.setLoanType("Wedding Loan");
        System.out.println("Type: " + loan10.getLoanType());
        loan10.setLoanAmount(1000000.00);
        System.out.println("Amount: Rs." + loan10.getLoanAmount());
        loan10.setInterestRate(12.75);
        System.out.println("Interest Rate: " + loan10.getInterestRate() + "%");
        loan10.setTenureYears(4);
        System.out.println("Tenure: " + loan10.getTenureYears() + " years");
        loan10.setLoanStatus("Disbursed");
        System.out.println("Status: " + loan10.getLoanStatus());
        System.out.println();

        LoanDetails loan11 = new LoanDetails();
        loan11.setLoanId(11);
        System.out.println("Loan ID: " + loan11.getLoanId());
        loan11.setCustomerName("Mohan Das");
        System.out.println("Customer: " + loan11.getCustomerName());
        loan11.setLoanType("MSME Loan");
        System.out.println("Type: " + loan11.getLoanType());
        loan11.setLoanAmount(2000000.00);
        System.out.println("Amount: Rs." + loan11.getLoanAmount());
        loan11.setInterestRate(10.00);
        System.out.println("Interest Rate: " + loan11.getInterestRate() + "%");
        loan11.setTenureYears(7);
        System.out.println("Tenure: " + loan11.getTenureYears() + " years");
        loan11.setLoanStatus("Active");
        System.out.println("Status: " + loan11.getLoanStatus());
        System.out.println();

        LoanDetails loan12 = new LoanDetails();
        loan12.setLoanId(12);
        System.out.println("Loan ID: " + loan12.getLoanId());
        loan12.setCustomerName("Deepa Rani");
        System.out.println("Customer: " + loan12.getCustomerName());
        loan12.setLoanType("Agricultural Loan");
        System.out.println("Type: " + loan12.getLoanType());
        loan12.setLoanAmount(450000.00);
        System.out.println("Amount: Rs." + loan12.getLoanAmount());
        loan12.setInterestRate(7.00);
        System.out.println("Interest Rate: " + loan12.getInterestRate() + "%");
        loan12.setTenureYears(3);
        System.out.println("Tenure: " + loan12.getTenureYears() + " years");
        loan12.setLoanStatus("Seasonal Repayment");
        System.out.println("Status: " + loan12.getLoanStatus());
        System.out.println();

        LoanDetails loan13 = new LoanDetails();
        loan13.setLoanId(13);
        System.out.println("Loan ID: " + loan13.getLoanId());
        loan13.setCustomerName("Arjun Patil");
        System.out.println("Customer: " + loan13.getCustomerName());
        loan13.setLoanType("Solar Loan");
        System.out.println("Type: " + loan13.getLoanType());
        loan13.setLoanAmount(350000.00);
        System.out.println("Amount: Rs." + loan13.getLoanAmount());
        loan13.setInterestRate(8.75);
        System.out.println("Interest Rate: " + loan13.getInterestRate() + "%");
        loan13.setTenureYears(5);
        System.out.println("Tenure: " + loan13.getTenureYears() + " years");
        loan13.setLoanStatus("Approved");
        System.out.println("Status: " + loan13.getLoanStatus());
        System.out.println();

        LoanDetails loan14 = new LoanDetails();
        loan14.setLoanId(14);
        System.out.println("Loan ID: " + loan14.getLoanId());
        loan14.setCustomerName("Neha Kapoor");
        System.out.println("Customer: " + loan14.getCustomerName());
        loan14.setLoanType("Credit Card Top-up");
        System.out.println("Type: " + loan14.getLoanType());
        loan14.setLoanAmount(250000.00);
        System.out.println("Amount: Rs." + loan14.getLoanAmount());
        loan14.setInterestRate(14.50);
        System.out.println("Interest Rate: " + loan14.getInterestRate() + "%");
        loan14.setTenureYears(2);
        System.out.println("Tenure: " + loan14.getTenureYears() + " years");
        loan14.setLoanStatus("Active");
        System.out.println("Status: " + loan14.getLoanStatus());
        System.out.println();

        LoanDetails loan15 = new LoanDetails();
        loan15.setLoanId(15);
        System.out.println("Loan ID: " + loan15.getLoanId());
        loan15.setCustomerName("Ramesh Babu");
        System.out.println("Customer: " + loan15.getCustomerName());
        loan15.setLoanType("Property Loan");
        System.out.println("Type: " + loan15.getLoanType());
        loan15.setLoanAmount(1800000.00);
        System.out.println("Amount: Rs." + loan15.getLoanAmount());
        loan15.setInterestRate(9.25);
        System.out.println("Interest Rate: " + loan15.getInterestRate() + "%");
        loan15.setTenureYears(15);
        System.out.println("Tenure: " + loan15.getTenureYears() + " years");
        loan15.setLoanStatus("Disbursed");
        System.out.println("Status: " + loan15.getLoanStatus());
        System.out.println();

        LoanDetails loan16 = new LoanDetails();
        loan16.setLoanId(16);
        System.out.println("Loan ID: " + loan16.getLoanId());
        loan16.setCustomerName("Pooja Shetty");
        System.out.println("Customer: " + loan16.getCustomerName());
        loan16.setLoanType("Festival Loan");
        System.out.println("Type: " + loan16.getLoanType());
        loan16.setLoanAmount(50000.00);
        System.out.println("Amount: Rs." + loan16.getLoanAmount());
        loan16.setInterestRate(15.00);
        System.out.println("Interest Rate: " + loan16.getInterestRate() + "%");
        loan16.setTenureYears(1);
        System.out.println("Tenure: " + loan16.getTenureYears() + " years");
        loan16.setLoanStatus("Closed");
        System.out.println("Status: " + loan16.getLoanStatus());
        System.out.println();

        LoanDetails loan17 = new LoanDetails();
        loan17.setLoanId(17);
        System.out.println("Loan ID: " + loan17.getLoanId());
        loan17.setCustomerName("Sanjay Rao");
        System.out.println("Customer: " + loan17.getCustomerName());
        loan17.setLoanType("Overdraft Loan");
        System.out.println("Type: " + loan17.getLoanType());
        loan17.setLoanAmount(1000000.00);
        System.out.println("Amount: Rs." + loan17.getLoanAmount());
        loan17.setInterestRate(10.75);
        System.out.println("Interest Rate: " + loan17.getInterestRate() + "%");
        loan17.setTenureYears(2);
        System.out.println("Tenure: " + loan17.getTenureYears() + " years");
        loan17.setLoanStatus("Active");
        System.out.println("Status: " + loan17.getLoanStatus());
        System.out.println();
		
		LoanDetails loan18 = new LoanDetails();
        loan18.setLoanId(18);
        System.out.println("Loan ID: " + loan18.getLoanId());
        loan18.setCustomerName("Ganesh Hegde");
        System.out.println("Customer: " + loan18.getCustomerName());
        loan18.setLoanType("Medical Loan");
        System.out.println("Type: " + loan18.getLoanType());
        loan18.setLoanAmount(650000.00);
        System.out.println("Amount: Rs." + loan18.getLoanAmount());
        loan18.setInterestRate(10.25);
        System.out.println("Interest Rate: " + loan18.getInterestRate() + "%");
        loan18.setTenureYears(4);
        System.out.println("Tenure: " + loan18.getTenureYears() + " years");
        loan18.setLoanStatus("Active");
        System.out.println("Status: " + loan18.getLoanStatus());
        System.out.println();

        LoanDetails loan19 = new LoanDetails();
        loan19.setLoanId(19);
        System.out.println("Loan ID: " + loan19.getLoanId());
        loan19.setCustomerName("Shweta Nair");
        System.out.println("Customer: " + loan19.getCustomerName());
        loan19.setLoanType("Travel Loan");
        System.out.println("Type: " + loan19.getLoanType());
        loan19.setLoanAmount(300000.00);
        System.out.println("Amount: Rs." + loan19.getLoanAmount());
        loan19.setInterestRate(13.00);
        System.out.println("Interest Rate: " + loan19.getInterestRate() + "%");
        loan19.setTenureYears(2);
        System.out.println("Tenure: " + loan19.getTenureYears() + " years");
        loan19.setLoanStatus("Repaying");
        System.out.println("Status: " + loan19.getLoanStatus());
        System.out.println();

        LoanDetails loan20 = new LoanDetails();
        loan20.setLoanId(20);
        System.out.println("Loan ID: " + loan20.getLoanId());
        loan20.setCustomerName("Balaji M");
        System.out.println("Customer: " + loan20.getCustomerName());
        loan20.setLoanType("Construction Equipment Loan");
        System.out.println("Type: " + loan20.getLoanType());
        loan20.setLoanAmount(3500000.00);
        System.out.println("Amount: Rs." + loan20.getLoanAmount());
        loan20.setInterestRate(11.00);
        System.out.println("Interest Rate: " + loan20.getInterestRate() + "%");
        loan20.setTenureYears(8);
        System.out.println("Tenure: " + loan20.getTenureYears() + " years");
        loan20.setLoanStatus("Approved");
        System.out.println("Status: " + loan20.getLoanStatus());
        System.out.println();

        LoanDetails loan21 = new LoanDetails();
        loan21.setLoanId(21);
        System.out.println("Loan ID: " + loan21.getLoanId());
        loan21.setCustomerName("Radha K");
        System.out.println("Customer: " + loan21.getCustomerName());
        loan21.setLoanType("Consumer Durable Loan");
        System.out.println("Type: " + loan21.getLoanType());
        loan21.setLoanAmount(200000.00);
        System.out.println("Amount: Rs." + loan21.getLoanAmount());
        loan21.setInterestRate(14.00);
        System.out.println("Interest Rate: " + loan21.getInterestRate() + "%");
        loan21.setTenureYears(2);
        System.out.println("Tenure: " + loan21.getTenureYears() + " years");
        loan21.setLoanStatus("Closed");
        System.out.println("Status: " + loan21.getLoanStatus());
        System.out.println();

        LoanDetails loan22 = new LoanDetails();
        loan22.setLoanId(22);
        System.out.println("Loan ID: " + loan22.getLoanId());
        loan22.setCustomerName("Prakash Shetty");
        System.out.println("Customer: " + loan22.getCustomerName());
        loan22.setLoanType("Working Capital Loan");
        System.out.println("Type: " + loan22.getLoanType());
        loan22.setLoanAmount(750000.00);
        System.out.println("Amount: Rs." + loan22.getLoanAmount());
        loan22.setInterestRate(12.50);
        System.out.println("Interest Rate: " + loan22.getInterestRate() + "%");
        loan22.setTenureYears(1);
        System.out.println("Tenure: " + loan22.getTenureYears() + " years");
        loan22.setLoanStatus("Renewed");
        System.out.println("Status: " + loan22.getLoanStatus());
        System.out.println();

        LoanDetails loan23 = new LoanDetails();
        loan23.setLoanId(23);
        System.out.println("Loan ID: " + loan23.getLoanId());
        loan23.setCustomerName("Anjali Joshi");
        System.out.println("Customer: " + loan23.getCustomerName());
        loan23.setLoanType("Home Top-up Loan");
        System.out.println("Type: " + loan23.getLoanType());
        loan23.setLoanAmount(1500000.00);
        System.out.println("Amount: Rs." + loan23.getLoanAmount());
        loan23.setInterestRate(9.50);
        System.out.println("Interest Rate: " + loan23.getInterestRate() + "%");
        loan23.setTenureYears(12);
        System.out.println("Tenure: " + loan23.getTenureYears() + " years");
        loan23.setLoanStatus("Active");
        System.out.println("Status: " + loan23.getLoanStatus());
        System.out.println();

        LoanDetails loan24 = new LoanDetails();
        loan24.setLoanId(24);
        System.out.println("Loan ID: " + loan24.getLoanId());
        loan24.setCustomerName("Vijay Kumar");
        System.out.println("Customer: " + loan24.getCustomerName());
        loan24.setLoanType("Vehicle Refinance Loan");
        System.out.println("Type: " + loan24.getLoanType());
        loan24.setLoanAmount(600000.00);
        System.out.println("Amount: Rs." + loan24.getLoanAmount());
        loan24.setInterestRate(8.75);
        System.out.println("Interest Rate: " + loan24.getInterestRate() + "%");
        loan24.setTenureYears(4);
        System.out.println("Tenure: " + loan24.getTenureYears() + " years");
        loan24.setLoanStatus("Transferred");
        System.out.println("Status: " + loan24.getLoanStatus());
        System.out.println();

        LoanDetails loan25 = new LoanDetails();
        loan25.setLoanId(25);
        System.out.println("Loan ID: " + loan25.getLoanId());
        loan25.setCustomerName("Kavya S");
        System.out.println("Customer: " + loan25.getCustomerName());
        loan25.setLoanType("Study Abroad Loan");
        System.out.println("Type: " + loan25.getLoanType());
        loan25.setLoanAmount(2800000.00);
        System.out.println("Amount: Rs." + loan25.getLoanAmount());
        loan25.setInterestRate(10.75);
        System.out.println("Interest Rate: " + loan25.getInterestRate() + "%");
        loan25.setTenureYears(10);
        System.out.println("Tenure: " + loan25.getTenureYears() + " years");
        loan25.setLoanStatus("Disbursed");
        System.out.println("Status: " + loan25.getLoanStatus());
        System.out.println();

        LoanDetails loan26 = new LoanDetails();
        loan26.setLoanId(26);
        System.out.println("Loan ID: " + loan26.getLoanId());
        loan26.setCustomerName("Naveen D");
        System.out.println("Customer: " + loan26.getCustomerName());
        loan26.setLoanType("EV Two Wheeler Loan");
        System.out.println("Type: " + loan26.getLoanType());
        loan26.setLoanAmount(175000.00);
        System.out.println("Amount: Rs." + loan26.getLoanAmount());
        loan26.setInterestRate(9.25);
        System.out.println("Interest Rate: " + loan26.getInterestRate() + "%");
        loan26.setTenureYears(3);
        System.out.println("Tenure: " + loan26.getTenureYears() + " years");
        loan26.setLoanStatus("Active");
        System.out.println("Status: " + loan26.getLoanStatus());
        System.out.println();

        LoanDetails loan27 = new LoanDetails();
        loan27.setLoanId(27);
        System.out.println("Loan ID: " + loan27.getLoanId());
        loan27.setCustomerName("Divya M");
        System.out.println("Customer: " + loan27.getCustomerName());
        loan27.setLoanType("Furniture Loan");
        System.out.println("Type: " + loan27.getLoanType());
        loan27.setLoanAmount(125000.00);
        System.out.println("Amount: Rs." + loan27.getLoanAmount());
        loan27.setInterestRate(13.50);
        System.out.println("Interest Rate: " + loan27.getInterestRate() + "%");
        loan27.setTenureYears(2);
        System.out.println("Tenure: " + loan27.getTenureYears() + " years");
        loan27.setLoanStatus("Repaying");
        System.out.println("Status: " + loan27.getLoanStatus());
        System.out.println();

        LoanDetails loan28 = new LoanDetails();
        loan28.setLoanId(28);
        System.out.println("Loan ID: " + loan28.getLoanId());
        loan28.setCustomerName("Suresh K");
        System.out.println("Customer: " + loan28.getCustomerName());
        loan28.setLoanType("Plot Loan");
        System.out.println("Type: " + loan28.getLoanType());
        loan28.setLoanAmount(2200000.00);
        System.out.println("Amount: Rs." + loan28.getLoanAmount());
        loan28.setInterestRate(9.00);
        System.out.println("Interest Rate: " + loan28.getInterestRate() + "%");
        loan28.setTenureYears(15);
        System.out.println("Tenure: " + loan28.getTenureYears() + " years");
        loan28.setLoanStatus("Sanctioned");
        System.out.println("Status: " + loan28.getLoanStatus());
        System.out.println();

        LoanDetails loan29 = new LoanDetails();
        loan29.setLoanId(29);
        System.out.println("Loan ID: " + loan29.getLoanId());
        loan29.setCustomerName("Geetha R");
        System.out.println("Customer: " + loan29.getCustomerName());
        loan29.setLoanType("Balance Transfer Loan");
        System.out.println("Type: " + loan29.getLoanType());
        loan29.setLoanAmount(900000.00);
        System.out.println("Amount: Rs." + loan29.getLoanAmount());
        loan29.setInterestRate(8.50);
        System.out.println("Interest Rate: " + loan29.getInterestRate() + "%");
        loan29.setTenureYears(6);
        System.out.println("Tenure: " + loan29.getTenureYears() + " years");
        loan29.setLoanStatus("Active");
        System.out.println("Status: " + loan29.getLoanStatus());
        System.out.println();
		
    }
}