class NationalGamesExecutor {
    public static void main(String[] args) {
        NationalGames game1 = new NationalGames();
        
        game1.gameId = 2001;
        game1.gameTitle = "Hockey India League";
        game1.sportCategory = "Field Hockey";
        game1.teamSport = true;
        game1.primaryNation = "India";
        game1.totalMedals = 128;
        game1.governingBody = "Hockey India";
        game1.olympicSport = true;
        game1.worldRecordTime = 2.45;
        game1.ageGroup = "Senior";
        game1.individualEvent = false;
        game1.venueCapacity = 45000;
        game1.organizingCommittee = "Hockey India";
        game1.multiNation = true;
        game1.totalParticipations = 240;
        game1.eventFormat = "League + Knockout";
        game1.qualificationRounds = true;
        game1.prizeMoney = 50000000.00;
        game1.equipmentRequired = "Sticks, Balls, Goalie Gear";
        game1.paraSport = false;
        game1.totalAthletes = 240;
        game1.eventDuration = "3 Months";
        game1.liveBroadcast = true;
        game1.tvViewership = 150000000.0;
        game1.recordHolder = "India Men";
        game1.worldChampionship = false;
        game1.peakAttendance = "42K";
        
        System.out.println("Game ID: " + game1.gameId);
        System.out.println("Game Title: " + game1.gameTitle);
        System.out.println("Sport Category: " + game1.sportCategory);
        System.out.println("Team Sport: " + game1.teamSport);
        System.out.println("Primary Nation: " + game1.primaryNation);
        System.out.println("Total Medals: " + game1.totalMedals);
        System.out.println("Governing Body: " + game1.governingBody);
        System.out.println("Olympic Sport: " + game1.olympicSport);
        System.out.println("World Record Time: " + game1.worldRecordTime + " sec");
        System.out.println("Age Group: " + game1.ageGroup);
        System.out.println("Individual Event: " + game1.individualEvent);
        System.out.println("Venue Capacity: " + game1.venueCapacity);
        System.out.println("Organizing Committee: " + game1.organizingCommittee);
        System.out.println("Multi Nation: " + game1.multiNation);
        System.out.println("Total Participations: " + game1.totalParticipations);
        System.out.println("Event Format: " + game1.eventFormat);
        System.out.println("Qualification Rounds: " + game1.qualificationRounds);
        System.out.println("Prize Money: " + game1.prizeMoney);
        System.out.println("Equipment Required: " + game1.equipmentRequired);
        System.out.println("Para Sport: " + game1.paraSport);
        System.out.println("Total Athletes: " + game1.totalAthletes);
        System.out.println("Event Duration: " + game1.eventDuration);
        System.out.println("Live Broadcast: " + game1.liveBroadcast);
        System.out.println("TV Viewership: " + game1.tvViewership);
        System.out.println("Record Holder: " + game1.recordHolder);
        System.out.println("World Championship: " + game1.worldChampionship);
        System.out.println("Peak Attendance: " + game1.peakAttendance);
        System.out.println("-----------------------------");
		
        NationalGames game2 = new NationalGames();
        
        game2.gameId = 2002;
        game2.gameTitle = "Pro Kabaddi League";
        game2.sportCategory = "Kabaddi";
        game2.teamSport = true;
        game2.primaryNation = "India";
        game2.totalMedals = 156;
        game2.governingBody = "Pro Kabaddi League Pvt Ltd";
        game2.olympicSport = true;
        game2.worldRecordTime = 45.30;
        game2.ageGroup = "Senior";
        game2.individualEvent = false;
        game2.venueCapacity = 35000;
        game2.organizingCommittee = "Mashal Sports";
        game2.multiNation = false;
        game2.totalParticipations = 192;
        game2.eventFormat = "League + Playoffs";
        game2.qualificationRounds = true;
        game2.prizeMoney = 30000000.00;
        game2.equipmentRequired = "Mats, Microphones";
        game2.paraSport = false;
        game2.totalAthletes = 192;
        game2.eventDuration = "4 Months";
        game2.liveBroadcast = true;
        game2.tvViewership = 200000000.0;
        game2.recordHolder = "Patna Pirates";
        game2.worldChampionship = false;
        game2.peakAttendance = "35K";
        
        System.out.println("Game ID: " + game2.gameId);
        System.out.println("Game Title: " + game2.gameTitle);
        System.out.println("Sport Category: " + game2.sportCategory);
        System.out.println("Team Sport: " + game2.teamSport);
        System.out.println("Primary Nation: " + game2.primaryNation);
        System.out.println("Total Medals: " + game2.totalMedals);
        System.out.println("Governing Body: " + game2.governingBody);
        System.out.println("Olympic Sport: " + game2.olympicSport);
        System.out.println("World Record Time: " + game2.worldRecordTime + " sec");
        System.out.println("Age Group: " + game2.ageGroup);
        System.out.println("Individual Event: " + game2.individualEvent);
        System.out.println("Venue Capacity: " + game2.venueCapacity);
        System.out.println("Organizing Committee: " + game2.organizingCommittee);
        System.out.println("Multi Nation: " + game2.multiNation);
        System.out.println("Total Participations: " + game2.totalParticipations);
        System.out.println("Event Format: " + game2.eventFormat);
        System.out.println("Qualification Rounds: " + game2.qualificationRounds);
        System.out.println("Prize Money: " + game2.prizeMoney);
        System.out.println("Equipment Required: " + game2.equipmentRequired);
        System.out.println("Para Sport: " + game2.paraSport);
        System.out.println("Total Athletes: " + game2.totalAthletes);
        System.out.println("Event Duration: " + game2.eventDuration);
        System.out.println("Live Broadcast: " + game2.liveBroadcast);
        System.out.println("TV Viewership: " + game2.tvViewership);
        System.out.println("Record Holder: " + game2.recordHolder);
        System.out.println("World Championship: " + game2.worldChampionship);
        System.out.println("Peak Attendance: " + game2.peakAttendance);
        System.out.println("-----------------------------");

       
	        NationalGames game3 = new NationalGames();
        
        game3.gameId = 2003;
        game3.gameTitle = "Premier Badminton League";
        game3.sportCategory = "Badminton";
        game3.teamSport = true;
        game3.primaryNation = "India";
        game3.totalMedals = 89;
        game3.governingBody = "Badminton Association of India (BAI)";
        game3.olympicSport = true;
        game3.worldRecordTime = 28.15;
        game3.ageGroup = "Senior";
        game3.individualEvent = false;
        game3.venueCapacity = 25000;
        game3.organizingCommittee = "SportzLive";
        game3.multiNation = true;
        game3.totalParticipations = 135;
        game3.eventFormat = "League + Trump Matches";
        game3.qualificationRounds = true;
        game3.prizeMoney = 15000000.00;
        game3.equipmentRequired = "Rackets, Shuttles, Nets";
        game3.paraSport = false;
        game3.totalAthletes = 135;
        game3.eventDuration = "2 Months";
        game3.liveBroadcast = true;
        game3.tvViewership = 80000000.0;
        game3.recordHolder = "Bengaluru Raptors";
        game3.worldChampionship = false;
        game3.peakAttendance = "22K";
        
        System.out.println("Game ID: " + game3.gameId);
        System.out.println("Game Title: " + game3.gameTitle);
        System.out.println("Sport Category: " + game3.sportCategory);
        System.out.println("Team Sport: " + game3.teamSport);
        System.out.println("Primary Nation: " + game3.primaryNation);
        System.out.println("Total Medals: " + game3.totalMedals);
        System.out.println("Governing Body: " + game3.governingBody);
        System.out.println("Olympic Sport: " + game3.olympicSport);
        System.out.println("World Record Time: " + game3.worldRecordTime + " sec");
        System.out.println("Age Group: " + game3.ageGroup);
        System.out.println("Individual Event: " + game3.individualEvent);
        System.out.println("Venue Capacity: " + game3.venueCapacity);
        System.out.println("Organizing Committee: " + game3.organizingCommittee);
        System.out.println("Multi Nation: " + game3.multiNation);
        System.out.println("Total Participations: " + game3.totalParticipations);
        System.out.println("Event Format: " + game3.eventFormat);
        System.out.println("Qualification Rounds: " + game3.qualificationRounds);
        System.out.println("Prize Money: " + game3.prizeMoney);
        System.out.println("Equipment Required: " + game3.equipmentRequired);
        System.out.println("Para Sport: " + game3.paraSport);
        System.out.println("Total Athletes: " + game3.totalAthletes);
        System.out.println("Event Duration: " + game3.eventDuration);
        System.out.println("Live Broadcast: " + game3.liveBroadcast);
        System.out.println("TV Viewership: " + game3.tvViewership);
        System.out.println("Record Holder: " + game3.recordHolder);
        System.out.println("World Championship: " + game3.worldChampionship);
        System.out.println("Peak Attendance: " + game3.peakAttendance);
        System.out.println("-----------------------------");
        
        NationalGames game4 = new NationalGames();
        
        game4.gameId = 2004;
        game4.gameTitle = "Indian Super League";
        game4.sportCategory = "Football";
        game4.teamSport = true;
        game4.primaryNation = "India";
        game4.totalMedals = 210;
        game4.governingBody = "All India Football Federation (AIFF)";
        game4.olympicSport = true;
        game4.worldRecordTime = 90.00;
        game4.ageGroup = "Senior";
        game4.individualEvent = false;
        game4.venueCapacity = 65000;
        game4.organizingCommittee = "Football Sports Development Ltd";
        game4.multiNation = false;
        game4.totalParticipations = 300;
        game4.eventFormat = "League + Playoffs";
        game4.qualificationRounds = true;
        game4.prizeMoney = 80000000.00;
        game4.equipmentRequired = "Balls, Jerseys, Studs";
        game4.paraSport = false;
        game4.totalAthletes = 300;
        game4.eventDuration = "7 Months";
        game4.liveBroadcast = true;
        game4.tvViewership = 350000000.0;
        game4.recordHolder = "ATK Mohun Bagan";
        game4.worldChampionship = false;
        game4.peakAttendance = "60K";
        
        System.out.println("Game ID: " + game4.gameId);
        System.out.println("Game Title: " + game4.gameTitle);
        System.out.println("Sport Category: " + game4.sportCategory);
        System.out.println("Team Sport: " + game4.teamSport);
        System.out.println("Primary Nation: " + game4.primaryNation);
        System.out.println("Total Medals: " + game4.totalMedals);
        System.out.println("Governing Body: " + game4.governingBody);
        System.out.println("Olympic Sport: " + game4.olympicSport);
        System.out.println("World Record Time: " + game4.worldRecordTime + " sec");
        System.out.println("Age Group: " + game4.ageGroup);
        System.out.println("Individual Event: " + game4.individualEvent);
        System.out.println("Venue Capacity: " + game4.venueCapacity);
        System.out.println("Organizing Committee: " + game4.organizingCommittee);
        System.out.println("Multi Nation: " + game4.multiNation);
        System.out.println("Total Participations: " + game4.totalParticipations);
        System.out.println("Event Format: " + game4.eventFormat);
        System.out.println("Qualification Rounds: " + game4.qualificationRounds);
      System.out.println("Equipment Required: " + game4.equipmentRequired);
        System.out.println("Para Sport: " + game4.paraSport);
        System.out.println("Total Athletes: " + game4.totalAthletes);
        System.out.println("Event Duration: " + game4.eventDuration);
        System.out.println("Live Broadcast: " + game4.liveBroadcast);
        System.out.println("TV Viewership: " + game4.tvViewership);
        System.out.println("Record Holder: " + game4.recordHolder);
        System.out.println("World Championship: " + game4.worldChampionship);
        System.out.println("Peak Attendance: " + game4.peakAttendance);
        System.out.println("-----------------------------");
	
		
		
		        NationalGames game5 = new NationalGames();
        
        game5.gameId = 2005;
        game5.gameTitle = "Indian Premier League";
        game5.sportCategory = "Cricket";
        game5.teamSport = true;
        game5.primaryNation = "India";
        game5.totalMedals = 342;
        game5.governingBody = "Board of Control for Cricket in India (BCCI)";
        game5.olympicSport = false;
        game5.worldRecordTime = 14.25;
        game5.ageGroup = "Senior";
        game5.individualEvent = false;
        game5.venueCapacity = 65000;
        game5.organizingCommittee = "IPG";
        game5.multiNation = true;
        game5.totalParticipations = 600;
        game5.eventFormat = "League + Playoffs";
        game5.qualificationRounds = true;
        game5.prizeMoney = 467000000.00;
        game5.equipmentRequired = "Bats, Balls, Pads, Helmets";
        game5.paraSport = false;
        game5.totalAthletes = 600;
        game5.eventDuration = "2.5 Months";
        game5.liveBroadcast = true;
        game5.tvViewership = 500000000.0;
        game5.recordHolder = "Mumbai Indians";
        game5.worldChampionship = false;
        game5.peakAttendance = "62K";
        
        System.out.println("Game ID: " + game5.gameId);
        System.out.println("Game Title: " + game5.gameTitle);
        System.out.println("Sport Category: " + game5.sportCategory);
        System.out.println("Team Sport: " + game5.teamSport);
        System.out.println("Primary Nation: " + game5.primaryNation);
        System.out.println("Total Medals: " + game5.totalMedals);
        System.out.println("Governing Body: " + game5.governingBody);
        System.out.println("Olympic Sport: " + game5.olympicSport);
        System.out.println("World Record Time: " + game5.worldRecordTime + " sec");
        System.out.println("Age Group: " + game5.ageGroup);
        System.out.println("Individual Event: " + game5.individualEvent);
        System.out.println("Venue Capacity: " + game5.venueCapacity);
        System.out.println("Organizing Committee: " + game5.organizingCommittee);
        System.out.println("Multi Nation: " + game5.multiNation);
        System.out.println("Total Participations: " + game5.totalParticipations);
        System.out.println("Event Format: " + game5.eventFormat);
        System.out.println("Qualification Rounds: " + game5.qualificationRounds);
       // System.out.println("Prize Money: $" + game5.prizeMoney);
        System.out.println("Equipment Required: " + game5.equipmentRequired);
        System.out.println("Para Sport: " + game5.paraSport);
        System.out.println("Total Athletes: " + game5.totalAthletes);
        System.out.println("Event Duration: " + game5.eventDuration);
        System.out.println("Live Broadcast: " + game5.liveBroadcast);
        System.out.println("TV Viewership: " + game5.tvViewership);
        System.out.println("Record Holder: " + game5.recordHolder);
        System.out.println("World Championship: " + game5.worldChampionship);
        System.out.println("Peak Attendance: " + game5.peakAttendance);
        System.out.println("-----------------------------");
        
        NationalGames game6 = new NationalGames();
        
        game6.gameId = 2006;
        game6.gameTitle = "Pro Wrestling League";
        game6.sportCategory = "Wrestling";
        game6.teamSport = true;
        game6.primaryNation = "India";
        game6.totalMedals = 78;
        game6.governingBody = "Wrestling Federation of India";
        game6.olympicSport = true;
        game6.worldRecordTime = 3.45;
        game6.ageGroup = "Senior";
        game6.individualEvent = false;
        game6.venueCapacity = 18000;
        game6.organizingCommittee = "JP Sports Pvt Ltd";
        game6.multiNation = true;
        game6.totalParticipations = 96;
        game6.eventFormat = "League + Finals";
        game6.qualificationRounds = true;
        game6.prizeMoney = 12000000.00;
        game6.equipmentRequired = "Mats, Singlets";
        game6.paraSport = false;
        game6.totalAthletes = 96;
        game6.eventDuration = "1.5 Months";
        game6.liveBroadcast = true;
        game6.tvViewership = 45000000.0;
        game6.recordHolder = "Delhi Sultans";
        game6.worldChampionship = false;
        game6.peakAttendance = "16K";
        
        System.out.println("Game ID: " + game6.gameId);
        System.out.println("Game Title: " + game6.gameTitle);
        System.out.println("Sport Category: " + game6.sportCategory);
        System.out.println("Team Sport: " + game6.teamSport);
        System.out.println("Primary Nation: " + game6.primaryNation);
        System.out.println("Total Medals: " + game6.totalMedals);
        System.out.println("Governing Body: " + game6.governingBody);
        System.out.println("Olympic Sport: " + game6.olympicSport);
        System.out.println("World Record Time: " + game6.worldRecordTime + " sec");
        System.out.println("Age Group: " + game6.ageGroup);
        System.out.println("Individual Event: " + game6.individualEvent);
        System.out.println("Venue Capacity: " + game6.venueCapacity);
        System.out.println("Organizing Committee: " + game6.organizingCommittee);
        System.out.println("Multi Nation: " + game6.multiNation);
        System.out.println("Total Participations: " + game6.totalParticipations);
        System.out.println("Event Format: " + game6.eventFormat);
        System.out.println("Qualification Rounds: " + game6.qualificationRounds);
     //   System.out.println("Prize Money: $" + game6.prizeMoney);
        System.out.println("Equipment Required: " + game6.equipmentRequired);
        System.out.println("Para Sport: " + game6.paraSport);
        System.out.println("Total Athletes: " + game6.totalAthletes);
        System.out.println("Event Duration: " + game6.eventDuration);
        System.out.println("Live Broadcast: " + game6.liveBroadcast);
        System.out.println("TV Viewership: " + game6.tvViewership);
        System.out.println("Record Holder: " + game6.recordHolder);
        System.out.println("World Championship: " + game6.worldChampionship);
        System.out.println("Peak Attendance: " + game6.peakAttendance);
        System.out.println("-----------------------------");

		
		        NationalGames game7 = new NationalGames();
        
        game7.gameId = 2007;
        game7.gameTitle = "Ultimate Table Tennis";
        game7.sportCategory = "Table Tennis";
        game7.teamSport = true;
        game7.primaryNation = "India";
        game7.totalMedals = 56;
        game7.governingBody = "Table Tennis Federation of India";
        game7.olympicSport = true;
        game7.worldRecordTime = 11.25;
        game7.ageGroup = "Senior";
        game7.individualEvent = false;
        game7.venueCapacity = 12000;
        game7.organizingCommittee = "11Sports";
        game7.multiNation = true;
        game7.totalParticipations = 72;
        game7.eventFormat = "League + Super Semis";
        game7.qualificationRounds = true;
        game7.prizeMoney = 2500000.00;
        game7.equipmentRequired = "Bats, Balls, Tables";
        game7.paraSport = false;
        game7.totalAthletes = 72;
        game7.eventDuration = "1 Month";
        game7.liveBroadcast = true;
        game7.tvViewership = 25000000.0;
        game7.recordHolder = "Dabang Chennai";
        game7.worldChampionship = false;
        game7.peakAttendance = "10K";
        
        System.out.println("Game ID: " + game7.gameId);
        System.out.println("Game Title: " + game7.gameTitle);
        System.out.println("Sport Category: " + game7.sportCategory);
        System.out.println("Team Sport: " + game7.teamSport);
        System.out.println("Primary Nation: " + game7.primaryNation);
        System.out.println("Total Medals: " + game7.totalMedals);
        System.out.println("Governing Body: " + game7.governingBody);
        System.out.println("Olympic Sport: " + game7.olympicSport);
        System.out.println("World Record Time: " + game7.worldRecordTime + " sec");
        System.out.println("Age Group: " + game7.ageGroup);
        System.out.println("Individual Event: " + game7.individualEvent);
        System.out.println("Venue Capacity: " + game7.venueCapacity);
        System.out.println("Organizing Committee: " + game7.organizingCommittee);
        System.out.println("Multi Nation: " + game7.multiNation);
        System.out.println("Total Participations: " + game7.totalParticipations);
        System.out.println("Event Format: " + game7.eventFormat);
        System.out.println("Qualification Rounds: " + game7.qualificationRounds);
        System.out.println("Prize Money: " + game7.prizeMoney);
        System.out.println("Equipment Required: " + game7.equipmentRequired);
        System.out.println("Para Sport: " + game7.paraSport);
        System.out.println("Total Athletes: " + game7.totalAthletes);
        System.out.println("Event Duration: " + game7.eventDuration);
        System.out.println("Live Broadcast: " + game7.liveBroadcast);
        System.out.println("TV Viewership: " + game7.tvViewership);
        System.out.println("Record Holder: " + game7.recordHolder);
        System.out.println("World Championship: " + game7.worldChampionship);
        System.out.println("Peak Attendance: " + game7.peakAttendance);
        System.out.println("-----------------------------");
        
        NationalGames game8 = new NationalGames();
        
        game8.gameId = 2008;
        game8.gameTitle = "Rugby Premier League";
        game8.sportCategory = "Rugby";
        game8.teamSport = true;
        game8.primaryNation = "India";
        game8.totalMedals = 112;
        game8.governingBody = "Rugby Football India";
        game8.olympicSport = true;
        game8.worldRecordTime = 4.15;
        game8.ageGroup = "Senior";
        game8.individualEvent = false;
        game8.venueCapacity = 28000;
        game8.organizingCommittee = "Rugby India";
        game8.multiNation = false;
        game8.totalParticipations = 168;
        game8.eventFormat = "League + Knockout";
        game8.qualificationRounds = true;
        game8.prizeMoney = 8000000.00;
        game8.equipmentRequired = "Balls, Jerseys, Mouthguards";
        game8.paraSport = false;
        game8.totalAthletes = 168;
        game8.eventDuration = "3 Months";
        game8.liveBroadcast = true;
        game8.tvViewership = 35000000.0;
        game8.recordHolder = "Mumbai Rugby Club";
        game8.worldChampionship = false;
        game8.peakAttendance = "25K";
        
        System.out.println("Game ID: " + game8.gameId);
        System.out.println("Game Title: " + game8.gameTitle);
        System.out.println("Sport Category: " + game8.sportCategory);
        System.out.println("Team Sport: " + game8.teamSport);
        System.out.println("Primary Nation: " + game8.primaryNation);
        System.out.println("Total Medals: " + game8.totalMedals);
        System.out.println("Governing Body: " + game8.governingBody);
        System.out.println("Olympic Sport: " + game8.olympicSport);
        System.out.println("World Record Time: " + game8.worldRecordTime + " sec");
        System.out.println("Age Group: " + game8.ageGroup);
        System.out.println("Individual Event: " + game8.individualEvent);
        System.out.println("Venue Capacity: " + game8.venueCapacity);
        System.out.println("Organizing Committee: " + game8.organizingCommittee);
        System.out.println("Multi Nation: " + game8.multiNation);
        System.out.println("Total Participations: " + game8.totalParticipations);
        System.out.println("Event Format: " + game8.eventFormat);
        System.out.println("Qualification Rounds: " + game8.qualificationRounds);
        System.out.println("Prize Money: " + game8.prizeMoney);
        System.out.println("Equipment Required: " + game8.equipmentRequired);
        System.out.println("Para Sport: " + game8.paraSport);
        System.out.println("Total Athletes: " + game8.totalAthletes);
        System.out.println("Event Duration: " + game8.eventDuration);
        System.out.println("Live Broadcast: " + game8.liveBroadcast);
        System.out.println("TV Viewership: " + game8.tvViewership);
        System.out.println("Record Holder: " + game8.recordHolder);
        System.out.println("World Championship: " + game8.worldChampionship);
        System.out.println("Peak Attendance: " + game8.peakAttendance);
        System.out.println("-----------------------------");

	        NationalGames game9 = new NationalGames();
        
        game9.gameId = 2009;
        game9.gameTitle = "Premier Volleyball League";
        game9.sportCategory = "Volleyball";
        game9.teamSport = true;
        game9.primaryNation = "India";
        game9.totalMedals = 98;
        game9.governingBody = "Volleyball Federation of India";
        game9.olympicSport = true;
        game9.worldRecordTime = 22.50;
        game9.ageGroup = "Senior";
        game9.individualEvent = false;
        game9.venueCapacity = 22000;
        game9.organizingCommittee = "Baseline Ventures";
        game9.multiNation = false;
        game9.totalParticipations = 144;
        game9.eventFormat = "League + Super 5s";
        game9.qualificationRounds = true;
        game9.prizeMoney = 18000000.00;
        game9.equipmentRequired = "Balls, Nets, Uniforms";
        game9.paraSport = false;
        game9.totalAthletes = 144;
        game9.eventDuration = "2 Months";
        game9.liveBroadcast = true;
        game9.tvViewership = 65000000.0;
        game9.recordHolder = "Ahmedabad Defenders";
        game9.worldChampionship = false;
        game9.peakAttendance = "20K";
        
        System.out.println("Game ID: " + game9.gameId);
        System.out.println("Game Title: " + game9.gameTitle);
        System.out.println("Sport Category: " + game9.sportCategory);
        System.out.println("Team Sport: " + game9.teamSport);
        System.out.println("Primary Nation: " + game9.primaryNation);
        System.out.println("Total Medals: " + game9.totalMedals);
        System.out.println("Governing Body: " + game9.governingBody);
        System.out.println("Olympic Sport: " + game9.olympicSport);
        System.out.println("World Record Time: " + game9.worldRecordTime + " sec");
        System.out.println("Age Group: " + game9.ageGroup);
        System.out.println("Individual Event: " + game9.individualEvent);
        System.out.println("Venue Capacity: " + game9.venueCapacity);
        System.out.println("Organizing Committee: " + game9.organizingCommittee);
        System.out.println("Multi Nation: " + game9.multiNation);
        System.out.println("Total Participations: " + game9.totalParticipations);
        
        NationalGames game10 = new NationalGames();
        
        game10.gameId = 2010;
        game10.gameTitle = "Super Major League Chess";
        game10.sportCategory = "Chess";
        game10.teamSport = true;
        game10.primaryNation = "India";
        game10.totalMedals = 45;
        game10.governingBody = "All India Chess Federation";
        game10.olympicSport = false;
        game10.worldRecordTime = 180.00;
        game10.ageGroup = "Senior";
        game10.individualEvent = false;
        game10.venueCapacity = 8000;
        game10.organizingCommittee = "Chess Super League Pvt Ltd";
        game10.multiNation = true;
        game10.totalParticipations = 90;
        game10.eventFormat = "League + Finals";
        game10.qualificationRounds = true;
        game10.prizeMoney = 5000000.00;
        game10.equipmentRequired = "Chess Boards, Clocks, Pieces";
        game10.paraSport = false;
        game10.totalAthletes = 90;
        game10.eventDuration = "1 Month";
        game10.liveBroadcast = true;
        game10.tvViewership = 12000000.0;
        game10.recordHolder = "Chennai Grandmasters";
        game10.worldChampionship = false;
        game10.peakAttendance = "7K";
        
        System.out.println("Game ID: " + game10.gameId);
        System.out.println("Game Title: " + game10.gameTitle);
        System.out.println("Sport Category: " + game10.sportCategory);
        System.out.println("Team Sport: " + game10.teamSport);
        System.out.println("Primary Nation: " + game10.primaryNation);
        System.out.println("Total Medals: " + game10.totalMedals);
        System.out.println("Governing Body: " + game10.governingBody);
        System.out.println("Olympic Sport: " + game10.olympicSport);
        System.out.println("World Record Time: " + game10.worldRecordTime + " sec");
        System.out.println("Age Group: " + game10.ageGroup);
        System.out.println("Individual Event: " + game10.individualEvent);
        System.out.println("Venue Capacity: " + game10.venueCapacity);
        System.out.println("Organizing Committee: " + game10.organizingCommittee);
        System.out.println("Multi Nation: " + game10.multiNation);
        System.out.println("Total Participations: " + game10.totalParticipations);
	
		
		        NationalGames game11 = new NationalGames();
        
        game11.gameId = 2011;
        game11.gameTitle = "Indian Street Premier League";
        game11.sportCategory = "Cricket";
        game11.teamSport = true;
        game11.primaryNation = "India";
        game11.totalMedals = 120;
        game11.governingBody = "Street Cricket India";
        game11.olympicSport = false;
        game11.worldRecordTime = 12.30;
        game11.ageGroup = "Senior";
        game11.individualEvent = false;
        game11.venueCapacity = 15000;
        game11.organizingCommittee = "Kishan Kumar";
        game11.multiNation = false;
        game11.totalParticipations = 180;
        game11.eventFormat = "League + Finals";
        game11.qualificationRounds = true;
        game11.prizeMoney = 5000000.00;
        game11.equipmentRequired = "Tennis Balls, Plastic Bats";
        game11.paraSport = false;
        game11.totalAthletes = 180;
        game11.eventDuration = "1 Month";
        game11.liveBroadcast = true;
        game11.tvViewership = 30000000.0;
        game11.recordHolder = "Mumbai Champions";
        game11.worldChampionship = false;
        game11.peakAttendance = "14K";
        
        System.out.println("Game ID: " + game11.gameId);
        System.out.println("Game Title: " + game11.gameTitle);
        System.out.println("Sport Category: " + game11.sportCategory);
        System.out.println("Team Sport: " + game11.teamSport);
        System.out.println("Primary Nation: " + game11.primaryNation);
        System.out.println("Total Medals: " + game11.totalMedals);
        System.out.println("Governing Body: " + game11.governingBody);
        System.out.println("Olympic Sport: " + game11.olympicSport);
        System.out.println("World Record Time: " + game11.worldRecordTime + " sec");
        System.out.println("Age Group: " + game11.ageGroup);
        System.out.println("Individual Event: " + game11.individualEvent);
        System.out.println("Venue Capacity: " + game11.venueCapacity);
        System.out.println("Organizing Committee: " + game11.organizingCommittee);
        System.out.println("Multi Nation: " + game11.multiNation);
        System.out.println("Total Participations: " + game11.totalParticipations);
        
        NationalGames game12 = new NationalGames();
        
        game12.gameId = 2012;
        game12.gameTitle = "3x3 Basketball India League";
        game12.sportCategory = "Basketball";
        game12.teamSport = true;
        game12.primaryNation = "India";
        game12.totalMedals = 84;
        game12.governingBody = "Basketball Federation of India";
        game12.olympicSport = true;
        game12.worldRecordTime = 10.15;
        game12.ageGroup = "Senior";
        game12.individualEvent = false;
        game12.venueCapacity = 10000;
        game12.organizingCommittee = "3x3 India Sports";
        game12.multiNation = true;
        game12.totalParticipations = 120;
        game12.eventFormat = "Pool + Knockout";
        game12.qualificationRounds = true;
        game12.prizeMoney = 3000000.00;
        game12.equipmentRequired = "Basketballs, Hoops";
        game12.paraSport = false;
        game12.totalAthletes = 120;
        game12.eventDuration = "3 Weeks";
        game12.liveBroadcast = true;
        game12.tvViewership = 18000000.0;
        game12.recordHolder = "Delhi 3x3 Kings";
        game12.worldChampionship = false;
        game12.peakAttendance = "9K";
        
        System.out.println("Game ID: " + game12.gameId);
        System.out.println("Game Title: " + game12.gameTitle);
        System.out.println("Sport Category: " + game12.sportCategory);
        System.out.println("Team Sport: " + game12.teamSport);
        System.out.println("Primary Nation: " + game12.primaryNation);
        System.out.println("Total Medals: " + game12.totalMedals);
        System.out.println("Governing Body: " + game12.governingBody);
        System.out.println("Olympic Sport: " + game12.olympicSport);
        System.out.println("World Record Time: " + game12.worldRecordTime + " sec");
        System.out.println("Age Group: " + game12.ageGroup);
        System.out.println("Individual Event: " + game12.individualEvent);
        System.out.println("Venue Capacity: " + game12.venueCapacity);
        System.out.println("Organizing Committee: " + game12.organizingCommittee);
        System.out.println("Multi Nation: " + game12.multiNation);
        System.out.println("Total Participations: " + game12.totalParticipations);
        
        NationalGames game13 = new NationalGames();
        
        game13.gameId = 2013;
        game13.gameTitle = "Indian Futsal League";
        game13.sportCategory = "Futsal";
        game13.teamSport = true;
        game13.primaryNation = "India";
        game13.totalMedals = 96;
        game13.governingBody = "All India Football Federation";
        game13.olympicSport = false;
        game13.worldRecordTime = 24.45;
        game13.ageGroup = "Senior";
        game13.individualEvent = false;
        game13.venueCapacity = 8000;
        game13.organizingCommittee = "Futsal India";
        game13.multiNation = false;
        game13.totalParticipations = 144;
        game13.eventFormat = "League + Semis";
        game13.qualificationRounds = true;
        game13.prizeMoney = 2500000.00;
        game13.equipmentRequired = "Futsal Balls, Goalie Gear";
        game13.paraSport = false;
        game13.totalAthletes = 144;
        game13.eventDuration = "2 Months";
        game13.liveBroadcast = true;
        game13.tvViewership = 22000000.0;
        game13.recordHolder = "Bengaluru Futsal FC";
        game13.worldChampionship = false;
        game13.peakAttendance = "7K";
        
        System.out.println("Game ID: " + game13.gameId);
        System.out.println("Game Title: " + game13.gameTitle);
        System.out.println("Sport Category: " + game13.sportCategory);
        System.out.println("Team Sport: " + game13.teamSport);
        System.out.println("Primary Nation: " + game13.primaryNation);
        System.out.println("Total Medals: " + game13.totalMedals);
        System.out.println("Governing Body: " + game13.governingBody);
        System.out.println("Olympic Sport: " + game13.olympicSport);
        System.out.println("World Record Time: " + game13.worldRecordTime + " sec");
        System.out.println("Age Group: " + game13.ageGroup);
        System.out.println("Individual Event: " + game13.individualEvent);
        System.out.println("Venue Capacity: " + game13.venueCapacity);
        System.out.println("Organizing Committee: " + game13.organizingCommittee);
        System.out.println("Multi Nation: " + game13.multiNation);
        System.out.println("Total Participations: " + game13.totalParticipations);
        System.out.println("-----------------------------");


        NationalGames game14 = new NationalGames();
        
        game14.gameId = 2014;
        game14.gameTitle = "Kho Kho World League";
        game14.sportCategory = "Kho Kho";
        game14.teamSport = true;
        game14.primaryNation = "India";
        game14.totalMedals = 76;
        game14.governingBody = "Kho Kho Federation of India";
        game14.olympicSport = false;
        game14.worldRecordTime = 8.45;
        game14.ageGroup = "Senior";
        game14.individualEvent = false;
        game14.venueCapacity = 12000;
        game14.organizingCommittee = "Kho Kho India Pvt Ltd";
        game14.multiNation = true;
        game14.totalParticipations = 108;
        game14.eventFormat = "League + Finals";
        game14.qualificationRounds = true;
        game14.prizeMoney = 4000000.00;
        game14.equipmentRequired = "Measuring Poles, Poles";
        game14.paraSport = false;
        game14.totalAthletes = 108;
        game14.eventDuration = "1.5 Months";
        game14.liveBroadcast = true;
        game14.tvViewership = 15000000.0;
        game14.recordHolder = "Odisha Warriors";
        game14.worldChampionship = false;
        game14.peakAttendance = "11K";
        
        System.out.println("Game ID: " + game14.gameId);
        System.out.println("Game Title: " + game14.gameTitle);
        System.out.println("Sport Category: " + game14.sportCategory);
        System.out.println("Team Sport: " + game14.teamSport);
        System.out.println("Primary Nation: " + game14.primaryNation);
        System.out.println("Total Medals: " + game14.totalMedals);
        System.out.println("Governing Body: " + game14.governingBody);
        System.out.println("Olympic Sport: " + game14.olympicSport);
        System.out.println("World Record Time: " + game14.worldRecordTime + " sec");
        System.out.println("Age Group: " + game14.ageGroup);
        System.out.println("Individual Event: " + game14.individualEvent);
        System.out.println("Venue Capacity: " + game14.venueCapacity);
        System.out.println("Organizing Committee: " + game14.organizingCommittee);
        System.out.println("Multi Nation: " + game14.multiNation);
        System.out.println("Total Participations: " + game14.totalParticipations);
        
        NationalGames game15 = new NationalGames();
        
        game15.gameId = 2015;
        game15.gameTitle = "Indian Squash Premier League";
        game15.sportCategory = "Squash";
        game15.teamSport = true;
        game15.primaryNation = "India";
        game15.totalMedals = 64;
        game15.governingBody = "Squash Rackets Federation of India";
        game15.olympicSport = false;
        game15.worldRecordTime = 18.30;
        game15.ageGroup = "Senior";
        game15.individualEvent = false;
        game15.venueCapacity = 6000;
        game15.organizingCommittee = "Squash India";
        game15.multiNation = true;
        game15.totalParticipations = 80;
        game15.eventFormat = "League + Playoffs";
        game15.qualificationRounds = true;
        game15.prizeMoney = 3000000.00;
        game15.equipmentRequired = "Rackets, Balls, Glasses";
        game15.paraSport = false;
        game15.totalAthletes = 80;
        game15.eventDuration = "3 Weeks";
        game15.liveBroadcast = true;
        game15.tvViewership = 8000000.0;
        game15.recordHolder = "Mumbai Squash Kings";
        game15.worldChampionship = false;
        game15.peakAttendance = "5K";
        
        System.out.println("Game ID: " + game15.gameId);
        System.out.println("Game Title: " + game15.gameTitle);
        System.out.println("Sport Category: " + game15.sportCategory);
        System.out.println("Team Sport: " + game15.teamSport);
        System.out.println("Primary Nation: " + game15.primaryNation);
        System.out.println("Total Medals: " + game15.totalMedals);
        System.out.println("Governing Body: " + game15.governingBody);
        System.out.println("Olympic Sport: " + game15.olympicSport);
        System.out.println("World Record Time: " + game15.worldRecordTime + " sec");
        System.out.println("Age Group: " + game15.ageGroup);
        System.out.println("Individual Event: " + game15.individualEvent);
        System.out.println("Venue Capacity: " + game15.venueCapacity);
        System.out.println("Organizing Committee: " + game15.organizingCommittee);
        System.out.println("Multi Nation: " + game15.multiNation);
        System.out.println("Total Participations: " + game15.totalParticipations);
        
        NationalGames game16 = new NationalGames();
        
        game16.gameId = 2016;
        game16.gameTitle = "Box Cricket Premier League";
        game16.sportCategory = "Cricket";
        game16.teamSport = true;
        game16.primaryNation = "India";
        game16.totalMedals = 132;
        game16.governingBody = "Box Cricket Federation India";
        game16.olympicSport = false;
        game16.worldRecordTime = 6.20;
        game16.ageGroup = "Senior";
        game16.individualEvent = false;
        game16.venueCapacity = 8000;
        game16.organizingCommittee = "Box Cricket India";
        game16.multiNation = false;
        game16.totalParticipations = 200;
        game16.eventFormat = "League + Knockout";
        game16.qualificationRounds = true;
        game16.prizeMoney = 2000000.00;
        game16.equipmentRequired = "Box Balls, Bats, Wickets";
        game16.paraSport = false;
        game16.totalAthletes = 200;
        game16.eventDuration = "1 Month";
        game16.liveBroadcast = true;
        game16.tvViewership = 25000000.0;
        game16.recordHolder = "Hyderabad Box Tigers";
        game16.worldChampionship = false;
        game16.peakAttendance = "7K";
        
        System.out.println("Game ID: " + game16.gameId);
        System.out.println("Game Title: " + game16.gameTitle);
        System.out.println("Sport Category: " + game16.sportCategory);
        System.out.println("Team Sport: " + game16.teamSport);
        System.out.println("Primary Nation: " + game16.primaryNation);
        System.out.println("Total Medals: " + game16.totalMedals);
        System.out.println("Governing Body: " + game16.governingBody);
        System.out.println("Olympic Sport: " + game16.olympicSport);
        System.out.println("World Record Time: " + game16.worldRecordTime + " sec");
        System.out.println("Age Group: " + game16.ageGroup);
        System.out.println("Individual Event: " + game16.individualEvent);
        System.out.println("Venue Capacity: " + game16.venueCapacity);
        System.out.println("Organizing Committee: " + game16.organizingCommittee);
        System.out.println("Multi Nation: " + game16.multiNation);
        System.out.println("Total Participations: " + game16.totalParticipations);
        System.out.println("-----------------------------");


        NationalGames game17 = new NationalGames();
        
        game17.gameId = 2017;
        game17.gameTitle = "Indian Roller Sports League";
        game17.sportCategory = "Roller Sports";
        game17.teamSport = true;
        game17.primaryNation = "India";
        game17.totalMedals = 88;
        game17.governingBody = "Roller Sports Federation of India";
        game17.olympicSport = false;
        game17.worldRecordTime = 32.15;
        game17.ageGroup = "Senior";
        game17.individualEvent = false;
        game17.venueCapacity = 10000;
        game17.organizingCommittee = "Roller India Pvt Ltd";
        game17.multiNation = true;
        game17.totalParticipations = 120;
        game17.eventFormat = "League + Finals";
        game17.qualificationRounds = true;
        game17.prizeMoney = 2500000.00;
        game17.equipmentRequired = "Inline Skates, Helmets, Cones";
        game17.paraSport = false;
        game17.totalAthletes = 120;
        game17.eventDuration = "1 Month";
        game17.liveBroadcast = true;
        game17.tvViewership = 12000000.0;
        game17.recordHolder = "Mumbai Rollers";
        game17.worldChampionship = false;
        game17.peakAttendance = "9K";
        
        System.out.println("Game ID: " + game17.gameId);
        System.out.println("Game Title: " + game17.gameTitle);
        System.out.println("Sport Category: " + game17.sportCategory);
        System.out.println("Team Sport: " + game17.teamSport);
        System.out.println("Primary Nation: " + game17.primaryNation);
        System.out.println("Total Medals: " + game17.totalMedals);
        System.out.println("Governing Body: " + game17.governingBody);
        System.out.println("Olympic Sport: " + game17.olympicSport);
        System.out.println("World Record Time: " + game17.worldRecordTime + " sec");
        System.out.println("Age Group: " + game17.ageGroup);
        System.out.println("Individual Event: " + game17.individualEvent);
        System.out.println("Venue Capacity: " + game17.venueCapacity);
        System.out.println("Organizing Committee: " + game17.organizingCommittee);
        System.out.println("Multi Nation: " + game17.multiNation);
        System.out.println("Total Participations: " + game17.totalParticipations);
        
        NationalGames game18 = new NationalGames();
        
        game18.gameId = 2018;
        game18.gameTitle = "Kudo Martial Arts League";
        game18.sportCategory = "Martial Arts";
        game18.teamSport = true;
        game18.primaryNation = "India";
        game18.totalMedals = 72;
        game18.governingBody = "Kudo Federation of India";
        game18.olympicSport = false;
        game18.worldRecordTime = 2.55;
        game18.ageGroup = "Senior";
        game18.individualEvent = false;
        game18.venueCapacity = 8000;
        game18.organizingCommittee = "Kudo India";
        game18.multiNation = false;
        game18.totalParticipations = 96;
        game18.eventFormat = "League + Semis";
        game18.qualificationRounds = true;
        game18.prizeMoney = 2000000.00;
        game18.equipmentRequired = "Gloves, Headgear, Mats";
        game18.paraSport = false;
        game18.totalAthletes = 96;
        game18.eventDuration = "3 Weeks";
        game18.liveBroadcast = true;
        game18.tvViewership = 8000000.0;
        game18.recordHolder = "Delhi Kudo Warriors";
        game18.worldChampionship = false;
        game18.peakAttendance = "7K";
        
        System.out.println("Game ID: " + game18.gameId);
        System.out.println("Game Title: " + game18.gameTitle);
        System.out.println("Sport Category: " + game18.sportCategory);
        System.out.println("Team Sport: " + game18.teamSport);
        System.out.println("Primary Nation: " + game18.primaryNation);
        System.out.println("Total Medals: " + game18.totalMedals);
        System.out.println("Governing Body: " + game18.governingBody);
        System.out.println("Olympic Sport: " + game18.olympicSport);
        System.out.println("World Record Time: " + game18.worldRecordTime + " sec");
        System.out.println("Age Group: " + game18.ageGroup);
        System.out.println("Individual Event: " + game18.individualEvent);
        System.out.println("Venue Capacity: " + game18.venueCapacity);
        System.out.println("Organizing Committee: " + game18.organizingCommittee);
        System.out.println("Multi Nation: " + game18.multiNation);
        System.out.println("Total Participations: " + game18.totalParticipations);
        
        NationalGames game19 = new NationalGames();
        
        game19.gameId = 2019;
        game19.gameTitle = "Indian Padel League";
        game19.sportCategory = "Padel";
        game19.teamSport = true;
        game19.primaryNation = "India";
        game19.totalMedals = 54;
        game19.governingBody = "Padel Federation of India";
        game19.olympicSport = false;
        game19.worldRecordTime = 15.40;
        game19.ageGroup = "Senior";
        game19.individualEvent = false;
        game19.venueCapacity = 5000;
        game19.organizingCommittee = "Padel India Sports";
        game19.multiNation = true;
        game19.totalParticipations = 72;
        game19.eventFormat = "League + Playoffs";
        game19.qualificationRounds = true;
        game19.prizeMoney = 1500000.00;
        game19.equipmentRequired = "Padel Rackets, Balls";
        game19.paraSport = false;
        game19.totalAthletes = 72;
        game19.eventDuration = "3 Weeks";
        game19.liveBroadcast = true;
        game19.tvViewership = 5000000.0;
        game19.recordHolder = "Bangalore Padel Masters";
        game19.worldChampionship = false;
        game19.peakAttendance = "4K";
        
        System.out.println("Game ID: " + game19.gameId);
        System.out.println("Game Title: " + game19.gameTitle);
        System.out.println("Sport Category: " + game19.sportCategory);
        System.out.println("Team Sport: " + game19.teamSport);
        System.out.println("Primary Nation: " + game19.primaryNation);
        System.out.println("Total Medals: " + game19.totalMedals);
        System.out.println("Governing Body: " + game19.governingBody);
        System.out.println("Olympic Sport: " + game19.olympicSport);
        System.out.println("World Record Time: " + game19.worldRecordTime + " sec");
        System.out.println("Age Group: " + game19.ageGroup);
        System.out.println("Individual Event: " + game19.individualEvent);
        System.out.println("Venue Capacity: " + game19.venueCapacity);
        System.out.println("Organizing Committee: " + game19.organizingCommittee);
        System.out.println("Multi Nation: " + game19.multiNation);
        System.out.println("Total Participations: " + game19.totalParticipations);
        System.out.println("-----------------------------");


        NationalGames game20 = new NationalGames();
        
        game20.gameId = 2020;
        game20.gameTitle = "Indian Archery Premier League";
        game20.sportCategory = "Archery";
        game20.teamSport = true;
        game20.primaryNation = "India";
        game20.totalMedals = 62;
        game20.governingBody = "Archery Association of India";
        game20.olympicSport = true;
        game20.worldRecordTime = 27.80;
        game20.ageGroup = "Senior";
        game20.individualEvent = false;
        game20.venueCapacity = 7000;
        game20.organizingCommittee = "Archery India Sports";
        game20.multiNation = true;
        game20.totalParticipations = 84;
        game20.eventFormat = "League + Finals";
        game20.qualificationRounds = true;
        game20.prizeMoney = 2000000.00;
        game20.equipmentRequired = "Bows, Arrows, Targets";
        game20.paraSport = false;
        game20.totalAthletes = 84;
        game20.eventDuration = "3 Weeks";
        game20.liveBroadcast = true;
        game20.tvViewership = 6000000.0;
        game20.recordHolder = "Delhi Archers";
        game20.worldChampionship = false;
        game20.peakAttendance = "6K";
        
        System.out.println("Game ID: " + game20.gameId);
        System.out.println("Game Title: " + game20.gameTitle);
        System.out.println("Sport Category: " + game20.sportCategory);
        System.out.println("Team Sport: " + game20.teamSport);
        System.out.println("Primary Nation: " + game20.primaryNation);
        System.out.println("Total Medals: " + game20.totalMedals);
        System.out.println("Governing Body: " + game20.governingBody);
        System.out.println("Olympic Sport: " + game20.olympicSport);
        System.out.println("World Record Time: " + game20.worldRecordTime + " sec");
        System.out.println("Age Group: " + game20.ageGroup);
        System.out.println("Individual Event: " + game20.individualEvent);
        System.out.println("Venue Capacity: " + game20.venueCapacity);
        System.out.println("Organizing Committee: " + game20.organizingCommittee);
        System.out.println("Multi Nation: " + game20.multiNation);
        System.out.println("Total Participations: " + game20.totalParticipations);
        System.out.println("-----------------------------");

	
		
    }
}
