public class PlayGroundDetailsExecutor {

    public static void main(String[] ground) {
	
        PlayGroundDetails playground1 = new PlayGroundDetails();
        playground1.setPlaygroundId(1);
        System.out.println("Playground ID: " + playground1.getPlaygroundId());
        playground1.setPlaygroundName("Cubbon Park Playground");
        System.out.println("Name: " + playground1.getPlaygroundName());
        playground1.setLocation("Bengaluru, Karnataka");
        System.out.println("Location: " + playground1.getLocation());
        playground1.setSurfaceType("Sand + Grass");
        System.out.println("Surface: " + playground1.getSurfaceType());
        playground1.setAreaSqFt(15000);
        System.out.println("Area: " + playground1.getAreaSqFt() + " sq ft");
        playground1.setFacilities("Slides, Swings, Seesaw");
        System.out.println("Facilities: " + playground1.getFacilities());
        playground1.setTiming("6AM-8PM");
        System.out.println("Timing: " + playground1.getTiming());
        System.out.println();

        PlayGroundDetails playground2 = new PlayGroundDetails();
        playground2.setPlaygroundId(2);
        System.out.println("Playground ID: " + playground2.getPlaygroundId());
        playground2.setPlaygroundName("Lalbagh Playground");
        System.out.println("Name: " + playground2.getPlaygroundName());
        playground2.setLocation("South Bengaluru");
        System.out.println("Location: " + playground2.getLocation());
        playground2.setSurfaceType("Rubber Mats");
        System.out.println("Surface: " + playground2.getSurfaceType());
        playground2.setAreaSqFt(12000);
        System.out.println("Area: " + playground2.getAreaSqFt() + " sq ft");
        playground2.setFacilities("Merry-go-round, Climbing net");
        System.out.println("Facilities: " + playground2.getFacilities());
        playground2.setTiming("5AM-7PM");
        System.out.println("Timing: " + playground2.getTiming());
        System.out.println();

        PlayGroundDetails playground3 = new PlayGroundDetails();
        playground3.setPlaygroundId(3);
        System.out.println("Playground ID: " + playground3.getPlaygroundId());
        playground3.setPlaygroundName("JV Park Playground");
        System.out.println("Name: " + playground3.getPlaygroundName());
        playground3.setLocation("Koramangala, Bengaluru");
        System.out.println("Location: " + playground3.getLocation());
        playground3.setSurfaceType("Turf + Sand");
        System.out.println("Surface: " + playground3.getSurfaceType());
        playground3.setAreaSqFt(8000);
        System.out.println("Area: " + playground3.getAreaSqFt() + " sq ft");
        playground3.setFacilities("Multi-play station, Swing");
        System.out.println("Facilities: " + playground3.getFacilities());
        playground3.setTiming("6AM-9PM");
        System.out.println("Timing: " + playground3.getTiming());
        System.out.println();

        PlayGroundDetails playground4 = new PlayGroundDetails();
        playground4.setPlaygroundId(4);
        System.out.println("Playground ID: " + playground4.getPlaygroundId());
        playground4.setPlaygroundName("NCC Park Playground");
        System.out.println("Name: " + playground4.getPlaygroundName());
        playground4.setLocation("Jayanagar, Bengaluru");
        System.out.println("Location: " + playground4.getLocation());
        playground4.setSurfaceType("Grass");
        System.out.println("Surface: " + playground4.getSurfaceType());
        playground4.setAreaSqFt(10000);
        System.out.println("Area: " + playground4.getAreaSqFt() + " sq ft");
        playground4.setFacilities("Slide combo, Monkey bars");
        System.out.println("Facilities: " + playground4.getFacilities());
        playground4.setTiming("5AM-8PM");
        System.out.println("Timing: " + playground4.getTiming());
        System.out.println();

        PlayGroundDetails playground5 = new PlayGroundDetails();
        playground5.setPlaygroundId(5);
        System.out.println("Playground ID: " + playground5.getPlaygroundId());
        playground5.setPlaygroundName("MG Road Park");
        System.out.println("Name: " + playground5.getPlaygroundName());
        playground5.setLocation("MG Road, Bengaluru");
        System.out.println("Location: " + playground5.getLocation());
        playground5.setSurfaceType("Sand");
        System.out.println("Surface: " + playground5.getSurfaceType());
        playground5.setAreaSqFt(6000);
        System.out.println("Area: " + playground5.getAreaSqFt() + " sq ft");
        playground5.setFacilities("Seesaw, Spring rider");
        System.out.println("Facilities: " + playground5.getFacilities());
        playground5.setTiming("7AM-7PM");
        System.out.println("Timing: " + playground5.getTiming());
        System.out.println();
		
		PlayGroundDetails playground6 = new PlayGroundDetails();
        playground6.setPlaygroundId(6);
        System.out.println("Playground ID: " + playground6.getPlaygroundId());
        playground6.setPlaygroundName("Defence Colony Park");
        System.out.println("Name: " + playground6.getPlaygroundName());
        playground6.setLocation("Indiranagar, Bengaluru");
        System.out.println("Location: " + playground6.getLocation());
        playground6.setSurfaceType("Sand + Rubber");
        System.out.println("Surface: " + playground6.getSurfaceType());
        playground6.setAreaSqFt(7500);
        System.out.println("Area: " + playground6.getAreaSqFt() + " sq ft");
        playground6.setFacilities("Slides, Swings, Climber");
        System.out.println("Facilities: " + playground6.getFacilities());
        playground6.setTiming("8AM-12PM, 3:30PM-7PM");
        System.out.println("Timing: " + playground6.getTiming());
        System.out.println();

        PlayGroundDetails playground7 = new PlayGroundDetails();
        playground7.setPlaygroundId(7);
        System.out.println("Playground ID: " + playground7.getPlaygroundId());
        playground7.setPlaygroundName("Nandanavana Park");
        System.out.println("Name: " + playground7.getPlaygroundName());
        playground7.setLocation("Jayanagar 4th T Block");
        System.out.println("Location: " + playground7.getLocation());
        playground7.setSurfaceType("Grass + Mats");
        System.out.println("Surface: " + playground7.getSurfaceType());
        playground7.setAreaSqFt(9000);
        System.out.println("Area: " + playground7.getAreaSqFt() + " sq ft");
        playground7.setFacilities("Multi-play, Seesaw, Swing");
        System.out.println("Facilities: " + playground7.getFacilities());
        playground7.setTiming("4PM-8PM");
        System.out.println("Timing: " + playground7.getTiming());
        System.out.println();

        PlayGroundDetails playground8 = new PlayGroundDetails();
        playground8.setPlaygroundId(8);
        System.out.println("Playground ID: " + playground8.getPlaygroundId());
        playground8.setPlaygroundName("Fun World Playground");
        System.out.println("Name: " + playground8.getPlaygroundName());
        playground8.setLocation("Jayamahal Main Road");
        System.out.println("Location: " + playground8.getLocation());
        playground8.setSurfaceType("Rubber Flooring");
        System.out.println("Surface: " + playground8.getSurfaceType());
        playground8.setAreaSqFt(20000);
        System.out.println("Area: " + playground8.getAreaSqFt() + " sq ft");
        playground8.setFacilities("Thrill rides, Slides, Swings");
        System.out.println("Facilities: " + playground8.getFacilities());
        playground8.setTiming("10AM-6PM");
        System.out.println("Timing: " + playground8.getTiming());
        System.out.println();

        PlayGroundDetails playground9 = new PlayGroundDetails();
        playground9.setPlaygroundId(9);
        System.out.println("Playground ID: " + playground9.getPlaygroundId());
        playground9.setPlaygroundName("Kuvempu Park");
        System.out.println("Name: " + playground9.getPlaygroundName());
        playground9.setLocation("BTM Layout 2nd Stage");
        System.out.println("Location: " + playground9.getLocation());
        playground9.setSurfaceType("Sand");
        System.out.println("Surface: " + playground9.getSurfaceType());
        playground9.setAreaSqFt(5000);
        System.out.println("Area: " + playground9.getAreaSqFt() + " sq ft");
        playground9.setFacilities("Slides, Climbers, Swings");
        System.out.println("Facilities: " + playground9.getFacilities());
        playground9.setTiming("5AM-9AM, 4PM-8PM");
        System.out.println("Timing: " + playground9.getTiming());
        System.out.println();

        PlayGroundDetails playground10 = new PlayGroundDetails();
        playground10.setPlaygroundId(10);
        System.out.println("Playground ID: " + playground10.getPlaygroundId());
        playground10.setPlaygroundName("Indira Gandhi Fountain Park");
        System.out.println("Name: " + playground10.getPlaygroundName());
        playground10.setLocation("Near RV College");
        System.out.println("Location: " + playground10.getLocation());
        playground10.setSurfaceType("Turf + Sand");
        System.out.println("Surface: " + playground10.getSurfaceType());
        playground10.setAreaSqFt(12000);
        System.out.println("Area: " + playground10.getAreaSqFt() + " sq ft");
        playground10.setFacilities("Scooter paths, Musical fountain");
        System.out.println("Facilities: " + playground10.getFacilities());
        playground10.setTiming("6AM-9PM");
        System.out.println("Timing: " + playground10.getTiming());
        System.out.println();

        PlayGroundDetails playground11 = new PlayGroundDetails();
        playground11.setPlaygroundId(11);
        System.out.println("Playground ID: " + playground11.getPlaygroundId());
        playground11.setPlaygroundName("KydzAdda Playground");
        System.out.println("Name: " + playground11.getPlaygroundName());
        playground11.setLocation("Banashankari, Bengaluru");
        System.out.println("Location: " + playground11.getLocation());
        playground11.setSurfaceType("Soft Mats");
        System.out.println("Surface: " + playground11.getSurfaceType());
        playground11.setAreaSqFt(4000);
        System.out.println("Area: " + playground11.getAreaSqFt() + " sq ft");
        playground11.setFacilities("Ball pit, Monkey gym, Slides");
        System.out.println("Facilities: " + playground11.getFacilities());
        playground11.setTiming("10AM-8PM");
        System.out.println("Timing: " + playground11.getTiming());
        System.out.println();

        PlayGroundDetails playground12 = new PlayGroundDetails();
        playground12.setPlaygroundId(12);
        System.out.println("Playground ID: " + playground12.getPlaygroundId());
        playground12.setPlaygroundName("Funky Monkeys");
        System.out.println("Name: " + playground12.getPlaygroundName());
        playground12.setLocation("MG Road Mall, Bengaluru");
        System.out.println("Location: " + playground12.getLocation());
        playground12.setSurfaceType("Foam Mats");
        System.out.println("Surface: " + playground12.getSurfaceType());
        playground12.setAreaSqFt(6000);
        System.out.println("Area: " + playground12.getAreaSqFt() + " sq ft");
        playground12.setFacilities("Trampoline, Climbing walls");
        System.out.println("Facilities: " + playground12.getFacilities());
        playground12.setTiming("10AM-10PM");
        System.out.println("Timing: " + playground12.getTiming());
        System.out.println();

        PlayGroundDetails playground13 = new PlayGroundDetails();
        playground13.setPlaygroundId(13);
        System.out.println("Playground ID: " + playground13.getPlaygroundId());
        playground13.setPlaygroundName("Tumble Town");
        System.out.println("Name: " + playground13.getPlaygroundName());
        playground13.setLocation("Banashankari, Bengaluru");
        System.out.println("Location: " + playground13.getLocation());
        playground13.setSurfaceType("Soft Play Mats");
        System.out.println("Surface: " + playground13.getSurfaceType());
        playground13.setAreaSqFt(3500);
        System.out.println("Area: " + playground13.getAreaSqFt() + " sq ft");
        playground13.setFacilities("Ball pools, Mini trampolines");
        System.out.println("Facilities: " + playground13.getFacilities());
        playground13.setTiming("10AM-8PM");
        System.out.println("Timing: " + playground13.getTiming());
        System.out.println();

        PlayGroundDetails playground14 = new PlayGroundDetails();
        playground14.setPlaygroundId(14);
        System.out.println("Playground ID: " + playground14.getPlaygroundId());
        playground14.setPlaygroundName("SkyJumper Trampoline Park");
        System.out.println("Name: " + playground14.getPlaygroundName());
        playground14.setLocation("Whitefield, Bengaluru");
        System.out.println("Location: " + playground14.getLocation());
        playground14.setSurfaceType("Trampoline Surface");
        System.out.println("Surface: " + playground14.getSurfaceType());
        playground14.setAreaSqFt(15000);
        System.out.println("Area: " + playground14.getAreaSqFt() + " sq ft");
        playground14.setFacilities("Trampolines, Dodgeball, Foam pit");
        System.out.println("Facilities: " + playground14.getFacilities());
        playground14.setTiming("11AM-10PM");
        System.out.println("Timing: " + playground14.getTiming());
        System.out.println();

        PlayGroundDetails playground15 = new PlayGroundDetails();
        playground15.setPlaygroundId(15);
        System.out.println("Playground ID: " + playground15.getPlaygroundId());
        playground15.setPlaygroundName("KidZania Playground");
        System.out.println("Name: " + playground15.getPlaygroundName());
        playground15.setLocation("VR Mall, Whitefield");
        System.out.println("Location: " + playground15.getLocation());
        playground15.setSurfaceType("Indoor Soft Mats");
        System.out.println("Surface: " + playground15.getSurfaceType());
        playground15.setAreaSqFt(8000);
        System.out.println("Area: " + playground15.getAreaSqFt() + " sq ft");
        playground15.setFacilities("Role-play zones, Mini city");
        System.out.println("Facilities: " + playground15.getFacilities());
        playground15.setTiming("10AM-7PM");
        System.out.println("Timing: " + playground15.getTiming());
        System.out.println();

        PlayGroundDetails playground16 = new PlayGroundDetails();
        playground16.setPlaygroundId(16);
        System.out.println("Playground ID: " + playground16.getPlaygroundId());
        playground16.setPlaygroundName("Fun Galaxy");
        System.out.println("Name: " + playground16.getPlaygroundName());
        playground16.setLocation("Electronic City, Bengaluru");
        System.out.println("Location: " + playground16.getLocation());
        playground16.setSurfaceType("Rubber Flooring");
        System.out.println("Surface: " + playground16.getSurfaceType());
        playground16.setAreaSqFt(7000);
        System.out.println("Area: " + playground16.getAreaSqFt() + " sq ft");
        playground16.setFacilities("Arcade games, Play structures");
        System.out.println("Facilities: " + playground16.getFacilities());
        playground16.setTiming("11AM-9PM");
        System.out.println("Timing: " + playground16.getTiming());
        System.out.println();

        PlayGroundDetails playground17 = new PlayGroundDetails();
        playground17.setPlaygroundId(17);
        System.out.println("Playground ID: " + playground17.getPlaygroundId());
        playground17.setPlaygroundName("Hop Bob Trampoline");
        System.out.println("Name: " + playground17.getPlaygroundName());
        playground17.setLocation("Akshayanagar, Bengaluru");
        System.out.println("Location: " + playground17.getLocation());
        playground17.setSurfaceType("Trampoline + Foam");
        System.out.println("Surface: " + playground17.getSurfaceType());
        playground17.setAreaSqFt(10000);
        System.out.println("Area: " + playground17.getAreaSqFt() + " sq ft");
        playground17.setFacilities("Trampolines, Ninja course");
        System.out.println("Facilities: " + playground17.getFacilities());
        playground17.setTiming("10AM-10PM");
        System.out.println("Timing: " + playground17.getTiming());
        System.out.println();
		
		PlayGroundDetails playground18 = new PlayGroundDetails();
        playground18.setPlaygroundId(18);
        System.out.println("Playground ID: " + playground18.getPlaygroundId());
        playground18.setPlaygroundName("Jumpin Bouncers");
        System.out.println("Name: " + playground18.getPlaygroundName());
        playground18.setLocation("Marathahalli, Bengaluru");
        System.out.println("Location: " + playground18.getLocation());
        playground18.setSurfaceType("Foam + Trampoline");
        System.out.println("Surface: " + playground18.getSurfaceType());
        playground18.setAreaSqFt(4500);
        System.out.println("Area: " + playground18.getAreaSqFt() + " sq ft");
        playground18.setFacilities("Bouncy castles, Ball pool");
        System.out.println("Facilities: " + playground18.getFacilities());
        playground18.setTiming("11AM-9PM");
        System.out.println("Timing: " + playground18.getTiming());
        System.out.println();

        PlayGroundDetails playground19 = new PlayGroundDetails();
        playground19.setPlaygroundId(19);
        System.out.println("Playground ID: " + playground19.getPlaygroundId());
        playground19.setPlaygroundName("Little Elly Play Area");
        System.out.println("Name: " + playground19.getPlaygroundName());
        playground19.setLocation("HSR Layout, Bengaluru");
        System.out.println("Location: " + playground19.getLocation());
        playground19.setSurfaceType("Soft Mats");
        System.out.println("Surface: " + playground19.getSurfaceType());
        playground19.setAreaSqFt(3000);
        System.out.println("Area: " + playground19.getAreaSqFt() + " sq ft");
        playground19.setFacilities("Toddler slides, Sensory play");
        System.out.println("Facilities: " + playground19.getFacilities());
        playground19.setTiming("9AM-7PM");
        System.out.println("Timing: " + playground19.getTiming());
        System.out.println();

        PlayGroundDetails playground20 = new PlayGroundDetails();
        playground20.setPlaygroundId(20);
        System.out.println("Playground ID: " + playground20.getPlaygroundId());
        playground20.setPlaygroundName("Infant Jesus Park");
        System.out.println("Name: " + playground20.getPlaygroundName());
        playground20.setLocation("Viveknagar, Bengaluru");
        System.out.println("Location: " + playground20.getLocation());
        playground20.setSurfaceType("Sand + Grass");
        System.out.println("Surface: " + playground20.getSurfaceType());
        playground20.setAreaSqFt(6500);
        System.out.println("Area: " + playground20.getAreaSqFt() + " sq ft");
        playground20.setFacilities("Swings, Seesaw, Climber");
        System.out.println("Facilities: " + playground20.getFacilities());
        playground20.setTiming("6AM-8PM");
        System.out.println("Timing: " + playground20.getTiming());
        System.out.println();

        PlayGroundDetails playground21 = new PlayGroundDetails();
        playground21.setPlaygroundId(21);
        System.out.println("Playground ID: " + playground21.getPlaygroundId());
        playground21.setPlaygroundName("Phoenix Marketcity Zone");
        System.out.println("Name: " + playground21.getPlaygroundName());
        playground21.setLocation("Whitefield, Bengaluru");
        System.out.println("Location: " + playground21.getLocation());
        playground21.setSurfaceType("Indoor Rubber");
        System.out.println("Surface: " + playground21.getSurfaceType());
        playground21.setAreaSqFt(5000);
        System.out.println("Area: " + playground21.getAreaSqFt() + " sq ft");
        playground21.setFacilities("Trampoline, Slides, Games");
        System.out.println("Facilities: " + playground21.getFacilities());
        playground21.setTiming("10AM-10PM");
        System.out.println("Timing: " + playground21.getTiming());
        System.out.println();

        PlayGroundDetails playground22 = new PlayGroundDetails();
        playground22.setPlaygroundId(22);
        System.out.println("Playground ID: " + playground22.getPlaygroundId());
        playground22.setPlaygroundName("Storm Coasters Park");
        System.out.println("Name: " + playground22.getPlaygroundName());
        playground22.setLocation("Yelahanka, Bengaluru");
        System.out.println("Location: " + playground22.getLocation());
        playground22.setSurfaceType("Asphalt + Mats");
        System.out.println("Surface: " + playground22.getSurfaceType());
        playground22.setAreaSqFt(18000);
        System.out.println("Area: " + playground22.getAreaSqFt() + " sq ft");
        playground22.setFacilities("Go-kart track, Bouncers");
        System.out.println("Facilities: " + playground22.getFacilities());
        playground22.setTiming("9AM-9PM");
        System.out.println("Timing: " + playground22.getTiming());
        System.out.println();

        PlayGroundDetails playground23 = new PlayGroundDetails();
        playground23.setPlaygroundId(23);
        System.out.println("Playground ID: " + playground23.getPlaygroundId());
        playground23.setPlaygroundName("Garden City Park");
        System.out.println("Name: " + playground23.getPlaygroundName());
        playground23.setLocation("Kammanahalli, Bengaluru");
        System.out.println("Location: " + playground23.getLocation());
        playground23.setSurfaceType("Turf");
        System.out.println("Surface: " + playground23.getSurfaceType());
        playground23.setAreaSqFt(8500);
        System.out.println("Area: " + playground23.getAreaSqFt() + " sq ft");
        playground23.setFacilities("Multi-play unit, Swings");
        System.out.println("Facilities: " + playground23.getFacilities());
        playground23.setTiming("5AM-9PM");
        System.out.println("Timing: " + playground23.getTiming());
        System.out.println();

        PlayGroundDetails playground24 = new PlayGroundDetails();
        playground24.setPlaygroundId(24);
        System.out.println("Playground ID: " + playground24.getPlaygroundId());
        playground24.setPlaygroundName("Playtopia Indoor");
        System.out.println("Name: " + playground24.getPlaygroundName());
        playground24.setLocation("Koramangala, Bengaluru");
        System.out.println("Location: " + playground24.getLocation());
        playground24.setSurfaceType("Foam Flooring");
        System.out.println("Surface: " + playground24.getSurfaceType());
        playground24.setAreaSqFt(4000);
        System.out.println("Area: " + playground24.getAreaSqFt() + " sq ft");
        playground24.setFacilities("Ball pit, Climbing walls");
        System.out.println("Facilities: " + playground24.getFacilities());
        playground24.setTiming("10AM-8PM");
        System.out.println("Timing: " + playground24.getTiming());
        System.out.println();

        PlayGroundDetails playground25 = new PlayGroundDetails();
        playground25.setPlaygroundId(25);
        System.out.println("Playground ID: " + playground25.getPlaygroundId());
        playground25.setPlaygroundName("BBMP Park Playground");
        System.out.println("Name: " + playground25.getPlaygroundName());
        playground25.setLocation("Malleshwaram, Bengaluru");
        System.out.println("Location: " + playground25.getLocation());
        playground25.setSurfaceType("Sand");
        System.out.println("Surface: " + playground25.getSurfaceType());
        playground25.setAreaSqFt(7000);
        System.out.println("Area: " + playground25.getAreaSqFt() + " sq ft");
        playground25.setFacilities("Slides, Seesaw, Swing");
        System.out.println("Facilities: " + playground25.getFacilities());
        playground25.setTiming("6AM-8PM");
        System.out.println("Timing: " + playground25.getTiming());
        System.out.println();

        PlayGroundDetails playground26 = new PlayGroundDetails();
        playground26.setPlaygroundId(26);
        System.out.println("Playground ID: " + playground26.getPlaygroundId());
        playground26.setPlaygroundName("Wonderla Play Zone");
        System.out.println("Name: " + playground26.getPlaygroundName());
        playground26.setLocation("Mysore Road, Bengaluru");
        System.out.println("Location: " + playground26.getLocation());
        playground26.setSurfaceType("Water + Mats");
        System.out.println("Surface: " + playground26.getSurfaceType());
        playground26.setAreaSqFt(25000);
        System.out.println("Area: " + playground26.getAreaSqFt() + " sq ft");
        playground26.setFacilities("Water slides, Lazy river");
        System.out.println("Facilities: " + playground26.getFacilities());
        playground26.setTiming("11AM-6PM");
        System.out.println("Timing: " + playground26.getTiming());
        System.out.println();

        PlayGroundDetails playground27 = new PlayGroundDetails();
        playground27.setPlaygroundId(27);
        System.out.println("Playground ID: " + playground27.getPlaygroundId());
        playground27.setPlaygroundName("Tree House Play Area");
        System.out.println("Name: " + playground27.getPlaygroundName());
        playground27.setLocation("Hebbal, Bengaluru");
        System.out.println("Location: " + playground27.getLocation());
        playground27.setSurfaceType("Wooden + Sand");
        System.out.println("Surface: " + playground27.getSurfaceType());
        playground27.setAreaSqFt(5500);
        System.out.println("Area: " + playground27.getAreaSqFt() + " sq ft");
        playground27.setFacilities("Tree houses, Zip line");
        System.out.println("Facilities: " + playground27.getFacilities());
        playground27.setTiming("9AM-7PM");
        System.out.println("Timing: " + playground27.getTiming());
        System.out.println();

        PlayGroundDetails playground28 = new PlayGroundDetails();
        playground28.setPlaygroundId(28);
        System.out.println("Playground ID: " + playground28.getPlaygroundId());
        playground28.setPlaygroundName("Joyland Kids Zone");
        System.out.println("Name: " + playground28.getPlaygroundName());
        playground28.setLocation("RT Nagar, Bengaluru");
        System.out.println("Location: " + playground28.getLocation());
        playground28.setSurfaceType("Rubber Mats");
        System.out.println("Surface: " + playground28.getSurfaceType());
        playground28.setAreaSqFt(3800);
        System.out.println("Area: " + playground28.getAreaSqFt() + " sq ft");
        playground28.setFacilities("Mini slides, Rocking animals");
        System.out.println("Facilities: " + playground28.getFacilities());
        playground28.setTiming("10AM-8PM");
        System.out.println("Timing: " + playground28.getTiming());
        System.out.println();

        PlayGroundDetails playground29 = new PlayGroundDetails();
        playground29.setPlaygroundId(29);
        System.out.println("Playground ID: " + playground29.getPlaygroundId());
        playground29.setPlaygroundName("Bal Bhavan Playground");
        System.out.println("Name: " + playground29.getPlaygroundName());
        playground29.setLocation("Vasanth Nagar, Bengaluru");
        System.out.println("Location: " + playground29.getLocation());
        playground29.setSurfaceType("Grass + Sand");
        System.out.println("Surface: " + playground29.getSurfaceType());
        playground29.setAreaSqFt(11000);
        System.out.println("Area: " + playground29.getAreaSqFt() + " sq ft");
        playground29.setFacilities("Toy train, Carousel, Slides");
        System.out.println("Facilities: " + playground29.getFacilities());
        playground29.setTiming("10AM-5:30PM");
        System.out.println("Timing: " + playground29.getTiming());
        System.out.println();
    }
}