class PocketExecutor {
    public static void main(String[] args) {
        Pocket d1 = new Pocket(); d1.pocketId = 2947; d1.pocketType = "Front"; d1.fabric = "Cotton";
        Pocket d2 = new Pocket(); d2.pocketId = 7813; d2.pocketType = "Back"; d2.fabric = "Denim";
        Pocket d3 = new Pocket(); d3.pocketId = 4562; d3.pocketType = "Side"; d3.fabric = "Canvas";
        Pocket d4 = new Pocket(); d4.pocketId = 1398; d4.pocketType = "Chest"; d4.fabric = "Leather";
        Pocket d5 = new Pocket(); d5.pocketId = 6724; d5.pocketType = "Front"; d5.fabric = "Polyester";
        Pocket d6 = new Pocket(); d6.pocketId = 8259; d6.pocketType = "Back"; d6.fabric = "Wool";
        Pocket d7 = new Pocket(); d7.pocketId = 3416; d7.pocketType = "Side"; d7.fabric = "Nylon";
        Pocket d8 = new Pocket(); d8.pocketId = 5981; d8.pocketType = "Chest"; d8.fabric = "Silk";
        Pocket d9 = new Pocket(); d9.pocketId = 7642; d9.pocketType = "Front"; d9.fabric = "Linen";
        Pocket d10 = new Pocket(); d10.pocketId = 2175; d10.pocketType = "Back"; d10.fabric = "Corduroy";
        Pocket d11 = new Pocket(); d11.pocketId = 4938; d11.pocketType = "Side"; d11.fabric = "Fleece";
        Pocket d12 = new Pocket(); d12.pocketId = 8567; d12.pocketType = "Chest"; d12.fabric = "Suede";
        Pocket d13 = new Pocket(); d13.pocketId = 1284; d13.pocketType = "Front"; d13.fabric = "Velvet";
        Pocket d14 = new Pocket(); d14.pocketId = 7391; d14.pocketType = "Back"; d14.fabric = "Twill";
        Pocket d15 = new Pocket(); d15.pocketId = 3652; d15.pocketType = "Side"; d15.fabric = "Satin";
        Pocket d16 = new Pocket(); d16.pocketId = 9473; d16.pocketType = "Chest"; d16.fabric = "Chiffon";
        Pocket d17 = new Pocket(); d17.pocketId = 5826; d17.pocketType = "Front"; d17.fabric = "Flannel";
        Pocket d18 = new Pocket(); d18.pocketId = 2149; d18.pocketType = "Back"; d18.fabric = "Seersucker";
        Pocket d19 = new Pocket(); d19.pocketId = 6738; d19.pocketType = "Side"; d19.fabric = "Poplin";
        Pocket d20 = new Pocket(); d20.pocketId = 4591; d20.pocketType = "Chest"; d20.fabric = "Taffeta";
        Pocket d21 = new Pocket(); d21.pocketId = 7824; d21.pocketType = "Front"; d21.fabric = "Gabardine";
        Pocket d22 = new Pocket(); d22.pocketId = 1367; d22.pocketType = "Back"; d22.fabric = "Drill";
        Pocket d23 = new Pocket(); d23.pocketId = 6942; d23.pocketType = "Side"; d23.fabric = "Buckram";
        Pocket d24 = new Pocket(); d24.pocketId = 8519; d24.pocketType = "Chest"; d24.fabric = "Organdy";
        Pocket d25 = new Pocket(); d25.pocketId = 3276; d25.pocketType = "Front"; d25.fabric = "Batiste";
        
        Pocket p1 = new Pocket(2947, "Front", "Cotton");
        Pocket p2 = new Pocket(7813, "Back", "Denim");
        Pocket p3 = new Pocket(4562, "Side", "Canvas");
        Pocket p4 = new Pocket(1398, "Chest", "Leather");
        Pocket p5 = new Pocket(6724, "Front", "Polyester");
        Pocket p6 = new Pocket(8259, "Back", "Wool");
        Pocket p7 = new Pocket(3416, "Side", "Nylon");
        Pocket p8 = new Pocket(5981, "Chest", "Silk");
        Pocket p9 = new Pocket(7642, "Front", "Linen");
        Pocket p10 = new Pocket(2175, "Back", "Corduroy");
        Pocket p11 = new Pocket(4938, "Side", "Fleece");
        Pocket p12 = new Pocket(8567, "Chest", "Suede");
        Pocket p13 = new Pocket(1284, "Front", "Velvet");
        Pocket p14 = new Pocket(7391, "Back", "Twill");
        Pocket p15 = new Pocket(3652, "Side", "Satin");
        Pocket p16 = new Pocket(9473, "Chest", "Chiffon");
        Pocket p17 = new Pocket(5826, "Front", "Flannel");
        Pocket p18 = new Pocket(2149, "Back", "Seersucker");
        Pocket p19 = new Pocket(6738, "Side", "Poplin");
        Pocket p20 = new Pocket(4591, "Chest", "Taffeta");
        Pocket p21 = new Pocket(7824, "Front", "Gabardine");
        Pocket p22 = new Pocket(1367, "Back", "Drill");
        Pocket p23 = new Pocket(6942, "Side", "Buckram");
        Pocket p24 = new Pocket(8519, "Chest", "Organdy");
        Pocket p25 = new Pocket(3276, "Front", "Batiste");
        
        System.out.println("Pocket d1 ID: " + d1.pocketId + " Type: " + d1.pocketType + " Fabric: " + d1.fabric);
        System.out.println("Pocket d2 ID: " + d2.pocketId + " Type: " + d2.pocketType + " Fabric: " + d2.fabric);
        System.out.println("Pocket d3 ID: " + d3.pocketId + " Type: " + d3.pocketType + " Fabric: " + d3.fabric);
        System.out.println("Pocket d4 ID: " + d4.pocketId + " Type: " + d4.pocketType + " Fabric: " + d4.fabric);
        System.out.println("Pocket d5 ID: " + d5.pocketId + " Type: " + d5.pocketType + " Fabric: " + d5.fabric);
        System.out.println("Pocket d6 ID: " + d6.pocketId + " Type: " + d6.pocketType + " Fabric: " + d6.fabric);
        System.out.println("Pocket d7 ID: " + d7.pocketId + " Type: " + d7.pocketType + " Fabric: " + d7.fabric);
        System.out.println("Pocket d8 ID: " + d8.pocketId + " Type: " + d8.pocketType + " Fabric: " + d8.fabric);
        System.out.println("Pocket d9 ID: " + d9.pocketId + " Type: " + d9.pocketType + " Fabric: " + d9.fabric);
        System.out.println("Pocket d10 ID: " + d10.pocketId + " Type: " + d10.pocketType + " Fabric: " + d10.fabric);
        System.out.println("Pocket d11 ID: " + d11.pocketId + " Type: " + d11.pocketType + " Fabric: " + d11.fabric);
        System.out.println("Pocket d12 ID: " + d12.pocketId + " Type: " + d12.pocketType + " Fabric: " + d12.fabric);
        System.out.println("Pocket d13 ID: " + d13.pocketId + " Type: " + d13.pocketType + " Fabric: " + d13.fabric);
        System.out.println("Pocket d14 ID: " + d14.pocketId + " Type: " + d14.pocketType + " Fabric: " + d14.fabric);
        System.out.println("Pocket d15 ID: " + d15.pocketId + " Type: " + d15.pocketType + " Fabric: " + d15.fabric);
        System.out.println("Pocket d16 ID: " + d16.pocketId + " Type: " + d16.pocketType + " Fabric: " + d16.fabric);
        System.out.println("Pocket d17 ID: " + d17.pocketId + " Type: " + d17.pocketType + " Fabric: " + d17.fabric);
        System.out.println("Pocket d18 ID: " + d18.pocketId + " Type: " + d18.pocketType + " Fabric: " + d18.fabric);
        System.out.println("Pocket d19 ID: " + d19.pocketId + " Type: " + d19.pocketType + " Fabric: " + d19.fabric);
        System.out.println("Pocket d20 ID: " + d20.pocketId + " Type: " + d20.pocketType + " Fabric: " + d20.fabric);
        System.out.println("Pocket d21 ID: " + d21.pocketId + " Type: " + d21.pocketType + " Fabric: " + d21.fabric);
        System.out.println("Pocket d22 ID: " + d22.pocketId + " Type: " + d22.pocketType + " Fabric: " + d22.fabric);
        System.out.println("Pocket d23 ID: " + d23.pocketId + " Type: " + d23.pocketType + " Fabric: " + d23.fabric);
        System.out.println("Pocket d24 ID: " + d24.pocketId + " Type: " + d24.pocketType + " Fabric: " + d24.fabric);
        System.out.println("Pocket d25 ID: " + d25.pocketId + " Type: " + d25.pocketType + " Fabric: " + d25.fabric);
        System.out.println("----------------------------------------------------------");
        
       System.out.println("Pocket p1 ID: " + p1.pocketId + " Type: " + p1.pocketType + " Fabric: " + p1.fabric);
        System.out.println("Pocket p2 ID: " + p2.pocketId + " Type: " + p2.pocketType + " Fabric: " + p2.fabric);
        System.out.println("Pocket p3 ID: " + p3.pocketId + " Type: " + p3.pocketType + " Fabric: " + p3.fabric);
        System.out.println("Pocket p4 ID: " + p4.pocketId + " Type: " + p4.pocketType + " Fabric: " + p4.fabric);
        System.out.println("Pocket p5 ID: " + p5.pocketId + " Type: " + p5.pocketType + " Fabric: " + p5.fabric);
        System.out.println("Pocket p6 ID: " + p6.pocketId + " Type: " + p6.pocketType + " Fabric: " + p6.fabric);
        System.out.println("Pocket p7 ID: " + p7.pocketId + " Type: " + p7.pocketType + " Fabric: " + p7.fabric);
        System.out.println("Pocket p8 ID: " + p8.pocketId + " Type: " + p8.pocketType + " Fabric: " + p8.fabric);
        System.out.println("Pocket p9 ID: " + p9.pocketId + " Type: " + p9.pocketType + " Fabric: " + p9.fabric);
        System.out.println("Pocket p10 ID: " + p10.pocketId + " Type: " + p10.pocketType + " Fabric: " + p10.fabric);
        System.out.println("Pocket p11 ID: " + p11.pocketId + " Type: " + p11.pocketType + " Fabric: " + p11.fabric);
        System.out.println("Pocket p12 ID: " + p12.pocketId + " Type: " + p12.pocketType + " Fabric: " + p12.fabric);
        System.out.println("Pocket p13 ID: " + p13.pocketId + " Type: " + p13.pocketType + " Fabric: " + p13.fabric);
        System.out.println("Pocket p14 ID: " + p14.pocketId + " Type: " + p14.pocketType + " Fabric: " + p14.fabric);
        System.out.println("Pocket p15 ID: " + p15.pocketId + " Type: " + p15.pocketType + " Fabric: " + p15.fabric);
        System.out.println("Pocket p16 ID: " + p16.pocketId + " Type: " + p16.pocketType + " Fabric: " + p16.fabric);
        System.out.println("Pocket p17 ID: " + p17.pocketId + " Type: " + p17.pocketType + " Fabric: " + p17.fabric);
        System.out.println("Pocket p18 ID: " + p18.pocketId + " Type: " + p18.pocketType + " Fabric: " + p18.fabric);
        System.out.println("Pocket p19 ID: " + p19.pocketId + " Type: " + p19.pocketType + " Fabric: " + p19.fabric);
        System.out.println("Pocket p20 ID: " + p20.pocketId + " Type: " + p20.pocketType + " Fabric: " + p20.fabric);
        System.out.println("Pocket p21 ID: " + p21.pocketId + " Type: " + p21.pocketType + " Fabric: " + p21.fabric);
        System.out.println("Pocket p22 ID: " + p22.pocketId + " Type: " + p22.pocketType + " Fabric: " + p22.fabric);
        System.out.println("Pocket p23 ID: " + p23.pocketId + " Type: " + p23.pocketType + " Fabric: " + p23.fabric);
        System.out.println("Pocket p24 ID: " + p24.pocketId + " Type: " + p24.pocketType + " Fabric: " + p24.fabric);
        System.out.println("Pocket p25 ID: " + p25.pocketId + " Type: " + p25.pocketType + " Fabric: " + p25.fabric);
        System.out.println("----------------------------------------------------------");
    }
}
