public class PoliticianDetailsExecutor {

    public static void main(String[] args) {
	
        PoliticianDetails pol1 = new PoliticianDetails();
        pol1.setId(1);
        System.out.println("ID: " + pol1.getId());
        pol1.setName("Siddaramaiah");
        System.out.println("Name: " + pol1.getName());
        pol1.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol1.getPartyName());
        pol1.setAge(78);
        System.out.println("Age: " + pol1.getAge());
        pol1.setEducation("LLB");
        System.out.println("Education: " + pol1.getEducation());
        pol1.setDistrict("Mysuru");
        System.out.println("District: " + pol1.getDistrict());
        pol1.setPosition("Chief Minister");
        System.out.println("Position: " + pol1.getPosition());
        System.out.println();

        PoliticianDetails pol2 = new PoliticianDetails();
        pol2.setId(2);
        System.out.println("ID: " + pol2.getId());
        pol2.setName("R. Ashoka");
        System.out.println("Name: " + pol2.getName());
        pol2.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol2.getPartyName());
        pol2.setAge(65);
        System.out.println("Age: " + pol2.getAge());
        pol2.setEducation("BA");
        System.out.println("Education: " + pol2.getEducation());
        pol2.setDistrict("Bengaluru South");
        System.out.println("District: " + pol2.getDistrict());
        pol2.setPosition("Leader of Opposition");
        System.out.println("Position: " + pol2.getPosition());
        System.out.println();

        PoliticianDetails pol3 = new PoliticianDetails();
        pol3.setId(3);
        System.out.println("ID: " + pol3.getId());
        pol3.setName("D.K. Shivakumar");
        System.out.println("Name: " + pol3.getName());
        pol3.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol3.getPartyName());
        pol3.setAge(62);
        System.out.println("Age: " + pol3.getAge());
        pol3.setEducation("B.Com");
        System.out.println("Education: " + pol3.getEducation());
        pol3.setDistrict("Kannakapura");
        System.out.println("District: " + pol3.getDistrict());
        pol3.setPosition("Deputy Chief Minister");
        System.out.println("Position: " + pol3.getPosition());
        System.out.println();

        PoliticianDetails pol4 = new PoliticianDetails();
        pol4.setId(4);
        System.out.println("ID: " + pol4.getId());
        pol4.setName("H.D. Kumaraswamy");
        System.out.println("Name: " + pol4.getName());
        pol4.setPartyName("Janata Dal (Secular)");
        System.out.println("Party: " + pol4.getPartyName());
        pol4.setAge(66);
        System.out.println("Age: " + pol4.getAge());
        pol4.setEducation("Diploma");
        System.out.println("Education: " + pol4.getEducation());
        pol4.setDistrict("Channapatna");
        System.out.println("District: " + pol4.getDistrict());
        pol4.setPosition("Union Minister");
        System.out.println("Position: " + pol4.getPosition());
        System.out.println();

        PoliticianDetails pol5 = new PoliticianDetails();
        pol5.setId(5);
        System.out.println("ID: " + pol5.getId());
        pol5.setName("N.S. Boseraju");
        System.out.println("Name: " + pol5.getName());
        pol5.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol5.getPartyName());
        pol5.setAge(58);
        System.out.println("Age: " + pol5.getAge());
        pol5.setEducation("MA");
        System.out.println("Education: " + pol5.getEducation());
        pol5.setDistrict("Raichur");
        System.out.println("District: " + pol5.getDistrict());
        pol5.setPosition("Leader of Council");
        System.out.println("Position: " + pol5.getPosition());
        System.out.println();
		
		PoliticianDetails pol6 = new PoliticianDetails();
        pol6.setId(6);
        System.out.println("ID: " + pol6.getId());
        pol6.setName("Priyank Kharge");
        System.out.println("Name: " + pol6.getName());
        pol6.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol6.getPartyName());
        pol6.setAge(45);
        System.out.println("Age: " + pol6.getAge());
        pol6.setEducation("B.Tech");
        System.out.println("Education: " + pol6.getEducation());
        pol6.setDistrict("Chittapur");
        System.out.println("District: " + pol6.getDistrict());
        pol6.setPosition("Minister for IT");
        System.out.println("Position: " + pol6.getPosition());
        System.out.println();

        PoliticianDetails pol7 = new PoliticianDetails();
        pol7.setId(7);
        System.out.println("ID: " + pol7.getId());
        pol7.setName("B.Y. Vijayendra");
        System.out.println("Name: " + pol7.getName());
        pol7.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol7.getPartyName());
        pol7.setAge(48);
        System.out.println("Age: " + pol7.getAge());
        pol7.setEducation("BA");
        System.out.println("Education: " + pol7.getEducation());
        pol7.setDistrict("Shikaripura");
        System.out.println("District: " + pol7.getDistrict());
        pol7.setPosition("State BJP President");
        System.out.println("Position: " + pol7.getPosition());
        System.out.println();

        PoliticianDetails pol8 = new PoliticianDetails();
        pol8.setId(8);
        System.out.println("ID: " + pol8.getId());
        pol8.setName("Tanveer Sait");
        System.out.println("Name: " + pol8.getName());
        pol8.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol8.getPartyName());
        pol8.setAge(52);
        System.out.println("Age: " + pol8.getAge());
        pol8.setEducation("BA");
        System.out.println("Education: " + pol8.getEducation());
        pol8.setDistrict("Narasimharaja");
        System.out.println("District: " + pol8.getDistrict());
        pol8.setPosition("Minister for Urban Development");
        System.out.println("Position: " + pol8.getPosition());
        System.out.println();

        PoliticianDetails pol9 = new PoliticianDetails();
        pol9.setId(9);
        System.out.println("ID: " + pol9.getId());
        pol9.setName("U.T. Khader");
        System.out.println("Name: " + pol9.getName());
        pol9.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol9.getPartyName());
        pol9.setAge(49);
        System.out.println("Age: " + pol9.getAge());
        pol9.setEducation("LLB");
        System.out.println("Education: " + pol9.getEducation());
        pol9.setDistrict("Mangaluru");
        System.out.println("District: " + pol9.getDistrict());
        pol9.setPosition("Assembly Speaker");
        System.out.println("Position: " + pol9.getPosition());
        System.out.println();

        PoliticianDetails pol10 = new PoliticianDetails();
        pol10.setId(10);
        System.out.println("ID: " + pol10.getId());
        pol10.setName("G.T. Devegowda");
        System.out.println("Name: " + pol10.getName());
        pol10.setPartyName("Janata Dal (Secular)");
        System.out.println("Party: " + pol10.getPartyName());
        pol10.setAge(60);
        System.out.println("Age: " + pol10.getAge());
        pol10.setEducation("Diploma");
        System.out.println("Education: " + pol10.getEducation());
        pol10.setDistrict("Chamundeshwari");
        System.out.println("District: " + pol10.getDistrict());
        pol10.setPosition("MLA");
        System.out.println("Position: " + pol10.getPosition());
        System.out.println();

        PoliticianDetails pol11 = new PoliticianDetails();
        pol11.setId(11);
        System.out.println("ID: " + pol11.getId());
        pol11.setName("Darshan Puttannaiah");
        System.out.println("Name: " + pol11.getName());
        pol11.setPartyName("Sarvodaya Karnataka Paksha");
        System.out.println("Party: " + pol11.getPartyName());
        pol11.setAge(42);
        System.out.println("Age: " + pol11.getAge());
        pol11.setEducation("M.Tech");
        System.out.println("Education: " + pol11.getEducation());
        pol11.setDistrict("Melukote");
        System.out.println("District: " + pol11.getDistrict());
        pol11.setPosition("MLA");
        System.out.println("Position: " + pol11.getPosition());
        System.out.println();

        PoliticianDetails pol12 = new PoliticianDetails();
        pol12.setId(12);
        System.out.println("ID: " + pol12.getId());
        pol12.setName("H.D. Revanna");
        System.out.println("Name: " + pol12.getName());
        pol12.setPartyName("Janata Dal (Secular)");
        System.out.println("Party: " + pol12.getPartyName());
        pol12.setAge(64);
        System.out.println("Age: " + pol12.getAge());
        pol12.setEducation("BA");
        System.out.println("Education: " + pol12.getEducation());
        pol12.setDistrict("Holenarasipur");
        System.out.println("District: " + pol12.getDistrict());
        pol12.setPosition("MLA");
        System.out.println("Position: " + pol12.getPosition());
        System.out.println();

        PoliticianDetails pol13 = new PoliticianDetails();
        pol13.setId(13);
        System.out.println("ID: " + pol13.getId());
        pol13.setName("K.M. Shivalinge Gowda");
        System.out.println("Name: " + pol13.getName());
        pol13.setPartyName("Janata Dal (Secular)");
        System.out.println("Party: " + pol13.getPartyName());
        pol13.setAge(55);
        System.out.println("Age: " + pol13.getAge());
        pol13.setEducation("MA");
        System.out.println("Education: " + pol13.getEducation());
        pol13.setDistrict("Arsikere");
        System.out.println("District: " + pol13.getDistrict());
        pol13.setPosition("MLA");
        System.out.println("Position: " + pol13.getPosition());
        System.out.println();

        PoliticianDetails pol14 = new PoliticianDetails();
        pol14.setId(14);
        System.out.println("ID: " + pol14.getId());
        pol14.setName("P.M. Narendra Swamy");
        System.out.println("Name: " + pol14.getName());
        pol14.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol14.getPartyName());
        pol14.setAge(59);
        System.out.println("Age: " + pol14.getAge());
        pol14.setEducation("B.Com");
        System.out.println("Education: " + pol14.getEducation());
        pol14.setDistrict("Malavalli");
        System.out.println("District: " + pol14.getDistrict());
        pol14.setPosition("MLA");
        System.out.println("Position: " + pol14.getPosition());
        System.out.println();

        PoliticianDetails pol15 = new PoliticianDetails();
        pol15.setId(15);
        System.out.println("ID: " + pol15.getId());
        pol15.setName("Ravikumar Gowda");
        System.out.println("Name: " + pol15.getName());
        pol15.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol15.getPartyName());
        pol15.setAge(47);
        System.out.println("Age: " + pol15.getAge());
        pol15.setEducation("LLB");
        System.out.println("Education: " + pol15.getEducation());
        pol15.setDistrict("Mandya");
        System.out.println("District: " + pol15.getDistrict());
        pol15.setPosition("MLA");
        System.out.println("Position: " + pol15.getPosition());
        System.out.println();

        PoliticianDetails pol16 = new PoliticianDetails();
        pol16.setId(16);
        System.out.println("ID: " + pol16.getId());
        pol16.setName("Ramesha Bandisiddegowda");
        System.out.println("Name: " + pol16.getName());
        pol16.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol16.getPartyName());
        pol16.setAge(53);
        System.out.println("Age: " + pol16.getAge());
        pol16.setEducation("BA");
        System.out.println("Education: " + pol16.getEducation());
        pol16.setDistrict("Shrirangapattana");
        System.out.println("District: " + pol16.getDistrict());
        pol16.setPosition("MLA");
        System.out.println("Position: " + pol16.getPosition());
        System.out.println();

        PoliticianDetails pol17 = new PoliticianDetails();
        pol17.setId(17);
        System.out.println("ID: " + pol17.getId());
        pol17.setName("N. Chaluvaraya Swamy");
        System.out.println("Name: " + pol17.getName());
        pol17.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol17.getPartyName());
        pol17.setAge(61);
        System.out.println("Age: " + pol17.getAge());
        pol17.setEducation("MA");
        System.out.println("Education: " + pol17.getEducation());
        pol17.setDistrict("Nagamangala");
        System.out.println("District: " + pol17.getDistrict());
        pol17.setPosition("MLA");
        System.out.println("Position: " + pol17.getPosition());
        System.out.println();
		
		PoliticianDetails pol18 = new PoliticianDetails();
        pol18.setId(18);
        System.out.println("ID: " + pol18.getId());
        pol18.setName("S. Rudregowda");
        System.out.println("Name: " + pol18.getName());
        pol18.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol18.getPartyName());
        pol18.setAge(56);
        System.out.println("Age: " + pol18.getAge());
        pol18.setEducation("BA");
        System.out.println("Education: " + pol18.getEducation());
        pol18.setDistrict("Vijayapura City");
        System.out.println("District: " + pol18.getDistrict());
        pol18.setPosition("MLA");
        System.out.println("Position: " + pol18.getPosition());
        System.out.println();

        PoliticianDetails pol19 = new PoliticianDetails();
        pol19.setId(19);
        System.out.println("ID: " + pol19.getId());
        pol19.setName("K. Harishkumar");
        System.out.println("Name: " + pol19.getName());
        pol19.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol19.getPartyName());
        pol19.setAge(44);
        System.out.println("Age: " + pol19.getAge());
        pol19.setEducation("B.Com");
        System.out.println("Education: " + pol19.getEducation());
        pol19.setDistrict("Kalghatgi");
        System.out.println("District: " + pol19.getDistrict());
        pol19.setPosition("MLA");
        System.out.println("Position: " + pol19.getPosition());
        System.out.println();

        PoliticianDetails pol20 = new PoliticianDetails();
        pol20.setId(20);
        System.out.println("ID: " + pol20.getId());
        pol20.setName("Ivan D'Souza");
        System.out.println("Name: " + pol20.getName());
        pol20.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol20.getPartyName());
        pol20.setAge(50);
        System.out.println("Age: " + pol20.getAge());
        pol20.setEducation("LLB");
        System.out.println("Education: " + pol20.getEducation());
        pol20.setDistrict("Mangalore City North");
        System.out.println("District: " + pol20.getDistrict());
        pol20.setPosition("MLC");
        System.out.println("Position: " + pol20.getPosition());
        System.out.println();

        PoliticianDetails pol21 = new PoliticianDetails();
        pol21.setId(21);
        System.out.println("ID: " + pol21.getId());
        pol21.setName("Ayanur Manjunath");
        System.out.println("Name: " + pol21.getName());
        pol21.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol21.getPartyName());
        pol21.setAge(57);
        System.out.println("Age: " + pol21.getAge());
        pol21.setEducation("MA");
        System.out.println("Education: " + pol21.getEducation());
        pol21.setDistrict("South-West Graduate");
        System.out.println("District: " + pol21.getDistrict());
        pol21.setPosition("MLC");
        System.out.println("Position: " + pol21.getPosition());
        System.out.println();

        PoliticianDetails pol22 = new PoliticianDetails();
        pol22.setId(22);
        System.out.println("ID: " + pol22.getId());
        pol22.setName("Maritibbe Gowda");
        System.out.println("Name: " + pol22.getName());
        pol22.setPartyName("Janata Dal (Secular)");
        System.out.println("Party: " + pol22.getPartyName());
        pol22.setAge(63);
        System.out.println("Age: " + pol22.getAge());
        pol22.setEducation("BA");
        System.out.println("Education: " + pol22.getEducation());
        pol22.setDistrict("South Teachers");
        System.out.println("District: " + pol22.getDistrict());
        pol22.setPosition("MLC");
        System.out.println("Position: " + pol22.getPosition());
        System.out.println();

        PoliticianDetails pol23 = new PoliticianDetails();
        pol23.setId(23);
        System.out.println("ID: " + pol23.getId());
        pol23.setName("Tejashwini Gowda");
        System.out.println("Name: " + pol23.getName());
        pol23.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol23.getPartyName());
        pol23.setAge(39);
        System.out.println("Age: " + pol23.getAge());
        pol23.setEducation("MBA");
        System.out.println("Education: " + pol23.getEducation());
        pol23.setDistrict("Mysuru");
        System.out.println("District: " + pol23.getDistrict());
        pol23.setPosition("MLC");
        System.out.println("Position: " + pol23.getPosition());
        System.out.println();

        PoliticianDetails pol24 = new PoliticianDetails();
        pol24.setId(24);
        System.out.println("ID: " + pol24.getId());
        pol24.setName("Raghunath Rao Malkapure");
        System.out.println("Name: " + pol24.getName());
        pol24.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol24.getPartyName());
        pol24.setAge(62);
        System.out.println("Age: " + pol24.getAge());
        pol24.setEducation("B.Tech");
        System.out.println("Education: " + pol24.getEducation());
        pol24.setDistrict("Belagavi");
        System.out.println("District: " + pol24.getDistrict());
        pol24.setPosition("MLC");
        System.out.println("Position: " + pol24.getPosition());
        System.out.println();

        PoliticianDetails pol25 = new PoliticianDetails();
        pol25.setId(25);
        System.out.println("ID: " + pol25.getId());
        pol25.setName("K.P. Nanjundi");
        System.out.println("Name: " + pol25.getName());
        pol25.setPartyName("Bharatiya Janata Party");
        System.out.println("Party: " + pol25.getPartyName());
        pol25.setAge(54);
        System.out.println("Age: " + pol25.getAge());
        pol25.setEducation("MA");
        System.out.println("Education: " + pol25.getEducation());
        pol25.setDistrict("North-West Graduate");
        System.out.println("District: " + pol25.getDistrict());
        pol25.setPosition("MLC");
        System.out.println("Position: " + pol25.getPosition());
        System.out.println();

        PoliticianDetails pol26 = new PoliticianDetails();
        pol26.setId(26);
        System.out.println("ID: " + pol26.getId());
        pol26.setName("Jagdev Guttedar");
        System.out.println("Name: " + pol26.getName());
        pol26.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol26.getPartyName());
        pol26.setAge(67);
        System.out.println("Age: " + pol26.getAge());
        pol26.setEducation("B.Com");
        System.out.println("Education: " + pol26.getEducation());
        pol26.setDistrict("Nippani");
        System.out.println("District: " + pol26.getDistrict());
        pol26.setPosition("MLC");
        System.out.println("Position: " + pol26.getPosition());
        System.out.println();

        PoliticianDetails pol27 = new PoliticianDetails();
        pol27.setId(27);
        System.out.println("ID: " + pol27.getId());
        pol27.setName("Bilkis Bano");
        System.out.println("Name: " + pol27.getName());
        pol27.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol27.getPartyName());
        pol27.setAge(46);
        System.out.println("Age: " + pol27.getAge());
        pol27.setEducation("MA");
        System.out.println("Education: " + pol27.getEducation());
        pol27.setDistrict("Kalaburagi");
        System.out.println("District: " + pol27.getDistrict());
        pol27.setPosition("MLC");
        System.out.println("Position: " + pol27.getPosition());
        System.out.println();

        PoliticianDetails pol28 = new PoliticianDetails();
        pol28.setId(28);
        System.out.println("ID: " + pol28.getId());
        pol28.setName("K.A. Thippeswamy");
        System.out.println("Name: " + pol28.getName());
        pol28.setPartyName("Janata Dal (Secular)");
        System.out.println("Party: " + pol28.getPartyName());
        pol28.setAge(59);
        System.out.println("Age: " + pol28.getAge());
        pol28.setEducation("Diploma");
        System.out.println("Education: " + pol28.getEducation());
        pol28.setDistrict("Nominated");
        System.out.println("District: " + pol28.getDistrict());
        pol28.setPosition("MLC");
        System.out.println("Position: " + pol28.getPosition());
        System.out.println();

        PoliticianDetails pol29 = new PoliticianDetails();
        pol29.setId(29);
        System.out.println("ID: " + pol29.getId());
        pol29.setName("Prakash Rathod");
        System.out.println("Name: " + pol29.getName());
        pol29.setPartyName("Indian National Congress");
        System.out.println("Party: " + pol29.getPartyName());
        pol29.setAge(51);
        System.out.println("Age: " + pol29.getAge());
        pol29.setEducation("B.Tech");
        System.out.println("Education: " + pol29.getEducation());
        pol29.setDistrict("Nominated");
        System.out.println("District: " + pol29.getDistrict());
        pol29.setPosition("MLC");
        System.out.println("Position: " + pol29.getPosition());
        System.out.println();
    }
}