class PostMortemReportExecutor {
    public static void main(String[] cases) {
	
        PostMortemReport case1 = new PostMortemReport();
        case1.setCaseId(1);
        System.out.println("Case ID: " + case1.getCaseId());
        case1.setDeceasedName("Cyrus Mistry");
        System.out.println("Deceased: " + case1.getDeceasedName());
        case1.setDateOfDeath("2022-09-04");
        System.out.println("Date of Death: " + case1.getDateOfDeath());
        case1.setCauseOfDeath("Polytrauma - Car Crash");
        System.out.println("Cause: " + case1.getCauseOfDeath());
        case1.setExternalInjuries("Head trauma, chest impact");
        System.out.println("External Injuries: " + case1.getExternalInjuries());
        case1.setInternalFindings("Heart rupture, multiple fractures");
        System.out.println("Internal Findings: " + case1.getInternalFindings());
        case1.setDoctorOpinion("Death due to overspeeding crash");
        System.out.println("Doctor Opinion: " + case1.getDoctorOpinion());
        System.out.println();

        PostMortemReport case2 = new PostMortemReport();
        case2.setCaseId(2);
        System.out.println("Case ID: " + case2.getCaseId());
        case2.setDeceasedName("Ajith Kumar");
        System.out.println("Deceased: " + case2.getDeceasedName());
        case2.setDateOfDeath("2025-07-03");
        System.out.println("Date of Death: " + case2.getDateOfDeath());
        case2.setCauseOfDeath("Custodial Torture");
        System.out.println("Cause: " + case2.getCauseOfDeath());
        case2.setExternalInjuries("50+ torture marks on body");
        System.out.println("External Injuries: " + case2.getExternalInjuries());
        case2.setInternalFindings("Internal bleeding, organ damage");
        System.out.println("Internal Findings: " + case2.getInternalFindings());
        case2.setDoctorOpinion("Evidence of severe police brutality");
        System.out.println("Doctor Opinion: " + case2.getDoctorOpinion());
        System.out.println();

        PostMortemReport case3 = new PostMortemReport();
        case3.setCaseId(3);
        System.out.println("Case ID: " + case3.getCaseId());
        case3.setDeceasedName("Dr. Vandana Das");
        System.out.println("Deceased: " + case3.getDeceasedName());
        case3.setDateOfDeath("2021-02-11");
        System.out.println("Date of Death: " + case3.getDateOfDeath());
        case3.setCauseOfDeath("Multiple Stab Wounds");
        System.out.println("Cause: " + case3.getCauseOfDeath());
        case3.setExternalInjuries("27 scissor stab wounds");
        System.out.println("External Injuries: " + case3.getExternalInjuries());
        case3.setInternalFindings("Lacerated heart, punctured lungs");
        System.out.println("Internal Findings: " + case3.getInternalFindings());
        case3.setDoctorOpinion("Brutal hospital attack");
        System.out.println("Doctor Opinion: " + case3.getDoctorOpinion());
        System.out.println();

        PostMortemReport case4 = new PostMortemReport();
        case4.setCaseId(4);
        System.out.println("Case ID: " + case4.getCaseId());
        case4.setDeceasedName("Veterinary Doctor");
        System.out.println("Deceased: " + case4.getDeceasedName());
        case4.setDateOfDeath("2019-11-27");
        System.out.println("Date of Death: " + case4.getDateOfDeath());
        case4.setCauseOfDeath("Gang Rape & Murder");
        System.out.println("Cause: " + case4.getCauseOfDeath());
        case4.setExternalInjuries("Strangulation marks, burn injuries");
        System.out.println("External Injuries: " + case4.getExternalInjuries());
        case4.setInternalFindings("Sexual assault evidence, asphyxia");
        System.out.println("Internal Findings: " + case4.getInternalFindings());
        case4.setDoctorOpinion("Hyderabad sensational case");
        System.out.println("Doctor Opinion: " + case4.getDoctorOpinion());
        System.out.println();

        PostMortemReport case5 = new PostMortemReport();
        case5.setCaseId(5);
        System.out.println("Case ID: " + case5.getCaseId());
        case5.setDeceasedName("Charanpreet Singh");
        System.out.println("Deceased: " + case5.getDeceasedName());
        case5.setDateOfDeath("2026-03-20");
        System.out.println("Date of Death: " + case5.getDateOfDeath());
        case5.setCauseOfDeath("Gunshot Wound");
        System.out.println("Cause: " + case5.getCauseOfDeath());
        case5.setExternalInjuries("Multiple bullet wounds to chest");
        System.out.println("External Injuries: " + case5.getExternalInjuries());
        case5.setInternalFindings("Heart and lung perforation");
        System.out.println("Internal Findings: " + case5.getInternalFindings());
        case5.setDoctorOpinion("Chandigarh contract killing");
        System.out.println("Doctor Opinion: " + case5.getDoctorOpinion());
        System.out.println();
		
		PostMortemReport case6 = new PostMortemReport();
        case6.setCaseId(6);
        System.out.println("Case ID: " + case6.getCaseId());
        case6.setDeceasedName("Saurabh Rajput");
        System.out.println("Deceased: " + case6.getDeceasedName());
        case6.setDateOfDeath("2025-03-04");
        System.out.println("Date of Death: " + case6.getDateOfDeath());
        case6.setCauseOfDeath("Dismemberment Murder");
        System.out.println("Cause: " + case6.getCauseOfDeath());
        case6.setExternalInjuries("Body chopped into 15 pieces");
        System.out.println("External Injuries: " + case6.getExternalInjuries());
        case6.setInternalFindings("Cement-filled blue drum");
        System.out.println("Internal Findings: " + case6.getInternalFindings());
        case6.setDoctorOpinion("Meerut Blue Drum horror case");
        System.out.println("Doctor Opinion: " + case6.getDoctorOpinion());
        System.out.println();

        PostMortemReport case7 = new PostMortemReport();
        case7.setCaseId(7);
        System.out.println("Case ID: " + case7.getCaseId());
        case7.setDeceasedName("Dilip Yadav");
        System.out.println("Deceased: " + case7.getDeceasedName());
        case7.setDateOfDeath("2025-03-15");
        System.out.println("Date of Death: " + case7.getDateOfDeath());
        case7.setCauseOfDeath("Contract Killing");
        System.out.println("Cause: " + case7.getCauseOfDeath());
        case7.setExternalInjuries("Multiple sharp weapon wounds");
        System.out.println("External Injuries: " + case7.getExternalInjuries());
        case7.setInternalFindings("Stabbed by hired killer");
        System.out.println("Internal Findings: " + case7.getInternalFindings());
        case7.setDoctorOpinion("Auraiya Killer Bride case");
        System.out.println("Doctor Opinion: " + case7.getDoctorOpinion());
        System.out.println();

        PostMortemReport case8 = new PostMortemReport();
        case8.setCaseId(8);
        System.out.println("Case ID: " + case8.getCaseId());
        case8.setDeceasedName("Praveen");
        System.out.println("Deceased: " + case8.getDeceasedName());
        case8.setDateOfDeath("2025-03-25");
        System.out.println("Date of Death: " + case8.getDateOfDeath());
        case8.setCauseOfDeath("Strangulation");
        System.out.println("Cause: " + case8.getCauseOfDeath());
        case8.setExternalInjuries("Dupatta ligature marks");
        System.out.println("External Injuries: " + case8.getExternalInjuries());
        case8.setInternalFindings("Asphyxia, neck compression");
        System.out.println("Internal Findings: " + case8.getInternalFindings());
        case8.setDoctorOpinion("Wife-lover honor killing");
        System.out.println("Doctor Opinion: " + case8.getDoctorOpinion());
        System.out.println();

        PostMortemReport case9 = new PostMortemReport();
        case9.setCaseId(9);
        System.out.println("Case ID: " + case9.getCaseId());
        case9.setDeceasedName("RG Kar Doctor");
        System.out.println("Deceased: " + case9.getDeceasedName());
        case9.setDateOfDeath("2024-08-09");
        System.out.println("Date of Death: " + case9.getDateOfDeath());
        case9.setCauseOfDeath("Strangulation + Rape");
        System.out.println("Cause: " + case9.getCauseOfDeath());
        case9.setExternalInjuries("14 injuries, genital trauma");
        System.out.println("External Injuries: " + case9.getExternalInjuries());
        case9.setInternalFindings("Manual strangulation, smothering");
        System.out.println("Internal Findings: " + case9.getInternalFindings());
        case9.setDoctorOpinion("Kolkata hospital horror");
        System.out.println("Doctor Opinion: " + case9.getDoctorOpinion());
        System.out.println();

        PostMortemReport case10 = new PostMortemReport();
        case10.setCaseId(10);
        System.out.println("Case ID: " + case10.getCaseId());
        case10.setDeceasedName("Aarushi Talwar");
        System.out.println("Deceased: " + case10.getDeceasedName());
        case10.setDateOfDeath("2008-05-16");
        System.out.println("Date of Death: " + case10.getDateOfDeath());
        case10.setCauseOfDeath("Blunt Force Trauma");
        System.out.println("Cause: " + case10.getCauseOfDeath());
        case10.setExternalInjuries("Head injuries, throat slit");
        System.out.println("External Injuries: " + case10.getExternalInjuries());
        case10.setInternalFindings("Skull fracture, hemorrhage");
        System.out.println("Internal Findings: " + case10.getInternalFindings());
        case10.setDoctorOpinion("Noida double murder mystery");
        System.out.println("Doctor Opinion: " + case10.getDoctorOpinion());
        System.out.println();

        PostMortemReport case11 = new PostMortemReport();
        case11.setCaseId(11);
        System.out.println("Case ID: " + case11.getCaseId());
        case11.setDeceasedName("Hemraj");
        System.out.println("Deceased: " + case11.getDeceasedName());
        case11.setDateOfDeath("2008-05-16");
        System.out.println("Date of Death: " + case11.getDateOfDeath());
        case11.setCauseOfDeath("Blunt Force + Stab");
        System.out.println("Cause: " + case11.getCauseOfDeath());
        case11.setExternalInjuries("Multiple head injuries");
        System.out.println("External Injuries: " + case11.getExternalInjuries());
        case11.setInternalFindings("Brain hemorrhage");
        System.out.println("Internal Findings: " + case11.getInternalFindings());
        case11.setDoctorOpinion("Aarushi case domestic help");
        System.out.println("Doctor Opinion: " + case11.getDoctorOpinion());
        System.out.println();

        PostMortemReport case12 = new PostMortemReport();
        case12.setCaseId(12);
        System.out.println("Case ID: " + case12.getCaseId());
        case12.setDeceasedName("Nirbhaya");
        System.out.println("Deceased: " + case12.getDeceasedName());
        case12.setDateOfDeath("2012-12-16");
        System.out.println("Date of Death: " + case12.getDateOfDeath());
        case12.setCauseOfDeath("Gang Rape + Internal Injuries");
        System.out.println("Cause: " + case12.getCauseOfDeath());
        case12.setExternalInjuries("Brutalized with iron rod");
        System.out.println("External Injuries: " + case12.getExternalInjuries());
        case12.setInternalFindings("Peritonitis, septic shock");
        System.out.println("Internal Findings: " + case12.getInternalFindings());
        case12.setDoctorOpinion("Delhi bus gang rape case");
        System.out.println("Doctor Opinion: " + case12.getDoctorOpinion());
        System.out.println();

        PostMortemReport case13 = new PostMortemReport();
        case13.setCaseId(13);
        System.out.println("Case ID: " + case13.getCaseId());
        case13.setDeceasedName("Raja Raghuvanshi");
        System.out.println("Deceased: " + case13.getDeceasedName());
        case13.setDateOfDeath("2025-05-20");
        System.out.println("Date of Death: " + case13.getDateOfDeath());
        case13.setCauseOfDeath("Honeymoon Murder");
        System.out.println("Cause: " + case13.getCauseOfDeath());
        case13.setExternalInjuries("Stabbed multiple times");
        System.out.println("External Injuries: " + case13.getExternalInjuries());
        case13.setInternalFindings("Chest and abdominal wounds");
        System.out.println("Internal Findings: " + case13.getInternalFindings());
        case13.setDoctorOpinion("Meghalaya honeymoon killing");
        System.out.println("Doctor Opinion: " + case13.getDoctorOpinion());
        System.out.println();

        PostMortemReport case14 = new PostMortemReport();
        case14.setCaseId(14);
        System.out.println("Case ID: " + case14.getCaseId());
        case14.setDeceasedName("Sheena Bora");
        System.out.println("Deceased: " + case14.getDeceasedName());
        case14.setDateOfDeath("2012-04-24");
        System.out.println("Date of Death: " + case14.getDateOfDeath());
        case14.setCauseOfDeath("Strangulation");
        System.out.println("Cause: " + case14.getCauseOfDeath());
        case14.setExternalInjuries("Ligature marks on neck");
        System.out.println("External Injuries: " + case14.getExternalInjuries());
        case14.setInternalFindings("Asphyxia confirmed");
        System.out.println("Internal Findings: " + case14.getInternalFindings());
        case14.setDoctorOpinion("Mumbai family murder scandal");
        System.out.println("Doctor Opinion: " + case14.getDoctorOpinion());
        System.out.println();

        PostMortemReport case15 = new PostMortemReport();
        case15.setCaseId(15);
        System.out.println("Case ID: " + case15.getCaseId());
        case15.setDeceasedName("Sunanda Pushkar");
        System.out.println("Deceased: " + case15.getDeceasedName());
        case15.setDateOfDeath("2014-01-17");
        System.out.println("Date of Death: " + case15.getDateOfDeath());
        case15.setCauseOfDeath("Poisoning");
        System.out.println("Cause: " + case15.getCauseOfDeath());
        case15.setExternalInjuries("Multiple injury marks");
        System.out.println("External Injuries: " + case15.getExternalInjuries());
        case15.setInternalFindings("Toxicology positive");
        System.out.println("Internal Findings: " + case15.getInternalFindings());
        case15.setDoctorOpinion("Hotel room mystery death");
        System.out.println("Doctor Opinion: " + case15.getDoctorOpinion());
        System.out.println();

        PostMortemReport case16 = new PostMortemReport();
        case16.setCaseId(16);
        System.out.println("Case ID: " + case16.getCaseId());
        case16.setDeceasedName("Neeraj Grover");
        System.out.println("Deceased: " + case16.getDeceasedName());
        case16.setDateOfDeath("2008-04-07");
        System.out.println("Date of Death: " + case16.getDateOfDeath());
        case16.setCauseOfDeath("Stabbed & Burnt");
        System.out.println("Cause: " + case16.getCauseOfDeath());
        case16.setExternalInjuries("Multiple stab wounds");
        System.out.println("External Injuries: " + case16.getExternalInjuries());
        case16.setInternalFindings("Charred remains found");
        System.out.println("Internal Findings: " + case16.getInternalFindings());
        case16.setDoctorOpinion("TV actress murder case");
        System.out.println("Doctor Opinion: " + case16.getDoctorOpinion());
        System.out.println();

        PostMortemReport case17 = new PostMortemReport();
        case17.setCaseId(17);
        System.out.println("Case ID: " + case17.getCaseId());
        case17.setDeceasedName("Unknown Train Passenger");
        System.out.println("Deceased: " + case17.getDeceasedName());
        case17.setDateOfDeath("2025-06-20");
        System.out.println("Date of Death: " + case17.getDateOfDeath());
        case17.setCauseOfDeath("Blunt Force Trauma");
        System.out.println("Cause: " + case17.getCauseOfDeath());
        case17.setExternalInjuries("Head injuries, fractures");
        System.out.println("External Injuries: " + case17.getExternalInjuries());
        case17.setInternalFindings("Brain hemorrhage");
        System.out.println("Internal Findings: " + case17.getInternalFindings());
        case17.setDoctorOpinion("Bhubaneswar train mystery");
        System.out.println("Doctor Opinion: " + case17.getDoctorOpinion());
        System.out.println();
		
		PostMortemReport case18 = new PostMortemReport();
        case18.setCaseId(18);
        System.out.println("Case ID: " + case18.getCaseId());
        case18.setDeceasedName("Shraddha Walkar");
        System.out.println("Deceased: " + case18.getDeceasedName());
        case18.setDateOfDeath("2022-05-18");
        System.out.println("Date of Death: " + case18.getDateOfDeath());
        case18.setCauseOfDeath("Strangulation");
        System.out.println("Cause: " + case18.getCauseOfDeath());
        case18.setExternalInjuries("Ligature marks on neck");
        System.out.println("External Injuries: " + case18.getExternalInjuries());
        case18.setInternalFindings("Asphyxia, body dismembered");
        System.out.println("Internal Findings: " + case18.getInternalFindings());
        case18.setDoctorOpinion("Delhi fridge murder case");
        System.out.println("Doctor Opinion: " + case18.getDoctorOpinion());
        System.out.println();

        PostMortemReport case19 = new PostMortemReport();
        case19.setCaseId(19);
        System.out.println("Case ID: " + case19.getCaseId());
        case19.setDeceasedName("Ankit Saxena");
        System.out.println("Deceased: " + case19.getDeceasedName());
        case19.setDateOfDeath("2018-02-01");
        System.out.println("Date of Death: " + case19.getDateOfDeath());
        case19.setCauseOfDeath("Multiple Stab Wounds");
        System.out.println("Cause: " + case19.getCauseOfDeath());
        case19.setExternalInjuries("20+ knife wounds");
        System.out.println("External Injuries: " + case19.getExternalInjuries());
        case19.setInternalFindings("Chest and abdominal trauma");
        System.out.println("Internal Findings: " + case19.getInternalFindings());
        case19.setDoctorOpinion("Honor killing Delhi");
        System.out.println("Doctor Opinion: " + case19.getDoctorOpinion());
        System.out.println();

        PostMortemReport case20 = new PostMortemReport();
        case20.setCaseId(20);
        System.out.println("Case ID: " + case20.getCaseId());
        case20.setDeceasedName("Priyadarshini Mattoo");
        System.out.println("Deceased: " + case20.getDeceasedName());
        case20.setDateOfDeath("1996-01-23");
        System.out.println("Date of Death: " + case20.getDateOfDeath());
        case20.setCauseOfDeath("Rape & Murder");
        System.out.println("Cause: " + case20.getCauseOfDeath());
        case20.setExternalInjuries("Raped, skull fractured");
        System.out.println("External Injuries: " + case20.getExternalInjuries());
        case20.setInternalFindings("Brutal head injuries");
        System.out.println("Internal Findings: " + case20.getInternalFindings());
        case20.setDoctorOpinion("Delhi law student case");
        System.out.println("Doctor Opinion: " + case20.getDoctorOpinion());
        System.out.println();

        PostMortemReport case21 = new PostMortemReport();
        case21.setCaseId(21);
        System.out.println("Case ID: " + case21.getCaseId());
        case21.setDeceasedName("Jessica Lal");
        System.out.println("Deceased: " + case21.getDeceasedName());
        case21.setDateOfDeath("1999-04-29");
        System.out.println("Date of Death: " + case21.getDateOfDeath());
        case21.setCauseOfDeath("Gunshot Wound");
        System.out.println("Cause: " + case21.getCauseOfDeath());
        case21.setExternalInjuries("Single bullet to head");
        System.out.println("External Injuries: " + case21.getExternalInjuries());
        case21.setInternalFindings("Brain damage, instant death");
        System.out.println("Internal Findings: " + case21.getInternalFindings());
        case21.setDoctorOpinion("Delhi pub shooter case");
        System.out.println("Doctor Opinion: " + case21.getDoctorOpinion());
        System.out.println();

        PostMortemReport case22 = new PostMortemReport();
        case22.setCaseId(22);
        System.out.println("Case ID: " + case22.getCaseId());
        case22.setDeceasedName("Akhlaq");
        System.out.println("Deceased: " + case22.getDeceasedName());
        case22.setDateOfDeath("2015-09-28");
        System.out.println("Date of Death: " + case22.getDateOfDeath());
        case22.setCauseOfDeath("Mob Lynching");
        System.out.println("Cause: " + case22.getCauseOfDeath());
        case22.setExternalInjuries("Blunt injuries chest/head");
        System.out.println("External Injuries: " + case22.getExternalInjuries());
        case22.setInternalFindings("Chest compression, hemorrhage");
        System.out.println("Internal Findings: " + case22.getInternalFindings());
        case22.setDoctorOpinion("Dadri beef lynching");
        System.out.println("Doctor Opinion: " + case22.getDoctorOpinion());
        System.out.println();

        PostMortemReport case23 = new PostMortemReport();
        case23.setCaseId(23);
        System.out.println("Case ID: " + case23.getCaseId());
        case23.setDeceasedName("Pehlu Khan");
        System.out.println("Deceased: " + case23.getDeceasedName());
        case23.setDateOfDeath("2017-04-01");
        System.out.println("Date of Death: " + case23.getDateOfDeath());
        case23.setCauseOfDeath("Cow Vigilante Attack");
        System.out.println("Cause: " + case23.getCauseOfDeath());
        case23.setExternalInjuries("Multiple fractures, bruises");
        System.out.println("External Injuries: " + case23.getExternalInjuries());
        case23.setInternalFindings("Internal bleeding");
        System.out.println("Internal Findings: " + case23.getInternalFindings());
        case23.setDoctorOpinion("Rajasthan mob violence");
        System.out.println("Doctor Opinion: " + case23.getDoctorOpinion());
        System.out.println();

        PostMortemReport case24 = new PostMortemReport();
        case24.setCaseId(24);
        System.out.println("Case ID: " + case24.getCaseId());
        case24.setDeceasedName("Tabrez Ansari");
        System.out.println("Deceased: " + case24.getDeceasedName());
        case24.setDateOfDeath("2019-06-18");
        System.out.println("Date of Death: " + case24.getDateOfDeath());
        case24.setCauseOfDeath("Mob Lynching");
        System.out.println("Cause: " + case24.getCauseOfDeath());
        case24.setExternalInjuries("Beaten with sticks 8 hrs");
        System.out.println("External Injuries: " + case24.getExternalInjuries());
        case24.setInternalFindings("Multiple organ failure");
        System.out.println("Internal Findings: " + case24.getInternalFindings());
        case24.setDoctorOpinion("Jharkhand mob torture");
        System.out.println("Doctor Opinion: " + case24.getDoctorOpinion());
        System.out.println();

        PostMortemReport case25 = new PostMortemReport();
        case25.setCaseId(25);
        System.out.println("Case ID: " + case25.getCaseId());
        case25.setDeceasedName("Gauri Lankesh");
        System.out.println("Deceased: " + case25.getDeceasedName());
        case25.setDateOfDeath("2017-09-05");
        System.out.println("Date of Death: " + case25.getDateOfDeath());
        case25.setCauseOfDeath("Gunshot Wounds");
        System.out.println("Cause: " + case25.getCauseOfDeath());
        case25.setExternalInjuries("3 bullets to chest/head");
        System.out.println("External Injuries: " + case25.getExternalInjuries());
        case25.setInternalFindings("Cardio-pulmonary arrest");
        System.out.println("Internal Findings: " + case25.getInternalFindings());
        case25.setDoctorOpinion("Journalist assassination");
        System.out.println("Doctor Opinion: " + case25.getDoctorOpinion());
        System.out.println();

        PostMortemReport case26 = new PostMortemReport();
        case26.setCaseId(26);
        System.out.println("Case ID: " + case26.getCaseId());
        case26.setDeceasedName("Judge Loya");
        System.out.println("Deceased: " + case26.getDeceasedName());
        case26.setDateOfDeath("2014-12-01");
        System.out.println("Date of Death: " + case26.getDateOfDeath());
        case26.setCauseOfDeath("Heart Attack (Disputed)");
        System.out.println("Cause: " + case26.getCauseOfDeath());
        case26.setExternalInjuries("No external injuries");
        System.out.println("External Injuries: " + case26.getExternalInjuries());
        case26.setInternalFindings("Cardiac arrest");
        System.out.println("Internal Findings: " + case26.getInternalFindings());
        case26.setDoctorOpinion("Controversial judge death");
        System.out.println("Doctor Opinion: " + case26.getDoctorOpinion());
        System.out.println();

        PostMortemReport case27 = new PostMortemReport();
        case27.setCaseId(27);
        System.out.println("Case ID: " + case27.getCaseId());
        case27.setDeceasedName("Kalburgi");
        System.out.println("Deceased: " + case27.getDeceasedName());
        case27.setDateOfDeath("2015-08-30");
        System.out.println("Date of Death: " + case27.getDateOfDeath());
        case27.setCauseOfDeath("Gunshot Wound");
        System.out.println("Cause: " + case27.getCauseOfDeath());
        case27.setExternalInjuries("Single shot to face");
        System.out.println("External Injuries: " + case27.getExternalInjuries());
        case27.setInternalFindings("Instant death");
        System.out.println("Internal Findings: " + case27.getInternalFindings());
        case27.setDoctorOpinion("Rationalist killing");
        System.out.println("Doctor Opinion: " + case27.getDoctorOpinion());
        System.out.println();

        PostMortemReport case28 = new PostMortemReport();
        case28.setCaseId(28);
        System.out.println("Case ID: " + case28.getCaseId());
        case28.setDeceasedName("MM Kalburgi");
        System.out.println("Deceased: " + case28.getDeceasedName());
        case28.setDateOfDeath("2015-08-30");
        System.out.println("Date of Death: " + case28.getDateOfDeath());
        case28.setCauseOfDeath("Assassination");
        System.out.println("Cause: " + case28.getCauseOfDeath());
        case28.setExternalInjuries("Country-made gun shot");
        System.out.println("External Injuries: " + case28.getExternalInjuries());
        case28.setInternalFindings("Facial destruction");
        System.out.println("Internal Findings: " + case28.getInternalFindings());
        case28.setDoctorOpinion("Killer pistol case");
        System.out.println("Doctor Opinion: " + case28.getDoctorOpinion());
        System.out.println();

        PostMortemReport case29 = new PostMortemReport();
        case29.setCaseId(29);
        System.out.println("Case ID: " + case29.getCaseId());
        case29.setDeceasedName("Govind Pansare");
        System.out.println("Deceased: " + case29.getDeceasedName());
        case29.setDateOfDeath("2015-02-16");
        System.out.println("Date of Death: " + case29.getDateOfDeath());
        case29.setCauseOfDeath("Gunshot Wounds");
        System.out.println("Cause: " + case29.getCauseOfDeath());
        case29.setExternalInjuries("2 bullets to chest");
        System.out.println("External Injuries: " + case29.getExternalInjuries());
        case29.setInternalFindings("Excessive blood loss");
        System.out.println("Internal Findings: " + case29.getInternalFindings());
        case29.setDoctorOpinion("Leftist leader assassination");
        System.out.println("Doctor Opinion: " + case29.getDoctorOpinion());
        System.out.println();
    }
}