class RacketExecutor {
    public static void main(String[] args) {
        Racket r1 = new Racket(); r1.racketId=1001; r1.playerName="Srushti"; r1.brand="Yonex"; r1.model="ArcSaber11"; r1.matchesPlayed=45; r1.avgScore=78.2; r1.gripSize="G5"; r1.stringTension="24lbs"; r1.weightCategory="3U"; r1.balancePoint="HeadHeavy"; r1.material="HM Graphite"; r1.price=18900; r1.headShape="Isometric"; r1.durability=9.2; r1.color="Blue"; r1.shaftFlex=9; r1.playerLevel="Advanced"; r1.swingSpeed=85.6; r1.frameType="Box"; r1.warrantyYears=2;
        Racket r2 = new Racket(); r2.racketId=1002; r2.playerName="Ankit"; r2.brand="Victor"; r2.model="ThrusterK"; r2.matchesPlayed=32; r2.avgScore=82.1; r2.gripSize="G4"; r2.stringTension="26lbs"; r2.weightCategory="3U"; r2.balancePoint="EvenBalance"; r2.material="Carbon"; r2.price=16500; r2.headShape="Oval"; r2.durability=8.9; r2.color="Red"; r2.shaftFlex=10; r2.playerLevel="Pro"; r2.swingSpeed=92.3; r2.frameType="Slim"; r2.warrantyYears=1;
     
        Racket r3 = new Racket(); r3.racketId=1003; r3.playerName="Priya"; r3.brand="LiNing"; r3.model="TurboCharging"; r3.matchesPlayed=28; r3.avgScore=75.8; r3.gripSize="G5"; r3.stringTension="25lbs"; r3.weightCategory="4U"; r3.balancePoint="HeadLight"; r3.material="TB Nano"; r3.price=14200; r3.headShape="AeroTec"; r3.durability=9.1; r3.color="White"; r3.shaftFlex=8; r3.playerLevel="Intermediate"; r3.swingSpeed=78.4; r3.frameType="Aero"; r3.warrantyYears=2;

        Racket r4 = new Racket(); r4.racketId=1004; r4.playerName="Rahul"; r4.brand="Yonex"; r4.model="Nanoflare700"; r4.matchesPlayed=52; r4.avgScore=84.3; r4.gripSize="G4"; r4.stringTension="27lbs"; r4.weightCategory="3U"; r4.balancePoint="HeadLight"; r4.material="NanocellNeo"; r4.price=19800; r4.headShape="Isometric"; r4.durability=9.4; r4.color="Yellow"; r4.shaftFlex=11; r4.playerLevel="Pro"; r4.swingSpeed=94.2; r4.frameType="Sonic"; r4.warrantyYears=1;

        Racket r5 = new Racket(); r5.racketId=1005; r5.playerName="Neha"; r5.brand="Apacs"; r5.model="VirgoPro"; r5.matchesPlayed=38; r5.avgScore=79.6; r5.gripSize="G5"; r5.stringTension="23lbs"; r5.weightCategory="4U"; r5.balancePoint="EvenBalance"; r5.material="HighModulusGraphite"; r5.price=12500; r5.headShape="Oval"; r5.durability=8.7; r5.color="Purple"; r5.shaftFlex=9; r5.playerLevel="Advanced"; r5.swingSpeed=87.1; r5.frameType="Box"; r5.warrantyYears=1;
 
System.out.println("Racket r1 ID: " + r1.racketId + " Player: " + r1.playerName + " Brand: " + r1.brand + " Model: " + r1.model + " Matches: " + r1.matchesPlayed + " Avg: " + r1.avgScore + " Grip: " + r1.gripSize + " Tension: " + r1.stringTension + " Weight: " + r1.weightCategory + " Balance: " + r1.balancePoint + " Material: " + r1.material + " Price: " + r1.price + " Head: " + r1.headShape + " Durability: " + r1.durability + " Color: " + r1.color + " Flex: " + r1.shaftFlex + " Level: " + r1.playerLevel + " SwingSpeed: " + r1.swingSpeed + " Frame: " + r1.frameType + " Warranty: " + r1.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket r2 ID: " + r2.racketId + " Player: " + r2.playerName + " Brand: " + r2.brand + " Model: " + r2.model + " Matches: " + r2.matchesPlayed + " Avg: " + r2.avgScore + " Grip: " + r2.gripSize + " Tension: " + r2.stringTension + " Weight: " + r2.weightCategory + " Balance: " + r2.balancePoint + " Material: " + r2.material + " Price: " + r2.price + " Head: " + r2.headShape + " Durability: " + r2.durability + " Color: " + r2.color + " Flex: " + r2.shaftFlex + " Level: " + r2.playerLevel + " SwingSpeed: " + r2.swingSpeed + " Frame: " + r2.frameType + " Warranty: " + r2.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket r3 ID: " + r3.racketId + " Player: " + r3.playerName + " Brand: " + r3.brand + " Model: " + r3.model + " Matches: " + r3.matchesPlayed + " Avg: " + r3.avgScore + " Grip: " + r3.gripSize + " Tension: " + r3.stringTension + " Weight: " + r3.weightCategory + " Balance: " + r3.balancePoint + " Material: " + r3.material + " Price: " + r3.price + " Head: " + r3.headShape + " Durability: " + r3.durability + " Color: " + r3.color + " Flex: " + r3.shaftFlex + " Level: " + r3.playerLevel + " SwingSpeed: " + r3.swingSpeed + " Frame: " + r3.frameType + " Warranty: " + r3.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket r4 ID: " + r4.racketId + " Player: " + r4.playerName + " Brand: " + r4.brand + " Model: " + r4.model + " Matches: " + r4.matchesPlayed + " Avg: " + r4.avgScore + " Grip: " + r4.gripSize + " Tension: " + r4.stringTension + " Weight: " + r4.weightCategory + " Balance: " + r4.balancePoint + " Material: " + r4.material + " Price: " + r4.price + " Head: " + r4.headShape + " Durability: " + r4.durability + " Color: " + r4.color + " Flex: " + r4.shaftFlex + " Level: " + r4.playerLevel + " SwingSpeed: " + r4.swingSpeed + " Frame: " + r4.frameType + " Warranty: " + r4.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket r5 ID: " + r5.racketId + " Player: " + r5.playerName + " Brand: " + r5.brand + " Model: " + r5.model + " Matches: " + r5.matchesPlayed + " Avg: " + r5.avgScore + " Grip: " + r5.gripSize + " Tension: " + r5.stringTension + " Weight: " + r5.weightCategory + " Balance: " + r5.balancePoint + " Material: " + r5.material + " Price: " + r5.price + " Head: " + r5.headShape + " Durability: " + r5.durability + " Color: " + r5.color + " Flex: " + r5.shaftFlex + " Level: " + r5.playerLevel + " SwingSpeed: " + r5.swingSpeed + " Frame: " + r5.frameType + " Warranty: " + r5.warrantyYears + " yrs");
System.out.println();
 
 Racket p1 = new Racket(1001,"Srushti","Yonex","ArcSaber11",45,78.2,"G5","24lbs","3U","HeadHeavy","HM Graphite",18900,"Isometric",9.2,"Blue",9,"Advanced",85.6,"Box",2);
Racket p2 = new Racket(1002,"Ankit","Victor","ThrusterK",32,82.1,"G4","26lbs","3U","EvenBalance","Carbon",16500,"Oval",8.9,"Red",10,"Pro",92.3,"Slim",1);     
Racket p3 = new Racket(1003,"Priya","LiNing","TurboCharging",28,75.8,"G5","25lbs","4U","HeadLight","TB Nano",14200,"AeroTec",9.1,"White",8,"Intermediate",78.4,"Aero",2);
Racket p4 = new Racket(1004,"Rahul","Yonex","Nanoflare700",52,84.3,"G4","27lbs","3U","HeadLight","NanocellNeo",19800,"Isometric",9.4,"Yellow",11,"Pro",94.2,"Sonic",1);
Racket p5 = new Racket(1005,"Neha","Apacs","VirgoPro",38,79.6,"G5","23lbs","4U","EvenBalance","HighModulusGraphite",12500,"Oval",8.7,"Purple",9,"Advanced",87.1,"Box",1);

 
 System.out.println("Racket p1 ID: " + p1.racketId + " Player: " + p1.playerName + " Brand: " + p1.brand + " Model: " + p1.model + " Matches: " + p1.matchesPlayed + " Avg: " + p1.avgScore + " Grip: " + p1.gripSize + " Tension: " + p1.stringTension + " Weight: " + p1.weightCategory + " Balance: " + p1.balancePoint + " Material: " + p1.material + " Price: " + p1.price + " Head: " + p1.headShape + " Durability: " + p1.durability + " Color: " + p1.color + " Flex: " + p1.shaftFlex + " Level: " + p1.playerLevel + " SwingSpeed: " + p1.swingSpeed + " Frame: " + p1.frameType + " Warranty: " + p1.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket p2 ID: " + p2.racketId + " Player: " + p2.playerName + " Brand: " + p2.brand + " Model: " + p2.model + " Matches: " + p2.matchesPlayed + " Avg: " + p2.avgScore + " Grip: " + p2.gripSize + " Tension: " + p2.stringTension + " Weight: " + p2.weightCategory + " Balance: " + p2.balancePoint + " Material: " + p2.material + " Price: " + p2.price + " Head: " + p2.headShape + " Durability: " + p2.durability + " Color: " + p2.color + " Flex: " + p2.shaftFlex + " Level: " + p2.playerLevel + " SwingSpeed: " + p2.swingSpeed + " Frame: " + p2.frameType + " Warranty: " + p2.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket p3 ID: " + p3.racketId + " Player: " + p3.playerName + " Brand: " + p3.brand + " Model: " + p3.model + " Matches: " + p3.matchesPlayed + " Avg: " + p3.avgScore + " Grip: " + p3.gripSize + " Tension: " + p3.stringTension + " Weight: " + p3.weightCategory + " Balance: " + p3.balancePoint + " Material: " + p3.material + " Price: " + p3.price + " Head: " + p3.headShape + " Durability: " + p3.durability + " Color: " + p3.color + " Flex: " + p3.shaftFlex + " Level: " + p3.playerLevel + " SwingSpeed: " + p3.swingSpeed + " Frame: " + p3.frameType + " Warranty: " + p3.warrantyYears + " yrs");
System.out.println();
System.out.println("Racket p4 ID: " + p4.racketId + " Player: " + p4.playerName + " Brand: " + p4.brand + " Model: " + p4.model + " Matches: " + p4.matchesPlayed + " Avg: " + p4.avgScore + " Grip: " + p4.gripSize + " Tension: " + p4.stringTension + " Weight: " + p4.weightCategory + " Balance: " + p4.balancePoint + " Material: " + p4.material + " Price: " + p4.price + " Head: " + p4.headShape + " Durability: " + p4.durability + " Color: " + p4.color + " Flex: " + p4.shaftFlex + " Level: " + p4.playerLevel + " SwingSpeed: " + p4.swingSpeed + " Frame: " + p4.frameType + " Warranty: " + p4.warrantyYears + " yrs");
System.out.println();

    }
}
