class SareeExecutor {
    public static void main(String[] args) {

        Saree saree1 = new Saree();
        
        saree1.itemCode = 2001;
        saree1.unitPrice = 8999.99;
        saree1.hypoAllergenic = true;
        saree1.inStock = true;
        saree1.purchaseDate = "05/03/2026";
        saree1.warrantyEnd = "05/03/2028";
        saree1.warrantyValid = true;
        saree1.brand = "KVK";
        saree1.material = "Pure Kanjivaram Silk";
        saree1.size = "5.5 Yards";
        saree1.color = "Green-Gold Zari";
        saree1.threadCount = 1200;
        saree1.weaveType = "Kanchipuram Korvai";
        saree1.fittedSheet = false;
        saree1.pillowCaseCount = 0;
        saree1.weight = 0.65;
        saree1.careInstructions = "Dry Clean Only";
        saree1.machineWashable = false;
        saree1.fabricQuality = "Temple Silk";
        saree1.gsm = 85;
        saree1.wrinkleResistant = false;
        saree1.patternDesign = "Traditional Temple";
        saree1.organicCotton = false;
        saree1.collectionName = "Wedding Collection";
        saree1.discountPrice = 7499.99;
        saree1.storageMethod = "Silk Moth Repellent Pouch";
        
        System.out.println("Item Code: " + saree1.itemCode);
        System.out.println("Unit Price: " + saree1.unitPrice);
        System.out.println("Hypo Allergenic: " + saree1.hypoAllergenic);
        System.out.println("In Stock: " + saree1.inStock);
        System.out.println("Purchase Date: " + saree1.purchaseDate);
        System.out.println("Warranty Ends: " + saree1.warrantyEnd);
        System.out.println("Warranty Valid: " + saree1.warrantyValid);
        System.out.println("Brand: " + saree1.brand);
        System.out.println("Material: " + saree1.material);
        System.out.println("Size: " + saree1.size);
        System.out.println("Color: " + saree1.color);
        System.out.println("Thread Count: " + saree1.threadCount);
        System.out.println("Weave Type: " + saree1.weaveType);
        System.out.println("Fitted Sheet: " + saree1.fittedSheet);
        System.out.println("Pillow Case Count: " + saree1.pillowCaseCount);
        System.out.println("Weight: " + saree1.weight + "kg");
        System.out.println("Care Instructions: " + saree1.careInstructions);
        System.out.println("Machine Washable: " + saree1.machineWashable);
        System.out.println("Fabric Quality: " + saree1.fabricQuality);
        System.out.println("GSM: " + saree1.gsm);
        System.out.println("Wrinkle Resistant: " + saree1.wrinkleResistant);
        System.out.println("Pattern Design: " + saree1.patternDesign);
        System.out.println("Organic Cotton: " + saree1.organicCotton);
        System.out.println("Collection Name: " + saree1.collectionName);
        System.out.println("Discount Price: " + saree1.discountPrice);
        System.out.println("Storage Method: " + saree1.storageMethod);
        System.out.println("-----------------------------");
		
		
        Saree saree2 = new Saree();
        saree2.itemCode = 2002;
        saree2.unitPrice = 12999.99;
        saree2.hypoAllergenic = true;
        saree2.inStock = true;
        saree2.purchaseDate = "05/03/2026";
        saree2.warrantyEnd = "05/03/2028";
        saree2.warrantyValid = true;
        saree2.brand = "Ilkal Weavers";
        saree2.material = "Mulberry Silk x Cotton";
        saree2.size = "6.3 Yards";
        saree2.color = "Red-Gold Tope Teni";
        saree2.threadCount = 1000;
        saree2.weaveType = "Ilkal Tope Teni";
        saree2.fittedSheet = false;
        saree2.pillowCaseCount = 0;
        saree2.weight = 0.52;
        saree2.careInstructions = "Dry Clean Only";
        saree2.machineWashable = false;
        saree2.fabricQuality = "GI Tagged Ilkal";
        saree2.gsm = 92;
        saree2.wrinkleResistant = true;
        saree2.patternDesign = "Temple Border";
        saree2.organicCotton = true;
        saree2.collectionName = "Heritage Collection";
        saree2.discountPrice = 10999.99;
        saree2.storageMethod = "Anti-Tarnish Silk Box";
        
        System.out.println("Item Code: " + saree2.itemCode);
        System.out.println("Unit Price: " + saree2.unitPrice);
        System.out.println("Hypo Allergenic: " + saree2.hypoAllergenic);
        System.out.println("In Stock: " + saree2.inStock);
        System.out.println("Purchase Date: " + saree2.purchaseDate);
        System.out.println("Warranty Ends: " + saree2.warrantyEnd);
        System.out.println("Warranty Valid: " + saree2.warrantyValid);
        System.out.println("Brand: " + saree2.brand);
        System.out.println("Material: " + saree2.material);
        System.out.println("Size: " + saree2.size);
        System.out.println("Color: " + saree2.color);
        System.out.println("Thread Count: " + saree2.threadCount);
        System.out.println("Weave Type: " + saree2.weaveType);
        System.out.println("Fitted Sheet: " + saree2.fittedSheet);
        System.out.println("Pillow Case Count: " + saree2.pillowCaseCount);
        System.out.println("Weight: " + saree2.weight + "kg");
        System.out.println("Care Instructions: " + saree2.careInstructions);
        System.out.println("Machine Washable: " + saree2.machineWashable);
        System.out.println("Fabric Quality: " + saree2.fabricQuality);
        System.out.println("GSM: " + saree2.gsm);
        System.out.println("Wrinkle Resistant: " + saree2.wrinkleResistant);
        System.out.println("Pattern Design: " + saree2.patternDesign);
        System.out.println("Organic Cotton: " + saree2.organicCotton);
        System.out.println("Collection Name: " + saree2.collectionName);
        System.out.println("Discount Price: " + saree2.discountPrice);
        System.out.println("Storage Method: " + saree2.storageMethod);
        System.out.println("-----------------------------");

        Saree saree3 = new Saree();
        saree3.itemCode = 2003;
        saree3.unitPrice = 15999.99;
        saree3.hypoAllergenic = true;
        saree3.inStock = true;
        saree3.purchaseDate = "05/03/2026";
        saree3.warrantyEnd = "05/03/2029";
        saree3.warrantyValid = true;
        saree3.brand = "Mysore Pattu";
        saree3.material = "Pure Mulberry Crepe Silk";
        saree3.size = "6.25 Yards";
        saree3.color = "Magenta-Purple Checks";
        saree3.threadCount = 1400;
        saree3.weaveType = "Mysore Crepe Weave";
        saree3.fittedSheet = false;
        saree3.pillowCaseCount = 0;
        saree3.weight = 0.48;
        saree3.careInstructions = "Dry Clean Shade Dry";
        saree3.machineWashable = false;
        saree3.fabricQuality = "KSIC Certified";
        saree3.gsm = 78;
        saree3.wrinkleResistant = true;
        saree3.patternDesign = "Ganda Berunda Pallu";
        saree3.organicCotton = false;
        saree3.collectionName = "Royal Heritage";
        saree3.discountPrice = 13599.99;
        saree3.storageMethod = "Hermetic Silk Vault";
        
        System.out.println("Item Code: " + saree3.itemCode);
        System.out.println("Unit Price: " + saree3.unitPrice);
        System.out.println("Hypo Allergenic: " + saree3.hypoAllergenic);
        System.out.println("In Stock: " + saree3.inStock);
        System.out.println("Purchase Date: " + saree3.purchaseDate);
        System.out.println("Warranty Ends: " + saree3.warrantyEnd);
        System.out.println("Warranty Valid: " + saree3.warrantyValid);
        System.out.println("Brand: " + saree3.brand);
        System.out.println("Material: " + saree3.material);
        System.out.println("Size: " + saree3.size);
        System.out.println("Color: " + saree3.color);
        System.out.println("Thread Count: " + saree3.threadCount);
        System.out.println("Weave Type: " + saree3.weaveType);
        System.out.println("Fitted Sheet: " + saree3.fittedSheet);
        System.out.println("Pillow Case Count: " + saree3.pillowCaseCount);
        System.out.println("Weight: " + saree3.weight + "kg");
        System.out.println("Care Instructions: " + saree3.careInstructions);
        System.out.println("Machine Washable: " + saree3.machineWashable);
        System.out.println("Fabric Quality: " + saree3.fabricQuality);
        System.out.println("GSM: " + saree3.gsm);
        System.out.println("Wrinkle Resistant: " + saree3.wrinkleResistant);
        System.out.println("Pattern Design: " + saree3.patternDesign);
        System.out.println("Organic Cotton: " + saree3.organicCotton);
        System.out.println("Collection Name: " + saree3.collectionName);
        System.out.println("Discount Price: " + saree3.discountPrice);
        System.out.println("Storage Method: " + saree3.storageMethod);
        System.out.println("-----------------------------");

        Saree saree4 = new Saree();
        saree4.itemCode = 2004;
        saree4.unitPrice = 11500.99;
        saree4.hypoAllergenic = true;
        saree4.inStock = true;
        saree4.purchaseDate = "05/03/2026";
        saree4.warrantyEnd = "05/03/2028";
        saree4.warrantyValid = true;
        saree4.brand = "Molakalmuru Co-op";
        saree4.material = "Mulberry Silk Blend";
        saree4.size = "6 Yards";
        saree4.color = "Maroon-Silver Zari";
        saree4.threadCount = 1100;
        saree4.weaveType = "Molakalmuru Double Warp";
        saree4.fittedSheet = false;
        saree4.pillowCaseCount = 0;
        saree4.weight = 0.58;
        saree4.careInstructions = "Dry Clean Only";
        saree4.machineWashable = false;
        saree4.fabricQuality = "Handloom Mark Certified";
        saree4.gsm = 88;
        saree4.wrinkleResistant = true;
        saree4.patternDesign = "Floral Jaal";
        saree4.organicCotton = true;
        saree4.collectionName = "Artisan Special";
        saree4.discountPrice = 9799.99;
        saree4.storageMethod = "Cedar Wood Silk Box";
        
        System.out.println("Item Code: " + saree4.itemCode);
        System.out.println("Unit Price: " + saree4.unitPrice);
        System.out.println("Hypo Allergenic: " + saree4.hypoAllergenic);
        System.out.println("In Stock: " + saree4.inStock);
        System.out.println("Purchase Date: " + saree4.purchaseDate);
        System.out.println("Warranty Ends: " + saree4.warrantyEnd);
        System.out.println("Warranty Valid: " + saree4.warrantyValid);
        System.out.println("Brand: " + saree4.brand);
        System.out.println("Material: " + saree4.material);
        System.out.println("Size: " + saree4.size);
        System.out.println("Color: " + saree4.color);
        System.out.println("Thread Count: " + saree4.threadCount);
        System.out.println("Weave Type: " + saree4.weaveType);
        System.out.println("Fitted Sheet: " + saree4.fittedSheet);
        System.out.println("Pillow Case Count: " + saree4.pillowCaseCount);
        System.out.println("Weight: " + saree4.weight + "kg");
        System.out.println("Care Instructions: " + saree4.careInstructions);
        System.out.println("Machine Washable: " + saree4.machineWashable);
        System.out.println("Fabric Quality: " + saree4.fabricQuality);
        System.out.println("GSM: " + saree4.gsm);
        System.out.println("Wrinkle Resistant: " + saree4.wrinkleResistant);
        System.out.println("Pattern Design: " + saree4.patternDesign);
        System.out.println("Organic Cotton: " + saree4.organicCotton);
        System.out.println("Collection Name: " + saree4.collectionName);
        System.out.println("Discount Price: " + saree4.discountPrice);
        System.out.println("Storage Method: " + saree4.storageMethod);
        System.out.println("-----------------------------");

        Saree saree5 = new Saree();
        saree5.itemCode = 2005;
        saree5.unitPrice = 6899.99;
        saree5.hypoAllergenic = true;
        saree5.inStock = true;
        saree5.purchaseDate = "05/03/2026";
        saree5.warrantyEnd = "05/03/2027";
        saree5.warrantyValid = true;
        saree5.brand = "Dharwad Kasuti";
        saree5.material = "100% Organic Cotton";
        saree5.size = "5.8 Yards";
        saree5.color = "Navy Blue-White";
        saree5.threadCount = 180;
        saree5.weaveType = "Kasuti Embroidery";
        saree5.fittedSheet = false;
        saree5.pillowCaseCount = 0;
        saree5.weight = 0.42;
        saree5.careInstructions = "Hand Wash Cold";
        saree5.machineWashable = true;
        saree5.fabricQuality = "Handwoven Cotton";
        saree5.gsm = 140;
        saree5.wrinkleResistant = false;
        saree5.patternDesign = "Gadisuga-Muggu Motifs";
        saree5.organicCotton = true;
        saree5.collectionName = "Daily Wear";
        saree5.discountPrice = 5899.99;
        saree5.storageMethod = "Cotton Breathable Pouch";
        
        System.out.println("Item Code: " + saree5.itemCode);
        System.out.println("Unit Price: " + saree5.unitPrice);
        System.out.println("Hypo Allergenic: " + saree5.hypoAllergenic);
        System.out.println("In Stock: " + saree5.inStock);
        System.out.println("Purchase Date: " + saree5.purchaseDate);
        System.out.println("Warranty Ends: " + saree5.warrantyEnd);
        System.out.println("Warranty Valid: " + saree5.warrantyValid);
        System.out.println("Brand: " + saree5.brand);
        System.out.println("Material: " + saree5.material);
        System.out.println("Size: " + saree5.size);
        System.out.println("Color: " + saree5.color);
        System.out.println("Thread Count: " + saree5.threadCount);
        System.out.println("Weave Type: " + saree5.weaveType);
        System.out.println("Fitted Sheet: " + saree5.fittedSheet);
        System.out.println("Pillow Case Count: " + saree5.pillowCaseCount);
        System.out.println("Weight: " + saree5.weight + "kg");
        System.out.println("Care Instructions: " + saree5.careInstructions);
        System.out.println("Machine Washable: " + saree5.machineWashable);
        System.out.println("Fabric Quality: " + saree5.fabricQuality);
        System.out.println("GSM: " + saree5.gsm);
        System.out.println("Wrinkle Resistant: " + saree5.wrinkleResistant);
        System.out.println("Pattern Design: " + saree5.patternDesign);
        System.out.println("Organic Cotton: " + saree5.organicCotton);
        System.out.println("Collection Name: " + saree5.collectionName);
        System.out.println("Discount Price: " + saree5.discountPrice);
        System.out.println("Storage Method: " + saree5.storageMethod);
        System.out.println("-----------------------------");


        Saree saree6 = new Saree();
        saree6.itemCode = 2006;
        saree6.unitPrice = 9500.99;
        saree6.hypoAllergenic = true;
        saree6.inStock = true;
        saree6.purchaseDate = "05/03/2026";
        saree6.warrantyEnd = "05/03/2028";
        saree6.warrantyValid = true;
        saree6.brand = "Venkatagiri Weavers";
        saree6.material = "Cotton Silk Blend";
        saree6.size = "6 Yards";
        saree6.color = "Peacock Blue-Silver";
        saree6.threadCount = 950;
        saree6.weaveType = "Venkatagiri Fine Count";
        saree6.fittedSheet = false;
        saree6.pillowCaseCount = 0;
        saree6.weight = 0.45;
        saree6.careInstructions = "Dry Clean Shade Dry";
        saree6.machineWashable = false;
        saree6.fabricQuality = "Temple Border Silk";
        saree6.gsm = 96;
        saree6.wrinkleResistant = true;
        saree6.patternDesign = "Floral Buttis";
        saree6.organicCotton = true;
        saree6.collectionName = "Bridal Collection";
        saree6.discountPrice = 7999.99;
        saree6.storageMethod = "Silk Preservation Box";
        
        System.out.println("Item Code: " + saree6.itemCode);
        System.out.println("Unit Price: " + saree6.unitPrice);
        System.out.println("Hypo Allergenic: " + saree6.hypoAllergenic);
        System.out.println("In Stock: " + saree6.inStock);
        System.out.println("Purchase Date: " + saree6.purchaseDate);
        System.out.println("Warranty Ends: " + saree6.warrantyEnd);
        System.out.println("Warranty Valid: " + saree6.warrantyValid);
        System.out.println("Brand: " + saree6.brand);
        System.out.println("Material: " + saree6.material);
        System.out.println("Size: " + saree6.size);
        System.out.println("Color: " + saree6.color);
        System.out.println("Thread Count: " + saree6.threadCount);
        System.out.println("Weave Type: " + saree6.weaveType);
        System.out.println("Fitted Sheet: " + saree6.fittedSheet);
        System.out.println("Pillow Case Count: " + saree6.pillowCaseCount);
        System.out.println("Weight: " + saree6.weight + "kg");
        System.out.println("Care Instructions: " + saree6.careInstructions);
        System.out.println("Machine Washable: " + saree6.machineWashable);
        System.out.println("Fabric Quality: " + saree6.fabricQuality);
        System.out.println("GSM: " + saree6.gsm);
        System.out.println("Wrinkle Resistant: " + saree6.wrinkleResistant);
        System.out.println("Pattern Design: " + saree6.patternDesign);
        System.out.println("Organic Cotton: " + saree6.organicCotton);
        System.out.println("Collection Name: " + saree6.collectionName);
        System.out.println("Discount Price: " + saree6.discountPrice);
        System.out.println("Storage Method: " + saree6.storageMethod);
        System.out.println("-----------------------------");

        Saree saree7 = new Saree();
        saree7.itemCode = 2007;
        saree7.unitPrice = 13999.99;
        saree7.hypoAllergenic = true;
        saree7.inStock = true;
        saree7.purchaseDate = "05/03/2026";
        saree7.warrantyEnd = "05/03/2029";
        saree7.warrantyValid = true;
        saree7.brand = "Channapatna Silk";
        saree7.material = "Pure Bomkai Silk";
        saree7.size = "6.2 Yards";
        saree7.color = "Royal Purple-Gold";
        saree7.threadCount = 1300;
        saree7.weaveType = "Channapatna Brocade";
        saree7.fittedSheet = false;
        saree7.pillowCaseCount = 0;
        saree7.weight = 0.62;
        saree7.careInstructions = "Dry Clean Only";
        saree7.machineWashable = false;
        saree7.fabricQuality = "Art Silk Brocade";
        saree7.gsm = 82;
        saree7.wrinkleResistant = false;
        saree7.patternDesign = "Peacock Motifs";
        saree7.organicCotton = false;
        saree7.collectionName = "Royal Wedding";
        saree7.discountPrice = 11999.99;
        saree7.storageMethod = "Velvet Lined Box";
        
        System.out.println("Item Code: " + saree7.itemCode);
        System.out.println("Unit Price: " + saree7.unitPrice);
        System.out.println("Hypo Allergenic: " + saree7.hypoAllergenic);
        System.out.println("In Stock: " + saree7.inStock);
        System.out.println("Purchase Date: " + saree7.purchaseDate);
        System.out.println("Warranty Ends: " + saree7.warrantyEnd);
        System.out.println("Warranty Valid: " + saree7.warrantyValid);
        System.out.println("Brand: " + saree7.brand);
        System.out.println("Material: " + saree7.material);
        System.out.println("Size: " + saree7.size);
        System.out.println("Color: " + saree7.color);
        System.out.println("Thread Count: " + saree7.threadCount);
        System.out.println("Weave Type: " + saree7.weaveType);
        System.out.println("Fitted Sheet: " + saree7.fittedSheet);
        System.out.println("Pillow Case Count: " + saree7.pillowCaseCount);
        System.out.println("Weight: " + saree7.weight + "kg");
        System.out.println("Care Instructions: " + saree7.careInstructions);
        System.out.println("Machine Washable: " + saree7.machineWashable);
        System.out.println("Fabric Quality: " + saree7.fabricQuality);
        System.out.println("GSM: " + saree7.gsm);
        System.out.println("Wrinkle Resistant: " + saree7.wrinkleResistant);
        System.out.println("Pattern Design: " + saree7.patternDesign);
        System.out.println("Organic Cotton: " + saree7.organicCotton);
        System.out.println("Collection Name: " + saree7.collectionName);
        System.out.println("Discount Price: " + saree7.discountPrice);
        System.out.println("Storage Method: " + saree7.storageMethod);
        System.out.println("-----------------------------");

		
        Saree saree8 = new Saree();
        saree8.itemCode = 2008;
        saree8.unitPrice = 7200.99;
        saree8.hypoAllergenic = true;
        saree8.inStock = true;
        saree8.purchaseDate = "05/03/2026";
        saree8.warrantyEnd = "05/03/2027";
        saree8.warrantyValid = true;
        saree8.brand = "Gadag Handlooms";
        saree8.material = "Fine Cotton";
        saree8.size = "5.9 Yards";
        saree8.color = "Saffron-Yellow";
        saree8.threadCount = 120;
        saree8.weaveType = "Gadag Plain Weave";
        saree8.fittedSheet = false;
        saree8.pillowCaseCount = 0;
        saree8.weight = 0.38;
        saree8.careInstructions = "Gentle Machine Wash";
        saree8.machineWashable = true;
        saree8.fabricQuality = "Khadi Certified";
        saree8.gsm = 125;
        saree8.wrinkleResistant = false;
        saree8.patternDesign = "Temple Stripes";
        saree8.organicCotton = true;
        saree8.collectionName = "Everyday Elegant";
        saree8.discountPrice = 6299.99;
        saree8.storageMethod = "Breathable Cotton Bag";
        
        System.out.println("Item Code: " + saree8.itemCode);
        System.out.println("Unit Price: " + saree8.unitPrice);
        System.out.println("Hypo Allergenic: " + saree8.hypoAllergenic);
        System.out.println("In Stock: " + saree8.inStock);
        System.out.println("Purchase Date: " + saree8.purchaseDate);
        System.out.println("Warranty Ends: " + saree8.warrantyEnd);
        System.out.println("Warranty Valid: " + saree8.warrantyValid);
        System.out.println("Brand: " + saree8.brand);
        System.out.println("Material: " + saree8.material);
        System.out.println("Size: " + saree8.size);
        System.out.println("Color: " + saree8.color);
        System.out.println("Thread Count: " + saree8.threadCount);
        System.out.println("Weave Type: " + saree8.weaveType);
        System.out.println("Fitted Sheet: " + saree8.fittedSheet);
        System.out.println("Pillow Case Count: " + saree8.pillowCaseCount);
        System.out.println("Weight: " + saree8.weight + "kg");
        System.out.println("Care Instructions: " + saree8.careInstructions);
        System.out.println("Machine Washable: " + saree8.machineWashable);
        System.out.println("Fabric Quality: " + saree8.fabricQuality);
        System.out.println("GSM: " + saree8.gsm);
        System.out.println("Wrinkle Resistant: " + saree8.wrinkleResistant);
        System.out.println("Pattern Design: " + saree8.patternDesign);
        System.out.println("Organic Cotton: " + saree8.organicCotton);
        System.out.println("Collection Name: " + saree8.collectionName);
        System.out.println("Discount Price: " + saree8.discountPrice);
        System.out.println("Storage Method: " + saree8.storageMethod);
        System.out.println("-----------------------------");

        Saree saree9 = new Saree();
        saree9.itemCode = 2009;
        saree9.unitPrice = 10899.99;
        saree9.hypoAllergenic = true;
        saree9.inStock = true;
        saree9.purchaseDate = "05/03/2026";
        saree9.warrantyEnd = "05/03/2028";
        saree9.warrantyValid = true;
        saree9.brand = "Belgaum Silk House";
        saree9.material = "Pure Tussar Silk";
        saree9.size = "6.1 Yards";
        saree9.color = "Emerald Green-Blue";
        saree9.threadCount = 1050;
        saree9.weaveType = "Belgaum Tussar Weave";
        saree9.fittedSheet = false;
        saree9.pillowCaseCount = 0;
        saree9.weight = 0.55;
        saree9.careInstructions = "Dry Clean Only";
        saree9.machineWashable = false;
        saree9.fabricQuality = "Tussar Silk Excellence";
        saree9.gsm = 90;
        saree9.wrinkleResistant = true;
        saree9.patternDesign = "Pechki Border";
        saree9.organicCotton = false;
        saree9.collectionName = "Festive Collection";
        saree9.discountPrice = 9299.99;
        saree9.storageMethod = "Silk Moth Guard Pouch";
        
        System.out.println("Item Code: " + saree9.itemCode);
        System.out.println("Unit Price: " + saree9.unitPrice);
        System.out.println("Hypo Allergenic: " + saree9.hypoAllergenic);
        System.out.println("In Stock: " + saree9.inStock);
        System.out.println("Purchase Date: " + saree9.purchaseDate);
        System.out.println("Warranty Ends: " + saree9.warrantyEnd);
        System.out.println("Warranty Valid: " + saree9.warrantyValid);
        System.out.println("Brand: " + saree9.brand);
        System.out.println("Material: " + saree9.material);
        System.out.println("Size: " + saree9.size);
        System.out.println("Color: " + saree9.color);
        System.out.println("Thread Count: " + saree9.threadCount);
        System.out.println("Weave Type: " + saree9.weaveType);
        System.out.println("Fitted Sheet: " + saree9.fittedSheet);
        System.out.println("Pillow Case Count: " + saree9.pillowCaseCount);
        System.out.println("Weight: " + saree9.weight + "kg");
        System.out.println("Care Instructions: " + saree9.careInstructions);
        System.out.println("Machine Washable: " + saree9.machineWashable);
        System.out.println("Fabric Quality: " + saree9.fabricQuality);
        System.out.println("GSM: " + saree9.gsm);
        System.out.println("Wrinkle Resistant: " + saree9.wrinkleResistant);
        System.out.println("Pattern Design: " + saree9.patternDesign);
        System.out.println("Organic Cotton: " + saree9.organicCotton);
        System.out.println("Collection Name: " + saree9.collectionName);
        System.out.println("Discount Price: " + saree9.discountPrice);
        System.out.println("Storage Method: " + saree9.storageMethod);
        System.out.println("-----------------------------");

		
        Saree saree10 = new Saree();
        saree10.itemCode = 2010;
        saree10.unitPrice = 14500.99;
        saree10.hypoAllergenic = true;
        saree10.inStock = true;
        saree10.purchaseDate = "05/03/2026";
        saree10.warrantyEnd = "05/03/2029";
        saree10.warrantyValid = true;
        saree10.brand = "Narasapura Silk";
        saree10.material = "Pure Mulberry Sandalwood Silk";
        saree10.size = "6.3 Yards";
        saree10.color = "Sandalwood Cream-Gold";
        saree10.threadCount = 1350;
        saree10.weaveType = "Narasapura Plain Silk";
        saree10.fittedSheet = false;
        saree10.pillowCaseCount = 0;
        saree10.weight = 0.60;
        saree10.careInstructions = "Dry Clean Only";
        saree10.machineWashable = false;
        saree10.fabricQuality = "Sandalwood Scented";
        saree10.gsm = 84;
        saree10.wrinkleResistant = true;
        saree10.patternDesign = "Self Zari Stripe";
        saree10.organicCotton = false;
        saree10.collectionName = "Luxury Bridal";
        saree10.discountPrice = 12499.99;
        saree10.storageMethod = "Sandalwood Silk Case";
        
        System.out.println("Item Code: " + saree10.itemCode);
        System.out.println("Unit Price: " + saree10.unitPrice);
        System.out.println("Hypo Allergenic: " + saree10.hypoAllergenic);
        System.out.println("In Stock: " + saree10.inStock);
        System.out.println("Purchase Date: " + saree10.purchaseDate);
        System.out.println("Warranty Ends: " + saree10.warrantyEnd);
        System.out.println("Warranty Valid: " + saree10.warrantyValid);
        System.out.println("Brand: " + saree10.brand);
        System.out.println("Material: " + saree10.material);
        System.out.println("Size: " + saree10.size);
        System.out.println("Color: " + saree10.color);
        System.out.println("Thread Count: " + saree10.threadCount);
        System.out.println("Weave Type: " + saree10.weaveType);
        System.out.println("Fitted Sheet: " + saree10.fittedSheet);
        System.out.println("Pillow Case Count: " + saree10.pillowCaseCount);
        System.out.println("Weight: " + saree10.weight + "kg");
        System.out.println("Care Instructions: " + saree10.careInstructions);
        System.out.println("Machine Washable: " + saree10.machineWashable);
        System.out.println("Fabric Quality: " + saree10.fabricQuality);
        System.out.println("GSM: " + saree10.gsm);
        System.out.println("Wrinkle Resistant: " + saree10.wrinkleResistant);
        System.out.println("Pattern Design: " + saree10.patternDesign);
        System.out.println("Organic Cotton: " + saree10.organicCotton);
        System.out.println("Collection Name: " + saree10.collectionName);
        System.out.println("Discount Price: " + saree10.discountPrice);
        System.out.println("Storage Method: " + saree10.storageMethod);
        System.out.println("-----------------------------");

        Saree saree11 = new Saree();
        saree11.itemCode = 2011;
        saree11.unitPrice = 8299.99;
        saree11.hypoAllergenic = true;
        saree11.inStock = true;
        saree11.purchaseDate = "05/03/2026";
        saree11.warrantyEnd = "05/03/2028";
        saree11.warrantyValid = true;
        saree11.brand = "Sirsi Kasuti Artisans";
        saree11.material = "Organic Cotton Mulmul";
        saree11.size = "5.75 Yards";
        saree11.color = "Terracotta-Red";
        saree11.threadCount = 200;
        saree11.weaveType = "Kasuti Hand Embroidery";
        saree11.fittedSheet = false;
        saree11.pillowCaseCount = 0;
        saree11.weight = 0.35;
        saree11.careInstructions = "Hand Wash Gentle";
        saree11.machineWashable = true;
        saree11.fabricQuality = "Mulmul Fine Count";
        saree11.gsm = 110;
        saree11.wrinkleResistant = false;
        saree11.patternDesign = "Rangoli-Mercara Motifs";
        saree11.organicCotton = true;
        saree11.collectionName = "Artisan Heritage";
        saree11.discountPrice = 7299.99;
        saree11.storageMethod = "Handloom Muslin Wrap";
        
        System.out.println("Item Code: " + saree11.itemCode);
        System.out.println("Unit Price: " + saree11.unitPrice);
        System.out.println("Hypo Allergenic: " + saree11.hypoAllergenic);
        System.out.println("In Stock: " + saree11.inStock);
        System.out.println("Purchase Date: " + saree11.purchaseDate);
        System.out.println("Warranty Ends: " + saree11.warrantyEnd);
        System.out.println("Warranty Valid: " + saree11.warrantyValid);
        System.out.println("Brand: " + saree11.brand);
        System.out.println("Material: " + saree11.material);
        System.out.println("Size: " + saree11.size);
        System.out.println("Color: " + saree11.color);
        System.out.println("Thread Count: " + saree11.threadCount);
        System.out.println("Weave Type: " + saree11.weaveType);
        System.out.println("Fitted Sheet: " + saree11.fittedSheet);
        System.out.println("Pillow Case Count: " + saree11.pillowCaseCount);
        System.out.println("Weight: " + saree11.weight + "kg");
        System.out.println("Care Instructions: " + saree11.careInstructions);
        System.out.println("Machine Washable: " + saree11.machineWashable);
        System.out.println("Fabric Quality: " + saree11.fabricQuality);
        System.out.println("GSM: " + saree11.gsm);
        System.out.println("Wrinkle Resistant: " + saree11.wrinkleResistant);
        System.out.println("Pattern Design: " + saree11.patternDesign);
        System.out.println("Organic Cotton: " + saree11.organicCotton);
        System.out.println("Collection Name: " + saree11.collectionName);
        System.out.println("Discount Price: " + saree11.discountPrice);
        System.out.println("Storage Method: " + saree11.storageMethod);
        System.out.println("-----------------------------");


        Saree saree12 = new Saree();
        saree12.itemCode = 2012;
        saree12.unitPrice = 6500.99;
        saree12.hypoAllergenic = true;
        saree12.inStock = true;
        saree12.purchaseDate = "05/03/2026";
        saree12.warrantyEnd = "05/03/2027";
        saree12.warrantyValid = true;
        saree12.brand = "Koppal Weavers";
        saree12.material = "Coarse Handspun Cotton";
        saree12.size = "6 Yards";
        saree12.color = "Earth Brown-Cream";
        saree12.threadCount = 80;
        saree12.weaveType = "Koppal Temple Weave";
        saree12.fittedSheet = false;
        saree12.pillowCaseCount = 0;
        saree12.weight = 0.47;
        saree12.careInstructions = "Cold Water Wash";
        saree12.machineWashable = true;
        saree12.fabricQuality = "Artisan Spun";
        saree12.gsm = 155;
        saree12.wrinkleResistant = false;
        saree12.patternDesign = "Geometric Temple";
        saree12.organicCotton = true;
        saree12.collectionName = "Rural Artisan";
        saree12.discountPrice = 5599.99;
        saree12.storageMethod = "Jute Storage Bag";
        
        System.out.println("Item Code: " + saree12.itemCode);
        System.out.println("Unit Price: " + saree12.unitPrice);
        System.out.println("Hypo Allergenic: " + saree12.hypoAllergenic);
        System.out.println("In Stock: " + saree12.inStock);
        System.out.println("Purchase Date: " + saree12.purchaseDate);
        System.out.println("Warranty Ends: " + saree12.warrantyEnd);
        System.out.println("Warranty Valid: " + saree12.warrantyValid);
        System.out.println("Brand: " + saree12.brand);
        System.out.println("Material: " + saree12.material);
        System.out.println("Size: " + saree12.size);
        System.out.println("Color: " + saree12.color);
        System.out.println("Thread Count: " + saree12.threadCount);
        System.out.println("Weave Type: " + saree12.weaveType);
        System.out.println("Fitted Sheet: " + saree12.fittedSheet);
        System.out.println("Pillow Case Count: " + saree12.pillowCaseCount);
        System.out.println("Weight: " + saree12.weight + "kg");
        System.out.println("Care Instructions: " + saree12.careInstructions);
        System.out.println("Machine Washable: " + saree12.machineWashable);
        System.out.println("Fabric Quality: " + saree12.fabricQuality);
        System.out.println("GSM: " + saree12.gsm);
        System.out.println("Wrinkle Resistant: " + saree12.wrinkleResistant);
        System.out.println("Pattern Design: " + saree12.patternDesign);
        System.out.println("Organic Cotton: " + saree12.organicCotton);
        System.out.println("Collection Name: " + saree12.collectionName);
        System.out.println("Discount Price: " + saree12.discountPrice);
        System.out.println("Storage Method: " + saree12.storageMethod);
        System.out.println("-----------------------------");

        Saree saree13 = new Saree();
        saree13.itemCode = 2013;
        saree13.unitPrice = 9850.99;
        saree13.hypoAllergenic = true;
        saree13.inStock = true;
        saree13.purchaseDate = "05/03/2026";
        saree13.warrantyEnd = "05/03/2028";
        saree13.warrantyValid = true;
        saree13.brand = "Haveri Silk";
        saree13.material = "Silk Cotton Blend";
        saree13.size = "6 Yards";
        saree13.color = "Turquoise-Silver";
        saree13.threadCount = 980;
        saree13.weaveType = "Haveri Check Pattern";
        saree13.fittedSheet = false;
        saree13.pillowCaseCount = 0;
        saree13.weight = 0.50;
        saree13.careInstructions = "Dry Clean Preferred";
        saree13.machineWashable = false;
        saree13.fabricQuality = "Handloom Blend";
        saree13.gsm = 102;
        saree13.wrinkleResistant = true;
        saree13.patternDesign = "Paithani Inspired";
        saree13.organicCotton = true;
        saree13.collectionName = "Contemporary Classic";
        saree13.discountPrice = 8499.99;
        saree13.storageMethod = "Silk Lined Pouch";
        
        System.out.println("Item Code: " + saree13.itemCode);
        System.out.println("Unit Price: " + saree13.unitPrice);
        System.out.println("Hypo Allergenic: " + saree13.hypoAllergenic);
        System.out.println("In Stock: " + saree13.inStock);
        System.out.println("Purchase Date: " + saree13.purchaseDate);
        System.out.println("Warranty Ends: " + saree13.warrantyEnd);
        System.out.println("Warranty Valid: " + saree13.warrantyValid);
        System.out.println("Brand: " + saree13.brand);
        System.out.println("Material: " + saree13.material);
        System.out.println("Size: " + saree13.size);
        System.out.println("Color: " + saree13.color);
        System.out.println("Thread Count: " + saree13.threadCount);
        System.out.println("Weave Type: " + saree13.weaveType);
        System.out.println("Fitted Sheet: " + saree13.fittedSheet);
        System.out.println("Pillow Case Count: " + saree13.pillowCaseCount);
        System.out.println("Weight: " + saree13.weight + "kg");
        System.out.println("Care Instructions: " + saree13.careInstructions);
        System.out.println("Machine Washable: " + saree13.machineWashable);
        System.out.println("Fabric Quality: " + saree13.fabricQuality);
        System.out.println("GSM: " + saree13.gsm);
        System.out.println("Wrinkle Resistant: " + saree13.wrinkleResistant);
        System.out.println("Pattern Design: " + saree13.patternDesign);
        System.out.println("Organic Cotton: " + saree13.organicCotton);
        System.out.println("Collection Name: " + saree13.collectionName);
        System.out.println("Discount Price: " + saree13.discountPrice);
        System.out.println("Storage Method: " + saree13.storageMethod);
        System.out.println("-----------------------------");

        Saree saree14 = new Saree();
        saree14.itemCode = 2014;
        saree14.unitPrice = 7800.99;
        saree14.hypoAllergenic = true;
        saree14.inStock = true;
        saree14.purchaseDate = "05/03/2026";
        saree14.warrantyEnd = "05/03/2028";
        saree14.warrantyValid = true;
        saree14.brand = "Bagalkot Co-op";
        saree14.material = "Art Silk Cotton";
        saree14.size = "6 Yards";
        saree14.color = "Mustard-Black";
        saree14.threadCount = 140;
        saree14.weaveType = "Bagalkot Ikat";
        saree14.fittedSheet = false;
        saree14.pillowCaseCount = 0;
        saree14.weight = 0.44;
        saree14.careInstructions = "Machine Wash Gentle";
        saree14.machineWashable = true;
        saree14.fabricQuality = "Ikat Handloom";
        saree14.gsm = 135;
        saree14.wrinkleResistant = false;
        saree14.patternDesign = "Tie-Dye Ikat";
        saree14.organicCotton = true;
        saree14.collectionName = "Block Print Series";
        saree14.discountPrice = 6899.99;
        saree14.storageMethod = "Anti-Fade Cotton Pouch";
        
        System.out.println("Item Code: " + saree14.itemCode);
        System.out.println("Unit Price: " + saree14.unitPrice);
        System.out.println("Hypo Allergenic: " + saree14.hypoAllergenic);
        System.out.println("In Stock: " + saree14.inStock);
        System.out.println("Purchase Date: " + saree14.purchaseDate);
        System.out.println("Warranty Ends: " + saree14.warrantyEnd);
        System.out.println("Warranty Valid: " + saree14.warrantyValid);
        System.out.println("Brand: " + saree14.brand);
        System.out.println("Material: " + saree14.material);
        System.out.println("Size: " + saree14.size);
        System.out.println("Color: " + saree14.color);
        System.out.println("Thread Count: " + saree14.threadCount);
        System.out.println("Weave Type: " + saree14.weaveType);
        System.out.println("Fitted Sheet: " + saree14.fittedSheet);
        System.out.println("Pillow Case Count: " + saree14.pillowCaseCount);
        System.out.println("Weight: " + saree14.weight + "kg");
        System.out.println("Care Instructions: " + saree14.careInstructions);
        System.out.println("Machine Washable: " + saree14.machineWashable);
        System.out.println("Fabric Quality: " + saree14.fabricQuality);
        System.out.println("GSM: " + saree14.gsm);
        System.out.println("Wrinkle Resistant: " + saree14.wrinkleResistant);
        System.out.println("Pattern Design: " + saree14.patternDesign);
        System.out.println("Organic Cotton: " + saree14.organicCotton);
        System.out.println("Collection Name: " + saree14.collectionName);
        System.out.println("Discount Price: " + saree14.discountPrice);
        System.out.println("Storage Method: " + saree14.storageMethod);
        System.out.println("-----------------------------");

        Saree saree15 = new Saree();
        saree15.itemCode = 2015;
        saree15.unitPrice = 11200.99;
        saree15.hypoAllergenic = true;
        saree15.inStock = true;
        saree15.purchaseDate = "05/03/2026";
        saree15.warrantyEnd = "05/03/2028";
        saree15.warrantyValid = true;
        saree15.brand = "Davangere Silk";
        saree15.material = "Fine Cotton Mulberry Silk";
        saree15.size = "6.25 Yards";
        saree15.color = "Teal-Gold Zari";
        saree15.threadCount = 1150;
        saree15.weaveType = "Davangere Tissue Silk";
        saree15.fittedSheet = false;
        saree15.pillowCaseCount = 0;
        saree15.weight = 0.53;
        saree15.careInstructions = "Dry Clean Shade Dry";
        saree15.machineWashable = false;
        saree15.fabricQuality = "Tissue Lightweight";
        saree15.gsm = 76;
        saree15.wrinkleResistant = true;
        saree15.patternDesign = "Zari Woven Floral";
        saree15.organicCotton = true;
        saree15.collectionName = "Party Wear";
        saree15.discountPrice = 9599.99;
        saree15.storageMethod = "Tissue Silk Protector";
        
        System.out.println("Item Code: " + saree15.itemCode);
        System.out.println("Unit Price: " + saree15.unitPrice);
        System.out.println("Hypo Allergenic: " + saree15.hypoAllergenic);
        System.out.println("In Stock: " + saree15.inStock);
        System.out.println("Purchase Date: " + saree15.purchaseDate);
        System.out.println("Warranty Ends: " + saree15.warrantyEnd);
        System.out.println("Warranty Valid: " + saree15.warrantyValid);
        System.out.println("Brand: " + saree15.brand);
        System.out.println("Material: " + saree15.material);
        System.out.println("Size: " + saree15.size);
        System.out.println("Color: " + saree15.color);
        System.out.println("Thread Count: " + saree15.threadCount);
        System.out.println("Weave Type: " + saree15.weaveType);
        System.out.println("Fitted Sheet: " + saree15.fittedSheet);
        System.out.println("Pillow Case Count: " + saree15.pillowCaseCount);
        System.out.println("Weight: " + saree15.weight + "kg");
        System.out.println("Care Instructions: " + saree15.careInstructions);
        System.out.println("Machine Washable: " + saree15.machineWashable);
        System.out.println("Fabric Quality: " + saree15.fabricQuality);
        System.out.println("GSM: " + saree15.gsm);
        System.out.println("Wrinkle Resistant: " + saree15.wrinkleResistant);
        System.out.println("Pattern Design: " + saree15.patternDesign);
        System.out.println("Organic Cotton: " + saree15.organicCotton);
        System.out.println("Collection Name: " + saree15.collectionName);
        System.out.println("Discount Price: " + saree15.discountPrice);
        System.out.println("Storage Method: " + saree15.storageMethod);
        System.out.println("-----------------------------");

	
        Saree saree16 = new Saree();
        saree16.itemCode = 2016;
        saree16.unitPrice = 16750.99;
        saree16.hypoAllergenic = true;
        saree16.inStock = true;
        saree16.purchaseDate = "05/03/2026";
        saree16.warrantyEnd = "05/03/2029";
        saree16.warrantyValid = true;
        saree16.brand = "Tumkur Pure Silk";
        saree16.material = "6/60s Mulberry Silk";
        saree16.size = "6.3 Yards";
        saree16.color = "Ivory-Diamond Zari";
        saree16.threadCount = 1550;
        saree16.weaveType = "Tumkur Bridal Plain";
        saree16.fittedSheet = false;
        saree16.pillowCaseCount = 0;
        saree16.weight = 0.68;
        saree16.careInstructions = "Professional Dry Clean";
        saree16.machineWashable = false;
        saree16.fabricQuality = "Bridal Grade Silk";
        saree16.gsm = 72;
        saree16.wrinkleResistant = true;
        saree16.patternDesign = "Heavy Zari Border";
        saree16.organicCotton = false;
        saree16.collectionName = "Elite Wedding";
        saree16.discountPrice = 14299.99;
        saree16.storageMethod = "Luxury Silk Vault";
        
        System.out.println("Item Code: " + saree16.itemCode);
        System.out.println("Unit Price: " + saree16.unitPrice);
        System.out.println("Hypo Allergenic: " + saree16.hypoAllergenic);
        System.out.println("In Stock: " + saree16.inStock);
        System.out.println("Purchase Date: " + saree16.purchaseDate);
        System.out.println("Warranty Ends: " + saree16.warrantyEnd);
        System.out.println("Warranty Valid: " + saree16.warrantyValid);
        System.out.println("Brand: " + saree16.brand);
        System.out.println("Material: " + saree16.material);
        System.out.println("Size: " + saree16.size);
        System.out.println("Color: " + saree16.color);
        System.out.println("Thread Count: " + saree16.threadCount);
        System.out.println("Weave Type: " + saree16.weaveType);
        System.out.println("Fitted Sheet: " + saree16.fittedSheet);
        System.out.println("Pillow Case Count: " + saree16.pillowCaseCount);
        System.out.println("Weight: " + saree16.weight + "kg");
        System.out.println("Care Instructions: " + saree16.careInstructions);
        System.out.println("Machine Washable: " + saree16.machineWashable);
        System.out.println("Fabric Quality: " + saree16.fabricQuality);
        System.out.println("GSM: " + saree16.gsm);
        System.out.println("Wrinkle Resistant: " + saree16.wrinkleResistant);
        System.out.println("Pattern Design: " + saree16.patternDesign);
        System.out.println("Organic Cotton: " + saree16.organicCotton);
        System.out.println("Collection Name: " + saree16.collectionName);
        System.out.println("Discount Price: " + saree16.discountPrice);
        System.out.println("Storage Method: " + saree16.storageMethod);
        System.out.println("-----------------------------");

        Saree saree17 = new Saree();
        saree17.itemCode = 2017;
        saree17.unitPrice = 8900.99;
        saree17.hypoAllergenic = true;
        saree17.inStock = true;
        saree17.purchaseDate = "05/03/2026";
        saree17.warrantyEnd = "05/03/2028";
        saree17.warrantyValid = true;
        saree17.brand = "Mandya Kasuti";
        saree17.material = "Fine Mulmul Cotton";
        saree17.size = "5.8 Yards";
        saree17.color = "Deep Maroon-Gold";
        saree17.threadCount = 220;
        saree17.weaveType = "Kasuti Count Stitch";
        saree17.fittedSheet = false;
        saree17.pillowCaseCount = 0;
        saree17.weight = 0.39;
        saree17.careInstructions = "Hand Wash Cold Iron";
        saree17.machineWashable = true;
        saree17.fabricQuality = "Kasuti Masterpiece";
        saree17.gsm = 118;
        saree17.wrinkleResistant = false;
        saree17.patternDesign = "Dasara Elephant Motif";
        saree17.organicCotton = true;
        saree17.collectionName = "Cultural Heritage";
        saree17.discountPrice = 7699.99;
        saree17.storageMethod = "Kasuti Display Frame";
        
        System.out.println("Item Code: " + saree17.itemCode);
        System.out.println("Unit Price: " + saree17.unitPrice);
        System.out.println("Hypo Allergenic: " + saree17.hypoAllergenic);
        System.out.println("In Stock: " + saree17.inStock);
        System.out.println("Purchase Date: " + saree17.purchaseDate);
        System.out.println("Warranty Ends: " + saree17.warrantyEnd);
        System.out.println("Warranty Valid: " + saree17.warrantyValid);
        System.out.println("Brand: " + saree17.brand);
        System.out.println("Material: " + saree17.material);
        System.out.println("Size: " + saree17.size);
        System.out.println("Color: " + saree17.color);
        System.out.println("Thread Count: " + saree17.threadCount);
        System.out.println("Weave Type: " + saree17.weaveType);
        System.out.println("Fitted Sheet: " + saree17.fittedSheet);
        System.out.println("Pillow Case Count: " + saree17.pillowCaseCount);
        System.out.println("Weight: " + saree17.weight + "kg");
        System.out.println("Care Instructions: " + saree17.careInstructions);
        System.out.println("Machine Washable: " + saree17.machineWashable);
        System.out.println("Fabric Quality: " + saree17.fabricQuality);
        System.out.println("GSM: " + saree17.gsm);
        System.out.println("Wrinkle Resistant: " + saree17.wrinkleResistant);
        System.out.println("Pattern Design: " + saree17.patternDesign);
        System.out.println("Organic Cotton: " + saree17.organicCotton);
        System.out.println("Collection Name: " + saree17.collectionName);
        System.out.println("Discount Price: " + saree17.discountPrice);
        System.out.println("Storage Method: " + saree17.storageMethod);
        System.out.println("-----------------------------");

        Saree saree18 = new Saree();
        saree18.itemCode = 2018;
        saree18.unitPrice = 18900.99;
        saree18.hypoAllergenic = true;
        saree18.inStock = true;
        saree18.purchaseDate = "05/03/2026";
        saree18.warrantyEnd = "05/03/2030";
        saree18.warrantyValid = true;
        saree18.brand = "Kollegal Silk Weavers";
        saree18.material = "Pure Pit Loom Mulberry";
        saree18.size = "6.4 Yards";
        saree18.color = "White-Zari Brocade";
        saree18.threadCount = 1650;
        saree18.weaveType = "240 Hook Jacquard";
        saree18.fittedSheet = false;
        saree18.pillowCaseCount = 0;
        saree18.weight = 0.71;
        saree18.careInstructions = "Specialist Dry Clean";
        saree18.machineWashable = false;
        saree18.fabricQuality = "Chamarajanagar Pure";
        saree18.gsm = 68;
        saree18.wrinkleResistant = true;
        saree18.patternDesign = "Zari Brocade Body";
        saree18.organicCotton = false;
        saree18.collectionName = "Presidential Collection";
        saree18.discountPrice = 15999.99;
        saree18.storageMethod = "Museum Grade Silk Case";
        
        System.out.println("Item Code: " + saree18.itemCode);
        System.out.println("Unit Price: " + saree18.unitPrice);
        System.out.println("Hypo Allergenic: " + saree18.hypoAllergenic);
        System.out.println("In Stock: " + saree18.inStock);
        System.out.println("Purchase Date: " + saree18.purchaseDate);
        System.out.println("Warranty Ends: " + saree18.warrantyEnd);
        System.out.println("Warranty Valid: " + saree18.warrantyValid);
        System.out.println("Brand: " + saree18.brand);
        System.out.println("Material: " + saree18.material);
        System.out.println("Size: " + saree18.size);
        System.out.println("Color: " + saree18.color);
        System.out.println("Thread Count: " + saree18.threadCount);
        System.out.println("Weave Type: " + saree18.weaveType);
        System.out.println("Fitted Sheet: " + saree18.fittedSheet);
        System.out.println("Pillow Case Count: " + saree18.pillowCaseCount);
        System.out.println("Weight: " + saree18.weight + "kg");
        System.out.println("Care Instructions: " + saree18.careInstructions);
        System.out.println("Machine Washable: " + saree18.machineWashable);
        System.out.println("Fabric Quality: " + saree18.fabricQuality);
        System.out.println("GSM: " + saree18.gsm);
        System.out.println("Wrinkle Resistant: " + saree18.wrinkleResistant);
        System.out.println("Pattern Design: " + saree18.patternDesign);
        System.out.println("Organic Cotton: " + saree18.organicCotton);
        System.out.println("Collection Name: " + saree18.collectionName);
        System.out.println("Discount Price: " + saree18.discountPrice);
        System.out.println("Storage Method: " + saree18.storageMethod);
        System.out.println("-----------------------------");

        Saree saree19 = new Saree();
        saree19.itemCode = 2019;
        saree19.unitPrice = 13250.99;
        saree19.hypoAllergenic = true;
        saree19.inStock = true;
        saree19.purchaseDate = "05/03/2026";
        saree19.warrantyEnd = "05/03/2029";
        saree19.warrantyValid = true;
        saree19.brand = "Ramanagara Silks";
        saree19.material = "Sandwashed Mulberry";
        saree19.size = "6.2 Yards";
        saree19.color = "Grey-Green Khadi";
        saree19.threadCount = 1250;
        saree19.weaveType = "Sandwash Soft Finish";
        saree19.fittedSheet = false;
        saree19.pillowCaseCount = 0;
        saree19.weight = 0.46;
        saree19.careInstructions = "Delicate Dry Clean";
        saree19.machineWashable = false;
        saree19.fabricQuality = "Double Shaded Silk";
        saree19.gsm = 80;
        saree19.wrinkleResistant = true;
        saree19.patternDesign = "Bharatanatyam Motifs";
        saree19.organicCotton = false;
        saree19.collectionName = "Contemporary Heritage";
        saree19.discountPrice = 11299.99;
        saree19.storageMethod = "Silk Duochrome Pouch";
        
        System.out.println("Item Code: " + saree19.itemCode);
        System.out.println("Unit Price: " + saree19.unitPrice);
        System.out.println("Hypo Allergenic: " + saree19.hypoAllergenic);
        System.out.println("In Stock: " + saree19.inStock);
        System.out.println("Purchase Date: " + saree19.purchaseDate);
        System.out.println("Warranty Ends: " + saree19.warrantyEnd);
        System.out.println("Warranty Valid: " + saree19.warrantyValid);
        System.out.println("Brand: " + saree19.brand);
        System.out.println("Material: " + saree19.material);
        System.out.println("Size: " + saree19.size);
        System.out.println("Color: " + saree19.color);
        System.out.println("Thread Count: " + saree19.threadCount);
        System.out.println("Weave Type: " + saree19.weaveType);
        System.out.println("Fitted Sheet: " + saree19.fittedSheet);
        System.out.println("Pillow Case Count: " + saree19.pillowCaseCount);
        System.out.println("Weight: " + saree19.weight + "kg");
        System.out.println("Care Instructions: " + saree19.careInstructions);
        System.out.println("Machine Washable: " + saree19.machineWashable);
        System.out.println("Fabric Quality: " + saree19.fabricQuality);
        System.out.println("GSM: " + saree19.gsm);
        System.out.println("Wrinkle Resistant: " + saree19.wrinkleResistant);
        System.out.println("Pattern Design: " + saree19.patternDesign);
        System.out.println("Organic Cotton: " + saree19.organicCotton);
        System.out.println("Collection Name: " + saree19.collectionName);
        System.out.println("Discount Price: " + saree19.discountPrice);
        System.out.println("Storage Method: " + saree19.storageMethod);
        System.out.println("-----------------------------");

		
        Saree saree20 = new Saree();
        saree20.itemCode = 2020;
        saree20.unitPrice = 24999.99;
        saree20.hypoAllergenic = true;
        saree20.inStock = true;
        saree20.purchaseDate = "05/03/2026";
        saree20.warrantyEnd = "05/03/2031";
        saree20.warrantyValid = true;
        saree20.brand = "Davangere Silk Masterweavers";
        saree20.material = "Premium Cotton Silk Fusion";
        saree20.size = "6.5 Yards";
        saree20.color = "Royal Blue-Platinum Zari";
        saree20.threadCount = 1800;
        saree20.weaveType = "Davangere Double Tissue";
        saree20.fittedSheet = false;
        saree20.pillowCaseCount = 0;
        saree20.weight = 0.75;
        saree20.careInstructions = "Museum Quality Dry Clean";
        saree20.machineWashable = false;
        saree20.fabricQuality = "Presidential Award Winner";
        saree20.gsm = 65;
        saree20.wrinkleResistant = true;
        saree20.patternDesign = "Complete Zari Kanjivaram";
        saree20.organicCotton = true;
        saree20.collectionName = "Masterpiece Collection";
        saree20.discountPrice = 20999.99;
        saree20.storageMethod = "Climate Controlled Silk Vault";
        
        System.out.println("Item Code: " + saree20.itemCode);
        System.out.println("Unit Price: " + saree20.unitPrice);
        System.out.println("Hypo Allergenic: " + saree20.hypoAllergenic);
        System.out.println("In Stock: " + saree20.inStock);
        System.out.println("Purchase Date: " + saree20.purchaseDate);
        System.out.println("Warranty Ends: " + saree20.warrantyEnd);
        System.out.println("Warranty Valid: " + saree20.warrantyValid);
        System.out.println("Brand: " + saree20.brand);
        System.out.println("Material: " + saree20.material);
        System.out.println("Size: " + saree20.size);
        System.out.println("Color: " + saree20.color);
        System.out.println("Thread Count: " + saree20.threadCount);
        System.out.println("Weave Type: " + saree20.weaveType);
        System.out.println("Fitted Sheet: " + saree20.fittedSheet);
        System.out.println("Pillow Case Count: " + saree20.pillowCaseCount);
        System.out.println("Weight: " + saree20.weight + "kg");
        System.out.println("Care Instructions: " + saree20.careInstructions);
        System.out.println("Machine Washable: " + saree20.machineWashable);
        System.out.println("Fabric Quality: " + saree20.fabricQuality);
        System.out.println("GSM: " + saree20.gsm);
        System.out.println("Wrinkle Resistant: " + saree20.wrinkleResistant);
        System.out.println("Pattern Design: " + saree20.patternDesign);
        System.out.println("Organic Cotton: " + saree20.organicCotton);
        System.out.println("Collection Name: " + saree20.collectionName);
        System.out.println("Discount Price: " + saree20.discountPrice);
        System.out.println("Storage Method: " + saree20.storageMethod);
        System.out.println("-----------------------------");
	
		
		
		
    }
}
