class StudentsExecutor {
    public static void main(String[] args) {
        Students student1 = new Students();
        student1.studentId = 1001;
        student1.studentName = "Rahul Sharma";
        student1.course = "B.Tech CSE";
        student1.age = 20;
        student1.email = "rahul@university.edu";
        student1.gpa = 8.75;
        student1.scholarship = true;
        student1.city = "Bangalore";
        student1.rollNumber = 101;
        student1.department = "Computer Science";
        student1.activeStatus = true;
        student1.fees = 75000.00;
        student1.semester = 4;
        student1.phoneNumber = "9876543210";
        student1.bloodGroup = "O+";
        
        System.out.println("Student ID: " + student1.studentId);
        System.out.println("Student Name: " + student1.studentName);
        System.out.println("Course: " + student1.course);
        System.out.println("Age: " + student1.age);
        System.out.println("Email: " + student1.email);
        System.out.println("GPA: " + student1.gpa);
        System.out.println("Scholarship: " + student1.scholarship);
        System.out.println("City: " + student1.city);
        System.out.println("Roll Number: " + student1.rollNumber);
        System.out.println("Department: " + student1.department);
        System.out.println("Active Status: " + student1.activeStatus);
        System.out.println("Fees: " + student1.fees);
        System.out.println("Semester: " + student1.semester);
        System.out.println("Phone Number: " + student1.phoneNumber);
        System.out.println("Blood Group: " + student1.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student2 = new Students();
        student2.studentId = 1002;
        student2.studentName = "Priya Patel";
        student2.course = "B.Tech ECE";
        student2.age = 19;
        student2.email = "priya@university.edu";
        student2.gpa = 8.45;
        student2.scholarship = false;
        student2.city = "Mumbai";
        student2.rollNumber = 102;
        student2.department = "Electronics";
        student2.activeStatus = true;
        student2.fees = 72000.00;
        student2.semester = 4;
        student2.phoneNumber = "9876543211";
        student2.bloodGroup = "B+";
        
        System.out.println("Student ID: " + student2.studentId);
        System.out.println("Student Name: " + student2.studentName);
        System.out.println("Course: " + student2.course);
        System.out.println("Age: " + student2.age);
        System.out.println("Email: " + student2.email);
        System.out.println("GPA: " + student2.gpa);
        System.out.println("Scholarship: " + student2.scholarship);
        System.out.println("City: " + student2.city);
        System.out.println("Roll Number: " + student2.rollNumber);
        System.out.println("Department: " + student2.department);
        System.out.println("Active Status: " + student2.activeStatus);
        System.out.println("Fees: " + student2.fees);
        System.out.println("Semester: " + student2.semester);
        System.out.println("Phone Number: " + student2.phoneNumber);
        System.out.println("Blood Group: " + student2.bloodGroup);
        System.out.println("-----------------------------");
		
		
	        Students student3 = new Students();
        student3.studentId = 1003;
        student3.studentName = "Anita Verma";
        student3.course = "B.Tech ME";
        student3.age = 21;
        student3.email = "anita@university.edu";
        student3.gpa = 7.95;
        student3.scholarship = true;
        student3.city = "Delhi";
        student3.rollNumber = 103;
        student3.department = "Mechanical";
        student3.activeStatus = true;
        student3.fees = 68000.00;
        student3.semester = 5;
        student3.phoneNumber = "9876543212";
        student3.bloodGroup = "A+";
        
        System.out.println("Student ID: " + student3.studentId);
        System.out.println("Student Name: " + student3.studentName);
        System.out.println("Course: " + student3.course);
        System.out.println("Age: " + student3.age);
        System.out.println("Email: " + student3.email);
        System.out.println("GPA: " + student3.gpa);
        System.out.println("Scholarship: " + student3.scholarship);
        System.out.println("City: " + student3.city);
        System.out.println("Roll Number: " + student3.rollNumber);
        System.out.println("Department: " + student3.department);
        System.out.println("Active Status: " + student3.activeStatus);
        System.out.println("Fees: " + student3.fees);
        System.out.println("Semester: " + student3.semester);
        System.out.println("Phone Number: " + student3.phoneNumber);
        System.out.println("Blood Group: " + student3.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student4 = new Students();
        student4.studentId = 1004;
        student4.studentName = "Vikram Singh";
        student4.course = "B.Tech Civil";
        student4.age = 22;
        student4.email = "vikram@university.edu";
        student4.gpa = 8.12;
        student4.scholarship = false;
        student4.city = "Chennai";
        student4.rollNumber = 104;
        student4.department = "Civil Engineering";
        student4.activeStatus = true;
        student4.fees = 65000.00;
        student4.semester = 6;
        student4.phoneNumber = "9876543213";
        student4.bloodGroup = "AB+";
        
        System.out.println("Student ID: " + student4.studentId);
        System.out.println("Student Name: " + student4.studentName);
        System.out.println("Course: " + student4.course);
        System.out.println("Age: " + student4.age);
        System.out.println("Email: " + student4.email);
        System.out.println("GPA: " + student4.gpa);
        System.out.println("Scholarship: " + student4.scholarship);
        System.out.println("City: " + student4.city);
        System.out.println("Roll Number: " + student4.rollNumber);
        System.out.println("Department: " + student4.department);
        System.out.println("Active Status: " + student4.activeStatus);
        System.out.println("Fees: " + student4.fees);
        System.out.println("Semester: " + student4.semester);
        System.out.println("Phone Number: " + student4.phoneNumber);
        System.out.println("Blood Group: " + student4.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student5 = new Students();
        student5.studentId = 1005;
        student5.studentName = "Sneha Reddy";
        student5.course = "B.Sc Sports Management";
        student5.age = 19;
        student5.email = "sneha@university.edu";
        student5.gpa = 9.25;
        student5.scholarship = true;
        student5.city = "Hyderabad";
        student5.rollNumber = 105;
        student5.department = "Sports Management";
        student5.activeStatus = true;
        student5.fees = 45000.00;
        student5.semester = 3;
        student5.phoneNumber = "9876543214";
        student5.bloodGroup = "B-";
        
        System.out.println("Student ID: " + student5.studentId);
        System.out.println("Student Name: " + student5.studentName);
        System.out.println("Course: " + student5.course);
        System.out.println("Age: " + student5.age);
        System.out.println("Email: " + student5.email);
        System.out.println("GPA: " + student5.gpa);
        System.out.println("Scholarship: " + student5.scholarship);
        System.out.println("City: " + student5.city);
        System.out.println("Roll Number: " + student5.rollNumber);
        System.out.println("Department: " + student5.department);
        System.out.println("Active Status: " + student5.activeStatus);
        System.out.println("Fees: " + student5.fees);
        System.out.println("Semester: " + student5.semester);
        System.out.println("Phone Number: " + student5.phoneNumber);
        System.out.println("Blood Group: " + student5.bloodGroup);
        System.out.println("-----------------------------");
	
		
		        Students student6 = new Students();
        student6.studentId = 1006;
        student6.studentName = "Karthik M";
        student6.course = "B.Tech IT";
        student6.age = 20;
        student6.email = "karthik@university.edu";
        student6.gpa = 8.65;
        student6.scholarship = true;
        student6.city = "Tumkur";
        student6.rollNumber = 106;
        student6.department = "Information Technology";
        student6.activeStatus = true;
        student6.fees = 70000.00;
        student6.semester = 4;
        student6.phoneNumber = "9876543215";
        student6.bloodGroup = "O-";
        
        System.out.println("Student ID: " + student6.studentId);
        System.out.println("Student Name: " + student6.studentName);
        System.out.println("Course: " + student6.course);
        System.out.println("Age: " + student6.age);
        System.out.println("Email: " + student6.email);
        System.out.println("GPA: " + student6.gpa);
        System.out.println("Scholarship: " + student6.scholarship);
        System.out.println("City: " + student6.city);
        System.out.println("Roll Number: " + student6.rollNumber);
        System.out.println("Department: " + student6.department);
        System.out.println("Active Status: " + student6.activeStatus);
        System.out.println("Fees: " + student6.fees);
        System.out.println("Semester: " + student6.semester);
        System.out.println("Phone Number: " + student6.phoneNumber);
        System.out.println("Blood Group: " + student6.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student7 = new Students();
        student7.studentId = 1007;
        student7.studentName = "Meera N";
        student7.course = "BCA";
        student7.age = 19;
        student7.email = "meera@university.edu";
        student7.gpa = 8.92;
        student7.scholarship = true;
        student7.city = "Mysore";
        student7.rollNumber = 107;
        student7.department = "Computer Applications";
        student7.activeStatus = true;
        student7.fees = 55000.00;
        student7.semester = 3;
        student7.phoneNumber = "9876543216";
        student7.bloodGroup = "A-";
        
        System.out.println("Student ID: " + student7.studentId);
        System.out.println("Student Name: " + student7.studentName);
        System.out.println("Course: " + student7.course);
        System.out.println("Age: " + student7.age);
        System.out.println("Email: " + student7.email);
        System.out.println("GPA: " + student7.gpa);
        System.out.println("Scholarship: " + student7.scholarship);
        System.out.println("City: " + student7.city);
        System.out.println("Roll Number: " + student7.rollNumber);
        System.out.println("Department: " + student7.department);
        System.out.println("Active Status: " + student7.activeStatus);
        System.out.println("Fees: " + student7.fees);
        System.out.println("Semester: " + student7.semester);
        System.out.println("Phone Number: " + student7.phoneNumber);
        System.out.println("Blood Group: " + student7.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student8 = new Students();
        student8.studentId = 1008;
        student8.studentName = "Arjun K";
        student8.course = "B.Tech Sports Engineering";
        student8.age = 21;
        student8.email = "arjun@university.edu";
        student8.gpa = 8.35;
        student8.scholarship = false;
        student8.city = "Kolkata";
        student8.rollNumber = 108;
        student8.department = "Sports Engineering";
        student8.activeStatus = true;
        student8.fees = 78000.00;
        student8.semester = 5;
        student8.phoneNumber = "9876543217";
        student8.bloodGroup = "B+";
        
        System.out.println("Student ID: " + student8.studentId);
        System.out.println("Student Name: " + student8.studentName);
        System.out.println("Course: " + student8.course);
        System.out.println("Age: " + student8.age);
        System.out.println("Email: " + student8.email);
        System.out.println("GPA: " + student8.gpa);
        System.out.println("Scholarship: " + student8.scholarship);
        System.out.println("City: " + student8.city);
        System.out.println("Roll Number: " + student8.rollNumber);
        System.out.println("Department: " + student8.department);
        System.out.println("Active Status: " + student8.activeStatus);
        System.out.println("Fees: " + student8.fees);
        System.out.println("Semester: " + student8.semester);
        System.out.println("Phone Number: " + student8.phoneNumber);
        System.out.println("Blood Group: " + student8.bloodGroup);
        System.out.println("-----------------------------");

		
	        Students student9 = new Students();
        student9.studentId = 1009;
        student9.studentName = "Srushti G M";
        student9.course = "B.Tech CSE";
        student9.age = 20;
        student9.email = "srushti@university.edu";
        student9.gpa = 9.10;
        student9.scholarship = true;
        student9.city = "Tumkur";
        student9.rollNumber = 109;
        student9.department = "Computer Science";
        student9.activeStatus = true;
        student9.fees = 72000.00;
        student9.semester = 4;
        student9.phoneNumber = "9876543218";
        student9.bloodGroup = "O+";
        
        System.out.println("Student ID: " + student9.studentId);
        System.out.println("Student Name: " + student9.studentName);
        System.out.println("Course: " + student9.course);
        System.out.println("Age: " + student9.age);
        System.out.println("Email: " + student9.email);
        System.out.println("GPA: " + student9.gpa);
        System.out.println("Scholarship: " + student9.scholarship);
        System.out.println("City: " + student9.city);
        System.out.println("Roll Number: " + student9.rollNumber);
        System.out.println("Department: " + student9.department);
        System.out.println("Active Status: " + student9.activeStatus);
        System.out.println("Fees: " + student9.fees);
        System.out.println("Semester: " + student9.semester);
        System.out.println("Phone Number: " + student9.phoneNumber);
        System.out.println("Blood Group: " + student9.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student10 = new Students();
        student10.studentId = 1010;
        student10.studentName = "Rohan D";
        student10.course = "B.Tech AI&ML";
        student10.age = 21;
        student10.email = "rohan@university.edu";
        student10.gpa = 8.78;
        student10.scholarship = false;
        student10.city = "Pune";
        student10.rollNumber = 110;
        student10.department = "Artificial Intelligence";
        student10.activeStatus = true;
        student10.fees = 85000.00;
        student10.semester = 5;
        student10.phoneNumber = "9876543219";
        student10.bloodGroup = "A+";
        
        System.out.println("Student ID: " + student10.studentId);
        System.out.println("Student Name: " + student10.studentName);
        System.out.println("Course: " + student10.course);
        System.out.println("Age: " + student10.age);
        System.out.println("Email: " + student10.email);
        System.out.println("GPA: " + student10.gpa);
        System.out.println("Scholarship: " + student10.scholarship);
        System.out.println("City: " + student10.city);
        System.out.println("Roll Number: " + student10.rollNumber);
        System.out.println("Department: " + student10.department);
        System.out.println("Active Status: " + student10.activeStatus);
        System.out.println("Fees: " + student10.fees);
        System.out.println("Semester: " + student10.semester);
        System.out.println("Phone Number: " + student10.phoneNumber);
        System.out.println("Blood Group: " + student10.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student11 = new Students();
        student11.studentId = 1011;
        student11.studentName = "Lakshmi S";
        student11.course = "M.Tech Data Science";
        student11.age = 23;
        student11.email = "lakshmi@university.edu";
        student11.gpa = 9.45;
        student11.scholarship = true;
        student11.city = "Bangalore";
        student11.rollNumber = 111;
        student11.department = "Data Science";
        student11.activeStatus = true;
        student11.fees = 95000.00;
        student11.semester = 2;
        student11.phoneNumber = "9876543220";
        student11.bloodGroup = "B+";
        
        System.out.println("Student ID: " + student11.studentId);
        System.out.println("Student Name: " + student11.studentName);
        System.out.println("Course: " + student11.course);
        System.out.println("Age: " + student11.age);
        System.out.println("Email: " + student11.email);
        System.out.println("GPA: " + student11.gpa);
        System.out.println("Scholarship: " + student11.scholarship);
        System.out.println("City: " + student11.city);
        System.out.println("Roll Number: " + student11.rollNumber);
        System.out.println("Department: " + student11.department);
        System.out.println("Active Status: " + student11.activeStatus);
        System.out.println("Fees: " + student11.fees);
        System.out.println("Semester: " + student11.semester);
        System.out.println("Phone Number: " + student11.phoneNumber);
        System.out.println("Blood Group: " + student11.bloodGroup);
        System.out.println("-----------------------------");
	
	        Students student12 = new Students();
        student12.studentId = 1012;
        student12.studentName = "Naveen R";
        student12.course = "B.Tech EEE";
        student12.age = 20;
        student12.email = "naveen@university.edu";
        student12.gpa = 8.25;
        student12.scholarship = false;
        student12.city = "Coimbatore";
        student12.rollNumber = 112;
        student12.department = "Electrical Engineering";
        student12.activeStatus = true;
        student12.fees = 69000.00;
        student12.semester = 4;
        student12.phoneNumber = "9876543221";
        student12.bloodGroup = "A-";
        
        System.out.println("Student ID: " + student12.studentId);
        System.out.println("Student Name: " + student12.studentName);
        System.out.println("Course: " + student12.course);
        System.out.println("Age: " + student12.age);
        System.out.println("Email: " + student12.email);
        System.out.println("GPA: " + student12.gpa);
        System.out.println("Scholarship: " + student12.scholarship);
        System.out.println("City: " + student12.city);
        System.out.println("Roll Number: " + student12.rollNumber);
        System.out.println("Department: " + student12.department);
        System.out.println("Active Status: " + student12.activeStatus);
        System.out.println("Fees: " + student12.fees);
        System.out.println("Semester: " + student12.semester);
        System.out.println("Phone Number: " + student12.phoneNumber);
        System.out.println("Blood Group: " + student12.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student13 = new Students();
        student13.studentId = 1013;
        student13.studentName = "Pooja K";
        student13.course = "B.Sc Physical Education";
        student13.age = 19;
        student13.email = "pooja@university.edu";
        student13.gpa = 8.88;
        student13.scholarship = true;
        student13.city = "Mangalore";
        student13.rollNumber = 113;
        student13.department = "Physical Education";
        student13.activeStatus = true;
        student13.fees = 42000.00;
        student13.semester = 3;
        student13.phoneNumber = "9876543222";
        student13.bloodGroup = "O+";
        
        System.out.println("Student ID: " + student13.studentId);
        System.out.println("Student Name: " + student13.studentName);
        System.out.println("Course: " + student13.course);
        System.out.println("Age: " + student13.age);
        System.out.println("Email: " + student13.email);
        System.out.println("GPA: " + student13.gpa);
        System.out.println("Scholarship: " + student13.scholarship);
        System.out.println("City: " + student13.city);
        System.out.println("Roll Number: " + student13.rollNumber);
        System.out.println("Department: " + student13.department);
        System.out.println("Active Status: " + student13.activeStatus);
        System.out.println("Fees: " + student13.fees);
        System.out.println("Semester: " + student13.semester);
        System.out.println("Phone Number: " + student13.phoneNumber);
        System.out.println("Blood Group: " + student13.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student14 = new Students();
        student14.studentId = 1014;
        student14.studentName = "Ajay P";
        student14.course = "B.Tech Chemical";
        student14.age = 22;
        student14.email = "ajay@university.edu";
        student14.gpa = 7.85;
        student14.scholarship = false;
        student14.city = "Visakhapatnam";
        student14.rollNumber = 114;
        student14.department = "Chemical Engineering";
        student14.activeStatus = true;
        student14.fees = 71000.00;
        student14.semester = 5;
        student14.phoneNumber = "9876543223";
        student14.bloodGroup = "AB-";
        
        System.out.println("Student ID: " + student14.studentId);
        System.out.println("Student Name: " + student14.studentName);
        System.out.println("Course: " + student14.course);
        System.out.println("Age: " + student14.age);
        System.out.println("Email: " + student14.email);
        System.out.println("GPA: " + student14.gpa);
        System.out.println("Scholarship: " + student14.scholarship);
        System.out.println("City: " + student14.city);
        System.out.println("Roll Number: " + student14.rollNumber);
        System.out.println("Department: " + student14.department);
        System.out.println("Active Status: " + student14.activeStatus);
        System.out.println("Fees: " + student14.fees);
        System.out.println("Semester: " + student14.semester);
        System.out.println("Phone Number: " + student14.phoneNumber);
        System.out.println("Blood Group: " + student14.bloodGroup);
        System.out.println("-----------------------------");
	
	        Students student15 = new Students();
        student15.studentId = 1015;
        student15.studentName = "Divya R";
        student15.course = "B.Tech Biotechnology";
        student15.age = 20;
        student15.email = "divya@university.edu";
        student15.gpa = 8.42;
        student15.scholarship = true;
        student15.city = "Hubli";
        student15.rollNumber = 115;
        student15.department = "Biotechnology";
        student15.activeStatus = true;
        student15.fees = 74000.00;
        student15.semester = 4;
        student15.phoneNumber = "9876543224";
        student15.bloodGroup = "B-";
        
        System.out.println("Student ID: " + student15.studentId);
        System.out.println("Student Name: " + student15.studentName);
        System.out.println("Course: " + student15.course);
        System.out.println("Age: " + student15.age);
        System.out.println("Email: " + student15.email);
        System.out.println("GPA: " + student15.gpa);
        System.out.println("Scholarship: " + student15.scholarship);
        System.out.println("City: " + student15.city);
        System.out.println("Roll Number: " + student15.rollNumber);
        System.out.println("Department: " + student15.department);
        System.out.println("Active Status: " + student15.activeStatus);
        System.out.println("Fees: " + student15.fees);
        System.out.println("Semester: " + student15.semester);
        System.out.println("Phone Number: " + student15.phoneNumber);
        System.out.println("Blood Group: " + student15.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student16 = new Students();
        student16.studentId = 1016;
        student16.studentName = "Ganesh S";
        student16.course = "MBA Sports Management";
        student16.age = 24;
        student16.email = "ganesh@university.edu";
        student16.gpa = 8.67;
        student16.scholarship = false;
        student16.city = "Indore";
        student16.rollNumber = 116;
        student16.department = "Sports Management";
        student16.activeStatus = true;
        student16.fees = 120000.00;
        student16.semester = 2;
        student16.phoneNumber = "9876543225";
        student16.bloodGroup = "O+";
        
        System.out.println("Student ID: " + student16.studentId);
        System.out.println("Student Name: " + student16.studentName);
        System.out.println("Course: " + student16.course);
        System.out.println("Age: " + student16.age);
        System.out.println("Email: " + student16.email);
        System.out.println("GPA: " + student16.gpa);
        System.out.println("Scholarship: " + student16.scholarship);
        System.out.println("City: " + student16.city);
        System.out.println("Roll Number: " + student16.rollNumber);
        System.out.println("Department: " + student16.department);
        System.out.println("Active Status: " + student16.activeStatus);
        System.out.println("Fees: " + student16.fees);
        System.out.println("Semester: " + student16.semester);
        System.out.println("Phone Number: " + student16.phoneNumber);
        System.out.println("Blood Group: " + student16.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student17 = new Students();
        student17.studentId = 1017;
        student17.studentName = "Swathi M";
        student17.course = "B.Tech Aerospace";
        student17.age = 21;
        student17.email = "swathi@university.edu";
        student17.gpa = 8.95;
        student17.scholarship = true;
        student17.city = "Kochi";
        student17.rollNumber = 117;
        student17.department = "Aerospace Engineering";
        student17.activeStatus = true;
        student17.fees = 88000.00;
        student17.semester = 5;
        student17.phoneNumber = "9876543226";
        student17.bloodGroup = "A+";
        
        System.out.println("Student ID: " + student17.studentId);
        System.out.println("Student Name: " + student17.studentName);
        System.out.println("Course: " + student17.course);
        System.out.println("Age: " + student17.age);
        System.out.println("Email: " + student17.email);
        System.out.println("GPA: " + student17.gpa);
        System.out.println("Scholarship: " + student17.scholarship);
        System.out.println("City: " + student17.city);
        System.out.println("Roll Number: " + student17.rollNumber);
        System.out.println("Department: " + student17.department);
        System.out.println("Active Status: " + student17.activeStatus);
        System.out.println("Fees: " + student17.fees);
        System.out.println("Semester: " + student17.semester);
        System.out.println("Phone Number: " + student17.phoneNumber);
        System.out.println("Blood Group: " + student17.bloodGroup);
        System.out.println("-----------------------------");
	
	        Students student18 = new Students();
        student18.studentId = 1018;
        student18.studentName = "Ravi Kumar";
        student18.course = "B.Tech Robotics";
        student18.age = 20;
        student18.email = "ravi@university.edu";
        student18.gpa = 8.55;
        student18.scholarship = false;
        student18.city = "Bhopal";
        student18.rollNumber = 118;
        student18.department = "Robotics";
        student18.activeStatus = true;
        student18.fees = 82000.00;
        student18.semester = 4;
        student18.phoneNumber = "9876543227";
        student18.bloodGroup = "B+";
        
        System.out.println("Student ID: " + student18.studentId);
        System.out.println("Student Name: " + student18.studentName);
        System.out.println("Course: " + student18.course);
        System.out.println("Age: " + student18.age);
        System.out.println("Email: " + student18.email);
        System.out.println("GPA: " + student18.gpa);
        System.out.println("Scholarship: " + student18.scholarship);
        System.out.println("City: " + student18.city);
        System.out.println("Roll Number: " + student18.rollNumber);
        System.out.println("Department: " + student18.department);
        System.out.println("Active Status: " + student18.activeStatus);
        System.out.println("Fees: " + student18.fees);
        System.out.println("Semester: " + student18.semester);
        System.out.println("Phone Number: " + student18.phoneNumber);
        System.out.println("Blood Group: " + student18.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student19 = new Students();
        student19.studentId = 1019;
        student19.studentName = "Neha J";
        student19.course = "B.Tech Sports Technology";
        student19.age = 19;
        student19.email = "neha@university.edu";
        student19.gpa = 9.32;
        student19.scholarship = true;
        student19.city = "Jaipur";
        student19.rollNumber = 119;
        student19.department = "Sports Technology";
        student19.activeStatus = true;
        student19.fees = 79000.00;
        student19.semester = 3;
        student19.phoneNumber = "9876543228";
        student19.bloodGroup = "AB+";
        
        System.out.println("Student ID: " + student19.studentId);
        System.out.println("Student Name: " + student19.studentName);
        System.out.println("Course: " + student19.course);
        System.out.println("Age: " + student19.age);
        System.out.println("Email: " + student19.email);
        System.out.println("GPA: " + student19.gpa);
        System.out.println("Scholarship: " + student19.scholarship);
        System.out.println("City: " + student19.city);
        System.out.println("Roll Number: " + student19.rollNumber);
        System.out.println("Department: " + student19.department);
        System.out.println("Active Status: " + student19.activeStatus);
        System.out.println("Fees: " + student19.fees);
        System.out.println("Semester: " + student19.semester);
        System.out.println("Phone Number: " + student19.phoneNumber);
        System.out.println("Blood Group: " + student19.bloodGroup);
        System.out.println("-----------------------------");
        
        Students student20 = new Students();
        student20.studentId = 1020;
        student20.studentName = "Yashwant B";
        student20.course = "B.Tech Automobile";
        student20.age = 22;
        student20.email = "yashwant@university.edu";
        student20.gpa = 8.15;
        student20.scholarship = false;
        student20.city = "Nagpur";
        student20.rollNumber = 120;
        student20.department = "Automobile Engineering";
        student20.activeStatus = true;
        student20.fees = 76000.00;
        student20.semester = 6;
        student20.phoneNumber = "9876543229";
        student20.bloodGroup = "O-";
        
        System.out.println("Student ID: " + student20.studentId);
        System.out.println("Student Name: " + student20.studentName);
        System.out.println("Course: " + student20.course);
        System.out.println("Age: " + student20.age);
        System.out.println("Email: " + student20.email);
        System.out.println("GPA: " + student20.gpa);
        System.out.println("Scholarship: " + student20.scholarship);
        System.out.println("City: " + student20.city);
        System.out.println("Roll Number: " + student20.rollNumber);
        System.out.println("Department: " + student20.department);
        System.out.println("Active Status: " + student20.activeStatus);
        System.out.println("Fees: " + student20.fees);
        System.out.println("Semester: " + student20.semester);
        System.out.println("Phone Number: " + student20.phoneNumber);
        System.out.println("Blood Group: " + student20.bloodGroup);
        System.out.println("-----------------------------");
	
		
		
    }
}
