class TempleExecutor {
    public static void main(String[] args) {
        Temple temple1 = new Temple();
        
        temple1.templeId = 301;
        temple1.location = "Dharmasthala Manjunatha Temple";
        temple1.state = "Karnataka";
        temple1.activeStatus = true;
        temple1.constructionDate = "16th Century";
        temple1.lastRenovationDate = "2025";
        temple1.renovationDue = false;
        temple1.deityName = "Lord Manjunatha (Shiva)";
        temple1.architectureStyle = "Dravidian";
        temple1.areaSquareFeet = 25000;
        temple1.mainDeity = "Manjunatha";
        temple1.heritageSite = true;
        temple1.annualVisitors = 4000000;
        temple1.presidingDeity = "Lord Shiva";
        temple1.pilgrimageCenter = true;
        temple1.festivalsCount = 12;
        temple1.annualDonations = 500000000.00;
        temple1.geographicalZone = "Tulunadu";
        temple1.waterBody = true;
        temple1.primaryStone = "Granite";
        temple1.gopuraHeight = 75;
        temple1.earthquakeResistant = true;
        temple1.pilgrimageRoute = "Dharmasthala-Ujire";
        temple1.digitalDarshan = true;
        temple1.templeTrust = "Dharmasthala Temple Committee";
        temple1.annualBudget = 120000000.00;
        temple1.emergencyContact = "08256-277072";
        
        System.out.println("Temple ID: " + temple1.templeId);
        System.out.println("Location: " + temple1.location);
        System.out.println("State: " + temple1.state);
        System.out.println("Active Status: " + temple1.activeStatus);
        System.out.println("Construction Date: " + temple1.constructionDate);
        System.out.println("Last Renovation: " + temple1.lastRenovationDate);
        System.out.println("Renovation Due: " + temple1.renovationDue);
        System.out.println("Deity Name: " + temple1.deityName);
        System.out.println("Architecture Style: " + temple1.architectureStyle);
        System.out.println("Area: " + temple1.areaSquareFeet + " sq.ft");
        System.out.println("Main Deity: " + temple1.mainDeity);
        System.out.println("Heritage Site: " + temple1.heritageSite);
        System.out.println("Annual Visitors: " + temple1.annualVisitors);
        System.out.println("Presiding Deity: " + temple1.presidingDeity);
        System.out.println("Pilgrimage Center: " + temple1.pilgrimageCenter);
        System.out.println("Festivals Count: " + temple1.festivalsCount);
        System.out.println("Annual Donations: " + temple1.annualDonations);
        System.out.println("Geographical Zone: " + temple1.geographicalZone);
        System.out.println("Water Body: " + temple1.waterBody);
        System.out.println("Primary Stone: " + temple1.primaryStone);
        System.out.println("Gopura Height: " + temple1.gopuraHeight + " feet");
        System.out.println("Earthquake Resistant: " + temple1.earthquakeResistant);
        System.out.println("Pilgrimage Route: " + temple1.pilgrimageRoute);
        System.out.println("Digital Darshan: " + temple1.digitalDarshan);
        System.out.println("Temple Trust: " + temple1.templeTrust);
        System.out.println("Annual Budget: " + temple1.annualBudget);
        System.out.println("Emergency Contact: " + temple1.emergencyContact);
        System.out.println("================================");
		
Temple temple2 = new Temple();

temple2.templeId = 302;
temple2.location = "Udupi Sri Krishna Temple";
temple2.state = "Karnataka";
temple2.activeStatus = true;
temple2.constructionDate = "13th Century";
temple2.lastRenovationDate = "2024";
temple2.renovationDue = false;
temple2.deityName = "Lord Krishna";
temple2.architectureStyle = "Dvaita Philosophy";
temple2.areaSquareFeet = 18000;
temple2.mainDeity = "Balakrishna";
temple2.heritageSite = true;
temple2.annualVisitors = 2000000;
temple2.presidingDeity = "Lord Krishna";
temple2.pilgrimageCenter = true;
temple2.festivalsCount = 18;
temple2.annualDonations = 250000000.00;
temple2.geographicalZone = "Tulunadu";
temple2.waterBody = true;
temple2.primaryStone = "Laterite";
temple2.gopuraHeight = 60;
temple2.earthquakeResistant = true;
temple2.pilgrimageRoute = "Udupi-Kukke";
temple2.digitalDarshan = true;
temple2.templeTrust = "Udupi Krishna Matha";
temple2.annualBudget = 85000000.00;
temple2.emergencyContact = "0820-2520717";

System.out.println("Temple ID: " + temple2.templeId);
System.out.println("Location: " + temple2.location);
System.out.println("State: " + temple2.state);
System.out.println("Active Status: " + temple2.activeStatus);
System.out.println("Construction Date: " + temple2.constructionDate);
System.out.println("Last Renovation: " + temple2.lastRenovationDate);
System.out.println("Renovation Due: " + temple2.renovationDue);
System.out.println("Deity Name: " + temple2.deityName);
System.out.println("Architecture Style: " + temple2.architectureStyle);
System.out.println("Area: " + temple2.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple2.mainDeity);
System.out.println("Heritage Site: " + temple2.heritageSite);
System.out.println("Annual Visitors: " + temple2.annualVisitors);
System.out.println("Presiding Deity: " + temple2.presidingDeity);
System.out.println("Pilgrimage Center: " + temple2.pilgrimageCenter);
System.out.println("Festivals Count: " + temple2.festivalsCount);
System.out.println("Annual Donations: " + temple2.annualDonations);
System.out.println("Geographical Zone: " + temple2.geographicalZone);
System.out.println("Water Body: " + temple2.waterBody);
System.out.println("Primary Stone: " + temple2.primaryStone);
System.out.println("Gopura Height: " + temple2.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple2.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple2.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple2.digitalDarshan);
System.out.println("Temple Trust: " + temple2.templeTrust);
System.out.println("Annual Budget: " + temple2.annualBudget);
System.out.println("Emergency Contact: " + temple2.emergencyContact);
System.out.println("================================");

		
Temple temple3 = new Temple();

temple3.templeId = 303;
temple3.location = "Kukke Subramanya Temple";
temple3.state = "Karnataka";
temple3.activeStatus = true;
temple3.constructionDate = "Ancient Times";
temple3.lastRenovationDate = "2025";
temple3.renovationDue = false;
temple3.deityName = "Lord Subramanya";
temple3.architectureStyle = "Dravidian Kerala";
temple3.areaSquareFeet = 22000;
temple3.mainDeity = "Kartikeya";
temple3.heritageSite = true;
temple3.annualVisitors = 3500000;
temple3.presidingDeity = "Lord Subramanya";
temple3.pilgrimageCenter = true;
temple3.festivalsCount = 15;
temple3.annualDonations = 380000000.00;
temple3.geographicalZone = "Western Ghats";
temple3.waterBody = true;
temple3.primaryStone = "Granite";
temple3.gopuraHeight = 68;
temple3.earthquakeResistant = true;
temple3.pilgrimageRoute = "Udupi-Dharmasthala-Kukke";
temple3.digitalDarshan = true;
temple3.templeTrust = "Kukke Subramanya Temple Trust";
temple3.annualBudget = 95000000.00;
temple3.emergencyContact = "08236-281233";

System.out.println("Temple ID: " + temple3.templeId);
System.out.println("Location: " + temple3.location);
System.out.println("State: " + temple3.state);
System.out.println("Active Status: " + temple3.activeStatus);
System.out.println("Construction Date: " + temple3.constructionDate);
System.out.println("Last Renovation: " + temple3.lastRenovationDate);
System.out.println("Renovation Due: " + temple3.renovationDue);
System.out.println("Deity Name: " + temple3.deityName);
System.out.println("Architecture Style: " + temple3.architectureStyle);
System.out.println("Area: " + temple3.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple3.mainDeity);
System.out.println("Heritage Site: " + temple3.heritageSite);
System.out.println("Annual Visitors: " + temple3.annualVisitors);
System.out.println("Presiding Deity: " + temple3.presidingDeity);
System.out.println("Pilgrimage Center: " + temple3.pilgrimageCenter);
System.out.println("Festivals Count: " + temple3.festivalsCount);
System.out.println("Annual Donations: " + temple3.annualDonations);
System.out.println("Geographical Zone: " + temple3.geographicalZone);
System.out.println("Water Body: " + temple3.waterBody);
System.out.println("Primary Stone: " + temple3.primaryStone);
System.out.println("Gopura Height: " + temple3.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple3.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple3.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple3.digitalDarshan);
System.out.println("Temple Trust: " + temple3.templeTrust);
System.out.println("Annual Budget: " + temple3.annualBudget);
System.out.println("Emergency Contact: " + temple3.emergencyContact);
System.out.println("================================");
	
		
Temple temple4 = new Temple();

temple4.templeId = 304;
temple4.location = "Chamundeshwari Temple";
temple4.state = "Karnataka";
temple4.activeStatus = true;
temple4.constructionDate = "12th Century";
temple4.lastRenovationDate = "2025";
temple4.renovationDue = false;
temple4.deityName = "Goddess Chamundeshwari";
temple4.architectureStyle = "Dravidian";
temple4.areaSquareFeet = 32000;
temple4.mainDeity = "Durga";
temple4.heritageSite = true;
temple4.annualVisitors = 5000000;
temple4.presidingDeity = "Chamundeshwari";
temple4.pilgrimageCenter = true;
temple4.festivalsCount = 10;
temple4.annualDonations = 420000000.00;
temple4.geographicalZone = "Mysore Plateau";
temple4.waterBody = true;
temple4.primaryStone = "Granite";
temple4.gopuraHeight = 82;
temple4.earthquakeResistant = true;
temple4.pilgrimageRoute = "Mysore-Chamundi Hills";
temple4.digitalDarshan = true;
temple4.templeTrust = "Chamundeshwari Temple Board";
temple4.annualBudget = 105000000.00;
temple4.emergencyContact = "0821-2474282";

System.out.println("Temple ID: " + temple4.templeId);
System.out.println("Location: " + temple4.location);
System.out.println("State: " + temple4.state);
System.out.println("Active Status: " + temple4.activeStatus);
System.out.println("Construction Date: " + temple4.constructionDate);
System.out.println("Last Renovation: " + temple4.lastRenovationDate);
System.out.println("Renovation Due: " + temple4.renovationDue);
System.out.println("Deity Name: " + temple4.deityName);
System.out.println("Architecture Style: " + temple4.architectureStyle);
System.out.println("Area: " + temple4.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple4.mainDeity);
System.out.println("Heritage Site: " + temple4.heritageSite);
System.out.println("Annual Visitors: " + temple4.annualVisitors);
System.out.println("Presiding Deity: " + temple4.presidingDeity);
System.out.println("Pilgrimage Center: " + temple4.pilgrimageCenter);
System.out.println("Festivals Count: " + temple4.festivalsCount);
System.out.println("Annual Donations: " + temple4.annualDonations);
System.out.println("Geographical Zone: " + temple4.geographicalZone);
System.out.println("Water Body: " + temple4.waterBody);
System.out.println("Primary Stone: " + temple4.primaryStone);
System.out.println("Gopura Height: " + temple4.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple4.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple4.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple4.digitalDarshan);
System.out.println("Temple Trust: " + temple4.templeTrust);
System.out.println("Annual Budget: " + temple4.annualBudget);
System.out.println("Emergency Contact: " + temple4.emergencyContact);
System.out.println("================================");
	
		
Temple temple5 = new Temple();

temple5.templeId = 305;
temple5.location = "Murudeshwar Shiva Temple";
temple5.state = "Karnataka";
temple5.activeStatus = true;
temple5.constructionDate = "Recent (1990s)";
temple5.lastRenovationDate = "2024";
temple5.renovationDue = false;
temple5.deityName = "Lord Shiva";
temple5.architectureStyle = "Modern Dravidian";
temple5.areaSquareFeet = 45000;
temple5.mainDeity = "Shiva";
temple5.heritageSite = false;
temple5.annualVisitors = 3000000;
temple5.presidingDeity = "Atmalinga";
temple5.pilgrimageCenter = true;
temple5.festivalsCount = 8;
temple5.annualDonations = 180000000.00;
temple5.geographicalZone = "Coastal Karnataka";
temple5.waterBody = true;
temple5.primaryStone = "Granite";
temple5.gopuraHeight = 237;
temple5.earthquakeResistant = true;
temple5.pilgrimageRoute = "Murudeshwar-Gokarna";
temple5.digitalDarshan = true;
temple5.templeTrust = "Murudeshwar Temple Trust";
temple5.annualBudget = 75000000.00;
temple5.emergencyContact = "08385-262251";

System.out.println("Temple ID: " + temple5.templeId);
System.out.println("Location: " + temple5.location);
System.out.println("State: " + temple5.state);
System.out.println("Active Status: " + temple5.activeStatus);
System.out.println("Construction Date: " + temple5.constructionDate);
System.out.println("Last Renovation: " + temple5.lastRenovationDate);
System.out.println("Renovation Due: " + temple5.renovationDue);
System.out.println("Deity Name: " + temple5.deityName);
System.out.println("Architecture Style: " + temple5.architectureStyle);
System.out.println("Area: " + temple5.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple5.mainDeity);
System.out.println("Heritage Site: " + temple5.heritageSite);
System.out.println("Annual Visitors: " + temple5.annualVisitors);
System.out.println("Presiding Deity: " + temple5.presidingDeity);
System.out.println("Pilgrimage Center: " + temple5.pilgrimageCenter);
System.out.println("Festivals Count: " + temple5.festivalsCount);
System.out.println("Annual Donations: " + temple5.annualDonations);
System.out.println("Geographical Zone: " + temple5.geographicalZone);
System.out.println("Water Body: " + temple5.waterBody);
System.out.println("Primary Stone: " + temple5.primaryStone);
System.out.println("Gopura Height: " + temple5.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple5.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple5.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple5.digitalDarshan);
System.out.println("Temple Trust: " + temple5.templeTrust);
System.out.println("Annual Budget: " + temple5.annualBudget);
System.out.println("Emergency Contact: " + temple5.emergencyContact);
System.out.println("================================");
	
		
Temple temple6 = new Temple();

temple6.templeId = 306;
temple6.location = "Gavi Gangadhareshwara Temple";
temple6.state = "Karnataka";
temple6.activeStatus = true;
temple6.constructionDate = "16th Century";
temple6.lastRenovationDate = "2025";
temple6.renovationDue = false;
temple6.deityName = "Lord Shiva";
temple6.architectureStyle = "Rock-cut Cave";
temple6.areaSquareFeet = 12000;
temple6.mainDeity = "Gangadhareshwara";
temple6.heritageSite = true;
temple6.annualVisitors = 800000;
temple6.presidingDeity = "Shiva Linga";
temple6.pilgrimageCenter = true;
temple6.festivalsCount = 6;
temple6.annualDonations = 65000000.00;
temple6.geographicalZone = "Bangalore Plateau";
temple6.waterBody = false;
temple6.primaryStone = "Single Monolith";
temple6.gopuraHeight = 45;
temple6.earthquakeResistant = true;
temple6.pilgrimageRoute = "Basavanagudi Circuit";
temple6.digitalDarshan = true;
temple6.templeTrust = "Gavi Gangadhareshwara Trust";
temple6.annualBudget = 28000000.00;
temple6.emergencyContact = "080-22352828";

System.out.println("Temple ID: " + temple6.templeId);
System.out.println("Location: " + temple6.location);
System.out.println("State: " + temple6.state);
System.out.println("Active Status: " + temple6.activeStatus);
System.out.println("Construction Date: " + temple6.constructionDate);
System.out.println("Last Renovation: " + temple6.lastRenovationDate);
System.out.println("Renovation Due: " + temple6.renovationDue);
System.out.println("Deity Name: " + temple6.deityName);
System.out.println("Architecture Style: " + temple6.architectureStyle);
System.out.println("Area: " + temple6.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple6.mainDeity);
System.out.println("Heritage Site: " + temple6.heritageSite);
System.out.println("Annual Visitors: " + temple6.annualVisitors);
System.out.println("Presiding Deity: " + temple6.presidingDeity);
System.out.println("Pilgrimage Center: " + temple6.pilgrimageCenter);
System.out.println("Festivals Count: " + temple6.festivalsCount);
System.out.println("Annual Donations: " + temple6.annualDonations);
System.out.println("Geographical Zone: " + temple6.geographicalZone);
System.out.println("Water Body: " + temple6.waterBody);
System.out.println("Primary Stone: " + temple6.primaryStone);
System.out.println("Gopura Height: " + temple6.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple6.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple6.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple6.digitalDarshan);
System.out.println("Temple Trust: " + temple6.templeTrust);
System.out.println("Annual Budget: " + temple6.annualBudget);
System.out.println("Emergency Contact: " + temple6.emergencyContact);
System.out.println("================================");
	
		
Temple temple7 = new Temple();

temple7.templeId = 307;
temple7.location = "Banashankari Temple";
temple7.state = "Karnataka";
temple7.activeStatus = true;
temple7.constructionDate = "7th Century";
temple7.lastRenovationDate = "2024";
temple7.renovationDue = false;
temple7.deityName = "Goddess Banashankari";
temple7.architectureStyle = "Chalukyan";
temple7.areaSquareFeet = 28000;
temple7.mainDeity = "Mahishasura Mardini";
temple7.heritageSite = true;
temple7.annualVisitors = 2500000;
temple7.presidingDeity = "Banashankari Devi";
temple7.pilgrimageCenter = true;
temple7.festivalsCount = 14;
temple7.annualDonations = 320000000.00;
temple7.geographicalZone = "North Karnataka";
temple7.waterBody = true;
temple7.primaryStone = "Basalt";
temple7.gopuraHeight = 90;
temple7.earthquakeResistant = true;
temple7.pilgrimageRoute = "Badami-Banashankari";
temple7.digitalDarshan = true;
temple7.templeTrust = "Banashankari Temple Committee";
temple7.annualBudget = 92000000.00;
temple7.emergencyContact = "08353-220027";

System.out.println("Temple ID: " + temple7.templeId);
System.out.println("Location: " + temple7.location);
System.out.println("State: " + temple7.state);
System.out.println("Active Status: " + temple7.activeStatus);
System.out.println("Construction Date: " + temple7.constructionDate);
System.out.println("Last Renovation: " + temple7.lastRenovationDate);
System.out.println("Renovation Due: " + temple7.renovationDue);
System.out.println("Deity Name: " + temple7.deityName);
System.out.println("Architecture Style: " + temple7.architectureStyle);
System.out.println("Area: " + temple7.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple7.mainDeity);
System.out.println("Heritage Site: " + temple7.heritageSite);
System.out.println("Annual Visitors: " + temple7.annualVisitors);
System.out.println("Presiding Deity: " + temple7.presidingDeity);
System.out.println("Pilgrimage Center: " + temple7.pilgrimageCenter);
System.out.println("Festivals Count: " + temple7.festivalsCount);
System.out.println("Annual Donations: " + temple7.annualDonations);
System.out.println("Geographical Zone: " + temple7.geographicalZone);
System.out.println("Water Body: " + temple7.waterBody);
System.out.println("Primary Stone: " + temple7.primaryStone);
System.out.println("Gopura Height: " + temple7.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple7.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple7.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple7.digitalDarshan);
System.out.println("Temple Trust: " + temple7.templeTrust);
System.out.println("Annual Budget: " + temple7.annualBudget);
System.out.println("Emergency Contact: " + temple7.emergencyContact);
System.out.println("================================");
	
		
	Temple temple8 = new Temple();

temple8.templeId = 308;
temple8.location = "Hoysaleswara Temple";
temple8.state = "Karnataka";
temple8.activeStatus = true;
temple8.constructionDate = "1121 CE";
temple8.lastRenovationDate = "2025";
temple8.renovationDue = false;
temple8.deityName = "Lord Shiva";
temple8.architectureStyle = "Hoysala";
temple8.areaSquareFeet = 35000;
temple8.mainDeity = "Hoysaleswara";
temple8.heritageSite = true;
temple8.annualVisitors = 1200000;
temple8.presidingDeity = "Shiva Linga";
temple8.pilgrimageCenter = true;
temple8.festivalsCount = 9;
temple8.annualDonations = 95000000.00;
temple8.geographicalZone = "Malnad";
temple8.waterBody = true;
temple8.primaryStone = "Soapstone";
temple8.gopuraHeight = 65;
temple8.earthquakeResistant = true;
temple8.pilgrimageRoute = "Halebidu-Belur";
temple8.digitalDarshan = true;
temple8.templeTrust = "ASI Protected";
temple8.annualBudget = 45000000.00;
temple8.emergencyContact = "08172-265038";


System.out.println("Temple ID: " + temple8.templeId);
System.out.println("Location: " + temple8.location);
System.out.println("State: " + temple8.state);
System.out.println("Active Status: " + temple8.activeStatus);
System.out.println("Construction Date: " + temple8.constructionDate);
System.out.println("Last Renovation: " + temple8.lastRenovationDate);
System.out.println("Renovation Due: " + temple8.renovationDue);
System.out.println("Deity Name: " + temple8.deityName);
System.out.println("Architecture Style: " + temple8.architectureStyle);
System.out.println("Area: " + temple8.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple8.mainDeity);
System.out.println("Heritage Site: " + temple8.heritageSite);
System.out.println("Annual Visitors: " + temple8.annualVisitors);
System.out.println("Presiding Deity: " + temple8.presidingDeity);
System.out.println("Pilgrimage Center: " + temple8.pilgrimageCenter);
System.out.println("Festivals Count: " + temple8.festivalsCount);
System.out.println("Annual Donations: " + temple8.annualDonations);
System.out.println("Geographical Zone: " + temple8.geographicalZone);
System.out.println("Water Body: " + temple8.waterBody);
System.out.println("Primary Stone: " + temple8.primaryStone);
System.out.println("Gopura Height: " + temple8.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple8.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple8.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple8.digitalDarshan);
System.out.println("Temple Trust: " + temple8.templeTrust);
System.out.println("Annual Budget: " + temple8.annualBudget);
System.out.println("Emergency Contact: " + temple8.emergencyContact);
System.out.println("================================");
	
	Temple temple9 = new Temple();

temple9.templeId = 309;
temple9.location = "Chennakesava Temple";
temple9.state = "Karnataka";
temple9.activeStatus = true;
temple9.constructionDate = "1117 CE";
temple9.lastRenovationDate = "2024";
temple9.renovationDue = false;
temple9.deityName = "Lord Vishnu";
temple9.architectureStyle = "Hoysala";
temple9.areaSquareFeet = 41000;
temple9.mainDeity = "Chennakesava";
temple9.heritageSite = true;
temple9.annualVisitors = 1500000;
temple9.presidingDeity = "Vishnu";
temple9.pilgrimageCenter = true;
temple9.festivalsCount = 11;
temple9.annualDonations = 78000000.00;
temple9.geographicalZone = "Malnad";
temple9.waterBody = true;
temple9.primaryStone = "Soapstone";
temple9.gopuraHeight = 72;
temple9.earthquakeResistant = true;
temple9.pilgrimageRoute = "Belur-Halebidu";
temple9.digitalDarshan = true;
temple9.templeTrust = "ASI Protected";
temple9.annualBudget = 52000000.00;
temple9.emergencyContact = "08177-268402";

System.out.println("Temple ID: " + temple9.templeId);
System.out.println("Location: " + temple9.location);
System.out.println("State: " + temple9.state);
System.out.println("Active Status: " + temple9.activeStatus);
System.out.println("Construction Date: " + temple9.constructionDate);
System.out.println("Last Renovation: " + temple9.lastRenovationDate);
System.out.println("Renovation Due: " + temple9.renovationDue);
System.out.println("Deity Name: " + temple9.deityName);
System.out.println("Architecture Style: " + temple9.architectureStyle);
System.out.println("Area: " + temple9.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple9.mainDeity);
System.out.println("Heritage Site: " + temple9.heritageSite);
System.out.println("Annual Visitors: " + temple9.annualVisitors);
System.out.println("Presiding Deity: " + temple9.presidingDeity);
System.out.println("Pilgrimage Center: " + temple9.pilgrimageCenter);
System.out.println("Festivals Count: " + temple9.festivalsCount);
System.out.println("Annual Donations: " + temple9.annualDonations);
System.out.println("Geographical Zone: " + temple9.geographicalZone);
System.out.println("Water Body: " + temple9.waterBody);
System.out.println("Primary Stone: " + temple9.primaryStone);
System.out.println("Gopura Height: " + temple9.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple9.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple9.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple9.digitalDarshan);
System.out.println("Temple Trust: " + temple9.templeTrust);
System.out.println("Annual Budget: " + temple9.annualBudget);
System.out.println("Emergency Contact: " + temple9.emergencyContact);
System.out.println("================================");
	
		
		
	Temple temple10 = new Temple();

temple10.templeId = 310;
temple10.location = "Virupaksha Temple";
temple10.state = "Karnataka";
temple10.activeStatus = true;
temple10.constructionDate = "7th Century";
temple10.lastRenovationDate = "2025";
temple10.renovationDue = false;
temple10.deityName = "Lord Shiva";
temple10.architectureStyle = "Dravidian-Vijayanagara";
temple10.areaSquareFeet = 85000;
temple10.mainDeity = "Virupaksha";
temple10.heritageSite = true;
temple10.annualVisitors = 3500000;
temple10.presidingDeity = "Shiva Linga";
temple10.pilgrimageCenter = true;
temple10.festivalsCount = 16;
temple10.annualDonations = 285000000.00;
temple10.geographicalZone = "Deccan Plateau";
temple10.waterBody = true;
temple10.primaryStone = "Granite";
temple10.gopuraHeight = 156;
temple10.earthquakeResistant = true;
temple10.pilgrimageRoute = "Hampi Circuit";
temple10.digitalDarshan = true;
temple10.templeTrust = "Virupaksha Temple Trust";
temple10.annualBudget = 135000000.00;
temple10.emergencyContact = "08394-241362";

System.out.println("Temple ID: " + temple10.templeId);
System.out.println("Location: " + temple10.location);
System.out.println("State: " + temple10.state);
System.out.println("Active Status: " + temple10.activeStatus);
System.out.println("Construction Date: " + temple10.constructionDate);
System.out.println("Last Renovation: " + temple10.lastRenovationDate);
System.out.println("Renovation Due: " + temple10.renovationDue);
System.out.println("Deity Name: " + temple10.deityName);
System.out.println("Architecture Style: " + temple10.architectureStyle);
System.out.println("Area: " + temple10.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple10.mainDeity);
System.out.println("Heritage Site: " + temple10.heritageSite);
System.out.println("Annual Visitors: " + temple10.annualVisitors);
System.out.println("Presiding Deity: " + temple10.presidingDeity);
System.out.println("Pilgrimage Center: " + temple10.pilgrimageCenter);
System.out.println("Festivals Count: " + temple10.festivalsCount);
System.out.println("Annual Donations: " + temple10.annualDonations);
System.out.println("Geographical Zone: " + temple10.geographicalZone);
System.out.println("Water Body: " + temple10.waterBody);
System.out.println("Primary Stone: " + temple10.primaryStone);
System.out.println("Gopura Height: " + temple10.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple10.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple10.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple10.digitalDarshan);
System.out.println("Temple Trust: " + temple10.templeTrust);
System.out.println("Annual Budget: " + temple10.annualBudget);
System.out.println("Emergency Contact: " + temple10.emergencyContact);
System.out.println("================================");


Temple temple11 = new Temple();

temple11.templeId = 311;
temple11.location = "Kashi Vishweshwara Temple";
temple11.state = "Karnataka";
temple11.activeStatus = true;
temple11.constructionDate = "9th Century";
temple11.lastRenovationDate = "2024";
temple11.renovationDue = false;
temple11.deityName = "Lord Shiva";
temple11.architectureStyle = "Kalyan Chalukya";
temple11.areaSquareFeet = 24000;
temple11.mainDeity = "Kashi Vishweshwara";
temple11.heritageSite = true;
temple11.annualVisitors = 1800000;
temple11.presidingDeity = "Shiva";
temple11.pilgrimageCenter = true;
temple11.festivalsCount = 13;
temple11.annualDonations = 165000000.00;
temple11.geographicalZone = "North Karnataka";
temple11.waterBody = true;
temple11.primaryStone = "Basalt";
temple11.gopuraHeight = 88;
temple11.earthquakeResistant = true;
temple11.pilgrimageRoute = "Lakshmeshwar Circuit";
temple11.digitalDarshan = true;
temple11.templeTrust = "Kashi Vishweshwara Trust";
temple11.annualBudget = 68000000.00;
temple11.emergencyContact = "08360-278021";

System.out.println("Temple ID: " + temple11.templeId);
System.out.println("Location: " + temple11.location);
System.out.println("State: " + temple11.state);
System.out.println("Active Status: " + temple11.activeStatus);
System.out.println("Construction Date: " + temple11.constructionDate);
System.out.println("Last Renovation: " + temple11.lastRenovationDate);
System.out.println("Renovation Due: " + temple11.renovationDue);
System.out.println("Deity Name: " + temple11.deityName);
System.out.println("Architecture Style: " + temple11.architectureStyle);
System.out.println("Area: " + temple11.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple11.mainDeity);
System.out.println("Heritage Site: " + temple11.heritageSite);
System.out.println("Annual Visitors: " + temple11.annualVisitors);
System.out.println("Presiding Deity: " + temple11.presidingDeity);
System.out.println("Pilgrimage Center: " + temple11.pilgrimageCenter);
System.out.println("Festivals Count: " + temple11.festivalsCount);
System.out.println("Annual Donations: " + temple11.annualDonations);
System.out.println("Geographical Zone: " + temple11.geographicalZone);
System.out.println("Water Body: " + temple11.waterBody);
System.out.println("Primary Stone: " + temple11.primaryStone);
System.out.println("Gopura Height: " + temple11.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple11.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple11.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple11.digitalDarshan);
System.out.println("Temple Trust: " + temple11.templeTrust);
System.out.println("Annual Budget: " + temple11.annualBudget);
System.out.println("Emergency Contact: " + temple11.emergencyContact);
System.out.println("================================");


Temple temple12 = new Temple();

temple12.templeId = 312;
temple12.location = "Chennakesava Temple";
temple12.state = "Karnataka";
temple12.activeStatus = true;
temple12.constructionDate = "1117 CE";
temple12.lastRenovationDate = "2025";
temple12.renovationDue = false;
temple12.deityName = "Lord Vishnu";
temple12.architectureStyle = "Hoysala Star-shaped";
temple12.areaSquareFeet = 41000;
temple12.mainDeity = "Chennakesava";
temple12.heritageSite = true;
temple12.annualVisitors = 1500000;
temple12.presidingDeity = "Vishnu Kesava";
temple12.pilgrimageCenter = true;
temple12.festivalsCount = 11;
temple12.annualDonations = 82000000.00;
temple12.geographicalZone = "Malnad Region";
temple12.waterBody = true;
temple12.primaryStone = "Soapstone";
temple12.gopuraHeight = 120;
temple12.earthquakeResistant = true;
temple12.pilgrimageRoute = "Belur-Halebidu Circuit";
temple12.digitalDarshan = true;
temple12.templeTrust = "ASI Protected Monument";
temple12.annualBudget = 58000000.00;
temple12.emergencyContact = "08177-268402";

System.out.println("Temple ID: " + temple12.templeId);
System.out.println("Location: " + temple12.location);
System.out.println("State: " + temple12.state);
System.out.println("Active Status: " + temple12.activeStatus);
System.out.println("Construction Date: " + temple12.constructionDate);
System.out.println("Last Renovation: " + temple12.lastRenovationDate);
System.out.println("Renovation Due: " + temple12.renovationDue);
System.out.println("Deity Name: " + temple12.deityName);
System.out.println("Architecture Style: " + temple12.architectureStyle);
System.out.println("Area: " + temple12.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple12.mainDeity);
System.out.println("Heritage Site: " + temple12.heritageSite);
System.out.println("Annual Visitors: " + temple12.annualVisitors);
System.out.println("Presiding Deity: " + temple12.presidingDeity);
System.out.println("Pilgrimage Center: " + temple12.pilgrimageCenter);
System.out.println("Festivals Count: " + temple12.festivalsCount);
System.out.println("Annual Donations: " + temple12.annualDonations);
System.out.println("Geographical Zone: " + temple12.geographicalZone);
System.out.println("Water Body: " + temple12.waterBody);
System.out.println("Primary Stone: " + temple12.primaryStone);
System.out.println("Gopura Height: " + temple12.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple12.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple12.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple12.digitalDarshan);
System.out.println("Temple Trust: " + temple12.templeTrust);
System.out.println("Annual Budget: " + temple12.annualBudget);
System.out.println("Emergency Contact: " + temple12.emergencyContact);
System.out.println("================================");


Temple temple13 = new Temple();

temple13.templeId = 313;
temple13.location = "Nanjangud Srikanteshwara Temple";
temple13.state = "Karnataka";
temple13.activeStatus = true;
temple13.constructionDate = "9th Century";
temple13.lastRenovationDate = "2025";
temple13.renovationDue = false;
temple13.deityName = "Lord Shiva";
temple13.architectureStyle = "Dravidian";
temple13.areaSquareFeet = 65000;
temple13.mainDeity = "Srikanteshwara";
temple13.heritageSite = true;
temple13.annualVisitors = 2800000;
temple13.presidingDeity = "Shiva Linga";
temple13.pilgrimageCenter = true;
temple13.festivalsCount = 20;
temple13.annualDonations = 245000000.00;
temple13.geographicalZone = "Mysore Plateau";
temple13.waterBody = true;
temple13.primaryStone = "Granite";
temple13.gopuraHeight = 120;
temple13.earthquakeResistant = true;
temple13.pilgrimageRoute = "Mysore-Nanjangud";
temple13.digitalDarshan = true;
temple13.templeTrust = "Srikanteshwara Temple Board";
temple13.annualBudget = 112000000.00;
temple13.emergencyContact = "08221-233202";

System.out.println("Temple ID: " + temple13.templeId);
System.out.println("Location: " + temple13.location);
System.out.println("State: " + temple13.state);
System.out.println("Active Status: " + temple13.activeStatus);
System.out.println("Construction Date: " + temple13.constructionDate);
System.out.println("Last Renovation: " + temple13.lastRenovationDate);
System.out.println("Renovation Due: " + temple13.renovationDue);
System.out.println("Deity Name: " + temple13.deityName);
System.out.println("Architecture Style: " + temple13.architectureStyle);
System.out.println("Area: " + temple13.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple13.mainDeity);
System.out.println("Heritage Site: " + temple13.heritageSite);
System.out.println("Annual Visitors: " + temple13.annualVisitors);
System.out.println("Presiding Deity: " + temple13.presidingDeity);
System.out.println("Pilgrimage Center: " + temple13.pilgrimageCenter);
System.out.println("Festivals Count: " + temple13.festivalsCount);
System.out.println("Annual Donations: " + temple13.annualDonations);
System.out.println("Geographical Zone: " + temple13.geographicalZone);
System.out.println("Water Body: " + temple13.waterBody);
System.out.println("Primary Stone: " + temple13.primaryStone);
System.out.println("Gopura Height: " + temple13.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple13.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple13.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple13.digitalDarshan);
System.out.println("Temple Trust: " + temple13.templeTrust);
System.out.println("Annual Budget: " + temple13.annualBudget);
System.out.println("Emergency Contact: " + temple13.emergencyContact);
System.out.println("================================");


Temple temple14 = new Temple();

temple14.templeId = 314;
temple14.location = "Rameshwara Temple Keladi";
temple14.state = "Karnataka";
temple14.activeStatus = true;
temple14.constructionDate = "1499 CE";
temple14.lastRenovationDate = "2024";
temple14.renovationDue = false;
temple14.deityName = "Lord Shiva";
temple14.architectureStyle = "Hoysala-Dravida";
temple14.areaSquareFeet = 32000;
temple14.mainDeity = "Rameshwara";
temple14.heritageSite = true;
temple14.annualVisitors = 750000;
temple14.presidingDeity = "Shiva";
temple14.pilgrimageCenter = true;
temple14.festivalsCount = 12;
temple14.annualDonations = 72000000.00;
temple14.geographicalZone = "Malnad";
temple14.waterBody = true;
temple14.primaryStone = "Granite";
temple14.gopuraHeight = 95;
temple14.earthquakeResistant = true;
temple14.pilgrimageRoute = "Keladi-Aghoreshwara";
temple14.digitalDarshan = true;
temple14.templeTrust = "ASI Protected";
temple14.annualBudget = 42000000.00;
temple14.emergencyContact = "08187-248022";

System.out.println("Temple ID: " + temple14.templeId);
System.out.println("Location: " + temple14.location);
System.out.println("State: " + temple14.state);
System.out.println("Active Status: " + temple14.activeStatus);
System.out.println("Construction Date: " + temple14.constructionDate);
System.out.println("Last Renovation: " + temple14.lastRenovationDate);
System.out.println("Renovation Due: " + temple14.renovationDue);
System.out.println("Deity Name: " + temple14.deityName);
System.out.println("Architecture Style: " + temple14.architectureStyle);
System.out.println("Area: " + temple14.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple14.mainDeity);
System.out.println("Heritage Site: " + temple14.heritageSite);
System.out.println("Annual Visitors: " + temple14.annualVisitors);
System.out.println("Presiding Deity: " + temple14.presidingDeity);
System.out.println("Pilgrimage Center: " + temple14.pilgrimageCenter);
System.out.println("Festivals Count: " + temple14.festivalsCount);
System.out.println("Annual Donations: " + temple14.annualDonations);
System.out.println("Geographical Zone: " + temple14.geographicalZone);
System.out.println("Water Body: " + temple14.waterBody);
System.out.println("Primary Stone: " + temple14.primaryStone);
System.out.println("Gopura Height: " + temple14.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple14.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple14.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple14.digitalDarshan);
System.out.println("Temple Trust: " + temple14.templeTrust);
System.out.println("Annual Budget: " + temple14.annualBudget);
System.out.println("Emergency Contact: " + temple14.emergencyContact);
System.out.println("================================");



Temple temple15 = new Temple();

temple15.templeId = 315;
temple15.location = "Kotilingeshwara Temple";
temple15.state = "Karnataka";
temple15.activeStatus = true;
temple15.constructionDate = "1980 CE";
temple15.lastRenovationDate = "2025";
temple15.renovationDue = false;
temple15.deityName = "Lord Shiva";
temple15.architectureStyle = "Modern Dravidian";
temple15.areaSquareFeet = 150000;
temple15.mainDeity = "Kotilingeshwara";
temple15.heritageSite = false;
temple15.annualVisitors = 2000000;
temple15.presidingDeity = "108ft Shiva Linga";
temple15.pilgrimageCenter = true;
temple15.festivalsCount = 10;
temple15.annualDonations = 95000000.00;
temple15.geographicalZone = "Kolar Plateau";
temple15.waterBody = true;
temple15.primaryStone = "Granite";
temple15.gopuraHeight = 110;
temple15.earthquakeResistant = true;
temple15.pilgrimageRoute = "Kolar-Mulbagal";
temple15.digitalDarshan = true;
temple15.templeTrust = "Kotilingeshwara Trust";
temple15.annualBudget = 65000000.00;
temple15.emergencyContact = "08152-262221";

System.out.println("Temple ID: " + temple15.templeId);
System.out.println("Location: " + temple15.location);
System.out.println("State: " + temple15.state);
System.out.println("Active Status: " + temple15.activeStatus);
System.out.println("Construction Date: " + temple15.constructionDate);
System.out.println("Last Renovation: " + temple15.lastRenovationDate);
System.out.println("Renovation Due: " + temple15.renovationDue);
System.out.println("Deity Name: " + temple15.deityName);
System.out.println("Architecture Style: " + temple15.architectureStyle);
System.out.println("Area: " + temple15.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple15.mainDeity);
System.out.println("Heritage Site: " + temple15.heritageSite);
System.out.println("Annual Visitors: " + temple15.annualVisitors);
System.out.println("Presiding Deity: " + temple15.presidingDeity);
System.out.println("Pilgrimage Center: " + temple15.pilgrimageCenter);
System.out.println("Festivals Count: " + temple15.festivalsCount);
System.out.println("Annual Donations: " + temple15.annualDonations);
System.out.println("Geographical Zone: " + temple15.geographicalZone);
System.out.println("Water Body: " + temple15.waterBody);
System.out.println("Primary Stone: " + temple15.primaryStone);
System.out.println("Gopura Height: " + temple15.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple15.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple15.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple15.digitalDarshan);
System.out.println("Temple Trust: " + temple15.templeTrust);
System.out.println("Annual Budget: " + temple15.annualBudget);
System.out.println("Emergency Contact: " + temple15.emergencyContact);
System.out.println("================================");


Temple temple16 = new Temple();

temple16.templeId = 316;
temple16.location = "Mahabaleshwar Temple";
temple16.state = "Karnataka";
temple16.activeStatus = true;
temple16.constructionDate = "4th Century";
temple16.lastRenovationDate = "2024";
temple16.renovationDue = false;
temple16.deityName = "Lord Shiva";
temple16.architectureStyle = "Kadamba-Karavada";
temple16.areaSquareFeet = 28000;
temple16.mainDeity = "Mahabaleshwar";
temple16.heritageSite = true;
temple16.annualVisitors = 3200000;
temple16.presidingDeity = "Atma Linga";
temple16.pilgrimageCenter = true;
temple16.festivalsCount = 18;
temple16.annualDonations = 210000000.00;
temple16.geographicalZone = "Coastal Karnataka";
temple16.waterBody = true;
temple16.primaryStone = "Basalt";
temple16.gopuraHeight = 75;
temple16.earthquakeResistant = true;
temple16.pilgrimageRoute = "Gokarna Circuit";
temple16.digitalDarshan = true;
temple16.templeTrust = "Mahabaleshwar Temple Trust";
temple16.annualBudget = 98000000.00;
temple16.emergencyContact = "08386-257202";

System.out.println("Temple ID: " + temple16.templeId);
System.out.println("Location: " + temple16.location);
System.out.println("State: " + temple16.state);
System.out.println("Active Status: " + temple16.activeStatus);
System.out.println("Construction Date: " + temple16.constructionDate);
System.out.println("Last Renovation: " + temple16.lastRenovationDate);
System.out.println("Renovation Due: " + temple16.renovationDue);
System.out.println("Deity Name: " + temple16.deityName);
System.out.println("Architecture Style: " + temple16.architectureStyle);
System.out.println("Area: " + temple16.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple16.mainDeity);
System.out.println("Heritage Site: " + temple16.heritageSite);
System.out.println("Annual Visitors: " + temple16.annualVisitors);
System.out.println("Presiding Deity: " + temple16.presidingDeity);
System.out.println("Pilgrimage Center: " + temple16.pilgrimageCenter);
System.out.println("Festivals Count: " + temple16.festivalsCount);
System.out.println("Annual Donations: " + temple16.annualDonations);
System.out.println("Geographical Zone: " + temple16.geographicalZone);
System.out.println("Water Body: " + temple16.waterBody);
System.out.println("Primary Stone: " + temple16.primaryStone);
System.out.println("Gopura Height: " + temple16.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple16.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple16.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple16.digitalDarshan);
System.out.println("Temple Trust: " + temple16.templeTrust);
System.out.println("Annual Budget: " + temple16.annualBudget);
System.out.println("Emergency Contact: " + temple16.emergencyContact);
System.out.println("================================");

Temple temple17 = new Temple();

temple17.templeId = 317;
temple17.location = "Kollur Mookambika Temple";
temple17.state = "Karnataka";
temple17.activeStatus = true;
temple17.constructionDate = "9th Century";
temple17.lastRenovationDate = "2025";
temple17.renovationDue = false;
temple17.deityName = "Goddess Mookambika";
temple17.architectureStyle = "Kerala-Dravida";
temple17.areaSquareFeet = 45000;
temple17.mainDeity = "Mookambika Devi";
temple17.heritageSite = true;
temple17.annualVisitors = 4500000;
temple17.presidingDeity = "Adi Shakti";
temple17.pilgrimageCenter = true;
temple17.festivalsCount = 22;
temple17.annualDonations = 375000000.00;
temple17.geographicalZone = "Western Ghats";
temple17.waterBody = true;
temple17.primaryStone = "Granite";
temple17.gopuraHeight = 135;
temple17.earthquakeResistant = true;
temple17.pilgrimageRoute = "Kollur-Sringeri";
temple17.digitalDarshan = true;
temple17.templeTrust = "Mookambika Temple Board";
temple17.annualBudget = 145000000.00;
temple17.emergencyContact = "08254-233200";

System.out.println("Temple ID: " + temple17.templeId);
System.out.println("Location: " + temple17.location);
System.out.println("State: " + temple17.state);
System.out.println("Active Status: " + temple17.activeStatus);
System.out.println("Construction Date: " + temple17.constructionDate);
System.out.println("Last Renovation: " + temple17.lastRenovationDate);
System.out.println("Renovation Due: " + temple17.renovationDue);
System.out.println("Deity Name: " + temple17.deityName);
System.out.println("Architecture Style: " + temple17.architectureStyle);
System.out.println("Area: " + temple17.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple17.mainDeity);
System.out.println("Heritage Site: " + temple17.heritageSite);
System.out.println("Annual Visitors: " + temple17.annualVisitors);
System.out.println("Presiding Deity: " + temple17.presidingDeity);
System.out.println("Pilgrimage Center: " + temple17.pilgrimageCenter);
System.out.println("Festivals Count: " + temple17.festivalsCount);
System.out.println("Annual Donations: " + temple17.annualDonations);
System.out.println("Geographical Zone: " + temple17.geographicalZone);
System.out.println("Water Body: " + temple17.waterBody);
System.out.println("Primary Stone: " + temple17.primaryStone);
System.out.println("Gopura Height: " + temple17.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple17.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple17.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple17.digitalDarshan);
System.out.println("Temple Trust: " + temple17.templeTrust);
System.out.println("Annual Budget: " + temple17.annualBudget);
System.out.println("Emergency Contact: " + temple17.emergencyContact);
System.out.println("================================");

Temple temple18 = new Temple();

temple18.templeId = 318;
temple18.location = "Sringeri Sharada Peetham";
temple18.state = "Karnataka";
temple18.activeStatus = true;
temple18.constructionDate = "8th Century";
temple18.lastRenovationDate = "2024";
temple18.renovationDue = false;
temple18.deityName = "Goddess Sharadamba";
temple18.architectureStyle = "Vijayanagara";
temple18.areaSquareFeet = 38000;
temple18.mainDeity = "Sharadamba";
temple18.heritageSite = true;
temple18.annualVisitors = 2200000;
temple18.presidingDeity = "Sarada Devi";
temple18.pilgrimageCenter = true;
temple18.festivalsCount = 25;
temple18.annualDonations = 285000000.00;
temple18.geographicalZone = "Western Ghats";
temple18.waterBody = true;
temple18.primaryStone = "Granite";
temple18.gopuraHeight = 105;
temple18.earthquakeResistant = true;
temple18.pilgrimageRoute = "Sringeri-Kollur";
temple18.digitalDarshan = true;
temple18.templeTrust = "Sringeri Sharada Peetham";
temple18.annualBudget = 125000000.00;
temple18.emergencyContact = "08265-250243";

System.out.println("Temple ID: " + temple18.templeId);
System.out.println("Location: " + temple18.location);
System.out.println("State: " + temple18.state);
System.out.println("Active Status: " + temple18.activeStatus);
System.out.println("Construction Date: " + temple18.constructionDate);
System.out.println("Last Renovation: " + temple18.lastRenovationDate);
System.out.println("Renovation Due: " + temple18.renovationDue);
System.out.println("Deity Name: " + temple18.deityName);
System.out.println("Architecture Style: " + temple18.architectureStyle);
System.out.println("Area: " + temple18.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple18.mainDeity);
System.out.println("Heritage Site: " + temple18.heritageSite);
System.out.println("Annual Visitors: " + temple18.annualVisitors);
System.out.println("Presiding Deity: " + temple18.presidingDeity);
System.out.println("Pilgrimage Center: " + temple18.pilgrimageCenter);
System.out.println("Festivals Count: " + temple18.festivalsCount);
System.out.println("Annual Donations: " + temple18.annualDonations);
System.out.println("Geographical Zone: " + temple18.geographicalZone);
System.out.println("Water Body: " + temple18.waterBody);
System.out.println("Primary Stone: " + temple18.primaryStone);
System.out.println("Gopura Height: " + temple18.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple18.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple18.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple18.digitalDarshan);
System.out.println("Temple Trust: " + temple18.templeTrust);
System.out.println("Annual Budget: " + temple18.annualBudget);
System.out.println("Emergency Contact: " + temple18.emergencyContact);
System.out.println("================================");


Temple temple19 = new Temple();

temple19.templeId = 319;
temple19.location = "Annapoorneshwari Temple Horanadu";
temple19.state = "Karnataka";
temple19.activeStatus = true;
temple19.constructionDate = "9th Century";
temple19.lastRenovationDate = "2025";
temple19.renovationDue = false;
temple19.deityName = "Goddess Annapoorneshwari";
temple19.architectureStyle = "Vijayanagara";
temple19.areaSquareFeet = 52000;
temple19.mainDeity = "Annapoorneshwari";
temple19.heritageSite = true;
temple19.annualVisitors = 3800000;
temple19.presidingDeity = "Food Goddess";
temple19.pilgrimageCenter = true;
temple19.festivalsCount = 16;
temple19.annualDonations = 265000000.00;
temple19.geographicalZone = "Western Ghats";
temple19.waterBody = true;
temple19.primaryStone = "Granite";
temple19.gopuraHeight = 98;
temple19.earthquakeResistant = true;
temple19.pilgrimageRoute = "Horanadu-Kalasa";
temple19.digitalDarshan = true;
temple19.templeTrust = "Annapoorneshwari Temple Trust";
temple19.annualBudget = 118000000.00;
temple19.emergencyContact = "08266-263230";

System.out.println("Temple ID: " + temple19.templeId);
System.out.println("Location: " + temple19.location);
System.out.println("State: " + temple19.state);
System.out.println("Active Status: " + temple19.activeStatus);
System.out.println("Construction Date: " + temple19.constructionDate);
System.out.println("Last Renovation: " + temple19.lastRenovationDate);
System.out.println("Renovation Due: " + temple19.renovationDue);
System.out.println("Deity Name: " + temple19.deityName);
System.out.println("Architecture Style: " + temple19.architectureStyle);
System.out.println("Area: " + temple19.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple19.mainDeity);
System.out.println("Heritage Site: " + temple19.heritageSite);
System.out.println("Annual Visitors: " + temple19.annualVisitors);
System.out.println("Presiding Deity: " + temple19.presidingDeity);
System.out.println("Pilgrimage Center: " + temple19.pilgrimageCenter);
System.out.println("Festivals Count: " + temple19.festivalsCount);
System.out.println("Annual Donations: " + temple19.annualDonations);
System.out.println("Geographical Zone: " + temple19.geographicalZone);
System.out.println("Water Body: " + temple19.waterBody);
System.out.println("Primary Stone: " + temple19.primaryStone);
System.out.println("Gopura Height: " + temple19.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple19.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple19.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple19.digitalDarshan);
System.out.println("Temple Trust: " + temple19.templeTrust);
System.out.println("Annual Budget: " + temple19.annualBudget);
System.out.println("Emergency Contact: " + temple19.emergencyContact);
System.out.println("================================");


Temple temple20 = new Temple();

temple20.templeId = 320;
temple20.location = "Ghati Subramanya Temple";
temple20.state = "Karnataka";
temple20.activeStatus = true;
temple20.constructionDate = "Ancient Times";
temple20.lastRenovationDate = "2024";
temple20.renovationDue = false;
temple20.deityName = "Lord Subramanya";
temple20.architectureStyle = "Dravidian";
temple20.areaSquareFeet = 42000;
temple20.mainDeity = "Subramanya";
temple20.heritageSite = true;
temple20.annualVisitors = 2900000;
temple20.presidingDeity = "Kartikeya-Shesha";
temple20.pilgrimageCenter = true;
temple20.festivalsCount = 19;
temple20.annualDonations = 198000000.00;
temple20.geographicalZone = "Bangalore Rural";
temple20.waterBody = true;
temple20.primaryStone = "Granite";
temple20.gopuraHeight = 115;
temple20.earthquakeResistant = true;
temple20.pilgrimageRoute = "Dodballapur Circuit";
temple20.digitalDarshan = true;
temple20.templeTrust = "Ghati Subramanya Temple Trust";
temple20.annualBudget = 92000000.00;
temple20.emergencyContact = "080-27641167";

System.out.println("Temple ID: " + temple20.templeId);
System.out.println("Location: " + temple20.location);
System.out.println("State: " + temple20.state);
System.out.println("Active Status: " + temple20.activeStatus);
System.out.println("Construction Date: " + temple20.constructionDate);
System.out.println("Last Renovation: " + temple20.lastRenovationDate);
System.out.println("Renovation Due: " + temple20.renovationDue);
System.out.println("Deity Name: " + temple20.deityName);
System.out.println("Architecture Style: " + temple20.architectureStyle);
System.out.println("Area: " + temple20.areaSquareFeet + " sq.ft");
System.out.println("Main Deity: " + temple20.mainDeity);
System.out.println("Heritage Site: " + temple20.heritageSite);
System.out.println("Annual Visitors: " + temple20.annualVisitors);
System.out.println("Presiding Deity: " + temple20.presidingDeity);
System.out.println("Pilgrimage Center: " + temple20.pilgrimageCenter);
System.out.println("Festivals Count: " + temple20.festivalsCount);
System.out.println("Annual Donations: " + temple20.annualDonations);
System.out.println("Geographical Zone: " + temple20.geographicalZone);
System.out.println("Water Body: " + temple20.waterBody);
System.out.println("Primary Stone: " + temple20.primaryStone);
System.out.println("Gopura Height: " + temple20.gopuraHeight + " feet");
System.out.println("Earthquake Resistant: " + temple20.earthquakeResistant);
System.out.println("Pilgrimage Route: " + temple20.pilgrimageRoute);
System.out.println("Digital Darshan: " + temple20.digitalDarshan);
System.out.println("Temple Trust: " + temple20.templeTrust);
System.out.println("Annual Budget: " + temple20.annualBudget);
System.out.println("Emergency Contact: " + temple20.emergencyContact);
System.out.println("================================");

	
		
		
    }
}
