class TrafficSignalExecutor {
    public static void main(String[] args) {
        TrafficSignal signal1 = new TrafficSignal();
        
        signal1.signalId = 101;
        signal1.location = "MG Road Junction";
        signal1.city = "Bengaluru";
        signal1.operationalStatus = true;
        signal1.installationDate = "15/01/2025";
        signal1.lastMaintenanceDate = "28/02/2026";
        signal1.maintenanceDue = false;
        signal1.manufacturer = "Siemens";
        signal1.model = "ST-4000";
        signal1.signalHeight = 5;
        signal1.powerSource = "Solar + Grid";
        signal1.solarPowered = true;
        signal1.lightIntensity = 5000;
        signal1.controlType = "Adaptive";
        signal1.pedestrianSignal = true;
        signal1.cycleDuration = 120;
        signal1.powerConsumption = 150.5;
        signal1.weatherRating = "IP65";
        signal1.waterproof = true;
        signal1.ledType = "High Brightness LED";
        signal1.ledCount = 48;
        signal1.adaptiveTiming = true;
        signal1.trafficDirection = "4-Way";
        signal1.cameraIntegrated = true;
        signal1.signalGroup = "Group-A";
        signal1.maintenanceCost = 8500.00;
        signal1.emergencyContact = "080-25501234";
        
        System.out.println("Signal ID: " + signal1.signalId);
        System.out.println("Location: " + signal1.location);
        System.out.println("City: " + signal1.city);
        System.out.println("Operational Status: " + signal1.operationalStatus);
        System.out.println("Installation Date: " + signal1.installationDate);
        System.out.println("Last Maintenance: " + signal1.lastMaintenanceDate);
        System.out.println("Maintenance Due: " + signal1.maintenanceDue);
        System.out.println("Manufacturer: " + signal1.manufacturer);
        System.out.println("Model: " + signal1.model);
        System.out.println("Signal Height: " + signal1.signalHeight + " meters");
        System.out.println("Power Source: " + signal1.powerSource);
        System.out.println("Solar Powered: " + signal1.solarPowered);
        System.out.println("Light Intensity: " + signal1.lightIntensity + " lumens");
        System.out.println("Control Type: " + signal1.controlType);
        System.out.println("Pedestrian Signal: " + signal1.pedestrianSignal);
        System.out.println("Cycle Duration: " + signal1.cycleDuration + " seconds");
        System.out.println("Power Consumption: " + signal1.powerConsumption + " watts");
        System.out.println("Weather Rating: " + signal1.weatherRating);
        System.out.println("Waterproof: " + signal1.waterproof);
        System.out.println("LED Type: " + signal1.ledType);
        System.out.println("LED Count: " + signal1.ledCount);
        System.out.println("Adaptive Timing: " + signal1.adaptiveTiming);
        System.out.println("Traffic Direction: " + signal1.trafficDirection);
        System.out.println("Camera Integrated: " + signal1.cameraIntegrated);
        System.out.println("Signal Group: " + signal1.signalGroup);
        System.out.println("Maintenance Cost: " + signal1.maintenanceCost);
        System.out.println("Emergency Contact: " + signal1.emergencyContact);
        System.out.println("================================");
		
TrafficSignal signal2 = new TrafficSignal();

signal2.signalId = 102;
signal2.location = "Brigade Road Intersection";
signal2.city = "Bengaluru";
signal2.operationalStatus = true;
signal2.installationDate = "20/02/2025";
signal2.lastMaintenanceDate = "01/03/2026";
signal2.maintenanceDue = true;
signal2.manufacturer = "Schneider";
signal2.model = "TS-3000";
signal2.signalHeight = 4;
signal2.powerSource = "Grid";
signal2.solarPowered = false;
signal2.lightIntensity = 4500;
signal2.controlType = "Fixed";
signal2.pedestrianSignal = true;
signal2.cycleDuration = 90;
signal2.powerConsumption = 120.0;
signal2.weatherRating = "IP67";
signal2.waterproof = true;
signal2.ledType = "Standard LED";
signal2.ledCount = 36;
signal2.adaptiveTiming = false;
signal2.trafficDirection = "3-Way";
signal2.cameraIntegrated = false;
signal2.signalGroup = "Group-B";
signal2.maintenanceCost = 7200.00;
signal2.emergencyContact = "080-26789012";

System.out.println("Signal ID: " + signal2.signalId);
System.out.println("Location: " + signal2.location);
System.out.println("City: " + signal2.city);
System.out.println("Operational Status: " + signal2.operationalStatus);
System.out.println("Installation Date: " + signal2.installationDate);
System.out.println("Last Maintenance: " + signal2.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal2.maintenanceDue);
System.out.println("Manufacturer: " + signal2.manufacturer);
System.out.println("Model: " + signal2.model);
System.out.println("Signal Height: " + signal2.signalHeight + " meters");
System.out.println("Power Source: " + signal2.powerSource);
System.out.println("Solar Powered: " + signal2.solarPowered);
System.out.println("Light Intensity: " + signal2.lightIntensity + " lumens");
System.out.println("Control Type: " + signal2.controlType);
System.out.println("Pedestrian Signal: " + signal2.pedestrianSignal);
System.out.println("Cycle Duration: " + signal2.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal2.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal2.weatherRating);
System.out.println("Waterproof: " + signal2.waterproof);
System.out.println("LED Type: " + signal2.ledType);
System.out.println("LED Count: " + signal2.ledCount);
System.out.println("Adaptive Timing: " + signal2.adaptiveTiming);
System.out.println("Traffic Direction: " + signal2.trafficDirection);
System.out.println("Camera Integrated: " + signal2.cameraIntegrated);
System.out.println("Signal Group: " + signal2.signalGroup);
System.out.println("Maintenance Cost: " + signal2.maintenanceCost);
System.out.println("Emergency Contact: " + signal2.emergencyContact);
System.out.println("================================");

TrafficSignal signal3 = new TrafficSignal();

signal3.signalId = 103;
signal3.location = "Electronic City Flyover";
signal3.city = "Bengaluru";
signal3.operationalStatus = false;
signal3.installationDate = "10/12/2024";
signal3.lastMaintenanceDate = "15/02/2026";
signal3.maintenanceDue = true;
signal3.manufacturer = "Honeywell";
signal3.model = "HTS-5000";
signal3.signalHeight = 6;
signal3.powerSource = "Solar";
signal3.solarPowered = true;
signal3.lightIntensity = 6000;
signal3.controlType = "AI Adaptive";
signal3.pedestrianSignal = false;
signal3.cycleDuration = 150;
signal3.powerConsumption = 180.0;
signal3.weatherRating = "IP68";
signal3.waterproof = true;
signal3.ledType = "Smart LED";
signal3.ledCount = 60;
signal3.adaptiveTiming = true;
signal3.trafficDirection = "2-Way";
signal3.cameraIntegrated = true;
signal3.signalGroup = "Group-C";
signal3.maintenanceCost = 12000.00;
signal3.emergencyContact = "080-27890123";

System.out.println("Signal ID: " + signal3.signalId);
System.out.println("Location: " + signal3.location);
System.out.println("City: " + signal3.city);
System.out.println("Operational Status: " + signal3.operationalStatus);
System.out.println("Installation Date: " + signal3.installationDate);
System.out.println("Last Maintenance: " + signal3.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal3.maintenanceDue);
System.out.println("Manufacturer: " + signal3.manufacturer);
System.out.println("Model: " + signal3.model);
System.out.println("Signal Height: " + signal3.signalHeight + " meters");
System.out.println("Power Source: " + signal3.powerSource);
System.out.println("Solar Powered: " + signal3.solarPowered);
System.out.println("Light Intensity: " + signal3.lightIntensity + " lumens");
System.out.println("Control Type: " + signal3.controlType);
System.out.println("Pedestrian Signal: " + signal3.pedestrianSignal);
System.out.println("Cycle Duration: " + signal3.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal3.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal3.weatherRating);
System.out.println("Waterproof: " + signal3.waterproof);
System.out.println("LED Type: " + signal3.ledType);
System.out.println("LED Count: " + signal3.ledCount);
System.out.println("Adaptive Timing: " + signal3.adaptiveTiming);
System.out.println("Traffic Direction: " + signal3.trafficDirection);
System.out.println("Camera Integrated: " + signal3.cameraIntegrated);
System.out.println("Signal Group: " + signal3.signalGroup);
System.out.println("Maintenance Cost: " + signal3.maintenanceCost);
System.out.println("Emergency Contact: " + signal3.emergencyContact);
System.out.println("================================");

TrafficSignal signal4 = new TrafficSignal();

signal4.signalId = 104;
signal4.location = "Whitefield Main Road";
signal4.city = "Bengaluru";
signal4.operationalStatus = true;
signal4.installationDate = "05/06/2025";
signal4.lastMaintenanceDate = "03/03/2026";
signal4.maintenanceDue = false;
signal4.manufacturer = "ABB";
signal4.model = "TSX-2000";
signal4.signalHeight = 5;
signal4.powerSource = "Grid";
signal4.solarPowered = false;
signal4.lightIntensity = 5200;
signal4.controlType = "Adaptive";
signal4.pedestrianSignal = true;
signal4.cycleDuration = 135;
signal4.powerConsumption = 165.0;
signal4.weatherRating = "IP66";
signal4.waterproof = true;
signal4.ledType = "Premium LED";
signal4.ledCount = 54;
signal4.adaptiveTiming = true;
signal4.trafficDirection = "4-Way";
signal4.cameraIntegrated = true;
signal4.signalGroup = "Group-D";
signal4.maintenanceCost = 9500.00;
signal4.emergencyContact = "080-28901234";



System.out.println("Signal ID: " + signal4.signalId);
System.out.println("Location: " + signal4.location);
System.out.println("City: " + signal4.city);
System.out.println("Operational Status: " + signal4.operationalStatus);
System.out.println("Installation Date: " + signal4.installationDate);
System.out.println("Last Maintenance: " + signal4.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal4.maintenanceDue);
System.out.println("Manufacturer: " + signal4.manufacturer);
System.out.println("Model: " + signal4.model);
System.out.println("Signal Height: " + signal4.signalHeight + " meters");
System.out.println("Power Source: " + signal4.powerSource);
System.out.println("Solar Powered: " + signal4.solarPowered);
System.out.println("Light Intensity: " + signal4.lightIntensity + " lumens");
System.out.println("Control Type: " + signal4.controlType);
System.out.println("Pedestrian Signal: " + signal4.pedestrianSignal);
System.out.println("Cycle Duration: " + signal4.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal4.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal4.weatherRating);
System.out.println("Waterproof: " + signal4.waterproof);
System.out.println("LED Type: " + signal4.ledType);
System.out.println("LED Count: " + signal4.ledCount);
System.out.println("Adaptive Timing: " + signal4.adaptiveTiming);
System.out.println("Traffic Direction: " + signal4.trafficDirection);
System.out.println("Camera Integrated: " + signal4.cameraIntegrated);
System.out.println("Signal Group: " + signal4.signalGroup);
System.out.println("Maintenance Cost: " + signal4.maintenanceCost);
System.out.println("Emergency Contact: " + signal4.emergencyContact);
System.out.println("================================");


TrafficSignal signal5 = new TrafficSignal();

signal5.signalId = 105;
signal5.location = "Koramangala BDA Complex";
signal5.city = "Bengaluru";
signal5.operationalStatus = true;
signal5.installationDate = "12/08/2025";
signal5.lastMaintenanceDate = "04/03/2026";
signal5.maintenanceDue = false;
signal5.manufacturer = "GE";
signal5.model = "TS-7000";
signal5.signalHeight = 4;
signal5.powerSource = "Solar";
signal5.solarPowered = true;
signal5.lightIntensity = 4800;
signal5.controlType = "Fixed";
signal5.pedestrianSignal = true;
signal5.cycleDuration = 100;
signal5.powerConsumption = 110.0;
signal5.weatherRating = "IP65";
signal5.waterproof = true;
signal5.ledType = "Eco LED";
signal5.ledCount = 42;
signal5.adaptiveTiming = false;
signal5.trafficDirection = "3-Way";
signal5.cameraIntegrated = false;
signal5.signalGroup = "Group-E";
signal5.maintenanceCost = 6800.00;
signal5.emergencyContact = "080-29812345";

System.out.println("Signal ID: " + signal5.signalId);
System.out.println("Location: " + signal5.location);
System.out.println("City: " + signal5.city);
System.out.println("Operational Status: " + signal5.operationalStatus);
System.out.println("Installation Date: " + signal5.installationDate);
System.out.println("Last Maintenance: " + signal5.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal5.maintenanceDue);
System.out.println("Manufacturer: " + signal5.manufacturer);
System.out.println("Model: " + signal5.model);
System.out.println("Signal Height: " + signal5.signalHeight + " meters");
System.out.println("Power Source: " + signal5.powerSource);
System.out.println("Solar Powered: " + signal5.solarPowered);
System.out.println("Light Intensity: " + signal5.lightIntensity + " lumens");
System.out.println("Control Type: " + signal5.controlType);
System.out.println("Pedestrian Signal: " + signal5.pedestrianSignal);
System.out.println("Cycle Duration: " + signal5.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal5.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal5.weatherRating);
System.out.println("Waterproof: " + signal5.waterproof);
System.out.println("LED Type: " + signal5.ledType);
System.out.println("LED Count: " + signal5.ledCount);
System.out.println("Adaptive Timing: " + signal5.adaptiveTiming);
System.out.println("Traffic Direction: " + signal5.trafficDirection);
System.out.println("Camera Integrated: " + signal5.cameraIntegrated);
System.out.println("Signal Group: " + signal5.signalGroup);
System.out.println("Maintenance Cost: ₹" + signal5.maintenanceCost);
System.out.println("Emergency Contact: " + signal5.emergencyContact);
System.out.println("================================");



TrafficSignal signal6 = new TrafficSignal();

signal6.signalId = 106;
signal6.location = "Indiranagar 100 Feet Road";
signal6.city = "Bengaluru";
signal6.operationalStatus = true;
signal6.installationDate = "25/11/2025";
signal6.lastMaintenanceDate = "05/03/2026";
signal6.maintenanceDue = false;
signal6.manufacturer = "Philips";
signal6.model = "PS-9000";
signal6.signalHeight = 5;
signal6.powerSource = "Solar + Grid";
signal6.solarPowered = true;
signal6.lightIntensity = 5500;
signal6.controlType = "Adaptive";
signal6.pedestrianSignal = true;
signal6.cycleDuration = 110;
signal6.powerConsumption = 140.0;
signal6.weatherRating = "IP67";
signal6.waterproof = true;
signal6.ledType = "Ultra Bright LED";
signal6.ledCount = 52;
signal6.adaptiveTiming = true;
signal6.trafficDirection = "4-Way";
signal6.cameraIntegrated = true;
signal6.signalGroup = "Group-F";
signal6.maintenanceCost = 9800.00;
signal6.emergencyContact = "080-30123456";

System.out.println("Signal ID: " + signal6.signalId);
System.out.println("Location: " + signal6.location);
System.out.println("City: " + signal6.city);
System.out.println("Operational Status: " + signal6.operationalStatus);
System.out.println("Installation Date: " + signal6.installationDate);
System.out.println("Last Maintenance: " + signal6.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal6.maintenanceDue);
System.out.println("Manufacturer: " + signal6.manufacturer);
System.out.println("Model: " + signal6.model);
System.out.println("Signal Height: " + signal6.signalHeight + " meters");
System.out.println("Power Source: " + signal6.powerSource);
System.out.println("Solar Powered: " + signal6.solarPowered);
System.out.println("Light Intensity: " + signal6.lightIntensity + " lumens");
System.out.println("Control Type: " + signal6.controlType);
System.out.println("Pedestrian Signal: " + signal6.pedestrianSignal);
System.out.println("Cycle Duration: " + signal6.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal6.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal6.weatherRating);
System.out.println("Waterproof: " + signal6.waterproof);
System.out.println("LED Type: " + signal6.ledType);
System.out.println("LED Count: " + signal6.ledCount);
System.out.println("Adaptive Timing: " + signal6.adaptiveTiming);
System.out.println("Traffic Direction: " + signal6.trafficDirection);
System.out.println("Camera Integrated: " + signal6.cameraIntegrated);
System.out.println("Signal Group: " + signal6.signalGroup);
System.out.println("Maintenance Cost: " + signal6.maintenanceCost);
System.out.println("Emergency Contact: " + signal6.emergencyContact);
System.out.println("================================");


TrafficSignal signal7 = new TrafficSignal();

signal7.signalId = 107;
signal7.location = "Jayanagar 4th Block";
signal7.city = "Bengaluru";
signal7.operationalStatus = true;
signal7.installationDate = "18/09/2025";
signal7.lastMaintenanceDate = "02/03/2026";
signal7.maintenanceDue = false;
signal7.manufacturer = "Schneider";
signal7.model = "TS-4500";
signal7.signalHeight = 4;
signal7.powerSource = "Grid";
signal7.solarPowered = false;
signal7.lightIntensity = 4700;
signal7.controlType = "Fixed";
signal7.pedestrianSignal = true;
signal7.cycleDuration = 105;
signal7.powerConsumption = 130.0;
signal7.weatherRating = "IP66";
signal7.waterproof = true;
signal7.ledType = "Standard LED";
signal7.ledCount = 40;
signal7.adaptiveTiming = false;
signal7.trafficDirection = "3-Way";
signal7.cameraIntegrated = false;
signal7.signalGroup = "Group-G";
signal7.maintenanceCost = 7400.00;
signal7.emergencyContact = "080-31234567";

System.out.println("Signal ID: " + signal7.signalId);
System.out.println("Location: " + signal7.location);
System.out.println("City: " + signal7.city);
System.out.println("Operational Status: " + signal7.operationalStatus);
System.out.println("Installation Date: " + signal7.installationDate);
System.out.println("Last Maintenance: " + signal7.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal7.maintenanceDue);
System.out.println("Manufacturer: " + signal7.manufacturer);
System.out.println("Model: " + signal7.model);
System.out.println("Signal Height: " + signal7.signalHeight + " meters");
System.out.println("Power Source: " + signal7.powerSource);
System.out.println("Solar Powered: " + signal7.solarPowered);
System.out.println("Light Intensity: " + signal7.lightIntensity + " lumens");
System.out.println("Control Type: " + signal7.controlType);
System.out.println("Pedestrian Signal: " + signal7.pedestrianSignal);
System.out.println("Cycle Duration: " + signal7.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal7.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal7.weatherRating);
System.out.println("Waterproof: " + signal7.waterproof);
System.out.println("LED Type: " + signal7.ledType);
System.out.println("LED Count: " + signal7.ledCount);
System.out.println("Adaptive Timing: " + signal7.adaptiveTiming);
System.out.println("Traffic Direction: " + signal7.trafficDirection);
System.out.println("Camera Integrated: " + signal7.cameraIntegrated);
System.out.println("Signal Group: " + signal7.signalGroup);
System.out.println("Maintenance Cost: " + signal7.maintenanceCost);
System.out.println("Emergency Contact: " + signal7.emergencyContact);
System.out.println("================================");


TrafficSignal signal8 = new TrafficSignal();

signal8.signalId = 108;
signal8.location = "Malleswaram Circle";
signal8.city = "Bengaluru";
signal8.operationalStatus = false;
signal8.installationDate = "03/04/2025";
signal8.lastMaintenanceDate = "20/02/2026";
signal8.maintenanceDue = true;
signal8.manufacturer = "Siemens";
signal8.model = "ST-6000";
signal8.signalHeight = 6;
signal8.powerSource = "Solar + Grid";
signal8.solarPowered = true;
signal8.lightIntensity = 5800;
signal8.controlType = "Adaptive";
signal8.pedestrianSignal = true;
signal8.cycleDuration = 140;
signal8.powerConsumption = 170.0;
signal8.weatherRating = "IP68";
signal8.waterproof = true;
signal8.ledType = "High Performance LED";
signal8.ledCount = 56;
signal8.adaptiveTiming = true;
signal8.trafficDirection = "5-Way";
signal8.cameraIntegrated = true;
signal8.signalGroup = "Group-H";
signal8.maintenanceCost = 11500.00;
signal8.emergencyContact = "080-32345678";

System.out.println("Signal ID: " + signal8.signalId);
System.out.println("Location: " + signal8.location);
System.out.println("City: " + signal8.city);
System.out.println("Operational Status: " + signal8.operationalStatus);
System.out.println("Installation Date: " + signal8.installationDate);
System.out.println("Last Maintenance: " + signal8.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal8.maintenanceDue);
System.out.println("Manufacturer: " + signal8.manufacturer);
System.out.println("Model: " + signal8.model);
System.out.println("Signal Height: " + signal8.signalHeight + " meters");
System.out.println("Power Source: " + signal8.powerSource);
System.out.println("Solar Powered: " + signal8.solarPowered);
System.out.println("Light Intensity: " + signal8.lightIntensity + " lumens");
System.out.println("Control Type: " + signal8.controlType);
System.out.println("Pedestrian Signal: " + signal8.pedestrianSignal);
System.out.println("Cycle Duration: " + signal8.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal8.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal8.weatherRating);
System.out.println("Waterproof: " + signal8.waterproof);
System.out.println("LED Type: " + signal8.ledType);
System.out.println("LED Count: " + signal8.ledCount);
System.out.println("Adaptive Timing: " + signal8.adaptiveTiming);
System.out.println("Traffic Direction: " + signal8.trafficDirection);
System.out.println("Camera Integrated: " + signal8.cameraIntegrated);
System.out.println("Signal Group: " + signal8.signalGroup);
System.out.println("Maintenance Cost: " + signal8.maintenanceCost);
System.out.println("Emergency Contact: " + signal8.emergencyContact);
System.out.println("================================");


TrafficSignal signal9 = new TrafficSignal();

signal9.signalId = 109;
signal9.location = "Sarjapur Road Signal";
signal9.city = "Bengaluru";
signal9.operationalStatus = true;
signal9.installationDate = "22/07/2025";
signal9.lastMaintenanceDate = "06/03/2026";
signal9.maintenanceDue = false;
signal9.manufacturer = "Honeywell";
signal9.model = "HTS-4000";
signal9.signalHeight = 5;
signal9.powerSource = "Solar";
signal9.solarPowered = true;
signal9.lightIntensity = 5100;
signal9.controlType = "Adaptive";
signal9.pedestrianSignal = false;
signal9.cycleDuration = 125;
signal9.powerConsumption = 155.0;
signal9.weatherRating = "IP67";
signal9.waterproof = true;
signal9.ledType = "Bright LED";
signal9.ledCount = 50;
signal9.adaptiveTiming = true;
signal9.trafficDirection = "4-Way";
signal9.cameraIntegrated = true;
signal9.signalGroup = "Group-I";
signal9.maintenanceCost = 9200.00;
signal9.emergencyContact = "080-33456789";

System.out.println("Signal ID: " + signal9.signalId);
System.out.println("Location: " + signal9.location);
System.out.println("City: " + signal9.city);
System.out.println("Operational Status: " + signal9.operationalStatus);
System.out.println("Installation Date: " + signal9.installationDate);
System.out.println("Last Maintenance: " + signal9.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal9.maintenanceDue);
System.out.println("Manufacturer: " + signal9.manufacturer);
System.out.println("Model: " + signal9.model);
System.out.println("Signal Height: " + signal9.signalHeight + " meters");
System.out.println("Power Source: " + signal9.powerSource);
System.out.println("Solar Powered: " + signal9.solarPowered);
System.out.println("Light Intensity: " + signal9.lightIntensity + " lumens");
System.out.println("Control Type: " + signal9.controlType);
System.out.println("Pedestrian Signal: " + signal9.pedestrianSignal);
System.out.println("Cycle Duration: " + signal9.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal9.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal9.weatherRating);
System.out.println("Waterproof: " + signal9.waterproof);
System.out.println("LED Type: " + signal9.ledType);
System.out.println("LED Count: " + signal9.ledCount);
System.out.println("Adaptive Timing: " + signal9.adaptiveTiming);
System.out.println("Traffic Direction: " + signal9.trafficDirection);
System.out.println("Camera Integrated: " + signal9.cameraIntegrated);
System.out.println("Signal Group: " + signal9.signalGroup);
System.out.println("Maintenance Cost: " + signal9.maintenanceCost);
System.out.println("Emergency Contact: " + signal9.emergencyContact);
System.out.println("================================");

TrafficSignal signal10 = new TrafficSignal();

signal10.signalId = 110;
signal10.location = "Hebbal Flyover";
signal10.city = "Bengaluru";
signal10.operationalStatus = true;
signal10.installationDate = "14/10/2025";
signal10.lastMaintenanceDate = "07/03/2026";
signal10.maintenanceDue = false;
signal10.manufacturer = "ABB";
signal10.model = "TSX-5000";
signal10.signalHeight = 7;
signal10.powerSource = "Solar + Grid";
signal10.solarPowered = true;
signal10.lightIntensity = 6200;
signal10.controlType = "AI Adaptive";
signal10.pedestrianSignal = true;
signal10.cycleDuration = 160;
signal10.powerConsumption = 195.0;
signal10.weatherRating = "IP68";
signal10.waterproof = true;
signal10.ledType = "Super Bright LED";
signal10.ledCount = 64;
signal10.adaptiveTiming = true;
signal10.trafficDirection = "6-Way";
signal10.cameraIntegrated = true;
signal10.signalGroup = "Group-J";
signal10.maintenanceCost = 13500.00;
signal10.emergencyContact = "080-34567890";

System.out.println("Signal ID: " + signal10.signalId);
System.out.println("Location: " + signal10.location);
System.out.println("City: " + signal10.city);
System.out.println("Operational Status: " + signal10.operationalStatus);
System.out.println("Installation Date: " + signal10.installationDate);
System.out.println("Last Maintenance: " + signal10.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal10.maintenanceDue);
System.out.println("Manufacturer: " + signal10.manufacturer);
System.out.println("Model: " + signal10.model);
System.out.println("Signal Height: " + signal10.signalHeight + " meters");
System.out.println("Power Source: " + signal10.powerSource);
System.out.println("Solar Powered: " + signal10.solarPowered);
System.out.println("Light Intensity: " + signal10.lightIntensity + " lumens");
System.out.println("Control Type: " + signal10.controlType);
System.out.println("Pedestrian Signal: " + signal10.pedestrianSignal);
System.out.println("Cycle Duration: " + signal10.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal10.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal10.weatherRating);
System.out.println("Waterproof: " + signal10.waterproof);
System.out.println("LED Type: " + signal10.ledType);
System.out.println("LED Count: " + signal10.ledCount);
System.out.println("Adaptive Timing: " + signal10.adaptiveTiming);
System.out.println("Traffic Direction: " + signal10.trafficDirection);
System.out.println("Camera Integrated: " + signal10.cameraIntegrated);
System.out.println("Signal Group: " + signal10.signalGroup);
System.out.println("Maintenance Cost: " + signal10.maintenanceCost);
System.out.println("Emergency Contact: " + signal10.emergencyContact);
System.out.println("================================");

TrafficSignal signal11 = new TrafficSignal();

signal11.signalId = 111;
signal11.location = "Marathahalli Bridge";
signal11.city = "Bengaluru";
signal11.operationalStatus = true;
signal11.installationDate = "30/05/2025";
signal11.lastMaintenanceDate = "08/03/2026";
signal11.maintenanceDue = false;
signal11.manufacturer = "Philips";
signal11.model = "PS-6500";
signal11.signalHeight = 5;
signal11.powerSource = "Grid";
signal11.solarPowered = false;
signal11.lightIntensity = 4900;
signal11.controlType = "Fixed";
signal11.pedestrianSignal = true;
signal11.cycleDuration = 95;
signal11.powerConsumption = 125.0;
signal11.weatherRating = "IP65";
signal11.waterproof = true;
signal11.ledType = "Standard LED";
signal11.ledCount = 44;
signal11.adaptiveTiming = false;
signal11.trafficDirection = "4-Way";
signal11.cameraIntegrated = false;
signal11.signalGroup = "Group-K";
signal11.maintenanceCost = 7600.00;
signal11.emergencyContact = "080-35678901";


System.out.println("Signal ID: " + signal11.signalId);
System.out.println("Location: " + signal11.location);
System.out.println("City: " + signal11.city);
System.out.println("Operational Status: " + signal11.operationalStatus);
System.out.println("Installation Date: " + signal11.installationDate);
System.out.println("Last Maintenance: " + signal11.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal11.maintenanceDue);
System.out.println("Manufacturer: " + signal11.manufacturer);
System.out.println("Model: " + signal11.model);
System.out.println("Signal Height: " + signal11.signalHeight + " meters");
System.out.println("Power Source: " + signal11.powerSource);
System.out.println("Solar Powered: " + signal11.solarPowered);
System.out.println("Light Intensity: " + signal11.lightIntensity + " lumens");
System.out.println("Control Type: " + signal11.controlType);
System.out.println("Pedestrian Signal: " + signal11.pedestrianSignal);
System.out.println("Cycle Duration: " + signal11.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal11.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal11.weatherRating);
System.out.println("Waterproof: " + signal11.waterproof);
System.out.println("LED Type: " + signal11.ledType);
System.out.println("LED Count: " + signal11.ledCount);
System.out.println("Adaptive Timing: " + signal11.adaptiveTiming);
System.out.println("Traffic Direction: " + signal11.trafficDirection);
System.out.println("Camera Integrated: " + signal11.cameraIntegrated);
System.out.println("Signal Group: " + signal11.signalGroup);
System.out.println("Maintenance Cost: " + signal11.maintenanceCost);
System.out.println("Emergency Contact: " + signal11.emergencyContact);
System.out.println("================================");


TrafficSignal signal12 = new TrafficSignal();

signal12.signalId = 112;
signal12.location = "KR Puram Railway Gate";
signal12.city = "Bengaluru";
signal12.operationalStatus = true;
signal12.installationDate = "17/02/2026";
signal12.lastMaintenanceDate = "09/03/2026";
signal12.maintenanceDue = false;
signal12.manufacturer = "GE";
signal12.model = "TS-8000";
signal12.signalHeight = 6;
signal12.powerSource = "Solar";
signal12.solarPowered = true;
signal12.lightIntensity = 5900;
signal12.controlType = "Adaptive";
signal12.pedestrianSignal = false;
signal12.cycleDuration = 130;
signal12.powerConsumption = 160.0;
signal12.weatherRating = "IP67";
signal12.waterproof = true;
signal12.ledType = "High Brightness LED";
signal12.ledCount = 58;
signal12.adaptiveTiming = true;
signal12.trafficDirection = "3-Way";
signal12.cameraIntegrated = true;
signal12.signalGroup = "Group-L";
signal12.maintenanceCost = 10500.00;
signal12.emergencyContact = "080-36789012";

System.out.println("Signal ID: " + signal12.signalId);
System.out.println("Location: " + signal12.location);
System.out.println("City: " + signal12.city);
System.out.println("Operational Status: " + signal12.operationalStatus);
System.out.println("Installation Date: " + signal12.installationDate);
System.out.println("Last Maintenance: " + signal12.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal12.maintenanceDue);
System.out.println("Manufacturer: " + signal12.manufacturer);
System.out.println("Model: " + signal12.model);
System.out.println("Signal Height: " + signal12.signalHeight + " meters");
System.out.println("Power Source: " + signal12.powerSource);
System.out.println("Solar Powered: " + signal12.solarPowered);
System.out.println("Light Intensity: " + signal12.lightIntensity + " lumens");
System.out.println("Control Type: " + signal12.controlType);
System.out.println("Pedestrian Signal: " + signal12.pedestrianSignal);
System.out.println("Cycle Duration: " + signal12.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal12.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal12.weatherRating);
System.out.println("Waterproof: " + signal12.waterproof);
System.out.println("LED Type: " + signal12.ledType);
System.out.println("LED Count: " + signal12.ledCount);
System.out.println("Adaptive Timing: " + signal12.adaptiveTiming);
System.out.println("Traffic Direction: " + signal12.trafficDirection);
System.out.println("Camera Integrated: " + signal12.cameraIntegrated);
System.out.println("Signal Group: " + signal12.signalGroup);
System.out.println("Maintenance Cost: " + signal12.maintenanceCost);
System.out.println("Emergency Contact: " + signal12.emergencyContact);
System.out.println("================================");


TrafficSignal signal13 = new TrafficSignal();

signal13.signalId = 113;
signal13.location = "Bannerghatta Road";
signal13.city = "Bengaluru";
signal13.operationalStatus = true;
signal13.installationDate = "08/01/2026";
signal13.lastMaintenanceDate = "10/03/2026";
signal13.maintenanceDue = false;
signal13.manufacturer = "Siemens";
signal13.model = "ST-3500";
signal13.signalHeight = 4;
signal13.powerSource = "Grid";
signal13.solarPowered = false;
signal13.lightIntensity = 4600;
signal13.controlType = "Fixed";
signal13.pedestrianSignal = true;
signal13.cycleDuration = 115;
signal13.powerConsumption = 135.0;
signal13.weatherRating = "IP66";
signal13.waterproof = true;
signal13.ledType = "Standard LED";
signal13.ledCount = 46;
signal13.adaptiveTiming = false;
signal13.trafficDirection = "4-Way";
signal13.cameraIntegrated = false;
signal13.signalGroup = "Group-M";
signal13.maintenanceCost = 7800.00;
signal13.emergencyContact = "080-37890123";

System.out.println("Signal ID: " + signal13.signalId);
System.out.println("Location: " + signal13.location);
System.out.println("City: " + signal13.city);
System.out.println("Operational Status: " + signal13.operationalStatus);
System.out.println("Installation Date: " + signal13.installationDate);
System.out.println("Last Maintenance: " + signal13.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal13.maintenanceDue);
System.out.println("Manufacturer: " + signal13.manufacturer);
System.out.println("Model: " + signal13.model);
System.out.println("Signal Height: " + signal13.signalHeight + " meters");
System.out.println("Power Source: " + signal13.powerSource);
System.out.println("Solar Powered: " + signal13.solarPowered);
System.out.println("Light Intensity: " + signal13.lightIntensity + " lumens");
System.out.println("Control Type: " + signal13.controlType);
System.out.println("Pedestrian Signal: " + signal13.pedestrianSignal);
System.out.println("Cycle Duration: " + signal13.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal13.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal13.weatherRating);
System.out.println("Waterproof: " + signal13.waterproof);
System.out.println("LED Type: " + signal13.ledType);
System.out.println("LED Count: " + signal13.ledCount);
System.out.println("Adaptive Timing: " + signal13.adaptiveTiming);
System.out.println("Traffic Direction: " + signal13.trafficDirection);
System.out.println("Camera Integrated: " + signal13.cameraIntegrated);
System.out.println("Signal Group: " + signal13.signalGroup);
System.out.println("Maintenance Cost: " + signal13.maintenanceCost);
System.out.println("Emergency Contact: " + signal13.emergencyContact);
System.out.println("================================");


TrafficSignal signal14 = new TrafficSignal();

signal14.signalId = 114;
signal14.location = "Yeshwanthpur Industrial Area";
signal14.city = "Bengaluru";
signal14.operationalStatus = false;
signal14.installationDate = "28/03/2025";
signal14.lastMaintenanceDate = "25/02/2026";
signal14.maintenanceDue = true;
signal14.manufacturer = "Honeywell";
signal14.model = "HTS-3000";
signal14.signalHeight = 5;
signal14.powerSource = "Solar";
signal14.solarPowered = true;
signal14.lightIntensity = 5300;
signal14.controlType = "Adaptive";
signal14.pedestrianSignal = false;
signal14.cycleDuration = 145;
signal14.powerConsumption = 175.0;
signal14.weatherRating = "IP68";
signal14.waterproof = true;
signal14.ledType = "Industrial LED";
signal14.ledCount = 62;
signal14.adaptiveTiming = true;
signal14.trafficDirection = "3-Way";
signal14.cameraIntegrated = true;
signal14.signalGroup = "Group-N";
signal14.maintenanceCost = 11200.00;
signal14.emergencyContact = "080-38901234";

System.out.println("Signal ID: " + signal14.signalId);
System.out.println("Location: " + signal14.location);
System.out.println("City: " + signal14.city);
System.out.println("Operational Status: " + signal14.operationalStatus);
System.out.println("Installation Date: " + signal14.installationDate);
System.out.println("Last Maintenance: " + signal14.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal14.maintenanceDue);
System.out.println("Manufacturer: " + signal14.manufacturer);
System.out.println("Model: " + signal14.model);
System.out.println("Signal Height: " + signal14.signalHeight + " meters");
System.out.println("Power Source: " + signal14.powerSource);
System.out.println("Solar Powered: " + signal14.solarPowered);
System.out.println("Light Intensity: " + signal14.lightIntensity + " lumens");
System.out.println("Control Type: " + signal14.controlType);
System.out.println("Pedestrian Signal: " + signal14.pedestrianSignal);
System.out.println("Cycle Duration: " + signal14.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal14.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal14.weatherRating);
System.out.println("Waterproof: " + signal14.waterproof);
System.out.println("LED Type: " + signal14.ledType);
System.out.println("LED Count: " + signal14.ledCount);
System.out.println("Adaptive Timing: " + signal14.adaptiveTiming);
System.out.println("Traffic Direction: " + signal14.trafficDirection);
System.out.println("Camera Integrated: " + signal14.cameraIntegrated);
System.out.println("Signal Group: " + signal14.signalGroup);
System.out.println("Maintenance Cost: " + signal14.maintenanceCost);
System.out.println("Emergency Contact: " + signal14.emergencyContact);
System.out.println("================================");


TrafficSignal signal15 = new TrafficSignal();

signal15.signalId = 115;
signal15.location = "HSR Layout Signal";
signal15.city = "Bengaluru";
signal15.operationalStatus = true;
signal15.installationDate = "15/04/2025";
signal15.lastMaintenanceDate = "11/03/2026";
signal15.maintenanceDue = false;
signal15.manufacturer = "ABB";
signal15.model = "TSX-3500";
signal15.signalHeight = 5;
signal15.powerSource = "Solar + Grid";
signal15.solarPowered = true;
signal15.lightIntensity = 5000;
signal15.controlType = "Adaptive";
signal15.pedestrianSignal = true;
signal15.cycleDuration = 120;
signal15.powerConsumption = 145.0;
signal15.weatherRating = "IP66";
signal15.waterproof = true;
signal15.ledType = "Premium LED";
signal15.ledCount = 48;
signal15.adaptiveTiming = true;
signal15.trafficDirection = "4-Way";
signal15.cameraIntegrated = true;
signal15.signalGroup = "Group-O";
signal15.maintenanceCost = 8900.00;
signal15.emergencyContact = "080-39012345";

System.out.println("Signal ID: " + signal15.signalId);
System.out.println("Location: " + signal15.location);
System.out.println("City: " + signal15.city);
System.out.println("Operational Status: " + signal15.operationalStatus);
System.out.println("Installation Date: " + signal15.installationDate);
System.out.println("Last Maintenance: " + signal15.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal15.maintenanceDue);
System.out.println("Manufacturer: " + signal15.manufacturer);
System.out.println("Model: " + signal15.model);
System.out.println("Signal Height: " + signal15.signalHeight + " meters");
System.out.println("Power Source: " + signal15.powerSource);
System.out.println("Solar Powered: " + signal15.solarPowered);
System.out.println("Light Intensity: " + signal15.lightIntensity + " lumens");
System.out.println("Control Type: " + signal15.controlType);
System.out.println("Pedestrian Signal: " + signal15.pedestrianSignal);
System.out.println("Cycle Duration: " + signal15.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal15.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal15.weatherRating);
System.out.println("Waterproof: " + signal15.waterproof);
System.out.println("LED Type: " + signal15.ledType);
System.out.println("LED Count: " + signal15.ledCount);
System.out.println("Adaptive Timing: " + signal15.adaptiveTiming);
System.out.println("Traffic Direction: " + signal15.trafficDirection);
System.out.println("Camera Integrated: " + signal15.cameraIntegrated);
System.out.println("Signal Group: " + signal15.signalGroup);
System.out.println("Maintenance Cost: " + signal15.maintenanceCost);
System.out.println("Emergency Contact: " + signal15.emergencyContact);
System.out.println("================================");


TrafficSignal signal16 = new TrafficSignal();

signal16.signalId = 116;
signal16.location = "Bellandur Forum Mall";
signal16.city = "Bengaluru";
signal16.operationalStatus = true;
signal16.installationDate = "21/09/2025";
signal16.lastMaintenanceDate = "12/03/2026";
signal16.maintenanceDue = false;
signal16.manufacturer = "Schneider";
signal16.model = "TS-5500";
signal16.signalHeight = 6;
signal16.powerSource = "Grid";
signal16.solarPowered = false;
signal16.lightIntensity = 5700;
signal16.controlType = "AI Adaptive";
signal16.pedestrianSignal = true;
signal16.cycleDuration = 155;
signal16.powerConsumption = 185.0;
signal16.weatherRating = "IP67";
signal16.waterproof = true;
signal16.ledType = "High Performance LED";
signal16.ledCount = 60;
signal16.adaptiveTiming = true;
signal16.trafficDirection = "5-Way";
signal16.cameraIntegrated = true;
signal16.signalGroup = "Group-P";
signal16.maintenanceCost = 12800.00;
signal16.emergencyContact = "080-40123456";

System.out.println("Signal ID: " + signal16.signalId);
System.out.println("Location: " + signal16.location);
System.out.println("City: " + signal16.city);
System.out.println("Operational Status: " + signal16.operationalStatus);
System.out.println("Installation Date: " + signal16.installationDate);
System.out.println("Last Maintenance: " + signal16.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal16.maintenanceDue);
System.out.println("Manufacturer: " + signal16.manufacturer);
System.out.println("Model: " + signal16.model);
System.out.println("Signal Height: " + signal16.signalHeight + " meters");
System.out.println("Power Source: " + signal16.powerSource);
System.out.println("Solar Powered: " + signal16.solarPowered);
System.out.println("Light Intensity: " + signal16.lightIntensity + " lumens");
System.out.println("Control Type: " + signal16.controlType);
System.out.println("Pedestrian Signal: " + signal16.pedestrianSignal);
System.out.println("Cycle Duration: " + signal16.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal16.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal16.weatherRating);
System.out.println("Waterproof: " + signal16.waterproof);
System.out.println("LED Type: " + signal16.ledType);
System.out.println("LED Count: " + signal16.ledCount);
System.out.println("Adaptive Timing: " + signal16.adaptiveTiming);
System.out.println("Traffic Direction: " + signal16.trafficDirection);
System.out.println("Camera Integrated: " + signal16.cameraIntegrated);
System.out.println("Signal Group: " + signal16.signalGroup);
System.out.println("Maintenance Cost: " + signal16.maintenanceCost);
System.out.println("Emergency Contact: " + signal16.emergencyContact);
System.out.println("================================");


TrafficSignal signal17 = new TrafficSignal();

signal17.signalId = 117;
signal17.location = "Silk Board Junction";
signal17.city = "Bengaluru";
signal17.operationalStatus = true;
signal17.installationDate = "05/11/2025";
signal17.lastMaintenanceDate = "13/03/2026";
signal17.maintenanceDue = false;
signal17.manufacturer = "GE";
signal17.model = "TS-9000";
signal17.signalHeight = 7;
signal17.powerSource = "Solar + Grid";
signal17.solarPowered = true;
signal17.lightIntensity = 6500;
signal17.controlType = "AI Adaptive";
signal17.pedestrianSignal = true;
signal17.cycleDuration = 170;
signal17.powerConsumption = 200.0;
signal17.weatherRating = "IP68";
signal17.waterproof = true;
signal17.ledType = "Super Bright LED";
signal17.ledCount = 68;
signal17.adaptiveTiming = true;
signal17.trafficDirection = "6-Way";
signal17.cameraIntegrated = true;
signal17.signalGroup = "Group-Q";
signal17.maintenanceCost = 14500.00;
signal17.emergencyContact = "080-41234567";

System.out.println("Signal ID: " + signal17.signalId);
System.out.println("Location: " + signal17.location);
System.out.println("City: " + signal17.city);
System.out.println("Operational Status: " + signal17.operationalStatus);
System.out.println("Installation Date: " + signal17.installationDate);
System.out.println("Last Maintenance: " + signal17.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal17.maintenanceDue);
System.out.println("Manufacturer: " + signal17.manufacturer);
System.out.println("Model: " + signal17.model);
System.out.println("Signal Height: " + signal17.signalHeight + " meters");
System.out.println("Power Source: " + signal17.powerSource);
System.out.println("Solar Powered: " + signal17.solarPowered);
System.out.println("Light Intensity: " + signal17.lightIntensity + " lumens");
System.out.println("Control Type: " + signal17.controlType);
System.out.println("Pedestrian Signal: " + signal17.pedestrianSignal);
System.out.println("Cycle Duration: " + signal17.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal17.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal17.weatherRating);
System.out.println("Waterproof: " + signal17.waterproof);
System.out.println("LED Type: " + signal17.ledType);
System.out.println("LED Count: " + signal17.ledCount);
System.out.println("Adaptive Timing: " + signal17.adaptiveTiming);
System.out.println("Traffic Direction: " + signal17.trafficDirection);
System.out.println("Camera Integrated: " + signal17.cameraIntegrated);
System.out.println("Signal Group: " + signal17.signalGroup);
System.out.println("Maintenance Cost: " + signal17.maintenanceCost);
System.out.println("Emergency Contact: " + signal17.emergencyContact);
System.out.println("================================");

TrafficSignal signal18 = new TrafficSignal();

signal18.signalId = 118;
signal18.location = "Majestic Bus Stand";
signal18.city = "Bengaluru";
signal18.operationalStatus = false;
signal18.installationDate = "12/06/2025";
signal18.lastMaintenanceDate = "28/02/2026";
signal18.maintenanceDue = true;
signal18.manufacturer = "Philips";
signal18.model = "PS-7500";
signal18.signalHeight = 6;
signal18.powerSource = "Grid";
signal18.solarPowered = false;
signal18.lightIntensity = 5400;
signal18.controlType = "Adaptive";
signal18.pedestrianSignal = true;
signal18.cycleDuration = 135;
signal18.powerConsumption = 155.0;
signal18.weatherRating = "IP67";
signal18.waterproof = true;
signal18.ledType = "High Brightness LED";
signal18.ledCount = 54;
signal18.adaptiveTiming = true;
signal18.trafficDirection = "5-Way";
signal18.cameraIntegrated = true;
signal18.signalGroup = "Group-R";
signal18.maintenanceCost = 11800.00;
signal18.emergencyContact = "080-42345678";


System.out.println("Signal ID: " + signal18.signalId);
System.out.println("Location: " + signal18.location);
System.out.println("City: " + signal18.city);
System.out.println("Operational Status: " + signal18.operationalStatus);
System.out.println("Installation Date: " + signal18.installationDate);
System.out.println("Last Maintenance: " + signal18.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal18.maintenanceDue);
System.out.println("Manufacturer: " + signal18.manufacturer);
System.out.println("Model: " + signal18.model);
System.out.println("Signal Height: " + signal18.signalHeight + " meters");
System.out.println("Power Source: " + signal18.powerSource);
System.out.println("Solar Powered: " + signal18.solarPowered);
System.out.println("Light Intensity: " + signal18.lightIntensity + " lumens");
System.out.println("Control Type: " + signal18.controlType);
System.out.println("Pedestrian Signal: " + signal18.pedestrianSignal);
System.out.println("Cycle Duration: " + signal18.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal18.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal18.weatherRating);
System.out.println("Waterproof: " + signal18.waterproof);
System.out.println("LED Type: " + signal18.ledType);
System.out.println("LED Count: " + signal18.ledCount);
System.out.println("Adaptive Timing: " + signal18.adaptiveTiming);
System.out.println("Traffic Direction: " + signal18.trafficDirection);
System.out.println("Camera Integrated: " + signal18.cameraIntegrated);
System.out.println("Signal Group: " + signal18.signalGroup);
System.out.println("Maintenance Cost: " + signal18.maintenanceCost);
System.out.println("Emergency Contact: " + signal18.emergencyContact);
System.out.println("================================");


TrafficSignal signal19 = new TrafficSignal();

signal19.signalId = 119;
signal19.location = "Domlur Flyover";
signal19.city = "Bengaluru";
signal19.operationalStatus = true;
signal19.installationDate = "27/08/2025";
signal19.lastMaintenanceDate = "14/03/2026";
signal19.maintenanceDue = false;
signal19.manufacturer = "Siemens";
signal19.model = "ST-7500";
signal19.signalHeight = 7;
signal19.powerSource = "Solar";
signal19.solarPowered = true;
signal19.lightIntensity = 6100;
signal19.controlType = "Adaptive";
signal19.pedestrianSignal = false;
signal19.cycleDuration = 148;
signal19.powerConsumption = 182.0;
signal19.weatherRating = "IP68";
signal19.waterproof = true;
signal19.ledType = "Super Bright LED";
signal19.ledCount = 66;
signal19.adaptiveTiming = true;
signal19.trafficDirection = "4-Way";
signal19.cameraIntegrated = true;
signal19.signalGroup = "Group-S";
signal19.maintenanceCost = 13200.00;
signal19.emergencyContact = "080-43456789";

System.out.println("Signal ID: " + signal19.signalId);
System.out.println("Location: " + signal19.location);
System.out.println("City: " + signal19.city);
System.out.println("Operational Status: " + signal19.operationalStatus);
System.out.println("Installation Date: " + signal19.installationDate);
System.out.println("Last Maintenance: " + signal19.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal19.maintenanceDue);
System.out.println("Manufacturer: " + signal19.manufacturer);
System.out.println("Model: " + signal19.model);
System.out.println("Signal Height: " + signal19.signalHeight + " meters");
System.out.println("Power Source: " + signal19.powerSource);
System.out.println("Solar Powered: " + signal19.solarPowered);
System.out.println("Light Intensity: " + signal19.lightIntensity + " lumens");
System.out.println("Control Type: " + signal19.controlType);
System.out.println("Pedestrian Signal: " + signal19.pedestrianSignal);
System.out.println("Cycle Duration: " + signal19.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal19.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal19.weatherRating);
System.out.println("Waterproof: " + signal19.waterproof);
System.out.println("LED Type: " + signal19.ledType);
System.out.println("LED Count: " + signal19.ledCount);
System.out.println("Adaptive Timing: " + signal19.adaptiveTiming);
System.out.println("Traffic Direction: " + signal19.trafficDirection);
System.out.println("Camera Integrated: " + signal19.cameraIntegrated);
System.out.println("Signal Group: " + signal19.signalGroup);
System.out.println("Maintenance Cost: " + signal19.maintenanceCost);
System.out.println("Emergency Contact: " + signal19.emergencyContact);
System.out.println("================================");


TrafficSignal signal20 = new TrafficSignal();

signal20.signalId = 120;
signal20.location = "Shivaji Nagar Bus Station";
signal20.city = "Bengaluru";
signal20.operationalStatus = true;
signal20.installationDate = "19/12/2025";
signal20.lastMaintenanceDate = "15/03/2026";
signal20.maintenanceDue = false;
signal20.manufacturer = "ABB";
signal20.model = "TSX-6500";
signal20.signalHeight = 5;
signal20.powerSource = "Grid";
signal20.solarPowered = false;
signal20.lightIntensity = 5600;
signal20.controlType = "Fixed";
signal20.pedestrianSignal = true;
signal20.cycleDuration = 132;
signal20.powerConsumption = 168.0;
signal20.weatherRating = "IP67";
signal20.waterproof = true;
signal20.ledType = "Premium LED";
signal20.ledCount = 52;
signal20.adaptiveTiming = false;
signal20.trafficDirection = "5-Way";
signal20.cameraIntegrated = false;
signal20.signalGroup = "Group-T";
signal20.maintenanceCost = 10200.00;
signal20.emergencyContact = "080-44567890";

System.out.println("Signal ID: " + signal20.signalId);
System.out.println("Location: " + signal20.location);
System.out.println("City: " + signal20.city);
System.out.println("Operational Status: " + signal20.operationalStatus);
System.out.println("Installation Date: " + signal20.installationDate);
System.out.println("Last Maintenance: " + signal20.lastMaintenanceDate);
System.out.println("Maintenance Due: " + signal20.maintenanceDue);
System.out.println("Manufacturer: " + signal20.manufacturer);
System.out.println("Model: " + signal20.model);
System.out.println("Signal Height: " + signal20.signalHeight + " meters");
System.out.println("Power Source: " + signal20.powerSource);
System.out.println("Solar Powered: " + signal20.solarPowered);
System.out.println("Light Intensity: " + signal20.lightIntensity + " lumens");
System.out.println("Control Type: " + signal20.controlType);
System.out.println("Pedestrian Signal: " + signal20.pedestrianSignal);
System.out.println("Cycle Duration: " + signal20.cycleDuration + " seconds");
System.out.println("Power Consumption: " + signal20.powerConsumption + " watts");
System.out.println("Weather Rating: " + signal20.weatherRating);
System.out.println("Waterproof: " + signal20.waterproof);
System.out.println("LED Type: " + signal20.ledType);
System.out.println("LED Count: " + signal20.ledCount);
System.out.println("Adaptive Timing: " + signal20.adaptiveTiming);
System.out.println("Traffic Direction: " + signal20.trafficDirection);
System.out.println("Camera Integrated: " + signal20.cameraIntegrated);
System.out.println("Signal Group: " + signal20.signalGroup);
System.out.println("Maintenance Cost: " + signal20.maintenanceCost);
System.out.println("Emergency Contact: " + signal20.emergencyContact);
System.out.println("================================");


		
    }
}
