class TraineeDetailsExecutor {

    public static void main(String[] args) {
        TraineeDetails trainee1 = new TraineeDetails();
        trainee1.setId(1);
        System.out.println("ID: " + trainee1.getId());
        trainee1.setName("Srushti");
        System.out.println("Name: " + trainee1.getName());
        trainee1.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee1.getCourse());
        trainee1.setPhoneNumber("9988776655");
        System.out.println("Phone: " + trainee1.getPhoneNumber());
        trainee1.setEmail("srushti@xworkz.in");
        System.out.println("Email: " + trainee1.getEmail());
        trainee1.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee1.getBatch());
        trainee1.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee1.getJoinDate());
        System.out.println();

        TraineeDetails trainee2 = new TraineeDetails();
        trainee2.setId(2);
        System.out.println("ID: " + trainee2.getId());
        trainee2.setName("Bhagya");
        System.out.println("Name: " + trainee2.getName());
        trainee2.setCourse("Python DSA");
        System.out.println("Course: " + trainee2.getCourse());
        trainee2.setPhoneNumber("9345678901");
        System.out.println("Phone: " + trainee2.getPhoneNumber());
        trainee2.setEmail("bhagya@xworkz.in");
        System.out.println("Email: " + trainee2.getEmail());
        trainee2.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee2.getBatch());
        trainee2.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee2.getJoinDate());
        System.out.println();

        TraineeDetails trainee3 = new TraineeDetails();
        trainee3.setId(3);
        System.out.println("ID: " + trainee3.getId());
        trainee3.setName("Shreya");
        System.out.println("Name: " + trainee3.getName());
        trainee3.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee3.getCourse());
        trainee3.setPhoneNumber("9876543210");
        System.out.println("Phone: " + trainee3.getPhoneNumber());
        trainee3.setEmail("shreya@xworkz.in");
        System.out.println("Email: " + trainee3.getEmail());
        trainee3.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee3.getBatch());
        trainee3.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee3.getJoinDate());
        System.out.println();

        TraineeDetails trainee4 = new TraineeDetails();
        trainee4.setId(4);
        System.out.println("ID: " + trainee4.getId());
        trainee4.setName("Shashikala");
        System.out.println("Name: " + trainee4.getName());
        trainee4.setCourse("React Full Stack");
        System.out.println("Course: " + trainee4.getCourse());
        trainee4.setPhoneNumber("9123456789");
        System.out.println("Phone: " + trainee4.getPhoneNumber());
        trainee4.setEmail("shashikala@xworkz.in");
        System.out.println("Email: " + trainee4.getEmail());
        trainee4.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee4.getBatch());
        trainee4.setJoinDate("2026-03-03");
        System.out.println("Join Date: " + trainee4.getJoinDate());
        System.out.println();

        TraineeDetails trainee5 = new TraineeDetails();
        trainee5.setId(5);
        System.out.println("ID: " + trainee5.getId());
        trainee5.setName("Meghana");
        System.out.println("Name: " + trainee5.getName());
        trainee5.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee5.getCourse());
        trainee5.setPhoneNumber("9444555666");
        System.out.println("Phone: " + trainee5.getPhoneNumber());
        trainee5.setEmail("meghana@xworkz.in");
        System.out.println("Email: " + trainee5.getEmail());
        trainee5.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee5.getBatch());
        trainee5.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee5.getJoinDate());
        System.out.println();

        TraineeDetails trainee6 = new TraineeDetails();
        trainee6.setId(6);
        System.out.println("ID: " + trainee6.getId());
        trainee6.setName("Inchara");
        System.out.println("Name: " + trainee6.getName());
        trainee6.setCourse("Python DSA");
        System.out.println("Course: " + trainee6.getCourse());
        trainee6.setPhoneNumber("9534567890");
        System.out.println("Phone: " + trainee6.getPhoneNumber());
        trainee6.setEmail("inchara@xworkz.in");
        System.out.println("Email: " + trainee6.getEmail());
        trainee6.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee6.getBatch());
        trainee6.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee6.getJoinDate());
        System.out.println();

        TraineeDetails trainee7 = new TraineeDetails();
        trainee7.setId(7);
        System.out.println("ID: " + trainee7.getId());
        trainee7.setName("Likitha");
        System.out.println("Name: " + trainee7.getName());
        trainee7.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee7.getCourse());
        trainee7.setPhoneNumber("8765432109");
        System.out.println("Phone: " + trainee7.getPhoneNumber());
        trainee7.setEmail("likitha@xworkz.in");
        System.out.println("Email: " + trainee7.getEmail());
        trainee7.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee7.getBatch());
        trainee7.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee7.getJoinDate());
        System.out.println();
		
		TraineeDetails trainee8 = new TraineeDetails();
        trainee8.setId(8);
        System.out.println("ID: " + trainee8.getId());
        trainee8.setName("Vijayalakshmi");
        System.out.println("Name: " + trainee8.getName());
        trainee8.setCourse("React Full Stack");
        System.out.println("Course: " + trainee8.getCourse());
        trainee8.setPhoneNumber("9012345678");
        System.out.println("Phone: " + trainee8.getPhoneNumber());
        trainee8.setEmail("vijayalakshmi@xworkz.in");
        System.out.println("Email: " + trainee8.getEmail());
        trainee8.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee8.getBatch());
        trainee8.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee8.getJoinDate());
        System.out.println();

        TraineeDetails trainee9 = new TraineeDetails();
        trainee9.setId(9);
        System.out.println("ID: " + trainee9.getId());
        trainee9.setName("Swathi");
        System.out.println("Name: " + trainee9.getName());
        trainee9.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee9.getCourse());
        trainee9.setPhoneNumber("9678901234");
        System.out.println("Phone: " + trainee9.getPhoneNumber());
        trainee9.setEmail("swathi@xworkz.in");
        System.out.println("Email: " + trainee9.getEmail());
        trainee9.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee9.getBatch());
        trainee9.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee9.getJoinDate());
        System.out.println();

        TraineeDetails trainee10 = new TraineeDetails();
        trainee10.setId(10);
        System.out.println("ID: " + trainee10.getId());
        trainee10.setName("Shrusti");
        System.out.println("Name: " + trainee10.getName());
        trainee10.setCourse("Python DSA");
        System.out.println("Course: " + trainee10.getCourse());
        trainee10.setPhoneNumber("7890123456");
        System.out.println("Phone: " + trainee10.getPhoneNumber());
        trainee10.setEmail("shrusti@xworkz.in");
        System.out.println("Email: " + trainee10.getEmail());
        trainee10.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee10.getBatch());
        trainee10.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee10.getJoinDate());
        System.out.println();

        TraineeDetails trainee11 = new TraineeDetails();
        trainee11.setId(11);
        System.out.println("ID: " + trainee11.getId());
        trainee11.setName("Kerthana");
        System.out.println("Name: " + trainee11.getName());
        trainee11.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee11.getCourse());
        trainee11.setPhoneNumber("8123456789");
        System.out.println("Phone: " + trainee11.getPhoneNumber());
        trainee11.setEmail("kerthana@xworkz.in");
        System.out.println("Email: " + trainee11.getEmail());
        trainee11.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee11.getBatch());
        trainee11.setJoinDate("2026-03-03");
        System.out.println("Join Date: " + trainee11.getJoinDate());
        System.out.println();

        TraineeDetails trainee12 = new TraineeDetails();
        trainee12.setId(12);
        System.out.println("ID: " + trainee12.getId());
        trainee12.setName("Bindhu");
        System.out.println("Name: " + trainee12.getName());
        trainee12.setCourse("React Full Stack");
        System.out.println("Course: " + trainee12.getCourse());
        trainee12.setPhoneNumber("9567890123");
        System.out.println("Phone: " + trainee12.getPhoneNumber());
        trainee12.setEmail("bindhu@xworkz.in");
        System.out.println("Email: " + trainee12.getEmail());
        trainee12.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee12.getBatch());
        trainee12.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee12.getJoinDate());
        System.out.println();

        TraineeDetails trainee13 = new TraineeDetails();
        trainee13.setId(13);
        System.out.println("ID: " + trainee13.getId());
        trainee13.setName("Pavithra");
        System.out.println("Name: " + trainee13.getName());
        trainee13.setCourse("Python DSA");
        System.out.println("Course: " + trainee13.getCourse());
        trainee13.setPhoneNumber("9345678901");
        System.out.println("Phone: " + trainee13.getPhoneNumber());
        trainee13.setEmail("pavithra@xworkz.in");
        System.out.println("Email: " + trainee13.getEmail());
        trainee13.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee13.getBatch());
        trainee13.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee13.getJoinDate());
        System.out.println();

        TraineeDetails trainee14 = new TraineeDetails();
        trainee14.setId(14);
        System.out.println("ID: " + trainee14.getId());
        trainee14.setName("Nandini");
        System.out.println("Name: " + trainee14.getName());
        trainee14.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee14.getCourse());
        trainee14.setPhoneNumber("8901234567");
        System.out.println("Phone: " + trainee14.getPhoneNumber());
        trainee14.setEmail("nandini@xworkz.in");
        System.out.println("Email: " + trainee14.getEmail());
        trainee14.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee14.getBatch());
        trainee14.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee14.getJoinDate());
        System.out.println();

        TraineeDetails trainee15 = new TraineeDetails();
        trainee15.setId(15);
        System.out.println("ID: " + trainee15.getId());
        trainee15.setName("Rashmi");
        System.out.println("Name: " + trainee15.getName());
        trainee15.setCourse("React Full Stack");
        System.out.println("Course: " + trainee15.getCourse());
        trainee15.setPhoneNumber("9789012345");
        System.out.println("Phone: " + trainee15.getPhoneNumber());
        trainee15.setEmail("rashmi@xworkz.in");
        System.out.println("Email: " + trainee15.getEmail());
        trainee15.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee15.getBatch());
        trainee15.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee15.getJoinDate());
        System.out.println();

        TraineeDetails trainee16 = new TraineeDetails();
        trainee16.setId(16);
        System.out.println("ID: " + trainee16.getId());
        trainee16.setName("Supriya");
        System.out.println("Name: " + trainee16.getName());
        trainee16.setCourse("Python DSA");
        System.out.println("Course: " + trainee16.getCourse());
        trainee16.setPhoneNumber("9123456780");
        System.out.println("Phone: " + trainee16.getPhoneNumber());
        trainee16.setEmail("supriya@xworkz.in");
        System.out.println("Email: " + trainee16.getEmail());
        trainee16.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee16.getBatch());
        trainee16.setJoinDate("2026-03-03");
        System.out.println("Join Date: " + trainee16.getJoinDate());
        System.out.println();

        TraineeDetails trainee17 = new TraineeDetails();
        trainee17.setId(17);
        System.out.println("ID: " + trainee17.getId());
        trainee17.setName("Anusha");
        System.out.println("Name: " + trainee17.getName());
        trainee17.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee17.getCourse());
        trainee17.setPhoneNumber("9456789012");
        System.out.println("Phone: " + trainee17.getPhoneNumber());
        trainee17.setEmail("anusha@xworkz.in");
        System.out.println("Email: " + trainee17.getEmail());
        trainee17.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee17.getBatch());
        trainee17.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee17.getJoinDate());
        System.out.println();

        TraineeDetails trainee18 = new TraineeDetails();
        trainee18.setId(18);
        System.out.println("ID: " + trainee18.getId());
        trainee18.setName("Deepika");
        System.out.println("Name: " + trainee18.getName());
        trainee18.setCourse("React Full Stack");
        System.out.println("Course: " + trainee18.getCourse());
        trainee18.setPhoneNumber("9012345678");
        System.out.println("Phone: " + trainee18.getPhoneNumber());
        trainee18.setEmail("deepika@xworkz.in");
        System.out.println("Email: " + trainee18.getEmail());
        trainee18.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee18.getBatch());
        trainee18.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee18.getJoinDate());
        System.out.println();
		
		TraineeDetails trainee19 = new TraineeDetails();
        trainee19.setId(19);
        System.out.println("ID: " + trainee19.getId());
        trainee19.setName("Sangeetha");
        System.out.println("Name: " + trainee19.getName());
        trainee19.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee19.getCourse());
        trainee19.setPhoneNumber("9035771662");
        System.out.println("Phone: " + trainee19.getPhoneNumber());
        trainee19.setEmail("sangeetha@xworkz.in");
        System.out.println("Email: " + trainee19.getEmail());
        trainee19.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee19.getBatch());
        trainee19.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee19.getJoinDate());
        System.out.println();

        TraineeDetails trainee20 = new TraineeDetails();
        trainee20.setId(20);
        System.out.println("ID: " + trainee20.getId());
        trainee20.setName("Divya");
        System.out.println("Name: " + trainee20.getName());
        trainee20.setCourse("Python DSA");
        System.out.println("Course: " + trainee20.getCourse());
        trainee20.setPhoneNumber("7894561230");
        System.out.println("Phone: " + trainee20.getPhoneNumber());
        trainee20.setEmail("divya@xworkz.in");
        System.out.println("Email: " + trainee20.getEmail());
        trainee20.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee20.getBatch());
        trainee20.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee20.getJoinDate());
        System.out.println();

        TraineeDetails trainee21 = new TraineeDetails();
        trainee21.setId(21);
        System.out.println("ID: " + trainee21.getId());
        trainee21.setName("Priya");
        System.out.println("Name: " + trainee21.getName());
        trainee21.setCourse("React Full Stack");
        System.out.println("Course: " + trainee21.getCourse());
        trainee21.setPhoneNumber("9945112233");
        System.out.println("Phone: " + trainee21.getPhoneNumber());
        trainee21.setEmail("priya@xworkz.in");
        System.out.println("Email: " + trainee21.getEmail());
        trainee21.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee21.getBatch());
        trainee21.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee21.getJoinDate());
        System.out.println();

        TraineeDetails trainee22 = new TraineeDetails();
        trainee22.setId(22);
        System.out.println("ID: " + trainee22.getId());
        trainee22.setName("Aishwarya");
        System.out.println("Name: " + trainee22.getName());
        trainee22.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee22.getCourse());
        trainee22.setPhoneNumber("8556789012");
        System.out.println("Phone: " + trainee22.getPhoneNumber());
        trainee22.setEmail("aishwarya@xworkz.in");
        System.out.println("Email: " + trainee22.getEmail());
        trainee22.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee22.getBatch());
        trainee22.setJoinDate("2026-03-03");
        System.out.println("Join Date: " + trainee22.getJoinDate());
        System.out.println();

        TraineeDetails trainee23 = new TraineeDetails();
        trainee23.setId(23);
        System.out.println("ID: " + trainee23.getId());
        trainee23.setName("Kavya");
        System.out.println("Name: " + trainee23.getName());
        trainee23.setCourse("Python DSA");
        System.out.println("Course: " + trainee23.getCourse());
        trainee23.setPhoneNumber("9901234567");
        System.out.println("Phone: " + trainee23.getPhoneNumber());
        trainee23.setEmail("kavya@xworkz.in");
        System.out.println("Email: " + trainee23.getEmail());
        trainee23.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee23.getBatch());
        trainee23.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee23.getJoinDate());
        System.out.println();

        TraineeDetails trainee24 = new TraineeDetails();
        trainee24.setId(24);
        System.out.println("ID: " + trainee24.getId());
        trainee24.setName("Sowmya");
        System.out.println("Name: " + trainee24.getName());
        trainee24.setCourse("React Full Stack");
        System.out.println("Course: " + trainee24.getCourse());
        trainee24.setPhoneNumber("8976543210");
        System.out.println("Phone: " + trainee24.getPhoneNumber());
        trainee24.setEmail("sowmya@xworkz.in");
        System.out.println("Email: " + trainee24.getEmail());
        trainee24.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee24.getBatch());
        trainee24.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee24.getJoinDate());
        System.out.println();

        TraineeDetails trainee25 = new TraineeDetails();
        trainee25.setId(25);
        System.out.println("ID: " + trainee25.getId());
        trainee25.setName("Chaitra");
        System.out.println("Name: " + trainee25.getName());
        trainee25.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee25.getCourse());
        trainee25.setPhoneNumber("9845678901");
        System.out.println("Phone: " + trainee25.getPhoneNumber());
        trainee25.setEmail("chaitra@xworkz.in");
        System.out.println("Email: " + trainee25.getEmail());
        trainee25.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee25.getBatch());
        trainee25.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee25.getJoinDate());
        System.out.println();

        TraineeDetails trainee26 = new TraineeDetails();
        trainee26.setId(26);
        System.out.println("ID: " + trainee26.getId());
        trainee26.setName("Nisha");
        System.out.println("Name: " + trainee26.getName());
        trainee26.setCourse("Python DSA");
        System.out.println("Course: " + trainee26.getCourse());
        trainee26.setPhoneNumber("7790123456");
        System.out.println("Phone: " + trainee26.getPhoneNumber());
        trainee26.setEmail("nisha@xworkz.in");
        System.out.println("Email: " + trainee26.getEmail());
        trainee26.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee26.getBatch());
        trainee26.setJoinDate("2026-03-03");
        System.out.println("Join Date: " + trainee26.getJoinDate());
        System.out.println();

        TraineeDetails trainee27 = new TraineeDetails();
        trainee27.setId(27);
        System.out.println("ID: " + trainee27.getId());
        trainee27.setName("Varsha");
        System.out.println("Name: " + trainee27.getName());
        trainee27.setCourse("React Full Stack");
        System.out.println("Course: " + trainee27.getCourse());
        trainee27.setPhoneNumber("8889990001");
        System.out.println("Phone: " + trainee27.getPhoneNumber());
        trainee27.setEmail("varsha@xworkz.in");
        System.out.println("Email: " + trainee27.getEmail());
        trainee27.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee27.getBatch());
        trainee27.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee27.getJoinDate());
        System.out.println();

        TraineeDetails trainee28 = new TraineeDetails();
        trainee28.setId(28);
        System.out.println("ID: " + trainee28.getId());
        trainee28.setName("Pooja");
        System.out.println("Name: " + trainee28.getName());
        trainee28.setCourse("Java Full Stack");
        System.out.println("Course: " + trainee28.getCourse());
        trainee28.setPhoneNumber("9977881122");
        System.out.println("Phone: " + trainee28.getPhoneNumber());
        trainee28.setEmail("pooja@xworkz.in");
        System.out.println("Email: " + trainee28.getEmail());
        trainee28.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee28.getBatch());
        trainee28.setJoinDate("2026-03-02");
        System.out.println("Join Date: " + trainee28.getJoinDate());
        System.out.println();

        TraineeDetails trainee29 = new TraineeDetails();
        trainee29.setId(29);
        System.out.println("ID: " + trainee29.getId());
        trainee29.setName("Rohini");
        System.out.println("Name: " + trainee29.getName());
        trainee29.setCourse("Python DSA");
        System.out.println("Course: " + trainee29.getCourse());
        trainee29.setPhoneNumber("8866775544");
        System.out.println("Phone: " + trainee29.getPhoneNumber());
        trainee29.setEmail("rohini@xworkz.in");
        System.out.println("Email: " + trainee29.getEmail());
        trainee29.setBatch("March 2026 Batch");
        System.out.println("Batch: " + trainee29.getBatch());
        trainee29.setJoinDate("2026-03-01");
        System.out.println("Join Date: " + trainee29.getJoinDate());
        System.out.println();
    }
}