class TrekkingTrailsExecutor {
    public static void main(String[] args) {

        TrekkingTrails trail1 = new TrekkingTrails();
        
        trail1.trailId = 2001;
        trail1.trailName = "Mullayanagiri Peak";
        trail1.mountainRange = "Chikmagalur Range";
        trail1.permitRequired = true;
        trail1.difficultyGrade = "Moderate";
        trail1.elevationGain = 1850;
        trail1.trailLengthKM = 4.2;
        trail1.waterSources = true;
        trail1.bestSeason = "Oct-Mar";
        trail1.dailyHikerLimit = 350;
        trail1.campingPermitted = true;
        trail1.emergencyBeacon = "PLB-2001";
        trail1.trailheadAltitude = 1200;
        trail1.wildlifeCorridor = true;
        trail1.checkpointCount = 3;
        trail1.summitView = "360 Panoramic";
        trail1.technicalSections = false;
        trail1.avgCompletionTime = 3.5;
        trail1.forestType = "Shola Forest";
        trail1.solarChargers = true;
        trail1.biodiversityHotspot = 9;
        trail1.rescueHelipad = "Mulla-Heli-1";
        trail1.nightHiking = false;
        trail1.annualMaintenance = 1250000.00;
        trail1.trailGuardianNGO = "WGS Foundation";
        trail1.leechSeason = true;
        trail1.peakBaggingRank = "Karnataka #1";
        
        System.out.println("Trail ID: " + trail1.trailId);
        System.out.println("Trail Name: " + trail1.trailName);
        System.out.println("Mountain Range: " + trail1.mountainRange);
        System.out.println("Permit Required: " + trail1.permitRequired);
        System.out.println("Difficulty Grade: " + trail1.difficultyGrade);
        System.out.println("Elevation Gain: " + trail1.elevationGain + "m");
        System.out.println("Trail Length: " + trail1.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail1.waterSources);
        System.out.println("Best Season: " + trail1.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail1.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail1.campingPermitted);
        System.out.println("Emergency Beacon: " + trail1.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail1.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail1.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail1.checkpointCount);
        System.out.println("Summit View: " + trail1.summitView);
        System.out.println("Technical Sections: " + trail1.technicalSections);
        System.out.println("Avg Completion Time: " + trail1.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail1.forestType);
        System.out.println("Solar Chargers: " + trail1.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail1.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail1.rescueHelipad);
        System.out.println("Night Hiking: " + trail1.nightHiking);
        System.out.println("Annual Maintenance: " + trail1.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail1.trailGuardianNGO);
        System.out.println("Leech Season: " + trail1.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail1.peakBaggingRank);
        System.out.println("-----------------------------");
		
		
        TrekkingTrails trail2 = new TrekkingTrails();
        trail2.trailId = 2002;
        trail2.trailName = "Tadiandamol Peak";
        trail2.mountainRange = "Brahmagiri Range";
        trail2.permitRequired = true;
        trail2.difficultyGrade = "Moderate";
        trail2.elevationGain = 1748;
        trail2.trailLengthKM = 13.5;
        trail2.waterSources = true;
        trail2.bestSeason = "Oct-May";
        trail2.dailyHikerLimit = 280;
        
        System.out.println("Trail ID: " + trail2.trailId);
        System.out.println("Trail Name: " + trail2.trailName);
        System.out.println("Mountain Range: " + trail2.mountainRange);
        System.out.println("Permit Required: " + trail2.permitRequired);
        System.out.println("Difficulty Grade: " + trail2.difficultyGrade);
        System.out.println("Elevation Gain: " + trail2.elevationGain + "m");
        System.out.println("Trail Length: " + trail2.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail2.waterSources);
        System.out.println("Best Season: " + trail2.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail2.dailyHikerLimit);
        System.out.println("-----------------------------");

        TrekkingTrails trail3 = new TrekkingTrails();
        trail3.trailId = 2003;
        trail3.trailName = "Kodachadri Peak";
        trail3.mountainRange = "Shimoga Ghats";
        trail3.permitRequired = true;
        trail3.difficultyGrade = "Moderate-Difficult";
        trail3.elevationGain = 1343;
        trail3.trailLengthKM = 18.0;
        trail3.waterSources = true;
        trail3.bestSeason = "Sep-Apr";
        trail3.dailyHikerLimit = 220;
        
        System.out.println("Trail ID: " + trail3.trailId);
        System.out.println("Trail Name: " + trail3.trailName);
        System.out.println("Mountain Range: " + trail3.mountainRange);
        System.out.println("Permit Required: " + trail3.permitRequired);
        System.out.println("Difficulty Grade: " + trail3.difficultyGrade);
        System.out.println("Elevation Gain: " + trail3.elevationGain + "m");
        System.out.println("Trail Length: " + trail3.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail3.waterSources);
        System.out.println("Best Season: " + trail3.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail3.dailyHikerLimit);
        System.out.println("-----------------------------");

        TrekkingTrails trail4 = new TrekkingTrails();
        trail4.trailId = 2004;
        trail4.trailName = "Kudremukh Peak";
        trail4.mountainRange = "Western Ghats";
        trail4.permitRequired = true;
        trail4.difficultyGrade = "Difficult";
        trail4.elevationGain = 1894;
        trail4.trailLengthKM = 22.0;
        trail4.waterSources = true;
        trail4.bestSeason = "Oct-Feb";
        trail4.dailyHikerLimit = 150;
        
        System.out.println("Trail ID: " + trail4.trailId);
        System.out.println("Trail Name: " + trail4.trailName);
        System.out.println("Mountain Range: " + trail4.mountainRange);
        System.out.println("Permit Required: " + trail4.permitRequired);
        System.out.println("Difficulty Grade: " + trail4.difficultyGrade);
        System.out.println("Elevation Gain: " + trail4.elevationGain + "m");
        System.out.println("Trail Length: " + trail4.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail4.waterSources);
        System.out.println("Best Season: " + trail4.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail4.dailyHikerLimit);
        System.out.println("-----------------------------");

        TrekkingTrails trail5 = new TrekkingTrails();
        trail5.trailId = 2005;
        trail5.trailName = "Kumara Parvatha";
        trail5.mountainRange = "Pushpagiri Range";
        trail5.permitRequired = true;
        trail5.difficultyGrade = "Very Difficult";
        trail5.elevationGain = 1712;
        trail5.trailLengthKM = 25.0;
        trail5.waterSources = true;
        trail5.bestSeason = "Nov-Mar";
        trail5.dailyHikerLimit = 120;
        
        System.out.println("Trail ID: " + trail5.trailId);
        System.out.println("Trail Name: " + trail5.trailName);
        System.out.println("Mountain Range: " + trail5.mountainRange);
        System.out.println("Permit Required: " + trail5.permitRequired);
        System.out.println("Difficulty Grade: " + trail5.difficultyGrade);
        System.out.println("Elevation Gain: " + trail5.elevationGain + "m");
        System.out.println("Trail Length: " + trail5.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail5.waterSources);
        System.out.println("Best Season: " + trail5.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail5.dailyHikerLimit);
        System.out.println("-----------------------------");

		
        TrekkingTrails trail6 = new TrekkingTrails();
        trail6.trailId = 2006;
        trail6.trailName = "Netravali Bubbling Lake";
        trail6.mountainRange = "Sahyadri Range";
        trail6.permitRequired = false;
        trail6.difficultyGrade = "Easy-Moderate";
        trail6.elevationGain = 320;
        trail6.trailLengthKM = 8.5;
        trail6.waterSources = true;
        trail6.bestSeason = "Jun-Feb";
        trail6.dailyHikerLimit = 450;
        trail6.campingPermitted = true;
        trail6.emergencyBeacon = "SBR-2006";
        trail6.trailheadAltitude = 850;
        trail6.wildlifeCorridor = true;
        trail6.checkpointCount = 2;
        trail6.summitView = "Lake Panorama";
        trail6.technicalSections = false;
        trail6.avgCompletionTime = 4.0;
        trail6.forestType = "Evergreen Forest";
        
        System.out.println("Trail ID: " + trail6.trailId);
        System.out.println("Trail Name: " + trail6.trailName);
        System.out.println("Mountain Range: " + trail6.mountainRange);
        System.out.println("Permit Required: " + trail6.permitRequired);
        System.out.println("Difficulty Grade: " + trail6.difficultyGrade);
        System.out.println("Elevation Gain: " + trail6.elevationGain + "m");
        System.out.println("Trail Length: " + trail6.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail6.waterSources);
        System.out.println("Best Season: " + trail6.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail6.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail6.campingPermitted);
        System.out.println("Emergency Beacon: " + trail6.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail6.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail6.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail6.checkpointCount);
        System.out.println("Summit View: " + trail6.summitView);
        System.out.println("Technical Sections: " + trail6.technicalSections);
        System.out.println("Avg Completion Time: " + trail6.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail6.forestType);
        System.out.println("-----------------------------");

        TrekkingTrails trail7 = new TrekkingTrails();
        trail7.trailId = 2007;
        trail7.trailName = "Kattadri Peak";
        trail7.mountainRange = "Mullayanagiri Range";
        trail7.permitRequired = true;
        trail7.difficultyGrade = "Difficult";
        trail7.elevationGain = 1450;
        trail7.trailLengthKM = 16.2;
        trail7.waterSources = true;
        trail7.bestSeason = "Oct-Mar";
        trail7.dailyHikerLimit = 180;
        trail7.campingPermitted = true;
        trail7.emergencyBeacon = "PLB-2007";
        trail7.trailheadAltitude = 950;
        trail7.wildlifeCorridor = true;
        trail7.checkpointCount = 4;
        trail7.summitView = "Baba Budan Giri";
        trail7.technicalSections = true;
        trail7.avgCompletionTime = 7.5;
        trail7.forestType = "Shola-Grassland";
        
        System.out.println("Trail ID: " + trail7.trailId);
        System.out.println("Trail Name: " + trail7.trailName);
        System.out.println("Mountain Range: " + trail7.mountainRange);
        System.out.println("Permit Required: " + trail7.permitRequired);
        System.out.println("Difficulty Grade: " + trail7.difficultyGrade);
        System.out.println("Elevation Gain: " + trail7.elevationGain + "m");
        System.out.println("Trail Length: " + trail7.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail7.waterSources);
        System.out.println("Best Season: " + trail7.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail7.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail7.campingPermitted);
        System.out.println("Emergency Beacon: " + trail7.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail7.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail7.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail7.checkpointCount);
        System.out.println("Summit View: " + trail7.summitView);
        System.out.println("Technical Sections: " + trail7.technicalSections);
        System.out.println("Avg Completion Time: " + trail7.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail7.forestType);
        System.out.println("-----------------------------");

        TrekkingTrails trail8 = new TrekkingTrails();
        trail8.trailId = 2008;
        trail8.trailName = "Skandagiri Sunrise";
        trail8.mountainRange = "Nandi Hills Range";
        trail8.permitRequired = true;
        trail8.difficultyGrade = "Moderate";
        trail8.elevationGain = 450;
        trail8.trailLengthKM = 6.0;
        trail8.waterSources = false;
        trail8.bestSeason = "Oct-Feb";
        trail8.dailyHikerLimit = 400;
        trail8.campingPermitted = false;
        trail8.emergencyBeacon = "PLB-2008";
        trail8.trailheadAltitude = 1250;
        trail8.wildlifeCorridor = false;
        trail8.checkpointCount = 2;
        trail8.summitView = "Bangalore Skyline";
        trail8.technicalSections = true;
        trail8.avgCompletionTime = 3.0;
        trail8.forestType = "Scrub Forest";
        trail8.solarChargers = true;
        trail8.biodiversityHotspot = 4;
        trail8.rescueHelipad = "SKG-Heli-1";
        trail8.nightHiking = true;
        trail8.annualMaintenance = 850000.00;
        trail8.trailGuardianNGO = "BLR Trekkers";
        trail8.leechSeason = false;
        trail8.peakBaggingRank = "Sunrise #1";
        
        System.out.println("Trail ID: " + trail8.trailId);
        System.out.println("Trail Name: " + trail8.trailName);
        System.out.println("Mountain Range: " + trail8.mountainRange);
        System.out.println("Permit Required: " + trail8.permitRequired);
        System.out.println("Difficulty Grade: " + trail8.difficultyGrade);
        System.out.println("Elevation Gain: " + trail8.elevationGain + "m");
        System.out.println("Trail Length: " + trail8.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail8.waterSources);
        System.out.println("Best Season: " + trail8.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail8.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail8.campingPermitted);
        System.out.println("Emergency Beacon: " + trail8.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail8.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail8.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail8.checkpointCount);
        System.out.println("Summit View: " + trail8.summitView);
        System.out.println("Technical Sections: " + trail8.technicalSections);
        System.out.println("Avg Completion Time: " + trail8.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail8.forestType);
        System.out.println("Solar Chargers: " + trail8.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail8.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail8.rescueHelipad);
        System.out.println("Night Hiking: " + trail8.nightHiking);
        System.out.println("Annual Maintenance: " + trail8.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail8.trailGuardianNGO);
        System.out.println("Leech Season: " + trail8.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail8.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail9 = new TrekkingTrails();
        trail9.trailId = 2009;
        trail9.trailName = "Anthargange Caves";
        trail9.mountainRange = "Kolar Hills";
        trail9.permitRequired = false;
        trail9.difficultyGrade = "Easy";
        trail9.elevationGain = 200;
        trail9.trailLengthKM = 4.5;
        trail9.waterSources = true;
        trail9.bestSeason = "Year Round";
        trail9.dailyHikerLimit = 600;
        trail9.campingPermitted = false;
        trail9.emergencyBeacon = "SBR-2009";
        trail9.trailheadAltitude = 950;
        trail9.wildlifeCorridor = false;
        trail9.checkpointCount = 1;
        trail9.summitView = "Cave Vista";
        trail9.technicalSections = true;
        trail9.avgCompletionTime = 2.5;
        trail9.forestType = "Dry Deciduous";
        trail9.solarChargers = false;
        trail9.biodiversityHotspot = 3;
        trail9.rescueHelipad = "ANTH-Heli-1";
        trail9.nightHiking = true;
        trail9.annualMaintenance = 420000.00;
        trail9.trailGuardianNGO = "Kolar Explorers";
        trail9.leechSeason = false;
        trail9.peakBaggingRank = "Cave #1";
        
        System.out.println("Trail ID: " + trail9.trailId);
        System.out.println("Trail Name: " + trail9.trailName);
        System.out.println("Mountain Range: " + trail9.mountainRange);
        System.out.println("Permit Required: " + trail9.permitRequired);
        System.out.println("Difficulty Grade: " + trail9.difficultyGrade);
        System.out.println("Elevation Gain: " + trail9.elevationGain + "m");
        System.out.println("Trail Length: " + trail9.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail9.waterSources);
        System.out.println("Best Season: " + trail9.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail9.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail9.campingPermitted);
        System.out.println("Emergency Beacon: " + trail9.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail9.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail9.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail9.checkpointCount);
        System.out.println("Summit View: " + trail9.summitView);
        System.out.println("Technical Sections: " + trail9.technicalSections);
        System.out.println("Avg Completion Time: " + trail9.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail9.forestType);
        System.out.println("Solar Chargers: " + trail9.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail9.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail9.rescueHelipad);
        System.out.println("Night Hiking: " + trail9.nightHiking);
        System.out.println("Annual Maintenance: " + trail9.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail9.trailGuardianNGO);
        System.out.println("Leech Season: " + trail9.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail9.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail10 = new TrekkingTrails();
        trail10.trailId = 2010;
        trail10.trailName = "Avathi Ridge Trail";
        trail10.mountainRange = "Nandi Betta Range";
        trail10.permitRequired = false;
        trail10.difficultyGrade = "Moderate";
        trail10.elevationGain = 380;
        trail10.trailLengthKM = 7.8;
        trail10.waterSources = true;
        trail10.bestSeason = "Sep-Apr";
        trail10.dailyHikerLimit = 320;
        trail10.campingPermitted = true;
        trail10.emergencyBeacon = "PLB-2010";
        trail10.trailheadAltitude = 850;
        trail10.wildlifeCorridor = true;
        trail10.checkpointCount = 2;
        trail10.summitView = "Skandagiri Vista";
        trail10.technicalSections = false;
        trail10.avgCompletionTime = 4.2;
        trail10.forestType = "Mixed Deciduous";
        trail10.solarChargers = true;
        trail10.biodiversityHotspot = 6;
        trail10.rescueHelipad = "AVT-Heli-1";
        trail10.nightHiking = false;
        trail10.annualMaintenance = 680000.00;
        trail10.trailGuardianNGO = "B'lore Mountaineers";
        trail10.leechSeason = true;
        trail10.peakBaggingRank = "Ridge #2";
        
        System.out.println("Trail ID: " + trail10.trailId);
        System.out.println("Trail Name: " + trail10.trailName);
        System.out.println("Mountain Range: " + trail10.mountainRange);
        System.out.println("Permit Required: " + trail10.permitRequired);
        System.out.println("Difficulty Grade: " + trail10.difficultyGrade);
        System.out.println("Elevation Gain: " + trail10.elevationGain + "m");
        System.out.println("Trail Length: " + trail10.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail10.waterSources);
        System.out.println("Best Season: " + trail10.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail10.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail10.campingPermitted);
        System.out.println("Emergency Beacon: " + trail10.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail10.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail10.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail10.checkpointCount);
        System.out.println("Summit View: " + trail10.summitView);
        System.out.println("Technical Sections: " + trail10.technicalSections);
        System.out.println("Avg Completion Time: " + trail10.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail10.forestType);
        System.out.println("Solar Chargers: " + trail10.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail10.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail10.rescueHelipad);
        System.out.println("Night Hiking: " + trail10.nightHiking);
        System.out.println("Annual Maintenance: " + trail10.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail10.trailGuardianNGO);
        System.out.println("Leech Season: " + trail10.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail10.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail11 = new TrekkingTrails();
        trail11.trailId = 2011;
        trail11.trailName = "Meenagadi Peak";
        trail11.mountainRange = "Brahmagiri Range";
        trail11.permitRequired = true;
        trail11.difficultyGrade = "Moderate";
        trail11.elevationGain = 1620;
        trail11.trailLengthKM = 14.8;
        trail11.waterSources = true;
        trail11.bestSeason = "Sep-May";
        trail11.dailyHikerLimit = 250;
        trail11.campingPermitted = true;
        trail11.emergencyBeacon = "PLB-2011";
        trail11.trailheadAltitude = 1100;
        trail11.wildlifeCorridor = true;
        trail11.checkpointCount = 3;
        trail11.summitView = "Coorg Panorama";
        trail11.technicalSections = false;
        trail11.avgCompletionTime = 6.2;
        trail11.forestType = "Montane Shola";
        trail11.solarChargers = true;
        trail11.biodiversityHotspot = 8;
        trail11.rescueHelipad = "MEEN-Heli-1";
        trail11.nightHiking = false;
        trail11.annualMaintenance = 920000.00;
        trail11.trailGuardianNGO = "Coorg Trekkers";
        trail11.leechSeason = true;
        trail11.peakBaggingRank = "Coorg #2";
        
        System.out.println("Trail ID: " + trail11.trailId);
        System.out.println("Trail Name: " + trail11.trailName);
        System.out.println("Mountain Range: " + trail11.mountainRange);
        System.out.println("Permit Required: " + trail11.permitRequired);
        System.out.println("Difficulty Grade: " + trail11.difficultyGrade);
        System.out.println("Elevation Gain: " + trail11.elevationGain + "m");
        System.out.println("Trail Length: " + trail11.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail11.waterSources);
        System.out.println("Best Season: " + trail11.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail11.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail11.campingPermitted);
        System.out.println("Emergency Beacon: " + trail11.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail11.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail11.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail11.checkpointCount);
        System.out.println("Summit View: " + trail11.summitView);
        System.out.println("Technical Sections: " + trail11.technicalSections);
        System.out.println("Avg Completion Time: " + trail11.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail11.forestType);
        System.out.println("Solar Chargers: " + trail11.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail11.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail11.rescueHelipad);
        System.out.println("Night Hiking: " + trail11.nightHiking);
        System.out.println("Annual Maintenance: " + trail11.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail11.trailGuardianNGO);
        System.out.println("Leech Season: " + trail11.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail11.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail12 = new TrekkingTrails();
        trail12.trailId = 2012;
        trail12.trailName = "Bandaje Ridge";
        trail12.mountainRange = "Pushpagiri Range";
        trail12.permitRequired = true;
        trail12.difficultyGrade = "Difficult";
        trail12.elevationGain = 1520;
        trail12.trailLengthKM = 20.1;
        trail12.waterSources = true;
        trail12.bestSeason = "Oct-Mar";
        trail12.dailyHikerLimit = 140;
        trail12.campingPermitted = true;
        trail12.emergencyBeacon = "PLB-2012";
        trail12.trailheadAltitude = 1050;
        trail12.wildlifeCorridor = true;
        trail12.checkpointCount = 4;
        trail12.summitView = "Ballalarayana Fort";
        trail12.technicalSections = true;
        trail12.avgCompletionTime = 9.0;
        trail12.forestType = "Rainforest";
        trail12.solarChargers = true;
        trail12.biodiversityHotspot = 9;
        trail12.rescueHelipad = "BAND-Heli-1";
        trail12.nightHiking = false;
        trail12.annualMaintenance = 1150000.00;
        trail12.trailGuardianNGO = "Subramanya Treks";
        trail12.leechSeason = true;
        trail12.peakBaggingRank = "Toughest #3";
        
        System.out.println("Trail ID: " + trail12.trailId);
        System.out.println("Trail Name: " + trail12.trailName);
        System.out.println("Mountain Range: " + trail12.mountainRange);
        System.out.println("Permit Required: " + trail12.permitRequired);
        System.out.println("Difficulty Grade: " + trail12.difficultyGrade);
        System.out.println("Elevation Gain: " + trail12.elevationGain + "m");
        System.out.println("Trail Length: " + trail12.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail12.waterSources);
        System.out.println("Best Season: " + trail12.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail12.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail12.campingPermitted);
        System.out.println("Emergency Beacon: " + trail12.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail12.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail12.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail12.checkpointCount);
        System.out.println("Summit View: " + trail12.summitView);
        System.out.println("Technical Sections: " + trail12.technicalSections);
        System.out.println("Avg Completion Time: " + trail12.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail12.forestType);
        System.out.println("Solar Chargers: " + trail12.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail12.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail12.rescueHelipad);
        System.out.println("Night Hiking: " + trail12.nightHiking);
        System.out.println("Annual Maintenance: " + trail12.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail12.trailGuardianNGO);
        System.out.println("Leech Season: " + trail12.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail12.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail13 = new TrekkingTrails();
        trail13.trailId = 2013;
        trail13.trailName = "Kurinjal Peak";
        trail13.mountainRange = "Brahmagiri Range";
        trail13.permitRequired = true;
        trail13.difficultyGrade = "Moderate-Difficult";
        trail13.elevationGain = 1580;
        trail13.trailLengthKM = 15.6;
        trail13.waterSources = true;
        trail13.bestSeason = "Nov-Apr";
        trail13.dailyHikerLimit = 200;
        trail13.campingPermitted = true;
        trail13.emergencyBeacon = "PLB-2013";
        trail13.trailheadAltitude = 1150;
        trail13.wildlifeCorridor = true;
        trail13.checkpointCount = 3;
        trail13.summitView = "Talacauvery View";
        trail13.technicalSections = false;
        trail13.avgCompletionTime = 7.8;
        trail13.forestType = "Moist Deciduous";
        trail13.solarChargers = true;
        trail13.biodiversityHotspot = 8;
        trail13.rescueHelipad = "KURJ-Heli-1";
        trail13.nightHiking = false;
        trail13.annualMaintenance = 980000.00;
        trail13.trailGuardianNGO = "Talacauvery Treks";
        trail13.leechSeason = true;
        trail13.peakBaggingRank = "Viewpoint #1";
        
        System.out.println("Trail ID: " + trail13.trailId);
        System.out.println("Trail Name: " + trail13.trailName);
        System.out.println("Mountain Range: " + trail13.mountainRange);
        System.out.println("Permit Required: " + trail13.permitRequired);
        System.out.println("Difficulty Grade: " + trail13.difficultyGrade);
        System.out.println("Elevation Gain: " + trail13.elevationGain + "m");
        System.out.println("Trail Length: " + trail13.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail13.waterSources);
        System.out.println("Best Season: " + trail13.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail13.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail13.campingPermitted);
        System.out.println("Emergency Beacon: " + trail13.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail13.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail13.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail13.checkpointCount);
        System.out.println("Summit View: " + trail13.summitView);
        System.out.println("Technical Sections: " + trail13.technicalSections);
        System.out.println("Avg Completion Time: " + trail13.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail13.forestType);
        System.out.println("Solar Chargers: " + trail13.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail13.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail13.rescueHelipad);
        System.out.println("Night Hiking: " + trail13.nightHiking);
        System.out.println("Annual Maintenance: " + trail13.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail13.trailGuardianNGO);
        System.out.println("Leech Season: " + trail13.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail13.peakBaggingRank);
        System.out.println("-----------------------------");



        TrekkingTrails trail14 = new TrekkingTrails();
        trail14.trailId = 2014;
        trail14.trailName = "Sakleshpur Manjarabad";
        trail14.mountainRange = "Western Ghats";
        trail14.permitRequired = false;
        trail14.difficultyGrade = "Easy-Moderate";
        trail14.elevationGain = 980;
        trail14.trailLengthKM = 12.3;
        trail14.waterSources = true;
        trail14.bestSeason = "Sep-Apr";
        trail14.dailyHikerLimit = 380;
        trail14.campingPermitted = true;
        trail14.emergencyBeacon = "PLB-2014";
        trail14.trailheadAltitude = 1050;
        trail14.wildlifeCorridor = true;
        trail14.checkpointCount = 2;
        trail14.summitView = "Manjarabad Fort";
        trail14.technicalSections = false;
        trail14.avgCompletionTime = 5.5;
        trail14.forestType = "Coffee Plantation";
        trail14.solarChargers = true;
        trail14.biodiversityHotspot = 7;
        trail14.rescueHelipad = "SAKL-Heli-1";
        trail14.nightHiking = false;
        trail14.annualMaintenance = 740000.00;
        trail14.trailGuardianNGO = "Sakleshpur Treks";
        trail14.leechSeason = true;
        trail14.peakBaggingRank = "Fort #1";
        
        System.out.println("Trail ID: " + trail14.trailId);
        System.out.println("Trail Name: " + trail14.trailName);
        System.out.println("Mountain Range: " + trail14.mountainRange);
        System.out.println("Permit Required: " + trail14.permitRequired);
        System.out.println("Difficulty Grade: " + trail14.difficultyGrade);
        System.out.println("Elevation Gain: " + trail14.elevationGain + "m");
        System.out.println("Trail Length: " + trail14.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail14.waterSources);
        System.out.println("Best Season: " + trail14.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail14.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail14.campingPermitted);
        System.out.println("Emergency Beacon: " + trail14.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail14.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail14.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail14.checkpointCount);
        System.out.println("Summit View: " + trail14.summitView);
        System.out.println("Technical Sections: " + trail14.technicalSections);
        System.out.println("Avg Completion Time: " + trail14.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail14.forestType);
        System.out.println("Solar Chargers: " + trail14.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail14.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail14.rescueHelipad);
        System.out.println("Night Hiking: " + trail14.nightHiking);
        System.out.println("Annual Maintenance: " + trail14.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail14.trailGuardianNGO);
        System.out.println("Leech Season: " + trail14.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail14.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail15 = new TrekkingTrails();
        trail15.trailId = 2015;
        trail15.trailName = "Uttari Betta";
        trail15.mountainRange = "Uttara Kannada Hills";
        trail15.permitRequired = true;
        trail15.difficultyGrade = "Moderate";
        trail15.elevationGain = 1250;
        trail15.trailLengthKM = 10.8;
        trail15.waterSources = true;
        trail15.bestSeason = "Oct-Mar";
        trail15.dailyHikerLimit = 290;
        trail15.campingPermitted = true;
        trail15.emergencyBeacon = "PLB-2015";
        trail15.trailheadAltitude = 800;
        trail15.wildlifeCorridor = true;
        trail15.checkpointCount = 3;
        trail15.summitView = "Arabian Sea View";
        trail15.technicalSections = true;
        trail15.avgCompletionTime = 6.8;
        trail15.forestType = "Evergreen Rainforest";
        trail15.solarChargers = true;
        trail15.biodiversityHotspot = 9;
        trail15.rescueHelipad = "UTTR-Heli-1";
        trail15.nightHiking = false;
        trail15.annualMaintenance = 860000.00;
        trail15.trailGuardianNGO = "Karwar Trekkers";
        trail15.leechSeason = true;
        trail15.peakBaggingRank = "Sea View #1";
        
        System.out.println("Trail ID: " + trail15.trailId);
        System.out.println("Trail Name: " + trail15.trailName);
        System.out.println("Mountain Range: " + trail15.mountainRange);
        System.out.println("Permit Required: " + trail15.permitRequired);
        System.out.println("Difficulty Grade: " + trail15.difficultyGrade);
        System.out.println("Elevation Gain: " + trail15.elevationGain + "m");
        System.out.println("Trail Length: " + trail15.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail15.waterSources);
        System.out.println("Best Season: " + trail15.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail15.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail15.campingPermitted);
        System.out.println("Emergency Beacon: " + trail15.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail15.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail15.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail15.checkpointCount);
        System.out.println("Summit View: " + trail15.summitView);
        System.out.println("Technical Sections: " + trail15.technicalSections);
        System.out.println("Avg Completion Time: " + trail15.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail15.forestType);
        System.out.println("Solar Chargers: " + trail15.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail15.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail15.rescueHelipad);
        System.out.println("Night Hiking: " + trail15.nightHiking);
        System.out.println("Annual Maintenance: " + trail15.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail15.trailGuardianNGO);
        System.out.println("Leech Season: " + trail15.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail15.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail16 = new TrekkingTrails();
        trail16.trailId = 2016;
        trail16.trailName = "Devaramane Peak";
        trail16.mountainRange = "Sahyadri Range";
        trail16.permitRequired = true;
        trail16.difficultyGrade = "Difficult";
        trail16.elevationGain = 1445;
        trail16.trailLengthKM = 18.5;
        trail16.waterSources = true;
        trail16.bestSeason = "Nov-Feb";
        trail16.dailyHikerLimit = 160;
        trail16.campingPermitted = true;
        trail16.emergencyBeacon = "PLB-2016";
        trail16.trailheadAltitude = 920;
        trail16.wildlifeCorridor = true;
        trail16.checkpointCount = 4;
        trail16.summitView = "Pushpagiri Panorama";
        trail16.technicalSections = true;
        trail16.avgCompletionTime = 8.2;
        trail16.forestType = "Shola Forest";
        trail16.solarChargers = true;
        trail16.biodiversityHotspot = 10;
        trail16.rescueHelipad = "DEVA-Heli-1";
        trail16.nightHiking = false;
        trail16.annualMaintenance = 1020000.00;
        trail16.trailGuardianNGO = "Samse Trekkers";
        trail16.leechSeason = true;
        trail16.peakBaggingRank = "Hidden Gem #1";
        
        System.out.println("Trail ID: " + trail16.trailId);
        System.out.println("Trail Name: " + trail16.trailName);
        System.out.println("Mountain Range: " + trail16.mountainRange);
        System.out.println("Permit Required: " + trail16.permitRequired);
        System.out.println("Difficulty Grade: " + trail16.difficultyGrade);
        System.out.println("Elevation Gain: " + trail16.elevationGain + "m");
        System.out.println("Trail Length: " + trail16.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail16.waterSources);
        System.out.println("Best Season: " + trail16.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail16.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail16.campingPermitted);
        System.out.println("Emergency Beacon: " + trail16.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail16.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail16.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail16.checkpointCount);
        System.out.println("Summit View: " + trail16.summitView);
        System.out.println("Technical Sections: " + trail16.technicalSections);
        System.out.println("Avg Completion Time: " + trail16.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail16.forestType);
        System.out.println("Solar Chargers: " + trail16.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail16.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail16.rescueHelipad);
        System.out.println("Night Hiking: " + trail16.nightHiking);
        System.out.println("Annual Maintenance: " + trail16.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail16.trailGuardianNGO);
        System.out.println("Leech Season: " + trail16.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail16.peakBaggingRank);
        System.out.println("-----------------------------");


        TrekkingTrails trail17 = new TrekkingTrails();
        trail17.trailId = 2017;
        trail17.trailName = "Savandurga West";
        trail17.mountainRange = "Magadi Hills";
        trail17.permitRequired = false;
        trail17.difficultyGrade = "Moderate-Difficult";
        trail17.elevationGain = 1220;
        trail17.trailLengthKM = 9.5;
        trail17.waterSources = false;
        trail17.bestSeason = "Oct-Mar";
        trail17.dailyHikerLimit = 500;
        trail17.campingPermitted = false;
        trail17.emergencyBeacon = "PLB-2017";
        trail17.trailheadAltitude = 780;
        trail17.wildlifeCorridor = true;
        trail17.checkpointCount = 2;
        trail17.summitView = "Asia's Largest Monolith";
        trail17.technicalSections = true;
        trail17.avgCompletionTime = 5.2;
        trail17.forestType = "Dry Scrub";
        trail17.solarChargers = true;
        trail17.biodiversityHotspot = 6;
        trail17.rescueHelipad = "SAVW-Heli-1";
        trail17.nightHiking = true;
        trail17.annualMaintenance = 950000.00;
        trail17.trailGuardianNGO = "Magadi Trekkers";
        trail17.leechSeason = false;
        trail17.peakBaggingRank = "Monolith #1";
        
        System.out.println("Trail ID: " + trail17.trailId);
        System.out.println("Trail Name: " + trail17.trailName);
        System.out.println("Mountain Range: " + trail17.mountainRange);
        System.out.println("Permit Required: " + trail17.permitRequired);
        System.out.println("Difficulty Grade: " + trail17.difficultyGrade);
        System.out.println("Elevation Gain: " + trail17.elevationGain + "m");
        System.out.println("Trail Length: " + trail17.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail17.waterSources);
        System.out.println("Best Season: " + trail17.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail17.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail17.campingPermitted);
        System.out.println("Emergency Beacon: " + trail17.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail17.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail17.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail17.checkpointCount);
        System.out.println("Summit View: " + trail17.summitView);
        System.out.println("Technical Sections: " + trail17.technicalSections);
        System.out.println("Avg Completion Time: " + trail17.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail17.forestType);
        System.out.println("Solar Chargers: " + trail17.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail17.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail17.rescueHelipad);
        System.out.println("Night Hiking: " + trail17.nightHiking);
        System.out.println("Annual Maintenance: " + trail17.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail17.trailGuardianNGO);
        System.out.println("Leech Season: " + trail17.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail17.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail18 = new TrekkingTrails();
        trail18.trailId = 2018;
        trail18.trailName = "Shivagange Peak";
        trail18.mountainRange = "Tumkur Hills";
        trail18.permitRequired = false;
        trail18.difficultyGrade = "Moderate";
        trail18.elevationGain = 1350;
        trail18.trailLengthKM = 8.2;
        trail18.waterSources = true;
        trail18.bestSeason = "Sep-Apr";
        trail18.dailyHikerLimit = 650;
        trail18.campingPermitted = false;
        trail18.emergencyBeacon = "SBR-2018";
        trail18.trailheadAltitude = 650;
        trail18.wildlifeCorridor = false;
        trail18.checkpointCount = 1;
        trail18.summitView = "Nandi Hills Horizon";
        trail18.technicalSections = true;
        trail18.avgCompletionTime = 4.8;
        trail18.forestType = "Mixed Deciduous";
        trail18.solarChargers = true;
        trail18.biodiversityHotspot = 5;
        trail18.rescueHelipad = "SHVG-Heli-1";
        trail18.nightHiking = true;
        trail18.annualMaintenance = 720000.00;
        trail18.trailGuardianNGO = "Tumkur Climbers";
        trail18.leechSeason = false;
        trail18.peakBaggingRank = "Spiritual #1";
        
        System.out.println("Trail ID: " + trail18.trailId);
        System.out.println("Trail Name: " + trail18.trailName);
        System.out.println("Mountain Range: " + trail18.mountainRange);
        System.out.println("Permit Required: " + trail18.permitRequired);
        System.out.println("Difficulty Grade: " + trail18.difficultyGrade);
        System.out.println("Elevation Gain: " + trail18.elevationGain + "m");
        System.out.println("Trail Length: " + trail18.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail18.waterSources);
        System.out.println("Best Season: " + trail18.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail18.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail18.campingPermitted);
        System.out.println("Emergency Beacon: " + trail18.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail18.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail18.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail18.checkpointCount);
        System.out.println("Summit View: " + trail18.summitView);
        System.out.println("Technical Sections: " + trail18.technicalSections);
        System.out.println("Avg Completion Time: " + trail18.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail18.forestType);
        System.out.println("Solar Chargers: " + trail18.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail18.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail18.rescueHelipad);
        System.out.println("Night Hiking: " + trail18.nightHiking);
        System.out.println("Annual Maintenance: " + trail18.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail18.trailGuardianNGO);
        System.out.println("Leech Season: " + trail18.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail18.peakBaggingRank);
        System.out.println("-----------------------------");


        TrekkingTrails trail19 = new TrekkingTrails();
        trail19.trailId = 2019;
        trail19.trailName = "Makalidurga Fort";
        trail19.mountainRange = "Yelahanka Hills";
        trail19.permitRequired = false;
        trail19.difficultyGrade = "Easy-Moderate";
        trail19.elevationGain = 410;
        trail19.trailLengthKM = 5.5;
        trail19.waterSources = true;
        trail19.bestSeason = "Oct-Apr";
        trail19.dailyHikerLimit = 750;
        trail19.campingPermitted = true;
        trail19.emergencyBeacon = "PLB-2019";
        trail19.trailheadAltitude = 950;
        trail19.wildlifeCorridor = false;
        trail19.checkpointCount = 1;
        trail19.summitView = "Railway + Lake View";
        trail19.technicalSections = false;
        trail19.avgCompletionTime = 3.2;
        trail19.forestType = "Scrub Jungle";
        trail19.solarChargers = true;
        trail19.biodiversityHotspot = 4;
        trail19.rescueHelipad = "MAKA-Heli-1";
        trail19.nightHiking = true;
        trail19.annualMaintenance = 580000.00;
        trail19.trailGuardianNGO = "Yelahanka Trekkers";
        trail19.leechSeason = false;
        trail19.peakBaggingRank = "Railway #1";
        
        System.out.println("Trail ID: " + trail19.trailId);
        System.out.println("Trail Name: " + trail19.trailName);
        System.out.println("Mountain Range: " + trail19.mountainRange);
        System.out.println("Permit Required: " + trail19.permitRequired);
        System.out.println("Difficulty Grade: " + trail19.difficultyGrade);
        System.out.println("Elevation Gain: " + trail19.elevationGain + "m");
        System.out.println("Trail Length: " + trail19.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail19.waterSources);
        System.out.println("Best Season: " + trail19.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail19.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail19.campingPermitted);
        System.out.println("Emergency Beacon: " + trail19.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail19.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail19.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail19.checkpointCount);
        System.out.println("Summit View: " + trail19.summitView);
        System.out.println("Technical Sections: " + trail19.technicalSections);
        System.out.println("Avg Completion Time: " + trail19.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail19.forestType);
        System.out.println("Solar Chargers: " + trail19.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail19.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail19.rescueHelipad);
        System.out.println("Night Hiking: " + trail19.nightHiking);
        System.out.println("Annual Maintenance: " + trail19.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail19.trailGuardianNGO);
        System.out.println("Leech Season: " + trail19.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail19.peakBaggingRank);
        System.out.println("-----------------------------");

        TrekkingTrails trail20 = new TrekkingTrails();
        trail20.trailId = 2020;
        trail20.trailName = "Ettina Bhuja";
        trail20.mountainRange = "Charmadi Ghat";
        trail20.permitRequired = true;
        trail20.difficultyGrade = "Very Difficult";
        trail20.elevationGain = 1720;
        trail20.trailLengthKM = 23.8;
        trail20.waterSources = true;
        trail20.bestSeason = "Oct-Feb";
        trail20.dailyHikerLimit = 90;
        trail20.campingPermitted = true;
        trail20.emergencyBeacon = "PLB-2020";
        trail20.trailheadAltitude = 980;
        trail20.wildlifeCorridor = true;
        trail20.checkpointCount = 5;
        trail20.summitView = "Ox-Back Shoulder";
        trail20.technicalSections = true;
        trail20.avgCompletionTime = 11.5;
        trail20.forestType = "Evergreen Rainforest";
        trail20.solarChargers = true;
        trail20.biodiversityHotspot = 10;
        trail20.rescueHelipad = "ETTI-Heli-1";
        trail20.nightHiking = false;
        trail20.annualMaintenance = 1380000.00;
        trail20.trailGuardianNGO = "Charmadi Trekkers";
        trail20.leechSeason = true;
        trail20.peakBaggingRank = "Karnataka #2";
        
        System.out.println("Trail ID: " + trail20.trailId);
        System.out.println("Trail Name: " + trail20.trailName);
        System.out.println("Mountain Range: " + trail20.mountainRange);
        System.out.println("Permit Required: " + trail20.permitRequired);
        System.out.println("Difficulty Grade: " + trail20.difficultyGrade);
        System.out.println("Elevation Gain: " + trail20.elevationGain + "m");
        System.out.println("Trail Length: " + trail20.trailLengthKM + "km");
        System.out.println("Water Sources: " + trail20.waterSources);
        System.out.println("Best Season: " + trail20.bestSeason);
        System.out.println("Daily Hiker Limit: " + trail20.dailyHikerLimit);
        System.out.println("Camping Permitted: " + trail20.campingPermitted);
        System.out.println("Emergency Beacon: " + trail20.emergencyBeacon);
        System.out.println("Trailhead Altitude: " + trail20.trailheadAltitude + "m");
        System.out.println("Wildlife Corridor: " + trail20.wildlifeCorridor);
        System.out.println("Checkpoint Count: " + trail20.checkpointCount);
        System.out.println("Summit View: " + trail20.summitView);
        System.out.println("Technical Sections: " + trail20.technicalSections);
        System.out.println("Avg Completion Time: " + trail20.avgCompletionTime + "hrs");
        System.out.println("Forest Type: " + trail20.forestType);
        System.out.println("Solar Chargers: " + trail20.solarChargers);
        System.out.println("Biodiversity Hotspot: " + trail20.biodiversityHotspot);
        System.out.println("Rescue Helipad: " + trail20.rescueHelipad);
        System.out.println("Night Hiking: " + trail20.nightHiking);
        System.out.println("Annual Maintenance: " + trail20.annualMaintenance);
        System.out.println("Trail Guardian NGO: " + trail20.trailGuardianNGO);
        System.out.println("Leech Season: " + trail20.leechSeason);
        System.out.println("Peak Bagging Rank: " + trail20.peakBaggingRank);
        System.out.println("-----------------------------");

	
    }
}
