 class TVchannelExecutor {
    public static void main(String[] args) {
        TVchannel channel1 = new TVchannel();
        channel1.channelId = 1;
        channel1.channelName = "Star Sports 1";
        channel1.broadcastNetwork = "Star Network";
        channel1.sportsCategory = "Cricket";
        channel1.hdQuality = true;
        channel1.liveSports = true;
        channel1.viewerRating = 9.2;
        channel1.language = "Hindi";
        channel1.subscriptionFee = 25.50;
        channel1.channelNumber = 401;
        channel1.freeToAir = false;
        channel1.primaryGenre = "Sports";
        channel1.dailyViewership = 45000000;
        channel1.availableOnIPTV = true;
        channel1.logoColor = "Blue";
        
        TVchannel channel2 = new TVchannel();
        channel2.channelId = 2;
        channel2.channelName = "Sony Sports";
        channel2.broadcastNetwork = "Sony Network";
        channel2.sportsCategory = "Football";
        channel2.hdQuality = true;
        channel2.liveSports = true;
        channel2.viewerRating = 8.1;
        channel2.language = "English";
        channel2.subscriptionFee = 22.00;
        channel2.channelNumber = 402;
        channel2.freeToAir = false;
        channel2.primaryGenre = "Sports";
        channel2.dailyViewership = 28000000;
        channel2.availableOnIPTV = true;
        channel2.logoColor = "Red";
        
        System.out.println("Channel ID: " + channel1.channelId);
        System.out.println("Channel Name: " + channel1.channelName);
        System.out.println("Broadcast Network: " + channel1.broadcastNetwork);
        System.out.println("Sports Category: " + channel1.sportsCategory);
        System.out.println("HD Quality: " + channel1.hdQuality);
        System.out.println("Live Sports: " + channel1.liveSports);
        System.out.println("Viewer Rating: " + channel1.viewerRating);
        System.out.println("Language: " + channel1.language);
        System.out.println("Subscription Fee: " + channel1.subscriptionFee);
        System.out.println("Channel Number: " + channel1.channelNumber);
        System.out.println("Free To Air: " + channel1.freeToAir);
        System.out.println("Primary Genre: " + channel1.primaryGenre);
        System.out.println("Daily Viewership: " + channel1.dailyViewership);
        System.out.println("Available on IPTV: " + channel1.availableOnIPTV);
        System.out.println("Logo Color: " + channel1.logoColor);
        System.out.println("-----------------------------");
        
        System.out.println("Channel ID: " + channel2.channelId);
        System.out.println("Channel Name: " + channel2.channelName);
        System.out.println("Broadcast Network: " + channel2.broadcastNetwork);
        System.out.println("Sports Category: " + channel2.sportsCategory);
        System.out.println("HD Quality: " + channel2.hdQuality);
        System.out.println("Live Sports: " + channel2.liveSports);
        System.out.println("Viewer Rating: " + channel2.viewerRating);
        System.out.println("Language: " + channel2.language);
        System.out.println("Subscription Fee: " + channel2.subscriptionFee);
        System.out.println("Channel Number: " + channel2.channelNumber);
        System.out.println("Free To Air: " + channel2.freeToAir);
        System.out.println("Primary Genre: " + channel2.primaryGenre);
        System.out.println("Daily Viewership: " + channel2.dailyViewership);
        System.out.println("Available on IPTV: " + channel2.availableOnIPTV);
        System.out.println("Logo Color: " + channel2.logoColor);
        System.out.println("-----------------------------");
		
	    
        TVchannel channel3 = new TVchannel();
        channel3.channelId = 3;
        channel3.channelName = "Sports18 1 HD";
        channel3.broadcastNetwork = "Viacom18 Network";
        channel3.sportsCategory = "Kabaddi";
        channel3.hdQuality = true;
        channel3.liveSports = true;
        channel3.viewerRating = 8.5;
        channel3.language = "Hindi";
        channel3.subscriptionFee = 20.00;
        channel3.channelNumber = 403;
        channel3.freeToAir = false;
        channel3.primaryGenre = "Sports";
        channel3.dailyViewership = 35000000;
        channel3.availableOnIPTV = true;
        channel3.logoColor = "Orange";
        
        TVchannel channel4 = new TVchannel();
        channel4.channelId = 4;
        channel4.channelName = "DD Sports HD";
        channel4.broadcastNetwork = "Prasar Bharati";
        channel4.sportsCategory = "Multi-Sport";
        channel4.hdQuality = true;
        channel4.liveSports = true;
        channel4.viewerRating = 7.8;
        channel4.language = "Hindi";
        channel4.subscriptionFee = 0.00;
        channel4.channelNumber = 137;
        channel4.freeToAir = true;
        channel4.primaryGenre = "Sports";
        channel4.dailyViewership = 20000000;
        channel4.availableOnIPTV = true;
        channel4.logoColor = "Green";
        
        System.out.println("Channel ID: " + channel3.channelId);
        System.out.println("Channel Name: " + channel3.channelName);
        System.out.println("Broadcast Network: " + channel3.broadcastNetwork);
        System.out.println("Sports Category: " + channel3.sportsCategory);
        System.out.println("HD Quality: " + channel3.hdQuality);
        System.out.println("Live Sports: " + channel3.liveSports);
        System.out.println("Viewer Rating: " + channel3.viewerRating);
        System.out.println("Language: " + channel3.language);
        System.out.println("Subscription Fee: " + channel3.subscriptionFee);
        System.out.println("Channel Number: " + channel3.channelNumber);
        System.out.println("Free To Air: " + channel3.freeToAir);
        System.out.println("Primary Genre: " + channel3.primaryGenre);
        System.out.println("Daily Viewership: " + channel3.dailyViewership);
        System.out.println("Available on IPTV: " + channel3.availableOnIPTV);
        System.out.println("Logo Color: " + channel3.logoColor);
        System.out.println("-----------------------------");
        
        System.out.println("Channel ID: " + channel4.channelId);
        System.out.println("Channel Name: " + channel4.channelName);
        System.out.println("Broadcast Network: " + channel4.broadcastNetwork);
        System.out.println("Sports Category: " + channel4.sportsCategory);
        System.out.println("HD Quality: " + channel4.hdQuality);
        System.out.println("Live Sports: " + channel4.liveSports);
        System.out.println("Viewer Rating: " + channel4.viewerRating);
        System.out.println("Language: " + channel4.language);
        System.out.println("Subscription Fee: " + channel4.subscriptionFee);
        System.out.println("Channel Number: " + channel4.channelNumber);
        System.out.println("Free To Air: " + channel4.freeToAir);
        System.out.println("Primary Genre: " + channel4.primaryGenre);
        System.out.println("Daily Viewership: " + channel4.dailyViewership);
        System.out.println("Available on IPTV: " + channel4.availableOnIPTV);
        System.out.println("Logo Color: " + channel4.logoColor);
        System.out.println("-----------------------------");
	
	        TVchannel channel5 = new TVchannel();
        channel5.channelId = 5;
        channel5.channelName = "FanCode Sports";
        channel5.broadcastNetwork = "Dream Sports";
        channel5.sportsCategory = "Multi-Sport OTT";
        channel5.hdQuality = true;
        channel5.liveSports = true;
        channel5.viewerRating = 8.7;
        channel5.language = "English";
        channel5.subscriptionFee = 29.99;
        channel5.channelNumber = 405;
        channel5.freeToAir = false;
        channel5.primaryGenre = "Digital Sports";
        channel5.dailyViewership = 18000000;
        channel5.availableOnIPTV = true;
        channel5.logoColor = "Purple";
        
        System.out.println("Channel ID: " + channel5.channelId);
        System.out.println("Channel Name: " + channel5.channelName);
        System.out.println("Broadcast Network: " + channel5.broadcastNetwork);
        System.out.println("Sports Category: " + channel5.sportsCategory);
        System.out.println("HD Quality: " + channel5.hdQuality);
        System.out.println("Live Sports: " + channel5.liveSports);
        System.out.println("Viewer Rating: " + channel5.viewerRating);
        System.out.println("Language: " + channel5.language);
        System.out.println("Subscription Fee: " + channel5.subscriptionFee);
        System.out.println("Channel Number: " + channel5.channelNumber);
        System.out.println("Free To Air: " + channel5.freeToAir);
        System.out.println("Primary Genre: " + channel5.primaryGenre);
        System.out.println("Daily Viewership: " + channel5.dailyViewership);
        System.out.println("Available on IPTV: " + channel5.availableOnIPTV);
        System.out.println("Logo Color: " + channel5.logoColor);
        System.out.println("-----------------------------");

        TVchannel channel6 = new TVchannel();
        channel6.channelId = 6;
        channel6.channelName = "Sony Sports Ten 2 HD";
        channel6.broadcastNetwork = "Sony Pictures Networks";
        channel6.sportsCategory = "Football";
        channel6.hdQuality = true;
        channel6.liveSports = true;
        channel6.viewerRating = 8.9;
        channel6.language = "English";
        channel6.subscriptionFee = 24.00;
        channel6.channelNumber = 406;
        channel6.freeToAir = false;
        channel6.primaryGenre = "Sports";
        channel6.dailyViewership = 32000000;
        channel6.availableOnIPTV = true;
        channel6.logoColor = "Gold";
        
        System.out.println("Channel ID: " + channel6.channelId);
        System.out.println("Channel Name: " + channel6.channelName);
        System.out.println("Broadcast Network: " + channel6.broadcastNetwork);
        System.out.println("Sports Category: " + channel6.sportsCategory);
        System.out.println("HD Quality: " + channel6.hdQuality);
        System.out.println("Live Sports: " + channel6.liveSports);
        System.out.println("Viewer Rating: " + channel6.viewerRating);
        System.out.println("Language: " + channel6.language);
        System.out.println("Subscription Fee: " + channel6.subscriptionFee);
        System.out.println("Channel Number: " + channel6.channelNumber);
        System.out.println("Free To Air: " + channel6.freeToAir);
        System.out.println("Primary Genre: " + channel6.primaryGenre);
        System.out.println("Daily Viewership: " + channel6.dailyViewership);
        System.out.println("Available on IPTV: " + channel6.availableOnIPTV);
        System.out.println("Logo Color: " + channel6.logoColor);
        System.out.println("-----------------------------");

        TVchannel channel7 = new TVchannel();
        channel7.channelId = 7;
        channel7.channelName = "Star Sports 1 Hindi HD";
        channel7.broadcastNetwork = "Star Network";
        channel7.sportsCategory = "Cricket";
        channel7.hdQuality = true;
        channel7.liveSports = true;
        channel7.viewerRating = 9.5;
        channel7.language = "Hindi";
        channel7.subscriptionFee = 25.00;
        channel7.channelNumber = 459;
        channel7.freeToAir = false;
        channel7.primaryGenre = "Sports";
        channel7.dailyViewership = 42000000;
        channel7.availableOnIPTV = true;
        channel7.logoColor = "Blue";
        
        System.out.println("Channel ID: " + channel7.channelId);
        System.out.println("Channel Name: " + channel7.channelName);
        System.out.println("Broadcast Network: " + channel7.broadcastNetwork);
        System.out.println("Sports Category: " + channel7.sportsCategory);
        System.out.println("HD Quality: " + channel7.hdQuality);
        System.out.println("Live Sports: " + channel7.liveSports);
        System.out.println("Viewer Rating: " + channel7.viewerRating);
        System.out.println("Language: " + channel7.language);
        System.out.println("Subscription Fee: " + channel7.subscriptionFee);  // No $
        System.out.println("Channel Number: " + channel7.channelNumber);
        System.out.println("Free To Air: " + channel7.freeToAir);
        System.out.println("Primary Genre: " + channel7.primaryGenre);
        System.out.println("Daily Viewership: " + channel7.dailyViewership);
        System.out.println("Available on IPTV: " + channel7.availableOnIPTV);
        System.out.println("Logo Color: " + channel7.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel8 = new TVchannel();
        channel8.channelId = 8;
        channel8.channelName = "Sports 18 1";
        channel8.broadcastNetwork = "Viacom18 Network";
        channel8.sportsCategory = "Multi-Sport";
        channel8.hdQuality = false;
        channel8.liveSports = true;
        channel8.viewerRating = 8.3;
        channel8.language = "Hindi";
        channel8.subscriptionFee = 18.00;
        channel8.channelNumber = 488;
        channel8.freeToAir = false;
        channel8.primaryGenre = "Sports";
        channel8.dailyViewership = 30000000;
        channel8.availableOnIPTV = true;
        channel8.logoColor = "Orange";
        
        System.out.println("Channel ID: " + channel8.channelId);
        System.out.println("Channel Name: " + channel8.channelName);
        System.out.println("Broadcast Network: " + channel8.broadcastNetwork);
        System.out.println("Sports Category: " + channel8.sportsCategory);
        System.out.println("HD Quality: " + channel8.hdQuality);
        System.out.println("Live Sports: " + channel8.liveSports);
        System.out.println("Viewer Rating: " + channel8.viewerRating);
        System.out.println("Language: " + channel8.language);
        System.out.println("Subscription Fee: " + channel8.subscriptionFee);  // No $
        System.out.println("Channel Number: " + channel8.channelNumber);
        System.out.println("Free To Air: " + channel8.freeToAir);
        System.out.println("Primary Genre: " + channel8.primaryGenre);
        System.out.println("Daily Viewership: " + channel8.dailyViewership);
        System.out.println("Available on IPTV: " + channel8.availableOnIPTV);
        System.out.println("Logo Color: " + channel8.logoColor);
        System.out.println("-----------------------------");

        TVchannel channel9 = new TVchannel();
        channel9.channelId = 9;
        channel9.channelName = "Eurosport India";
        channel9.broadcastNetwork = "Warner Bros Discovery";
        channel9.sportsCategory = "Olympic Sports";
        channel9.hdQuality = true;
        channel9.liveSports = true;
        channel9.viewerRating = 7.9;
        channel9.language = "English";
        channel9.subscriptionFee = 19.50;
        channel9.channelNumber = 462;
        channel9.freeToAir = false;
        channel9.primaryGenre = "Sports";
        channel9.dailyViewership = 15000000;
        channel9.availableOnIPTV = true;
        channel9.logoColor = "Yellow";
        
        System.out.println("Channel ID: " + channel9.channelId);
        System.out.println("Channel Name: " + channel9.channelName);
        System.out.println("Broadcast Network: " + channel9.broadcastNetwork);
        System.out.println("Sports Category: " + channel9.sportsCategory);
        System.out.println("HD Quality: " + channel9.hdQuality);
        System.out.println("Live Sports: " + channel9.liveSports);
        System.out.println("Viewer Rating: " + channel9.viewerRating);
        System.out.println("Language: " + channel9.language);
        System.out.println("Subscription Fee: " + channel9.subscriptionFee);
        System.out.println("Channel Number: " + channel9.channelNumber);
        System.out.println("Free To Air: " + channel9.freeToAir);
        System.out.println("Primary Genre: " + channel9.primaryGenre);
        System.out.println("Daily Viewership: " + channel9.dailyViewership);
        System.out.println("Available on IPTV: " + channel9.availableOnIPTV);
        System.out.println("Logo Color: " + channel9.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel10 = new TVchannel();
        channel10.channelId = 10;
        channel10.channelName = "Vijay Super FM Sports";
        channel10.broadcastNetwork = "Vijay TV Network";
        channel10.sportsCategory = "Regional Sports";
        channel10.hdQuality = true;
        channel10.liveSports = true;
        channel10.viewerRating = 8.2;
        channel10.language = "Tamil";
        channel10.subscriptionFee = 15.00;
        channel10.channelNumber = 475;
        channel10.freeToAir = false;
        channel10.primaryGenre = "Sports";
        channel10.dailyViewership = 12000000;
        channel10.availableOnIPTV = true;
        channel10.logoColor = "Red";
        
        System.out.println("Channel ID: " + channel10.channelId);
        System.out.println("Channel Name: " + channel10.channelName);
        System.out.println("Broadcast Network: " + channel10.broadcastNetwork);
        System.out.println("Sports Category: " + channel10.sportsCategory);
        System.out.println("HD Quality: " + channel10.hdQuality);
        System.out.println("Live Sports: " + channel10.liveSports);
        System.out.println("Viewer Rating: " + channel10.viewerRating);
        System.out.println("Language: " + channel10.language);
        System.out.println("Subscription Fee: " + channel10.subscriptionFee);
        System.out.println("Channel Number: " + channel10.channelNumber);
        System.out.println("Free To Air: " + channel10.freeToAir);
        System.out.println("Primary Genre: " + channel10.primaryGenre);
        System.out.println("Daily Viewership: " + channel10.dailyViewership);
        System.out.println("Available on IPTV: " + channel10.availableOnIPTV);
        System.out.println("Logo Color: " + channel10.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel11 = new TVchannel();
        channel11.channelId = 11;
        channel11.channelName = "Zee Sports";
        channel11.broadcastNetwork = "Zee Entertainment";
        channel11.sportsCategory = "Wrestling";
        channel11.hdQuality = true;
        channel11.liveSports = true;
        channel11.viewerRating = 8.6;
        channel11.language = "Hindi";
        channel11.subscriptionFee = 21.00;
        channel11.channelNumber = 420;
        channel11.freeToAir = false;
        channel11.primaryGenre = "Sports";
        channel11.dailyViewership = 25000000;
        channel11.availableOnIPTV = true;
        channel11.logoColor = "Purple";
        
        System.out.println("Channel ID: " + channel11.channelId);
        System.out.println("Channel Name: " + channel11.channelName);
        System.out.println("Broadcast Network: " + channel11.broadcastNetwork);
        System.out.println("Sports Category: " + channel11.sportsCategory);
        System.out.println("HD Quality: " + channel11.hdQuality);
        System.out.println("Live Sports: " + channel11.liveSports);
        System.out.println("Viewer Rating: " + channel11.viewerRating);
        System.out.println("Language: " + channel11.language);
        System.out.println("Subscription Fee: " + channel11.subscriptionFee);
        System.out.println("Channel Number: " + channel11.channelNumber);
        System.out.println("Free To Air: " + channel11.freeToAir);
        System.out.println("Primary Genre: " + channel11.primaryGenre);
        System.out.println("Daily Viewership: " + channel11.dailyViewership);
        System.out.println("Available on IPTV: " + channel11.availableOnIPTV);
        System.out.println("Logo Color: " + channel11.logoColor);
        System.out.println("-----------------------------");


        TVchannel channel12 = new TVchannel();
        channel12.channelId = 12;
        channel12.channelName = "Sony Sports Ten 3 HD";
        channel12.broadcastNetwork = "Sony Pictures Networks";
        channel12.sportsCategory = "Cricket Hindi";
        channel12.hdQuality = true;
        channel12.liveSports = true;
        channel12.viewerRating = 8.4;
        channel12.language = "Hindi";
        channel12.subscriptionFee = 22.00;
        channel12.channelNumber = 475;
        channel12.freeToAir = false;
        channel12.primaryGenre = "Sports";
        channel12.dailyViewership = 38000000;
        channel12.availableOnIPTV = true;
        channel12.logoColor = "Green";
        
        System.out.println("Channel ID: " + channel12.channelId);
        System.out.println("Channel Name: " + channel12.channelName);
        System.out.println("Broadcast Network: " + channel12.broadcastNetwork);
        System.out.println("Sports Category: " + channel12.sportsCategory);
        System.out.println("HD Quality: " + channel12.hdQuality);
        System.out.println("Live Sports: " + channel12.liveSports);
        System.out.println("Viewer Rating: " + channel12.viewerRating);
        System.out.println("Language: " + channel12.language);
        System.out.println("Subscription Fee: " + channel12.subscriptionFee);
        System.out.println("Channel Number: " + channel12.channelNumber);
        System.out.println("Free To Air: " + channel12.freeToAir);
        System.out.println("Primary Genre: " + channel12.primaryGenre);
        System.out.println("Daily Viewership: " + channel12.dailyViewership);
        System.out.println("Available on IPTV: " + channel12.availableOnIPTV);
        System.out.println("Logo Color: " + channel12.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel13 = new TVchannel();
        channel13.channelId = 13;
        channel13.channelName = "Star Sports First";
        channel13.broadcastNetwork = "Star Network";
        channel13.sportsCategory = "Multi-Sport";
        channel13.hdQuality = true;
        channel13.liveSports = true;
        channel13.viewerRating = 8.0;
        channel13.language = "English";
        channel13.subscriptionFee = 20.00;
        channel13.channelNumber = 497;
        channel13.freeToAir = false;
        channel13.primaryGenre = "Sports";
        channel13.dailyViewership = 22000000;
        channel13.availableOnIPTV = true;
        channel13.logoColor = "Silver";
        
        System.out.println("Channel ID: " + channel13.channelId);
        System.out.println("Channel Name: " + channel13.channelName);
        System.out.println("Broadcast Network: " + channel13.broadcastNetwork);
        System.out.println("Sports Category: " + channel13.sportsCategory);
        System.out.println("HD Quality: " + channel13.hdQuality);
        System.out.println("Live Sports: " + channel13.liveSports);
        System.out.println("Viewer Rating: " + channel13.viewerRating);
        System.out.println("Language: " + channel13.language);
        System.out.println("Subscription Fee: " + channel13.subscriptionFee);
        System.out.println("Channel Number: " + channel13.channelNumber);
        System.out.println("Free To Air: " + channel13.freeToAir);
        System.out.println("Primary Genre: " + channel13.primaryGenre);
        System.out.println("Daily Viewership: " + channel13.dailyViewership);
        System.out.println("Available on IPTV: " + channel13.availableOnIPTV);
        System.out.println("Logo Color: " + channel13.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel14 = new TVchannel();
        channel14.channelId = 14;
        channel14.channelName = "Sports18 2";
        channel14.broadcastNetwork = "Viacom18 Network";
        channel14.sportsCategory = "Kabaddi";
        channel14.hdQuality = false;
        channel14.liveSports = true;
        channel14.viewerRating = 7.7;
        channel14.language = "Hindi";
        channel14.subscriptionFee = 16.00;
        channel14.channelNumber = 490;
        channel14.freeToAir = false;
        channel14.primaryGenre = "Sports";
        channel14.dailyViewership = 28000000;
        channel14.availableOnIPTV = true;
        channel14.logoColor = "Orange";
        
        System.out.println("Channel ID: " + channel14.channelId);
        System.out.println("Channel Name: " + channel14.channelName);
        System.out.println("Broadcast Network: " + channel14.broadcastNetwork);
        System.out.println("Sports Category: " + channel14.sportsCategory);
        System.out.println("HD Quality: " + channel14.hdQuality);
        System.out.println("Live Sports: " + channel14.liveSports);
        System.out.println("Viewer Rating: " + channel14.viewerRating);
        System.out.println("Language: " + channel14.language);
        System.out.println("Subscription Fee: " + channel14.subscriptionFee);
        System.out.println("Channel Number: " + channel14.channelNumber);
        System.out.println("Free To Air: " + channel14.freeToAir);
        System.out.println("Primary Genre: " + channel14.primaryGenre);
        System.out.println("Daily Viewership: " + channel14.dailyViewership);
        System.out.println("Available on IPTV: " + channel14.availableOnIPTV);
        System.out.println("Logo Color: " + channel14.logoColor);
        System.out.println("-----------------------------");


        TVchannel channel15 = new TVchannel();
        channel15.channelId = 15;
        channel15.channelName = "Star Sports 2 HD";
        channel15.broadcastNetwork = "Star Network";
        channel15.sportsCategory = "Cricket";
        channel15.hdQuality = true;
        channel15.liveSports = true;
        channel15.viewerRating = 9.1;
        channel15.language = "English";
        channel15.subscriptionFee = 24.00;
        channel15.channelNumber = 456;
        channel15.freeToAir = false;
        channel15.primaryGenre = "Sports";
        channel15.dailyViewership = 40000000;
        channel15.availableOnIPTV = true;
        channel15.logoColor = "Blue";
        
        System.out.println("Channel ID: " + channel15.channelId);
        System.out.println("Channel Name: " + channel15.channelName);
        System.out.println("Broadcast Network: " + channel15.broadcastNetwork);
        System.out.println("Sports Category: " + channel15.sportsCategory);
        System.out.println("HD Quality: " + channel15.hdQuality);
        System.out.println("Live Sports: " + channel15.liveSports);
        System.out.println("Viewer Rating: " + channel15.viewerRating);
        System.out.println("Language: " + channel15.language);
        System.out.println("Subscription Fee: " + channel15.subscriptionFee);
        System.out.println("Channel Number: " + channel15.channelNumber);
        System.out.println("Free To Air: " + channel15.freeToAir);
        System.out.println("Primary Genre: " + channel15.primaryGenre);
        System.out.println("Daily Viewership: " + channel15.dailyViewership);
        System.out.println("Available on IPTV: " + channel15.availableOnIPTV);
        System.out.println("Logo Color: " + channel15.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel16 = new TVchannel();
        channel16.channelId = 16;
        channel16.channelName = "Sony Sports Ten 1 HD";
        channel16.broadcastNetwork = "Sony Pictures Networks";
        channel16.sportsCategory = "Football";
        channel16.hdQuality = true;
        channel16.liveSports = true;
        channel16.viewerRating = 8.8;
        channel16.language = "English";
        channel16.subscriptionFee = 23.00;
        channel16.channelNumber = 454;
        channel16.freeToAir = false;
        channel16.primaryGenre = "Sports";
        channel16.dailyViewership = 29000000;
        channel16.availableOnIPTV = true;
        channel16.logoColor = "Red";
        
        System.out.println("Channel ID: " + channel16.channelId);
        System.out.println("Channel Name: " + channel16.channelName);
        System.out.println("Broadcast Network: " + channel16.broadcastNetwork);
        System.out.println("Sports Category: " + channel16.sportsCategory);
        System.out.println("HD Quality: " + channel16.hdQuality);
        System.out.println("Live Sports: " + channel16.liveSports);
        System.out.println("Viewer Rating: " + channel16.viewerRating);
        System.out.println("Language: " + channel16.language);
        System.out.println("Subscription Fee: " + channel16.subscriptionFee);
        System.out.println("Channel Number: " + channel16.channelNumber);
        System.out.println("Free To Air: " + channel16.freeToAir);
        System.out.println("Primary Genre: " + channel16.primaryGenre);
        System.out.println("Daily Viewership: " + channel16.dailyViewership);
        System.out.println("Available on IPTV: " + channel16.availableOnIPTV);
        System.out.println("Logo Color: " + channel16.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel17 = new TVchannel();
        channel17.channelId = 17;
        channel17.channelName = "Sports18 Khel";
        channel17.broadcastNetwork = "Viacom18 Network";
        channel17.sportsCategory = "Kabaddi";
        channel17.hdQuality = true;
        channel17.liveSports = true;
        channel17.viewerRating = 8.1;
        channel17.language = "Hindi";
        channel17.subscriptionFee = 17.00;
        channel17.channelNumber = 492;
        channel17.freeToAir = false;
        channel17.primaryGenre = "Sports";
        channel17.dailyViewership = 26000000;
        channel17.availableOnIPTV = true;
        channel17.logoColor = "Orange";
        
        System.out.println("Channel ID: " + channel17.channelId);
        System.out.println("Channel Name: " + channel17.channelName);
        System.out.println("Broadcast Network: " + channel17.broadcastNetwork);
        System.out.println("Sports Category: " + channel17.sportsCategory);
        System.out.println("HD Quality: " + channel17.hdQuality);
        System.out.println("Live Sports: " + channel17.liveSports);
        System.out.println("Viewer Rating: " + channel17.viewerRating);
        System.out.println("Language: " + channel17.language);
        System.out.println("Subscription Fee: " + channel17.subscriptionFee);
        System.out.println("Channel Number: " + channel17.channelNumber);
        System.out.println("Free To Air: " + channel17.freeToAir);
        System.out.println("Primary Genre: " + channel17.primaryGenre);
        System.out.println("Daily Viewership: " + channel17.dailyViewership);
        System.out.println("Available on IPTV: " + channel17.availableOnIPTV);
        System.out.println("Logo Color: " + channel17.logoColor);
        System.out.println("-----------------------------");

        TVchannel channel18 = new TVchannel();
        channel18.channelId = 18;
        channel18.channelName = "Ten Sports HD";
        channel18.broadcastNetwork = "Zee Network";
        channel18.sportsCategory = "Wrestling";
        channel18.hdQuality = true;
        channel18.liveSports = true;
        channel18.viewerRating = 8.3;
        channel18.language = "Hindi";
        channel18.subscriptionFee = 19.00;
        channel18.channelNumber = 415;
        channel18.freeToAir = false;
        channel18.primaryGenre = "Sports";
        channel18.dailyViewership = 24000000;
        channel18.availableOnIPTV = true;
        channel18.logoColor = "Yellow";
        
        System.out.println("Channel ID: " + channel18.channelId);
        System.out.println("Channel Name: " + channel18.channelName);
        System.out.println("Broadcast Network: " + channel18.broadcastNetwork);
        System.out.println("Sports Category: " + channel18.sportsCategory);
        System.out.println("HD Quality: " + channel18.hdQuality);
        System.out.println("Live Sports: " + channel18.liveSports);
        System.out.println("Viewer Rating: " + channel18.viewerRating);
        System.out.println("Language: " + channel18.language);
        System.out.println("Subscription Fee: " + channel18.subscriptionFee);
        System.out.println("Channel Number: " + channel18.channelNumber);
        System.out.println("Free To Air: " + channel18.freeToAir);
        System.out.println("Primary Genre: " + channel18.primaryGenre);
        System.out.println("Daily Viewership: " + channel18.dailyViewership);
        System.out.println("Available on IPTV: " + channel18.availableOnIPTV);
        System.out.println("Logo Color: " + channel18.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel19 = new TVchannel();
        channel19.channelId = 19;
        channel19.channelName = "DSport HD";
        channel19.broadcastNetwork = "Discovery Sports";
        channel19.sportsCategory = "Badminton";
        channel19.hdQuality = true;
        channel19.liveSports = true;
        channel19.viewerRating = 7.6;
        channel19.language = "English";
        channel19.subscriptionFee = 18.50;
        channel19.channelNumber = 463;
        channel19.freeToAir = false;
        channel19.primaryGenre = "Sports";
        channel19.dailyViewership = 13000000;
        channel19.availableOnIPTV = true;
        channel19.logoColor = "Green";
        
        System.out.println("Channel ID: " + channel19.channelId);
        System.out.println("Channel Name: " + channel19.channelName);
        System.out.println("Broadcast Network: " + channel19.broadcastNetwork);
        System.out.println("Sports Category: " + channel19.sportsCategory);
        System.out.println("HD Quality: " + channel19.hdQuality);
        System.out.println("Live Sports: " + channel19.liveSports);
        System.out.println("Viewer Rating: " + channel19.viewerRating);
        System.out.println("Language: " + channel19.language);
        System.out.println("Subscription Fee: " + channel19.subscriptionFee);
        System.out.println("Channel Number: " + channel19.channelNumber);
        System.out.println("Free To Air: " + channel19.freeToAir);
        System.out.println("Primary Genre: " + channel19.primaryGenre);
        System.out.println("Daily Viewership: " + channel19.dailyViewership);
        System.out.println("Available on IPTV: " + channel19.availableOnIPTV);
        System.out.println("Logo Color: " + channel19.logoColor);
        System.out.println("-----------------------------");
        
        TVchannel channel20 = new TVchannel();
        channel20.channelId = 20;
        channel20.channelName = "Neo Sports";
        channel20.broadcastNetwork = "Sun Network";
        channel20.sportsCategory = "Cricket Re-runs";
        channel20.hdQuality = false;
        channel20.liveSports = false;
        channel20.viewerRating = 6.8;
        channel20.language = "Hindi";
        channel20.subscriptionFee = 12.00;
        channel20.channelNumber = 512;
        channel20.freeToAir = false;
        channel20.primaryGenre = "Sports";
        channel20.dailyViewership = 8000000;
        channel20.availableOnIPTV = true;
        channel20.logoColor = "Black";
        
        System.out.println("Channel ID: " + channel20.channelId);
        System.out.println("Channel Name: " + channel20.channelName);
        System.out.println("Broadcast Network: " + channel20.broadcastNetwork);
        System.out.println("Sports Category: " + channel20.sportsCategory);
        System.out.println("HD Quality: " + channel20.hdQuality);
        System.out.println("Live Sports: " + channel20.liveSports);
        System.out.println("Viewer Rating: " + channel20.viewerRating);
        System.out.println("Language: " + channel20.language);
        System.out.println("Subscription Fee: " + channel20.subscriptionFee);
        System.out.println("Channel Number: " + channel20.channelNumber);
        System.out.println("Free To Air: " + channel20.freeToAir);
        System.out.println("Primary Genre: " + channel20.primaryGenre);
        System.out.println("Daily Viewership: " + channel20.dailyViewership);
        System.out.println("Available on IPTV: " + channel20.availableOnIPTV);
        System.out.println("Logo Color: " + channel20.logoColor);
        System.out.println("-----------------------------");




	
		
		
    }
}
