class VideoGamesExecutor {
    public static void main(String[] args) {

        VideoGames game1 = new VideoGames();
        
        game1.gameId = 1001;
        game1.gameTitle = "Cyberpunk 2077";
        game1.gameGenre = "Open World RPG";
        game1.multiplayerSupport = false;
        game1.releasePlatform = "PC/PS5/Xbox Series";
        game1.playerCountPeak = 10500000;
        game1.gameEngine = "REDengine 4";
        game1.rayTracing = true;
        game1.gameScoreMetacritic = 86.0;
        game1.esrbRating = "Mature 17+";
        game1.battleRoyale = false;
        game1.downloadSizeGB = 70;
        game1.leadDeveloper = "CD Projekt RED";
        game1.crossPlatform = false;
        game1.esportsPrizePool = 0;
        game1.gameMode = "Single Player";
        game1.dlcAvailable = true;
        game1.frameRateTarget = 60.0;
        game1.controllerSupport = "Full";
        game1.moddingCommunity = true;
        game1.activePlayerBase = 450000;
        game1.updateFrequency = "Major Patches";
        game1.cloudSave = true;
        game1.microtransactionRevenue = 250000000.00;
        game1.competitiveScene = "None";
        game1.vrCompatible = false;
        game1.peakConcurrentPlayers = "1.2M";
        
        System.out.println("Game ID: " + game1.gameId);
        System.out.println("Game Title: " + game1.gameTitle);
        System.out.println("Game Genre: " + game1.gameGenre);
        System.out.println("Multiplayer Support: " + game1.multiplayerSupport);
        System.out.println("Release Platform: " + game1.releasePlatform);
        System.out.println("Player Count Peak: " + game1.playerCountPeak);
        System.out.println("Game Engine: " + game1.gameEngine);
        System.out.println("Ray Tracing: " + game1.rayTracing);
        System.out.println("Game Score Metacritic: " + game1.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game1.esrbRating);
        System.out.println("Battle Royale: " + game1.battleRoyale);
        System.out.println("Download Size: " + game1.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game1.leadDeveloper);
        System.out.println("Cross Platform: " + game1.crossPlatform);
        System.out.println("Esports Prize Pool: $" + game1.esportsPrizePool);
        System.out.println("Game Mode: " + game1.gameMode);
        System.out.println("DLC Available: " + game1.dlcAvailable);
        System.out.println("Frame Rate Target: " + game1.frameRateTarget + "fps");
        System.out.println("Controller Support: " + game1.controllerSupport);
        System.out.println("Modding Community: " + game1.moddingCommunity);
        System.out.println("Active Player Base: " + game1.activePlayerBase);
        System.out.println("Update Frequency: " + game1.updateFrequency);
        System.out.println("Cloud Save: " + game1.cloudSave);
        System.out.println("Microtransaction Revenue: $" + game1.microtransactionRevenue);
        System.out.println("Competitive Scene: " + game1.competitiveScene);
        System.out.println("VR Compatible: " + game1.vrCompatible);
        System.out.println("Peak Concurrent Players: " + game1.peakConcurrentPlayers);
        System.out.println("-----------------------------");
		
		
        VideoGames game2 = new VideoGames();
        game2.gameId = 1002;
        game2.gameTitle = "Call of Duty: Black Ops 7";
        game2.gameGenre = "FPS / Battle Royale";
        game2.multiplayerSupport = true;
        game2.releasePlatform = "PC/PS5/Xbox Series";
        game2.playerCountPeak = 35000000;
        game2.gameEngine = "IW 9.0";
        game2.rayTracing = true;
        game2.gameScoreMetacritic = 84.0;
        game2.esrbRating = "Mature 17+";
        game2.battleRoyale = true;
        game2.downloadSizeGB = 145;
        game2.leadDeveloper = "Treyarch";
        game2.crossPlatform = true;
        game2.esportsPrizePool = 85000000;
        game2.gameMode = "Multiplayer/Warzone";
        game2.dlcAvailable = true;
        game2.frameRateTarget = 120.0;
        game2.controllerSupport = "Full";
        game2.moddingCommunity = false;
        game2.activePlayerBase = 2800000;
        game2.updateFrequency = "Weekly Seasons";
        game2.cloudSave = true;
        game2.microtransactionRevenue = 1200000000.00;
        game2.competitiveScene = "Major Leagues";
        game2.vrCompatible = false;
        game2.peakConcurrentPlayers = "8.5M";
        
        System.out.println("Game ID: " + game2.gameId);
        System.out.println("Game Title: " + game2.gameTitle);
        System.out.println("Game Genre: " + game2.gameGenre);
        System.out.println("Multiplayer Support: " + game2.multiplayerSupport);
        System.out.println("Release Platform: " + game2.releasePlatform);
        System.out.println("Player Count Peak: " + game2.playerCountPeak);
        System.out.println("Game Engine: " + game2.gameEngine);
        System.out.println("Ray Tracing: " + game2.rayTracing);
        System.out.println("Game Score Metacritic: " + game2.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game2.esrbRating);
        System.out.println("Battle Royale: " + game2.battleRoyale);
        System.out.println("Download Size: " + game2.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game2.leadDeveloper);
        System.out.println("Cross Platform: " + game2.crossPlatform);
        System.out.println("Esports Prize Pool: $" + game2.esportsPrizePool);
        System.out.println("Game Mode: " + game2.gameMode);
        System.out.println("DLC Available: " + game2.dlcAvailable);
        System.out.println("Frame Rate Target: " + game2.frameRateTarget + "fps");
        System.out.println("Controller Support: " + game2.controllerSupport);
        System.out.println("Modding Community: " + game2.moddingCommunity);
        System.out.println("Active Player Base: " + game2.activePlayerBase);
        System.out.println("Update Frequency: " + game2.updateFrequency);
        System.out.println("Cloud Save: " + game2.cloudSave);
        System.out.println("Microtransaction Revenue: $" + game2.microtransactionRevenue);
        System.out.println("Competitive Scene: " + game2.competitiveScene);
        System.out.println("VR Compatible: " + game2.vrCompatible);
        System.out.println("Peak Concurrent Players: " + game2.peakConcurrentPlayers);
        System.out.println("-----------------------------");

        VideoGames game3 = new VideoGames();
        game3.gameId = 1003;
        game3.gameTitle = "NBA 2K26";
        game3.gameGenre = "Sports Simulation";
        game3.multiplayerSupport = true;
        game3.releasePlatform = "PC/PS5/Xbox Series";
        game3.playerCountPeak = 18000000;
        game3.gameEngine = "2K Engine";
        game3.rayTracing = true;
        game3.gameScoreMetacritic = 89.0;
        game3.esrbRating = "Everyone";
        game3.battleRoyale = false;
        game3.downloadSizeGB = 95;
        game3.leadDeveloper = "Visual Concepts";
        game3.crossPlatform = true;
        game3.esportsPrizePool = 25000000;
        game3.gameMode = "MyCareer/MyTeam";
        game3.dlcAvailable = true;
        game3.frameRateTarget = 60.0;
        game3.controllerSupport = "Full";
        game3.moddingCommunity = true;
        game3.activePlayerBase = 1200000;
        game3.updateFrequency = "Weekly Roster";
        game3.cloudSave = true;
        game3.microtransactionRevenue = 850000000.00;
        game3.competitiveScene = "2K League";
        game3.vrCompatible = false;
        game3.peakConcurrentPlayers = "2.1M";
        
        System.out.println("Game ID: " + game3.gameId);
        System.out.println("Game Title: " + game3.gameTitle);
        System.out.println("Game Genre: " + game3.gameGenre);
        System.out.println("Multiplayer Support: " + game3.multiplayerSupport);
        System.out.println("Release Platform: " + game3.releasePlatform);
        System.out.println("Player Count Peak: " + game3.playerCountPeak);
        System.out.println("Game Engine: " + game3.gameEngine);
        System.out.println("Ray Tracing: " + game3.rayTracing);
        System.out.println("Game Score Metacritic: " + game3.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game3.esrbRating);
        System.out.println("Battle Royale: " + game3.battleRoyale);
        System.out.println("Download Size: " + game3.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game3.leadDeveloper);
        System.out.println("Cross Platform: " + game3.crossPlatform);
        System.out.println("Esports Prize Pool: $" + game3.esportsPrizePool);
        System.out.println("Game Mode: " + game3.gameMode);
        System.out.println("DLC Available: " + game3.dlcAvailable);
        System.out.println("Frame Rate Target: " + game3.frameRateTarget + "fps");
        System.out.println("Controller Support: " + game3.controllerSupport);
        System.out.println("Modding Community: " + game3.moddingCommunity);
        System.out.println("Active Player Base: " + game3.activePlayerBase);
        System.out.println("Update Frequency: " + game3.updateFrequency);
        System.out.println("Cloud Save: " + game3.cloudSave);
        System.out.println("Microtransaction Revenue: $" + game3.microtransactionRevenue);
        System.out.println("Competitive Scene: " + game3.competitiveScene);
        System.out.println("VR Compatible: " + game3.vrCompatible);
        System.out.println("Peak Concurrent Players: " + game3.peakConcurrentPlayers);
        System.out.println("-----------------------------");

        VideoGames game4 = new VideoGames();
        game4.gameId = 1004;
        game4.gameTitle = "Minecraft";
        game4.gameGenre = "Sandbox Survival";
        game4.multiplayerSupport = true;
        game4.releasePlatform = "All Platforms";
        game4.playerCountPeak = 300000000;
        game4.gameEngine = "Java Edition";
        game4.rayTracing = true;
        game4.gameScoreMetacritic = 93.0;
        game4.esrbRating = "Everyone 10+";
        game4.battleRoyale = false;
        game4.downloadSizeGB = 4;
        game4.leadDeveloper = "Mojang Studios";
        game4.crossPlatform = true;
        game4.esportsPrizePool = 5000000;
        game4.gameMode = "Creative/Survival";
        game4.dlcAvailable = true;
        game4.frameRateTarget = 60.0;
        game4.controllerSupport = "Full";
        game4.moddingCommunity = true;
        game4.activePlayerBase = 140000000;
        game4.updateFrequency = "Major Updates";
        game4.cloudSave = true;
        game4.microtransactionRevenue = 4500000000.00;
        game4.competitiveScene = "Speedrunning";
        game4.vrCompatible = true;
        game4.peakConcurrentPlayers = "1.5M";
        
        System.out.println("Game ID: " + game4.gameId);
        System.out.println("Game Title: " + game4.gameTitle);
        System.out.println("Game Genre: " + game4.gameGenre);
        System.out.println("Multiplayer Support: " + game4.multiplayerSupport);
        System.out.println("Release Platform: " + game4.releasePlatform);
        System.out.println("Player Count Peak: " + game4.playerCountPeak);
        System.out.println("Game Engine: " + game4.gameEngine);
        System.out.println("Ray Tracing: " + game4.rayTracing);
        System.out.println("Game Score Metacritic: " + game4.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game4.esrbRating);
        System.out.println("Battle Royale: " + game4.battleRoyale);
        System.out.println("Download Size: " + game4.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game4.leadDeveloper);
        System.out.println("Cross Platform: " + game4.crossPlatform);
        System.out.println("Esports Prize Pool: $" + game4.esportsPrizePool);
        System.out.println("Game Mode: " + game4.gameMode);
        System.out.println("DLC Available: " + game4.dlcAvailable);
        System.out.println("Frame Rate Target: " + game4.frameRateTarget + "fps");
        System.out.println("Controller Support: " + game4.controllerSupport);
        System.out.println("Modding Community: " + game4.moddingCommunity);
        System.out.println("Active Player Base: " + game4.activePlayerBase);
        System.out.println("Update Frequency: " + game4.updateFrequency);
        System.out.println("Cloud Save: " + game4.cloudSave);
        System.out.println("Microtransaction Revenue: $" + game4.microtransactionRevenue);
        System.out.println("Competitive Scene: " + game4.competitiveScene);
        System.out.println("VR Compatible: " + game4.vrCompatible);
        System.out.println("Peak Concurrent Players: " + game4.peakConcurrentPlayers);
        System.out.println("-----------------------------");

        VideoGames game5 = new VideoGames();
        game5.gameId = 1005;
        game5.gameTitle = "Madden NFL 26";
        game5.gameGenre = "Sports Simulation";
        game5.multiplayerSupport = true;
        game5.releasePlatform = "PC/PS5/Xbox Series";
        game5.playerCountPeak = 22000000;
        game5.gameEngine = "Frostbite";
        game5.rayTracing = true;
        game5.gameScoreMetacritic = 88.0;
        
        System.out.println("Game ID: " + game5.gameId);
        System.out.println("Game Title: " + game5.gameTitle);
        System.out.println("Game Genre: " + game5.gameGenre);
        System.out.println("Multiplayer Support: " + game5.multiplayerSupport);
        System.out.println("Release Platform: " + game5.releasePlatform);
        System.out.println("Player Count Peak: " + game5.playerCountPeak);
        System.out.println("Game Engine: " + game5.gameEngine);
        System.out.println("Ray Tracing: " + game5.rayTracing);
        System.out.println("Game Score Metacritic: " + game5.gameScoreMetacritic);
        System.out.println("ESRB Rating: Everyone");
        System.out.println("-----------------------------");

        VideoGames game6 = new VideoGames();
        game6.gameId = 1006;
        game6.gameTitle = "Battlefield 6";
        game6.gameGenre = "FPS Multiplayer";
        game6.multiplayerSupport = true;
        game6.releasePlatform = "PC/PS5/Xbox Series";
        game6.playerCountPeak = 28000000;
        game6.gameEngine = "Frostbite";
        game6.rayTracing = true;
        game6.gameScoreMetacritic = 85.0;
        
        System.out.println("Game ID: " + game6.gameId);
        System.out.println("Game Title: " + game6.gameTitle);
        System.out.println("Game Genre: " + game6.gameGenre);
        System.out.println("Multiplayer Support: " + game6.multiplayerSupport);
        System.out.println("Release Platform: " + game6.releasePlatform);
        System.out.println("Player Count Peak: " + game6.playerCountPeak);
        System.out.println("Game Engine: " + game6.gameEngine);
        System.out.println("Ray Tracing: " + game6.rayTracing);
        System.out.println("Game Score Metacritic: " + game6.gameScoreMetacritic);
        System.out.println("Download Size: 180GB");
        System.out.println("-----------------------------");

        VideoGames game7 = new VideoGames();
        game7.gameId = 1007;
        game7.gameTitle = "EA Sports FC 26";
        game7.gameGenre = "Sports Simulation";
        game7.multiplayerSupport = true;
        game7.releasePlatform = "PC/PS5/Xbox Series";
        game7.playerCountPeak = 32000000;
        game7.gameEngine = "Frostbite";
        game7.rayTracing = true;
        game7.gameScoreMetacritic = 87.0;
        
        System.out.println("Game ID: " + game7.gameId);
        System.out.println("Game Title: " + game7.gameTitle);
        System.out.println("Game Genre: " + game7.gameGenre);
        System.out.println("Multiplayer Support: " + game7.multiplayerSupport);
        System.out.println("Release Platform: " + game7.releasePlatform);
        System.out.println("Player Count Peak: " + game7.playerCountPeak);
        System.out.println("Game Engine: " + game7.gameEngine);
        System.out.println("Ray Tracing: " + game7.rayTracing);
        System.out.println("Game Score Metacritic: " + game7.gameScoreMetacritic);
        System.out.println("Esports Prize Pool: $45M");
        System.out.println("-----------------------------");

        VideoGames game8 = new VideoGames();
        game8.gameId = 1008;
        game8.gameTitle = "Roblox";
        game8.gameGenre = "User Generated Platform";
        game8.multiplayerSupport = true;
        game8.releasePlatform = "All Platforms";
        game8.playerCountPeak = 900000000;
        game8.gameEngine = "Lua Engine";
        game8.rayTracing = false;
        game8.gameScoreMetacritic = 85.0;
        
        System.out.println("Game ID: " + game8.gameId);
        System.out.println("Game Title: " + game8.gameTitle);
        System.out.println("Game Genre: " + game8.gameGenre);
        System.out.println("Multiplayer Support: " + game8.multiplayerSupport);
        System.out.println("Release Platform: " + game8.releasePlatform);
        System.out.println("Player Count Peak: " + game8.playerCountPeak);
        System.out.println("Game Engine: " + game8.gameEngine);
        System.out.println("Ray Tracing: " + game8.rayTracing);
        System.out.println("Game Score Metacritic: " + game8.gameScoreMetacritic);
        System.out.println("Monthly Active Users: 129M");
        System.out.println("-----------------------------");

		
        VideoGames game9 = new VideoGames();
        game9.gameId = 1009;
        game9.gameTitle = "GTA VI";
        game9.gameGenre = "Open World Action";
        game9.multiplayerSupport = true;
        game9.releasePlatform = "PC/PS5/Xbox Series";
        game9.playerCountPeak = 95000000;
        game9.gameEngine = "RAGE Engine";
        game9.rayTracing = true;
        game9.gameScoreMetacritic = 96.0;
        game9.esrbRating = "Mature 17+";
        game9.battleRoyale = false;
        game9.downloadSizeGB = 220;
        game9.leadDeveloper = "Rockstar North";
        
        System.out.println("Game ID: " + game9.gameId);
        System.out.println("Game Title: " + game9.gameTitle);
        System.out.println("Game Genre: " + game9.gameGenre);
        System.out.println("Multiplayer Support: " + game9.multiplayerSupport);
        System.out.println("Release Platform: " + game9.releasePlatform);
        System.out.println("Player Count Peak: " + game9.playerCountPeak);
        System.out.println("Game Engine: " + game9.gameEngine);
        System.out.println("Ray Tracing: " + game9.rayTracing);
        System.out.println("Game Score Metacritic: " + game9.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game9.esrbRating);
        System.out.println("Battle Royale: " + game9.battleRoyale);
        System.out.println("Download Size: " + game9.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game9.leadDeveloper);
        System.out.println("Cross Platform: true");
        System.out.println("-----------------------------");

        VideoGames game10 = new VideoGames();
        game10.gameId = 1010;
        game10.gameTitle = "Fortnite Chapter 6";
        game10.gameGenre = "Battle Royale";
        game10.multiplayerSupport = true;
        game10.releasePlatform = "All Platforms";
        game10.playerCountPeak = 650000000;
        game10.gameEngine = "Unreal Engine 5";
        game10.rayTracing = true;
        game10.gameScoreMetacritic = 84.0;
        game10.esrbRating = "Teen";
        game10.battleRoyale = true;
        game10.downloadSizeGB = 90;
        game10.leadDeveloper = "Epic Games";
        
        System.out.println("Game ID: " + game10.gameId);
        System.out.println("Game Title: " + game10.gameTitle);
        System.out.println("Game Genre: " + game10.gameGenre);
        System.out.println("Multiplayer Support: " + game10.multiplayerSupport);
        System.out.println("Release Platform: " + game10.releasePlatform);
        System.out.println("Player Count Peak: " + game10.playerCountPeak);
        System.out.println("Game Engine: " + game10.gameEngine);
        System.out.println("Ray Tracing: " + game10.rayTracing);
        System.out.println("Game Score Metacritic: " + game10.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game10.esrbRating);
        System.out.println("Battle Royale: " + game10.battleRoyale);
        System.out.println("Download Size: " + game10.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game10.leadDeveloper);
        System.out.println("Esports Prize Pool: $200M");
        System.out.println("-----------------------------");

        VideoGames game11 = new VideoGames();
        game11.gameId = 1011;
        game11.gameTitle = "Elden Ring 2";
        game11.gameGenre = "Action RPG";
        game11.multiplayerSupport = true;
        game11.releasePlatform = "PC/PS5/Xbox Series";
        game11.playerCountPeak = 25000000;
        game11.gameEngine = "FromSoftware Engine";
        game11.rayTracing = true;
        game11.gameScoreMetacritic = 94.0;
        game11.esrbRating = "Mature 17+";
        game11.battleRoyale = false;
        game11.downloadSizeGB = 65;
        game11.leadDeveloper = "FromSoftware";
        
        System.out.println("Game ID: " + game11.gameId);
        System.out.println("Game Title: " + game11.gameTitle);
        System.out.println("Game Genre: " + game11.gameGenre);
        System.out.println("Multiplayer Support: " + game11.multiplayerSupport);
        System.out.println("Release Platform: " + game11.releasePlatform);
        System.out.println("Player Count Peak: " + game11.playerCountPeak);
        System.out.println("Game Engine: " + game11.gameEngine);
        System.out.println("Ray Tracing: " + game11.rayTracing);
        System.out.println("Game Score Metacritic: " + game11.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game11.esrbRating);
        System.out.println("Battle Royale: " + game11.battleRoyale);
        System.out.println("Download Size: " + game11.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game11.leadDeveloper);
        System.out.println("Active Player Base: 1.2M");
        System.out.println("-----------------------------");

        VideoGames game12 = new VideoGames();
        game12.gameId = 1012;
        game12.gameTitle = "Call of Duty: Black Ops 6";
        game12.gameGenre = "FPS Multiplayer";
        game12.multiplayerSupport = true;
        game12.releasePlatform = "PC/PS5/Xbox Series";
        game12.playerCountPeak = 125000000;
        game12.gameEngine = "IW Engine 9.0";
        game12.rayTracing = true;
        game12.gameScoreMetacritic = 83.0;
        game12.esrbRating = "Mature 17+";
        game12.battleRoyale = true;
        game12.downloadSizeGB = 150;
        game12.leadDeveloper = "Treyarch";
        
        System.out.println("Game ID: " + game12.gameId);
        System.out.println("Game Title: " + game12.gameTitle);
        System.out.println("Game Genre: " + game12.gameGenre);
        System.out.println("Multiplayer Support: " + game12.multiplayerSupport);
        System.out.println("Release Platform: " + game12.releasePlatform);
        System.out.println("Player Count Peak: " + game12.playerCountPeak);
        System.out.println("Game Engine: " + game12.gameEngine);
        System.out.println("Ray Tracing: " + game12.rayTracing);
        System.out.println("Game Score Metacritic: " + game12.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game12.esrbRating);
        System.out.println("Battle Royale: " + game12.battleRoyale);
        System.out.println("Download Size: " + game12.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game12.leadDeveloper);
        System.out.println("Esports Prize Pool: $35M");
        System.out.println("-----------------------------");

        VideoGames game13 = new VideoGames();
        game13.gameId = 1013;
        game13.gameTitle = "Star Wars Outlaws";
        game13.gameGenre = "Open World Action";
        game13.multiplayerSupport = false;
        game13.releasePlatform = "PC/PS5/Xbox Series";
        game13.playerCountPeak = 18000000;
        game13.gameEngine = "Snowdrop Engine";
        game13.rayTracing = true;
        game13.gameScoreMetacritic = 82.0;
        game13.esrbRating = "Teen";
        game13.battleRoyale = false;
        game13.downloadSizeGB = 95;
        game13.leadDeveloper = "Massive Entertainment";
        
        System.out.println("Game ID: " + game13.gameId);
        System.out.println("Game Title: " + game13.gameTitle);
        System.out.println("Game Genre: " + game13.gameGenre);
        System.out.println("Multiplayer Support: " + game13.multiplayerSupport);
        System.out.println("Release Platform: " + game13.releasePlatform);
        System.out.println("Player Count Peak: " + game13.playerCountPeak);
        System.out.println("Game Engine: " + game13.gameEngine);
        System.out.println("Ray Tracing: " + game13.rayTracing);
        System.out.println("Game Score Metacritic: " + game13.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game13.esrbRating);
        System.out.println("Battle Royale: " + game13.battleRoyale);
        System.out.println("Download Size: " + game13.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game13.leadDeveloper);
        System.out.println("Single Player Focus: true");
        System.out.println("-----------------------------");

        VideoGames game14 = new VideoGames();
        game14.gameId = 1014;
        game14.gameTitle = "Cyberpunk 2077: Phantom Liberty 2";
        game14.gameGenre = "Open World RPG";
        game14.multiplayerSupport = true;
        game14.releasePlatform = "PC/PS5/Xbox Series";
        game14.playerCountPeak = 45000000;
        game14.gameEngine = "RED Engine 5";
        game14.rayTracing = true;
        game14.gameScoreMetacritic = 92.0;
        game14.esrbRating = "Mature 17+";
        game14.battleRoyale = false;
        game14.downloadSizeGB = 120;
        game14.leadDeveloper = "CD Projekt RED";
        
        System.out.println("Game ID: " + game14.gameId);
        System.out.println("Game Title: " + game14.gameTitle);
        System.out.println("Game Genre: " + game14.gameGenre);
        System.out.println("Multiplayer Support: " + game14.multiplayerSupport);
        System.out.println("Release Platform: " + game14.releasePlatform);
        System.out.println("Player Count Peak: " + game14.playerCountPeak);
        System.out.println("Game Engine: " + game14.gameEngine);
        System.out.println("Ray Tracing: " + game14.rayTracing);
        System.out.println("Game Score Metacritic: " + game14.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game14.esrbRating);
        System.out.println("Battle Royale: " + game14.battleRoyale);
        System.out.println("Download Size: " + game14.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game14.leadDeveloper);
        System.out.println("Active Player Base: 2.1M");
        System.out.println("-----------------------------");


        VideoGames game15 = new VideoGames();
        game15.gameId = 1015;
        game15.gameTitle = "Marvel's Wolverine";
        game15.gameGenre = "Action Adventure";
        game15.multiplayerSupport = false;
        game15.releasePlatform = "PS5/PC";
        game15.playerCountPeak = 12000000;
        game15.gameEngine = "Insomniac Engine";
        game15.rayTracing = true;
        game15.gameScoreMetacritic = 93.0;
        game15.esrbRating = "Mature 17+";
        game15.battleRoyale = false;
        game15.downloadSizeGB = 75;
        game15.leadDeveloper = "Insomniac Games";
        
        System.out.println("Game ID: " + game15.gameId);
        System.out.println("Game Title: " + game15.gameTitle);
        System.out.println("Game Genre: " + game15.gameGenre);
        System.out.println("Multiplayer Support: " + game15.multiplayerSupport);
        System.out.println("Release Platform: " + game15.releasePlatform);
        System.out.println("Player Count Peak: " + game15.playerCountPeak);
        System.out.println("Game Engine: " + game15.gameEngine);
        System.out.println("Ray Tracing: " + game15.rayTracing);
        System.out.println("Game Score Metacritic: " + game15.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game15.esrbRating);
        System.out.println("Battle Royale: " + game15.battleRoyale);
        System.out.println("Download Size: " + game15.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game15.leadDeveloper);
        System.out.println("Single Player Focus: true");
        System.out.println("-----------------------------");

        VideoGames game16 = new VideoGames();
        game16.gameId = 1016;
        game16.gameTitle = "Death Stranding 2: On the Beach";
        game16.gameGenre = "Action Adventure";
        game16.multiplayerSupport = true;
        game16.releasePlatform = "PS5/PC";
        game16.playerCountPeak = 8500000;
        game16.gameEngine = "Decima Engine";
        game16.rayTracing = true;
        game16.gameScoreMetacritic = 91.0;
        game16.esrbRating = "Mature 17+";
        game16.battleRoyale = false;
        game16.downloadSizeGB = 110;
        game16.leadDeveloper = "Kojima Productions";
        
        System.out.println("Game ID: " + game16.gameId);
        System.out.println("Game Title: " + game16.gameTitle);
        System.out.println("Game Genre: " + game16.gameGenre);
        System.out.println("Multiplayer Support: " + game16.multiplayerSupport);
        System.out.println("Release Platform: " + game16.releasePlatform);
        System.out.println("Player Count Peak: " + game16.playerCountPeak);
        System.out.println("Game Engine: " + game16.gameEngine);
        System.out.println("Ray Tracing: " + game16.rayTracing);
        System.out.println("Game Score Metacritic: " + game16.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game16.esrbRating);
        System.out.println("Battle Royale: " + game16.battleRoyale);
        System.out.println("Download Size: " + game16.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game16.leadDeveloper);
        System.out.println("Kojima Vision: Cinematic");
        System.out.println("-----------------------------");

        VideoGames game17 = new VideoGames();
        game17.gameId = 1017;
        game17.gameTitle = "Crimson Desert";
        game17.gameGenre = "Open World Action RPG";
        game17.multiplayerSupport = true;
        game17.releasePlatform = "PC/PS5/Xbox Series";
        game17.playerCountPeak = 22000000;
        game17.gameEngine = "Pearl Abyss Engine";
        game17.rayTracing = true;
        game17.gameScoreMetacritic = 89.0;
        game17.esrbRating = "Mature 17+";
        game17.battleRoyale = false;
        game17.downloadSizeGB = 130;
        game17.leadDeveloper = "Pearl Abyss";
        
        System.out.println("Game ID: " + game17.gameId);
        System.out.println("Game Title: " + game17.gameTitle);
        System.out.println("Game Genre: " + game17.gameGenre);
        System.out.println("Multiplayer Support: " + game17.multiplayerSupport);
        System.out.println("Release Platform: " + game17.releasePlatform);
        System.out.println("Player Count Peak: " + game17.playerCountPeak);
        System.out.println("Game Engine: " + game17.gameEngine);
        System.out.println("Ray Tracing: " + game17.rayTracing);
        System.out.println("Game Score Metacritic: " + game17.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game17.esrbRating);
        System.out.println("Battle Royale: " + game17.battleRoyale);
        System.out.println("Download Size: " + game17.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game17.leadDeveloper);
        System.out.println("March 2026 Release");
        System.out.println("-----------------------------");

		
        VideoGames game18 = new VideoGames();
        game18.gameId = 1018;
        game18.gameTitle = "Assassin's Creed Shadows";
        game18.gameGenre = "Open World Stealth";
        game18.multiplayerSupport = true;
        game18.releasePlatform = "PC/PS5/Xbox Series";
        game18.playerCountPeak = 35000000;
        game18.gameEngine = "AnvilNext 2.0";
        game18.rayTracing = true;
        game18.gameScoreMetacritic = 90.0;
        game18.esrbRating = "Mature 17+";
        game18.battleRoyale = false;
        game18.downloadSizeGB = 140;
        game18.leadDeveloper = "Ubisoft Quebec";
        
        System.out.println("Game ID: " + game18.gameId);
        System.out.println("Game Title: " + game18.gameTitle);
        System.out.println("Game Genre: " + game18.gameGenre);
        System.out.println("Multiplayer Support: " + game18.multiplayerSupport);
        System.out.println("Release Platform: " + game18.releasePlatform);
        System.out.println("Player Count Peak: " + game18.playerCountPeak);
        System.out.println("Game Engine: " + game18.gameEngine);
        System.out.println("Ray Tracing: " + game18.rayTracing);
        System.out.println("Game Score Metacritic: " + game18.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game18.esrbRating);
        System.out.println("Battle Royale: " + game18.battleRoyale);
        System.out.println("Download Size: " + game18.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game18.leadDeveloper);
        System.out.println("Feudal Japan Setting");
        System.out.println("-----------------------------");

        VideoGames game19 = new VideoGames();
        game19.gameId = 1019;
        game19.gameTitle = "Fable";
        game19.gameGenre = "Action RPG";
        game19.multiplayerSupport = true;
        game19.releasePlatform = "PC/Xbox Series";
        game19.playerCountPeak = 15000000;
        game19.gameEngine = "ForzaTech";
        game19.rayTracing = true;
        game19.gameScoreMetacritic = 88.0;
        game19.esrbRating = "Mature 17+";
        game19.battleRoyale = false;
        game19.downloadSizeGB = 80;
        game19.leadDeveloper = "Playground Games";
        
        System.out.println("Game ID: " + game19.gameId);
        System.out.println("Game Title: " + game19.gameTitle);
        System.out.println("Game Genre: " + game19.gameGenre);
        System.out.println("Multiplayer Support: " + game19.multiplayerSupport);
        System.out.println("Release Platform: " + game19.releasePlatform);
        System.out.println("Player Count Peak: " + game19.playerCountPeak);
        System.out.println("Game Engine: " + game19.gameEngine);
        System.out.println("Ray Tracing: " + game19.rayTracing);
        System.out.println("Game Score Metacritic: " + game19.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game19.esrbRating);
        System.out.println("Battle Royale: " + game19.battleRoyale);
        System.out.println("Download Size: " + game19.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game19.leadDeveloper);
        System.out.println("Xbox Exclusive Launch");
        System.out.println("-----------------------------");

        VideoGames game20 = new VideoGames();
        game20.gameId = 1020;
        game20.gameTitle = "Kingdom Come: Deliverance 2";
        game20.gameGenre = "Realistic RPG";
        game20.multiplayerSupport = false;
        game20.releasePlatform = "PC/PS5/Xbox Series";
        game20.playerCountPeak = 8000000;
        game20.gameEngine = "CryEngine";
        game20.rayTracing = true;
        game20.gameScoreMetacritic = 92.0;
        game20.esrbRating = "Mature 17+";
        game20.battleRoyale = false;
        game20.downloadSizeGB = 100;
        game20.leadDeveloper = "Warhorse Studios";
        
        System.out.println("Game ID: " + game20.gameId);
        System.out.println("Game Title: " + game20.gameTitle);
        System.out.println("Game Genre: " + game20.gameGenre);
        System.out.println("Multiplayer Support: " + game20.multiplayerSupport);
        System.out.println("Release Platform: " + game20.releasePlatform);
        System.out.println("Player Count Peak: " + game20.playerCountPeak);
        System.out.println("Game Engine: " + game20.gameEngine);
        System.out.println("Ray Tracing: " + game20.rayTracing);
        System.out.println("Game Score Metacritic: " + game20.gameScoreMetacritic);
        System.out.println("ESRB Rating: " + game20.esrbRating);
        System.out.println("Battle Royale: " + game20.battleRoyale);
        System.out.println("Download Size: " + game20.downloadSizeGB + "GB");
        System.out.println("Lead Developer: " + game20.leadDeveloper);
        System.out.println("Medieval Realism Focus");
        System.out.println("-----------------------------");

		
		
		
    }
}
