class WaterfallsExecutor {
    public static void main(String[] args) {

        Waterfalls waterfall1 = new Waterfalls();
        
        waterfall1.cascadeId = 1001;
        waterfall1.cascadeName = "Jog Falls";
        waterfall1.district = "Shivamogga";
        waterfall1.protectedStatus = true;
        waterfall1.firstRecorded = "05/03/1850";
        waterfall1.recentAssessment = "05/03/2026";
        waterfall1.assessmentPending = false;
        waterfall1.cascadePattern = "Four-Tier Plunge";
        waterfall1.tributarySource = "Sharavati River";
        waterfall1.dropHeight = 253.0;
        waterfall1.plungePoolDepth = "Deep Scoured";
        waterfall1.therapeuticSprings = true;
        waterfall1.peakSeasonVisitors = 1250000;
        waterfall1.geologyFormation = "Basalt Columns";
        waterfall1.endemicAmphibians = true;
        waterfall1.geologicalAge = 65;
        waterfall1.ecoTourismRevenue = 28500000.00;
        waterfall1.rainfallZone = "Western Ghats";
        waterfall1.perennialFlow = true;
        waterfall1.accessDifficulty = "Medium Trek";
        waterfall1.crestWidth = 460;
        waterfall1.erosionResistant = true;
        waterfall1.biodiversityIndex = "Very High";
        waterfall1.droneSurveyed = true;
        waterfall1.conservationZone = "Shivamogga Division";
        waterfall1.annualPreservation = 1250000.00;
        waterfall1.rescueHelpline = "08281-234567";
        
        System.out.println("Cascade ID: " + waterfall1.cascadeId);
        System.out.println("Cascade Name: " + waterfall1.cascadeName);
        System.out.println("District: " + waterfall1.district);
        System.out.println("Protected Status: " + waterfall1.protectedStatus);
        System.out.println("First Recorded: " + waterfall1.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall1.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall1.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall1.cascadePattern);
        System.out.println("Tributary Source: " + waterfall1.tributarySource);
        System.out.println("Drop Height: " + waterfall1.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall1.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall1.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall1.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall1.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall1.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall1.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall1.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall1.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall1.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall1.accessDifficulty);
        System.out.println("Crest Width: " + waterfall1.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall1.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall1.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall1.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall1.conservationZone);
        System.out.println("Annual Preservation: " + waterfall1.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall1.rescueHelpline);
        System.out.println("-----------------------------");
		
        Waterfalls waterfall2 = new Waterfalls();
        waterfall2.cascadeId = 1002;
        waterfall2.cascadeName = "Abbey Falls";
        waterfall2.district = "Kodagu";
        waterfall2.protectedStatus = true;
        waterfall2.firstRecorded = "05/03/1920";
        waterfall2.recentAssessment = "05/03/2026";
        waterfall2.assessmentPending = false;
        waterfall2.cascadePattern = "Segmented Plunge";
        waterfall2.tributarySource = "Cauvery River";
        waterfall2.dropHeight = 70.0;
        waterfall2.plungePoolDepth = "Shallow Rocky";
        waterfall2.therapeuticSprings = true;
        waterfall2.peakSeasonVisitors = 850000;
        waterfall2.geologyFormation = "Granite Slabs";
        waterfall2.endemicAmphibians = true;
        waterfall2.geologicalAge = 45;
        waterfall2.ecoTourismRevenue = 18500000.00;
        waterfall2.rainfallZone = "Coorg Hills";
        waterfall2.perennialFlow = true;
        waterfall2.accessDifficulty = "Easy Walkway";
        waterfall2.crestWidth = 120;
        waterfall2.erosionResistant = true;
        waterfall2.biodiversityIndex = "High";
        waterfall2.droneSurveyed = true;
        waterfall2.conservationZone = "Madikeri Division";
        waterfall2.annualPreservation = 850000.00;
        waterfall2.rescueHelpline = "08272-225567";
        
        System.out.println("Cascade ID: " + waterfall2.cascadeId);
        System.out.println("Cascade Name: " + waterfall2.cascadeName);
        System.out.println("District: " + waterfall2.district);
        System.out.println("Protected Status: " + waterfall2.protectedStatus);
        System.out.println("First Recorded: " + waterfall2.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall2.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall2.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall2.cascadePattern);
        System.out.println("Tributary Source: " + waterfall2.tributarySource);
        System.out.println("Drop Height: " + waterfall2.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall2.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall2.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall2.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall2.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall2.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall2.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall2.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall2.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall2.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall2.accessDifficulty);
        System.out.println("Crest Width: " + waterfall2.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall2.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall2.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall2.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall2.conservationZone);
        System.out.println("Annual Preservation: " + waterfall2.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall2.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall3 = new Waterfalls();
        waterfall3.cascadeId = 1003;
        waterfall3.cascadeName = "Shivanasamudra Falls";
        waterfall3.district = "Chamarajanagar";
        waterfall3.protectedStatus = true;
        waterfall3.firstRecorded = "05/03/1810";
        waterfall3.recentAssessment = "05/03/2026";
        waterfall3.assessmentPending = true;
        waterfall3.cascadePattern = "Twin Tier Block";
        waterfall3.tributarySource = "Cauvery River";
        waterfall3.dropHeight = 98.0;
        waterfall3.plungePoolDepth = "Deep Turbulent";
        waterfall3.therapeuticSprings = false;
        waterfall3.peakSeasonVisitors = 650000;
        waterfall3.geologyFormation = "Gneiss Deccan";
        waterfall3.endemicAmphibians = false;
        waterfall3.geologicalAge = 75;
        waterfall3.ecoTourismRevenue = 14200000.00;
        waterfall3.rainfallZone = "Cauvery Basin";
        waterfall3.perennialFlow = true;
        waterfall3.accessDifficulty = "Steep Steps";
        waterfall3.crestWidth = 360;
        waterfall3.erosionResistant = false;
        waterfall3.biodiversityIndex = "Medium";
        waterfall3.droneSurveyed = true;
        waterfall3.conservationZone = "Mandya Division";
        waterfall3.annualPreservation = 950000.00;
        waterfall3.rescueHelpline = "08234-567890";
        
        System.out.println("Cascade ID: " + waterfall3.cascadeId);
        System.out.println("Cascade Name: " + waterfall3.cascadeName);
        System.out.println("District: " + waterfall3.district);
        System.out.println("Protected Status: " + waterfall3.protectedStatus);
        System.out.println("First Recorded: " + waterfall3.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall3.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall3.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall3.cascadePattern);
        System.out.println("Tributary Source: " + waterfall3.tributarySource);
        System.out.println("Drop Height: " + waterfall3.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall3.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall3.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall3.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall3.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall3.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall3.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall3.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall3.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall3.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall3.accessDifficulty);
        System.out.println("Crest Width: " + waterfall3.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall3.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall3.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall3.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall3.conservationZone);
        System.out.println("Annual Preservation: " + waterfall3.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall3.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall4 = new Waterfalls();
        waterfall4.cascadeId = 1004;
        waterfall4.cascadeName = "Hebbe Falls";
        waterfall4.district = "Chikkamagaluru";
        waterfall4.protectedStatus = true;
        waterfall4.firstRecorded = "05/03/1945";
        waterfall4.recentAssessment = "05/03/2026";
        waterfall4.assessmentPending = false;
        waterfall4.cascadePattern = "Horsetail Sheet";
        waterfall4.tributarySource = "Bhadra River";
        waterfall4.dropHeight = 168.0;
        waterfall4.plungePoolDepth = "Medium Natural";
        waterfall4.therapeuticSprings = true;
        waterfall4.peakSeasonVisitors = 420000;
        waterfall4.geologyFormation = "Laterite Cliffs";
        waterfall4.endemicAmphibians = true;
        waterfall4.geologicalAge = 35;
        waterfall4.ecoTourismRevenue = 9800000.00;
        waterfall4.rainfallZone = "Mullayanagiri";
        waterfall4.perennialFlow = false;
        waterfall4.accessDifficulty = "Jeep + Trek";
        waterfall4.crestWidth = 85;
        waterfall4.erosionResistant = true;
        waterfall4.biodiversityIndex = "Very High";
        waterfall4.droneSurveyed = true;
        waterfall4.conservationZone = "Kemmanagundi Division";
        waterfall4.annualPreservation = 620000.00;
        waterfall4.rescueHelpline = "08262-789012";
        
        System.out.println("Cascade ID: " + waterfall4.cascadeId);
        System.out.println("Cascade Name: " + waterfall4.cascadeName);
        System.out.println("District: " + waterfall4.district);
        System.out.println("Protected Status: " + waterfall4.protectedStatus);
        System.out.println("First Recorded: " + waterfall4.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall4.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall4.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall4.cascadePattern);
        System.out.println("Tributary Source: " + waterfall4.tributarySource);
        System.out.println("Drop Height: " + waterfall4.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall4.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall4.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall4.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall4.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall4.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall4.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall4.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall4.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall4.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall4.accessDifficulty);
        System.out.println("Crest Width: " + waterfall4.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall4.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall4.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall4.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall4.conservationZone);
        System.out.println("Annual Preservation: " + waterfall4.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall4.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall5 = new Waterfalls();
        waterfall5.cascadeId = 1005;
        waterfall5.cascadeName = "Barkana Falls";
        waterfall5.district = "Shivamogga";
        waterfall5.protectedStatus = true;
        waterfall5.firstRecorded = "05/03/1935";
        waterfall5.recentAssessment = "05/03/2026";
        waterfall5.assessmentPending = false;
        waterfall5.cascadePattern = "Tiered Segmented";
        waterfall5.tributarySource = "Sita River";
        waterfall5.dropHeight = 260.0;
        waterfall5.plungePoolDepth = "Deep Forest Pool";
        waterfall5.therapeuticSprings = true;
        waterfall5.peakSeasonVisitors = 320000;
        waterfall5.geologyFormation = "Laterite Cascades";
        waterfall5.endemicAmphibians = true;
        waterfall5.geologicalAge = 28;
        waterfall5.ecoTourismRevenue = 7500000.00;
        waterfall5.rainfallZone = "Agumbe Ghat";
        waterfall5.perennialFlow = false;
        waterfall5.accessDifficulty = "Forest Trek";
        waterfall5.crestWidth = 95;
        waterfall5.erosionResistant = true;
        waterfall5.biodiversityIndex = "Extremely High";
        waterfall5.droneSurveyed = false;
        waterfall5.conservationZone = "Agumbe Division";
        waterfall5.annualPreservation = 480000.00;
        waterfall5.rescueHelpline = "08181-345678";
        
        System.out.println("Cascade ID: " + waterfall5.cascadeId);
        System.out.println("Cascade Name: " + waterfall5.cascadeName);
        System.out.println("District: " + waterfall5.district);
        System.out.println("Protected Status: " + waterfall5.protectedStatus);
        System.out.println("First Recorded: " + waterfall5.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall5.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall5.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall5.cascadePattern);
        System.out.println("Tributary Source: " + waterfall5.tributarySource);
        System.out.println("Drop Height: " + waterfall5.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall5.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall5.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall5.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall5.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall5.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall5.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall5.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall5.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall5.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall5.accessDifficulty);
        System.out.println("Crest Width: " + waterfall5.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall5.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall5.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall5.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall5.conservationZone);
        System.out.println("Annual Preservation: " + waterfall5.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall5.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall6 = new Waterfalls();
        waterfall6.cascadeId = 1006;
        waterfall6.cascadeName = "Irupu Falls";
        waterfall6.district = "Kodagu";
        waterfall6.protectedStatus = true;
        waterfall6.firstRecorded = "05/03/1890";
        waterfall6.recentAssessment = "05/03/2026";
        waterfall6.assessmentPending = false;
        waterfall6.cascadePattern = "Horsetail Cascade";
        waterfall6.tributarySource = "Lakshmana Tirtha";
        waterfall6.dropHeight = 52.0;
        waterfall6.plungePoolDepth = "Sacred Pool";
        waterfall6.therapeuticSprings = true;
        waterfall6.peakSeasonVisitors = 580000;
        waterfall6.geologyFormation = "Granite Plateau";
        waterfall6.endemicAmphibians = true;
        waterfall6.geologicalAge = 52;
        waterfall6.ecoTourismRevenue = 12800000.00;
        waterfall6.rainfallZone = "Brahmagiri Hills";
        waterfall6.perennialFlow = true;
        waterfall6.accessDifficulty = "Easy Forest Path";
        waterfall6.crestWidth = 170;
        waterfall6.erosionResistant = true;
        waterfall6.biodiversityIndex = "High";
        waterfall6.droneSurveyed = true;
        waterfall6.conservationZone = "Virajpet Division";
        waterfall6.annualPreservation = 720000.00;
        waterfall6.rescueHelpline = "08294-456789";
        
        System.out.println("Cascade ID: " + waterfall6.cascadeId);
        System.out.println("-----------------------------");

        Waterfalls waterfall7 = new Waterfalls();
        waterfall7.cascadeId = 1007;
        waterfall7.cascadeName = "Magod Falls";
        waterfall7.district = "Uttara Kannada";
        waterfall7.protectedStatus = true;
        waterfall7.firstRecorded = "05/03/1875";
        waterfall7.recentAssessment = "05/03/2026";
        waterfall7.assessmentPending = true;
        waterfall7.cascadePattern = "Double Tier Plunge";
        waterfall7.tributarySource = "Bedti River";
        waterfall7.dropHeight = 200.0;
        waterfall7.plungePoolDepth = "Twin Deep Pools";
        waterfall7.therapeuticSprings = false;
        waterfall7.peakSeasonVisitors = 380000;
        waterfall7.geologyFormation = "Basaltic Trap";
        waterfall7.endemicAmphibians = true;
        waterfall7.geologicalAge = 68;
        waterfall7.ecoTourismRevenue = 9200000.00;
        waterfall7.rainfallZone = "Western Ghats";
        waterfall7.perennialFlow = false;
        waterfall7.accessDifficulty = "Moderate Steps";
        waterfall7.crestWidth = 240;
        waterfall7.erosionResistant = false;
        waterfall7.biodiversityIndex = "Very High";
        waterfall7.droneSurveyed = true;
        waterfall7.conservationZone = "Yellapur Division";
        waterfall7.annualPreservation = 580000.00;
        waterfall7.rescueHelpline = "08386-678901";
        
        System.out.println("Cascade ID: " + waterfall7.cascadeId);
        System.out.println("-----------------------------");

        Waterfalls waterfall8 = new Waterfalls();
        waterfall8.cascadeId = 1008;
        waterfall8.cascadeName = "Unchalli Falls";
        waterfall8.district = "Uttara Kannada";
        waterfall8.protectedStatus = true;
        waterfall8.firstRecorded = "05/03/1885";
        waterfall8.recentAssessment = "05/03/2026";
        waterfall8.assessmentPending = false;
        waterfall8.cascadePattern = "U-Shaped Plunge";
        waterfall8.tributarySource = "Aghanashini River";
        waterfall8.dropHeight = 116.0;
        waterfall8.plungePoolDepth = "L-Shaped Deep";
        waterfall8.therapeuticSprings = true;
        waterfall8.peakSeasonVisitors = 280000;
        waterfall8.geologyFormation = "Laterite Gorges";
        waterfall8.endemicAmphibians = true;
        waterfall8.geologicalAge = 42;
        waterfall8.ecoTourismRevenue = 6800000.00;
        waterfall8.rainfallZone = "Siddapur Ghat";
        waterfall8.perennialFlow = false;
        waterfall8.accessDifficulty = "Steep Jungle Trek";
        waterfall8.crestWidth = 65;
        waterfall8.erosionResistant = true;
        waterfall8.biodiversityIndex = "Extremely High";
        waterfall8.droneSurveyed = false;
        waterfall8.conservationZone = "Siddapur Division";
        waterfall8.annualPreservation = 420000.00;
        waterfall8.rescueHelpline = "08387-234567";
        
        System.out.println("Cascade ID: " + waterfall8.cascadeId);
        System.out.println("Cascade Name: " + waterfall8.cascadeName);
        System.out.println("District: " + waterfall8.district);
        System.out.println("Protected Status: " + waterfall8.protectedStatus);
        System.out.println("First Recorded: " + waterfall8.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall8.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall8.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall8.cascadePattern);
        System.out.println("Tributary Source: " + waterfall8.tributarySource);
        System.out.println("Drop Height: " + waterfall8.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall8.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall8.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall8.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall8.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall8.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall8.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall8.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall8.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall8.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall8.accessDifficulty);
        System.out.println("Crest Width: " + waterfall8.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall8.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall8.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall8.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall8.conservationZone);
        System.out.println("Annual Preservation: " + waterfall8.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall8.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall9 = new Waterfalls();
        waterfall9.cascadeId = 1009;
        waterfall9.cascadeName = "Dabbe Falls";
        waterfall9.district = "Shivamogga";
        waterfall9.protectedStatus = true;
        waterfall9.firstRecorded = "05/03/1975";
        waterfall9.recentAssessment = "05/03/2026";
        waterfall9.assessmentPending = true;
        waterfall9.cascadePattern = "Fan-Shaped Plunge";
        waterfall9.tributarySource = "Hosagadde Stream";
        waterfall9.dropHeight = 70.0;
        waterfall9.plungePoolDepth = "Crystal Clear Pool";
        waterfall9.therapeuticSprings = true;
        waterfall9.peakSeasonVisitors = 150000;
        waterfall9.geologyFormation = "Granite Boulders";
        waterfall9.endemicAmphibians = true;
        waterfall9.geologicalAge = 38;
        waterfall9.ecoTourismRevenue = 4200000.00;
        waterfall9.rainfallZone = "Kargal Rainforest";
        waterfall9.perennialFlow = false;
        waterfall9.accessDifficulty = "Difficult Trek";
        waterfall9.crestWidth = 45;
        waterfall9.erosionResistant = true;
        waterfall9.biodiversityIndex = "Extremely High";
        waterfall9.droneSurveyed = false;
        waterfall9.conservationZone = "Kargal Division";
        waterfall9.annualPreservation = 350000.00;
        waterfall9.rescueHelpline = "08187-567890";
        
        System.out.println("Cascade ID: " + waterfall9.cascadeId);
        System.out.println("Cascade Name: " + waterfall9.cascadeName);
        System.out.println("District: " + waterfall9.district);
        System.out.println("Protected Status: " + waterfall9.protectedStatus);
        System.out.println("First Recorded: " + waterfall9.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall9.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall9.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall9.cascadePattern);
        System.out.println("Tributary Source: " + waterfall9.tributarySource);
        System.out.println("Drop Height: " + waterfall9.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall9.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall9.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall9.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall9.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall9.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall9.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall9.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall9.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall9.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall9.accessDifficulty);
        System.out.println("Crest Width: " + waterfall9.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall9.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall9.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall9.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall9.conservationZone);
        System.out.println("Annual Preservation: " + waterfall9.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall9.rescueHelpline);
        System.out.println("-----------------------------");


        Waterfalls waterfall10 = new Waterfalls();
        waterfall10.cascadeId = 1010;
        waterfall10.cascadeName = "Kudlu Falls";
        waterfall10.district = "Udupi";
        waterfall10.protectedStatus = true;
        waterfall10.firstRecorded = "05/03/1905";
        waterfall10.recentAssessment = "05/03/2026";
        waterfall10.assessmentPending = false;
        waterfall10.cascadePattern = "Steep Fan Plunge";
        waterfall10.tributarySource = "Sita River";
        waterfall10.dropHeight = 120.0;
        waterfall10.plungePoolDepth = "Rocky Basin";
        waterfall10.therapeuticSprings = true;
        waterfall10.peakSeasonVisitors = 210000;
        waterfall10.geologyFormation = "Gneiss Slabs";
        waterfall10.endemicAmphibians = true;
        waterfall10.geologicalAge = 55;
        waterfall10.ecoTourismRevenue = 5200000.00;
        waterfall10.rainfallZone = "Someshwara Hills";
        waterfall10.perennialFlow = false;
        waterfall10.accessDifficulty = "Forest Trail";
        waterfall10.crestWidth = 75;
        waterfall10.erosionResistant = true;
        waterfall10.biodiversityIndex = "Very High";
        waterfall10.droneSurveyed = true;
        waterfall10.conservationZone = "Karkala Division";
        waterfall10.annualPreservation = 380000.00;
        waterfall10.rescueHelpline = "08252-456789";
        
        System.out.println("Cascade ID: " + waterfall10.cascadeId);
        System.out.println("Cascade Name: " + waterfall10.cascadeName);
        System.out.println("District: " + waterfall10.district);
        System.out.println("Protected Status: " + waterfall10.protectedStatus);
        System.out.println("First Recorded: " + waterfall10.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall10.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall10.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall10.cascadePattern);
        System.out.println("Tributary Source: " + waterfall10.tributarySource);
        System.out.println("Drop Height: " + waterfall10.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall10.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall10.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall10.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall10.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall10.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall10.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall10.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall10.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall10.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall10.accessDifficulty);
        System.out.println("Crest Width: " + waterfall10.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall10.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall10.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall10.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall10.conservationZone);
        System.out.println("Annual Preservation: " + waterfall10.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall10.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall11 = new Waterfalls();
        waterfall11.cascadeId = 1011;
        waterfall11.cascadeName = "Arisinagundi Falls";
        waterfall11.district = "Shivamogga";
        waterfall11.protectedStatus = true;
        waterfall11.firstRecorded = "05/03/1955";
        waterfall11.recentAssessment = "05/03/2026";
        waterfall11.assessmentPending = false;
        waterfall11.cascadePattern = "Horsetail Sheet";
        waterfall11.tributarySource = "Varahi River";
        waterfall11.dropHeight = 150.0;
        waterfall11.plungePoolDepth = "Underground Pool";
        waterfall11.therapeuticSprings = true;
        waterfall11.peakSeasonVisitors = 180000;
        waterfall11.geologyFormation = "Limestone Caves";
        waterfall11.endemicAmphibians = true;
        waterfall11.geologicalAge = 62;
        waterfall11.ecoTourismRevenue = 4500000.00;
        waterfall11.rainfallZone = "Thirthahalli Ghat";
        waterfall11.perennialFlow = true;
        waterfall11.accessDifficulty = "Cave Trek";
        waterfall11.crestWidth = 110;
        waterfall11.erosionResistant = true;
        waterfall11.biodiversityIndex = "High";
        waterfall11.droneSurveyed = false;
        waterfall11.conservationZone = "Thirthahalli Division";
        waterfall11.annualPreservation = 320000.00;
        waterfall11.rescueHelpline = "08187-789012";
        
        System.out.println("Cascade ID: " + waterfall11.cascadeId);
        System.out.println("Cascade Name: " + waterfall11.cascadeName);
        System.out.println("District: " + waterfall11.district);
        System.out.println("Protected Status: " + waterfall11.protectedStatus);
        System.out.println("First Recorded: " + waterfall11.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall11.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall11.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall11.cascadePattern);
        System.out.println("Tributary Source: " + waterfall11.tributarySource);
        System.out.println("Drop Height: " + waterfall11.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall11.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall11.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall11.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall11.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall11.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall11.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall11.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall11.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall11.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall11.accessDifficulty);
        System.out.println("Crest Width: " + waterfall11.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall11.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall11.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall11.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall11.conservationZone);
        System.out.println("Annual Preservation: " + waterfall11.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall11.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall12 = new Waterfalls();
        waterfall12.cascadeId = 1012;
        waterfall12.cascadeName = "Kunchikal Falls";
        waterfall12.district = "Shivamogga";
        waterfall12.protectedStatus = true;
        waterfall12.firstRecorded = "05/03/1965";
        waterfall12.recentAssessment = "05/03/2026";
        waterfall12.assessmentPending = true;
        waterfall12.cascadePattern = "Tiered Block";
        waterfall12.tributarySource = "Varahi River";
        waterfall12.dropHeight = 455.0;
        waterfall12.plungePoolDepth = "Deep Reservoir";
        waterfall12.therapeuticSprings = false;
        waterfall12.peakSeasonVisitors = 95000;
        waterfall12.geologyFormation = "Deccan Trap";
        waterfall12.endemicAmphibians = true;
        waterfall12.geologicalAge = 72;
        waterfall12.ecoTourismRevenue = 3800000.00;
        waterfall12.rainfallZone = "Hosanagara Ghat";
        waterfall12.perennialFlow = true;
        waterfall12.accessDifficulty = "Restricted Access";
        waterfall12.crestWidth = 320;
        waterfall12.erosionResistant = false;
        waterfall12.biodiversityIndex = "Medium";
        waterfall12.droneSurveyed = true;
        waterfall12.conservationZone = "Hosanagara Division";
        waterfall12.annualPreservation = 280000.00;
        waterfall12.rescueHelpline = "08187-123456";
        
        System.out.println("Cascade ID: " + waterfall12.cascadeId);
        System.out.println("Cascade Name: " + waterfall12.cascadeName);
        System.out.println("District: " + waterfall12.district);
        System.out.println("Protected Status: " + waterfall12.protectedStatus);
        System.out.println("First Recorded: " + waterfall12.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall12.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall12.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall12.cascadePattern);
        System.out.println("Tributary Source: " + waterfall12.tributarySource);
        System.out.println("Drop Height: " + waterfall12.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall12.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall12.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall12.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall12.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall12.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall12.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall12.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall12.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall12.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall12.accessDifficulty);
        System.out.println("Crest Width: " + waterfall12.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall12.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall12.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall12.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall12.conservationZone);
        System.out.println("Annual Preservation: " + waterfall12.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall12.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall13 = new Waterfalls();
        waterfall13.cascadeId = 1013;
        waterfall13.cascadeName = "Kalhatti Falls";
        waterfall13.district = "Chikkamagaluru";
        waterfall13.protectedStatus = true;
        waterfall13.firstRecorded = "05/03/1925";
        waterfall13.recentAssessment = "05/03/2026";
        waterfall13.assessmentPending = false;
        waterfall13.cascadePattern = "Curtain Sheet";
        waterfall13.tributarySource = "Hemavathi River";
        waterfall13.dropHeight = 40.0;
        waterfall13.plungePoolDepth = "Shallow Temple Pool";
        waterfall13.therapeuticSprings = true;
        waterfall13.peakSeasonVisitors = 240000;
        waterfall13.geologyFormation = "Hornblende Gneiss";
        waterfall13.endemicAmphibians = false;
        waterfall13.geologicalAge = 48;
        waterfall13.ecoTourismRevenue = 5600000.00;
        waterfall13.rainfallZone = "Baba Budangiri";
        waterfall13.perennialFlow = true;
        waterfall13.accessDifficulty = "Roadside Easy";
        waterfall13.crestWidth = 200;
        waterfall13.erosionResistant = true;
        waterfall13.biodiversityIndex = "High";
        waterfall13.droneSurveyed = true;
        waterfall13.conservationZone = "Tirthahalli Division";
        waterfall13.annualPreservation = 410000.00;
        waterfall13.rescueHelpline = "08263-345678";
        
        System.out.println("Cascade ID: " + waterfall13.cascadeId);
        System.out.println("Cascade Name: " + waterfall13.cascadeName);
        System.out.println("District: " + waterfall13.district);
        System.out.println("Protected Status: " + waterfall13.protectedStatus);
        System.out.println("First Recorded: " + waterfall13.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall13.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall13.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall13.cascadePattern);
        System.out.println("Tributary Source: " + waterfall13.tributarySource);
        System.out.println("Drop Height: " + waterfall13.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall13.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall13.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall13.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall13.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall13.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall13.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall13.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall13.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall13.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall13.accessDifficulty);
        System.out.println("Crest Width: " + waterfall13.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall13.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall13.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall13.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall13.conservationZone);
        System.out.println("Annual Preservation: " + waterfall13.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall13.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall14 = new Waterfalls();
        waterfall14.cascadeId = 1014;
        waterfall14.cascadeName = "Sathodi Falls";
        waterfall14.district = "Uttara Kannada";
        waterfall14.protectedStatus = true;
        waterfall14.firstRecorded = "05/03/1915";
        waterfall14.recentAssessment = "05/03/2026";
        waterfall14.assessmentPending = false;
        waterfall14.cascadePattern = "Horsetail Plunge";
        waterfall14.tributarySource = "Gerusoppa River";
        waterfall14.dropHeight = 125.0;
        waterfall14.plungePoolDepth = "Coconut Fringed";
        waterfall14.therapeuticSprings = true;
        waterfall14.peakSeasonVisitors = 290000;
        waterfall14.geologyFormation = "Laterite Plateau";
        waterfall14.endemicAmphibians = true;
        waterfall14.geologicalAge = 58;
        waterfall14.ecoTourismRevenue = 6400000.00;
        waterfall14.rainfallZone = "Yana Caves";
        waterfall14.perennialFlow = false;
        waterfall14.accessDifficulty = "Jeep Track";
        waterfall14.crestWidth = 90;
        waterfall14.erosionResistant = true;
        waterfall14.biodiversityIndex = "Very High";
        waterfall14.droneSurveyed = true;
        waterfall14.conservationZone = "Haliyal Division";
        waterfall14.annualPreservation = 450000.00;
        waterfall14.rescueHelpline = "08386-234567";
        
        System.out.println("Cascade ID: " + waterfall14.cascadeId);
        System.out.println("Cascade Name: " + waterfall14.cascadeName);
        System.out.println("District: " + waterfall14.district);
        System.out.println("Protected Status: " + waterfall14.protectedStatus);
        System.out.println("First Recorded: " + waterfall14.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall14.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall14.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall14.cascadePattern);
        System.out.println("Tributary Source: " + waterfall14.tributarySource);
        System.out.println("Drop Height: " + waterfall14.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall14.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall14.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall14.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall14.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall14.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall14.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall14.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall14.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall14.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall14.accessDifficulty);
        System.out.println("Crest Width: " + waterfall14.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall14.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall14.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall14.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall14.conservationZone);
        System.out.println("Annual Preservation: " + waterfall14.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall14.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall15 = new Waterfalls();
        waterfall15.cascadeId = 1015;
        waterfall15.cascadeName = "Chunchi Falls";
        waterfall15.district = "Ramanagara";
        waterfall15.protectedStatus = true;
        waterfall15.firstRecorded = "05/03/1895";
        waterfall15.recentAssessment = "05/03/2026";
        waterfall15.assessmentPending = false;
        waterfall15.cascadePattern = "Steep Segmented";
        waterfall15.tributarySource = "Arkavati River";
        waterfall15.dropHeight = 65.0;
        waterfall15.plungePoolDepth = "Rocky Rapids";
        waterfall15.therapeuticSprings = true;
        waterfall15.peakSeasonVisitors = 350000;
        waterfall15.geologyFormation = "Granite Escarpment";
        waterfall15.endemicAmphibians = true;
        waterfall15.geologicalAge = 36;
        waterfall15.ecoTourismRevenue = 7200000.00;
        waterfall15.rainfallZone = "Bannerghatta Hills";
        waterfall15.perennialFlow = false;
        waterfall15.accessDifficulty = "Rappelling Trek";
        waterfall15.crestWidth = 130;
        waterfall15.erosionResistant = true;
        waterfall15.biodiversityIndex = "High";
        waterfall15.droneSurveyed = true;
        waterfall15.conservationZone = "Kanakapura Division";
        waterfall15.annualPreservation = 520000.00;
        waterfall15.rescueHelpline = "080-27831234";
        
        System.out.println("Cascade ID: " + waterfall15.cascadeId);
        System.out.println("Cascade Name: " + waterfall15.cascadeName);
        System.out.println("District: " + waterfall15.district);
        System.out.println("Protected Status: " + waterfall15.protectedStatus);
        System.out.println("First Recorded: " + waterfall15.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall15.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall15.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall15.cascadePattern);
        System.out.println("Tributary Source: " + waterfall15.tributarySource);
        System.out.println("Drop Height: " + waterfall15.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall15.plungePoolDepth);

        Waterfalls waterfall16 = new Waterfalls();
        waterfall16.cascadeId = 1016;
        waterfall16.cascadeName = "Vaali Falls";
        waterfall16.district = "Uttara Kannada";
        waterfall16.protectedStatus = true;
        waterfall16.firstRecorded = "05/03/1930";
        waterfall16.recentAssessment = "05/03/2026";
        waterfall16.assessmentPending = true;
        waterfall16.cascadePattern = "Fan Plunge";
        waterfall16.tributarySource = "Kali River";
        waterfall16.dropHeight = 150.0;
        waterfall16.plungePoolDepth = "Deep Jungle Pool";
        waterfall16.therapeuticSprings = true;
        waterfall16.peakSeasonVisitors = 260000;
        waterfall16.geologyFormation = "Basalt Columns";
        waterfall16.endemicAmphibians = true;
        waterfall16.geologicalAge = 64;
        waterfall16.ecoTourismRevenue = 6800000.00;
        waterfall16.rainfallZone = "Dandeli Wildlife";
        waterfall16.perennialFlow = true;
        waterfall16.accessDifficulty = "Jungle Jeep";
        waterfall16.crestWidth = 160;
        waterfall16.erosionResistant = true;
        waterfall16.biodiversityIndex = "Very High";
        waterfall16.droneSurveyed = true;
        waterfall16.conservationZone = "Dandeli Division";
        waterfall16.annualPreservation = 610000.00;
        waterfall16.rescueHelpline = "08284-234567";
        
        System.out.println("Cascade ID: " + waterfall16.cascadeId);
        System.out.println("Cascade Name: " + waterfall16.cascadeName);
        System.out.println("District: " + waterfall16.district);
        System.out.println("Protected Status: " + waterfall16.protectedStatus);
        System.out.println("First Recorded: " + waterfall16.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall16.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall16.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall16.cascadePattern);
        System.out.println("Tributary Source: " + waterfall16.tributarySource);
        System.out.println("Drop Height: " + waterfall16.dropHeight + "m");

        Waterfalls waterfall17 = new Waterfalls();
        waterfall17.cascadeId = 1017;
        waterfall17.cascadeName = "Hogenakkal Falls";
        waterfall17.district = "Chamarajanagar";
        waterfall17.protectedStatus = true;
        waterfall17.firstRecorded = "05/03/1805";
        waterfall17.recentAssessment = "05/03/2026";
        waterfall17.assessmentPending = false;
        waterfall17.cascadePattern = "Series Cascades";
        waterfall17.tributarySource = "Kaveri River";
        waterfall17.dropHeight = 20.0;
        waterfall17.plungePoolDepth = "Medicinal Rapids";
        waterfall17.therapeuticSprings = true;
        waterfall17.peakSeasonVisitors = 480000;
        waterfall17.geologyFormation = "Cauvery Gorges";
        waterfall17.endemicAmphibians = false;
        waterfall17.geologicalAge = 82;
        waterfall17.ecoTourismRevenue = 11500000.00;
        waterfall17.rainfallZone = "MM Hills";
        waterfall17.perennialFlow = true;
        waterfall17.accessDifficulty = "Coracle Ride";
        waterfall17.crestWidth = 670;
        waterfall17.erosionResistant = false;
        waterfall17.biodiversityIndex = "Medium";
        waterfall17.droneSurveyed = true;
        waterfall17.conservationZone = "Kollegal Division";
        waterfall17.annualPreservation = 890000.00;
        waterfall17.rescueHelpline = "08234-456789";
        
        System.out.println("Cascade ID: " + waterfall17.cascadeId);
        System.out.println("Cascade Name: " + waterfall17.cascadeName);
        System.out.println("District: " + waterfall17.district);
        System.out.println("Protected Status: " + waterfall17.protectedStatus);
        System.out.println("First Recorded: " + waterfall17.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall17.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall17.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall17.cascadePattern);
        System.out.println("Tributary Source: " + waterfall17.tributarySource);
        System.out.println("Drop Height: " + waterfall17.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall17.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall17.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall17.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall17.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall17.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall17.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall17.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall17.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall17.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall17.accessDifficulty);
        System.out.println("Crest Width: " + waterfall17.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall17.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall17.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall17.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall17.conservationZone);
        System.out.println("Annual Preservation: " + waterfall17.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall17.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall18 = new Waterfalls();
        waterfall18.cascadeId = 1018;
        waterfall18.cascadeName = "Mallalli Falls";
        waterfall18.district = "Kodagu";
        waterfall18.protectedStatus = true;
        waterfall18.firstRecorded = "05/03/1880";
        waterfall18.recentAssessment = "05/03/2026";
        waterfall18.assessmentPending = false;
        waterfall18.cascadePattern = "Multi-Tiered Plunge";
        waterfall18.tributarySource = "Kumaradhara River";
        waterfall18.dropHeight = 120.0;
        waterfall18.plungePoolDepth = "Deep Misty Pool";
        waterfall18.therapeuticSprings = true;
        waterfall18.peakSeasonVisitors = 320000;
        waterfall18.geologyFormation = "Pushpagiri Slopes";
        waterfall18.endemicAmphibians = true;
        waterfall18.geologicalAge = 45;
        waterfall18.ecoTourismRevenue = 7800000.00;
        waterfall18.rainfallZone = "Pushpagiri Hills";
        waterfall18.perennialFlow = true;
        waterfall18.accessDifficulty = "Concrete Steps";
        waterfall18.crestWidth = 110;
        waterfall18.erosionResistant = true;
        waterfall18.biodiversityIndex = "Very High";
        waterfall18.droneSurveyed = true;
        waterfall18.conservationZone = "Somwarpet Division";
        waterfall18.annualPreservation = 540000.00;
        waterfall18.rescueHelpline = "08276-234567";
        
        System.out.println("Cascade ID: " + waterfall18.cascadeId);
        System.out.println("Cascade Name: " + waterfall18.cascadeName);
        System.out.println("District: " + waterfall18.district);
        System.out.println("Protected Status: " + waterfall18.protectedStatus);
        System.out.println("First Recorded: " + waterfall18.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall18.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall18.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall18.cascadePattern);
        System.out.println("Tributary Source: " + waterfall18.tributarySource);
        System.out.println("Drop Height: " + waterfall18.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall18.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall18.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall18.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall18.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall18.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall18.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall18.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall18.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall18.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall18.accessDifficulty);
        System.out.println("Crest Width: " + waterfall18.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall18.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall18.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall18.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall18.conservationZone);
        System.out.println("Annual Preservation: " + waterfall18.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall18.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall19 = new Waterfalls();
        waterfall19.cascadeId = 1019;
        waterfall19.cascadeName = "Thattekad Falls";
        waterfall19.district = "Kodagu";
        waterfall19.protectedStatus = true;
        waterfall19.firstRecorded = "05/03/1940";
        waterfall19.recentAssessment = "05/03/2026";
        waterfall19.assessmentPending = true;
        waterfall19.cascadePattern = "Tiered Horsetail";
        waterfall19.tributarySource = "Pushpagiri Stream";
        waterfall19.dropHeight = 85.0;
        waterfall19.plungePoolDepth = "Forest Pool";
        waterfall19.therapeuticSprings = true;
        waterfall19.peakSeasonVisitors = 190000;
        waterfall19.geologyFormation = "Laterite Cliffs";
        waterfall19.endemicAmphibians = true;
        waterfall19.geologicalAge = 41;
        waterfall19.ecoTourismRevenue = 4900000.00;
        waterfall19.rainfallZone = "Coorg Rainforest";
        waterfall19.perennialFlow = false;
        waterfall19.accessDifficulty = "Moderate Trek";
        waterfall19.crestWidth = 80;
        waterfall19.erosionResistant = true;
        waterfall19.biodiversityIndex = "Extremely High";
        waterfall19.droneSurveyed = false;
        waterfall19.conservationZone = "Madikeri Division";
        waterfall19.annualPreservation = 370000.00;
        waterfall19.rescueHelpline = "08272-567890";
        
        System.out.println("Cascade ID: " + waterfall19.cascadeId);
        System.out.println("Cascade Name: " + waterfall19.cascadeName);
        System.out.println("District: " + waterfall19.district);
        System.out.println("Protected Status: " + waterfall19.protectedStatus);
        System.out.println("First Recorded: " + waterfall19.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall19.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall19.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall19.cascadePattern);
        System.out.println("Tributary Source: " + waterfall19.tributarySource);
        System.out.println("Drop Height: " + waterfall19.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall19.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall19.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall19.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall19.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall19.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall19.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall19.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall19.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall19.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall19.accessDifficulty);
        System.out.println("Crest Width: " + waterfall19.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall19.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall19.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall19.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall19.conservationZone);
        System.out.println("Annual Preservation: " + waterfall19.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall19.rescueHelpline);
        System.out.println("-----------------------------");

        Waterfalls waterfall20 = new Waterfalls();
        waterfall20.cascadeId = 1020;
        waterfall20.cascadeName = "Belum Falls";
        waterfall20.district = "Chikkamagaluru";
        waterfall20.protectedStatus = true;
        waterfall20.firstRecorded = "05/03/1970";
        waterfall20.recentAssessment = "05/03/2026";
        waterfall20.assessmentPending = false;
        waterfall20.cascadePattern = "Plunge Sheet";
        waterfall20.tributarySource = "Bhadra River";
        waterfall20.dropHeight = 320.0;
        waterfall20.plungePoolDepth = "Deep Canyon Pool";
        waterfall20.therapeuticSprings = true;
        waterfall20.peakSeasonVisitors = 220000;
        waterfall20.geologyFormation = "Mullayanagiri Granite";
        waterfall20.endemicAmphibians = true;
        waterfall20.geologicalAge = 39;
        waterfall20.ecoTourismRevenue = 6200000.00;
        waterfall20.rainfallZone = "Mullayanagiri Range";
        waterfall20.perennialFlow = true;
        waterfall20.accessDifficulty = "High Altitude Trek";
        waterfall20.crestWidth = 140;
        waterfall20.erosionResistant = true;
        waterfall20.biodiversityIndex = "Very High";
        waterfall20.droneSurveyed = true;
        waterfall20.conservationZone = "Kemmangundi Division";
        waterfall20.annualPreservation = 480000.00;
        waterfall20.rescueHelpline = "08262-345678";
        
        System.out.println("Cascade ID: " + waterfall20.cascadeId);
        System.out.println("Cascade Name: " + waterfall20.cascadeName);
        System.out.println("District: " + waterfall20.district);
        System.out.println("Protected Status: " + waterfall20.protectedStatus);
        System.out.println("First Recorded: " + waterfall20.firstRecorded);
        System.out.println("Recent Assessment: " + waterfall20.recentAssessment);
        System.out.println("Assessment Pending: " + waterfall20.assessmentPending);
        System.out.println("Cascade Pattern: " + waterfall20.cascadePattern);
        System.out.println("Tributary Source: " + waterfall20.tributarySource);
        System.out.println("Drop Height: " + waterfall20.dropHeight + "m");
        System.out.println("Plunge Pool Depth: " + waterfall20.plungePoolDepth);
        System.out.println("Therapeutic Springs: " + waterfall20.therapeuticSprings);
        System.out.println("Peak Season Visitors: " + waterfall20.peakSeasonVisitors);
        System.out.println("Geology Formation: " + waterfall20.geologyFormation);
        System.out.println("Endemic Amphibians: " + waterfall20.endemicAmphibians);
        System.out.println("Geological Age: " + waterfall20.geologicalAge + "M years");
        System.out.println("Eco Tourism Revenue: " + waterfall20.ecoTourismRevenue);
        System.out.println("Rainfall Zone: " + waterfall20.rainfallZone);
        System.out.println("Perennial Flow: " + waterfall20.perennialFlow);
        System.out.println("Access Difficulty: " + waterfall20.accessDifficulty);
        System.out.println("Crest Width: " + waterfall20.crestWidth + "m");
        System.out.println("Erosion Resistant: " + waterfall20.erosionResistant);
        System.out.println("Biodiversity Index: " + waterfall20.biodiversityIndex);
        System.out.println("Drone Surveyed: " + waterfall20.droneSurveyed);
        System.out.println("Conservation Zone: " + waterfall20.conservationZone);
        System.out.println("Annual Preservation: " + waterfall20.annualPreservation);
        System.out.println("Rescue Helpline: " + waterfall20.rescueHelpline);
        System.out.println("-----------------------------");

		
		
		
    }
}
