class WindowsExecutor {
    public static void main(String[] args) {
      
        System.out.println(" BEFORE INSTANCE INITIALIZATION ");
        Windows win1 = new Windows();
        
        System.out.println("Product ID: " + win1.productId);
        System.out.println("License Price: " + win1.licensePrice);
        System.out.println("Genuine Key: " + win1.genuineKey);
        System.out.println("Activated: " + win1.activated);
        System.out.println("Install Date: " + win1.installDate);
        System.out.println("Support Ends: " + win1.supportEnd);
        System.out.println("Updates Available: " + win1.updatesAvailable);
        System.out.println("Edition: " + win1.edition);
        System.out.println("Version: " + win1.version);
        System.out.println("Build Number: " + win1.buildNumber);
        System.out.println("Architecture: " + win1.architecture);
        System.out.println("RAM Requirement: " + win1.ramRequirement + "GB");
        System.out.println("Storage Space: " + win1.storageSpace + "GB");
        System.out.println("Download Size: " + win1.downloadSize + "GB");
        System.out.println("Language: " + win1.language);
        System.out.println("Bit Version: " + win1.bitVersion);
        System.out.println("Activation Key: " + win1.activationKey);
        System.out.println("Home Edition: " + win1.homeEdition);
        System.out.println("System Requirements: " + win1.systemRequirements);
        System.out.println("CPU Speed: " + win1.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win1.uiTheme);
        System.out.println("Cortana Enabled: " + win1.cortanaEnabled);
        System.out.println("Max Users: " + win1.maxUsers);
        System.out.println("Developer: " + win1.developer);
        System.out.println("Release Date: " + win1.releaseDate);
        System.out.println("Upgrade Price: " + win1.upgradePrice);
        System.out.println("-----------------------------");
        
        
        System.out.println("=== AFTER FIRST INSTANCE INITIALIZED ===");
        win1.productId = 1001;
        win1.licensePrice = 9999.99;
        win1.genuineKey = true;
        win1.activated = true;
        win1.installDate = "05/03/2026";
        win1.supportEnd = "05/03/2029";
        win1.updatesAvailable = true;
        win1.edition = "Windows 11 Pro";
        win1.version = "11";
        win1.buildNumber = "22631.2792";
        win1.architecture = "64-bit";
        win1.ramRequirement = 4;
        win1.storageSpace = 64;
        win1.downloadSize = 5.2;
        win1.language = "English (India)";
        win1.bitVersion = 64;
        win1.activationKey = "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX";
        win1.homeEdition = false;
        win1.systemRequirements = "Intel i5 or equivalent";
        win1.cpuSpeed = 2.5;
        win1.uiTheme = "Dark Mode";
        win1.cortanaEnabled = false;
        win1.maxUsers = 1;
        win1.developer = "Microsoft";
        win1.releaseDate = "2021-10-05";
        win1.upgradePrice = 7999.99;
        
        System.out.println("Product ID: " + win1.productId);
        System.out.println("License Price: " + win1.licensePrice);
        System.out.println("Genuine Key: " + win1.genuineKey);
        System.out.println("Activated: " + win1.activated);
        System.out.println("Install Date: " + win1.installDate);
        System.out.println("Support Ends: " + win1.supportEnd);
        System.out.println("Updates Available: " + win1.updatesAvailable);
        System.out.println("Edition: " + win1.edition);
        System.out.println("Version: " + win1.version);
        System.out.println("Build Number: " + win1.buildNumber);
        System.out.println("Architecture: " + win1.architecture);
        System.out.println("RAM Requirement: " + win1.ramRequirement + "GB");
        System.out.println("Storage Space: " + win1.storageSpace + "GB");
        System.out.println("Download Size: " + win1.downloadSize + "GB");
        System.out.println("Language: " + win1.language);
        System.out.println("Bit Version: " + win1.bitVersion);
        System.out.println("Activation Key: " + win1.activationKey);
        System.out.println("Home Edition: " + win1.homeEdition);
        System.out.println("System Requirements: " + win1.systemRequirements);
        System.out.println("CPU Speed: " + win1.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win1.uiTheme);
        System.out.println("Cortana Enabled: " + win1.cortanaEnabled);
        System.out.println("Max Users: " + win1.maxUsers);
        System.out.println("Developer: " + win1.developer);
        System.out.println("Release Date: " + win1.releaseDate);
        System.out.println("Upgrade Price: " + win1.upgradePrice);
        System.out.println("-----------------------------");
     

	 
       System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win2 = new Windows();

System.out.println("Product ID: " + win2.productId);
System.out.println("License Price: " + win2.licensePrice);
System.out.println("Genuine Key: " + win2.genuineKey);
System.out.println("Activated: " + win2.activated);
System.out.println("Install Date: " + win2.installDate);
System.out.println("Support Ends: " + win2.supportEnd);
System.out.println("Updates Available: " + win2.updatesAvailable);
System.out.println("Edition: " + win2.edition);
System.out.println("Version: " + win2.version);
System.out.println("Build Number: " + win2.buildNumber);
System.out.println("Architecture: " + win2.architecture);
System.out.println("RAM Requirement: " + win2.ramRequirement + "GB");
System.out.println("Storage Space: " + win2.storageSpace + "GB");
System.out.println("Download Size: " + win2.downloadSize + "GB");
System.out.println("Language: " + win2.language);
System.out.println("Bit Version: " + win2.bitVersion);
System.out.println("Activation Key: " + win2.activationKey);
System.out.println("Home Edition: " + win2.homeEdition);
System.out.println("System Requirements: " + win2.systemRequirements);
System.out.println("CPU Speed: " + win2.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win2.uiTheme);
System.out.println("Cortana Enabled: " + win2.cortanaEnabled);
System.out.println("Max Users: " + win2.maxUsers);
System.out.println("Developer: " + win2.developer);
System.out.println("Release Date: " + win2.releaseDate);
System.out.println("Upgrade Price: " + win2.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN2 INSTANCE INITIALIZED ===");
win2.productId = 2002;
win2.licensePrice = 12999.99;
win2.genuineKey = true;
win2.activated = true;
win2.installDate = "04/03/2026";
win2.supportEnd = "04/03/2030";
win2.updatesAvailable = false;
win2.edition = "Windows 11 Home";
win2.version = "10";
win2.buildNumber = "19045.4170";
win2.architecture = "32-bit";
win2.ramRequirement = 2;
win2.storageSpace = 32;
win2.downloadSize = 4.8;
win2.language = "Hindi";
win2.bitVersion = 32;
win2.activationKey = "YYYYY-YYYYY-YYYYY-YYYYY-YYYYY";
win2.homeEdition = true;
win2.systemRequirements = "Intel i3 or equivalent";
win2.cpuSpeed = 1.8;
win2.uiTheme = "Light Mode";
win2.cortanaEnabled = true;
win2.maxUsers = 5;
win2.developer = "Microsoft";
win2.releaseDate = "2020-05-27";
win2.upgradePrice = 5999.99;

System.out.println("Product ID: " + win2.productId);
System.out.println("License Price: " + win2.licensePrice);
System.out.println("Genuine Key: " + win2.genuineKey);
System.out.println("Activated: " + win2.activated);
System.out.println("Install Date: " + win2.installDate);
System.out.println("Support Ends: " + win2.supportEnd);
System.out.println("Updates Available: " + win2.updatesAvailable);
System.out.println("Edition: " + win2.edition);
System.out.println("Version: " + win2.version);
System.out.println("Build Number: " + win2.buildNumber);
System.out.println("Architecture: " + win2.architecture);
System.out.println("RAM Requirement: " + win2.ramRequirement + "GB");
System.out.println("Storage Space: " + win2.storageSpace + "GB");
System.out.println("Download Size: " + win2.downloadSize + "GB");
System.out.println("Language: " + win2.language);
System.out.println("Bit Version: " + win2.bitVersion);
System.out.println("Activation Key: " + win2.activationKey);
System.out.println("Home Edition: " + win2.homeEdition);
System.out.println("System Requirements: " + win2.systemRequirements);
System.out.println("CPU Speed: " + win2.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win2.uiTheme);
System.out.println("Cortana Enabled: " + win2.cortanaEnabled);
System.out.println("Max Users: " + win2.maxUsers);
System.out.println("Developer: " + win2.developer);
System.out.println("Release Date: " + win2.releaseDate);
System.out.println("Upgrade Price: " + win2.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win3 = new Windows();

System.out.println("Product ID: " + win3.productId);
System.out.println("License Price: " + win3.licensePrice);
System.out.println("Genuine Key: " + win3.genuineKey);
System.out.println("Activated: " + win3.activated);
System.out.println("Install Date: " + win3.installDate);
System.out.println("Support Ends: " + win3.supportEnd);
System.out.println("Updates Available: " + win3.updatesAvailable);
System.out.println("Edition: " + win3.edition);
System.out.println("Version: " + win3.version);
System.out.println("Build Number: " + win3.buildNumber);
System.out.println("Architecture: " + win3.architecture);
System.out.println("RAM Requirement: " + win3.ramRequirement + "GB");
System.out.println("Storage Space: " + win3.storageSpace + "GB");
System.out.println("Download Size: " + win3.downloadSize + "GB");
System.out.println("Language: " + win3.language);
System.out.println("Bit Version: " + win3.bitVersion);
System.out.println("Activation Key: " + win3.activationKey);
System.out.println("Home Edition: " + win3.homeEdition);
System.out.println("System Requirements: " + win3.systemRequirements);
System.out.println("CPU Speed: " + win3.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win3.uiTheme);
System.out.println("Cortana Enabled: " + win3.cortanaEnabled);
System.out.println("Max Users: " + win3.maxUsers);
System.out.println("Developer: " + win3.developer);
System.out.println("Release Date: " + win3.releaseDate);
System.out.println("Upgrade Price: " + win3.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN3 INSTANCE INITIALIZED ===");
win3.productId = 3003;
win3.licensePrice = 7999.99;
win3.genuineKey = false;
win3.activated = false;
win3.installDate = "03/03/2026";
win3.supportEnd = "03/03/2028";
win3.updatesAvailable = true;
win3.edition = "Windows 10 Enterprise";
win3.version = "10";
win3.buildNumber = "19044.3930";
win3.architecture = "64-bit";
win3.ramRequirement = 8;
win3.storageSpace = 128;
win3.downloadSize = 6.1;
win3.language = "Kannada";
win3.bitVersion = 64;
win3.activationKey = "ZZZZZ-ZZZZZ-ZZZZZ-ZZZZZ-ZZZZZ";
win3.homeEdition = false;
win3.systemRequirements = "Intel i7 or equivalent";
win3.cpuSpeed = 3.2;
win3.uiTheme = "Fluent Design";
win3.cortanaEnabled = true;
win3.maxUsers = 10;
win3.developer = "Microsoft";
win3.releaseDate = "2019-11-12";
win3.upgradePrice = 14999.99;

System.out.println("Product ID: " + win3.productId);
System.out.println("License Price: " + win3.licensePrice);
System.out.println("Genuine Key: " + win3.genuineKey);
System.out.println("Activated: " + win3.activated);
System.out.println("Install Date: " + win3.installDate);
System.out.println("Support Ends: " + win3.supportEnd);
System.out.println("Updates Available: " + win3.updatesAvailable);
System.out.println("Edition: " + win3.edition);
System.out.println("Version: " + win3.version);
System.out.println("Build Number: " + win3.buildNumber);
System.out.println("Architecture: " + win3.architecture);
System.out.println("RAM Requirement: " + win3.ramRequirement + "GB");
System.out.println("Storage Space: " + win3.storageSpace + "GB");
System.out.println("Download Size: " + win3.downloadSize + "GB");
System.out.println("Language: " + win3.language);
System.out.println("Bit Version: " + win3.bitVersion);
System.out.println("Activation Key: " + win3.activationKey);
System.out.println("Home Edition: " + win3.homeEdition);
System.out.println("System Requirements: " + win3.systemRequirements);
System.out.println("CPU Speed: " + win3.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win3.uiTheme);
System.out.println("Cortana Enabled: " + win3.cortanaEnabled);
System.out.println("Max Users: " + win3.maxUsers);
System.out.println("Developer: " + win3.developer);
System.out.println("Release Date: " + win3.releaseDate);
System.out.println("Upgrade Price: " + win3.upgradePrice);
System.out.println("-----------------------------");


 System.out.println(" BEFORE INSTANCE INITIALIZATION ");
        Windows win4 = new Windows();
        
        System.out.println("Product ID: " + win4.productId);
        System.out.println("License Price: " + win4.licensePrice);
        System.out.println("Genuine Key: " + win4.genuineKey);
        System.out.println("Activated: " + win4.activated);
        System.out.println("Install Date: " + win4.installDate);
        System.out.println("Support Ends: " + win4.supportEnd);
        System.out.println("Updates Available: " + win4.updatesAvailable);
        System.out.println("Edition: " + win4.edition);
        System.out.println("Version: " + win4.version);
        System.out.println("Build Number: " + win4.buildNumber);
        System.out.println("Architecture: " + win4.architecture);
        System.out.println("RAM Requirement: " + win4.ramRequirement + "GB");
        System.out.println("Storage Space: " + win4.storageSpace + "GB");
        System.out.println("Download Size: " + win4.downloadSize + "GB");
        System.out.println("Language: " + win4.language);
        System.out.println("Bit Version: " + win4.bitVersion);
        System.out.println("Activation Key: " + win4.activationKey);
        System.out.println("Home Edition: " + win4.homeEdition);
        System.out.println("System Requirements: " + win4.systemRequirements);
        System.out.println("CPU Speed: " + win4.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win4.uiTheme);
        System.out.println("Cortana Enabled: " + win4.cortanaEnabled);
        System.out.println("Max Users: " + win4.maxUsers);
        System.out.println("Developer: " + win4.developer);
        System.out.println("Release Date: " + win4.releaseDate);
        System.out.println("Upgrade Price: " + win4.upgradePrice);
        System.out.println("-----------------------------");
        
        System.out.println("=== AFTER WIN4 INSTANCE INITIALIZED ===");
        win4.productId = 4004;
        win4.licensePrice = 14999.99;
        win4.genuineKey = true;
        win4.activated = true;
        win4.installDate = "02/03/2026";
        win4.supportEnd = "02/03/2031";
        win4.updatesAvailable = true;
        win4.edition = "Windows 11 Education";
        win4.version = "11";
        win4.buildNumber = "22621.3821";
        win4.architecture = "64-bit";
        win4.ramRequirement = 16;
        win4.storageSpace = 256;
        win4.downloadSize = 5.8;
        win4.language = "Tamil";
        win4.bitVersion = 64;
        win4.activationKey = "AAAAA-AAAAA-AAAAA-AAAAA-AAAAA";
        win4.homeEdition = false;
        win4.systemRequirements = "Intel i9 or equivalent";
        win4.cpuSpeed = 4.0;
        win4.uiTheme = "Custom Theme";
        win4.cortanaEnabled = false;
        win4.maxUsers = 50;
        win4.developer = "Microsoft";
        win4.releaseDate = "2022-09-20";
        win4.upgradePrice = 19999.99;
        
        System.out.println("Product ID: " + win4.productId);
        System.out.println("License Price: " + win4.licensePrice);
        System.out.println("Genuine Key: " + win4.genuineKey);
        System.out.println("Activated: " + win4.activated);
        System.out.println("Install Date: " + win4.installDate);
        System.out.println("Support Ends: " + win4.supportEnd);
        System.out.println("Updates Available: " + win4.updatesAvailable);
        System.out.println("Edition: " + win4.edition);
        System.out.println("Version: " + win4.version);
        System.out.println("Build Number: " + win4.buildNumber);
        System.out.println("Architecture: " + win4.architecture);
        System.out.println("RAM Requirement: " + win4.ramRequirement + "GB");
        System.out.println("Storage Space: " + win4.storageSpace + "GB");
        System.out.println("Download Size: " + win4.downloadSize + "GB");
        System.out.println("Language: " + win4.language);
        System.out.println("Bit Version: " + win4.bitVersion);
        System.out.println("Activation Key: " + win4.activationKey);
        System.out.println("Home Edition: " + win4.homeEdition);
        System.out.println("System Requirements: " + win4.systemRequirements);
        System.out.println("CPU Speed: " + win4.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win4.uiTheme);
        System.out.println("Cortana Enabled: " + win4.cortanaEnabled);
        System.out.println("Max Users: " + win4.maxUsers);
        System.out.println("Developer: " + win4.developer);
        System.out.println("Release Date: " + win4.releaseDate);
        System.out.println("Upgrade Price: " + win4.upgradePrice);
        System.out.println("-----------------------------");
        
  
  
  
  
        System.out.println(" BEFORE INSTANCE INITIALIZATION ");
        Windows win5 = new Windows();
        
        System.out.println("Product ID: " + win5.productId);
        System.out.println("License Price: " + win5.licensePrice);
        System.out.println("Genuine Key: " + win5.genuineKey);
        System.out.println("Activated: " + win5.activated);
        System.out.println("Install Date: " + win5.installDate);
        System.out.println("Support Ends: " + win5.supportEnd);
        System.out.println("Updates Available: " + win5.updatesAvailable);
        System.out.println("Edition: " + win5.edition);
        System.out.println("Version: " + win5.version);
        System.out.println("Build Number: " + win5.buildNumber);
        System.out.println("Architecture: " + win5.architecture);
        System.out.println("RAM Requirement: " + win5.ramRequirement + "GB");
        System.out.println("Storage Space: " + win5.storageSpace + "GB");
        System.out.println("Download Size: " + win5.downloadSize + "GB");
        System.out.println("Language: " + win5.language);
        System.out.println("Bit Version: " + win5.bitVersion);
        System.out.println("Activation Key: " + win5.activationKey);
        System.out.println("Home Edition: " + win5.homeEdition);
        System.out.println("System Requirements: " + win5.systemRequirements);
        System.out.println("CPU Speed: " + win5.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win5.uiTheme);
        System.out.println("Cortana Enabled: " + win5.cortanaEnabled);
        System.out.println("Max Users: " + win5.maxUsers);
        System.out.println("Developer: " + win5.developer);
        System.out.println("Release Date: " + win5.releaseDate);
        System.out.println("Upgrade Price: " + win5.upgradePrice);
        System.out.println("-----------------------------");
        
        System.out.println("=== AFTER WIN5 INSTANCE INITIALIZED ===");
        win5.productId = 5005;
        win5.licensePrice = 29999.99;
        win5.genuineKey = true;
        win5.activated = true;
        win5.installDate = "01/03/2026";
        win5.supportEnd = "01/03/2032";
        win5.updatesAvailable = true;
        win5.edition = "Windows Server 2022";
        win5.version = "Server 2022";
        win5.buildNumber = "20348.2887";
        win5.architecture = "64-bit";
        win5.ramRequirement = 32;
        win5.storageSpace = 1024;
        win5.downloadSize = 8.5;
        win5.language = "Telugu";
        win5.bitVersion = 64;
        win5.activationKey = "BBBBB-BBBBB-BBBBB-BBBBB-BBBBB";
        win5.homeEdition = false;
        win5.systemRequirements = "Server-grade CPU";
        win5.cpuSpeed = 3.8;
        win5.uiTheme = "Server Core";
        win5.cortanaEnabled = false;
        win5.maxUsers = 1000;
        win5.developer = "Microsoft";
        win5.releaseDate = "2021-08-18";
        win5.upgradePrice = 49999.99;
        
        System.out.println("Product ID: " + win5.productId);
        System.out.println("License Price: " + win5.licensePrice);
        System.out.println("Genuine Key: " + win5.genuineKey);
        System.out.println("Activated: " + win5.activated);
        System.out.println("Install Date: " + win5.installDate);
        System.out.println("Support Ends: " + win5.supportEnd);
        System.out.println("Updates Available: " + win5.updatesAvailable);
        System.out.println("Edition: " + win5.edition);
        System.out.println("Version: " + win5.version);
        System.out.println("Build Number: " + win5.buildNumber);
        System.out.println("Architecture: " + win5.architecture);
        System.out.println("RAM Requirement: " + win5.ramRequirement + "GB");
        System.out.println("Storage Space: " + win5.storageSpace + "GB");
        System.out.println("Download Size: " + win5.downloadSize + "GB");
        System.out.println("Language: " + win5.language);
        System.out.println("Bit Version: " + win5.bitVersion);
        System.out.println("Activation Key: " + win5.activationKey);
        System.out.println("Home Edition: " + win5.homeEdition);
        System.out.println("System Requirements: " + win5.systemRequirements);
        System.out.println("CPU Speed: " + win5.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win5.uiTheme);
        System.out.println("Cortana Enabled: " + win5.cortanaEnabled);
        System.out.println("Max Users: " + win5.maxUsers);
        System.out.println("Developer: " + win5.developer);
        System.out.println("Release Date: " + win5.releaseDate);
        System.out.println("Upgrade Price: " + win5.upgradePrice);
        System.out.println("-----------------------------");
		
		
        System.out.println(" BEFORE INSTANCE INITIALIZATION ");
        Windows win6 = new Windows();
        
        System.out.println("Product ID: " + win6.productId);
        System.out.println("License Price: " + win6.licensePrice);
        System.out.println("Genuine Key: " + win6.genuineKey);
        System.out.println("Activated: " + win6.activated);
        System.out.println("Install Date: " + win6.installDate);
        System.out.println("Support Ends: " + win6.supportEnd);
        System.out.println("Updates Available: " + win6.updatesAvailable);
        System.out.println("Edition: " + win6.edition);
        System.out.println("Version: " + win6.version);
        System.out.println("Build Number: " + win6.buildNumber);
        System.out.println("Architecture: " + win6.architecture);
        System.out.println("RAM Requirement: " + win6.ramRequirement + "GB");
        System.out.println("Storage Space: " + win6.storageSpace + "GB");
        System.out.println("Download Size: " + win6.downloadSize + "GB");
        System.out.println("Language: " + win6.language);
        System.out.println("Bit Version: " + win6.bitVersion);
        System.out.println("Activation Key: " + win6.activationKey);
        System.out.println("Home Edition: " + win6.homeEdition);
        System.out.println("System Requirements: " + win6.systemRequirements);
        System.out.println("CPU Speed: " + win6.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win6.uiTheme);
        System.out.println("Cortana Enabled: " + win6.cortanaEnabled);
        System.out.println("Max Users: " + win6.maxUsers);
        System.out.println("Developer: " + win6.developer);
        System.out.println("Release Date: " + win6.releaseDate);
        System.out.println("Upgrade Price: " + win6.upgradePrice);
        System.out.println("-----------------------------");
        
        System.out.println("=== AFTER WIN6 INSTANCE INITIALIZED ===");
        win6.productId = 6006;
        win6.licensePrice = 5999.99;
        win6.genuineKey = true;
        win6.activated = true;
        win6.installDate = "28/02/2026";
        win6.supportEnd = "28/02/2035";
        win6.updatesAvailable = false;
        win6.edition = "Windows 10 LTSC";
        win6.version = "10";
        win6.buildNumber = "19041.3913";
        win6.architecture = "64-bit";
        win6.ramRequirement = 4;
        win6.storageSpace = 64;
        win6.downloadSize = 4.2;
        win6.language = "Malayalam";
        win6.bitVersion = 64;
        win6.activationKey = "CCCCC-CCCCC-CCCCC-CCCCC-CCCCC";
        win6.homeEdition = false;
        win6.systemRequirements = "Industrial PC";
        win6.cpuSpeed = 2.0;
        win6.uiTheme = "Classic";
        win6.cortanaEnabled = false;
        win6.maxUsers = 1;
        win6.developer = "Microsoft";
        win6.releaseDate = "2021-11-16";
        win6.upgradePrice = 0.0;
        
        System.out.println("Product ID: " + win6.productId);
        System.out.println("License Price: " + win6.licensePrice);
        System.out.println("Genuine Key: " + win6.genuineKey);
        System.out.println("Activated: " + win6.activated);
        System.out.println("Install Date: " + win6.installDate);
        System.out.println("Support Ends: " + win6.supportEnd);
        System.out.println("Updates Available: " + win6.updatesAvailable);
        System.out.println("Edition: " + win6.edition);
        System.out.println("Version: " + win6.version);
        System.out.println("Build Number: " + win6.buildNumber);
        System.out.println("Architecture: " + win6.architecture);
        System.out.println("RAM Requirement: " + win6.ramRequirement + "GB");
        System.out.println("Storage Space: " + win6.storageSpace + "GB");
        System.out.println("Download Size: " + win6.downloadSize + "GB");
        System.out.println("Language: " + win6.language);
        System.out.println("Bit Version: " + win6.bitVersion);
        System.out.println("Activation Key: " + win6.activationKey);
        System.out.println("Home Edition: " + win6.homeEdition);
        System.out.println("System Requirements: " + win6.systemRequirements);
        System.out.println("CPU Speed: " + win6.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win6.uiTheme);
        System.out.println("Cortana Enabled: " + win6.cortanaEnabled);
        System.out.println("Max Users: " + win6.maxUsers);
        System.out.println("Developer: " + win6.developer);
        System.out.println("Release Date: " + win6.releaseDate);
        System.out.println("Upgrade Price: " + win6.upgradePrice);
        System.out.println("-----------------------------");

		
		
        System.out.println(" BEFORE INSTANCE INITIALIZATION ");
        Windows win7 = new Windows();
        
        System.out.println("Product ID: " + win7.productId);
        System.out.println("License Price: " + win7.licensePrice);
        System.out.println("Genuine Key: " + win7.genuineKey);
        System.out.println("Activated: " + win7.activated);
        System.out.println("Install Date: " + win7.installDate);
        System.out.println("Support Ends: " + win7.supportEnd);
        System.out.println("Updates Available: " + win7.updatesAvailable);
        System.out.println("Edition: " + win7.edition);
        System.out.println("Version: " + win7.version);
        System.out.println("Build Number: " + win7.buildNumber);
        System.out.println("Architecture: " + win7.architecture);
        System.out.println("RAM Requirement: " + win7.ramRequirement + "GB");
        System.out.println("Storage Space: " + win7.storageSpace + "GB");
        System.out.println("Download Size: " + win7.downloadSize + "GB");
        System.out.println("Language: " + win7.language);
        System.out.println("Bit Version: " + win7.bitVersion);
        System.out.println("Activation Key: " + win7.activationKey);
        System.out.println("Home Edition: " + win7.homeEdition);
        System.out.println("System Requirements: " + win7.systemRequirements);
        System.out.println("CPU Speed: " + win7.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win7.uiTheme);
        System.out.println("Cortana Enabled: " + win7.cortanaEnabled);
        System.out.println("Max Users: " + win7.maxUsers);
        System.out.println("Developer: " + win7.developer);
        System.out.println("Release Date: " + win7.releaseDate);
        System.out.println("Upgrade Price: " + win7.upgradePrice);
        System.out.println("-----------------------------");
        
        System.out.println("=== AFTER WIN7 INSTANCE INITIALIZED ===");
        win7.productId = 7007;
        win7.licensePrice = 24999.99;
        win7.genuineKey = true;
        win7.activated = true;
        win7.installDate = "06/03/2026";
        win7.supportEnd = "06/03/2030";
        win7.updatesAvailable = true;
        win7.edition = "Windows 11 IoT Enterprise";
        win7.version = "11";
        win7.buildNumber = "22621.4111";
        win7.architecture = "ARM64";
        win7.ramRequirement = 8;
        win7.storageSpace = 128;
        win7.downloadSize = 3.9;
        win7.language = "Marathi";
        win7.bitVersion = 64;
        win7.activationKey = "DDDDD-DDDDD-DDDDD-DDDDD-DDDDD";
        win7.homeEdition = false;
        win7.systemRequirements = "IoT Devices";
        win7.cpuSpeed = 2.4;
        win7.uiTheme = "Embedded UI";
        win7.cortanaEnabled = false;
        win7.maxUsers = 25;
        win7.developer = "Microsoft";
        win7.releaseDate = "2023-03-10";
        win7.upgradePrice = 34999.99;
        
        System.out.println("Product ID: " + win7.productId);
        System.out.println("License Price: " + win7.licensePrice);
        System.out.println("Genuine Key: " + win7.genuineKey);
        System.out.println("Activated: " + win7.activated);
        System.out.println("Install Date: " + win7.installDate);
        System.out.println("Support Ends: " + win7.supportEnd);
        System.out.println("Updates Available: " + win7.updatesAvailable);
        System.out.println("Edition: " + win7.edition);
        System.out.println("Version: " + win7.version);
        System.out.println("Build Number: " + win7.buildNumber);
        System.out.println("Architecture: " + win7.architecture);
        System.out.println("RAM Requirement: " + win7.ramRequirement + "GB");
        System.out.println("Storage Space: " + win7.storageSpace + "GB");
        System.out.println("Download Size: " + win7.downloadSize + "GB");
        System.out.println("Language: " + win7.language);
        System.out.println("Bit Version: " + win7.bitVersion);
        System.out.println("Activation Key: " + win7.activationKey);
        System.out.println("Home Edition: " + win7.homeEdition);
        System.out.println("System Requirements: " + win7.systemRequirements);
        System.out.println("CPU Speed: " + win7.cpuSpeed + "GHz");
        System.out.println("UI Theme: " + win7.uiTheme);
        System.out.println("Cortana Enabled: " + win7.cortanaEnabled);
        System.out.println("Max Users: " + win7.maxUsers);
        System.out.println("Developer: " + win7.developer);
        System.out.println("Release Date: " + win7.releaseDate);
        System.out.println("Upgrade Price: " + win7.upgradePrice);
        System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win8 = new Windows();

System.out.println("Product ID: " + win8.productId);
System.out.println("License Price: " + win8.licensePrice);
System.out.println("Genuine Key: " + win8.genuineKey);
System.out.println("Activated: " + win8.activated);
System.out.println("Install Date: " + win8.installDate);
System.out.println("Support Ends: " + win8.supportEnd);
System.out.println("Updates Available: " + win8.updatesAvailable);
System.out.println("Edition: " + win8.edition);
System.out.println("Version: " + win8.version);
System.out.println("Build Number: " + win8.buildNumber);
System.out.println("Architecture: " + win8.architecture);
System.out.println("RAM Requirement: " + win8.ramRequirement + "GB");
System.out.println("Storage Space: " + win8.storageSpace + "GB");
System.out.println("Download Size: " + win8.downloadSize + "GB");
System.out.println("Language: " + win8.language);
System.out.println("Bit Version: " + win8.bitVersion);
System.out.println("Activation Key: " + win8.activationKey);
System.out.println("Home Edition: " + win8.homeEdition);
System.out.println("System Requirements: " + win8.systemRequirements);
System.out.println("CPU Speed: " + win8.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win8.uiTheme);
System.out.println("Cortana Enabled: " + win8.cortanaEnabled);
System.out.println("Max Users: " + win8.maxUsers);
System.out.println("Developer: " + win8.developer);
System.out.println("Release Date: " + win8.releaseDate);
System.out.println("Upgrade Price: " + win8.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN8 INSTANCE INITIALIZED ===");
win8.productId = 8008;
win8.licensePrice = 19999.99;
win8.genuineKey = true;
win8.activated = true;
win8.installDate = "06/03/2026";
win8.supportEnd = "06/03/2027";
win8.updatesAvailable = false;
win8.edition = "Windows 8.1 Pro";
win8.version = "8.1";
win8.buildNumber = "9600.17415";
win8.architecture = "x64";
win8.ramRequirement = 4;
win8.storageSpace = 64;
win8.downloadSize = 2.8;
win8.language = "Marathi";
win8.bitVersion = 64;
win8.activationKey = "EEEEE-EEEEE-EEEEE-EEEEE-EEEEE";
win8.homeEdition = false;
win8.systemRequirements = "Desktop PCs";
win8.cpuSpeed = 1.6;
win8.uiTheme = "Metro UI";
win8.cortanaEnabled = false;
win8.maxUsers = 1;
win8.developer = "Microsoft";
win8.releaseDate = "2013-10-17";
win8.upgradePrice = 29999.99;

System.out.println("Product ID: " + win8.productId);
System.out.println("License Price: " + win8.licensePrice);
System.out.println("Genuine Key: " + win8.genuineKey);
System.out.println("Activated: " + win8.activated);
System.out.println("Install Date: " + win8.installDate);
System.out.println("Support Ends: " + win8.supportEnd);
System.out.println("Updates Available: " + win8.updatesAvailable);
System.out.println("Edition: " + win8.edition);
System.out.println("Version: " + win8.version);
System.out.println("Build Number: " + win8.buildNumber);
System.out.println("Architecture: " + win8.architecture);
System.out.println("RAM Requirement: " + win8.ramRequirement + "GB");
System.out.println("Storage Space: " + win8.storageSpace + "GB");
System.out.println("Download Size: " + win8.downloadSize + "GB");
System.out.println("Language: " + win8.language);
System.out.println("Bit Version: " + win8.bitVersion);
System.out.println("Activation Key: " + win8.activationKey);
System.out.println("Home Edition: " + win8.homeEdition);
System.out.println("System Requirements: " + win8.systemRequirements);
System.out.println("CPU Speed: " + win8.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win8.uiTheme);
System.out.println("Cortana Enabled: " + win8.cortanaEnabled);
System.out.println("Max Users: " + win8.maxUsers);
System.out.println("Developer: " + win8.developer);
System.out.println("Release Date: " + win8.releaseDate);
System.out.println("Upgrade Price: " + win8.upgradePrice);
System.out.println("-----------------------------");




System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win9 = new Windows();

System.out.println("Product ID: " + win9.productId);
System.out.println("License Price: " + win9.licensePrice);
System.out.println("Genuine Key: " + win9.genuineKey);
System.out.println("Activated: " + win9.activated);
System.out.println("Install Date: " + win9.installDate);
System.out.println("Support Ends: " + win9.supportEnd);
System.out.println("Updates Available: " + win9.updatesAvailable);
System.out.println("Edition: " + win9.edition);
System.out.println("Version: " + win9.version);
System.out.println("Build Number: " + win9.buildNumber);
System.out.println("Architecture: " + win9.architecture);
System.out.println("RAM Requirement: " + win9.ramRequirement + "GB");
System.out.println("Storage Space: " + win9.storageSpace + "GB");
System.out.println("Download Size: " + win9.downloadSize + "GB");
System.out.println("Language: " + win9.language);
System.out.println("Bit Version: " + win9.bitVersion);
System.out.println("Activation Key: " + win9.activationKey);
System.out.println("Home Edition: " + win9.homeEdition);
System.out.println("System Requirements: " + win9.systemRequirements);
System.out.println("CPU Speed: " + win9.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win9.uiTheme);
System.out.println("Cortana Enabled: " + win9.cortanaEnabled);
System.out.println("Max Users: " + win9.maxUsers);
System.out.println("Developer: " + win9.developer);
System.out.println("Release Date: " + win9.releaseDate);
System.out.println("Upgrade Price: " + win9.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN9 INSTANCE INITIALIZED ===");
win9.productId = 9009;
win9.licensePrice = 22999.99;
win9.genuineKey = true;
win9.activated = true;
win9.installDate = "06/03/2026";
win9.supportEnd = "06/03/2028";
win9.updatesAvailable = true;
win9.edition = "Windows 9 Pro";
win9.version = "9";
win9.buildNumber = "10240.19041";
win9.architecture = "x64";
win9.ramRequirement = 4;
win9.storageSpace = 80;
win9.downloadSize = 3.2;
win9.language = "Marathi";
win9.bitVersion = 64;
win9.activationKey = "FFFFF-FFFFF-FFFFF-FFFFF-FFFFF";
win9.homeEdition = false;
win9.systemRequirements = "Desktop & Tablets";
win9.cpuSpeed = 1.8;
win9.uiTheme = "Hybrid Metro";
win9.cortanaEnabled = true;
win9.maxUsers = 2;
win9.developer = "Microsoft";
win9.releaseDate = "2014-09-30";
win9.upgradePrice = 31999.99;

System.out.println("Product ID: " + win9.productId);
System.out.println("License Price: " + win9.licensePrice);
System.out.println("Genuine Key: " + win9.genuineKey);
System.out.println("Activated: " + win9.activated);
System.out.println("Install Date: " + win9.installDate);
System.out.println("Support Ends: " + win9.supportEnd);
System.out.println("Updates Available: " + win9.updatesAvailable);
System.out.println("Edition: " + win9.edition);
System.out.println("Version: " + win9.version);
System.out.println("Build Number: " + win9.buildNumber);
System.out.println("Architecture: " + win9.architecture);
System.out.println("RAM Requirement: " + win9.ramRequirement + "GB");
System.out.println("Storage Space: " + win9.storageSpace + "GB");
System.out.println("Download Size: " + win9.downloadSize + "GB");
System.out.println("Language: " + win9.language);
System.out.println("Bit Version: " + win9.bitVersion);
System.out.println("Activation Key: " + win9.activationKey);
System.out.println("Home Edition: " + win9.homeEdition);
System.out.println("System Requirements: " + win9.systemRequirements);
System.out.println("CPU Speed: " + win9.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win9.uiTheme);
System.out.println("Cortana Enabled: " + win9.cortanaEnabled);
System.out.println("Max Users: " + win9.maxUsers);
System.out.println("Developer: " + win9.developer);
System.out.println("Release Date: " + win9.releaseDate);
System.out.println("Upgrade Price: " + win9.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win10 = new Windows();

System.out.println("Product ID: " + win10.productId);
System.out.println("License Price: " + win10.licensePrice);
System.out.println("Genuine Key: " + win10.genuineKey);
System.out.println("Activated: " + win10.activated);
System.out.println("Install Date: " + win10.installDate);
System.out.println("Support Ends: " + win10.supportEnd);
System.out.println("Updates Available: " + win10.updatesAvailable);
System.out.println("Edition: " + win10.edition);
System.out.println("Version: " + win10.version);
System.out.println("Build Number: " + win10.buildNumber);
System.out.println("Architecture: " + win10.architecture);
System.out.println("RAM Requirement: " + win10.ramRequirement + "GB");
System.out.println("Storage Space: " + win10.storageSpace + "GB");
System.out.println("Download Size: " + win10.downloadSize + "GB");
System.out.println("Language: " + win10.language);
System.out.println("Bit Version: " + win10.bitVersion);
System.out.println("Activation Key: " + win10.activationKey);
System.out.println("Home Edition: " + win10.homeEdition);
System.out.println("System Requirements: " + win10.systemRequirements);
System.out.println("CPU Speed: " + win10.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win10.uiTheme);
System.out.println("Cortana Enabled: " + win10.cortanaEnabled);
System.out.println("Max Users: " + win10.maxUsers);
System.out.println("Developer: " + win10.developer);
System.out.println("Release Date: " + win10.releaseDate);
System.out.println("Upgrade Price: " + win10.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN10 INSTANCE INITIALIZED ===");
win10.productId = 1010;
win10.licensePrice = 25999.99;
win10.genuineKey = true;
win10.activated = true;
win10.installDate = "06/03/2026";
win10.supportEnd = "10/14/2025";
win10.updatesAvailable = true;
win10.edition = "Windows 10 Pro";
win10.version = "10";
win10.buildNumber = "19045.5011";
win10.architecture = "x64";
win10.ramRequirement = 4;
win10.storageSpace = 64;
win10.downloadSize = 4.5;
win10.language = "Marathi";
win10.bitVersion = 64;
win10.activationKey = "GGGGG-GGGGG-GGGGG-GGGGG-GGGGG";
win10.homeEdition = false;
win10.systemRequirements = "PCs, Tablets, 2-in-1s";
win10.cpuSpeed = 1.8;
win10.uiTheme = "Fluent Design";
win10.cortanaEnabled = true;
win10.maxUsers = 1;
win10.developer = "Microsoft";
win10.releaseDate = "2015-07-29";
win10.upgradePrice = 39999.99;

System.out.println("Product ID: " + win10.productId);
System.out.println("License Price: " + win10.licensePrice);
System.out.println("Genuine Key: " + win10.genuineKey);
System.out.println("Activated: " + win10.activated);
System.out.println("Install Date: " + win10.installDate);
System.out.println("Support Ends: " + win10.supportEnd);
System.out.println("Updates Available: " + win10.updatesAvailable);
System.out.println("Edition: " + win10.edition);
System.out.println("Version: " + win10.version);
System.out.println("Build Number: " + win10.buildNumber);
System.out.println("Architecture: " + win10.architecture);
System.out.println("RAM Requirement: " + win10.ramRequirement + "GB");
System.out.println("Storage Space: " + win10.storageSpace + "GB");
System.out.println("Download Size: " + win10.downloadSize + "GB");
System.out.println("Language: " + win10.language);
System.out.println("Bit Version: " + win10.bitVersion);
System.out.println("Activation Key: " + win10.activationKey);
System.out.println("Home Edition: " + win10.homeEdition);
System.out.println("System Requirements: " + win10.systemRequirements);
System.out.println("CPU Speed: " + win10.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win10.uiTheme);
System.out.println("Cortana Enabled: " + win10.cortanaEnabled);
System.out.println("Max Users: " + win10.maxUsers);
System.out.println("Developer: " + win10.developer);
System.out.println("Release Date: " + win10.releaseDate);
System.out.println("Upgrade Price: " + win10.upgradePrice);
System.out.println("-----------------------------");


System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win11 = new Windows();

System.out.println("Product ID: " + win11.productId);
System.out.println("License Price: " + win11.licensePrice);
System.out.println("Genuine Key: " + win11.genuineKey);
System.out.println("Activated: " + win11.activated);
System.out.println("Install Date: " + win11.installDate);
System.out.println("Support Ends: " + win11.supportEnd);
System.out.println("Updates Available: " + win11.updatesAvailable);
System.out.println("Edition: " + win11.edition);
System.out.println("Version: " + win11.version);
System.out.println("Build Number: " + win11.buildNumber);
System.out.println("Architecture: " + win11.architecture);
System.out.println("RAM Requirement: " + win11.ramRequirement + "GB");
System.out.println("Storage Space: " + win11.storageSpace + "GB");
System.out.println("Download Size: " + win11.downloadSize + "GB");
System.out.println("Language: " + win11.language);
System.out.println("Bit Version: " + win11.bitVersion);
System.out.println("Activation Key: " + win11.activationKey);
System.out.println("Home Edition: " + win11.homeEdition);
System.out.println("System Requirements: " + win11.systemRequirements);
System.out.println("CPU Speed: " + win11.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win11.uiTheme);
System.out.println("Cortana Enabled: " + win11.cortanaEnabled);
System.out.println("Max Users: " + win11.maxUsers);
System.out.println("Developer: " + win11.developer);
System.out.println("Release Date: " + win11.releaseDate);
System.out.println("Upgrade Price: " + win11.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN11 INSTANCE INITIALIZED ===");
win11.productId = 1111;
win11.licensePrice = 27999.99;
win11.genuineKey = true;
win11.activated = true;
win11.installDate = "06/03/2026";
win11.supportEnd = "10/13/2026";
win11.updatesAvailable = true;
win11.edition = "Windows 11 Pro";
win11.version = "11";
win11.buildNumber = "22631.4564";
win11.architecture = "x64";
win11.ramRequirement = 4;
win11.storageSpace = 64;
win11.downloadSize = 5.2;
win11.language = "Marathi";
win11.bitVersion = 64;
win11.activationKey = "HHHHH-HHHHH-HHHHH-HHHHH-HHHHH";
win11.homeEdition = false;
win11.systemRequirements = "TPM 2.0, Secure Boot, Modern PCs";
win11.cpuSpeed = 2.0;
win11.uiTheme = "Fluent Design 2.0";
win11.cortanaEnabled = false;
win11.maxUsers = 1;
win11.developer = "Microsoft";
win11.releaseDate = "2021-10-05";
win11.upgradePrice = 44999.99;

System.out.println("Product ID: " + win11.productId);
System.out.println("License Price: " + win11.licensePrice);
System.out.println("Genuine Key: " + win11.genuineKey);
System.out.println("Activated: " + win11.activated);
System.out.println("Install Date: " + win11.installDate);
System.out.println("Support Ends: " + win11.supportEnd);
System.out.println("Updates Available: " + win11.updatesAvailable);
System.out.println("Edition: " + win11.edition);
System.out.println("Version: " + win11.version);
System.out.println("Build Number: " + win11.buildNumber);
System.out.println("Architecture: " + win11.architecture);
System.out.println("RAM Requirement: " + win11.ramRequirement + "GB");
System.out.println("Storage Space: " + win11.storageSpace + "GB");
System.out.println("Download Size: " + win11.downloadSize + "GB");
System.out.println("Language: " + win11.language);
System.out.println("Bit Version: " + win11.bitVersion);
System.out.println("Activation Key: " + win11.activationKey);
System.out.println("Home Edition: " + win11.homeEdition);
System.out.println("System Requirements: " + win11.systemRequirements);
System.out.println("CPU Speed: " + win11.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win11.uiTheme);
System.out.println("Cortana Enabled: " + win11.cortanaEnabled);
System.out.println("Max Users: " + win11.maxUsers);
System.out.println("Developer: " + win11.developer);
System.out.println("Release Date: " + win11.releaseDate);
System.out.println("Upgrade Price: " + win11.upgradePrice);
System.out.println("-----------------------------");


System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win12 = new Windows();

System.out.println("Product ID: " + win12.productId);
System.out.println("License Price: " + win12.licensePrice);
System.out.println("Genuine Key: " + win12.genuineKey);
System.out.println("Activated: " + win12.activated);
System.out.println("Install Date: " + win12.installDate);
System.out.println("Support Ends: " + win12.supportEnd);
System.out.println("Updates Available: " + win12.updatesAvailable);
System.out.println("Edition: " + win12.edition);
System.out.println("Version: " + win12.version);
System.out.println("Build Number: " + win12.buildNumber);
System.out.println("Architecture: " + win12.architecture);
System.out.println("RAM Requirement: " + win12.ramRequirement + "GB");
System.out.println("Storage Space: " + win12.storageSpace + "GB");
System.out.println("Download Size: " + win12.downloadSize + "GB");
System.out.println("Language: " + win12.language);
System.out.println("Bit Version: " + win12.bitVersion);
System.out.println("Activation Key: " + win12.activationKey);
System.out.println("Home Edition: " + win12.homeEdition);
System.out.println("System Requirements: " + win12.systemRequirements);
System.out.println("CPU Speed: " + win12.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win12.uiTheme);
System.out.println("Cortana Enabled: " + win12.cortanaEnabled);
System.out.println("Max Users: " + win12.maxUsers);
System.out.println("Developer: " + win12.developer);
System.out.println("Release Date: " + win12.releaseDate);
System.out.println("Upgrade Price: " + win12.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN12 INSTANCE INITIALIZED ===");
win12.productId = 1212;
win12.licensePrice = 29999.99;
win12.genuineKey = true;
win12.activated = true;
win12.installDate = "06/03/2026";
win12.supportEnd = "10/13/2031";
win12.updatesAvailable = true;
win12.edition = "Windows 12 Pro";
win12.version = "12";
win12.buildNumber = "26100.2501";
win12.architecture = "x64";
win12.ramRequirement = 8;
win12.storageSpace = 128;
win12.downloadSize = 6.1;
win12.language = "Marathi";
win12.bitVersion = 64;
win12.activationKey = "IIIII-IIIII-IIIII-IIIII-IIIII";
win12.homeEdition = false;
win12.systemRequirements = "NPU required, TPM 2.0, AI PCs";
win12.cpuSpeed = 3.0;
win12.uiTheme = "AI-First Design";
win12.cortanaEnabled = false;
win12.maxUsers = 1;
win12.developer = "Microsoft";
win12.releaseDate = "2026-10-01";
win12.upgradePrice = 49999.99;

System.out.println("Product ID: " + win12.productId);
System.out.println("License Price: " + win12.licensePrice);
System.out.println("Genuine Key: " + win12.genuineKey);
System.out.println("Activated: " + win12.activated);
System.out.println("Install Date: " + win12.installDate);
System.out.println("Support Ends: " + win12.supportEnd);
System.out.println("Updates Available: " + win12.updatesAvailable);
System.out.println("Edition: " + win12.edition);
System.out.println("Version: " + win12.version);
System.out.println("Build Number: " + win12.buildNumber);
System.out.println("Architecture: " + win12.architecture);
System.out.println("RAM Requirement: " + win12.ramRequirement + "GB");
System.out.println("Storage Space: " + win12.storageSpace + "GB");
System.out.println("Download Size: " + win12.downloadSize + "GB");
System.out.println("Language: " + win12.language);
System.out.println("Bit Version: " + win12.bitVersion);
System.out.println("Activation Key: " + win12.activationKey);
System.out.println("Home Edition: " + win12.homeEdition);
System.out.println("System Requirements: " + win12.systemRequirements);
System.out.println("CPU Speed: " + win12.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win12.uiTheme);
System.out.println("Cortana Enabled: " + win12.cortanaEnabled);
System.out.println("Max Users: " + win12.maxUsers);
System.out.println("Developer: " + win12.developer);
System.out.println("Release Date: " + win12.releaseDate);
System.out.println("Upgrade Price: " + win12.upgradePrice);
System.out.println("-----------------------------");


System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win13 = new Windows();

System.out.println("Product ID: " + win13.productId);
System.out.println("License Price: " + win13.licensePrice);
System.out.println("Genuine Key: " + win13.genuineKey);
System.out.println("Activated: " + win13.activated);
System.out.println("Install Date: " + win13.installDate);
System.out.println("Support Ends: " + win13.supportEnd);
System.out.println("Updates Available: " + win13.updatesAvailable);
System.out.println("Edition: " + win13.edition);
System.out.println("Version: " + win13.version);
System.out.println("Build Number: " + win13.buildNumber);
System.out.println("Architecture: " + win13.architecture);
System.out.println("RAM Requirement: " + win13.ramRequirement + "GB");
System.out.println("Storage Space: " + win13.storageSpace + "GB");
System.out.println("Download Size: " + win13.downloadSize + "GB");
System.out.println("Language: " + win13.language);
System.out.println("Bit Version: " + win13.bitVersion);
System.out.println("Activation Key: " + win13.activationKey);
System.out.println("Home Edition: " + win13.homeEdition);
System.out.println("System Requirements: " + win13.systemRequirements);
System.out.println("CPU Speed: " + win13.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win13.uiTheme);
System.out.println("Cortana Enabled: " + win13.cortanaEnabled);
System.out.println("Max Users: " + win13.maxUsers);
System.out.println("Developer: " + win13.developer);
System.out.println("Release Date: " + win13.releaseDate);
System.out.println("Upgrade Price: " + win13.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN13 INSTANCE INITIALIZED ===");
win13.productId = 1313;
win13.licensePrice = 31999.99;
win13.genuineKey = true;
win13.activated = true;
win13.installDate = "06/03/2026";
win13.supportEnd = "10/13/2032";
win13.updatesAvailable = true;
win13.edition = "Windows 13 Pro";
win13.version = "13";
win13.buildNumber = "27100.3001";
win13.architecture = "x64";
win13.ramRequirement = 16;
win13.storageSpace = 256;
win13.downloadSize = 7.8;
win13.language = "Marathi";
win13.bitVersion = 64;
win13.activationKey = "JJJJJ-JJJJJ-JJJJJ-JJJJJ-JJJJJ";
win13.homeEdition = false;
win13.systemRequirements = "NPU 2.0, 16GB+ RAM, AI Super PCs";
win13.cpuSpeed = 4.0;
win13.uiTheme = "Neural UI";
win13.cortanaEnabled = false;
win13.maxUsers = 1;
win13.developer = "Microsoft";
win13.releaseDate = "2027-10-01";
win13.upgradePrice = 54999.99;

System.out.println("Product ID: " + win13.productId);
System.out.println("License Price: " + win13.licensePrice);
System.out.println("Genuine Key: " + win13.genuineKey);
System.out.println("Activated: " + win13.activated);
System.out.println("Install Date: " + win13.installDate);
System.out.println("Support Ends: " + win13.supportEnd);
System.out.println("Updates Available: " + win13.updatesAvailable);
System.out.println("Edition: " + win13.edition);
System.out.println("Version: " + win13.version);
System.out.println("Build Number: " + win13.buildNumber);
System.out.println("Architecture: " + win13.architecture);
System.out.println("RAM Requirement: " + win13.ramRequirement + "GB");
System.out.println("Storage Space: " + win13.storageSpace + "GB");
System.out.println("Download Size: " + win13.downloadSize + "GB");
System.out.println("Language: " + win13.language);
System.out.println("Bit Version: " + win13.bitVersion);
System.out.println("Activation Key: " + win13.activationKey);
System.out.println("Home Edition: " + win13.homeEdition);
System.out.println("System Requirements: " + win13.systemRequirements);
System.out.println("CPU Speed: " + win13.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win13.uiTheme);
System.out.println("Cortana Enabled: " + win13.cortanaEnabled);
System.out.println("Max Users: " + win13.maxUsers);
System.out.println("Developer: " + win13.developer);
System.out.println("Release Date: " + win13.releaseDate);
System.out.println("Upgrade Price: " + win13.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win14 = new Windows();

System.out.println("Product ID: " + win14.productId);
System.out.println("License Price: " + win14.licensePrice);
System.out.println("Genuine Key: " + win14.genuineKey);
System.out.println("Activated: " + win14.activated);
System.out.println("Install Date: " + win14.installDate);
System.out.println("Support Ends: " + win14.supportEnd);
System.out.println("Updates Available: " + win14.updatesAvailable);
System.out.println("Edition: " + win14.edition);
System.out.println("Version: " + win14.version);
System.out.println("Build Number: " + win14.buildNumber);
System.out.println("Architecture: " + win14.architecture);
System.out.println("RAM Requirement: " + win14.ramRequirement + "GB");
System.out.println("Storage Space: " + win14.storageSpace + "GB");
System.out.println("Download Size: " + win14.downloadSize + "GB");
System.out.println("Language: " + win14.language);
System.out.println("Bit Version: " + win14.bitVersion);
System.out.println("Activation Key: " + win14.activationKey);
System.out.println("Home Edition: " + win14.homeEdition);
System.out.println("System Requirements: " + win14.systemRequirements);
System.out.println("CPU Speed: " + win14.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win14.uiTheme);
System.out.println("Cortana Enabled: " + win14.cortanaEnabled);
System.out.println("Max Users: " + win14.maxUsers);
System.out.println("Developer: " + win14.developer);
System.out.println("Release Date: " + win14.releaseDate);
System.out.println("Upgrade Price: " + win14.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN14 INSTANCE INITIALIZED ===");
win14.productId = 1414;
win14.licensePrice = 42999.99;
win14.genuineKey = true;
win14.activated = false;
win14.installDate = "10/03/2026";
win14.supportEnd = "12/31/2033";
win14.updatesAvailable = true;
win14.edition = "Windows 14 Pro";
win14.version = "14";
win14.buildNumber = "30000.1000";
win14.architecture = "x64";
win14.ramRequirement = 24;
win14.storageSpace = 512;
win14.downloadSize = 9.5;
win14.language = "English (India)";
win14.bitVersion = 64;
win14.activationKey = "KKKKK-KKKKK-KKKKK-KKKKK-KKKKK";
win14.homeEdition = false;
win14.systemRequirements = "NPU 3.0, 24GB+ RAM, AI Ultra PCs";
win14.cpuSpeed = 4.5;
win14.uiTheme = "Neural UI 2.0";
win14.cortanaEnabled = false;
win14.maxUsers = 5;
win14.developer = "Microsoft";
win14.releaseDate = "2028-10-01";
win14.upgradePrice = 64999.99;

System.out.println("Product ID: " + win14.productId);
System.out.println("License Price: " + win14.licensePrice);
System.out.println("Genuine Key: " + win14.genuineKey);
System.out.println("Activated: " + win14.activated);
System.out.println("Install Date: " + win14.installDate);
System.out.println("Support Ends: " + win14.supportEnd);
System.out.println("Updates Available: " + win14.updatesAvailable);
System.out.println("Edition: " + win14.edition);
System.out.println("Version: " + win14.version);
System.out.println("Build Number: " + win14.buildNumber);
System.out.println("Architecture: " + win14.architecture);
System.out.println("RAM Requirement: " + win14.ramRequirement + "GB");
System.out.println("Storage Space: " + win14.storageSpace + "GB");
System.out.println("Download Size: " + win14.downloadSize + "GB");
System.out.println("Language: " + win14.language);
System.out.println("Bit Version: " + win14.bitVersion);
System.out.println("Activation Key: " + win14.activationKey);
System.out.println("Home Edition: " + win14.homeEdition);
System.out.println("System Requirements: " + win14.systemRequirements);
System.out.println("CPU Speed: " + win14.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win14.uiTheme);
System.out.println("Cortana Enabled: " + win14.cortanaEnabled);
System.out.println("Max Users: " + win14.maxUsers);
System.out.println("Developer: " + win14.developer);
System.out.println("Release Date: " + win14.releaseDate);
System.out.println("Upgrade Price: " + win14.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win15 = new Windows();

System.out.println("Product ID: " + win15.productId);
System.out.println("License Price: " + win15.licensePrice);
System.out.println("Genuine Key: " + win15.genuineKey);
System.out.println("Activated: " + win15.activated);
System.out.println("Install Date: " + win15.installDate);
System.out.println("Support Ends: " + win15.supportEnd);
System.out.println("Updates Available: " + win15.updatesAvailable);
System.out.println("Edition: " + win15.edition);
System.out.println("Version: " + win15.version);
System.out.println("Build Number: " + win15.buildNumber);
System.out.println("Architecture: " + win15.architecture);
System.out.println("RAM Requirement: " + win15.ramRequirement + "GB");
System.out.println("Storage Space: " + win15.storageSpace + "GB");
System.out.println("Download Size: " + win15.downloadSize + "GB");
System.out.println("Language: " + win15.language);
System.out.println("Bit Version: " + win15.bitVersion);
System.out.println("Activation Key: " + win15.activationKey);
System.out.println("Home Edition: " + win15.homeEdition);
System.out.println("System Requirements: " + win15.systemRequirements);
System.out.println("CPU Speed: " + win15.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win15.uiTheme);
System.out.println("Cortana Enabled: " + win15.cortanaEnabled);
System.out.println("Max Users: " + win15.maxUsers);
System.out.println("Developer: " + win15.developer);
System.out.println("Release Date: " + win15.releaseDate);
System.out.println("Upgrade Price: " + win15.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN15 INSTANCE INITIALIZED ===");
win15.productId = 1515;
win15.licensePrice = 59999.99;
win15.genuineKey = true;
win15.activated = true;
win15.installDate = "03/15/2026";
win15.supportEnd = "10/15/2035";
win15.updatesAvailable = true;
win15.edition = "Windows 15 Enterprise";
win15.version = "15";
win15.buildNumber = "35000.5001";
win15.architecture = "x64";
win15.ramRequirement = 32;
win15.storageSpace = 1024;
win15.downloadSize = 12.2;
win15.language = "Hindi";
win15.bitVersion = 64;
win15.activationKey = "MMMMM-MMMMM-MMMMM-MMMMM-MMMMM";
win15.homeEdition = false;
win15.systemRequirements = "NPU 4.0, 32GB+ RAM, Quantum AI PCs";
win15.cpuSpeed = 5.0;
win15.uiTheme = "Holographic Neural UI";
win15.cortanaEnabled = true;
win15.maxUsers = 10;
win15.developer = "Microsoft";
win15.releaseDate = "2029-10-01";
win15.upgradePrice = 89999.99;

System.out.println("Product ID: " + win15.productId);
System.out.println("License Price: " + win15.licensePrice);
System.out.println("Genuine Key: " + win15.genuineKey);
System.out.println("Activated: " + win15.activated);
System.out.println("Install Date: " + win15.installDate);
System.out.println("Support Ends: " + win15.supportEnd);
System.out.println("Updates Available: " + win15.updatesAvailable);
System.out.println("Edition: " + win15.edition);
System.out.println("Version: " + win15.version);
System.out.println("Build Number: " + win15.buildNumber);
System.out.println("Architecture: " + win15.architecture);
System.out.println("RAM Requirement: " + win15.ramRequirement + "GB");
System.out.println("Storage Space: " + win15.storageSpace + "GB");
System.out.println("Download Size: " + win15.downloadSize + "GB");
System.out.println("Language: " + win15.language);
System.out.println("Bit Version: " + win15.bitVersion);
System.out.println("Activation Key: " + win15.activationKey);
System.out.println("Home Edition: " + win15.homeEdition);
System.out.println("System Requirements: " + win15.systemRequirements);
System.out.println("CPU Speed: " + win15.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win15.uiTheme);
System.out.println("Cortana Enabled: " + win15.cortanaEnabled);
System.out.println("Max Users: " + win15.maxUsers);
System.out.println("Developer: " + win15.developer);
System.out.println("Release Date: " + win15.releaseDate);
System.out.println("Upgrade Price: " + win15.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win16 = new Windows();

System.out.println("Product ID: " + win16.productId);
System.out.println("License Price: " + win16.licensePrice);
System.out.println("Genuine Key: " + win16.genuineKey);
System.out.println("Activated: " + win16.activated);
System.out.println("Install Date: " + win16.installDate);
System.out.println("Support Ends: " + win16.supportEnd);
System.out.println("Updates Available: " + win16.updatesAvailable);
System.out.println("Edition: " + win16.edition);
System.out.println("Version: " + win16.version);
System.out.println("Build Number: " + win16.buildNumber);
System.out.println("Architecture: " + win16.architecture);
System.out.println("RAM Requirement: " + win16.ramRequirement + "GB");
System.out.println("Storage Space: " + win16.storageSpace + "GB");
System.out.println("Download Size: " + win16.downloadSize + "GB");
System.out.println("Language: " + win16.language);
System.out.println("Bit Version: " + win16.bitVersion);
System.out.println("Activation Key: " + win16.activationKey);
System.out.println("Home Edition: " + win16.homeEdition);
System.out.println("System Requirements: " + win16.systemRequirements);
System.out.println("CPU Speed: " + win16.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win16.uiTheme);
System.out.println("Cortana Enabled: " + win16.cortanaEnabled);
System.out.println("Max Users: " + win16.maxUsers);
System.out.println("Developer: " + win16.developer);
System.out.println("Release Date: " + win16.releaseDate);
System.out.println("Upgrade Price: " + win16.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN16 INSTANCE INITIALIZED ===");
win16.productId = 1616;
win16.licensePrice = 79999.99;
win16.genuineKey = true;
win16.activated = true;
win16.installDate = "06/01/2026";
win16.supportEnd = "12/31/2038";
win16.updatesAvailable = true;
win16.edition = "Windows 16 Ultimate";
win16.version = "16";
win16.buildNumber = "42000.1001";
win16.architecture = "x64";
win16.ramRequirement = 64;
win16.storageSpace = 2048;
win16.downloadSize = 15.8;
win16.language = "Kannada";
win16.bitVersion = 64;
win16.activationKey = "NNNNN-NNNNN-NNNNN-NNNNN-NNNNN";
win16.homeEdition = false;
win16.systemRequirements = "NPU 5.0, 64GB+ RAM, Quantum Core PCs";
win16.cpuSpeed = 6.0;
win16.uiTheme = "Quantum Holographic UI";
win16.cortanaEnabled = true;
win16.maxUsers = 25;
win16.developer = "Microsoft";
win16.releaseDate = "2030-10-01";
win16.upgradePrice = 119999.99;

System.out.println("Product ID: " + win16.productId);
System.out.println("License Price: " + win16.licensePrice);
System.out.println("Genuine Key: " + win16.genuineKey);
System.out.println("Activated: " + win16.activated);
System.out.println("Install Date: " + win16.installDate);
System.out.println("Support Ends: " + win16.supportEnd);
System.out.println("Updates Available: " + win16.updatesAvailable);
System.out.println("Edition: " + win16.edition);
System.out.println("Version: " + win16.version);
System.out.println("Build Number: " + win16.buildNumber);
System.out.println("Architecture: " + win16.architecture);
System.out.println("RAM Requirement: " + win16.ramRequirement + "GB");
System.out.println("Storage Space: " + win16.storageSpace + "GB");
System.out.println("Download Size: " + win16.downloadSize + "GB");
System.out.println("Language: " + win16.language);
System.out.println("Bit Version: " + win16.bitVersion);
System.out.println("Activation Key: " + win16.activationKey);
System.out.println("Home Edition: " + win16.homeEdition);
System.out.println("System Requirements: " + win16.systemRequirements);
System.out.println("CPU Speed: " + win16.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win16.uiTheme);
System.out.println("Cortana Enabled: " + win16.cortanaEnabled);
System.out.println("Max Users: " + win16.maxUsers);
System.out.println("Developer: " + win16.developer);
System.out.println("Release Date: " + win16.releaseDate);
System.out.println("Upgrade Price: " + win16.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win17 = new Windows();

System.out.println("Product ID: " + win17.productId);
System.out.println("License Price: " + win17.licensePrice);
System.out.println("Genuine Key: " + win17.genuineKey);
System.out.println("Activated: " + win17.activated);
System.out.println("Install Date: " + win17.installDate);
System.out.println("Support Ends: " + win17.supportEnd);
System.out.println("Updates Available: " + win17.updatesAvailable);
System.out.println("Edition: " + win17.edition);
System.out.println("Version: " + win17.version);
System.out.println("Build Number: " + win17.buildNumber);
System.out.println("Architecture: " + win17.architecture);
System.out.println("RAM Requirement: " + win17.ramRequirement + "GB");
System.out.println("Storage Space: " + win17.storageSpace + "GB");
System.out.println("Download Size: " + win17.downloadSize + "GB");
System.out.println("Language: " + win17.language);
System.out.println("Bit Version: " + win17.bitVersion);
System.out.println("Activation Key: " + win17.activationKey);
System.out.println("Home Edition: " + win17.homeEdition);
System.out.println("System Requirements: " + win17.systemRequirements);
System.out.println("CPU Speed: " + win17.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win17.uiTheme);
System.out.println("Cortana Enabled: " + win17.cortanaEnabled);
System.out.println("Max Users: " + win17.maxUsers);
System.out.println("Developer: " + win17.developer);
System.out.println("Release Date: " + win17.releaseDate);
System.out.println("Upgrade Price: " + win17.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN17 INSTANCE INITIALIZED ===");
win17.productId = 1717;
win17.licensePrice = 99999.99;
win17.genuineKey = true;
win17.activated = true;
win17.installDate = "09/01/2026";
win17.supportEnd = "12/31/2042";
win17.updatesAvailable = true;
win17.edition = "Windows 17 Quantum Edition";
win17.version = "17";
win17.buildNumber = "50000.2001";
win17.architecture = "x64";
win17.ramRequirement = 128;
win17.storageSpace = 4096;
win17.downloadSize = 22.5;
win17.language = "Tamil";
win17.bitVersion = 64;
win17.activationKey = "OOOOO-OOOOO-OOOOO-OOOOO-OOOOO";
win17.homeEdition = false;
win17.systemRequirements = "NPU 6.0, 128GB+ RAM, Quantum Fusion PCs";
win17.cpuSpeed = 8.0;
win17.uiTheme = "Quantum Fusion UI";
win17.cortanaEnabled = true;
win17.maxUsers = 50;
win17.developer = "Microsoft";
win17.releaseDate = "2031-10-01";
win17.upgradePrice = 149999.99;

System.out.println("Product ID: " + win17.productId);
System.out.println("License Price: " + win17.licensePrice);
System.out.println("Genuine Key: " + win17.genuineKey);
System.out.println("Activated: " + win17.activated);
System.out.println("Install Date: " + win17.installDate);
System.out.println("Support Ends: " + win17.supportEnd);
System.out.println("Updates Available: " + win17.updatesAvailable);
System.out.println("Edition: " + win17.edition);
System.out.println("Version: " + win17.version);
System.out.println("Build Number: " + win17.buildNumber);
System.out.println("Architecture: " + win17.architecture);
System.out.println("RAM Requirement: " + win17.ramRequirement + "GB");
System.out.println("Storage Space: " + win17.storageSpace + "GB");
System.out.println("Download Size: " + win17.downloadSize + "GB");
System.out.println("Language: " + win17.language);
System.out.println("Bit Version: " + win17.bitVersion);
System.out.println("Activation Key: " + win17.activationKey);
System.out.println("Home Edition: " + win17.homeEdition);
System.out.println("System Requirements: " + win17.systemRequirements);
System.out.println("CPU Speed: " + win17.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win17.uiTheme);
System.out.println("Cortana Enabled: " + win17.cortanaEnabled);
System.out.println("Max Users: " + win17.maxUsers);
System.out.println("Developer: " + win17.developer);
System.out.println("Release Date: " + win17.releaseDate);
System.out.println("Upgrade Price: " + win17.upgradePrice);
System.out.println("-----------------------------");


System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win18 = new Windows();

System.out.println("Product ID: " + win18.productId);
System.out.println("License Price: " + win18.licensePrice);
System.out.println("Genuine Key: " + win18.genuineKey);
System.out.println("Activated: " + win18.activated);
System.out.println("Install Date: " + win18.installDate);
System.out.println("Support Ends: " + win18.supportEnd);
System.out.println("Updates Available: " + win18.updatesAvailable);
System.out.println("Edition: " + win18.edition);
System.out.println("Version: " + win18.version);
System.out.println("Build Number: " + win18.buildNumber);
System.out.println("Architecture: " + win18.architecture);
System.out.println("RAM Requirement: " + win18.ramRequirement + "GB");
System.out.println("Storage Space: " + win18.storageSpace + "GB");
System.out.println("Download Size: " + win18.downloadSize + "GB");
System.out.println("Language: " + win18.language);
System.out.println("Bit Version: " + win18.bitVersion);
System.out.println("Activation Key: " + win18.activationKey);
System.out.println("Home Edition: " + win18.homeEdition);
System.out.println("System Requirements: " + win18.systemRequirements);
System.out.println("CPU Speed: " + win18.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win18.uiTheme);
System.out.println("Cortana Enabled: " + win18.cortanaEnabled);
System.out.println("Max Users: " + win18.maxUsers);
System.out.println("Developer: " + win18.developer);
System.out.println("Release Date: " + win18.releaseDate);
System.out.println("Upgrade Price: " + win18.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN18 INSTANCE INITIALIZED ===");
win18.productId = 1818;
win18.licensePrice = 129999.99;
win18.genuineKey = true;
win18.activated = true;
win18.installDate = "12/01/2026";
win18.supportEnd = "12/31/2048";
win18.updatesAvailable = true;
win18.edition = "Windows 18 Singularity Edition";
win18.version = "18";
win18.buildNumber = "60000.3001";
win18.architecture = "x64";
win18.ramRequirement = 256;
win18.storageSpace = 8192;
win18.downloadSize = 32.1;
win18.language = "Telugu";
win18.bitVersion = 64;
win18.activationKey = "PPPPP-PPPPP-PPPPP-PPPPP-PPPPP";
win18.homeEdition = false;
win18.systemRequirements = "NPU 8.0, 256GB+ RAM, Singularity Quantum PCs";
win18.cpuSpeed = 12.0;
win18.uiTheme = "Singularity Omni UI";
win18.cortanaEnabled = true;
win18.maxUsers = 100;
win18.developer = "Microsoft";
win18.releaseDate = "2032-10-01";
win18.upgradePrice = 199999.99;

System.out.println("Product ID: " + win18.productId);
System.out.println("License Price: " + win18.licensePrice);
System.out.println("Genuine Key: " + win18.genuineKey);
System.out.println("Activated: " + win18.activated);
System.out.println("Install Date: " + win18.installDate);
System.out.println("Support Ends: " + win18.supportEnd);
System.out.println("Updates Available: " + win18.updatesAvailable);
System.out.println("Edition: " + win18.edition);
System.out.println("Version: " + win18.version);
System.out.println("Build Number: " + win18.buildNumber);
System.out.println("Architecture: " + win18.architecture);
System.out.println("RAM Requirement: " + win18.ramRequirement + "GB");
System.out.println("Storage Space: " + win18.storageSpace + "GB");
System.out.println("Download Size: " + win18.downloadSize + "GB");
System.out.println("Language: " + win18.language);
System.out.println("Bit Version: " + win18.bitVersion);
System.out.println("Activation Key: " + win18.activationKey);
System.out.println("Home Edition: " + win18.homeEdition);
System.out.println("System Requirements: " + win18.systemRequirements);
System.out.println("CPU Speed: " + win18.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win18.uiTheme);
System.out.println("Cortana Enabled: " + win18.cortanaEnabled);
System.out.println("Max Users: " + win18.maxUsers);
System.out.println("Developer: " + win18.developer);
System.out.println("Release Date: " + win18.releaseDate);
System.out.println("Upgrade Price: " + win18.upgradePrice);
System.out.println("-----------------------------");



System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win19 = new Windows();

System.out.println("Product ID: " + win19.productId);
System.out.println("License Price: " + win19.licensePrice);
System.out.println("Genuine Key: " + win19.genuineKey);
System.out.println("Activated: " + win19.activated);
System.out.println("Install Date: " + win19.installDate);
System.out.println("Support Ends: " + win19.supportEnd);
System.out.println("Updates Available: " + win19.updatesAvailable);
System.out.println("Edition: " + win19.edition);
System.out.println("Version: " + win19.version);
System.out.println("Build Number: " + win19.buildNumber);
System.out.println("Architecture: " + win19.architecture);
System.out.println("RAM Requirement: " + win19.ramRequirement + "GB");
System.out.println("Storage Space: " + win19.storageSpace + "GB");
System.out.println("Download Size: " + win19.downloadSize + "GB");
System.out.println("Language: " + win19.language);
System.out.println("Bit Version: " + win19.bitVersion);
System.out.println("Activation Key: " + win19.activationKey);
System.out.println("Home Edition: " + win19.homeEdition);
System.out.println("System Requirements: " + win19.systemRequirements);
System.out.println("CPU Speed: " + win19.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win19.uiTheme);
System.out.println("Cortana Enabled: " + win19.cortanaEnabled);
System.out.println("Max Users: " + win19.maxUsers);
System.out.println("Developer: " + win19.developer);
System.out.println("Release Date: " + win19.releaseDate);
System.out.println("Upgrade Price: " + win19.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN19 INSTANCE INITIALIZED ===");
win19.productId = 1919;
win19.licensePrice = 179999.99;
win19.genuineKey = true;
win19.activated = true;
win19.installDate = "03/01/2027";
win19.supportEnd = "12/31/2055";
win19.updatesAvailable = true;
win19.edition = "Windows 19 Cosmic Edition";
win19.version = "19";
win19.buildNumber = "75000.4001";
win19.architecture = "x64";
win19.ramRequirement = 512;
win19.storageSpace = 16384;
win19.downloadSize = 48.7;
win19.language = "Malayalam";
win19.bitVersion = 64;
win19.activationKey = "QQQQQ-QQQQQ-QQQQQ-QQQQQ-QQQQQ";
win19.homeEdition = false;
win19.systemRequirements = "NPU 12.0, 512GB+ RAM, Cosmic Fusion PCs";
win19.cpuSpeed = 16.0;
win19.uiTheme = "Cosmic Omni UI";
win19.cortanaEnabled = true;
win19.maxUsers = 250;
win19.developer = "Microsoft";
win19.releaseDate = "2033-10-01";
win19.upgradePrice = 299999.99;

System.out.println("Product ID: " + win19.productId);
System.out.println("License Price: " + win19.licensePrice);
System.out.println("Genuine Key: " + win19.genuineKey);
System.out.println("Activated: " + win19.activated);
System.out.println("Install Date: " + win19.installDate);
System.out.println("Support Ends: " + win19.supportEnd);
System.out.println("Updates Available: " + win19.updatesAvailable);
System.out.println("Edition: " + win19.edition);
System.out.println("Version: " + win19.version);
System.out.println("Build Number: " + win19.buildNumber);
System.out.println("Architecture: " + win19.architecture);
System.out.println("RAM Requirement: " + win19.ramRequirement + "GB");
System.out.println("Storage Space: " + win19.storageSpace + "GB");
System.out.println("Download Size: " + win19.downloadSize + "GB");
System.out.println("Language: " + win19.language);
System.out.println("Bit Version: " + win19.bitVersion);
System.out.println("Activation Key: " + win19.activationKey);
System.out.println("Home Edition: " + win19.homeEdition);
System.out.println("System Requirements: " + win19.systemRequirements);
System.out.println("CPU Speed: " + win19.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win19.uiTheme);
System.out.println("Cortana Enabled: " + win19.cortanaEnabled);
System.out.println("Max Users: " + win19.maxUsers);
System.out.println("Developer: " + win19.developer);
System.out.println("Release Date: " + win19.releaseDate);
System.out.println("Upgrade Price: " + win19.upgradePrice);
System.out.println("-----------------------------");


System.out.println(" BEFORE INSTANCE INITIALIZATION ");
Windows win20 = new Windows();

System.out.println("Product ID: " + win20.productId);
System.out.println("License Price: " + win20.licensePrice);
System.out.println("Genuine Key: " + win20.genuineKey);
System.out.println("Activated: " + win20.activated);
System.out.println("Install Date: " + win20.installDate);
System.out.println("Support Ends: " + win20.supportEnd);
System.out.println("Updates Available: " + win20.updatesAvailable);
System.out.println("Edition: " + win20.edition);
System.out.println("Version: " + win20.version);
System.out.println("Build Number: " + win20.buildNumber);
System.out.println("Architecture: " + win20.architecture);
System.out.println("RAM Requirement: " + win20.ramRequirement + "GB");
System.out.println("Storage Space: " + win20.storageSpace + "GB");
System.out.println("Download Size: " + win20.downloadSize + "GB");
System.out.println("Language: " + win20.language);
System.out.println("Bit Version: " + win20.bitVersion);
System.out.println("Activation Key: " + win20.activationKey);
System.out.println("Home Edition: " + win20.homeEdition);
System.out.println("System Requirements: " + win20.systemRequirements);
System.out.println("CPU Speed: " + win20.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win20.uiTheme);
System.out.println("Cortana Enabled: " + win20.cortanaEnabled);
System.out.println("Max Users: " + win20.maxUsers);
System.out.println("Developer: " + win20.developer);
System.out.println("Release Date: " + win20.releaseDate);
System.out.println("Upgrade Price: " + win20.upgradePrice);
System.out.println("-----------------------------");

System.out.println("=== AFTER WIN20 INSTANCE INITIALIZED ===");
win20.productId = 2020;
win20.licensePrice = 249999.99;
win20.genuineKey = true;
win20.activated = true;
win20.installDate = "06/01/2027";
win20.supportEnd = "12/31/2065";
win20.updatesAvailable = true;
win20.edition = "Windows 20 Universal Edition";
win20.version = "20";
win20.buildNumber = "100000.5001";
win20.architecture = "x64";
win20.ramRequirement = 1024;
win20.storageSpace = 32768;
win20.downloadSize = 75.3;
win20.language = "Gujarati";
win20.bitVersion = 64;
win20.activationKey = "RRRRR-RRRRR-RRRRR-RRRRR-RRRRR";
win20.homeEdition = false;
win20.systemRequirements = "NPU 16.0, 1TB+ RAM, Universal Quantum PCs";
win20.cpuSpeed = 24.0;
win20.uiTheme = "Universal Omni UI";
win20.cortanaEnabled = true;
win20.maxUsers = 1000;
win20.developer = "Microsoft";
win20.releaseDate = "2034-10-01";
win20.upgradePrice = 499999.99;

System.out.println("Product ID: " + win20.productId);
System.out.println("License Price: " + win20.licensePrice);
System.out.println("Genuine Key: " + win20.genuineKey);
System.out.println("Activated: " + win20.activated);
System.out.println("Install Date: " + win20.installDate);
System.out.println("Support Ends: " + win20.supportEnd);
System.out.println("Updates Available: " + win20.updatesAvailable);
System.out.println("Edition: " + win20.edition);
System.out.println("Version: " + win20.version);
System.out.println("Build Number: " + win20.buildNumber);
System.out.println("Architecture: " + win20.architecture);
System.out.println("RAM Requirement: " + win20.ramRequirement + "GB");
System.out.println("Storage Space: " + win20.storageSpace + "GB");
System.out.println("Download Size: " + win20.downloadSize + "GB");
System.out.println("Language: " + win20.language);
System.out.println("Bit Version: " + win20.bitVersion);
System.out.println("Activation Key: " + win20.activationKey);
System.out.println("Home Edition: " + win20.homeEdition);
System.out.println("System Requirements: " + win20.systemRequirements);
System.out.println("CPU Speed: " + win20.cpuSpeed + "GHz");
System.out.println("UI Theme: " + win20.uiTheme);
System.out.println("Cortana Enabled: " + win20.cortanaEnabled);
System.out.println("Max Users: " + win20.maxUsers);
System.out.println("Developer: " + win20.developer);
System.out.println("Release Date: " + win20.releaseDate);
System.out.println("Upgrade Price: " + win20.upgradePrice);
System.out.println("-----------------------------");


    }
}
